Dash Core: src/rpc/blockchain.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
blockchain.cpp File Reference
#include "amount.h"
#include "chain.h"
#include "chainparams.h"
#include "checkpoints.h"
#include "coins.h"
#include "core_io.h"
#include "consensus/validation.h"
#include "instantx.h"
#include "validation.h"
#include "policy/policy.h"
#include "primitives/transaction.h"
#include "rpc/server.h"
#include "streams.h"
#include "sync.h"
#include "txdb.h"
#include "txmempool.h"
#include "util.h"
#include "utilstrencodings.h"
#include "hash.h"
#include "evo/specialtx.h"
#include "evo/cbtx.h"
#include <stdint.h>
#include <univalue.h>
#include <boost/thread/thread.hpp>
#include <mutex>
#include <condition_variable>
Classes
struct CUpdatedBlock
struct CCoinsStats
struct CompareBlocksByHeight
Comparison function for sorting the getchaintips heads.
Functions
void TxToJSON (const CTransaction &tx, const uint256 hashBlock, UniValue &entry)
void ScriptPubKeyToJSON (const CScript &scriptPubKey, UniValue &out, bool fIncludeHex)
double GetDifficulty (const CBlockIndex *blockindex)
UniValue blockheaderToJSON (const CBlockIndex *blockindex)
UniValue blockToJSON (const CBlock &block, const CBlockIndex *blockindex, bool txDetails=false)
UniValue getblockcount (const JSONRPCRequest &request)
UniValue getbestblockhash (const JSONRPCRequest &request)
void RPCNotifyBlockChange (bool ibd, const CBlockIndex *pindex)
UniValue waitfornewblock (const JSONRPCRequest &request)
UniValue waitforblock (const JSONRPCRequest &request)
UniValue waitforblockheight (const JSONRPCRequest &request)
UniValue getdifficulty (const JSONRPCRequest &request)
std::string EntryDescriptionString ()
void entryToJSON (UniValue &info, const CTxMemPoolEntry &e)
UniValue mempoolToJSON (bool fVerbose=false)
UniValue getrawmempool (const JSONRPCRequest &request)
UniValue getmempoolancestors (const JSONRPCRequest &request)
UniValue getmempooldescendants (const JSONRPCRequest &request)
UniValue getmempoolentry (const JSONRPCRequest &request)
UniValue getblockhashes (const JSONRPCRequest &request)
UniValue getblockhash (const JSONRPCRequest &request)
UniValue getblockheader (const JSONRPCRequest &request)
UniValue getblockheaders (const JSONRPCRequest &request)
UniValue getblock (const JSONRPCRequest &request)
static void ApplyStats (CCoinsStats &stats, CHashWriter &ss, const uint256 &hash, const std::map< uint32_t, Coin > &outputs)
static bool GetUTXOStats (CCoinsView *view, CCoinsStats &stats)
Calculate statistics about the unspent transaction output set.
UniValue pruneblockchain (const JSONRPCRequest &request)
UniValue gettxoutsetinfo (const JSONRPCRequest &request)
UniValue gettxout (const JSONRPCRequest &request)
UniValue verifychain (const JSONRPCRequest &request)
static UniValue SoftForkMajorityDesc (int version, CBlockIndex *pindex, const Consensus::Params &consensusParams)
Implementation of IsSuperMajority with better feedback.
static UniValue SoftForkDesc (const std::string &name, int version, CBlockIndex *pindex, const Consensus::Params &consensusParams)
static UniValue BIP9SoftForkDesc (const Consensus::Params &consensusParams, Consensus::DeploymentPos id)
void BIP9SoftForkDescPushBack (UniValue &bip9_softforks, const std::string &name, const Consensus::Params &consensusParams, Consensus::DeploymentPos id)
UniValue getblockchaininfo (const JSONRPCRequest &request)
UniValue getchaintips (const JSONRPCRequest &request)
UniValue mempoolInfoToJSON ()
UniValue getmempoolinfo (const JSONRPCRequest &request)
UniValue preciousblock (const JSONRPCRequest &request)
UniValue invalidateblock (const JSONRPCRequest &request)
UniValue reconsiderblock (const JSONRPCRequest &request)
UniValue getspecialtxes (const JSONRPCRequest &request)
void RegisterBlockchainRPCCommands (CRPCTable &t)
Register block chain RPC commands.
Variables
static std::mutex cs_blockchange
static std::condition_variable cond_blockchange
static CUpdatedBlock latestblock
static const CRPCCommand commands []
Function Documentation
ApplyStats()
static void ApplyStats (CCoinsStats & stats, CHashWriter & ss, const uint256 & hash, const std::map< uint32_t, Coin > & outputs) static
Definition at line 927 of file blockchain.cpp.
References CCoinsStats::nTotalAmount, CCoinsStats::nTransactionOutputs, CCoinsStats::nTransactions, and VARINT.
Referenced by GetUTXOStats().
BIP9SoftForkDesc()
static UniValue BIP9SoftForkDesc (const Consensus::Params & consensusParams, Consensus::DeploymentPos id) static
Definition at line 1208 of file blockchain.cpp.
References Consensus::BIP9Deployment::bit, chainActive, CChain::Height(), Consensus::Params::nMinerConfirmationWindow, Consensus::Params::nRuleChangeActivationThreshold, Consensus::BIP9Deployment::nStartTime, Consensus::BIP9Deployment::nThreshold, Consensus::BIP9Deployment::nTimeout, Consensus::BIP9Deployment::nWindowSize, Pair(), UniValue::push_back(), THRESHOLD_ACTIVE, THRESHOLD_DEFINED, THRESHOLD_FAILED, THRESHOLD_LOCKED_IN, THRESHOLD_STARTED, CChain::Tip(), Consensus::Params::vDeployments, VersionBitsCountBlocksInWindow(), VersionBitsTipState(), VersionBitsTipStateSinceHeight(), and UniValue::VOBJ.
Referenced by BIP9SoftForkDescPushBack().
BIP9SoftForkDescPushBack()
void BIP9SoftForkDescPushBack (UniValue & bip9_softforks, const std::string & name, const Consensus::Params & consensusParams, Consensus::DeploymentPos id)
Definition at line 1239 of file blockchain.cpp.
References BIP9SoftForkDesc(), name, Consensus::BIP9Deployment::nTimeout, Pair(), UniValue::push_back(), and Consensus::Params::vDeployments.
Referenced by getblockchaininfo().
blockheaderToJSON()
UniValue blockheaderToJSON (const CBlockIndex * blockindex)
Definition at line 83 of file blockchain.cpp.
References chainActive, CChain::Contains(), CBlockIndex::GetBlockHash(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), CBlockIndex::hashMerkleRoot, CChain::Height(), CBlockIndex::nBits, CBlockIndex::nChainWork, CChain::Next(), CBlockIndex::nHeight, CBlockIndex::nNonce, CBlockIndex::nTime, CBlockIndex::nVersion, Pair(), CBlockIndex::pprev, UniValue::push_back(), strprintf, and UniValue::VOBJ.
Referenced by getblockheader(), getblockheaders(), and rest_headers().
blockToJSON()
UniValue blockToJSON (const CBlock & block, const CBlockIndex * blockindex, bool txDetails = false)
Definition at line 111 of file blockchain.cpp.
References chainActive, CChain::Contains(), CBlockIndex::GetBlockHash(), CBlockHeader::GetBlockTime(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), GetSerializeSize(), GetTxPayload(), CBlockHeader::hashMerkleRoot, CChain::Height(), CBlockHeader::nBits, CBlockIndex::nChainWork, CChain::Next(), CBlockIndex::nHeight, CBlockHeader::nNonce, CBlockHeader::nVersion, Pair(), CBlockIndex::pprev, PROTOCOL_VERSION, UniValue::push_back(), SER_NETWORK, strprintf, CCbTx::ToJson(), TxToJSON(), UniValue::VARR, UniValue::VOBJ, and CBlock::vtx.
Referenced by getblock(), and rest_block().
EntryDescriptionString()
std::string EntryDescriptionString ()
Definition at line 344 of file blockchain.cpp.
References CURRENCY_UNIT.
Referenced by getmempoolancestors(), getmempooldescendants(), getmempoolentry(), and getrawmempool().
entryToJSON()
void entryToJSON (UniValue & info, const CTxMemPoolEntry & e)
Definition at line 366 of file blockchain.cpp.
References AssertLockHeld, chainActive, CTxMemPool::cs, CTxMemPool::exists(), CTxMemPoolEntry::GetCountWithAncestors(), CTxMemPoolEntry::GetCountWithDescendants(), CTxMemPoolEntry::GetFee(), CTransaction::GetHash(), CTxMemPoolEntry::GetHeight(), CTxMemPoolEntry::GetModFeesWithAncestors(), CTxMemPoolEntry::GetModFeesWithDescendants(), CTxMemPoolEntry::GetModifiedFee(), CTxMemPoolEntry::GetPriority(), CTxMemPoolEntry::GetSizeWithAncestors(), CTxMemPoolEntry::GetSizeWithDescendants(), CTxMemPoolEntry::GetTime(), CTxMemPoolEntry::GetTx(), CTxMemPoolEntry::GetTxSize(), COutPoint::hash, CInstantSend::HasTxLockRequest(), CChain::Height(), instantsend, CInstantSend::IsLockedInstantSendTransaction(), mempool, Pair(), CTxIn::prevout, UniValue::push_back(), base_blob< BITS >::ToString(), ValueFromAmount(), UniValue::VARR, and CTransaction::vin.
Referenced by getmempoolancestors(), getmempooldescendants(), getmempoolentry(), and mempoolToJSON().
getbestblockhash()
UniValue getbestblockhash (const JSONRPCRequest & request)
Definition at line 178 of file blockchain.cpp.
References chainActive, cs_main, JSONRPCRequest::fHelp, CBlockIndex::GetBlockHash(), base_blob< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), LOCK, JSONRPCRequest::params, UniValue::size(), and CChain::Tip().
getblock()
UniValue getblock (const JSONRPCRequest & request)
Definition at line 830 of file blockchain.cpp.
References CDataStream::begin(), BLOCK_HAVE_DATA, blockToJSON(), cs_main, CDataStream::end(), fHavePruned, JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), HexStr(), UniValue::isNum(), JSONRPCError(), LOCK, mapBlockIndex, CBlockIndex::nStatus, CBlockIndex::nTx, JSONRPCRequest::params, Params(), PROTOCOL_VERSION, ReadBlockFromDisk(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, UniValue::size(), and uint256S().
getblockchaininfo()
UniValue getblockchaininfo (const JSONRPCRequest & request)
Definition at line 1248 of file blockchain.cpp.
References BIP9SoftForkDescPushBack(), BLOCK_HAVE_DATA, chainActive, cs_main, Consensus::DEPLOYMENT_BIP147, Consensus::DEPLOYMENT_CSV, Consensus::DEPLOYMENT_DIP0001, Consensus::DEPLOYMENT_DIP0003, JSONRPCRequest::fHelp, fPruneMode, CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), GuessVerificationProgress(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, CBlockIndex::nChainWork, CBlockIndex::nHeight, CBlockIndex::nStatus, Pair(), JSONRPCRequest::params, Params(), pindexBestHeader, CBlockIndex::pprev, UniValue::push_back(), UniValue::size(), SoftForkDesc(), CChain::Tip(), UniValue::VARR, and UniValue::VOBJ.
Referenced by rest_chaininfo().
getblockcount()
UniValue getblockcount (const JSONRPCRequest & request)
Definition at line 161 of file blockchain.cpp.
References chainActive, cs_main, JSONRPCRequest::fHelp, CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, JSONRPCRequest::params, and UniValue::size().
getblockhash()
UniValue getblockhash (const JSONRPCRequest & request)
Definition at line 657 of file blockchain.cpp.
References chainActive, cs_main, JSONRPCRequest::fHelp, UniValue::get_int(), CBlockIndex::GetBlockHash(), base_blob< BITS >::GetHex(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, JSONRPCRequest::params, RPC_INVALID_PARAMETER, and UniValue::size().
getblockhashes()
UniValue getblockhashes (const JSONRPCRequest & request)
Definition at line 623 of file blockchain.cpp.
References JSONRPCRequest::fHelp, UniValue::get_int(), GetTimestampIndex(), HelpExampleCli(), HelpExampleRpc(), high, JSONRPCError(), low, JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and UniValue::VARR.
getblockheader()
UniValue getblockheader (const JSONRPCRequest & request)
Definition at line 682 of file blockchain.cpp.
References CDataStream::begin(), blockheaderToJSON(), cs_main, CDataStream::end(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_str(), CBlockIndex::GetBlockHeader(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK, mapBlockIndex, JSONRPCRequest::params, PROTOCOL_VERSION, RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, UniValue::size(), and uint256S().
getblockheaders()
UniValue getblockheaders (const JSONRPCRequest & request)
Definition at line 741 of file blockchain.cpp.
References CDataStream::begin(), blockheaderToJSON(), chainActive, cs_main, CDataStream::end(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), CBlockIndex::GetBlockHeader(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK, mapBlockIndex, MAX_HEADERS_RESULTS, CChain::Next(), JSONRPCRequest::params, PROTOCOL_VERSION, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, SER_NETWORK, UniValue::size(), strprintf, uint256S(), and UniValue::VARR.
getchaintips()
UniValue getchaintips (const JSONRPCRequest & request)
Definition at line 1348 of file blockchain.cpp.
References BLOCK_FAILED_MASK, BLOCK_VALID_SCRIPTS, BLOCK_VALID_TREE, chainActive, CChain::Contains(), cs_main, JSONRPCRequest::fHelp, CChain::FindFork(), UniValue::get_int(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), CBlockIndex::IsValid(), LOCK, mapBlockIndex, CBlockIndex::nChainTx, CBlockIndex::nChainWork, CBlockIndex::nHeight, CBlockIndex::nStatus, Pair(), PAIRTYPE, JSONRPCRequest::params, CBlockIndex::phashBlock, CBlockIndex::pprev, UniValue::push_back(), UniValue::size(), CChain::Tip(), UniValue::VARR, and UniValue::VOBJ.
GetDifficulty()
double GetDifficulty (const CBlockIndex * blockindex)
Definition at line 52 of file blockchain.cpp.
References chainActive, CBlockIndex::nBits, and CChain::Tip().
Referenced by blockheaderToJSON(), blockToJSON(), getblockchaininfo(), getchaintips(), getdifficulty(), getinfo(), and getmininginfo().
getdifficulty()
UniValue getdifficulty (const JSONRPCRequest & request)
Definition at line 327 of file blockchain.cpp.
References cs_main, JSONRPCRequest::fHelp, GetDifficulty(), HelpExampleCli(), HelpExampleRpc(), LOCK, JSONRPCRequest::params, and UniValue::size().
getmempoolancestors()
UniValue getmempoolancestors (const JSONRPCRequest & request)
Definition at line 462 of file blockchain.cpp.
References CTxMemPool::CalculateMemPoolAncestors(), CTxMemPool::cs, EntryDescriptionString(), entryToJSON(), JSONRPCRequest::fHelp, UniValue::get_bool(), CTransaction::GetHash(), CTxMemPoolEntry::GetTx(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, CTxMemPool::mapTx, mempool, Pair(), JSONRPCRequest::params, ParseHashV(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), base_blob< BITS >::ToString(), UniValue::VARR, and UniValue::VOBJ.
getmempooldescendants()
UniValue getmempooldescendants (const JSONRPCRequest & request)
Definition at line 526 of file blockchain.cpp.
References CTxMemPool::CalculateDescendants(), CTxMemPool::cs, EntryDescriptionString(), entryToJSON(), JSONRPCRequest::fHelp, UniValue::get_bool(), CTransaction::GetHash(), CTxMemPoolEntry::GetTx(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, CTxMemPool::mapTx, mempool, Pair(), JSONRPCRequest::params, ParseHashV(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), base_blob< BITS >::ToString(), UniValue::VARR, and UniValue::VOBJ.
getmempoolentry()
UniValue getmempoolentry (const JSONRPCRequest & request)
Definition at line 590 of file blockchain.cpp.
References CTxMemPool::cs, EntryDescriptionString(), entryToJSON(), JSONRPCRequest::fHelp, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, CTxMemPool::mapTx, mempool, JSONRPCRequest::params, ParseHashV(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and UniValue::VOBJ.
getmempoolinfo()
UniValue getmempoolinfo (const JSONRPCRequest & request)
Definition at line 1489 of file blockchain.cpp.
References JSONRPCRequest::fHelp, HelpExampleCli(), HelpExampleRpc(), mempoolInfoToJSON(), JSONRPCRequest::params, and UniValue::size().
getrawmempool()
UniValue getrawmempool (const JSONRPCRequest & request)
Definition at line 430 of file blockchain.cpp.
References EntryDescriptionString(), JSONRPCRequest::fHelp, UniValue::get_bool(), HelpExampleCli(), HelpExampleRpc(), mempoolToJSON(), JSONRPCRequest::params, and UniValue::size().
getspecialtxes()
UniValue getspecialtxes (const JSONRPCRequest & request)
Definition at line 1624 of file blockchain.cpp.
References BLOCK_HAVE_DATA, cs_main, EncodeHexTx(), fHavePruned, JSONRPCRequest::fHelp, UniValue::get_int(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, mapBlockIndex, CBlockIndex::nStatus, CBlockIndex::nTx, JSONRPCRequest::params, Params(), UniValue::push_back(), ReadBlockFromDisk(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, UniValue::size(), TRANSACTION_NORMAL, TxToJSON(), uint256S(), UniValue::VARR, UniValue::VOBJ, and CBlock::vtx.
gettxout()
UniValue gettxout (const JSONRPCRequest & request)
Definition at line 1070 of file blockchain.cpp.
References CTxMemPool::cs, cs_main, CURRENCY_UNIT, Coin::fCoinBase, JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), CCoinsViewCache::GetBestBlock(), CBlockIndex::GetBlockHash(), CCoinsViewCache::GetCoin(), CCoinsViewMemPool::GetCoin(), base_blob< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), CTxMemPool::isSpent(), LOCK, mapBlockIndex, mempool, MEMPOOL_HEIGHT, Coin::nHeight, CBlockIndex::nHeight, NullUniValue, CTxOut::nValue, Coin::out, Pair(), JSONRPCRequest::params, pcoinsTip, UniValue::push_back(), CTxOut::scriptPubKey, ScriptPubKeyToJSON(), UniValue::size(), uint256S(), ValueFromAmount(), and UniValue::VOBJ.
gettxoutsetinfo()
UniValue gettxoutsetinfo (const JSONRPCRequest & request)
Definition at line 1030 of file blockchain.cpp.
References JSONRPCRequest::fHelp, FlushStateToDisk(), base_blob< BITS >::GetHex(), GetUTXOStats(), CCoinsStats::hashBlock, CCoinsStats::hashSerialized, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), CCoinsStats::nDiskSize, CCoinsStats::nHeight, CCoinsStats::nTotalAmount, CCoinsStats::nTransactionOutputs, CCoinsStats::nTransactions, Pair(), JSONRPCRequest::params, pcoinsdbview, UniValue::push_back(), RPC_INTERNAL_ERROR, UniValue::size(), ValueFromAmount(), and UniValue::VOBJ.
GetUTXOStats()
static bool GetUTXOStats (CCoinsView * view, CCoinsStats & stats) static
Calculate statistics about the unspent transaction output set.
Definition at line 944 of file blockchain.cpp.
References ApplyStats(), cs_main, CCoinsView::Cursor(), error(), CCoinsView::EstimateSize(), COutPoint::hash, CCoinsStats::hashBlock, CCoinsStats::hashSerialized, LOCK, mapBlockIndex, COutPoint::n, CCoinsStats::nDiskSize, CCoinsStats::nHeight, PROTOCOL_VERSION, and SER_GETHASH.
Referenced by gettxoutsetinfo().
invalidateblock()
UniValue invalidateblock (const JSONRPCRequest & request)
Definition at line 1549 of file blockchain.cpp.
References ActivateBestChain(), cs_main, JSONRPCRequest::fHelp, UniValue::get_str(), CValidationState::GetRejectReason(), HelpExampleCli(), HelpExampleRpc(), InvalidateBlock(), CValidationState::IsValid(), JSONRPCError(), LOCK, mapBlockIndex, NullUniValue, JSONRPCRequest::params, Params(), RPC_DATABASE_ERROR, RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and uint256S().
mempoolInfoToJSON()
UniValue mempoolInfoToJSON ()
Definition at line 1476 of file blockchain.cpp.
References DEFAULT_MAX_MEMPOOL_SIZE, CTxMemPool::DynamicMemoryUsage(), GetArg(), CFeeRate::GetFeePerK(), CTxMemPool::GetMinFee(), CTxMemPool::GetTotalTxSize(), mempool, Pair(), UniValue::push_back(), CTxMemPool::size(), ValueFromAmount(), and UniValue::VOBJ.
Referenced by getmempoolinfo(), and rest_mempool_info().
mempoolToJSON()
UniValue mempoolToJSON (bool fVerbose = false)
Definition at line 402 of file blockchain.cpp.
References CTxMemPool::cs, entryToJSON(), CTransaction::GetHash(), CTxMemPoolEntry::GetTx(), LOCK, CTxMemPool::mapTx, mempool, Pair(), UniValue::push_back(), CTxMemPool::queryHashes(), base_blob< BITS >::ToString(), UniValue::VARR, and UniValue::VOBJ.
Referenced by getrawmempool(), and rest_mempool_contents().
preciousblock()
UniValue preciousblock (const JSONRPCRequest & request)
Definition at line 1511 of file blockchain.cpp.
References cs_main, JSONRPCRequest::fHelp, UniValue::get_str(), CValidationState::GetRejectReason(), HelpExampleCli(), HelpExampleRpc(), CValidationState::IsValid(), JSONRPCError(), LOCK, mapBlockIndex, NullUniValue, JSONRPCRequest::params, Params(), PreciousBlock(), RPC_DATABASE_ERROR, RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and uint256S().
pruneblockchain()
UniValue pruneblockchain (const JSONRPCRequest & request)
Definition at line 981 of file blockchain.cpp.
References chainActive, cs_main, JSONRPCRequest::fHelp, CChain::FindEarliestAtLeast(), fPruneMode, UniValue::get_int(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, LogPrint, MIN_BLOCKS_TO_KEEP, CBlockIndex::nHeight, JSONRPCRequest::params, Params(), PruneBlockFilesManual(), RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, RPC_METHOD_NOT_FOUND, and UniValue::size().
reconsiderblock()
UniValue reconsiderblock (const JSONRPCRequest & request)
Definition at line 1587 of file blockchain.cpp.
References ActivateBestChain(), cs_main, JSONRPCRequest::fHelp, UniValue::get_str(), CValidationState::GetRejectReason(), HelpExampleCli(), HelpExampleRpc(), CValidationState::IsValid(), JSONRPCError(), LOCK, mapBlockIndex, NullUniValue, JSONRPCRequest::params, Params(), ResetBlockFailureFlags(), RPC_DATABASE_ERROR, RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and uint256S().
RegisterBlockchainRPCCommands()
void RegisterBlockchainRPCCommands (CRPCTable & t)
Register block chain RPC commands.
Definition at line 1765 of file blockchain.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RPCNotifyBlockChange()
void RPCNotifyBlockChange (bool ibd, const CBlockIndex * pindex)
Definition at line 195 of file blockchain.cpp.
References cond_blockchange, cs_blockchange, CBlockIndex::GetBlockHash(), CUpdatedBlock::hash, CUpdatedBlock::height, latestblock, and CBlockIndex::nHeight.
Referenced by AppInitMain(), OnRPCStarted(), and OnRPCStopped().
ScriptPubKeyToJSON()
void ScriptPubKeyToJSON (const CScript & scriptPubKey, UniValue & out, bool fIncludeHex)
Definition at line 43 of file rawtransaction.cpp.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), ExtractDestinations(), GetTxnOutputType(), HexStr(), Pair(), UniValue::push_back(), ScriptToAsmStr(), and UniValue::VARR.
Referenced by decodescript(), gettxout(), and TxToJSON().
SoftForkDesc()
static UniValue SoftForkDesc (const std::string & name, int version, CBlockIndex * pindex, const Consensus::Params & consensusParams) static
Definition at line 1199 of file blockchain.cpp.
References name, Pair(), UniValue::push_back(), SoftForkMajorityDesc(), and UniValue::VOBJ.
Referenced by getblockchaininfo().
SoftForkMajorityDesc()
static UniValue SoftForkMajorityDesc (int version, CBlockIndex * pindex, const Consensus::Params & consensusParams) static
Implementation of IsSuperMajority with better feedback.
Definition at line 1179 of file blockchain.cpp.
References Consensus::Params::BIP34Height, Consensus::Params::BIP65Height, Consensus::Params::BIP66Height, CBlockIndex::nHeight, Pair(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by SoftForkDesc().
TxToJSON()
void TxToJSON (const CTransaction & tx, const uint256 hashBlock, UniValue & entry)
Definition at line 67 of file rawtransaction.cpp.
References CSpentIndexValue::addressHash, CSpentIndexValue::addressType, prevector< N, T, Size, Diff >::begin(), CSpentIndexValue::blockHeight, chainActive, CChain::Contains(), prevector< N, T, Size, Diff >::end(), CBlockIndex::GetBlockTime(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), GetSerializeSize(), GetSpentIndex(), GetTxPayload(), COutPoint::hash, CChain::Height(), HexStr(), CSpentIndexValue::inputIndex, instantsend, CTransaction::IsCoinBase(), CInstantSend::IsLockedInstantSendTransaction(), base_blob< BITS >::IsNull(), mapBlockIndex, COutPoint::n, CBlockIndex::nHeight, CTransaction::nLockTime, CTxIn::nSequence, CTransaction::nType, CTxOut::nValue, CTransaction::nVersion, Pair(), CTxIn::prevout, PROTOCOL_VERSION, UniValue::push_back(), CSpentIndexValue::satoshis, CTxOut::scriptPubKey, ScriptPubKeyToJSON(), CTxIn::scriptSig, ScriptToAsmStr(), SER_NETWORK, CCbTx::ToJson(), CProRegTx::ToJson(), CProUpServTx::ToJson(), llmq::CFinalCommitmentTxPayload::ToJson(), CProUpRegTx::ToJson(), CProUpRevTx::ToJson(), CBase58Data::ToString(), TRANSACTION_COINBASE, TRANSACTION_PROVIDER_REGISTER, TRANSACTION_PROVIDER_UPDATE_REGISTRAR, TRANSACTION_PROVIDER_UPDATE_REVOKE, TRANSACTION_PROVIDER_UPDATE_SERVICE, TRANSACTION_QUORUM_COMMITMENT, CSpentIndexValue::txid, ValueFromAmount(), UniValue::VARR, CTransaction::vExtraPayload, CTransaction::vin, UniValue::VOBJ, and CTransaction::vout.
Referenced by blockToJSON(), decoderawtransaction(), getrawtransaction(), and getspecialtxes().
verifychain()
UniValue verifychain (const JSONRPCRequest & request)
Definition at line 1150 of file blockchain.cpp.
References cs_main, DEFAULT_CHECKBLOCKS, DEFAULT_CHECKLEVEL, JSONRPCRequest::fHelp, UniValue::get_int(), GetArg(), HelpExampleCli(), HelpExampleRpc(), LOCK, JSONRPCRequest::params, Params(), pcoinsTip, UniValue::size(), strprintf, and CVerifyDB::VerifyDB().
waitforblock()
UniValue waitforblock (const JSONRPCRequest & request)
Definition at line 243 of file blockchain.cpp.
References cond_blockchange, cs_blockchange, JSONRPCRequest::fHelp, UniValue::get_int(), UniValue::get_str(), base_blob< BITS >::GetHex(), CUpdatedBlock::hash, CUpdatedBlock::height, HelpExampleCli(), HelpExampleRpc(), IsRPCRunning(), latestblock, Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), uint256S(), and UniValue::VOBJ.
waitforblockheight()
UniValue waitforblockheight (const JSONRPCRequest & request)
Definition at line 285 of file blockchain.cpp.
References cond_blockchange, cs_blockchange, JSONRPCRequest::fHelp, UniValue::get_int(), base_blob< BITS >::GetHex(), CUpdatedBlock::hash, CUpdatedBlock::height, HelpExampleCli(), HelpExampleRpc(), IsRPCRunning(), latestblock, Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), and UniValue::VOBJ.
waitfornewblock()
UniValue waitfornewblock (const JSONRPCRequest & request)
Definition at line 205 of file blockchain.cpp.
References cond_blockchange, cs_blockchange, JSONRPCRequest::fHelp, UniValue::get_int(), base_blob< BITS >::GetHex(), CUpdatedBlock::hash, CUpdatedBlock::height, HelpExampleCli(), HelpExampleRpc(), IsRPCRunning(), latestblock, Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), and UniValue::VOBJ.
Variable Documentation
commands
const CRPCCommand commands[] static
Definition at line 1731 of file blockchain.cpp.
Referenced by RegisterBlockchainRPCCommands().
cond_blockchange
std::condition_variable cond_blockchange static
Definition at line 46 of file blockchain.cpp.
Referenced by RPCNotifyBlockChange(), waitforblock(), waitforblockheight(), and waitfornewblock().
cs_blockchange
std::mutex cs_blockchange static
Definition at line 45 of file blockchain.cpp.
Referenced by RPCNotifyBlockChange(), waitforblock(), waitforblockheight(), and waitfornewblock().
latestblock
CUpdatedBlock latestblock static
Definition at line 47 of file blockchain.cpp.
Referenced by RPCNotifyBlockChange(), waitforblock(), waitforblockheight(), and waitfornewblock().
Released under the MIT license