Dash Core: src/chainparams.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
chainparams.h File Reference
#include "chainparamsbase.h"
#include "consensus/params.h"
#include "primitives/block.h"
#include "protocol.h"
#include <vector>
Classes
struct CDNSSeedData
struct SeedSpec6
struct CCheckpointData
struct ChainTxData
class CChainParams
CChainParams defines various tweakable parameters of a given instance of the Dash system.
Typedefs
typedef std::map< int, uint256 > MapCheckpoints
Functions
const CChainParams & Params ()
Return the currently selected parameters.
CChainParams & Params (const std::string &chain)
void SelectParams (const std::string &chain)
Sets the params returned by Params() to those for the given BIP70 chain name.
void UpdateRegtestBIP9Parameters (Consensus::DeploymentPos d, int64_t nStartTime, int64_t nTimeout)
Allows modifying the BIP9 regtest parameters.
void UpdateRegtestBudgetParameters (int nMasternodePaymentsStartBlock, int nBudgetPaymentsStartBlock, int nSuperblockStartBlock)
Allows modifying the budget regtest parameters.
void UpdateDevnetSubsidyAndDiffParams (int nMinimumDifficultyBlocks, int nHighSubsidyBlocks, int nHighSubsidyFactor)
Allows modifying the subsidy and difficulty devnet parameters.
Typedef Documentation
MapCheckpoints
typedef std::map<int, uint256> MapCheckpoints
Definition at line 27 of file chainparams.h.
Function Documentation
Params() [1/2]
const CChainParams& Params ()
Return the currently selected parameters.
This won't change after app startup, except for unit tests.
Definition at line 774 of file chainparams.cpp.
References pCurrentParams.
Referenced by AcceptToMemoryPoolWorker(), CNetFulfilledRequestManager::AddFulfilledRequest(), AddLocal(), AppInitMain(), AppInitParameterInteraction(), CMasternodeMan::AskForMN(), CWallet::AvailableCoins(), llmq::CDummyDKG::BuildDeterministicSvec(), BuildDMNListEntry(), CDeterministicMNManager::BuildNewListFromBlock(), BuildSimplifiedMNListDiff(), CBitcoinExtKeyBase< K, Size, Type >::CBitcoinExtKeyBase(), CPrivateSendServer::ChargeFees(), CMasternode::Check(), llmq::CheckLLMQCommitment(), CMasternodeBroadcast::CheckOutpoint(), CGovernanceManager::CheckPostponedObjects(), CheckService(), CheckSpecialTx(), ConnectBlock(), CConnman::ConnectNode(), ContextualCheckBlock(), ContextualCheckBlockHeader(), llmq::CDummyDKG::CreateDummyCommitment(), llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::CreateFinalCommitment(), BlockAssembler::CreateNewBlock(), CWallet::CreateTransaction(), CHDChain::DeriveChildExtKey(), BitcoinUnits::description(), DeserializeAndCheckBlockTest(), DisconnectBlock(), DisconnectBlocks(), CMasternodeMan::DsegUpdate(), PartiallyDownloadedBlock::FillBlock(), FlushStateToDisk(), generateBlocks(), CBitcoinAddress::Get(), CConnman::GetAddedNodeInfo(), llmq::CLLMQUtils::GetAllQuorumMembers(), getblock(), getblockchaininfo(), GetBlockSubsidy(), getblocktemplate(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), getgovernanceinfo(), CBitcoinAddress::GetIndexKey(), getinfo(), CBitcoinAddress::GetKeyID(), CHDPubKey::GetKeyPath(), ClientModel::getLastBlockDate(), GetListenPort(), CActiveDeterministicMasternodeManager::GetLocalAddress(), GetMasternodePayment(), CPrivateSend::GetMaxPoolTransactions(), llmq::CQuorumBlockProcessor::GetMinableCommitment(), getmininginfo(), CSuperblock::GetNearestSuperblocksHeights(), GetNetworkHashPS(), CSuperblock::GetPaymentsLimit(), llmq::CQuorumBlockProcessor::GetQuorumBlockHash(), getrawtransaction(), getspecialtxes(), CActiveLegacyMasternodeManager::GetStatus(), gettxoutproof(), llmq::CDummyDKG::GetValidMembers(), ClientModel::getVerificationProgress(), CNetFulfilledRequestManager::HasFulfilledRequest(), HelpMessage(), CActiveDeterministicMasternodeManager::Init(), invalidateblock(), PaymentServer::ipcParseCommandLine(), IsBlockPayeeValid(), IsBlockValueValid(), CGovernanceObject::IsCollateralValid(), CSuperblock::IsExpired(), CTxLockVote::IsExpired(), CTxLockCandidate::IsExpired(), IsInitialBlockDownload(), llmq::CQuorumBlockProcessor::IsMiningPhase(), IsOldBudgetBlockValueValid(), CBitcoinAddress::IsScript(), CBitcoinAddress::IsValid(), CBitcoinSecret::IsValid(), CTxLockRequest::IsValid(), CTxLockVote::IsValid(), CSuperblock::IsValidBlockHeight(), CMasternode::IsValidNetAddr(), CBlockTreeDB::LoadBlockIndexGuts(), main(), CActiveLegacyMasternodeManager::ManageState(), CActiveLegacyMasternodeManager::ManageStateInitial(), CGovernanceManager::MasternodeRateCheck(), BitcoinUnits::name(), CZMQPublishRawBlockNotifier::NotifyBlock(), CConnman::OpenNetworkConnection(), preciousblock(), llmq::CQuorumBlockProcessor::ProcessBlock(), CDeterministicMNManager::ProcessBlock(), llmq::CQuorumBlockProcessor::ProcessCommitment(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), llmq::CDummyDKG::ProcessMessage(), ProcessMessage(), ProcessMessages(), CMasternodeSync::ProcessTick(), pruneblockchain(), CConnman::PushMessage(), CMasternodeConfig::read(), CFlatDB< T >::Read(), CAddrDB::Read(), CBanDB::Read(), CNode::ReceiveMsgBytes(), reconsiderblock(), CNetFulfilledRequestManager::RemoveFulfilledRequest(), ReprocessBlocks(), CGovernanceManager::RequestGovernanceObject(), CGovernanceManager::RequestGovernanceObjectVotes(), CInstantSend::ResolveConflicts(), rest_block(), rest_tx(), CWallet::ScanForWalletTransactions(), SelectParams(), SendMessages(), CBitcoinAddress::Set(), setbip69enabled(), RPCConsole::setClientModel(), CBitcoinSecret::SetKey(), CBitcoinExtKeyBase< K, Size, Type >::SetKey(), setmocktime(), GUIUtil::setupAddressWidget(), CMasternodeBroadcast::SimpleCheck(), submitblock(), CMasternodeMan::SyncAll(), CConnman::ThreadDNSAddressSeed(), ThreadImport(), CConnman::ThreadOpenAddedConnections(), CConnman::ThreadOpenConnections(), ThreadSendAlert(), ModalOverlay::tipUpdate(), CGovernanceManager::UpdateCachesAndClean(), CDSNotificationInterface::UpdatedBlockTip(), llmq::CDummyDKG::UpdatedBlockTip(), SendCoinsDialog::updateGlobalFeeVariables(), BitcoinGUI::updateHeadersSyncProgressLabel(), CMasternode::UpdateLastPaid(), CGovernanceObject::UpdateSentinelVariables(), llmq::CFinalCommitment::Verify(), verifychain(), PaymentServer::verifyNetwork(), llmq::CFinalCommitment::VerifyNull(), CInstantSend::Vote(), CFlatDB< T >::Write(), CAddrDB::Write(), and CBanDB::Write().
Params() [2/2]
CChainParams& Params (const std::string & chain)
Returns
CChainParams for the given BIP70 chain name.
Definition at line 779 of file chainparams.cpp.
References CBaseChainParams::DEVNET, devNetParams, CBaseChainParams::MAIN, mainParams, CBaseChainParams::REGTEST, regTestParams, strprintf, CBaseChainParams::TESTNET, and testNetParams.
SelectParams()
void SelectParams (const std::string & chain)
Sets the params returned by Params() to those for the given BIP70 chain name.
Exceptions
std::runtime_error when the chain is not supported.
Definition at line 794 of file chainparams.cpp.
References CBaseChainParams::DEVNET, devNetParams, Params(), pCurrentParams, and SelectBaseParams().
Referenced by AppInit(), AppInitRawTx(), PaymentServer::ipcParseCommandLine(), and main().
UpdateDevnetSubsidyAndDiffParams()
void UpdateDevnetSubsidyAndDiffParams (int nMinimumDifficultyBlocks, int nHighSubsidyBlocks, int nHighSubsidyFactor)
Allows modifying the subsidy and difficulty devnet parameters.
Definition at line 816 of file chainparams.cpp.
References devNetParams, and CDevNetParams::UpdateSubsidyAndDiffParams().
Referenced by AppInitParameterInteraction().
UpdateRegtestBIP9Parameters()
void UpdateRegtestBIP9Parameters (Consensus::DeploymentPos d, int64_t nStartTime, int64_t nTimeout)
Allows modifying the BIP9 regtest parameters.
Definition at line 806 of file chainparams.cpp.
References regTestParams, and CRegTestParams::UpdateBIP9Parameters().
Referenced by AppInitParameterInteraction().
UpdateRegtestBudgetParameters()
void UpdateRegtestBudgetParameters (int nMasternodePaymentsStartBlock, int nBudgetPaymentsStartBlock, int nSuperblockStartBlock)
Allows modifying the budget regtest parameters.
Definition at line 811 of file chainparams.cpp.
References regTestParams, and CRegTestParams::UpdateBudgetParameters().
Referenced by AppInitParameterInteraction().
Released under the MIT license