Dash Core: CScopedDBTransaction< Parent, CommitTarget > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CScopedDBTransaction< Parent, CommitTarget > Class Template Reference
#include <dbwrapper.h>
Public Types
typedef CDBTransaction< Parent, CommitTarget > Transaction
Public Member Functions
CScopedDBTransaction (Transaction &dbTx)
~CScopedDBTransaction ()
void Commit ()
void Rollback ()
void SetCommitHandler (const std::function< void()> &h)
void SetRollbackHandler (const std::function< void()> &h)
Static Public Member Functions
static std::unique_ptr< CScopedDBTransaction< Parent, CommitTarget > > Begin (Transaction &dbTx)
Private Attributes
Transaction & dbTransaction
std::function< void()> commitHandler
std::function< void()> rollbackHandler
bool didCommitOrRollback {}
Detailed Description
template<typename Parent, typename CommitTarget>
class CScopedDBTransaction< Parent, CommitTarget >
Definition at line 536 of file dbwrapper.h.
Member Typedef Documentation
Transaction
template<typename Parent , typename CommitTarget > typedef CDBTransaction<Parent, CommitTarget> CScopedDBTransaction< Parent, CommitTarget >::Transaction
Definition at line 538 of file dbwrapper.h.
Constructor & Destructor Documentation
CScopedDBTransaction()
template<typename Parent , typename CommitTarget > CScopedDBTransaction< Parent, CommitTarget >::CScopedDBTransaction (Transaction & dbTx) inline
Definition at line 547 of file dbwrapper.h.
~CScopedDBTransaction()
template<typename Parent , typename CommitTarget > CScopedDBTransaction< Parent, CommitTarget >::~CScopedDBTransaction () inline
Definition at line 548 of file dbwrapper.h.
References CScopedDBTransaction< Parent, CommitTarget >::didCommitOrRollback, and CScopedDBTransaction< Parent, CommitTarget >::Rollback().
Member Function Documentation
Begin()
template<typename Parent , typename CommitTarget > static std::unique_ptr<CScopedDBTransaction<Parent, CommitTarget> > CScopedDBTransaction< Parent, CommitTarget >::Begin (Transaction & dbTx) inline static
Definition at line 567 of file dbwrapper.h.
References CDBTransaction< Parent, CommitTarget >::IsClean().
Referenced by CEvoDB::BeginTransaction().
Commit()
template<typename Parent , typename CommitTarget > void CScopedDBTransaction< Parent, CommitTarget >::Commit () inline
Definition at line 552 of file dbwrapper.h.
References CDBTransaction< Parent, CommitTarget >::Commit(), CScopedDBTransaction< Parent, CommitTarget >::commitHandler, CScopedDBTransaction< Parent, CommitTarget >::dbTransaction, and CScopedDBTransaction< Parent, CommitTarget >::didCommitOrRollback.
Rollback()
template<typename Parent , typename CommitTarget > void CScopedDBTransaction< Parent, CommitTarget >::Rollback () inline
Definition at line 559 of file dbwrapper.h.
References CDBTransaction< Parent, CommitTarget >::Clear(), CScopedDBTransaction< Parent, CommitTarget >::dbTransaction, CScopedDBTransaction< Parent, CommitTarget >::didCommitOrRollback, and CScopedDBTransaction< Parent, CommitTarget >::rollbackHandler.
Referenced by CScopedDBTransaction< Parent, CommitTarget >::~CScopedDBTransaction().
SetCommitHandler()
template<typename Parent , typename CommitTarget > void CScopedDBTransaction< Parent, CommitTarget >::SetCommitHandler (const std::function< void()> & h) inline
Definition at line 572 of file dbwrapper.h.
References CScopedDBTransaction< Parent, CommitTarget >::commitHandler.
SetRollbackHandler()
template<typename Parent , typename CommitTarget > void CScopedDBTransaction< Parent, CommitTarget >::SetRollbackHandler (const std::function< void()> & h) inline
Definition at line 575 of file dbwrapper.h.
References CScopedDBTransaction< Parent, CommitTarget >::rollbackHandler.
Member Data Documentation
commitHandler
template<typename Parent , typename CommitTarget > std::function<void ()> CScopedDBTransaction< Parent, CommitTarget >::commitHandler private
Definition at line 542 of file dbwrapper.h.
Referenced by CScopedDBTransaction< Parent, CommitTarget >::Commit(), and CScopedDBTransaction< Parent, CommitTarget >::SetCommitHandler().
dbTransaction
template<typename Parent , typename CommitTarget > Transaction& CScopedDBTransaction< Parent, CommitTarget >::dbTransaction private
Definition at line 541 of file dbwrapper.h.
Referenced by CScopedDBTransaction< Parent, CommitTarget >::Commit(), and CScopedDBTransaction< Parent, CommitTarget >::Rollback().
didCommitOrRollback
template<typename Parent , typename CommitTarget > bool CScopedDBTransaction< Parent, CommitTarget >::didCommitOrRollback {} private
Definition at line 544 of file dbwrapper.h.
Referenced by CScopedDBTransaction< Parent, CommitTarget >::Commit(), CScopedDBTransaction< Parent, CommitTarget >::Rollback(), and CScopedDBTransaction< Parent, CommitTarget >::~CScopedDBTransaction().
rollbackHandler
template<typename Parent , typename CommitTarget > std::function<void ()> CScopedDBTransaction< Parent, CommitTarget >::rollbackHandler private
Definition at line 543 of file dbwrapper.h.
Referenced by CScopedDBTransaction< Parent, CommitTarget >::Rollback(), and CScopedDBTransaction< Parent, CommitTarget >::SetRollbackHandler().
The documentation for this class was generated from the following file:
src/dbwrapper.h
Released under the MIT license