Dash Core: CBlockPolicyEstimator Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CBlockPolicyEstimator Class Reference
We want to be able to estimate feerates that are needed on tx's to be included in a certain number of blocks.
#include <fees.h>
Classes
struct TxStatsInfo
Public Member Functions
CBlockPolicyEstimator (const CFeeRate &minRelayFee)
Create new BlockPolicyEstimator and initialize stats tracking classes with default values.
void processBlock (unsigned int nBlockHeight, std::vector< const CTxMemPoolEntry *> &entries)
Process all the transactions that have been included in a block.
bool processBlockTx (unsigned int nBlockHeight, const CTxMemPoolEntry *entry)
Process a transaction confirmed in a block.
void processTransaction (const CTxMemPoolEntry &entry, bool validFeeEstimate)
Process a transaction accepted to the mempool.
bool removeTx (uint256 hash)
Remove a transaction from the mempool tracking stats.
CFeeRate estimateFee (int confTarget)
Return a feerate estimate.
CFeeRate estimateSmartFee (int confTarget, int *answerFoundAtTarget, const CTxMemPool &pool)
Estimate feerate needed to get be included in a block within confTarget blocks.
double estimatePriority (int confTarget)
Return a priority estimate.
double estimateSmartPriority (int confTarget, int *answerFoundAtTarget, const CTxMemPool &pool)
Estimate priority needed to get be included in a block within confTarget blocks.
void Write (CAutoFile &fileout)
Write estimation data to a file.
void Read (CAutoFile &filein, int nFileVersion)
Read estimation data from a file.
Private Attributes
CFeeRate minTrackedFee
Passed to constructor to avoid dependency on main.
unsigned int nBestSeenHeight
std::map< uint256, TxStatsInfo > mapMemPoolTxs
TxConfirmStats feeStats
Classes to track historical data on transaction confirmations.
unsigned int trackedTxs
unsigned int untrackedTxs
Detailed Description
We want to be able to estimate feerates that are needed on tx's to be included in a certain number of blocks.
The BlockPolicyEstimator is used for estimating the feerate needed for a transaction to be included in a block within a certain number of blocks.
Every time a block is added to the best chain, this class records stats on the transactions included in that block
At a high level the algorithm works by grouping transactions into buckets based on having similar feerates and then tracking how long it takes transactions in the various buckets to be mined. It operates under the assumption that in general transactions of higher feerate will be included in blocks before transactions of lower feerate. So for example if you wanted to know what feerate you should put on a transaction to be included in a block within the next 5 blocks, you would start by looking at the bucket with the highest feerate transactions and verifying that a sufficiently high percentage of them were confirmed within 5 blocks and then you would look at the next highest feerate bucket, and so on, stopping at the last bucket to pass the test. The average feerate of transactions in this bucket will give you an indication of the lowest feerate you can put on a transaction and still have a sufficiently high chance of being confirmed within your desired 5 blocks.
Here is a brief description of the implementation: When a transaction enters the mempool, we track the height of the block chain at entry. Whenever a block comes in, we count the number of transactions in each bucket and the total amount of feerate paid in each bucket. Then we calculate how many blocks Y it took each transaction to be mined and we track an array of counters in each bucket for how long it to took transactions to get confirmed from 1 to a max of 25 and we increment all the counters from Y up to 25. This is because for any number Z>=Y the transaction was successfully mined within Z blocks. We want to save a history of this information, so at any time we have a counter of the total number of transactions that happened in a given feerate bucket and the total number that were confirmed in each number 1-25 blocks or less for any bucket. We save this history by keeping an exponentially decaying moving average of each one of these stats. Furthermore we also keep track of the number unmined (in mempool) transactions in each bucket and for how many blocks they have been outstanding and use that to increase the number of transactions we've seen in that feerate bucket when calculating an estimate for any number of confirmations below the number of blocks they've been outstanding.
Definition at line 198 of file fees.h.
Constructor & Destructor Documentation
CBlockPolicyEstimator()
CBlockPolicyEstimator::CBlockPolicyEstimator (const CFeeRate & minRelayFee)
Create new BlockPolicyEstimator and initialize stats tracking classes with default values.
Definition at line 300 of file fees.cpp.
References DEFAULT_DECAY, FEE_SPACING, feeStats, CFeeRate::GetFeePerK(), INF_FEERATE, TxConfirmStats::Initialize(), MAX_BLOCK_CONFIRMS, MAX_FEERATE, MIN_FEERATE, and minTrackedFee.
Member Function Documentation
estimateFee()
CFeeRate CBlockPolicyEstimator::estimateFee (int confTarget)
Return a feerate estimate.
Definition at line 407 of file fees.cpp.
References TxConfirmStats::EstimateMedianVal(), feeStats, TxConfirmStats::GetMaxConfirms(), MIN_SUCCESS_PCT, nBestSeenHeight, and SUFFICIENT_FEETXS.
Referenced by CTxMemPool::estimateFee().
estimatePriority()
double CBlockPolicyEstimator::estimatePriority (int confTarget)
Return a priority estimate.
DEPRECATED Returns -1
Definition at line 453 of file fees.cpp.
Referenced by CTxMemPool::estimatePriority().
estimateSmartFee()
CFeeRate CBlockPolicyEstimator::estimateSmartFee (int confTarget, int * answerFoundAtTarget, const CTxMemPool & pool)
Estimate feerate needed to get be included in a block within confTarget blocks.
If no answer can be given at confTarget, return an estimate at the lowest target where one can be given.
Definition at line 422 of file fees.cpp.
References DEFAULT_MAX_MEMPOOL_SIZE, TxConfirmStats::EstimateMedianVal(), feeStats, GetArg(), CFeeRate::GetFeePerK(), TxConfirmStats::GetMaxConfirms(), CTxMemPool::GetMinFee(), MIN_SUCCESS_PCT, nBestSeenHeight, and SUFFICIENT_FEETXS.
Referenced by CTxMemPool::estimateSmartFee().
estimateSmartPriority()
double CBlockPolicyEstimator::estimateSmartPriority (int confTarget, int * answerFoundAtTarget, const CTxMemPool & pool)
Estimate priority needed to get be included in a block within confTarget blocks.
DEPRECATED Returns -1 unless mempool is currently limited then returns INF_PRIORITY answerFoundAtTarget is set to confTarget
Definition at line 458 of file fees.cpp.
References DEFAULT_MAX_MEMPOOL_SIZE, GetArg(), CFeeRate::GetFeePerK(), CTxMemPool::GetMinFee(), and INF_PRIORITY.
Referenced by CTxMemPool::estimateSmartPriority().
processBlock()
void CBlockPolicyEstimator::processBlock (unsigned int nBlockHeight, std::vector< const CTxMemPoolEntry *> & entries)
Process all the transactions that have been included in a block.
Definition at line 370 of file fees.cpp.
References TxConfirmStats::ClearCurrent(), feeStats, LogPrint, mapMemPoolTxs, nBestSeenHeight, processBlockTx(), trackedTxs, untrackedTxs, and TxConfirmStats::UpdateMovingAverages().
Referenced by CTxMemPool::removeForBlock().
processBlockTx()
bool CBlockPolicyEstimator::processBlockTx (unsigned int nBlockHeight, const CTxMemPoolEntry * entry)
Process a transaction confirmed in a block.
Definition at line 345 of file fees.cpp.
References feeStats, CTxMemPoolEntry::GetFee(), CTransaction::GetHash(), CTxMemPoolEntry::GetHeight(), CTxMemPoolEntry::GetTx(), CTxMemPoolEntry::GetTxSize(), LogPrint, TxConfirmStats::Record(), and removeTx().
Referenced by processBlock().
processTransaction()
void CBlockPolicyEstimator::processTransaction (const CTxMemPoolEntry & entry, bool validFeeEstimate)
Process a transaction accepted to the mempool.
Definition at line 313 of file fees.cpp.
References feeStats, CTxMemPoolEntry::GetFee(), CTransaction::GetHash(), CTxMemPoolEntry::GetHeight(), CTxMemPoolEntry::GetTx(), CTxMemPoolEntry::GetTxSize(), LogPrint, mapMemPoolTxs, nBestSeenHeight, TxConfirmStats::NewTx(), base_blob< BITS >::ToString(), trackedTxs, and untrackedTxs.
Referenced by CTxMemPool::addUnchecked().
Read()
void CBlockPolicyEstimator::Read (CAutoFile & filein, int nFileVersion)
Read estimation data from a file.
Definition at line 477 of file fees.cpp.
References feeStats, nBestSeenHeight, and TxConfirmStats::Read().
Referenced by CTxMemPool::ReadFeeEstimates().
removeTx()
bool CBlockPolicyEstimator::removeTx (uint256 hash)
Remove a transaction from the mempool tracking stats.
Definition at line 288 of file fees.cpp.
References feeStats, mapMemPoolTxs, nBestSeenHeight, and TxConfirmStats::removeTx().
Referenced by processBlockTx(), and CTxMemPool::removeUnchecked().
Write()
void CBlockPolicyEstimator::Write (CAutoFile & fileout)
Write estimation data to a file.
Definition at line 471 of file fees.cpp.
References feeStats, fileout, nBestSeenHeight, and TxConfirmStats::Write().
Referenced by CTxMemPool::WriteFeeEstimates().
Member Data Documentation
feeStats
TxConfirmStats CBlockPolicyEstimator::feeStats private
Classes to track historical data on transaction confirmations.
Definition at line 260 of file fees.h.
Referenced by CBlockPolicyEstimator(), estimateFee(), estimateSmartFee(), processBlock(), processBlockTx(), processTransaction(), Read(), removeTx(), and Write().
mapMemPoolTxs
std::map<uint256, TxStatsInfo> CBlockPolicyEstimator::mapMemPoolTxs private
Definition at line 257 of file fees.h.
Referenced by processBlock(), processTransaction(), and removeTx().
minTrackedFee
CFeeRate CBlockPolicyEstimator::minTrackedFee private
Passed to constructor to avoid dependency on main.
Definition at line 247 of file fees.h.
Referenced by CBlockPolicyEstimator().
nBestSeenHeight
unsigned int CBlockPolicyEstimator::nBestSeenHeight private
Definition at line 248 of file fees.h.
Referenced by estimateFee(), estimateSmartFee(), processBlock(), processTransaction(), Read(), removeTx(), and Write().
trackedTxs
unsigned int CBlockPolicyEstimator::trackedTxs private
Definition at line 262 of file fees.h.
Referenced by processBlock(), and processTransaction().
untrackedTxs
unsigned int CBlockPolicyEstimator::untrackedTxs private
Definition at line 263 of file fees.h.
Referenced by processBlock(), and processTransaction().
The documentation for this class was generated from the following files:
src/policy/fees.h
src/policy/fees.cpp
Released under the MIT license