Dash Core: CTxLockVote Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CTxLockVote Class Reference
An InstantSend transaction lock vote.
#include <instantx.h>
Public Member Functions
CTxLockVote ()
CTxLockVote (const uint256 &txHashIn, const COutPoint &outpointIn, const COutPoint &outpointMasternodeIn, const uint256 &quorumModifierHashIn, const uint256 &masternodeProTxHashIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
uint256 GetHash () const
uint256 GetSignatureHash () const
uint256 GetTxHash () const
COutPoint GetOutpoint () const
COutPoint GetMasternodeOutpoint () const
bool IsValid (CNode *pnode, CConnman &connman) const
void SetConfirmedHeight (int nConfirmedHeightIn)
bool IsExpired (int nHeight) const
bool IsTimedOut () const
bool IsFailed () const
bool Sign ()
bool CheckSignature () const
void Relay (CConnman &connman) const
Public Attributes
ADD_SERIALIZE_METHODS
Private Attributes
uint256 txHash
COutPoint outpoint
COutPoint outpointMasternode
uint256 quorumModifierHash
uint256 masternodeProTxHash
std::vector< unsigned char > vchMasternodeSignature
int nConfirmedHeight
When corresponding tx is 0-confirmed or conflicted, nConfirmedHeight is -1.
int64_t nTimeCreated
Detailed Description
An InstantSend transaction lock vote.
Sent by a masternode in response to a transaction lock request (ix message) to indicate the transaction input can be locked. Contains the proposed transaction's hash and the outpoint being locked along with the masternodes outpoint and signature.
See also
CTxLockRequest
Definition at line 231 of file instantx.h.
Constructor & Destructor Documentation
CTxLockVote() [1/2]
CTxLockVote::CTxLockVote () inline
Definition at line 246 of file instantx.h.
CTxLockVote() [2/2]
CTxLockVote::CTxLockVote (const uint256 & txHashIn, const COutPoint & outpointIn, const COutPoint & outpointMasternodeIn, const uint256 & quorumModifierHashIn, const uint256 & masternodeProTxHashIn) inline
Definition at line 257 of file instantx.h.
Member Function Documentation
CheckSignature()
bool CTxLockVote::CheckSignature () const
Definition at line 1104 of file instantx.cpp.
References masternode_info_t::blsPubKeyOperator, deterministicMNManager, CMasternodeMan::GetMasternodeInfo(), GetSignatureHash(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CSporkManager::IsSporkActive(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), masternode_info_t::legacyKeyIDOperator, LogPrintf, mnodeman, outpoint, outpointMasternode, CBLSWrapper< ImplType, _SerSize, C >::SetBuf(), SPORK_6_NEW_SIGS, sporkManager, base_blob< BITS >::ToString(), COutPoint::ToString(), COutPoint::ToStringShort(), txHash, vchMasternodeSignature, CHashSigner::VerifyHash(), CBLSSignature::VerifyInsecure(), and CMessageSigner::VerifyMessage().
Referenced by IsValid(), and CInstantSend::Vote().
GetHash()
uint256 CTxLockVote::GetHash () const
Definition at line 1094 of file instantx.cpp.
References SerializeHash().
Referenced by GetSignatureHash(), IsValid(), CInstantSend::ProcessNewTxLockVote(), CInstantSend::ProcessOrphanTxLockVote(), Relay(), and CInstantSend::Vote().
GetMasternodeOutpoint()
COutPoint CTxLockVote::GetMasternodeOutpoint () const inline
Definition at line 291 of file instantx.h.
References outpointMasternode.
Referenced by COutPointLock::AddVote(), CInstantSend::ProcessNewTxLockVote(), and CInstantSend::UpdateVotedOutpoints().
GetOutpoint()
COutPoint CTxLockVote::GetOutpoint () const inline
Definition at line 290 of file instantx.h.
References outpoint.
Referenced by CTxLockCandidate::AddVote(), and CInstantSend::UpdateVotedOutpoints().
GetSignatureHash()
uint256 CTxLockVote::GetSignatureHash () const
Definition at line 1099 of file instantx.cpp.
References GetHash().
Referenced by CheckSignature(), and Sign().
GetTxHash()
uint256 CTxLockVote::GetTxHash () const inline
Definition at line 289 of file instantx.h.
References txHash.
Referenced by IsFailed(), CInstantSend::ProcessNewTxLockVote(), CInstantSend::ProcessOrphanTxLockVote(), and CInstantSend::UpdateVotedOutpoints().
IsExpired()
bool CTxLockVote::IsExpired (int nHeight) const
Definition at line 1199 of file instantx.cpp.
References CChainParams::GetConsensus(), nConfirmedHeight, Consensus::Params::nInstantSendKeepLock, and Params().
IsFailed()
bool CTxLockVote::IsFailed () const
Definition at line 1210 of file instantx.cpp.
References GetTime(), GetTxHash(), instantsend, INSTANTSEND_FAILED_TIMEOUT_SECONDS, CInstantSend::IsLockedInstantSendTransaction(), and nTimeCreated.
IsTimedOut()
bool CTxLockVote::IsTimedOut () const
Definition at line 1205 of file instantx.cpp.
References GetTime(), INSTANTSEND_LOCK_TIMEOUT_SECONDS, and nTimeCreated.
IsValid()
bool CTxLockVote::IsValid (CNode * pnode, CConnman & connman) const
Definition at line 1030 of file instantx.cpp.
References CMasternodeMan::AskForMN(), CheckSignature(), deterministicMNManager, CChainParams::GetConsensus(), GetHash(), CMasternodeMan::GetMasternodeInfo(), CMasternodeMan::GetMasternodeRank(), CMasternodePayments::GetMinMasternodePaymentsProto(), GetUTXOCoin(), CMasternodeMan::Has(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), base_blob< BITS >::IsNull(), LogPrint, LogPrintf, masternodeProTxHash, MIN_INSTANTSEND_PROTO_VERSION, mnodeman, mnpayments, Coin::nHeight, Consensus::Params::nInstantSendConfirmationsRequired, masternode_info_t::outpoint, outpoint, outpointMasternode, Params(), quorumModifierHash, COutPointLock::SIGNATURES_TOTAL, base_blob< BITS >::ToString(), and COutPoint::ToStringShort().
Referenced by CInstantSend::ProcessNewTxLockVote().
Relay()
void CTxLockVote::Relay (CConnman & connman) const
Definition at line 1188 of file instantx.cpp.
References GetHash(), CInstantSend::GetTxLockRequest(), instantsend, MSG_TXLOCK_VOTE, CConnman::RelayInvFiltered(), CTxLockRequest::tx, and txHash.
Referenced by CInstantSend::ProcessNewTxLockVote(), and CInstantSend::Vote().
SerializationOp()
template<typename Stream , typename Operation > void CTxLockVote::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 271 of file instantx.h.
References deterministicMNManager, CDeterministicMNManager::IsDeterministicMNsSporkActive(), masternodeProTxHash, outpoint, outpointMasternode, quorumModifierHash, READWRITE, SER_GETHASH, txHash, and vchMasternodeSignature.
SetConfirmedHeight()
void CTxLockVote::SetConfirmedHeight (int nConfirmedHeightIn) inline
Definition at line 294 of file instantx.h.
References nConfirmedHeight.
Sign()
bool CTxLockVote::Sign ()
Definition at line 1147 of file instantx.cpp.
References activeMasternodeInfo, CActiveMasternodeInfo::blsKeyOperator, deterministicMNManager, CBLSWrapper< ImplType, _SerSize, C >::GetBuf(), GetSignatureHash(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CSporkManager::IsSporkActive(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CActiveMasternodeInfo::legacyKeyIDOperator, CActiveMasternodeInfo::legacyKeyOperator, LogPrintf, outpoint, CHashSigner::SignHash(), CMessageSigner::SignMessage(), SPORK_6_NEW_SIGS, sporkManager, base_blob< BITS >::ToString(), COutPoint::ToStringShort(), txHash, vchMasternodeSignature, CHashSigner::VerifyHash(), and CMessageSigner::VerifyMessage().
Referenced by CInstantSend::Vote().
Member Data Documentation
ADD_SERIALIZE_METHODS
CTxLockVote::ADD_SERIALIZE_METHODS
Definition at line 268 of file instantx.h.
masternodeProTxHash
uint256 CTxLockVote::masternodeProTxHash private
Definition at line 239 of file instantx.h.
Referenced by IsValid(), and SerializationOp().
nConfirmedHeight
int CTxLockVote::nConfirmedHeight private
When corresponding tx is 0-confirmed or conflicted, nConfirmedHeight is -1.
Definition at line 242 of file instantx.h.
Referenced by IsExpired(), and SetConfirmedHeight().
nTimeCreated
int64_t CTxLockVote::nTimeCreated private
Definition at line 243 of file instantx.h.
Referenced by IsFailed(), and IsTimedOut().
outpoint
COutPoint CTxLockVote::outpoint private
Definition at line 235 of file instantx.h.
Referenced by CheckSignature(), GetOutpoint(), IsValid(), SerializationOp(), and Sign().
outpointMasternode
COutPoint CTxLockVote::outpointMasternode private
Definition at line 237 of file instantx.h.
Referenced by CheckSignature(), GetMasternodeOutpoint(), IsValid(), and SerializationOp().
quorumModifierHash
uint256 CTxLockVote::quorumModifierHash private
Definition at line 238 of file instantx.h.
Referenced by IsValid(), and SerializationOp().
txHash
uint256 CTxLockVote::txHash private
Definition at line 234 of file instantx.h.
Referenced by CheckSignature(), GetTxHash(), Relay(), SerializationOp(), and Sign().
vchMasternodeSignature
std::vector<unsigned char> CTxLockVote::vchMasternodeSignature private
Definition at line 240 of file instantx.h.
Referenced by CheckSignature(), SerializationOp(), and Sign().
The documentation for this class was generated from the following files:
src/instantx.h
src/instantx.cpp
Released under the MIT license