Dash Core: CDeterministicMNManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CDeterministicMNManager Class Reference
#include <deterministicmns.h>
Public Member Functions
CDeterministicMNManager (CEvoDB &_evoDb)
bool ProcessBlock (const CBlock &block, const CBlockIndex *pindex, CValidationState &state)
bool UndoBlock (const CBlock &block, const CBlockIndex *pindex)
void UpdatedBlockTip (const CBlockIndex *pindex)
bool BuildNewListFromBlock (const CBlock &block, const CBlockIndex *pindexPrev, CValidationState &state, CDeterministicMNList &mnListRet, bool debugLogs)
void HandleQuorumCommitment (llmq::CFinalCommitment &qc, CDeterministicMNList &mnList, bool debugLogs)
void DecreasePoSePenalties (CDeterministicMNList &mnList)
CDeterministicMNList GetListForBlock (const uint256 &blockHash)
CDeterministicMNList GetListAtChainTip ()
bool HasValidMNCollateralAtChainTip (const COutPoint &outpoint)
bool HasMNCollateralAtChainTip (const COutPoint &outpoint)
bool IsProTxWithCollateral (const CTransactionRef &tx, uint32_t n)
bool IsDeterministicMNsSporkActive (int nHeight=-1)
Public Attributes
CCriticalSection cs
Private Member Functions
int64_t GetSpork15Value ()
void CleanupCache (int nHeight)
Private Attributes
CEvoDB & evoDb
std::map< uint256, CDeterministicMNList > mnListsCache
int tipHeight {-1}
uint256 tipBlockHash
Static Private Attributes
static const int SNAPSHOT_LIST_PERIOD = 576
static const int LISTS_CACHE_SIZE = 576
Detailed Description
Definition at line 451 of file deterministicmns.h.
Constructor & Destructor Documentation
CDeterministicMNManager()
CDeterministicMNManager::CDeterministicMNManager (CEvoDB & _evoDb)
Definition at line 443 of file deterministicmns.cpp.
Member Function Documentation
BuildNewListFromBlock()
bool CDeterministicMNManager::BuildNewListFromBlock (const CBlock & block, const CBlockIndex * pindexPrev, CValidationState & state, CDeterministicMNList & mnListRet, bool debugLogs)
Definition at line 517 of file deterministicmns.cpp.
References CProRegTx::addr, CProUpServTx::addr, AssertLockHeld, COIN, CProRegTx::collateralOutpoint, llmq::CFinalCommitmentTxPayload::commitment, cs, DecreasePoSePenalties(), CValidationState::DoS(), CDeterministicMNList::ForEachMN(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), CTransaction::GetHash(), GetListForBlock(), CDeterministicMNList::GetMNPayee(), GetTxPayload(), GetUTXOCoin(), HandleQuorumCommitment(), COutPoint::hash, base_blob< BITS >::IsNull(), llmq::CFinalCommitment::IsNull(), CProRegTx::keyIDOwner, CProUpRegTx::keyIDVoting, LogPrintf, COutPoint::n, CBlockIndex::nHeight, Consensus::Params::nMasternodeMinimumConfirmations, CProRegTx::nOperatorReward, CProUpRevTx::nReason, CDeterministicMNState::nRegisteredHeight, CTransaction::nType, CTxOut::nValue, CTransaction::nVersion, Coin::out, Params(), CProUpServTx::proTxHash, CProUpRegTx::proTxHash, CProUpRevTx::proTxHash, CProRegTx::pubKeyOperator, CProUpRegTx::pubKeyOperator, REJECT_CONFLICT, REJECT_INVALID, CProUpServTx::scriptOperatorPayout, CProUpRegTx::scriptPayout, CDeterministicMNList::SetBlockHash(), base_blob< BITS >::ToString(), CProRegTx::ToString(), CProUpServTx::ToString(), CProUpRegTx::ToString(), CProUpRevTx::ToString(), TRANSACTION_PROVIDER_REGISTER, TRANSACTION_PROVIDER_UPDATE_REGISTRAR, TRANSACTION_PROVIDER_UPDATE_REVOKE, TRANSACTION_PROVIDER_UPDATE_SERVICE, TRANSACTION_QUORUM_COMMITMENT, CDeterministicMNState::UpdateConfirmedHash(), CTransaction::vin, and CBlock::vtx.
Referenced by CalcCbTxMerkleRootMNList(), and ProcessBlock().
CleanupCache()
void CDeterministicMNManager::CleanupCache (int nHeight) private
Definition at line 890 of file deterministicmns.cpp.
References AssertLockHeld, cs, LISTS_CACHE_SIZE, and mnListsCache.
Referenced by ProcessBlock().
DecreasePoSePenalties()
void CDeterministicMNManager::DecreasePoSePenalties (CDeterministicMNList & mnList)
Definition at line 766 of file deterministicmns.cpp.
References CDeterministicMNList::ForEachMN(), CDeterministicMNList::GetValidMNsCount(), and CDeterministicMNList::PoSeDecrease().
Referenced by BuildNewListFromBlock().
GetListAtChainTip()
CDeterministicMNList CDeterministicMNManager::GetListAtChainTip ()
Definition at line 831 of file deterministicmns.cpp.
References cs, GetListForBlock(), LOCK, and tipBlockHash.
Referenced by CMasternodeMan::AddDeterministicMasternodes(), CTxMemPool::addUnchecked(), CMasternodeMan::CountEnabled(), CMasternodeMan::CountMasternodes(), CTxMemPool::existsProviderTxConflict(), CMasternodeMan::Find(), CMasternodeMan::GetFullMasternodeMap(), CMasternodeMan::GetMasternodeInfo(), CMasternodeMan::GetMasternodeScores(), GetNextMasternodeForPayment(), GetRequiredPaymentsStrings(), MasternodeList::GetSelectedDIP3MN(), gobject_vote_alias(), gobject_vote_many(), HasMNCollateralAtChainTip(), HasValidMNCollateralAtChainTip(), CActiveDeterministicMasternodeManager::Init(), CMasternodePayments::IsScheduled(), CActiveLegacyMasternodeManager::ManageStateRemote(), masternodelist(), protx_info(), CGovernanceManager::RemoveInvalidProposalVotes(), CMasternodeMan::RemoveNonDeterministicMasternodes(), CTxMemPool::removeProTxSpentCollateralConflicts(), CMasternodeMan::ToString(), and MasternodeList::updateDIP3List().
GetListForBlock()
CDeterministicMNList CDeterministicMNManager::GetListForBlock (const uint256 & blockHash)
Definition at line 783 of file deterministicmns.cpp.
References CDeterministicMNList::ApplyDiff(), cs, DB_LIST_DIFF, DB_LIST_SNAPSHOT, evoDb, LOCK, mnListsCache, CDeterministicMNListDiff::prevBlockHash, CEvoDB::Read(), CDeterministicMNList::SetBlockHash(), and CDeterministicMNList::SetHeight().
Referenced by BuildNewListFromBlock(), BuildSimplifiedMNListDiff(), CheckProRegTx(), CheckProUpRegTx(), CheckProUpRevTx(), CheckProUpServTx(), ComputeBlockVersion(), llmq::CLLMQUtils::GetAllQuorumMembers(), CMasternodePayments::GetBlockTxOuts(), GetListAtChainTip(), GetRequiredPaymentsStrings(), ProcessBlock(), protx_list(), CActiveDeterministicMasternodeManager::UpdatedBlockTip(), and CMasternode::UpdateLastPaid().
GetSpork15Value()
int64_t CDeterministicMNManager::GetSpork15Value () private
Definition at line 851 of file deterministicmns.cpp.
References CSporkManager::GetSporkValue(), SPORK_15_DETERMINISTIC_MNS_ENABLED, and sporkManager.
Referenced by IsDeterministicMNsSporkActive(), ProcessBlock(), and UndoBlock().
HandleQuorumCommitment()
void CDeterministicMNManager::HandleQuorumCommitment (llmq::CFinalCommitment & qc, CDeterministicMNList & mnList, bool debugLogs)
Definition at line 746 of file deterministicmns.cpp.
References CDeterministicMNList::CalcPenalty(), llmq::CLLMQUtils::GetAllQuorumMembers(), CDeterministicMNList::HasMN(), llmq::CFinalCommitment::llmqType, CDeterministicMNList::PoSePunish(), llmq::CFinalCommitment::quorumHash, and llmq::CFinalCommitment::validMembers.
Referenced by BuildNewListFromBlock().
HasMNCollateralAtChainTip()
bool CDeterministicMNManager::HasMNCollateralAtChainTip (const COutPoint & outpoint)
Definition at line 844 of file deterministicmns.cpp.
References GetListAtChainTip().
Referenced by CWallet::AddToWallet(), CWallet::AutoLockMasternodeCollaterals(), and CWallet::ListProTxCoins().
HasValidMNCollateralAtChainTip()
bool CDeterministicMNManager::HasValidMNCollateralAtChainTip (const COutPoint & outpoint)
Definition at line 837 of file deterministicmns.cpp.
References GetListAtChainTip().
Referenced by CMasternodeMan::FindRandomNotInVec(), and CMasternodeMan::Has().
IsDeterministicMNsSporkActive()
bool CDeterministicMNManager::IsDeterministicMNsSporkActive (int nHeight = -1)
Definition at line 878 of file deterministicmns.cpp.
References cs, GetSpork15Value(), LOCK, and tipHeight.
Referenced by CMasternodeMan::Add(), CMasternodeMan::AddDeterministicMasternodes(), CMasternodeMan::AskForMN(), CMasternodeMan::Check(), CMasternodeMan::CheckAndRemove(), CMasternodePayments::CheckAndRemove(), CMasternodeMan::CheckMasternode(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CheckProRegTx(), CheckProUpRegTx(), CMasternodeMan::CheckSameAddr(), CPrivateSendQueue::CheckSignature(), CTxLockVote::CheckSignature(), CPrivateSendBroadcastTx::CheckSignature(), CMasternodeMan::CheckVerifyRequestAddr(), ComputeBlockVersion(), CMasternodeMan::CountEnabled(), CMasternodeMan::CountMasternodes(), CMasternodeMan::DoFullVerificationStep(), CGovernanceManager::DoMaintenance(), CMasternodeMan::DsegUpdate(), FillBlockPayments(), CMasternodeMan::Find(), CMasternodeMan::FindRandomNotInVec(), getblocktemplate(), CMasternodePayments::GetBlockTxOuts(), CMasternodeMan::GetFullMasternodeMap(), CMasternodeMan::GetMasternodeInfo(), CMasternodeMan::GetMasternodeScores(), CMasternodePayments::GetMasternodeTxOuts(), CGovernanceManager::GetMinVoteTime(), GetNextMasternodeForPayment(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetRequiredPaymentsStrings(), gobject_submit(), gobject_vote_alias(), gobject_vote_conf(), gobject_vote_many(), CMasternodeMan::Has(), CActiveDeterministicMasternodeManager::Init(), IsBlockPayeeValid(), CMasternodePayments::IsScheduled(), CMasternodePayments::IsTransactionValid(), CGovernanceVote::IsValid(), CTxLockVote::IsValid(), CGovernanceObject::IsValidLocally(), CActiveLegacyMasternodeManager::ManageState(), CActiveLegacyMasternodeManager::ManageStateInitial(), CActiveLegacyMasternodeManager::ManageStateRemote(), masternode_count(), masternode_status(), masternodelist(), CMasternodeMan::PopScheduledMnbRequestConnection(), CMasternodeMan::PoSeBan(), CMasternodePayments::ProcessBlock(), ProcessGetData(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), ProcessMessage(), CMasternodeMan::ProcessPendingMnbRequests(), CMasternodeMan::ProcessPendingMnvRequests(), CMasternodeSync::ProcessTick(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), CMasternodePaymentVote::Relay(), CMasternodeMan::RemoveNonDeterministicMasternodes(), CActiveLegacyMasternodeManager::SendMasternodePing(), CMasternodeMan::SendVerifyReply(), CTxLockVote::SerializationOp(), CMasternodeMan::SetMasternodeLastPing(), CPrivateSendQueue::Sign(), CTxLockVote::Sign(), CPrivateSendBroadcastTx::Sign(), CMasternodeSync::SwitchToNextAsset(), CMasternodeMan::ToString(), CActiveDeterministicMasternodeManager::UpdatedBlockTip(), CMasternodePayments::UpdatedBlockTip(), CGovernanceManager::UpdatedBlockTip(), MasternodeList::updateDIP3List(), CMasternode::UpdateLastPaid(), CMasternodeMan::UpdateLastSentinelPingTime(), CMasternodePayments::UpdateLastVote(), MasternodeList::updateMyNodeList(), MasternodeList::updateNodeList(), CInstantSend::Vote(), and VoteWithMasternodeList().
IsProTxWithCollateral()
bool CDeterministicMNManager::IsProTxWithCollateral (const CTransactionRef & tx, uint32_t n)
Definition at line 856 of file deterministicmns.cpp.
References COIN, CProRegTx::collateralOutpoint, GetTxPayload(), COutPoint::hash, base_blob< BITS >::IsNull(), COutPoint::n, and TRANSACTION_PROVIDER_REGISTER.
Referenced by CWallet::AddToWallet(), CWallet::AutoLockMasternodeCollaterals(), and CWallet::ListProTxCoins().
ProcessBlock()
bool CDeterministicMNManager::ProcessBlock (const CBlock & block, const CBlockIndex * pindex, CValidationState & state)
Definition at line 448 of file deterministicmns.cpp.
References AssertLockHeld, CDeterministicMNList::BuildDiff(), BuildNewListFromBlock(), CleanupCache(), cs, cs_main, DB_LIST_DIFF, DB_LIST_SNAPSHOT, Consensus::DEPLOYMENT_DIP0003, evoDb, CDeterministicMNList::GetAllMNsCount(), CBlockIndex::GetBlockHash(), CBlockHeader::GetHash(), CDeterministicMNList::GetHeight(), GetListForBlock(), GetSpork15Value(), LOCK, LogPrintf, CBlockIndex::nHeight, Params(), CBlockIndex::pprev, CDeterministicMNList::SetBlockHash(), CDeterministicMNList::SetHeight(), SNAPSHOT_LIST_PERIOD, THRESHOLD_ACTIVE, versionbitscache, VersionBitsState(), and CEvoDB::Write().
Referenced by ProcessSpecialTxsInBlock().
UndoBlock()
bool CDeterministicMNManager::UndoBlock (const CBlock & block, const CBlockIndex * pindex)
Definition at line 491 of file deterministicmns.cpp.
References cs, DB_LIST_DIFF, DB_LIST_SNAPSHOT, CEvoDB::Erase(), evoDb, CBlockHeader::GetHash(), GetSpork15Value(), LOCK, LogPrintf, mnListsCache, and CBlockIndex::nHeight.
Referenced by UndoSpecialTxsInBlock().
UpdatedBlockTip()
void CDeterministicMNManager::UpdatedBlockTip (const CBlockIndex * pindex)
Definition at line 509 of file deterministicmns.cpp.
References cs, CBlockIndex::GetBlockHash(), LOCK, CBlockIndex::nHeight, tipBlockHash, and tipHeight.
Referenced by CDSNotificationInterface::UpdatedBlockTip().
Member Data Documentation
cs
CCriticalSection CDeterministicMNManager::cs
Definition at line 457 of file deterministicmns.h.
Referenced by BuildNewListFromBlock(), BuildSimplifiedMNListDiff(), CalcCbTxMerkleRootMNList(), CleanupCache(), GetListAtChainTip(), GetListForBlock(), IsDeterministicMNsSporkActive(), ProcessBlock(), UndoBlock(), and UpdatedBlockTip().
evoDb
CEvoDB& CDeterministicMNManager::evoDb private
Definition at line 460 of file deterministicmns.h.
Referenced by GetListForBlock(), ProcessBlock(), and UndoBlock().
LISTS_CACHE_SIZE
const int CDeterministicMNManager::LISTS_CACHE_SIZE = 576 static private
Definition at line 454 of file deterministicmns.h.
Referenced by CleanupCache().
mnListsCache
std::map<uint256, CDeterministicMNList> CDeterministicMNManager::mnListsCache private
Definition at line 462 of file deterministicmns.h.
Referenced by CleanupCache(), GetListForBlock(), and UndoBlock().
SNAPSHOT_LIST_PERIOD
const int CDeterministicMNManager::SNAPSHOT_LIST_PERIOD = 576 static private
Definition at line 453 of file deterministicmns.h.
Referenced by ProcessBlock().
tipBlockHash
uint256 CDeterministicMNManager::tipBlockHash private
Definition at line 464 of file deterministicmns.h.
Referenced by GetListAtChainTip(), and UpdatedBlockTip().
tipHeight
int CDeterministicMNManager::tipHeight {-1} private
Definition at line 463 of file deterministicmns.h.
Referenced by IsDeterministicMNsSporkActive(), and UpdatedBlockTip().
The documentation for this class was generated from the following files:
src/evo/deterministicmns.h
src/evo/deterministicmns.cpp
Released under the MIT license