Dash Core: COutPoint Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
COutPoint Class Reference
An outpoint - a combination of a transaction hash and an index n into its vout.
#include <transaction.h>
Public Member Functions
COutPoint ()
COutPoint (uint256 hashIn, uint32_t nIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
void SetNull ()
bool IsNull () const
std::string ToString () const
std::string ToStringShort () const
Public Attributes
uint256 hash
uint32_t n
ADD_SERIALIZE_METHODS
Friends
bool operator< (const COutPoint &a, const COutPoint &b)
bool operator== (const COutPoint &a, const COutPoint &b)
bool operator!= (const COutPoint &a, const COutPoint &b)
Detailed Description
An outpoint - a combination of a transaction hash and an index n into its vout.
Definition at line 26 of file transaction.h.
Constructor & Destructor Documentation
COutPoint() [1/2]
COutPoint::COutPoint () inline
Definition at line 32 of file transaction.h.
References SetNull().
COutPoint() [2/2]
COutPoint::COutPoint (uint256 hashIn, uint32_t nIn) inline
Definition at line 33 of file transaction.h.
References hash, and n.
Member Function Documentation
IsNull()
bool COutPoint::IsNull () const inline
Definition at line 44 of file transaction.h.
References hash, base_blob< BITS >::IsNull(), and n.
Referenced by CMasternodeMan::DoFullVerificationStep(), CWallet::GetBudgetSystemCollateralTX(), CGovernanceManager::GetCurrentVotes(), CMasternodeMan::ProcessVerifyReply(), CTxMemPool::removeUnchecked(), and CTxIn::ToString().
SerializationOp()
template<typename Stream , typename Operation > void COutPoint::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 38 of file transaction.h.
References hash, n, and READWRITE.
SetNull()
void COutPoint::SetNull () inline
Definition at line 43 of file transaction.h.
References hash, n, and base_blob< BITS >::SetNull().
Referenced by COutPoint(), and CActiveDeterministicMasternodeManager::UpdatedBlockTip().
ToString()
std::string COutPoint::ToString () const
Definition at line 12 of file transaction.cpp.
References hash, n, strprintf, and base_blob< BITS >::ToString().
Referenced by CTxLockVote::CheckSignature(), CGovernanceObject::RemoveInvalidProposalVotes(), and CTxIn::ToString().
ToStringShort()
std::string COutPoint::ToStringShort () const
Definition at line 17 of file transaction.cpp.
References hash, n, strprintf, and base_blob< BITS >::ToString().
Referenced by CMasternodeMan::AskForMN(), CMasternode::Check(), CMasternodePing::CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), CMasternodePing::CheckSignature(), CGovernanceVote::CheckSignature(), CMasternodePaymentVote::CheckSignature(), CTxLockVote::CheckSignature(), GetNextMasternodeForPayment(), CGovernanceObject::GetSignatureMessage(), gobject_get(), gobject_submit(), CGovernanceVote::IsValid(), CMasternodePaymentVote::IsValid(), CTxLockVote::IsValid(), CGovernanceObject::IsValidLocally(), CPrivateSendClientSession::JoinExistingQueue(), ListObjects(), masternode_status(), masternodebroadcast(), CGovernanceManager::MasternodeRateCheck(), CMasternodePayments::ProcessBlock(), ProcessMessage(), CInstantSend::ProcessNewTxLockVote(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), CGovernanceObject::ProcessVote(), CGovernanceManager::ProcessVote(), CActiveLegacyMasternodeManager::SendMasternodePing(), CGovernanceVote::Sign(), CMasternodePaymentVote::Sign(), CGovernanceObject::Sign(), CTxLockVote::Sign(), CPrivateSendClientSession::SignFinalTransaction(), CMasternodePing::SimpleCheck(), CMasternodeBroadcast::SimpleCheck(), CPrivateSendClientSession::StartNewQueue(), CMasternodeMan::SyncSingle(), CProRegTx::ToString(), CGovernanceVote::ToString(), CMasternodePaymentVote::ToString(), CDeterministicMN::ToString(), CPrivateSendQueue::ToString(), CMasternodeBroadcast::Update(), CMasternode::UpdateLastPaid(), CInstantSend::UpdateVotedOutpoints(), CInstantSend::Vote(), and voteraw().
Friends And Related Function Documentation
operator!=
bool operator!= (const COutPoint & a, const COutPoint & b) friend
Definition at line 57 of file transaction.h.
operator<
bool operator< (const COutPoint & a, const COutPoint & b) friend
Definition at line 46 of file transaction.h.
operator==
bool operator== (const COutPoint & a, const COutPoint & b) friend
Definition at line 52 of file transaction.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
COutPoint::ADD_SERIALIZE_METHODS
Definition at line 35 of file transaction.h.
hash
uint256 COutPoint::hash
Definition at line 29 of file transaction.h.
Referenced by CWallet::AbandonTransaction(), CTxMemPool::addAddressIndex(), CTxMemPool::addSpentIndex(), CTxMemPool::addUnchecked(), ApplyTxInUndo(), CDeterministicMNManager::BuildNewListFromBlock(), CTxMemPool::check(), CheckProRegTx(), CWallet::CommitTransaction(), ConnectBlock(), COutPoint(), DisconnectBlock(), entryToJSON(), CTxMemPool::exists(), CTxMemPool::existsProviderTxConflict(), CMasternodeMan::Find(), CWallet::GetAddressGroupings(), getblocktemplate(), CCoinsViewMemPool::GetCoin(), CWallet::GetDebit(), WalletModel::getOutputs(), CWallet::GetRealOutpointPrivateSendRounds(), GetUTXOStats(), CWallet::IsAllFromMe(), CWallet::IsDenominated(), CWallet::IsMine(), IsNull(), CDeterministicMNManager::IsProTxWithCollateral(), WalletModel::isSpent(), CWalletTx::IsTrusted(), WalletModel::listCoins(), listlockunspent(), CWallet::LoadToWallet(), CWallet::LockCoin(), CWallet::MarkConflicted(), CompareInputBIP69::operator()(), ProcessMessage(), CTxMemPool::removeForReorg(), CTxMemPool::removeProTxConflicts(), CTxMemPool::removeUnchecked(), CWallet::SelectCoins(), SerializationOp(), SetNull(), CWallet::SyncTransaction(), CProRegTx::ToJson(), CDeterministicMN::ToJson(), ToString(), ToStringShort(), CTxMemPool::TrimToSize(), TxInErrorToJSON(), TxToJSON(), TxToUniv(), and CWallet::UnlockCoin().
n
uint32_t COutPoint::n
Definition at line 30 of file transaction.h.
Referenced by AccessByTxid(), CTxMemPool::addAddressIndex(), CTxMemPool::addSpentIndex(), CDeterministicMNManager::BuildNewListFromBlock(), CTxMemPool::check(), CheckProRegTx(), ConnectBlock(), COutPoint(), DisconnectBlock(), CTxMemPool::exists(), CWallet::GetAddressGroupings(), CCoinsViewMemPool::GetCoin(), CWallet::GetDebit(), WalletModel::getOutputs(), CWallet::GetRealOutpointPrivateSendRounds(), GetUTXOStats(), CWallet::IsAllFromMe(), CWallet::IsDenominated(), CWallet::IsMine(), IsNull(), CDeterministicMNManager::IsProTxWithCollateral(), WalletModel::isSpent(), CWalletTx::IsTrusted(), WalletModel::listCoins(), listlockunspent(), CompareInputBIP69::operator()(), CWallet::SelectCoins(), SerializationOp(), SetNull(), CProRegTx::ToJson(), CDeterministicMN::ToJson(), ToString(), ToStringShort(), TxInErrorToJSON(), TxToJSON(), TxToUniv(), and CCoinsViewDB::Upgrade().
The documentation for this class was generated from the following files:
src/primitives/transaction.h
src/primitives/transaction.cpp
Released under the MIT license