Dash Core: CMasternodePaymentVote Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CMasternodePaymentVote Class Reference
#include <masternode-payments.h>
Public Member Functions
CMasternodePaymentVote ()
CMasternodePaymentVote (COutPoint outpoint, int nBlockHeight, CScript payee)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
uint256 GetHash () const
uint256 GetSignatureHash () const
bool Sign ()
bool CheckSignature (const CKeyID &keyIDOperator, int nValidationHeight, int &nDos) const
bool IsValid (CNode *pnode, int nValidationHeight, std::string &strError, CConnman &connman) const
void Relay (CConnman &connman) const
bool IsVerified () const
void MarkAsNotVerified ()
std::string ToString () const
Public Attributes
COutPoint masternodeOutpoint
int nBlockHeight
CScript payee
std::vector< unsigned char > vchSig
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 108 of file masternode-payments.h.
Constructor & Destructor Documentation
CMasternodePaymentVote() [1/2]
CMasternodePaymentVote::CMasternodePaymentVote () inline
Definition at line 117 of file masternode-payments.h.
CMasternodePaymentVote() [2/2]
CMasternodePaymentVote::CMasternodePaymentVote (COutPoint outpoint, int nBlockHeight, CScript payee) inline
Definition at line 124 of file masternode-payments.h.
Member Function Documentation
CheckSignature()
bool CMasternodePaymentVote::CheckSignature (const CKeyID & keyIDOperator, int nValidationHeight, int & nDos) const
Definition at line 1104 of file masternode-payments.cpp.
References error(), GetSignatureHash(), CMasternodeSync::IsMasternodeListSynced(), CSporkManager::IsSporkActive(), masternodeOutpoint, masternodeSync, nBlockHeight, payee, ScriptToAsmStr(), SPORK_6_NEW_SIGS, sporkManager, COutPoint::ToStringShort(), vchSig, CHashSigner::VerifyHash(), and CMessageSigner::VerifyMessage().
GetHash()
uint256 CMasternodePaymentVote::GetHash () const
Definition at line 538 of file masternode-payments.cpp.
References CHashWriter::GetHash(), masternodeOutpoint, nBlockHeight, payee, PROTOCOL_VERSION, and SER_GETHASH.
Referenced by CMasternodePayments::AddOrUpdatePaymentVote(), CMasternodeBlockPayees::AddPayee(), and Relay().
GetSignatureHash()
uint256 CMasternodePaymentVote::GetSignatureHash () const
Definition at line 549 of file masternode-payments.cpp.
References SerializeHash().
Referenced by CheckSignature(), and Sign().
IsValid()
bool CMasternodePaymentVote::IsValid (CNode * pnode, int nValidationHeight, std::string & strError, CConnman & connman) const
Definition at line 891 of file masternode-payments.cpp.
References CMasternodeMan::AskForMN(), cs_main, fMasternodeMode, CNode::GetId(), CMasternodeMan::GetMasternodeInfo(), CMasternodeMan::GetMasternodeRank(), CMasternodePayments::GetMinMasternodePaymentsProto(), CMasternodeSync::IsMasternodeListSynced(), LOCK, LogPrint, LogPrintf, masternodeOutpoint, masternodeSync, MIN_MASTERNODE_PAYMENT_PROTO_VERSION_1, Misbehaving(), mnodeman, mnpayments, MNPAYMENTS_SIGNATURES_TOTAL, nBlockHeight, masternode_info_t::nProtocolVersion, strprintf, and COutPoint::ToStringShort().
IsVerified()
bool CMasternodePaymentVote::IsVerified () const inline
Definition at line 152 of file masternode-payments.h.
References vchSig.
MarkAsNotVerified()
void CMasternodePaymentVote::MarkAsNotVerified () inline
Definition at line 153 of file masternode-payments.h.
References vchSig.
Relay()
void CMasternodePaymentVote::Relay (CConnman & connman) const
Definition at line 1088 of file masternode-payments.cpp.
References deterministicMNManager, GetHash(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CMasternodeSync::IsSynced(), LogPrint, masternodeSync, MSG_MASTERNODE_PAYMENT_VOTE, and CConnman::RelayInv().
Referenced by CMasternodePayments::ProcessBlock().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodePaymentVote::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 134 of file masternode-payments.h.
References masternodeOutpoint, nBlockHeight, payee, READWRITE, SER_GETHASH, and vchSig.
Sign()
bool CMasternodePaymentVote::Sign ()
Definition at line 554 of file masternode-payments.cpp.
References activeMasternodeInfo, GetSignatureHash(), CSporkManager::IsSporkActive(), CActiveMasternodeInfo::legacyKeyIDOperator, CActiveMasternodeInfo::legacyKeyOperator, LogPrintf, masternodeOutpoint, nBlockHeight, payee, ScriptToAsmStr(), CHashSigner::SignHash(), CMessageSigner::SignMessage(), SPORK_6_NEW_SIGS, sporkManager, COutPoint::ToStringShort(), vchSig, CHashSigner::VerifyHash(), and CMessageSigner::VerifyMessage().
Referenced by CMasternodePayments::ProcessBlock().
ToString()
std::string CMasternodePaymentVote::ToString () const
Definition at line 1150 of file masternode-payments.cpp.
References masternodeOutpoint, nBlockHeight, payee, ScriptToAsmStr(), COutPoint::ToStringShort(), and vchSig.
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodePaymentVote::ADD_SERIALIZE_METHODS
Definition at line 131 of file masternode-payments.h.
masternodeOutpoint
COutPoint CMasternodePaymentVote::masternodeOutpoint
Definition at line 111 of file masternode-payments.h.
Referenced by CheckSignature(), GetHash(), IsValid(), SerializationOp(), Sign(), ToString(), and CMasternodePayments::UpdateLastVote().
nBlockHeight
int CMasternodePaymentVote::nBlockHeight
Definition at line 113 of file masternode-payments.h.
Referenced by CMasternodePayments::AddOrUpdatePaymentVote(), CMasternodePayments::CheckAndRemove(), CheckSignature(), GetHash(), IsValid(), SerializationOp(), Sign(), ToString(), and CMasternodePayments::UpdateLastVote().
payee
CScript CMasternodePaymentVote::payee
Definition at line 114 of file masternode-payments.h.
Referenced by CMasternodeBlockPayees::AddPayee(), CheckSignature(), GetHash(), SerializationOp(), Sign(), and ToString().
vchSig
std::vector<unsigned char> CMasternodePaymentVote::vchSig
Definition at line 115 of file masternode-payments.h.
Referenced by CheckSignature(), IsVerified(), MarkAsNotVerified(), SerializationOp(), Sign(), and ToString().
The documentation for this class was generated from the following files:
src/masternode-payments.h
src/masternode-payments.cpp
Released under the MIT license