Dash Core: MemPoolConflictRemovalTracker Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
MemPoolConflictRemovalTracker Class Reference
Public Member Functions
MemPoolConflictRemovalTracker (CTxMemPool &_pool)
void NotifyEntryRemoved (CTransactionRef txRemoved, MemPoolRemovalReason reason)
~MemPoolConflictRemovalTracker ()
Private Attributes
std::vector< CTransactionRef > conflictedTxs
CTxMemPool & pool
Detailed Description
Definition at line 185 of file validation.cpp.
Constructor & Destructor Documentation
MemPoolConflictRemovalTracker()
MemPoolConflictRemovalTracker::MemPoolConflictRemovalTracker (CTxMemPool & _pool) inline
Definition at line 192 of file validation.cpp.
References NotifyEntryRemoved(), CTxMemPool::NotifyEntryRemoved, and pool.
~MemPoolConflictRemovalTracker()
MemPoolConflictRemovalTracker::~MemPoolConflictRemovalTracker () inline
Definition at line 202 of file validation.cpp.
References conflictedTxs, GetMainSignals(), NotifyEntryRemoved(), CTxMemPool::NotifyEntryRemoved, pool, CMainSignals::SYNC_TRANSACTION_NOT_IN_BLOCK, and CMainSignals::SyncTransaction.
Member Function Documentation
NotifyEntryRemoved()
void MemPoolConflictRemovalTracker::NotifyEntryRemoved (CTransactionRef txRemoved, MemPoolRemovalReason reason) inline
Definition at line 196 of file validation.cpp.
References CONFLICT, and conflictedTxs.
Referenced by MemPoolConflictRemovalTracker(), and ~MemPoolConflictRemovalTracker().
Member Data Documentation
conflictedTxs
std::vector<CTransactionRef> MemPoolConflictRemovalTracker::conflictedTxs private
Definition at line 188 of file validation.cpp.
Referenced by NotifyEntryRemoved(), and ~MemPoolConflictRemovalTracker().
pool
CTxMemPool& MemPoolConflictRemovalTracker::pool private
Definition at line 189 of file validation.cpp.
Referenced by MemPoolConflictRemovalTracker(), and ~MemPoolConflictRemovalTracker().
The documentation for this class was generated from the following file:
src/validation.cpp
Released under the MIT license