Dash Core: CPrivateSendClientManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CPrivateSendClientManager Class Reference
Used to keep track of current status of mixing pool.
#include <privatesend-client.h>
Public Member Functions
CPrivateSendClientManager ()
void ProcessMessage (CNode *pfrom, const std::string &strCommand, CDataStream &vRecv, CConnman &connman)
bool IsDenomSkipped (const CAmount &nDenomValue)
void AddSkippedDenom (const CAmount &nDenomValue)
void ClearSkippedDenominations ()
void SetMinBlocksToWait (int nMinBlocksToWaitIn)
void ResetPool ()
std::string GetStatuses ()
std::string GetSessionDenoms ()
bool GetMixingMasternodesInfo (std::vector< masternode_info_t > &vecMnInfoRet) const
bool DoAutomaticDenominating (CConnman &connman, bool fDryRun=false)
Passively run mixing in the background according to the configuration in settings.
void CheckTimeout ()
void ProcessPendingDsaRequest (CConnman &connman)
void AddUsedMasternode (const COutPoint &outpointMn)
masternode_info_t GetNotUsedMasternode ()
void UpdatedSuccessBlock ()
void UpdatedBlockTip (const CBlockIndex *pindex)
void DoMaintenance (CConnman &connman)
Public Member Functions inherited from CPrivateSendBaseManager
CPrivateSendBaseManager ()
int GetQueueSize () const
bool GetQueueItemAndTry (CPrivateSendQueue &dsqRet)
Public Attributes
int nPrivateSendSessions
int nPrivateSendRounds
int nPrivateSendAmount
int nLiquidityProvider
bool fEnablePrivateSend
bool fPrivateSendMultiSession
int nCachedNumBlocks
bool fCreateAutoBackups
Private Member Functions
bool WaitForAnotherBlock ()
bool CheckAutomaticBackup ()
Private Attributes
std::vector< COutPoint > vecMasternodesUsed
std::vector< CAmount > vecDenominationsSkipped
std::deque< CPrivateSendClientSession > deqSessions
CCriticalSection cs_deqsessions
int nCachedLastSuccessBlock
int nMinBlocksToWait
std::string strAutoDenomResult
int nCachedBlockHeight
Additional Inherited Members
Protected Member Functions inherited from CPrivateSendBaseManager
void SetNull ()
void CheckQueue ()
Protected Attributes inherited from CPrivateSendBaseManager
CCriticalSection cs_vecqueue
std::vector< CPrivateSendQueue > vecPrivateSendQueue
Detailed Description
Used to keep track of current status of mixing pool.
Definition at line 172 of file privatesend-client.h.
Constructor & Destructor Documentation
CPrivateSendClientManager()
CPrivateSendClientManager::CPrivateSendClientManager () inline
Definition at line 207 of file privatesend-client.h.
Member Function Documentation
AddSkippedDenom()
void CPrivateSendClientManager::AddSkippedDenom (const CAmount & nDenomValue)
Definition at line 707 of file privatesend-client.cpp.
References vecDenominationsSkipped.
Referenced by CPrivateSendClientSession::CreateDenominated().
AddUsedMasternode()
void CPrivateSendClientManager::AddUsedMasternode (const COutPoint & outpointMn)
Definition at line 988 of file privatesend-client.cpp.
References vecMasternodesUsed.
Referenced by CPrivateSendClientSession::JoinExistingQueue(), and CPrivateSendClientSession::StartNewQueue().
CheckAutomaticBackup()
bool CPrivateSendClientManager::CheckAutomaticBackup () private
Definition at line 723 of file privatesend-client.cpp.
References _(), AutoBackupWallet(), fCreateAutoBackups, fEnablePrivateSend, LogPrint, LogPrintf, CWallet::nKeysLeftSinceAutoBackup, nWalletBackups, PRIVATESEND_KEYS_THRESHOLD_STOP, PRIVATESEND_KEYS_THRESHOLD_WARNING, pwalletMain, strAutoDenomResult, and strprintf.
Referenced by DoAutomaticDenominating().
CheckTimeout()
void CPrivateSendClientManager::CheckTimeout ()
Definition at line 448 of file privatesend-client.cpp.
References _(), CPrivateSendBaseManager::CheckQueue(), cs_deqsessions, deqSessions, fEnablePrivateSend, fMasternodeMode, LOCK, and strAutoDenomResult.
Referenced by DoMaintenance().
ClearSkippedDenominations()
void CPrivateSendClientManager::ClearSkippedDenominations () inline
Definition at line 229 of file privatesend-client.h.
References vecDenominationsSkipped.
Referenced by CWallet::CreateTransaction().
DoAutomaticDenominating()
bool CPrivateSendClientManager::DoAutomaticDenominating (CConnman & connman, bool fDryRun = false)
Passively run mixing in the background according to the configuration in settings.
Definition at line 935 of file privatesend-client.cpp.
References _(), CheckAutomaticBackup(), CMasternodeMan::CountEnabled(), cs_deqsessions, deqSessions, fEnablePrivateSend, fMasternodeMode, CCryptoKeyStore::IsLocked(), CMasternodeSync::IsMasternodeListSynced(), LOCK, LogPrint, LogPrintf, masternodeSync, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, nPrivateSendSessions, pwalletMain, strAutoDenomResult, vecMasternodesUsed, and WaitForAnotherBlock().
Referenced by DoMaintenance(), and OverviewPage::privateSendAuto().
DoMaintenance()
void CPrivateSendClientManager::DoMaintenance (CConnman & connman)
Definition at line 1621 of file privatesend-client.cpp.
References CheckTimeout(), DoAutomaticDenominating(), fLiteMode, fMasternodeMode, GetRandInt(), CMasternodeSync::IsBlockchainSynced(), masternodeSync, PRIVATESEND_AUTO_TIMEOUT_MAX, PRIVATESEND_AUTO_TIMEOUT_MIN, ProcessPendingDsaRequest(), and ShutdownRequested().
Referenced by AppInitMain().
GetMixingMasternodesInfo()
bool CPrivateSendClientManager::GetMixingMasternodesInfo (std::vector< masternode_info_t > & vecMnInfoRet) const
Definition at line 377 of file privatesend-client.cpp.
References cs_deqsessions, deqSessions, and LOCK.
Referenced by getpoolinfo(), and CMasternodeMan::ProcessMasternodeConnections().
GetNotUsedMasternode()
masternode_info_t CPrivateSendClientManager::GetNotUsedMasternode ()
Definition at line 993 of file privatesend-client.cpp.
References CMasternodeMan::FindRandomNotInVec(), MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, and vecMasternodesUsed.
Referenced by CPrivateSendClientSession::StartNewQueue().
GetSessionDenoms()
std::string CPrivateSendClientManager::GetSessionDenoms ()
Definition at line 360 of file privatesend-client.cpp.
References cs_deqsessions, deqSessions, CPrivateSend::GetDenominationsToString(), and LOCK.
Referenced by OverviewPage::privateSendStatus().
GetStatuses()
std::string CPrivateSendClientManager::GetStatuses ()
Definition at line 348 of file privatesend-client.cpp.
References cs_deqsessions, deqSessions, LOCK, and WaitForAnotherBlock().
Referenced by getpoolinfo(), and OverviewPage::privateSendStatus().
IsDenomSkipped()
bool CPrivateSendClientManager::IsDenomSkipped (const CAmount & nDenomValue)
Definition at line 702 of file privatesend-client.cpp.
References vecDenominationsSkipped.
Referenced by CPrivateSendClientSession::CreateDenominated().
ProcessMessage()
void CPrivateSendClientManager::ProcessMessage (CNode * pfrom, const std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 24 of file privatesend-client.cpp.
References masternode_info_t::addr, CMasternodeMan::AllowMixing(), CMasternodeMan::AskForMN(), masternode_info_t::blsPubKeyOperator, CheckDiskSpace(), CMasternodeMan::CountMasternodes(), cs_deqsessions, CPrivateSendBaseManager::cs_vecqueue, deqSessions, NetMsgType::DSCOMPLETE, NetMsgType::DSFINALTX, NetMsgType::DSQUEUE, NetMsgType::DSSTATUSUPDATE, fEnablePrivateSend, fLiteMode, fMasternodeMode, CMasternodeMan::GetMasternodeInfo(), CNode::GetSendVersion(), CNode::id, CMasternodeSync::IsBlockchainSynced(), masternode_info_t::legacyKeyIDOperator, LOCK, LogPrint, LogPrintf, masternodeSync, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, CMasternodeMan::nDsqCount, masternode_info_t::nLastDsq, CNode::nVersion, masternode_info_t::outpoint, POOL_STATE_QUEUE, CConnman::PushMessage(), NetMsgType::REJECT, REJECT_OBSOLETE, ResetPool(), strprintf, CService::ToString(), TRY_LOCK, and CPrivateSendBaseManager::vecPrivateSendQueue.
Referenced by ProcessMessage().
ProcessPendingDsaRequest()
void CPrivateSendClientManager::ProcessPendingDsaRequest (CConnman & connman)
Definition at line 1165 of file privatesend-client.cpp.
References _(), cs_deqsessions, deqSessions, LOCK, and strAutoDenomResult.
Referenced by DoMaintenance().
ResetPool()
void CPrivateSendClientManager::ResetPool ()
Definition at line 245 of file privatesend-client.cpp.
References cs_deqsessions, deqSessions, LOCK, nCachedLastSuccessBlock, and vecMasternodesUsed.
Referenced by PrepareShutdown(), OverviewPage::privateSendReset(), ProcessMessage(), and OverviewPage::togglePrivateSend().
SetMinBlocksToWait()
void CPrivateSendClientManager::SetMinBlocksToWait (int nMinBlocksToWaitIn) inline
Definition at line 231 of file privatesend-client.h.
References nMinBlocksToWait.
Referenced by AppInitMain().
UpdatedBlockTip()
void CPrivateSendClientManager::UpdatedBlockTip (const CBlockIndex * pindex)
Definition at line 1615 of file privatesend-client.cpp.
References LogPrint, nCachedBlockHeight, and CBlockIndex::nHeight.
Referenced by CDSNotificationInterface::UpdatedBlockTip().
UpdatedSuccessBlock()
void CPrivateSendClientManager::UpdatedSuccessBlock ()
Definition at line 696 of file privatesend-client.cpp.
References fMasternodeMode, nCachedBlockHeight, and nCachedLastSuccessBlock.
Referenced by CPrivateSendClientSession::CompletedTransaction(), CPrivateSendClientSession::CreateDenominated(), and CPrivateSendClientSession::MakeCollateralAmounts().
WaitForAnotherBlock()
bool CPrivateSendClientManager::WaitForAnotherBlock () private
Definition at line 712 of file privatesend-client.cpp.
References fPrivateSendMultiSession, CMasternodeSync::IsMasternodeListSynced(), masternodeSync, nCachedBlockHeight, nCachedLastSuccessBlock, and nMinBlocksToWait.
Referenced by DoAutomaticDenominating(), and GetStatuses().
Member Data Documentation
cs_deqsessions
CCriticalSection CPrivateSendClientManager::cs_deqsessions mutable private
Definition at line 182 of file privatesend-client.h.
Referenced by CheckTimeout(), DoAutomaticDenominating(), GetMixingMasternodesInfo(), GetSessionDenoms(), GetStatuses(), ProcessMessage(), ProcessPendingDsaRequest(), and ResetPool().
deqSessions
std::deque<CPrivateSendClientSession> CPrivateSendClientManager::deqSessions private
Definition at line 181 of file privatesend-client.h.
Referenced by CheckTimeout(), DoAutomaticDenominating(), GetMixingMasternodesInfo(), GetSessionDenoms(), GetStatuses(), ProcessMessage(), ProcessPendingDsaRequest(), and ResetPool().
fCreateAutoBackups
bool CPrivateSendClientManager::fCreateAutoBackups
Definition at line 205 of file privatesend-client.h.
Referenced by CheckAutomaticBackup(), and OverviewPage::OverviewPage().
fEnablePrivateSend
bool CPrivateSendClientManager::fEnablePrivateSend
Definition at line 201 of file privatesend-client.h.
Referenced by AppInitMain(), CheckAutomaticBackup(), CheckTimeout(), OverviewPage::DisablePrivateSendCompletely(), DoAutomaticDenominating(), CWallet::NewKeyPool(), OverviewPage::OverviewPage(), PrepareShutdown(), OverviewPage::privateSendStatus(), ProcessMessage(), and OverviewPage::togglePrivateSend().
fPrivateSendMultiSession
bool CPrivateSendClientManager::fPrivateSendMultiSession
Definition at line 202 of file privatesend-client.h.
Referenced by AppInitMain(), CPrivateSendClientSession::DoAutomaticDenominating(), OptionsModel::Init(), OptionsModel::setData(), and WaitForAnotherBlock().
nCachedBlockHeight
int CPrivateSendClientManager::nCachedBlockHeight private
Definition at line 189 of file privatesend-client.h.
Referenced by UpdatedBlockTip(), UpdatedSuccessBlock(), and WaitForAnotherBlock().
nCachedLastSuccessBlock
int CPrivateSendClientManager::nCachedLastSuccessBlock private
Definition at line 184 of file privatesend-client.h.
Referenced by ResetPool(), UpdatedSuccessBlock(), and WaitForAnotherBlock().
nCachedNumBlocks
int CPrivateSendClientManager::nCachedNumBlocks
Definition at line 204 of file privatesend-client.h.
Referenced by OptionsDialog::on_okButton_clicked(), OverviewPage::privateSendStatus(), and OverviewPage::togglePrivateSend().
nLiquidityProvider
int CPrivateSendClientManager::nLiquidityProvider
Definition at line 200 of file privatesend-client.h.
Referenced by AppInitMain(), CPrivateSendClientSession::DoAutomaticDenominating(), and CPrivateSendClientSession::SubmitDenominate().
nMinBlocksToWait
int CPrivateSendClientManager::nMinBlocksToWait private
Definition at line 185 of file privatesend-client.h.
Referenced by SetMinBlocksToWait(), and WaitForAnotherBlock().
nPrivateSendAmount
int CPrivateSendClientManager::nPrivateSendAmount
Definition at line 199 of file privatesend-client.h.
Referenced by AppInitMain(), CPrivateSendClientSession::DoAutomaticDenominating(), CWallet::GetNeedsToBeAnonymizedBalance(), OptionsModel::Init(), OptionsModel::setData(), setprivatesendamount(), and OverviewPage::updatePrivateSendProgress().
nPrivateSendRounds
int CPrivateSendClientManager::nPrivateSendRounds
Definition at line 198 of file privatesend-client.h.
Referenced by AppInitMain(), CWalletTx::GetAnonymizedCredit(), CWallet::GetCappedOutpointPrivateSendRounds(), CWallet::GetNormalizedAnonymizedBalance(), OptionsModel::Init(), WalletModel::pollBalanceChanged(), CWallet::SelectCoins(), CWallet::SelectCoinsGroupedByAddresses(), CWallet::SelectCoinsMinConf(), CWallet::SelectPSInOutPairsByDenominations(), OptionsModel::setData(), setprivatesendrounds(), CPrivateSendClientSession::StartNewQueue(), CPrivateSendClientSession::SubmitDenominate(), OverviewPage::updatePrivateSendProgress(), and CoinControlDialog::viewItemChanged().
nPrivateSendSessions
int CPrivateSendClientManager::nPrivateSendSessions
Definition at line 197 of file privatesend-client.h.
Referenced by AppInitMain(), and DoAutomaticDenominating().
strAutoDenomResult
std::string CPrivateSendClientManager::strAutoDenomResult private
Definition at line 186 of file privatesend-client.h.
Referenced by CheckAutomaticBackup(), CheckTimeout(), DoAutomaticDenominating(), and ProcessPendingDsaRequest().
vecDenominationsSkipped
std::vector<CAmount> CPrivateSendClientManager::vecDenominationsSkipped private
Definition at line 178 of file privatesend-client.h.
Referenced by AddSkippedDenom(), ClearSkippedDenominations(), and IsDenomSkipped().
vecMasternodesUsed
std::vector<COutPoint> CPrivateSendClientManager::vecMasternodesUsed private
Definition at line 176 of file privatesend-client.h.
Referenced by AddUsedMasternode(), DoAutomaticDenominating(), GetNotUsedMasternode(), and ResetPool().
The documentation for this class was generated from the following files:
src/privatesend-client.h
src/privatesend-client.cpp
Released under the MIT license