Dash Core: CPrivateSendClientSession Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CPrivateSendClientSession Class Reference
#include <privatesend-client.h>
Public Member Functions
CPrivateSendClientSession ()
void ProcessMessage (CNode *pfrom, const std::string &strCommand, CDataStream &vRecv, CConnman &connman)
void UnlockCoins ()
void ResetPool ()
std::string GetStatus (bool fWaitForBlock)
bool GetMixingMasternodeInfo (masternode_info_t &mnInfoRet) const
bool DoAutomaticDenominating (CConnman &connman, bool fDryRun=false)
Passively run mixing in the background according to the configuration in settings.
bool SubmitDenominate (CConnman &connman)
As a client, submit part of a future mixing transaction to a Masternode to start the process.
bool ProcessPendingDsaRequest (CConnman &connman)
bool CheckTimeout ()
Public Member Functions inherited from CPrivateSendBaseSession
CPrivateSendBaseSession ()
int GetState () const
std::string GetStateString () const
int GetEntriesCount () const
Private Member Functions
bool CreateDenominated (CConnman &connman)
Create denominations.
bool CreateDenominated (const CompactTallyItem &tallyItem, bool fCreateMixingCollaterals, CConnman &connman)
bool MakeCollateralAmounts (CConnman &connman)
Split up large inputs or make fee sized inputs.
bool MakeCollateralAmounts (const CompactTallyItem &tallyItem, bool fTryDenominated, CConnman &connman)
bool JoinExistingQueue (CAmount nBalanceNeedsAnonymized, CConnman &connman)
bool StartNewQueue (CAmount nValueMin, CAmount nBalanceNeedsAnonymized, CConnman &connman)
bool SelectDenominate (std::string &strErrorRet, std::vector< std::pair< CTxDSIn, CTxOut > > &vecPSInOutPairsRet)
step 0: select denominated inputs and txouts
bool PrepareDenominate (int nMinRounds, int nMaxRounds, std::string &strErrorRet, const std::vector< std::pair< CTxDSIn, CTxOut > > &vecPSInOutPairsIn, std::vector< std::pair< CTxDSIn, CTxOut > > &vecPSInOutPairsRet, bool fDryRun=false)
step 1: prepare denominated inputs and outputs
bool SendDenominate (const std::vector< std::pair< CTxDSIn, CTxOut > > &vecPSInOutPairsIn, CConnman &connman)
step 2: send denominated inputs and outputs prepared in step 1
bool CheckPoolStateUpdate (PoolState nStateNew, int nEntriesCountNew, PoolStatusUpdate nStatusUpdate, PoolMessage nMessageID, int nSessionIDNew=0)
Get Masternode updates about the progress of mixing.
void SetState (PoolState nStateNew)
void CheckPool ()
Check for process.
void CompletedTransaction (PoolMessage nMessageID)
bool SignFinalTransaction (const CTransaction &finalTransactionNew, CNode *pnode, CConnman &connman)
As a client, check and sign the final transaction.
void RelayIn (const CPrivateSendEntry &entry, CConnman &connman)
void SetNull ()
Private Attributes
std::vector< COutPoint > vecOutPointLocked
int nEntriesCount
bool fLastEntryAccepted
std::string strLastMessage
std::string strAutoDenomResult
masternode_info_t infoMixingMasternode
CMutableTransaction txMyCollateral
CPendingDsaRequest pendingDsaRequest
CKeyHolderStorage keyHolderStorage
Additional Inherited Members
Public Attributes inherited from CPrivateSendBaseSession
int nSessionDenom
Protected Member Functions inherited from CPrivateSendBaseSession
void SetNull ()
Protected Attributes inherited from CPrivateSendBaseSession
CCriticalSection cs_privatesend
std::vector< CPrivateSendEntry > vecEntries
PoolState nState
int64_t nTimeLastSuccessfulStep
int nSessionID
CMutableTransaction finalMutableTransaction
Detailed Description
Definition at line 84 of file privatesend-client.h.
Constructor & Destructor Documentation
CPrivateSendClientSession()
CPrivateSendClientSession::CPrivateSendClientSession () inline
Definition at line 136 of file privatesend-client.h.
Member Function Documentation
CheckPool()
void CPrivateSendClientSession::CheckPool () private
Check for process.
Definition at line 392 of file privatesend-client.cpp.
References GetTime(), CKeyHolderStorage::KeepAll(), keyHolderStorage, LogPrint, CPrivateSendBaseSession::nState, CPrivateSendBaseSession::nTimeLastSuccessfulStep, POOL_STATE_ERROR, POOL_STATE_SUCCESS, CKeyHolderStorage::ReturnAll(), SetNull(), and UnlockCoins().
Referenced by CheckTimeout().
CheckPoolStateUpdate()
bool CPrivateSendClientSession::CheckPoolStateUpdate (PoolState nStateNew, int nEntriesCountNew, PoolStatusUpdate nStatusUpdate, PoolMessage nMessageID, int nSessionIDNew = 0) private
Get Masternode updates about the progress of mixing.
Definition at line 531 of file privatesend-client.cpp.
References _(), fLastEntryAccepted, fMasternodeMode, CPrivateSend::GetMessageByID(), GetTime(), keyHolderStorage, LogPrintf, nEntriesCount, CPrivateSendBaseSession::nSessionID, CPrivateSendBaseSession::nState, CPrivateSendBaseSession::nTimeLastSuccessfulStep, POOL_STATE_ACCEPTING_ENTRIES, POOL_STATE_ERROR, POOL_STATE_IDLE, POOL_STATE_QUEUE, POOL_STATE_SUCCESS, CKeyHolderStorage::ReturnAll(), SetNull(), SetState(), STATUS_ACCEPTED, STATUS_REJECTED, strAutoDenomResult, strLastMessage, and UnlockCoins().
Referenced by ProcessMessage().
CheckTimeout()
bool CPrivateSendClientSession::CheckTimeout ()
Definition at line 410 of file privatesend-client.cpp.
References CheckPool(), fMasternodeMode, GetTime(), keyHolderStorage, LogPrint, CPrivateSendBaseSession::nState, CPrivateSendBaseSession::nTimeLastSuccessfulStep, POOL_STATE_ERROR, POOL_STATE_IDLE, POOL_STATE_SIGNING, POOL_STATE_SUCCESS, PRIVATESEND_QUEUE_TIMEOUT, PRIVATESEND_SIGNING_TIMEOUT, CKeyHolderStorage::ReturnAll(), SetNull(), SetState(), and UnlockCoins().
CompletedTransaction()
void CPrivateSendClientSession::CompletedTransaction (PoolMessage nMessageID) private
Definition at line 679 of file privatesend-client.cpp.
References fMasternodeMode, CPrivateSend::GetMessageByID(), CKeyHolderStorage::KeepAll(), keyHolderStorage, LogPrintf, MSG_SUCCESS, privateSendClient, CKeyHolderStorage::ReturnAll(), SetNull(), strLastMessage, UnlockCoins(), and CPrivateSendClientManager::UpdatedSuccessBlock().
Referenced by ProcessMessage().
CreateDenominated() [1/2]
bool CPrivateSendClientSession::CreateDenominated (CConnman & connman) private
Create denominations.
Definition at line 1447 of file privatesend-client.cpp.
References cs_main, CWallet::cs_wallet, CWallet::HasCollateralInputs(), LOCK2, LogPrint, LogPrintf, CompactTallyItem::nAmount, pwalletMain, and CWallet::SelectCoinsGroupedByAddresses().
Referenced by DoAutomaticDenominating().
CreateDenominated() [2/2]
bool CPrivateSendClientSession::CreateDenominated (const CompactTallyItem & tallyItem, bool fCreateMixingCollaterals, CConnman & connman) private
Definition at line 1480 of file privatesend-client.cpp.
References _(), CKeyHolderStorage::AddKey(), CPrivateSendClientManager::AddSkippedDenom(), COIN, CWallet::CommitTransaction(), CWallet::CountInputsWithAmount(), CWallet::CreateTransaction(), DENOMS_COUNT_MAX, CCoinControl::destChange, CCoinControl::fAllowOtherInputs, CCoinControl::fAllowWatchOnly, CPrivateSend::GetCollateralAmount(), CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), CPrivateSend::GetMaxCollateralAmount(), CValidationState::GetRejectReason(), CPrivateSend::GetStandardDenominations(), CPrivateSendClientManager::IsDenomSkipped(), CKeyHolderStorage::KeepAll(), LogPrintf, CompactTallyItem::nAmount, ONLY_NONDENOMINATED, privateSendClient, prevector< N, T, Size, Diff >::push_back(), pwalletMain, CKeyHolderStorage::ReturnAll(), CCoinControl::Select(), strAutoDenomResult, strprintf, CBase58Data::ToString(), CompactTallyItem::txdest, CPrivateSendClientManager::UpdatedSuccessBlock(), and CompactTallyItem::vecOutPoints.
DoAutomaticDenominating()
bool CPrivateSendClientSession::DoAutomaticDenominating (CConnman & connman, bool fDryRun = false)
Passively run mixing in the background according to the configuration in settings.
Definition at line 798 of file privatesend-client.cpp.
References _(), COIN, CWallet::CreateCollateralTransaction(), CreateDenominated(), cs_main, CPrivateSendBaseSession::cs_privatesend, CWallet::cs_wallet, fMasternodeMode, CPrivateSendClientManager::fPrivateSendMultiSession, CWallet::GetAnonymizableBalance(), CPrivateSend::GetCollateralAmount(), CWallet::GetDenominatedBalance(), CPrivateSendBaseSession::GetEntriesCount(), CPrivateSend::GetMaxCollateralAmount(), CWallet::GetNeedsToBeAnonymizedBalance(), GetRandInt(), CPrivateSend::GetSmallestDenomination(), CWallet::HasCollateralInputs(), CPrivateSend::IsCollateralValid(), CCryptoKeyStore::IsLocked(), CMasternodeSync::IsMasternodeListSynced(), JoinExistingQueue(), keyHolderStorage, LOCK2, LogPrint, LogPrintf, MakeCollateralAmounts(), masternodeSync, mnodeman, CPrivateSendClientManager::nLiquidityProvider, CPrivateSendClientManager::nPrivateSendAmount, CPrivateSendBaseSession::nSessionID, CPrivateSendBaseSession::nState, POOL_STATE_IDLE, privateSendClient, pwalletMain, CKeyHolderStorage::ReturnAll(), SetNull(), CMasternodeMan::size(), StartNewQueue(), strAutoDenomResult, TRY_LOCK, txMyCollateral, and UnlockCoins().
GetMixingMasternodeInfo()
bool CPrivateSendClientSession::GetMixingMasternodeInfo (masternode_info_t & mnInfoRet) const
Definition at line 371 of file privatesend-client.cpp.
References masternode_info_t::fInfoValid, and infoMixingMasternode.
GetStatus()
std::string CPrivateSendClientSession::GetStatus (bool fWaitForBlock)
Definition at line 288 of file privatesend-client.cpp.
References _(), fLastEntryAccepted, CPrivateSend::GetMaxPoolTransactions(), CMasternodeSync::IsBlockchainSynced(), masternodeSync, nEntriesCount, CPrivateSendBaseSession::nState, POOL_STATE_ACCEPTING_ENTRIES, POOL_STATE_ERROR, POOL_STATE_IDLE, POOL_STATE_QUEUE, POOL_STATE_SIGNING, POOL_STATE_SUCCESS, strAutoDenomResult, strLastMessage, and strprintf.
JoinExistingQueue()
bool CPrivateSendClientSession::JoinExistingQueue (CAmount nBalanceNeedsAnonymized, CConnman & connman) private
Definition at line 998 of file privatesend-client.cpp.
References _(), CConnman::AddPendingMasternode(), masternode_info_t::addr, CPrivateSendClientManager::AddUsedMasternode(), CPrivateSend::GetDenominationsBits(), CPrivateSend::GetDenominationsToString(), CMasternodeMan::GetMasternodeInfo(), CPrivateSendBaseManager::GetQueueItemAndTry(), CPrivateSend::GetStandardDenominations(), GetTime(), infoMixingMasternode, CConnman::IsMasternodeOrDisconnectRequested(), CMasternodePayments::IsScheduled(), LogPrint, LogPrintf, CPrivateSendQueue::masternodeOutpoint, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, mnpayments, CPrivateSendQueue::nDenom, masternode_info_t::nProtocolVersion, CPrivateSendBaseSession::nSessionDenom, CPrivateSendBaseSession::nTimeLastSuccessfulStep, masternode_info_t::outpoint, pendingDsaRequest, POOL_STATE_QUEUE, privateSendClient, pwalletMain, CWallet::SelectPSInOutPairsByDenominations(), SetState(), strAutoDenomResult, CService::ToString(), CPrivateSendQueue::ToString(), COutPoint::ToStringShort(), and txMyCollateral.
Referenced by DoAutomaticDenominating().
MakeCollateralAmounts() [1/2]
bool CPrivateSendClientSession::MakeCollateralAmounts (CConnman & connman) private
Split up large inputs or make fee sized inputs.
Definition at line 1340 of file privatesend-client.cpp.
References LogPrint, LogPrintf, CompactTallyItem::nAmount, pwalletMain, and CWallet::SelectCoinsGroupedByAddresses().
Referenced by DoAutomaticDenominating().
MakeCollateralAmounts() [2/2]
bool CPrivateSendClientSession::MakeCollateralAmounts (const CompactTallyItem & tallyItem, bool fTryDenominated, CConnman & connman) private
Definition at line 1373 of file privatesend-client.cpp.
References ALL_COINS, CWallet::CommitTransaction(), CWallet::CreateTransaction(), cs_main, CWallet::cs_wallet, CCoinControl::destChange, CCoinControl::fAllowOtherInputs, CCoinControl::fAllowWatchOnly, CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), CPubKey::GetID(), CPrivateSend::GetMaxCollateralAmount(), CReserveKey::GetReservedKey(), GetScriptForDestination(), CPrivateSend::IsDenominatedAmount(), CReserveKey::KeepKey(), LOCK2, LogPrintf, CompactTallyItem::nAmount, ONLY_NONDENOMINATED, privateSendClient, prevector< N, T, Size, Diff >::push_back(), pwalletMain, CReserveKey::ReturnKey(), CCoinControl::Select(), CompactTallyItem::txdest, CPrivateSendClientManager::UpdatedSuccessBlock(), and CompactTallyItem::vecOutPoints.
PrepareDenominate()
bool CPrivateSendClientSession::PrepareDenominate (int nMinRounds, int nMaxRounds, std::string & strErrorRet, const std::vector< std::pair< CTxDSIn, CTxOut > > & vecPSInOutPairsIn, std::vector< std::pair< CTxDSIn, CTxOut > > & vecPSInOutPairsRet, bool fDryRun = false) private
step 1: prepare denominated inputs and outputs
Definition at line 1266 of file privatesend-client.cpp.
References CKeyHolderStorage::AddKey(), CPrivateSend::GetDenominationsBits(), GetRandInt(), CPrivateSend::GetStandardDenominations(), keyHolderStorage, CWallet::LockCoin(), CPrivateSendBaseSession::nSessionDenom, PRIVATESEND_ENTRY_MAX_SIZE, pwalletMain, CKeyHolderStorage::ReturnAll(), and CWallet::UnlockCoin().
Referenced by SubmitDenominate().
ProcessMessage()
void CPrivateSendClientSession::ProcessMessage (CNode * pfrom, const std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 129 of file privatesend-client.cpp.
References masternode_info_t::addr, CNode::addr, CheckPoolStateUpdate(), CompletedTransaction(), deserialize, NetMsgType::DSCOMPLETE, NetMsgType::DSFINALTX, NetMsgType::DSSTATUSUPDATE, masternode_info_t::fInfoValid, fLiteMode, fMasternodeMode, CPrivateSend::GetMessageByID(), CNode::GetSendVersion(), CNode::id, infoMixingMasternode, CMasternodeSync::IsBlockchainSynced(), LogPrint, masternodeSync, MIN_PRIVATESEND_PEER_PROTO_VERSION, MSG_POOL_MAX, nEntriesCount, CPrivateSendBaseSession::nSessionID, CNode::nVersion, POOL_STATE_MAX, CConnman::PushMessage(), NetMsgType::REJECT, REJECT_OBSOLETE, SignFinalTransaction(), STATUS_ACCEPTED, strprintf, CService::ToString(), and CTransaction::ToString().
ProcessPendingDsaRequest()
bool CPrivateSendClientSession::ProcessPendingDsaRequest (CConnman & connman)
Definition at line 1141 of file privatesend-client.cpp.
References NetMsgType::DSACCEPT, CConnman::ForNode(), CPendingDsaRequest::GetAddr(), CPendingDsaRequest::GetDSA(), GetTime(), CPendingDsaRequest::IsExpired(), LogPrint, CPrivateSendBaseSession::nTimeLastSuccessfulStep, pendingDsaRequest, CConnman::PushMessage(), SetNull(), and CService::ToString().
RelayIn()
void CPrivateSendClientSession::RelayIn (const CPrivateSendEntry & entry, CConnman & connman) private
Definition at line 1597 of file privatesend-client.cpp.
References masternode_info_t::addr, masternode_info_t::fInfoValid, CConnman::ForNode(), and infoMixingMasternode.
Referenced by SendDenominate().
ResetPool()
void CPrivateSendClientSession::ResetPool ()
Definition at line 237 of file privatesend-client.cpp.
References keyHolderStorage, CKeyHolderStorage::ReturnAll(), SetNull(), txMyCollateral, and UnlockCoins().
SelectDenominate()
bool CPrivateSendClientSession::SelectDenominate (std::string & strErrorRet, std::vector< std::pair< CTxDSIn, CTxOut > > & vecPSInOutPairsRet) private
step 0: select denominated inputs and txouts
Definition at line 1231 of file privatesend-client.cpp.
References CPrivateSend::GetDenominationsBits(), CPrivateSendBaseSession::GetEntriesCount(), CPrivateSend::GetMaxPoolAmount(), CPrivateSend::GetStandardDenominations(), CCryptoKeyStore::IsLocked(), CPrivateSendBaseSession::nSessionDenom, pwalletMain, and CWallet::SelectPSInOutPairsByDenominations().
Referenced by SubmitDenominate().
SendDenominate()
bool CPrivateSendClientSession::SendDenominate (const std::vector< std::pair< CTxDSIn, CTxOut > > & vecPSInOutPairsIn, CConnman & connman) private
step 2: send denominated inputs and outputs prepared in step 1
Definition at line 468 of file privatesend-client.cpp.
References CheckDiskSpace(), fMasternodeMode, GetTime(), keyHolderStorage, LogPrintf, CPrivateSendBaseSession::nSessionID, CPrivateSendBaseSession::nTimeLastSuccessfulStep, POOL_STATE_ACCEPTING_ENTRIES, RelayIn(), CKeyHolderStorage::ReturnAll(), SetNull(), SetState(), strLastMessage, CMutableTransaction::ToString(), txMyCollateral, UnlockCoins(), CPrivateSendBaseSession::vecEntries, vecOutPointLocked, CMutableTransaction::vin, and CMutableTransaction::vout.
Referenced by SubmitDenominate().
SetNull()
void CPrivateSendClientSession::SetNull () private
Definition at line 256 of file privatesend-client.cpp.
References fLastEntryAccepted, infoMixingMasternode, nEntriesCount, pendingDsaRequest, and CPrivateSendBaseSession::SetNull().
Referenced by CheckPool(), CheckPoolStateUpdate(), CheckTimeout(), CompletedTransaction(), DoAutomaticDenominating(), ProcessPendingDsaRequest(), ResetPool(), SendDenominate(), and SignFinalTransaction().
SetState()
void CPrivateSendClientSession::SetState (PoolState nStateNew) private
Definition at line 1609 of file privatesend-client.cpp.
References LogPrintf, and CPrivateSendBaseSession::nState.
Referenced by CheckPoolStateUpdate(), CheckTimeout(), JoinExistingQueue(), SendDenominate(), SignFinalTransaction(), and StartNewQueue().
SignFinalTransaction()
bool CPrivateSendClientSession::SignFinalTransaction (const CTransaction & finalTransactionNew, CNode * pnode, CConnman & connman) private
As a client, check and sign the final transaction.
Definition at line 576 of file privatesend-client.cpp.
References NetMsgType::DSSIGNFINALTX, CPrivateSendBaseSession::finalMutableTransaction, masternode_info_t::fInfoValid, fMasternodeMode, CTransaction::GetHash(), CMutableTransaction::GetHash(), CNode::GetSendVersion(), GetTime(), infoMixingMasternode, keyHolderStorage, LogPrint, LogPrintf, CPrivateSendBaseSession::nTimeLastSuccessfulStep, masternode_info_t::outpoint, POOL_STATE_SIGNING, CConnman::PushMessage(), pwalletMain, CKeyHolderStorage::ReturnAll(), ScriptToAsmStr(), SetNull(), SetState(), SIGHASH_ALL, SIGHASH_ANYONECANPAY, SignSignature(), CMutableTransaction::ToString(), COutPoint::ToStringShort(), UnlockCoins(), CPrivateSendBaseSession::vecEntries, CMutableTransaction::vin, and CMutableTransaction::vout.
Referenced by ProcessMessage().
StartNewQueue()
bool CPrivateSendClientSession::StartNewQueue (CAmount nValueMin, CAmount nBalanceNeedsAnonymized, CConnman & connman) private
Definition at line 1066 of file privatesend-client.cpp.
References _(), CConnman::AddPendingMasternode(), masternode_info_t::addr, CPrivateSendClientManager::AddUsedMasternode(), CWallet::ConvertList(), CMasternodeMan::CountMasternodes(), masternode_info_t::fInfoValid, CPrivateSend::GetDenominationsByAmounts(), CPrivateSend::GetDenominationsToString(), CPrivateSendClientManager::GetNotUsedMasternode(), GetTime(), infoMixingMasternode, CConnman::IsMasternodeOrDisconnectRequested(), CMasternodePayments::IsScheduled(), LogPrintf, mnodeman, mnpayments, CMasternodeMan::nDsqCount, masternode_info_t::nLastDsq, CPrivateSendClientManager::nPrivateSendRounds, CPrivateSendBaseSession::nSessionDenom, CPrivateSendBaseSession::nTimeLastSuccessfulStep, masternode_info_t::outpoint, pendingDsaRequest, POOL_STATE_QUEUE, privateSendClient, pwalletMain, CWallet::SelectPrivateCoins(), SetState(), strAutoDenomResult, CService::ToString(), COutPoint::ToStringShort(), and txMyCollateral.
Referenced by DoAutomaticDenominating().
SubmitDenominate()
bool CPrivateSendClientSession::SubmitDenominate (CConnman & connman)
As a client, submit part of a future mixing transaction to a Masternode to start the process.
Definition at line 1175 of file privatesend-client.cpp.
References cs_main, CWallet::cs_wallet, LOCK2, LogPrint, LogPrintf, CPrivateSendClientManager::nLiquidityProvider, CPrivateSendClientManager::nPrivateSendRounds, CPrivateSendBaseSession::nSessionDenom, PrepareDenominate(), privateSendClient, pwalletMain, SelectDenominate(), SendDenominate(), and strAutoDenomResult.
UnlockCoins()
void CPrivateSendClientSession::UnlockCoins ()
Definition at line 270 of file privatesend-client.cpp.
References CWallet::cs_wallet, MilliSleep(), pwalletMain, TRY_LOCK, CWallet::UnlockCoin(), and vecOutPointLocked.
Referenced by CheckPool(), CheckPoolStateUpdate(), CheckTimeout(), CompletedTransaction(), DoAutomaticDenominating(), ResetPool(), SendDenominate(), and SignFinalTransaction().
Member Data Documentation
fLastEntryAccepted
bool CPrivateSendClientSession::fLastEntryAccepted private
Definition at line 90 of file privatesend-client.h.
Referenced by CheckPoolStateUpdate(), GetStatus(), and SetNull().
infoMixingMasternode
masternode_info_t CPrivateSendClientSession::infoMixingMasternode private
Definition at line 95 of file privatesend-client.h.
Referenced by GetMixingMasternodeInfo(), JoinExistingQueue(), ProcessMessage(), RelayIn(), SetNull(), SignFinalTransaction(), and StartNewQueue().
keyHolderStorage
CKeyHolderStorage CPrivateSendClientSession::keyHolderStorage private
Definition at line 99 of file privatesend-client.h.
Referenced by CheckPool(), CheckPoolStateUpdate(), CheckTimeout(), CompletedTransaction(), DoAutomaticDenominating(), PrepareDenominate(), ResetPool(), SendDenominate(), and SignFinalTransaction().
nEntriesCount
int CPrivateSendClientSession::nEntriesCount private
Definition at line 89 of file privatesend-client.h.
Referenced by CheckPoolStateUpdate(), GetStatus(), ProcessMessage(), and SetNull().
pendingDsaRequest
CPendingDsaRequest CPrivateSendClientSession::pendingDsaRequest private
Definition at line 97 of file privatesend-client.h.
Referenced by JoinExistingQueue(), ProcessPendingDsaRequest(), SetNull(), and StartNewQueue().
strAutoDenomResult
std::string CPrivateSendClientSession::strAutoDenomResult private
Definition at line 93 of file privatesend-client.h.
Referenced by CheckPoolStateUpdate(), CreateDenominated(), DoAutomaticDenominating(), GetStatus(), JoinExistingQueue(), StartNewQueue(), and SubmitDenominate().
strLastMessage
std::string CPrivateSendClientSession::strLastMessage private
Definition at line 92 of file privatesend-client.h.
Referenced by CheckPoolStateUpdate(), CompletedTransaction(), GetStatus(), and SendDenominate().
txMyCollateral
CMutableTransaction CPrivateSendClientSession::txMyCollateral private
Definition at line 96 of file privatesend-client.h.
Referenced by DoAutomaticDenominating(), JoinExistingQueue(), ResetPool(), SendDenominate(), and StartNewQueue().
vecOutPointLocked
std::vector<COutPoint> CPrivateSendClientSession::vecOutPointLocked private
Definition at line 87 of file privatesend-client.h.
Referenced by SendDenominate(), and UnlockCoins().
The documentation for this class was generated from the following files:
src/privatesend-client.h
src/privatesend-client.cpp
Released under the MIT license