Dash Core: CChain Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CChain Class Reference
An in-memory indexed chain of blocks.
#include <chain.h>
Public Member Functions
CBlockIndex * Genesis () const
Returns the index entry for the genesis block of this chain, or NULL if none.
CBlockIndex * Tip () const
Returns the index entry for the tip of this chain, or NULL if none.
CBlockIndex * operator[] (int nHeight) const
Returns the index entry at a particular height in this chain, or NULL if no such height exists.
bool Contains (const CBlockIndex *pindex) const
Efficiently check whether a block is present in this chain.
CBlockIndex * Next (const CBlockIndex *pindex) const
Find the successor of a block in this chain, or NULL if the given index is not found or is the tip.
int Height () const
Return the maximal height in the chain.
void SetTip (CBlockIndex *pindex)
Set/initialize a chain with a given tip.
CBlockLocator GetLocator (const CBlockIndex *pindex=NULL) const
Return a CBlockLocator that refers to a block in this chain (by default the tip).
const CBlockIndex * FindFork (const CBlockIndex *pindex) const
Find the last common block between this chain and a block index entry.
CBlockIndex * FindEarliestAtLeast (int64_t nTime) const
Find the earliest block with timestamp equal or greater than the given.
Private Attributes
std::vector< CBlockIndex * > vChain
Friends
bool operator== (const CChain &a, const CChain &b)
Compare two chains efficiently.
Detailed Description
An in-memory indexed chain of blocks.
Definition at line 423 of file chain.h.
Member Function Documentation
Contains()
bool CChain::Contains (const CBlockIndex * pindex) const inline
Efficiently check whether a block is present in this chain.
Definition at line 452 of file chain.h.
References CBlockIndex::nHeight.
Referenced by blockheaderToJSON(), blockToJSON(), BuildSimplifiedMNListDiff(), FindFork(), FindForkInGlobalIndex(), FindMostWorkChain(), getchaintips(), CMerkleTx::GetDepthInMainChain(), CWallet::GetKeyBirthTimes(), GetLocator(), importprunedfunds(), InvalidateBlock(), CGovernanceObject::IsCollateralValid(), CWallet::MarkConflicted(), Next(), ProcessGetData(), ProcessMessage(), rest_headers(), TestLockPointValidity(), TxToJSON(), and verifytxoutproof().
FindEarliestAtLeast()
CBlockIndex * CChain::FindEarliestAtLeast (int64_t nTime) const
Find the earliest block with timestamp equal or greater than the given.
Definition at line 62 of file chain.cpp.
References vChain.
Referenced by importmulti(), importwallet(), and pruneblockchain().
FindFork()
const CBlockIndex * CChain::FindFork (const CBlockIndex * pindex) const
Find the last common block between this chain and a block index entry.
Definition at line 51 of file chain.cpp.
References Contains(), CBlockIndex::GetAncestor(), Height(), CBlockIndex::nHeight, and CBlockIndex::pprev.
Referenced by ActivateBestChain(), ActivateBestChainStep(), getchaintips(), and listsinceblock().
Genesis()
CBlockIndex* CChain::Genesis () const inline
Returns the index entry for the genesis block of this chain, or NULL if none.
Definition at line 429 of file chain.h.
References vChain.
Referenced by BuildSimplifiedMNListDiff(), CheckBlockIndex(), CWallet::CreateWalletFromFile(), FindForkInGlobalIndex(), importaddress(), importmulti(), importprivkey(), importpubkey(), and InitBlockIndex().
GetLocator()
CBlockLocator CChain::GetLocator (const CBlockIndex * pindex = NULL) const
Return a CBlockLocator that refers to a block in this chain (by default the tip).
Definition at line 23 of file chain.cpp.
References Contains(), CBlockIndex::GetAncestor(), CBlockIndex::GetBlockHash(), CBlockIndex::nHeight, and Tip().
Referenced by CWallet::CreateWalletFromFile(), FlushStateToDisk(), ProcessMessage(), and SendMessages().
Height()
int CChain::Height () const inline
Return the maximal height in the chain.
Is equal to chain.Tip() ? chain.Tip()->nHeight : -1.
Definition at line 465 of file chain.h.
References vChain.
Referenced by AcceptBlock(), AcceptToMemoryPoolWorker(), AppInitMain(), BIP9SoftForkDesc(), blockheaderToJSON(), blockToJSON(), CMasternode::Check(), CMasternodePing::CheckAndUpdate(), CheckBlockIndex(), CheckFinalTx(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), CMasternodeBroadcast::CheckOutpoint(), CMasternodePing::CMasternodePing(), CWallet::CreateTransaction(), CWallet::CreateWalletFromFile(), dumpwallet(), entryToJSON(), FindFork(), TransactionDesc::FormatTxStatus(), generateBlocks(), getblockchaininfo(), getblockcount(), GetBlockHash(), getblockhash(), getblocktemplate(), CMasternodePayments::GetBlockTxOuts(), CMerkleTx::GetDepthInMainChain(), getgovernanceinfo(), getinfo(), CWallet::GetKeyBirthTimes(), getmininginfo(), GetNetworkHashPS(), ClientModel::getNumBlocks(), GetRequiredPaymentsStrings(), gettxoutproof(), GetUTXOConfirmations(), importelectrumwallet(), importwallet(), InvalidChainFound(), CGovernanceObject::IsCollateralValid(), IsCurrentForFeeEstimation(), CTxLockRequest::IsValid(), listsinceblock(), LoadBlockIndexDB(), CWallet::MarkConflicted(), ParseBlock(), WalletModel::pollBalanceChanged(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), ProcessGetData(), ProcessMessage(), CSporkManager::ProcessSpork(), protx_list(), pruneblockchain(), rest_getutxos(), TransactionRecord::statusUpdateNeeded(), TxToJSON(), TransactionRecord::updateStatus(), UpdateTip(), and CVerifyDB::VerifyDB().
Next()
CBlockIndex* CChain::Next (const CBlockIndex * pindex) const inline
Find the successor of a block in this chain, or NULL if the given index is not found or is the tip.
Definition at line 457 of file chain.h.
References Contains(), and CBlockIndex::nHeight.
Referenced by blockheaderToJSON(), blockToJSON(), getblockheaders(), ProcessMessage(), rest_headers(), CWallet::ScanForWalletTransactions(), and CVerifyDB::VerifyDB().
operator[]()
CBlockIndex* CChain::operator[] (int nHeight) const inline
Returns the index entry at a particular height in this chain, or NULL if no such height exists.
Definition at line 439 of file chain.h.
References vChain.
SetTip()
void CChain::SetTip (CBlockIndex * pindex)
Set/initialize a chain with a given tip.
CChain implementation.
Definition at line 11 of file chain.cpp.
References CBlockIndex::nHeight, CBlockIndex::pprev, and vChain.
Referenced by LoadBlockIndexDB(), UnloadBlockIndex(), and UpdateTip().
Tip()
CBlockIndex* CChain::Tip () const inline
Returns the index entry for the tip of this chain, or NULL if none.
Definition at line 434 of file chain.h.
References vChain.
Referenced by AcceptBlock(), AcceptToMemoryPoolWorker(), ActivateBestChain(), ActivateBestChainStep(), AlreadyHave(), AppInitMain(), BIP9SoftForkDesc(), BOOST_FIXTURE_TEST_CASE(), CheckBlockIndex(), CheckFinalTx(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), CheckSequenceLocks(), CMasternodePing::CMasternodePing(), ConnectTip(), BlockAssembler::CreateNewBlock(), CWallet::CreateWalletFromFile(), DisconnectTip(), dumpwallet(), FindFilesToPrune(), FindFilesToPruneManual(), generateBlocks(), getbestblockhash(), getblockchaininfo(), GetBlockHash(), getblocktemplate(), getchaintips(), GetDifficulty(), ClientModel::getLastBlockDate(), GetLocator(), GetNetworkHashPS(), GetNextMasternodeForPayment(), GetUTXOConfirmations(), ClientModel::getVerificationProgress(), importmulti(), importwallet(), CDSNotificationInterface::InitializeCurrentBlockTip(), InvalidateBlock(), InvalidChainFound(), IsCurrentForFeeEstimation(), IsInitialBlockDownload(), LoadBlockIndexDB(), masternode_winners(), masternodelist(), PreciousBlock(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), ProcessMessage(), CSporkManager::ProcessSpork(), PruneBlockIndexCandidates(), ReceivedBlockTransactions(), CMasternodePayments::RequestLowDataPaymentBlocks(), ResetBlockFailureFlags(), rest_getutxos(), CWallet::ScanForWalletTransactions(), SendMessages(), TestBlockValidity(), ThreadImport(), llmq::CDummyDKG::UpdatedBlockTip(), UpdateTip(), CVerifyDB::VerifyDB(), VersionBitsTipState(), and VersionBitsTipStateSinceHeight().
Friends And Related Function Documentation
operator==
bool operator== (const CChain & a, const CChain & b) friend
Compare two chains efficiently.
Definition at line 446 of file chain.h.
Member Data Documentation
vChain
std::vector<CBlockIndex*> CChain::vChain private
Definition at line 425 of file chain.h.
Referenced by FindEarliestAtLeast(), Genesis(), Height(), operator[](), SetTip(), and Tip().
The documentation for this class was generated from the following files:
src/chain.h
src/chain.cpp
Released under the MIT license