Dash Core: CMasternodeSync Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CMasternodeSync Class Reference
#include <masternode-sync.h>
Public Member Functions
CMasternodeSync ()
void SendGovernanceSyncRequest (CNode *pnode, CConnman &connman)
bool IsFailed ()
bool IsBlockchainSynced ()
bool IsMasternodeListSynced ()
bool IsWinnersListSynced ()
bool IsSynced ()
int GetAssetID ()
int GetAttempt ()
void BumpAssetLastTime (const std::string &strFuncName)
int64_t GetAssetStartTime ()
std::string GetAssetName ()
std::string GetSyncStatus ()
void Reset ()
void SwitchToNextAsset (CConnman &connman)
void ProcessMessage (CNode *pfrom, const std::string &strCommand, CDataStream &vRecv)
void ProcessTick (CConnman &connman)
void AcceptedBlockHeader (const CBlockIndex *pindexNew)
void NotifyHeaderTip (const CBlockIndex *pindexNew, bool fInitialDownload, CConnman &connman)
void UpdatedBlockTip (const CBlockIndex *pindexNew, bool fInitialDownload, CConnman &connman)
void DoMaintenance (CConnman &connman)
Private Member Functions
void Fail ()
Private Attributes
int nCurrentAsset
int nTriedPeerCount
int64_t nTimeAssetSyncStarted
int64_t nTimeLastBumped
int64_t nTimeLastFailure
Detailed Description
Definition at line 31 of file masternode-sync.h.
Constructor & Destructor Documentation
CMasternodeSync()
CMasternodeSync::CMasternodeSync () inline
Definition at line 49 of file masternode-sync.h.
References Reset().
Member Function Documentation
AcceptedBlockHeader()
void CMasternodeSync::AcceptedBlockHeader (const CBlockIndex * pindexNew)
Definition at line 440 of file masternode-sync.cpp.
References BumpAssetLastTime(), IsBlockchainSynced(), LogPrint, and CBlockIndex::nHeight.
Referenced by CDSNotificationInterface::AcceptedBlockHeader().
BumpAssetLastTime()
void CMasternodeSync::BumpAssetLastTime (const std::string & strFuncName)
Definition at line 35 of file masternode-sync.cpp.
References GetTime(), IsFailed(), IsSynced(), LogPrint, and nTimeLastBumped.
Referenced by AcceptedBlockHeader(), CGovernanceManager::AddGovernanceObject(), CMasternodePing::CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), NotifyHeaderTip(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), SwitchToNextAsset(), CMasternodeBroadcast::Update(), and UpdatedBlockTip().
DoMaintenance()
void CMasternodeSync::DoMaintenance (CConnman & connman)
Definition at line 515 of file masternode-sync.cpp.
References ProcessTick(), and ShutdownRequested().
Referenced by AppInitMain().
Fail()
void CMasternodeSync::Fail () private
Definition at line 20 of file masternode-sync.cpp.
References GetTime(), MASTERNODE_SYNC_FAILED, nCurrentAsset, and nTimeLastFailure.
Referenced by ProcessTick().
GetAssetID()
int CMasternodeSync::GetAssetID () inline
Definition at line 60 of file masternode-sync.h.
References nCurrentAsset.
Referenced by mnsync().
GetAssetName()
std::string CMasternodeSync::GetAssetName ()
Definition at line 42 of file masternode-sync.cpp.
References MASTERNODE_SYNC_FAILED, MASTERNODE_SYNC_FINISHED, MASTERNODE_SYNC_GOVERNANCE, MASTERNODE_SYNC_INITIAL, MASTERNODE_SYNC_LIST, MASTERNODE_SYNC_MNW, MASTERNODE_SYNC_WAITING, and nCurrentAsset.
Referenced by mnsync(), ProcessTick(), and SwitchToNextAsset().
GetAssetStartTime()
int64_t CMasternodeSync::GetAssetStartTime () inline
Definition at line 63 of file masternode-sync.h.
References nTimeAssetSyncStarted.
Referenced by mnsync().
GetAttempt()
int CMasternodeSync::GetAttempt () inline
Definition at line 61 of file masternode-sync.h.
References nTriedPeerCount.
Referenced by mnsync().
GetSyncStatus()
std::string CMasternodeSync::GetSyncStatus ()
Definition at line 110 of file masternode-sync.cpp.
References _(), MASTERNODE_SYNC_FAILED, MASTERNODE_SYNC_FINISHED, MASTERNODE_SYNC_GOVERNANCE, MASTERNODE_SYNC_INITIAL, MASTERNODE_SYNC_LIST, MASTERNODE_SYNC_MNW, MASTERNODE_SYNC_WAITING, masternodeSync, and nCurrentAsset.
Referenced by BitcoinGUI::setAdditionalDataSyncProgress().
IsBlockchainSynced()
bool CMasternodeSync::IsBlockchainSynced () inline
Definition at line 55 of file masternode-sync.h.
References MASTERNODE_SYNC_WAITING, and nCurrentAsset.
Referenced by AcceptedBlockHeader(), CMasternodePayments::CheckAndRemove(), CPrivateSendServer::DoMaintenance(), CMasternodeMan::DoMaintenance(), CPrivateSendClientManager::DoMaintenance(), CPrivateSendClientSession::GetStatus(), gobject_submit(), CActiveLegacyMasternodeManager::ManageState(), mnsync(), NotifyHeaderTip(), OverviewPage::privateSendStatus(), CPrivateSendServer::ProcessMessage(), CPrivateSendClientSession::ProcessMessage(), CMasternodeMan::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), CGovernanceManager::ProcessMessage(), BitcoinGUI::setAdditionalDataSyncProgress(), BitcoinGUI::setNumBlocks(), UpdatedBlockTip(), and OverviewPage::updatePrivateSendProgress().
IsFailed()
bool CMasternodeSync::IsFailed () inline
Definition at line 54 of file masternode-sync.h.
References MASTERNODE_SYNC_FAILED, and nCurrentAsset.
Referenced by BumpAssetLastTime(), mnsync(), NotifyHeaderTip(), ProcessMessage(), ProcessTick(), and UpdatedBlockTip().
IsMasternodeListSynced()
bool CMasternodeSync::IsMasternodeListSynced () inline
Definition at line 56 of file masternode-sync.h.
References MASTERNODE_SYNC_LIST, and nCurrentAsset.
Referenced by CMasternode::Check(), CInstantSend::CheckAndRemove(), CMasternodeMan::CheckAndRemove(), CMasternodePing::CheckAndUpdate(), CMasternodePaymentVote::CheckSignature(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientManager::DoAutomaticDenominating(), CMasternodeMan::GetMasternodeRank(), CMasternodeMan::GetMasternodeRanks(), CMasternodeMan::GetMasternodeScores(), CMasternodePayments::IsScheduled(), CMasternodePaymentVote::IsValid(), mnsync(), MasternodeList::on_startMissingButton_clicked(), CMasternodePayments::ProcessBlock(), CInstantSend::ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), CMasternodePayments::RequestLowDataPaymentBlocks(), CPrivateSend::UpdatedBlockTip(), CPrivateSendClientManager::WaitForAnotherBlock(), and CMasternodeMan::WarnMasternodeDaemonUpdates().
IsSynced()
bool CMasternodeSync::IsSynced () inline
Definition at line 58 of file masternode-sync.h.
References MASTERNODE_SYNC_FINISHED, and nCurrentAsset.
Referenced by CConnman::AcceptConnection(), BumpAssetLastTime(), CMasternode::Check(), CMasternodeMan::CheckAndRemove(), CGovernanceManager::CheckPostponedObjects(), CMasternodeMan::CheckSameAddr(), CMasternodeMan::DoFullVerificationStep(), CGovernanceManager::DoMaintenance(), getblocktemplate(), IsBlockPayeeValid(), IsBlockValueValid(), IsOldBudgetBlockValueValid(), CGovernanceManager::MasternodeRateCheck(), mnsync(), NotifyHeaderTip(), ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), ProcessTick(), CMasternodePing::Relay(), CGovernanceVote::Relay(), CMasternodePaymentVote::Relay(), CGovernanceObject::Relay(), CMasternodeBroadcast::Relay(), BitcoinGUI::setAdditionalDataSyncProgress(), CMasternodeMan::SyncAll(), CGovernanceManager::SyncAll(), CMasternodeMan::SyncSingle(), CGovernanceManager::SyncSingleObjAndItsVotes(), and UpdatedBlockTip().
IsWinnersListSynced()
bool CMasternodeSync::IsWinnersListSynced () inline
Definition at line 57 of file masternode-sync.h.
References MASTERNODE_SYNC_MNW, and nCurrentAsset.
Referenced by CMasternodePayments::CheckBlockVotes(), CGovernanceManager::ConfirmInventoryRequest(), getblocktemplate(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), mnsync(), CMasternodePayments::Sync(), and CMasternodeMan::UpdateLastPaid().
NotifyHeaderTip()
void CMasternodeSync::NotifyHeaderTip (const CBlockIndex * pindexNew, bool fInitialDownload, CConnman & connman)
Definition at line 450 of file masternode-sync.cpp.
References BumpAssetLastTime(), IsBlockchainSynced(), IsFailed(), IsSynced(), LogPrint, CBlockIndex::nHeight, and pindexBestHeader.
Referenced by CDSNotificationInterface::NotifyHeaderTip().
ProcessMessage()
void CMasternodeSync::ProcessMessage (CNode * pfrom, const std::string & strCommand, CDataStream & vRecv)
Definition at line 124 of file masternode-sync.cpp.
References CNode::id, IsFailed(), IsSynced(), LogPrintf, and NetMsgType::SYNCSTATUSCOUNT.
Referenced by ProcessMessage().
ProcessTick()
void CMasternodeSync::ProcessTick (CConnman & connman)
Definition at line 139 of file masternode-sync.cpp.
References CNetFulfilledRequestManager::AddFulfilledRequest(), CConnman::CopyNodeVector(), deterministicMNManager, CMasternodeMan::DsegUpdate(), Fail(), fMasternodeMode, CConnman::FullyConnectedOnly, GetAssetName(), CMasternodePayments::GetMinMasternodePaymentsProto(), NetMsgType::GETSPORKS, GetTime(), CGovernanceManager::GetVoteCount(), governance, CNetFulfilledRequestManager::HasFulfilledRequest(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CMasternodePayments::IsEnoughData(), IsFailed(), IsSynced(), LogPrint, LogPrintf, MASTERNODE_SYNC_GOVERNANCE, MASTERNODE_SYNC_LIST, MASTERNODE_SYNC_MNW, MASTERNODE_SYNC_TICK_SECONDS, MASTERNODE_SYNC_TIMEOUT_SECONDS, MASTERNODE_SYNC_WAITING, NetMsgType::MASTERNODEPAYMENTSYNC, MIN_GOVERNANCE_PEER_PROTO_VERSION, mnodeman, mnpayments, nCurrentAsset, netfulfilledman, CChainParams::NetworkIDString(), CClientUIInterface::NotifyAdditionalDataSyncProgressChanged, nTimeLastBumped, nTimeLastFailure, nTriedPeerCount, Params(), CConnman::PushMessage(), CBaseChainParams::REGTEST, CConnman::ReleaseNodeVector(), CGovernanceManager::RequestGovernanceObjectVotes(), CMasternodePayments::RequestLowDataPaymentBlocks(), Reset(), SendGovernanceSyncRequest(), SwitchToNextAsset(), and uiInterface.
Referenced by DoMaintenance().
Reset()
void CMasternodeSync::Reset ()
Definition at line 26 of file masternode-sync.cpp.
References GetTime(), MASTERNODE_SYNC_INITIAL, nCurrentAsset, nTimeAssetSyncStarted, nTimeLastBumped, nTimeLastFailure, and nTriedPeerCount.
Referenced by CMasternodeSync(), mnsync(), ProcessTick(), and UpdatedBlockTip().
SendGovernanceSyncRequest()
void CMasternodeSync::SendGovernanceSyncRequest (CNode * pnode, CConnman & connman)
Definition at line 425 of file masternode-sync.cpp.
References CBloomFilter::clear(), CNode::GetSendVersion(), GOVERNANCE_FILTER_PROTO_VERSION, NetMsgType::MNGOVERNANCESYNC, CNode::nVersion, and CConnman::PushMessage().
Referenced by ProcessTick().
SwitchToNextAsset()
void CMasternodeSync::SwitchToNextAsset (CConnman & connman)
Definition at line 57 of file masternode-sync.cpp.
References CNetFulfilledRequestManager::AddFulfilledRequest(), CNode::addr, CConnman::AllNodes, BumpAssetLastTime(), deterministicMNManager, CConnman::ForEachNode(), GetAssetName(), GetTime(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), legacyActiveMasternodeManager, LogPrintf, CActiveLegacyMasternodeManager::ManageState(), MASTERNODE_SYNC_FAILED, MASTERNODE_SYNC_FINISHED, MASTERNODE_SYNC_GOVERNANCE, MASTERNODE_SYNC_INITIAL, MASTERNODE_SYNC_LIST, MASTERNODE_SYNC_MNW, MASTERNODE_SYNC_WAITING, nCurrentAsset, netfulfilledman, CClientUIInterface::NotifyAdditionalDataSyncProgressChanged, nTimeAssetSyncStarted, nTriedPeerCount, and uiInterface.
Referenced by mnsync(), ProcessTick(), and UpdatedBlockTip().
UpdatedBlockTip()
void CMasternodeSync::UpdatedBlockTip (const CBlockIndex * pindexNew, bool fInitialDownload, CConnman & connman)
Definition at line 463 of file masternode-sync.cpp.
References BumpAssetLastTime(), fLiteMode, CBlockIndex::GetBlockHash(), IsBlockchainSynced(), IsFailed(), IsSynced(), LogPrint, MASTERNODE_SYNC_FINISHED, nCurrentAsset, CBlockIndex::nHeight, pindexBestHeader, Reset(), and SwitchToNextAsset().
Referenced by CDSNotificationInterface::UpdatedBlockTip().
Member Data Documentation
nCurrentAsset
int CMasternodeSync::nCurrentAsset private
Definition at line 35 of file masternode-sync.h.
Referenced by Fail(), GetAssetID(), GetAssetName(), GetSyncStatus(), IsBlockchainSynced(), IsFailed(), IsMasternodeListSynced(), IsSynced(), IsWinnersListSynced(), ProcessTick(), Reset(), SwitchToNextAsset(), and UpdatedBlockTip().
nTimeAssetSyncStarted
int64_t CMasternodeSync::nTimeAssetSyncStarted private
Definition at line 40 of file masternode-sync.h.
Referenced by GetAssetStartTime(), Reset(), and SwitchToNextAsset().
nTimeLastBumped
int64_t CMasternodeSync::nTimeLastBumped private
Definition at line 42 of file masternode-sync.h.
Referenced by BumpAssetLastTime(), ProcessTick(), and Reset().
nTimeLastFailure
int64_t CMasternodeSync::nTimeLastFailure private
Definition at line 44 of file masternode-sync.h.
Referenced by Fail(), ProcessTick(), and Reset().
nTriedPeerCount
int CMasternodeSync::nTriedPeerCount private
Definition at line 37 of file masternode-sync.h.
Referenced by GetAttempt(), ProcessTick(), Reset(), and SwitchToNextAsset().
The documentation for this class was generated from the following files:
src/masternode-sync.h
src/masternode-sync.cpp
Released under the MIT license