Dash Core: CActiveDeterministicMasternodeManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CActiveDeterministicMasternodeManager Class Reference
#include <activemasternode.h>
Public Types
enum masternode_state_t {
MASTERNODE_WAITING_FOR_PROTX, MASTERNODE_POSE_BANNED, MASTERNODE_REMOVED, MASTERNODE_OPERATOR_KEY_CHANGED,
MASTERNODE_READY, MASTERNODE_ERROR
}
Public Member Functions
virtual void UpdatedBlockTip (const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload)
void Init ()
CDeterministicMNCPtr GetDMN () const
std::string GetStateString () const
std::string GetStatus () const
Private Member Functions
bool GetLocalAddress (CService &addrRet)
Private Attributes
CDeterministicMNCPtr mnListEntry
masternode_state_t state {MASTERNODE_WAITING_FOR_PROTX}
std::string strError
Additional Inherited Members
Protected Member Functions inherited from CValidationInterface
virtual void AcceptedBlockHeader (const CBlockIndex *pindexNew)
virtual void NotifyHeaderTip (const CBlockIndex *pindexNew, bool fInitialDownload)
virtual void SyncTransaction (const CTransaction &tx, const CBlockIndex *pindex, int posInBlock)
virtual void NotifyTransactionLock (const CTransaction &tx)
virtual void NotifyGovernanceVote (const CGovernanceVote &vote)
virtual void NotifyGovernanceObject (const CGovernanceObject &object)
virtual void NotifyInstantSendDoubleSpendAttempt (const CTransaction &currentTx, const CTransaction &previousTx)
virtual void SetBestChain (const CBlockLocator &locator)
virtual bool UpdatedTransaction (const uint256 &hash)
virtual void Inventory (const uint256 &hash)
virtual void ResendWalletTransactions (int64_t nBestBlockTime, CConnman *connman)
virtual void BlockChecked (const CBlock &, const CValidationState &)
virtual void GetScriptForMining (boost::shared_ptr< CReserveScript > &)
virtual void ResetRequestCount (const uint256 &hash)
virtual void NewPoWValidBlock (const CBlockIndex *pindex, const std::shared_ptr< const CBlock > &block)
friend void ::RegisterValidationInterface (CValidationInterface *)
friend void ::UnregisterValidationInterface (CValidationInterface *)
friend void ::UnregisterAllValidationInterfaces ()
Detailed Description
Definition at line 46 of file activemasternode.h.
Member Enumeration Documentation
masternode_state_t
enum CActiveDeterministicMasternodeManager::masternode_state_t
Enumerator
MASTERNODE_WAITING_FOR_PROTX
MASTERNODE_POSE_BANNED
MASTERNODE_REMOVED
MASTERNODE_OPERATOR_KEY_CHANGED
MASTERNODE_READY
MASTERNODE_ERROR
Definition at line 49 of file activemasternode.h.
Member Function Documentation
GetDMN()
CDeterministicMNCPtr CActiveDeterministicMasternodeManager::GetDMN () const inline
Definition at line 68 of file activemasternode.h.
References mnListEntry.
Referenced by masternode_status().
GetLocalAddress()
bool CActiveDeterministicMasternodeManager::GetLocalAddress (CService & addrRet) private
Definition at line 161 of file activemasternode.cpp.
References activeMasternodeInfo, CNode::addr, CConnman::AllNodes, immer::detail::dvektor::empty, g_connman, GetListenPort(), GetLocal(), CNetAddr::IsIPv4(), CMasternode::IsValidNetAddr(), LogPrintf, Lookup(), Params(), CBaseChainParams::REGTEST, CActiveMasternodeInfo::service, and strError.
Referenced by Init().
GetStateString()
std::string CActiveDeterministicMasternodeManager::GetStateString () const
Definition at line 20 of file activemasternode.cpp.
References MASTERNODE_ERROR, MASTERNODE_OPERATOR_KEY_CHANGED, MASTERNODE_POSE_BANNED, MASTERNODE_READY, MASTERNODE_REMOVED, MASTERNODE_WAITING_FOR_PROTX, and state.
Referenced by masternode_status().
GetStatus()
std::string CActiveDeterministicMasternodeManager::GetStatus () const
Definition at line 40 of file activemasternode.cpp.
References MASTERNODE_ERROR, MASTERNODE_OPERATOR_KEY_CHANGED, MASTERNODE_POSE_BANNED, MASTERNODE_READY, MASTERNODE_REMOVED, MASTERNODE_WAITING_FOR_PROTX, state, and strError.
Referenced by masternode_status().
Init()
void CActiveDeterministicMasternodeManager::Init ()
Definition at line 60 of file activemasternode.cpp.
References activeMasternodeInfo, CActiveMasternodeInfo::blsPubKeyOperator, CloseSocket(), ConnectSocket(), cs_main, deterministicMNManager, fListen, fMasternodeMode, CDeterministicMNManager::GetListAtChainTip(), GetLocalAddress(), CDeterministicMNList::GetMNByOperatorKey(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CDeterministicMNList::IsMNPoSeBanned(), CDeterministicMNList::IsMNValid(), IsSelectableSocket(), LOCK, LogPrintf, MASTERNODE_ERROR, MASTERNODE_POSE_BANNED, MASTERNODE_READY, MASTERNODE_REMOVED, mnListEntry, nConnectTimeout, CActiveMasternodeInfo::outpoint, Params(), CActiveMasternodeInfo::proTxHash, CBaseChainParams::REGTEST, CActiveMasternodeInfo::service, state, strError, and CService::ToString().
Referenced by ThreadImport(), and UpdatedBlockTip().
UpdatedBlockTip()
void CActiveDeterministicMasternodeManager::UpdatedBlockTip (const CBlockIndex * pindexNew, const CBlockIndex * pindexFork, bool fInitialDownload) virtual
Reimplemented from CValidationInterface.
Definition at line 130 of file activemasternode.cpp.
References activeMasternodeInfo, cs_main, deterministicMNManager, fMasternodeMode, CBlockIndex::GetBlockHash(), CDeterministicMNManager::GetListForBlock(), Init(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LOCK, MASTERNODE_OPERATOR_KEY_CHANGED, MASTERNODE_READY, MASTERNODE_REMOVED, mnListEntry, CBlockIndex::nHeight, CActiveMasternodeInfo::outpoint, CActiveMasternodeInfo::proTxHash, COutPoint::SetNull(), and state.
Member Data Documentation
mnListEntry
CDeterministicMNCPtr CActiveDeterministicMasternodeManager::mnListEntry private
Definition at line 59 of file activemasternode.h.
Referenced by GetDMN(), Init(), and UpdatedBlockTip().
state
masternode_state_t CActiveDeterministicMasternodeManager::state {MASTERNODE_WAITING_FOR_PROTX} private
Definition at line 60 of file activemasternode.h.
Referenced by GetStateString(), GetStatus(), Init(), and UpdatedBlockTip().
strError
std::string CActiveDeterministicMasternodeManager::strError private
Definition at line 61 of file activemasternode.h.
Referenced by GetLocalAddress(), GetStatus(), and Init().
The documentation for this class was generated from the following files:
src/activemasternode.h
src/activemasternode.cpp
Released under the MIT license