Dash Core: CActiveLegacyMasternodeManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CActiveLegacyMasternodeManager Class Reference
#include <activemasternode.h>
Public Types
enum masternode_type_enum_t { MASTERNODE_UNKNOWN = 0, MASTERNODE_REMOTE = 1 }
Public Member Functions
CActiveLegacyMasternodeManager ()
void ManageState (CConnman &connman)
Manage state of active Masternode.
std::string GetStateString () const
std::string GetStatus () const
std::string GetTypeString () const
bool UpdateSentinelPing (int version)
void DoMaintenance (CConnman &connman)
Public Attributes
int nState
std::string strNotCapableReason
Private Member Functions
bool SendMasternodePing (CConnman &connman)
Ping Masternode.
void ManageStateInitial (CConnman &connman)
void ManageStateRemote ()
Private Attributes
CCriticalSection cs
masternode_type_enum_t eType
bool fPingerEnabled
int64_t nSentinelPingTime
uint32_t nSentinelVersion
Detailed Description
Definition at line 78 of file activemasternode.h.
Member Enumeration Documentation
masternode_type_enum_t
enum CActiveLegacyMasternodeManager::masternode_type_enum_t
Enumerator
MASTERNODE_UNKNOWN
MASTERNODE_REMOTE
Definition at line 81 of file activemasternode.h.
Constructor & Destructor Documentation
CActiveLegacyMasternodeManager()
CActiveLegacyMasternodeManager::CActiveLegacyMasternodeManager () inline
Definition at line 106 of file activemasternode.h.
Member Function Documentation
DoMaintenance()
void CActiveLegacyMasternodeManager::DoMaintenance (CConnman & connman)
Definition at line 320 of file activemasternode.cpp.
References ManageState(), and ShutdownRequested().
Referenced by AppInitMain().
GetStateString()
std::string CActiveLegacyMasternodeManager::GetStateString () const
Definition at line 223 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_INITIAL, ACTIVE_MASTERNODE_INPUT_TOO_NEW, ACTIVE_MASTERNODE_NOT_CAPABLE, ACTIVE_MASTERNODE_STARTED, ACTIVE_MASTERNODE_SYNC_IN_PROCESS, and nState.
Referenced by ManageState(), ManageStateInitial(), ManageStateRemote(), and SendMasternodePing().
GetStatus()
std::string CActiveLegacyMasternodeManager::GetStatus () const
Definition at line 241 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_INITIAL, ACTIVE_MASTERNODE_INPUT_TOO_NEW, ACTIVE_MASTERNODE_NOT_CAPABLE, ACTIVE_MASTERNODE_STARTED, ACTIVE_MASTERNODE_SYNC_IN_PROCESS, nState, Params(), strNotCapableReason, and strprintf.
Referenced by ManageState(), ManageStateInitial(), ManageStateRemote(), and masternode_status().
GetTypeString()
std::string CActiveLegacyMasternodeManager::GetTypeString () const
Definition at line 259 of file activemasternode.cpp.
References eType, and MASTERNODE_REMOTE.
Referenced by ManageState(), ManageStateInitial(), and ManageStateRemote().
ManageState()
void CActiveLegacyMasternodeManager::ManageState (CConnman & connman)
Manage state of active Masternode.
Definition at line 191 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_INITIAL, ACTIVE_MASTERNODE_SYNC_IN_PROCESS, deterministicMNManager, eType, fMasternodeMode, fPingerEnabled, GetStateString(), GetStatus(), GetTypeString(), CMasternodeSync::IsBlockchainSynced(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LogPrint, LogPrintf, ManageStateInitial(), ManageStateRemote(), MASTERNODE_REMOTE, MASTERNODE_UNKNOWN, masternodeSync, nState, Params(), CBaseChainParams::REGTEST, and SendMasternodePing().
Referenced by CMasternodeMan::CheckMnbAndUpdateMasternodeList(), DoMaintenance(), CMasternodeSync::SwitchToNextAsset(), and CMasternode::UpdateFromNewBroadcast().
ManageStateInitial()
void CActiveLegacyMasternodeManager::ManageStateInitial (CConnman & connman) private
Definition at line 327 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_NOT_CAPABLE, activeMasternodeInfo, CNode::addr, CConnman::AllNodes, CloseSocket(), ConnectSocket(), deterministicMNManager, immer::detail::dvektor::empty, eType, fListen, CConnman::ForEachNodeContinueIf(), fPingerEnabled, CChainParams::GetDefaultPort(), GetListenPort(), GetLocal(), CService::GetPort(), GetStateString(), GetStatus(), GetTypeString(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CNetAddr::IsIPv4(), IsSelectableSocket(), CMasternode::IsValidNetAddr(), LogPrint, LogPrintf, Lookup(), CBaseChainParams::MAIN, MASTERNODE_REMOTE, nConnectTimeout, nState, Params(), CBaseChainParams::REGTEST, CActiveMasternodeInfo::service, strNotCapableReason, strprintf, and CService::ToString().
Referenced by ManageState().
ManageStateRemote()
void CActiveLegacyMasternodeManager::ManageStateRemote () private
Definition at line 410 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_NOT_CAPABLE, ACTIVE_MASTERNODE_STARTED, activeMasternodeInfo, masternode_info_t::addr, CMasternodeMan::CheckMasternode(), deterministicMNManager, fPingerEnabled, CDeterministicMNManager::GetListAtChainTip(), CMasternodeMan::GetMasternodeInfo(), CDeterministicMNList::GetMNByCollateral(), GetStateString(), GetStatus(), GetTypeString(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CMasternode::IsValidStateForAutoStart(), CActiveMasternodeInfo::legacyKeyIDOperator, LogPrint, LogPrintf, mnodeman, masternode_info_t::nActiveState, masternode_info_t::nProtocolVersion, nState, CActiveMasternodeInfo::outpoint, masternode_info_t::outpoint, PROTOCOL_VERSION, CActiveMasternodeInfo::service, CMasternode::StateToString(), strNotCapableReason, strprintf, and base_blob< BITS >::ToString().
Referenced by ManageState().
SendMasternodePing()
bool CActiveLegacyMasternodeManager::SendMasternodePing (CConnman & connman) private
Ping Masternode.
Definition at line 273 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_NOT_CAPABLE, activeMasternodeInfo, deterministicMNManager, fPingerEnabled, CMasternodePing::fSentinelIsCurrent, GetAdjustedTime(), GetStateString(), CMasternodeMan::Has(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CMasternodeMan::IsMasternodePingedWithin(), CActiveMasternodeInfo::legacyKeyIDOperator, CActiveMasternodeInfo::legacyKeyOperator, LogPrint, LogPrintf, MASTERNODE_MIN_MNP_SECONDS, MASTERNODE_SENTINEL_PING_MAX_SECONDS, mnodeman, nSentinelPingTime, CMasternodePing::nSentinelVersion, nSentinelVersion, nState, CActiveMasternodeInfo::outpoint, CMasternodePing::Relay(), CMasternodeMan::SetMasternodeLastPing(), CMasternodePing::Sign(), CMasternodePing::sigTime, strNotCapableReason, and COutPoint::ToStringShort().
Referenced by ManageState().
UpdateSentinelPing()
bool CActiveLegacyMasternodeManager::UpdateSentinelPing (int version)
Definition at line 312 of file activemasternode.cpp.
References GetAdjustedTime(), nSentinelPingTime, and nSentinelVersion.
Referenced by sentinelping().
Member Data Documentation
cs
CCriticalSection CActiveLegacyMasternodeManager::cs mutable private
Definition at line 88 of file activemasternode.h.
eType
masternode_type_enum_t CActiveLegacyMasternodeManager::eType private
Definition at line 90 of file activemasternode.h.
Referenced by GetTypeString(), ManageState(), and ManageStateInitial().
fPingerEnabled
bool CActiveLegacyMasternodeManager::fPingerEnabled private
Definition at line 92 of file activemasternode.h.
Referenced by ManageState(), ManageStateInitial(), ManageStateRemote(), and SendMasternodePing().
nSentinelPingTime
int64_t CActiveLegacyMasternodeManager::nSentinelPingTime private
Definition at line 98 of file activemasternode.h.
Referenced by SendMasternodePing(), and UpdateSentinelPing().
nSentinelVersion
uint32_t CActiveLegacyMasternodeManager::nSentinelVersion private
Definition at line 99 of file activemasternode.h.
Referenced by SendMasternodePing(), and UpdateSentinelPing().
nState
int CActiveLegacyMasternodeManager::nState
Definition at line 102 of file activemasternode.h.
Referenced by GetStateString(), GetStatus(), ManageState(), ManageStateInitial(), ManageStateRemote(), and SendMasternodePing().
strNotCapableReason
std::string CActiveLegacyMasternodeManager::strNotCapableReason
Definition at line 103 of file activemasternode.h.
Referenced by GetStatus(), ManageStateInitial(), ManageStateRemote(), and SendMasternodePing().
The documentation for this class was generated from the following files:
src/activemasternode.h
src/activemasternode.cpp
Released under the MIT license