Dash Core: CSporkManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CSporkManager Class Reference
CSporkManager is a higher-level class which manages the node's spork messages, rules for which sporks should be considered active/inactive, and processing for certain sporks (e.g.
#include <spork.h>
Public Member Functions
CSporkManager ()
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
void Clear ()
Clear is used to clear all in-memory active spork messages.
void CheckAndRemove ()
CheckAndRemove is defined to fulfill an interface as part of the on-disk cache used to cache sporks between runs.
void ProcessSpork (CNode *pfrom, const std::string &strCommand, CDataStream &vRecv, CConnman &connman)
ProcessSpork is used to handle the 'getsporks' and 'spork' p2p messages.
void ExecuteSpork (int nSporkID, int nValue)
ExecuteSpork is used to perform certain actions based on the spork value.
bool UpdateSpork (int nSporkID, int64_t nValue, CConnman &connman)
UpdateSpork is used by the spork RPC command to set a new spork value, sign and broadcast the spork message.
bool IsSporkActive (int nSporkID)
IsSporkActive returns a bool for time-based sporks, and should be used to determine whether the spork can be considered active or not.
int64_t GetSporkValue (int nSporkID)
GetSporkValue returns the spork value given a Spork ID.
int GetSporkIDByName (const std::string &strName)
GetSporkIDByName returns the internal Spork ID given the spork name.
std::string GetSporkNameByID (int nSporkID)
GetSporkNameByID returns the spork name as a string, given a Spork ID.
bool GetSporkByHash (const uint256 &hash, CSporkMessage &sporkRet)
GetSporkByHash returns a spork message given a hash of the spork message.
bool SetSporkAddress (const std::string &strAddress)
SetSporkAddress is used to set a public key ID which will be used to verify spork signatures.
bool SetMinSporkKeys (int minSporkKeys)
SetMinSporkKeys is used to set the required spork signer threshold, for a spork to be considered active.
bool SetPrivKey (const std::string &strPrivKey)
SetPrivKey is used to set a spork key to enable setting / signing of spork values.
std::string ToString () const
ToString returns the string representation of the SporkManager.
Public Attributes
ADD_SERIALIZE_METHODS
Private Member Functions
bool SporkValueIsActive (int nSporkID, int64_t &nActiveValueRet) const
SporkValueIsActive is used to get the value agreed upon by the majority of signed spork messages for a given Spork ID.
Private Attributes
CCriticalSection cs
std::map< uint256, CSporkMessage > mapSporksByHash
std::map< int, std::map< CKeyID, CSporkMessage > > mapSporksActive
std::set< CKeyID > setSporkPubKeyIDs
int nMinSporkKeys
CKey sporkPrivKey
Static Private Attributes
static const std::string SERIALIZATION_VERSION_STRING = "CSporkManager-Version-2"
Detailed Description
CSporkManager is a higher-level class which manages the node's spork messages, rules for which sporks should be considered active/inactive, and processing for certain sporks (e.g.
spork 12).
Definition at line 133 of file spork.h.
Constructor & Destructor Documentation
CSporkManager()
CSporkManager::CSporkManager () inline
Definition at line 154 of file spork.h.
Member Function Documentation
CheckAndRemove()
void CSporkManager::CheckAndRemove ()
CheckAndRemove is defined to fulfill an interface as part of the on-disk cache used to cache sporks between runs.
If sporks that are restored from cache do not have valid signatures when compared against the current spork private keys, they are removed from in-memory storage.
This method was introduced along with the spork cache.
Definition at line 65 of file spork.cpp.
References cs, LOCK, mapSporksActive, mapSporksByHash, and setSporkPubKeyIDs.
Clear()
void CSporkManager::Clear ()
Clear is used to clear all in-memory active spork messages.
Since spork public and private keys are set in init.cpp, we do not clear them here.
This method was introduced along with the spork cache.
Definition at line 56 of file spork.cpp.
References cs, LOCK, mapSporksActive, and mapSporksByHash.
ExecuteSpork()
void CSporkManager::ExecuteSpork (int nSporkID, int nValue)
ExecuteSpork is used to perform certain actions based on the spork value.
Currently only used with Spork 12.
Definition at line 198 of file spork.cpp.
References GetTime(), LogPrint, LogPrintf, ReprocessBlocks(), and SPORK_12_RECONSIDER_BLOCKS.
Referenced by ProcessSpork(), and spork().
GetSporkByHash()
bool CSporkManager::GetSporkByHash (const uint256 & hash, CSporkMessage & sporkRet)
GetSporkByHash returns a spork message given a hash of the spork message.
This is used when a requesting peer sends a MSG_SPORK inventory message with the hash, to quickly lookup and return the full spork message. We maintain a hash-based index of sporks for this reason, and this function is the access point into that index.
Definition at line 322 of file spork.cpp.
References cs, LOCK, and mapSporksByHash.
Referenced by AlreadyHave(), and ProcessGetData().
GetSporkIDByName()
int CSporkManager::GetSporkIDByName (const std::string & strName)
GetSporkIDByName returns the internal Spork ID given the spork name.
Definition at line 282 of file spork.cpp.
References LogPrint, SPORK_10_MASTERNODE_PAY_UPDATED_NODES, SPORK_12_RECONSIDER_BLOCKS, SPORK_14_REQUIRE_SENTINEL_FLAG, SPORK_15_DETERMINISTIC_MNS_ENABLED, SPORK_16_INSTANTSEND_AUTOLOCKS, SPORK_17_QUORUM_DKG_ENABLED, SPORK_2_INSTANTSEND_ENABLED, SPORK_3_INSTANTSEND_BLOCK_FILTERING, SPORK_5_INSTANTSEND_MAX_VALUE, SPORK_6_NEW_SIGS, SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT, and SPORK_9_SUPERBLOCKS_ENABLED.
Referenced by spork().
GetSporkNameByID()
std::string CSporkManager::GetSporkNameByID (int nSporkID)
GetSporkNameByID returns the spork name as a string, given a Spork ID.
Definition at line 301 of file spork.cpp.
References LogPrint, SPORK_10_MASTERNODE_PAY_UPDATED_NODES, SPORK_12_RECONSIDER_BLOCKS, SPORK_14_REQUIRE_SENTINEL_FLAG, SPORK_15_DETERMINISTIC_MNS_ENABLED, SPORK_16_INSTANTSEND_AUTOLOCKS, SPORK_17_QUORUM_DKG_ENABLED, SPORK_2_INSTANTSEND_ENABLED, SPORK_3_INSTANTSEND_BLOCK_FILTERING, SPORK_5_INSTANTSEND_MAX_VALUE, SPORK_6_NEW_SIGS, SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT, and SPORK_9_SUPERBLOCKS_ENABLED.
Referenced by spork().
GetSporkValue()
int64_t CSporkManager::GetSporkValue (int nSporkID)
GetSporkValue returns the spork value given a Spork ID.
If no active spork message has yet been received by the node, it returns the default value.
Definition at line 265 of file spork.cpp.
References cs, LOCK, LogPrint, mapSporkDefaults, and SporkValueIsActive().
Referenced by ApproximateBestSubset(), CWallet::CreateTransaction(), CGovernanceManager::GetMinVoteTime(), CDeterministicMNManager::GetSpork15Value(), CTxLockRequest::IsValid(), WalletModel::prepareTransaction(), CWallet::SelectCoinsMinConf(), and spork().
IsSporkActive()
bool CSporkManager::IsSporkActive (int nSporkID)
IsSporkActive returns a bool for time-based sporks, and should be used to determine whether the spork can be considered active or not.
For value-based sporks such as SPORK_5_INSTANTSEND_MAX_VALUE, the spork value should not be considered a timestamp, but an integer value instead, and therefore this method doesn't make sense and should not be used.
Definition at line 248 of file spork.cpp.
References cs, GetAdjustedTime(), LOCK, LogPrint, mapSporkDefaults, and SporkValueIsActive().
Referenced by CInstantSend::CanAutoLock(), CMasternodePing::CheckSignature(), CGovernanceVote::CheckSignature(), CMasternodePaymentVote::CheckSignature(), CPrivateSendQueue::CheckSignature(), CGovernanceObject::CheckSignature(), CTxLockVote::CheckSignature(), CPrivateSendBroadcastTx::CheckSignature(), CMasternodeBroadcast::CheckSignature(), ConnectBlock(), FillBlockPayments(), getblocktemplate(), CMasternodePing::GetHash(), CMasternodePayments::GetMinMasternodePaymentsProto(), CInstantSend::GetTransactionLockSignatures(), IsBlockPayeeValid(), IsBlockValueValid(), CInstantSend::IsLockedInstantSendTransaction(), CMasternode::IsValidForPayment(), CInstantSend::LockTransactionInputs(), CInstantSend::ProcessMessage(), llmq::CDummyDKG::ProcessMessage(), ProcessSpork(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), CMasternodeMan::SendVerifyReply(), SetPrivKey(), CMasternodePing::Sign(), CGovernanceVote::Sign(), CMasternodePaymentVote::Sign(), CPrivateSendQueue::Sign(), CGovernanceObject::Sign(), CTxLockVote::Sign(), CPrivateSendBroadcastTx::Sign(), CMasternodeBroadcast::Sign(), spork(), CInstantSend::TryToFinalizeLockCandidate(), llmq::CDummyDKG::UpdatedBlockTip(), UpdateSpork(), and CInstantSend::Vote().
ProcessSpork()
void CSporkManager::ProcessSpork (CNode * pfrom, const std::string & strCommand, CDataStream & vRecv, CConnman & connman)
ProcessSpork is used to handle the 'getsporks' and 'spork' p2p messages.
For 'getsporks', it sends active sporks to the requesting peer. For 'spork', it validates the spork and adds it to the internal spork storage and performs any necessary processing.
Definition at line 113 of file spork.cpp.
References chainActive, cs, cs_main, ExecuteSpork(), fLiteMode, GetAdjustedTime(), CNode::GetId(), CNode::GetSendVersion(), NetMsgType::GETSPORKS, CChain::Height(), CNode::id, IsSporkActive(), LOCK, LogPrint, LogPrintf, mapSporksActive, mapSporksByHash, Misbehaving(), CConnman::PushMessage(), CConnman::RemoveAskFor(), setSporkPubKeyIDs, NetMsgType::SPORK, spork(), SPORK_6_NEW_SIGS, SporkValueIsActive(), strprintf, CChain::Tip(), and base_blob< BITS >::ToString().
Referenced by ProcessMessage().
SerializationOp()
template<typename Stream , typename Operation > void CSporkManager::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 159 of file spork.h.
References mapSporksActive, mapSporksByHash, READWRITE, and SERIALIZATION_VERSION_STRING.
SetMinSporkKeys()
bool CSporkManager::SetMinSporkKeys (int minSporkKeys)
SetMinSporkKeys is used to set the required spork signer threshold, for a spork to be considered active.
This value must be at least a majority of the total number of spork keys, and for obvious resons cannot be larger than that number.
Definition at line 348 of file spork.cpp.
References LogPrintf, nMinSporkKeys, and setSporkPubKeyIDs.
Referenced by AppInitMain().
SetPrivKey()
bool CSporkManager::SetPrivKey (const std::string & strPrivKey)
SetPrivKey is used to set a spork key to enable setting / signing of spork values.
This will return false if the private key does not match any spork address in the set of valid spork signers (see SetSporkAddress).
Definition at line 359 of file spork.cpp.
References cs, CPubKey::GetID(), CMessageSigner::GetKeysFromSecret(), IsSporkActive(), LOCK, LogPrintf, setSporkPubKeyIDs, spork(), SPORK_6_NEW_SIGS, and sporkPrivKey.
Referenced by AppInitMain().
SetSporkAddress()
bool CSporkManager::SetSporkAddress (const std::string & strAddress)
SetSporkAddress is used to set a public key ID which will be used to verify spork signatures.
This can be called multiple times to add multiple keys to the set of valid spork signers.
Definition at line 336 of file spork.cpp.
References cs, CBitcoinAddress::GetKeyID(), CBitcoinAddress::IsValid(), LOCK, LogPrintf, and setSporkPubKeyIDs.
Referenced by AppInitMain().
SporkValueIsActive()
bool CSporkManager::SporkValueIsActive (int nSporkID, int64_t & nActiveValueRet) const private
SporkValueIsActive is used to get the value agreed upon by the majority of signed spork messages for a given Spork ID.
Definition at line 35 of file spork.cpp.
References cs, LOCK, mapSporksActive, and nMinSporkKeys.
Referenced by GetSporkValue(), IsSporkActive(), and ProcessSpork().
ToString()
std::string CSporkManager::ToString () const
ToString returns the string representation of the SporkManager.
Definition at line 387 of file spork.cpp.
References cs, LOCK, mapSporksActive, and strprintf.
UpdateSpork()
bool CSporkManager::UpdateSpork (int nSporkID, int64_t nValue, CConnman & connman)
UpdateSpork is used by the spork RPC command to set a new spork value, sign and broadcast the spork message.
Definition at line 227 of file spork.cpp.
References cs, GetAdjustedTime(), IsSporkActive(), LOCK, LogPrintf, mapSporksActive, mapSporksByHash, setSporkPubKeyIDs, spork(), SPORK_6_NEW_SIGS, and sporkPrivKey.
Referenced by spork().
Member Data Documentation
ADD_SERIALIZE_METHODS
CSporkManager::ADD_SERIALIZE_METHODS
Definition at line 156 of file spork.h.
cs
CCriticalSection CSporkManager::cs mutable private
Definition at line 138 of file spork.h.
Referenced by CheckAndRemove(), Clear(), GetSporkByHash(), GetSporkValue(), IsSporkActive(), ProcessSpork(), SetPrivKey(), SetSporkAddress(), SporkValueIsActive(), ToString(), and UpdateSpork().
mapSporksActive
std::map<int, std::map<CKeyID, CSporkMessage> > CSporkManager::mapSporksActive private
Definition at line 140 of file spork.h.
Referenced by CheckAndRemove(), Clear(), ProcessSpork(), SerializationOp(), SporkValueIsActive(), ToString(), and UpdateSpork().
mapSporksByHash
std::map<uint256, CSporkMessage> CSporkManager::mapSporksByHash private
Definition at line 139 of file spork.h.
Referenced by CheckAndRemove(), Clear(), GetSporkByHash(), ProcessSpork(), SerializationOp(), and UpdateSpork().
nMinSporkKeys
int CSporkManager::nMinSporkKeys private
Definition at line 143 of file spork.h.
Referenced by SetMinSporkKeys(), and SporkValueIsActive().
SERIALIZATION_VERSION_STRING
const std::string CSporkManager::SERIALIZATION_VERSION_STRING = "CSporkManager-Version-2" static private
Definition at line 136 of file spork.h.
Referenced by SerializationOp().
setSporkPubKeyIDs
std::set<CKeyID> CSporkManager::setSporkPubKeyIDs private
Definition at line 142 of file spork.h.
Referenced by CheckAndRemove(), ProcessSpork(), SetMinSporkKeys(), SetPrivKey(), SetSporkAddress(), and UpdateSpork().
sporkPrivKey
CKey CSporkManager::sporkPrivKey private
Definition at line 144 of file spork.h.
Referenced by SetPrivKey(), and UpdateSpork().
The documentation for this class was generated from the following files:
src/spork.h
src/spork.cpp
Released under the MIT license