Dash Core: MasternodeList Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
MasternodeList Class Reference
Masternode Manager page widget.
#include <masternodelist.h>
Public Slots
void updateMyMasternodeInfo (QString strAlias, QString strAddr, const COutPoint &outpoint)
void updateMyNodeList (bool fForce=false)
void updateNodeList ()
void updateDIP3List ()
Signals
void doubleClicked (const QModelIndex &)
Public Member Functions
MasternodeList (const PlatformStyle *platformStyle, QWidget *parent=0)
~MasternodeList ()
void setClientModel (ClientModel *clientModel)
void setWalletModel (WalletModel *walletModel)
void ShowQRCode (std::string strAlias)
void StartAlias (std::string strAlias)
void StartAll (std::string strCommand="start-all")
CDeterministicMNCPtr GetSelectedDIP3MN ()
Private Slots
void showContextMenu (const QPoint &)
void showContextMenuDIP3 (const QPoint &)
void on_filterLineEdit_textChanged (const QString &strFilterIn)
void on_filterLineEditDIP3_textChanged (const QString &strFilterIn)
void on_QRButton_clicked ()
void on_startButton_clicked ()
void on_startAllButton_clicked ()
void on_startMissingButton_clicked ()
void on_tableWidgetMyMasternodes_itemSelectionChanged ()
void on_UpdateButton_clicked ()
void on_checkBoxMyMasternodesOnly_stateChanged (int state)
void extraInfoDIP3_clicked ()
void copyProTxHash_clicked ()
void copyCollateralOutpoint_clicked ()
Private Attributes
QMenu * contextMenu
QMenu * contextMenuDIP3
int64_t nTimeFilterUpdated
int64_t nTimeFilterUpdatedDIP3
bool fFilterUpdated
bool fFilterUpdatedDIP3
QTimer * timer
Ui::MasternodeList * ui
ClientModel * clientModel
WalletModel * walletModel
CCriticalSection cs_mnlist
CCriticalSection cs_mymnlist
CCriticalSection cs_dip3list
QString strCurrentFilter
QString strCurrentFilterDIP3
Detailed Description
Masternode Manager page widget.
Definition at line 32 of file masternodelist.h.
Constructor & Destructor Documentation
MasternodeList()
MasternodeList::MasternodeList (const PlatformStyle * platformStyle, QWidget * parent = 0) explicit
Definition at line 35 of file masternodelist.cpp.
References contextMenu, contextMenuDIP3, copyCollateralOutpoint_clicked(), copyProTxHash_clicked(), doubleClicked(), extraInfoDIP3_clicked(), fFilterUpdated, fFilterUpdatedDIP3, GetTime(), nTimeFilterUpdated, nTimeFilterUpdatedDIP3, on_QRButton_clicked(), on_startButton_clicked(), showContextMenu(), showContextMenuDIP3(), timer, ui, updateDIP3List(), updateMyNodeList(), and updateNodeList().
~MasternodeList()
MasternodeList::~MasternodeList ()
Definition at line 120 of file masternodelist.cpp.
References ui.
Member Function Documentation
copyCollateralOutpoint_clicked
void MasternodeList::copyCollateralOutpoint_clicked () private slot
Definition at line 791 of file masternodelist.cpp.
References GetSelectedDIP3MN().
Referenced by MasternodeList().
copyProTxHash_clicked
void MasternodeList::copyProTxHash_clicked () private slot
Definition at line 781 of file masternodelist.cpp.
References GetSelectedDIP3MN().
Referenced by MasternodeList().
doubleClicked
void MasternodeList::doubleClicked (const QModelIndex &) signal
Referenced by MasternodeList().
extraInfoDIP3_clicked
void MasternodeList::extraInfoDIP3_clicked () private slot
Definition at line 764 of file masternodelist.cpp.
References GetSelectedDIP3MN(), UniValue::VOBJ, and UniValue::write().
Referenced by MasternodeList().
GetSelectedDIP3MN()
CDeterministicMNCPtr MasternodeList::GetSelectedDIP3MN ()
Definition at line 741 of file masternodelist.cpp.
References cs_dip3list, deterministicMNManager, CDeterministicMNManager::GetListAtChainTip(), CDeterministicMNList::GetMN(), LOCK, base_blob< BITS >::SetHex(), and ui.
Referenced by copyCollateralOutpoint_clicked(), copyProTxHash_clicked(), and extraInfoDIP3_clicked().
on_checkBoxMyMasternodesOnly_stateChanged
void MasternodeList::on_checkBoxMyMasternodesOnly_stateChanged (int state) private slot
Definition at line 734 of file masternodelist.cpp.
References fFilterUpdatedDIP3, GetTime(), MASTERNODELIST_FILTER_COOLDOWN_SECONDS, and nTimeFilterUpdatedDIP3.
on_filterLineEdit_textChanged
void MasternodeList::on_filterLineEdit_textChanged (const QString & strFilterIn) private slot
Definition at line 543 of file masternodelist.cpp.
References fFilterUpdated, GetTime(), MASTERNODELIST_FILTER_COOLDOWN_SECONDS, nTimeFilterUpdated, strCurrentFilter, strprintf, and ui.
on_filterLineEditDIP3_textChanged
void MasternodeList::on_filterLineEditDIP3_textChanged (const QString & strFilterIn) private slot
Definition at line 551 of file masternodelist.cpp.
References fFilterUpdatedDIP3, GetTime(), MASTERNODELIST_FILTER_COOLDOWN_SECONDS, nTimeFilterUpdatedDIP3, strCurrentFilterDIP3, strprintf, and ui.
on_QRButton_clicked
void MasternodeList::on_QRButton_clicked () private slot
Definition at line 664 of file masternodelist.cpp.
References cs_mymnlist, LOCK, ShowQRCode(), and ui.
Referenced by MasternodeList().
on_startAllButton_clicked
void MasternodeList::on_startAllButton_clicked () private slot
Definition at line 597 of file masternodelist.cpp.
References ctx, WalletModel::getEncryptionStatus(), WalletModel::Locked, WalletModel::requestUnlock(), StartAll(), WalletModel::UnlockedForMixingOnly, and walletModel.
on_startButton_clicked
void MasternodeList::on_startButton_clicked () private slot
Definition at line 559 of file masternodelist.cpp.
References cs_mymnlist, ctx, WalletModel::getEncryptionStatus(), LOCK, WalletModel::Locked, WalletModel::requestUnlock(), StartAlias(), ui, WalletModel::UnlockedForMixingOnly, and walletModel.
Referenced by MasternodeList().
on_startMissingButton_clicked
void MasternodeList::on_startMissingButton_clicked () private slot
Definition at line 621 of file masternodelist.cpp.
References ctx, WalletModel::getEncryptionStatus(), CMasternodeSync::IsMasternodeListSynced(), WalletModel::Locked, masternodeSync, WalletModel::requestUnlock(), StartAll(), WalletModel::UnlockedForMixingOnly, and walletModel.
on_tableWidgetMyMasternodes_itemSelectionChanged
void MasternodeList::on_tableWidgetMyMasternodes_itemSelectionChanged () private slot
Definition at line 652 of file masternodelist.cpp.
References ui.
on_UpdateButton_clicked
void MasternodeList::on_UpdateButton_clicked () private slot
Definition at line 659 of file masternodelist.cpp.
References updateMyNodeList().
setClientModel()
void MasternodeList::setClientModel (ClientModel * clientModel)
Definition at line 125 of file masternodelist.cpp.
References clientModel, and updateNodeList().
Referenced by WalletView::setClientModel().
setWalletModel()
void MasternodeList::setWalletModel (WalletModel * walletModel)
Definition at line 134 of file masternodelist.cpp.
References walletModel.
Referenced by WalletView::setWalletModel().
showContextMenu
void MasternodeList::showContextMenu (const QPoint & point) private slot
Definition at line 139 of file masternodelist.cpp.
References contextMenu, and ui.
Referenced by MasternodeList().
showContextMenuDIP3
void MasternodeList::showContextMenuDIP3 (const QPoint & point) private slot
Definition at line 145 of file masternodelist.cpp.
References contextMenuDIP3, and ui.
Referenced by MasternodeList().
ShowQRCode()
void MasternodeList::ShowQRCode (std::string strAlias)
Definition at line 683 of file masternodelist.cpp.
References atoi(), DateTimeStrFormat(), DEFAULT_DAEMON_VERSION, DEFAULT_SENTINEL_VERSION, DurationToDHMS(), FormatVersion(), CMasternodeMan::Get(), CMasternodeConfig::getEntries(), CPubKey::GetID(), GetOffsetFromUtc(), WalletModel::getOptionsModel(), GUIUtil::HtmlEscape(), CMasternode::lastPing, masternodeConfig, mnodeman, masternode_info_t::nActiveState, CMasternodePing::nDaemonVersion, masternode_info_t::nProtocolVersion, CMasternodePing::nSentinelVersion, masternode_info_t::pubKeyCollateralAddress, SafeIntVersionToString(), QRDialog::setInfo(), QRDialog::setModel(), CMasternodePing::sigTime, masternode_info_t::sigTime, CMasternode::StateToString(), uint256S(), and walletModel.
Referenced by on_QRButton_clicked().
StartAlias()
void MasternodeList::StartAlias (std::string strAlias)
Definition at line 162 of file masternodelist.cpp.
References CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::Create(), g_connman, CMasternodeConfig::getEntries(), masternodeConfig, mnodeman, CMasternodeMan::NotifyMasternodeUpdates(), and updateMyNodeList().
Referenced by on_startButton_clicked().
StartAll()
void MasternodeList::StartAll (std::string strCommand = "start-all")
Definition at line 198 of file masternodelist.cpp.
References CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::Create(), g_connman, CMasternodeConfig::getEntries(), CMasternodeMan::Has(), masternodeConfig, mnodeman, CMasternodeMan::NotifyMasternodeUpdates(), ParseInt32(), strprintf, uint256S(), and updateMyNodeList().
Referenced by on_startAllButton_clicked(), and on_startMissingButton_clicked().
updateDIP3List
void MasternodeList::updateDIP3List () slot
Definition at line 413 of file masternodelist.cpp.
References CheckWalletOwnsScript(), cs_dip3list, CWallet::cs_wallet, deterministicMNManager, ExtractDestination(), fFilterUpdatedDIP3, CDeterministicMNManager::GetListAtChainTip(), CDeterministicMNList::GetProjectedMNPayees(), GetTime(), CWallet::HaveKey(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CWallet::ListProTxCoins(), LOCK, MASTERNODELIST_FILTER_COOLDOWN_SECONDS, MASTERNODELIST_UPDATE_SECONDS, nTimeFilterUpdatedDIP3, pwalletMain, ShutdownRequested(), strCurrentFilterDIP3, strprintf, TRY_LOCK, and ui.
Referenced by MasternodeList().
updateMyMasternodeInfo
void MasternodeList::updateMyMasternodeInfo (QString strAlias, QString strAddr, const COutPoint & outpoint) slot
Definition at line 247 of file masternodelist.cpp.
References masternode_info_t::addr, DateTimeStrFormat(), DurationToDHMS(), CMasternodeMan::GetMasternodeInfo(), GetOffsetFromUtc(), masternode_info_t::keyIDCollateralAddress, mnodeman, masternode_info_t::nActiveState, masternode_info_t::nProtocolVersion, masternode_info_t::nTimeLastPing, masternode_info_t::sigTime, CMasternode::StateToString(), CBase58Data::ToString(), CService::ToString(), and ui.
Referenced by updateMyNodeList().
updateMyNodeList
void MasternodeList::updateMyNodeList (bool fForce = false) slot
Definition at line 286 of file masternodelist.cpp.
References cs_mymnlist, deterministicMNManager, CMasternodeConfig::getEntries(), GetTime(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), masternodeConfig, MY_MASTERNODELIST_UPDATE_SECONDS, ParseInt32(), ShutdownRequested(), TRY_LOCK, ui, uint256S(), and updateMyMasternodeInfo().
Referenced by MasternodeList(), on_UpdateButton_clicked(), StartAlias(), and StartAll().
updateNodeList
void MasternodeList::updateNodeList () slot
Definition at line 329 of file masternodelist.cpp.
References masternode_info_t::addr, cs_mnlist, DateTimeStrFormat(), deterministicMNManager, DurationToDHMS(), fFilterUpdated, CMasternodeMan::GetFullMasternodeMap(), GetOffsetFromUtc(), CMasternode::GetStatus(), GetTime(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), masternode_info_t::keyIDCollateralAddress, CMasternode::lastPing, MASTERNODELIST_FILTER_COOLDOWN_SECONDS, MASTERNODELIST_UPDATE_SECONDS, mnodeman, masternode_info_t::nProtocolVersion, nTimeFilterUpdated, ShutdownRequested(), CMasternodePing::sigTime, masternode_info_t::sigTime, strCurrentFilter, strprintf, CBase58Data::ToString(), CService::ToString(), TRY_LOCK, and ui.
Referenced by MasternodeList(), and setClientModel().
Member Data Documentation
clientModel
ClientModel* MasternodeList::clientModel private
Definition at line 67 of file masternodelist.h.
Referenced by setClientModel().
contextMenu
QMenu* MasternodeList::contextMenu private
Definition at line 48 of file masternodelist.h.
Referenced by MasternodeList(), and showContextMenu().
contextMenuDIP3
QMenu* MasternodeList::contextMenuDIP3 private
Definition at line 49 of file masternodelist.h.
Referenced by MasternodeList(), and showContextMenuDIP3().
cs_dip3list
CCriticalSection MasternodeList::cs_dip3list private
Definition at line 77 of file masternodelist.h.
Referenced by GetSelectedDIP3MN(), and updateDIP3List().
cs_mnlist
CCriticalSection MasternodeList::cs_mnlist private
Definition at line 71 of file masternodelist.h.
Referenced by updateNodeList().
cs_mymnlist
CCriticalSection MasternodeList::cs_mymnlist private
Definition at line 74 of file masternodelist.h.
Referenced by on_QRButton_clicked(), on_startButton_clicked(), and updateMyNodeList().
fFilterUpdated
bool MasternodeList::fFilterUpdated private
Definition at line 52 of file masternodelist.h.
Referenced by MasternodeList(), on_filterLineEdit_textChanged(), and updateNodeList().
fFilterUpdatedDIP3
bool MasternodeList::fFilterUpdatedDIP3 private
Definition at line 53 of file masternodelist.h.
Referenced by MasternodeList(), on_checkBoxMyMasternodesOnly_stateChanged(), on_filterLineEditDIP3_textChanged(), and updateDIP3List().
nTimeFilterUpdated
int64_t MasternodeList::nTimeFilterUpdated private
Definition at line 50 of file masternodelist.h.
Referenced by MasternodeList(), on_filterLineEdit_textChanged(), and updateNodeList().
nTimeFilterUpdatedDIP3
int64_t MasternodeList::nTimeFilterUpdatedDIP3 private
Definition at line 51 of file masternodelist.h.
Referenced by MasternodeList(), on_checkBoxMyMasternodesOnly_stateChanged(), on_filterLineEditDIP3_textChanged(), and updateDIP3List().
strCurrentFilter
QString MasternodeList::strCurrentFilter private
Definition at line 79 of file masternodelist.h.
Referenced by on_filterLineEdit_textChanged(), and updateNodeList().
strCurrentFilterDIP3
QString MasternodeList::strCurrentFilterDIP3 private
Definition at line 80 of file masternodelist.h.
Referenced by on_filterLineEditDIP3_textChanged(), and updateDIP3List().
timer
QTimer* MasternodeList::timer private
Definition at line 65 of file masternodelist.h.
Referenced by MasternodeList().
ui
Ui::MasternodeList* MasternodeList::ui private
Definition at line 66 of file masternodelist.h.
Referenced by GetSelectedDIP3MN(), MasternodeList(), on_filterLineEdit_textChanged(), on_filterLineEditDIP3_textChanged(), on_QRButton_clicked(), on_startButton_clicked(), on_tableWidgetMyMasternodes_itemSelectionChanged(), showContextMenu(), showContextMenuDIP3(), updateDIP3List(), updateMyMasternodeInfo(), updateMyNodeList(), updateNodeList(), and ~MasternodeList().
walletModel
WalletModel* MasternodeList::walletModel private
Definition at line 68 of file masternodelist.h.
Referenced by on_startAllButton_clicked(), on_startButton_clicked(), on_startMissingButton_clicked(), setWalletModel(), and ShowQRCode().
The documentation for this class was generated from the following files:
src/qt/masternodelist.h
src/qt/masternodelist.cpp
Released under the MIT license