Dash Core: llmq::CDummyDKG Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
llmq::CDummyDKG Class Reference
#include <quorums_dummydkg.h>
Public Member Functions
void ProcessMessage (CNode *pfrom, const std::string &strCommand, CDataStream &vRecv, CConnman &connman)
void ProcessDummyContribution (NodeId from, const CDummyContribution &qc)
void ProcessDummyCommitment (NodeId from, const CDummyCommitment &qc)
void UpdatedBlockTip (const CBlockIndex *pindex, bool fInitialDownload)
void CreateDummyContribution (Consensus::LLMQType llmqType, const CBlockIndex *pindex)
void CreateDummyCommitment (Consensus::LLMQType llmqType, const CBlockIndex *pindex)
void CreateFinalCommitment (Consensus::LLMQType llmqType, const CBlockIndex *pindex)
bool HasDummyContribution (const uint256 &hash)
bool GetDummyContribution (const uint256 &hash, CDummyContribution &ret)
bool HasDummyCommitment (const uint256 &hash)
bool GetDummyCommitment (const uint256 &hash, CDummyCommitment &ret)
Private Member Functions
std::vector< bool > GetValidMembers (Consensus::LLMQType llmqType, const std::vector< CDeterministicMNCPtr > &members)
BLSSecretKeyVector BuildDeterministicSvec (Consensus::LLMQType llmqType, const uint256 &quorumHash)
BLSPublicKeyVector BuildVvec (const BLSSecretKeyVector &svec)
Private Attributes
CCriticalSection sessionCs
std::map< Consensus::LLMQType, CDummyDKGSession > curSessions
Detailed Description
Definition at line 126 of file quorums_dummydkg.h.
Member Function Documentation
BuildDeterministicSvec()
BLSSecretKeyVector llmq::CDummyDKG::BuildDeterministicSvec (Consensus::LLMQType llmqType, const uint256 & quorumHash) private
Definition at line 520 of file quorums_dummydkg.cpp.
References base_blob< BITS >::begin(), CHash256::Finalize(), CChainParams::GetConsensus(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), Consensus::Params::llmqs, Params(), SerializeHash(), CBLSWrapper< ImplType, _SerSize, C >::SetBuf(), base_blob< BITS >::size(), and CHash256::Write().
Referenced by CreateDummyCommitment(), CreateFinalCommitment(), and ProcessDummyCommitment().
BuildVvec()
BLSPublicKeyVector llmq::CDummyDKG::BuildVvec (const BLSSecretKeyVector & svec) private
Definition at line 548 of file quorums_dummydkg.cpp.
Referenced by CreateDummyCommitment(), CreateFinalCommitment(), and ProcessDummyCommitment().
CreateDummyCommitment()
void llmq::CDummyDKG::CreateDummyCommitment (Consensus::LLMQType llmqType, const CBlockIndex * pindex)
Definition at line 358 of file quorums_dummydkg.cpp.
References activeMasternodeInfo, CActiveMasternodeInfo::blsKeyOperator, llmq::CLLMQUtils::BuildCommitmentHash(), BuildDeterministicSvec(), BuildVvec(), chainActive, count, cs_main, CBLSId::FromHash(), llmq::CLLMQUtils::GetAllQuorumMembers(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), GetValidMembers(), Consensus::Params::llmqs, llmq::CDummyCommitment::llmqType, LOCK, llmq::CDummyCommitment::membersSig, CBlockIndex::nHeight, CActiveMasternodeInfo::outpoint, Params(), ProcessDummyCommitment(), llmq::CDummyCommitment::quorumHash, llmq::CDummyCommitment::quorumSig, CBLSSecretKey::SecretKeyShare(), SerializeHash(), CBLSSecretKey::Sign(), llmq::CDummyCommitment::signer, and llmq::CDummyCommitment::validMembers.
Referenced by UpdatedBlockTip().
CreateDummyContribution()
void llmq::CDummyDKG::CreateDummyContribution (Consensus::LLMQType llmqType, const CBlockIndex * pindex)
Definition at line 321 of file quorums_dummydkg.cpp.
References activeMasternodeInfo, CActiveMasternodeInfo::blsKeyOperator, chainActive, cs_main, llmq::CLLMQUtils::GetAllQuorumMembers(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), llmq::CDummyContribution::GetSignHash(), Consensus::Params::llmqs, llmq::CDummyContribution::llmqType, LOCK, CBlockIndex::nHeight, CActiveMasternodeInfo::outpoint, Params(), ProcessDummyContribution(), llmq::CDummyContribution::quorumHash, llmq::CDummyContribution::sig, and llmq::CDummyContribution::signer.
Referenced by UpdatedBlockTip().
CreateFinalCommitment()
void llmq::CDummyDKG::CreateFinalCommitment (Consensus::LLMQType llmqType, const CBlockIndex * pindex)
Definition at line 413 of file quorums_dummydkg.cpp.
References llmq::CQuorumBlockProcessor::AddMinableCommitment(), CBLSSignature::AggregateSecure(), BuildDeterministicSvec(), BuildVvec(), chainActive, llmq::CFinalCommitment::CountSigners(), llmq::CFinalCommitment::CountValidMembers(), cs_main, curSessions, CBLSId::FromHash(), llmq::CLLMQUtils::GetAllQuorumMembers(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), Consensus::Params::llmqs, llmq::CFinalCommitment::llmqType, LOCK, LogPrintf, llmq::CFinalCommitment::membersSig, CBlockIndex::nHeight, Params(), llmq::quorumBlockProcessor, llmq::CFinalCommitment::quorumHash, llmq::CFinalCommitment::quorumPublicKey, llmq::CFinalCommitment::quorumSig, llmq::CFinalCommitment::quorumVvecHash, CBLSSignature::Recover(), SerializeHash(), sessionCs, llmq::CFinalCommitment::signers, base_blob< BITS >::ToString(), llmq::CFinalCommitment::validMembers, and llmq::CFinalCommitment::Verify().
Referenced by UpdatedBlockTip().
GetDummyCommitment()
bool llmq::CDummyDKG::GetDummyCommitment (const uint256 & hash, CDummyCommitment & ret)
Definition at line 595 of file quorums_dummydkg.cpp.
References curSessions, LOCK, and sessionCs.
GetDummyContribution()
bool llmq::CDummyDKG::GetDummyContribution (const uint256 & hash, CDummyContribution & ret)
Definition at line 570 of file quorums_dummydkg.cpp.
References curSessions, LOCK, and sessionCs.
GetValidMembers()
std::vector< bool > llmq::CDummyDKG::GetValidMembers (Consensus::LLMQType llmqType, const std::vector< CDeterministicMNCPtr > & members) private
Definition at line 499 of file quorums_dummydkg.cpp.
References curSessions, CChainParams::GetConsensus(), Consensus::Params::llmqs, LOCK, Params(), and sessionCs.
Referenced by CreateDummyCommitment().
HasDummyCommitment()
bool llmq::CDummyDKG::HasDummyCommitment (const uint256 & hash)
Definition at line 583 of file quorums_dummydkg.cpp.
References curSessions, LOCK, and sessionCs.
Referenced by AlreadyHave().
HasDummyContribution()
bool llmq::CDummyDKG::HasDummyContribution (const uint256 & hash)
Definition at line 558 of file quorums_dummydkg.cpp.
References curSessions, LOCK, and sessionCs.
Referenced by AlreadyHave().
ProcessDummyCommitment()
void llmq::CDummyDKG::ProcessDummyCommitment (NodeId from, const CDummyCommitment & qc)
Definition at line 156 of file quorums_dummydkg.cpp.
References llmq::CLLMQUtils::BuildCommitmentHash(), BuildDeterministicSvec(), BuildVvec(), chainActive, llmq::CDummyCommitment::CountValidMembers(), cs_main, curSessions, DMN_PROTO_VERSION, CBLSId::FromHash(), g_connman, llmq::CLLMQUtils::GetAllQuorumMembers(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), CChain::Height(), Consensus::Params::llmqs, llmq::CDummyCommitment::llmqType, LOCK, LogPrintf, llmq::CDummyCommitment::membersSig, Misbehaving(), MSG_QUORUM_DUMMY_COMMITMENT, Params(), CBLSPublicKey::PublicKeyShare(), llmq::CDummyCommitment::quorumHash, llmq::CDummyCommitment::quorumSig, SerializeHash(), sessionCs, llmq::CDummyCommitment::signer, base_blob< BITS >::ToString(), llmq::CDummyCommitment::validMembers, and CBLSSignature::VerifyInsecure().
Referenced by CreateDummyCommitment(), and ProcessMessage().
ProcessDummyContribution()
void llmq::CDummyDKG::ProcessDummyContribution (NodeId from, const CDummyContribution & qc)
Definition at line 73 of file quorums_dummydkg.cpp.
References chainActive, cs_main, curSessions, DMN_PROTO_VERSION, g_connman, llmq::CLLMQUtils::GetAllQuorumMembers(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), llmq::CDummyContribution::GetSignHash(), CChain::Height(), Consensus::Params::llmqs, llmq::CDummyContribution::llmqType, LOCK, LogPrintf, Misbehaving(), MSG_QUORUM_DUMMY_CONTRIBUTION, Params(), llmq::CDummyContribution::quorumHash, SerializeHash(), sessionCs, llmq::CDummyContribution::sig, llmq::CDummyContribution::signer, base_blob< BITS >::ToString(), and CBLSSignature::VerifyInsecure().
Referenced by CreateDummyContribution(), and ProcessMessage().
ProcessMessage()
void llmq::CDummyDKG::ProcessMessage (CNode * pfrom, const std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 28 of file quorums_dummydkg.cpp.
References cs_main, CNode::id, CSporkManager::IsSporkActive(), LOCK, Misbehaving(), Params(), ProcessDummyCommitment(), ProcessDummyContribution(), NetMsgType::QCONTRIB, NetMsgType::QDCOMMITMENT, CConnman::RemoveAskFor(), SerializeHash(), SPORK_17_QUORUM_DKG_ENABLED, and sporkManager.
Referenced by ProcessMessage().
UpdatedBlockTip()
void llmq::CDummyDKG::UpdatedBlockTip (const CBlockIndex * pindex, bool fInitialDownload)
Definition at line 289 of file quorums_dummydkg.cpp.
References chainActive, CreateDummyCommitment(), CreateDummyContribution(), CreateFinalCommitment(), Consensus::DEPLOYMENT_DIP0003, fMasternodeMode, CChainParams::GetConsensus(), CSporkManager::IsSporkActive(), Consensus::Params::llmqs, CBlockIndex::nHeight, Params(), SPORK_17_QUORUM_DKG_ENABLED, sporkManager, THRESHOLD_ACTIVE, CChain::Tip(), versionbitscache, and VersionBitsState().
Referenced by CDSNotificationInterface::UpdatedBlockTip().
Member Data Documentation
curSessions
std::map<Consensus::LLMQType, CDummyDKGSession> llmq::CDummyDKG::curSessions private
Definition at line 130 of file quorums_dummydkg.h.
Referenced by CreateFinalCommitment(), GetDummyCommitment(), GetDummyContribution(), GetValidMembers(), HasDummyCommitment(), HasDummyContribution(), ProcessDummyCommitment(), and ProcessDummyContribution().
sessionCs
CCriticalSection llmq::CDummyDKG::sessionCs private
Definition at line 129 of file quorums_dummydkg.h.
Referenced by CreateFinalCommitment(), GetDummyCommitment(), GetDummyContribution(), GetValidMembers(), HasDummyCommitment(), HasDummyContribution(), ProcessDummyCommitment(), and ProcessDummyContribution().
The documentation for this class was generated from the following files:
src/llmq/quorums_dummydkg.h
src/llmq/quorums_dummydkg.cpp
Released under the MIT license