Dash Core: llmq::CLLMQUtils Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
llmq::CLLMQUtils Class Reference
#include <quorums_utils.h>
Static Public Member Functions
static std::vector< CDeterministicMNCPtr > GetAllQuorumMembers (Consensus::LLMQType llmqType, const uint256 &blockHash)
static uint256 BuildCommitmentHash (uint8_t llmqType, const uint256 &blockHash, const std::vector< bool > &validMembers, const CBLSPublicKey &pubKey, const uint256 &vvecHash)
Detailed Description
Definition at line 17 of file quorums_utils.h.
Member Function Documentation
BuildCommitmentHash()
uint256 llmq::CLLMQUtils::BuildCommitmentHash (uint8_t llmqType, const uint256 & blockHash, const std::vector< bool > & validMembers, const CBLSPublicKey & pubKey, const uint256 & vvecHash) static
Definition at line 21 of file quorums_utils.cpp.
References DYNBITSET, CHashWriter::GetHash(), and SER_NETWORK.
Referenced by llmq::CDummyDKG::CreateDummyCommitment(), llmq::CDummyDKG::ProcessDummyCommitment(), and llmq::CFinalCommitment::Verify().
GetAllQuorumMembers()
std::vector< CDeterministicMNCPtr > llmq::CLLMQUtils::GetAllQuorumMembers (Consensus::LLMQType llmqType, const uint256 & blockHash) static
Definition at line 13 of file quorums_utils.cpp.
References deterministicMNManager, CChainParams::GetConsensus(), CDeterministicMNManager::GetListForBlock(), Consensus::Params::llmqs, Params(), and SerializeHash().
Referenced by llmq::CheckLLMQCommitment(), llmq::CDummyDKG::CreateDummyCommitment(), llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::CreateFinalCommitment(), CDeterministicMNManager::HandleQuorumCommitment(), llmq::CQuorumBlockProcessor::ProcessCommitment(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), and llmq::CQuorumBlockProcessor::ProcessMessage().
The documentation for this class was generated from the following files:
src/llmq/quorums_utils.h
src/llmq/quorums_utils.cpp
Released under the MIT license