Dash Core: CTxLockCandidate Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CTxLockCandidate Class Reference
An InstantSend transaction lock candidate.
#include <instantx.h>
Public Member Functions
CTxLockCandidate ()
CTxLockCandidate (const CTxLockRequest &txLockRequestIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
uint256 GetHash () const
void AddOutPointLock (const COutPoint &outpoint)
void MarkOutpointAsAttacked (const COutPoint &outpoint)
bool AddVote (const CTxLockVote &vote)
bool IsAllOutPointsReady () const
bool HasMasternodeVoted (const COutPoint &outpointIn, const COutPoint &outpointMasternodeIn)
int CountVotes () const
void SetConfirmedHeight (int nConfirmedHeightIn)
bool IsExpired (int nHeight) const
bool IsTimedOut () const
void Relay (CConnman &connman) const
Public Attributes
CTxLockRequest txLockRequest
std::map< COutPoint, COutPointLock > mapOutPointLocks
ADD_SERIALIZE_METHODS
Private Attributes
int nConfirmedHeight
When corresponding tx is 0-confirmed or conflicted, nConfirmedHeight is -1.
int64_t nTimeCreated
Detailed Description
An InstantSend transaction lock candidate.
Definition at line 350 of file instantx.h.
Constructor & Destructor Documentation
CTxLockCandidate() [1/2]
CTxLockCandidate::CTxLockCandidate () inline
Definition at line 357 of file instantx.h.
CTxLockCandidate() [2/2]
CTxLockCandidate::CTxLockCandidate (const CTxLockRequest & txLockRequestIn) inline
Definition at line 362 of file instantx.h.
Member Function Documentation
AddOutPointLock()
void CTxLockCandidate::AddOutPointLock (const COutPoint & outpoint)
Definition at line 1249 of file instantx.cpp.
References mapOutPointLocks.
AddVote()
bool CTxLockCandidate::AddVote (const CTxLockVote & vote)
Definition at line 1261 of file instantx.cpp.
References CTxLockVote::GetOutpoint(), and mapOutPointLocks.
Referenced by CInstantSend::ProcessNewTxLockVote(), and CInstantSend::ProcessOrphanTxLockVote().
CountVotes()
int CTxLockCandidate::CountVotes () const
Definition at line 1284 of file instantx.cpp.
References mapOutPointLocks.
Referenced by CInstantSend::ProcessNewTxLockVote(), and CInstantSend::ProcessOrphanTxLockVote().
GetHash()
uint256 CTxLockCandidate::GetHash () const inline
Definition at line 382 of file instantx.h.
References CTxLockRequest::GetHash(), and txLockRequest.
Referenced by CInstantSend::CheckAndRemove(), CInstantSend::LockTransactionInputs(), CInstantSend::ResolveConflicts(), CInstantSend::UpdateLockedTransaction(), and CInstantSend::Vote().
HasMasternodeVoted()
bool CTxLockCandidate::HasMasternodeVoted (const COutPoint & outpointIn, const COutPoint & outpointMasternodeIn)
Definition at line 1278 of file instantx.cpp.
References mapOutPointLocks.
IsAllOutPointsReady()
bool CTxLockCandidate::IsAllOutPointsReady () const
Definition at line 1268 of file instantx.cpp.
References mapOutPointLocks.
Referenced by CInstantSend::LockTransactionInputs(), CInstantSend::ResolveConflicts(), and CInstantSend::TryToFinalizeLockCandidate().
IsExpired()
bool CTxLockCandidate::IsExpired (int nHeight) const
Definition at line 1294 of file instantx.cpp.
References CChainParams::GetConsensus(), nConfirmedHeight, Consensus::Params::nInstantSendKeepLock, and Params().
Referenced by CInstantSend::CheckAndRemove().
IsTimedOut()
bool CTxLockCandidate::IsTimedOut () const
Definition at line 1300 of file instantx.cpp.
References GetTime(), INSTANTSEND_LOCK_TIMEOUT_SECONDS, and nTimeCreated.
Referenced by CInstantSend::ProcessNewTxLockVote(), and CInstantSend::ProcessOrphanTxLockVote().
MarkOutpointAsAttacked()
void CTxLockCandidate::MarkOutpointAsAttacked (const COutPoint & outpoint)
Definition at line 1254 of file instantx.cpp.
References mapOutPointLocks.
Referenced by CInstantSend::UpdateVotedOutpoints().
Relay()
void CTxLockCandidate::Relay (CConnman & connman) const
Definition at line 1305 of file instantx.cpp.
References mapOutPointLocks, CConnman::RelayTransaction(), CTxLockRequest::tx, and txLockRequest.
SerializationOp()
template<typename Stream , typename Operation > void CTxLockCandidate::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 375 of file instantx.h.
References mapOutPointLocks, nConfirmedHeight, nTimeCreated, READWRITE, and txLockRequest.
SetConfirmedHeight()
void CTxLockCandidate::SetConfirmedHeight (int nConfirmedHeightIn) inline
Definition at line 392 of file instantx.h.
References nConfirmedHeight.
Member Data Documentation
ADD_SERIALIZE_METHODS
CTxLockCandidate::ADD_SERIALIZE_METHODS
Definition at line 372 of file instantx.h.
mapOutPointLocks
std::map<COutPoint, COutPointLock> CTxLockCandidate::mapOutPointLocks
Definition at line 370 of file instantx.h.
Referenced by AddOutPointLock(), AddVote(), CInstantSend::CheckAndRemove(), CountVotes(), HasMasternodeVoted(), IsAllOutPointsReady(), CInstantSend::LockTransactionInputs(), MarkOutpointAsAttacked(), Relay(), SerializationOp(), and CInstantSend::Vote().
nConfirmedHeight
int CTxLockCandidate::nConfirmedHeight private
When corresponding tx is 0-confirmed or conflicted, nConfirmedHeight is -1.
Definition at line 353 of file instantx.h.
Referenced by IsExpired(), SerializationOp(), and SetConfirmedHeight().
nTimeCreated
int64_t CTxLockCandidate::nTimeCreated private
Definition at line 354 of file instantx.h.
Referenced by IsTimedOut(), and SerializationOp().
txLockRequest
CTxLockRequest CTxLockCandidate::txLockRequest
Definition at line 369 of file instantx.h.
Referenced by GetHash(), CInstantSend::ProcessNewTxLockVote(), CInstantSend::ProcessOrphanTxLockVote(), Relay(), CInstantSend::ResolveConflicts(), SerializationOp(), CInstantSend::TryToFinalizeLockCandidate(), and CInstantSend::UpdateLockedTransaction().
The documentation for this class was generated from the following files:
src/instantx.h
src/instantx.cpp
Released under the MIT license