Dash Core: CTxLockRequest Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CTxLockRequest Class Reference
An InstantSend transaction lock request.
#include <instantx.h>
Public Member Functions
CTxLockRequest ()
CTxLockRequest (const CTransaction &_tx)
CTxLockRequest (const CTransactionRef &_tx)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
bool IsValid () const
CAmount GetMinFee (bool fForceMinFee) const
int GetMaxSignatures () const
bool IsSimple () const
const uint256 & GetHash () const
std::string ToString () const
operator bool () const
Public Attributes
CTransactionRef tx
ADD_SERIALIZE_METHODS
Static Public Attributes
static const int WARN_MANY_INPUTS = 100
Warn for a large number of inputs to an IS tx - fees could be substantial and the number txlvote responses requested large (10 * # of inputs)
Static Private Attributes
static const CAmount MIN_FEE = 0.0001 * COIN
static const int MAX_INPUTS_FOR_AUTO_IX = 4
If transaction has less or equal inputs than MAX_INPUTS_FOR_AUTO_IX, it will be automatically locked.
Friends
bool operator== (const CTxLockRequest &a, const CTxLockRequest &b)
bool operator!= (const CTxLockRequest &a, const CTxLockRequest &b)
Detailed Description
An InstantSend transaction lock request.
Definition at line 167 of file instantx.h.
Constructor & Destructor Documentation
CTxLockRequest() [1/3]
CTxLockRequest::CTxLockRequest () inline
Definition at line 182 of file instantx.h.
Referenced by operator bool().
CTxLockRequest() [2/3]
CTxLockRequest::CTxLockRequest (const CTransaction & _tx) inline
Definition at line 183 of file instantx.h.
CTxLockRequest() [3/3]
CTxLockRequest::CTxLockRequest (const CTransactionRef & _tx) inline
Definition at line 184 of file instantx.h.
Member Function Documentation
GetHash()
const uint256& CTxLockRequest::GetHash () const inline
Definition at line 200 of file instantx.h.
References tx.
Referenced by CInstantSend::AcceptLockRequest(), CInstantSend::CreateTxLockCandidate(), CTxLockCandidate::GetHash(), IsValid(), ProcessMessage(), CInstantSend::ProcessTxLockRequest(), and CInstantSend::RejectLockRequest().
GetMaxSignatures()
int CTxLockRequest::GetMaxSignatures () const
Definition at line 1016 of file instantx.cpp.
References COutPointLock::SIGNATURES_TOTAL, and tx.
Referenced by TransactionDesc::FormatTxStatus(), CInstantSend::ProcessNewTxLockVote(), and CInstantSend::ProcessOrphanTxLockVote().
GetMinFee()
CAmount CTxLockRequest::GetMinFee (bool fForceMinFee) const
Definition at line 1007 of file instantx.cpp.
References CInstantSend::CanAutoLock(), IsSimple(), MIN_FEE, and tx.
Referenced by CWallet::CreateTransaction(), and IsValid().
IsSimple()
bool CTxLockRequest::IsSimple () const
Definition at line 1021 of file instantx.cpp.
References MAX_INPUTS_FOR_AUTO_IX, and tx.
Referenced by GetMinFee(), ProcessMessage(), and CWalletTx::RelayWalletTransaction().
IsValid()
bool CTxLockRequest::IsValid () const
Definition at line 952 of file instantx.cpp.
References AssertLockHeld, chainActive, CheckFinalTx(), COIN, cs_main, CChainParams::GetConsensus(), GetHash(), GetMinFee(), CSporkManager::GetSporkValue(), GetUTXOCoin(), CChain::Height(), LogPrint, Coin::nHeight, Consensus::Params::nInstantSendConfirmationsRequired, CTxOut::nValue, Coin::out, Params(), SPORK_5_INSTANTSEND_MAX_VALUE, sporkManager, base_blob< BITS >::ToString(), ToString(), tx, and WARN_MANY_INPUTS.
Referenced by AcceptToMemoryPoolWorker(), and CInstantSend::CreateTxLockCandidate().
operator bool()
CTxLockRequest::operator bool () const inline explicit
Definition at line 218 of file instantx.h.
References CTxLockRequest().
SerializationOp()
template<typename Stream , typename Operation > void CTxLockRequest::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 189 of file instantx.h.
References READWRITE, and tx.
ToString()
std::string CTxLockRequest::ToString () const inline
Definition at line 204 of file instantx.h.
References tx.
Referenced by IsValid().
Friends And Related Function Documentation
operator!=
bool operator!= (const CTxLockRequest & a, const CTxLockRequest & b) friend
Definition at line 213 of file instantx.h.
operator==
bool operator== (const CTxLockRequest & a, const CTxLockRequest & b) friend
Definition at line 208 of file instantx.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CTxLockRequest::ADD_SERIALIZE_METHODS
Definition at line 184 of file instantx.h.
MAX_INPUTS_FOR_AUTO_IX
const int CTxLockRequest::MAX_INPUTS_FOR_AUTO_IX = 4 static private
If transaction has less or equal inputs than MAX_INPUTS_FOR_AUTO_IX, it will be automatically locked.
Definition at line 173 of file instantx.h.
Referenced by IsSimple().
MIN_FEE
const CAmount CTxLockRequest::MIN_FEE = 0.0001 * COIN static private
Definition at line 170 of file instantx.h.
Referenced by GetMinFee().
tx
CTransactionRef CTxLockRequest::tx
Definition at line 180 of file instantx.h.
Referenced by CInstantSend::CreateTxLockCandidate(), GetHash(), GetMaxSignatures(), GetMinFee(), IsSimple(), IsValid(), ProcessMessage(), CInstantSend::ProcessTxLockRequest(), CTxLockVote::Relay(), CTxLockCandidate::Relay(), CInstantSend::ResolveConflicts(), SerializationOp(), ToString(), CInstantSend::TryToFinalizeLockCandidate(), and CInstantSend::UpdateLockedTransaction().
WARN_MANY_INPUTS
const int CTxLockRequest::WARN_MANY_INPUTS = 100 static
Warn for a large number of inputs to an IS tx - fees could be substantial and the number txlvote responses requested large (10 * # of inputs)
Definition at line 178 of file instantx.h.
Referenced by IsValid(), and WalletModel::prepareTransaction().
The documentation for this class was generated from the following files:
src/instantx.h
src/instantx.cpp
Released under the MIT license