Dash Core: CDB Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CDB Class Reference
RAII class that provides access to a Berkeley database.
#include <db.h>
Public Member Functions
void Flush ()
void Close ()
bool TxnBegin ()
bool TxnCommit ()
bool TxnAbort ()
bool ReadVersion (int &nVersion)
bool WriteVersion (int nVersion)
Static Public Member Functions
static bool Rewrite (const std::string &strFile, const char *pszSkip=NULL)
Protected Member Functions
CDB (const std::string &strFilename, const char *pszMode="r+", bool fFlushOnCloseIn=true)
~CDB ()
template<typename K , typename T >
bool Read (const K &key, T &value)
template<typename K , typename T >
bool Write (const K &key, const T &value, bool fOverwrite=true)
template<typename K >
bool Erase (const K &key)
template<typename K >
bool Exists (const K &key)
Dbc * GetCursor ()
int ReadAtCursor (Dbc *pcursor, CDataStream &ssKey, CDataStream &ssValue, bool setRange=false)
Protected Attributes
Db * pdb
std::string strFile
DbTxn * activeTxn
bool fReadOnly
bool fFlushOnClose
Private Member Functions
CDB (const CDB &)
void operator= (const CDB &)
Detailed Description
RAII class that provides access to a Berkeley database.
Definition at line 92 of file db.h.
Constructor & Destructor Documentation
CDB() [1/2]
CDB::CDB (const std::string & strFilename, const char * pszMode = "r+", bool fFlushOnCloseIn = true) explicit protected
Definition at line 237 of file db.cpp.
References bitdb, CLIENT_VERSION, CDBEnv::cs_db, CDBEnv::dbenv, Exists(), fFlushOnClose, fReadOnly, GetDataDir(), CDBEnv::IsMock(), LOCK, CDBEnv::mapDb, CDBEnv::mapFileUseCount, CDBEnv::Open(), pdb, strFile, strprintf, and WriteVersion().
~CDB()
CDB::~CDB () inline protected
Definition at line 102 of file db.h.
References Close().
CDB() [2/2]
CDB::CDB (const CDB &) private
Member Function Documentation
Close()
void CDB::Close ()
Definition at line 309 of file db.cpp.
References activeTxn, bitdb, CDBEnv::cs_db, fFlushOnClose, Flush(), LOCK, CDBEnv::mapFileUseCount, pdb, and strFile.
Referenced by ~CDB().
Erase()
template<typename K > bool CDB::Erase (const K & key) inline protected
Definition at line 178 of file db.h.
References activeTxn, CLIENT_VERSION, CDataStream::data(), fReadOnly, memory_cleanse(), pdb, CDataStream::reserve(), SER_DISK, and CDataStream::size().
Referenced by CWalletDB::EraseDestData(), CWalletDB::EraseName(), CWalletDB::ErasePool(), CWalletDB::ErasePurpose(), CWalletDB::EraseTx(), CWalletDB::EraseWatchOnly(), CWalletDB::WriteCryptedHDChain(), and CWalletDB::WriteCryptedKey().
Exists()
template<typename K > bool CDB::Exists (const K & key) inline protected
Definition at line 200 of file db.h.
References activeTxn, CLIENT_VERSION, CDataStream::data(), memory_cleanse(), pdb, CDataStream::reserve(), SER_DISK, and CDataStream::size().
Referenced by CDB().
Flush()
void CDB::Flush ()
Definition at line 296 of file db.cpp.
References activeTxn, bitdb, CDBEnv::dbenv, DEFAULT_WALLET_DBLOGSIZE, fReadOnly, and GetArg().
Referenced by Close().
GetCursor()
Dbc* CDB::GetCursor () inline protected
Definition at line 219 of file db.h.
References pdb.
Referenced by CWalletDB::FindWalletTx(), CWalletDB::ListAccountCreditDebit(), and CWalletDB::LoadWallet().
operator=()
void CDB::operator= (const CDB &) private
Read()
template<typename K , typename T > bool CDB::Read (const K & key, T & value) inline protected
Definition at line 114 of file db.h.
References activeTxn, CLIENT_VERSION, CDataStream::data(), memory_cleanse(), pdb, CDataStream::reserve(), SER_DISK, and CDataStream::size().
Referenced by CWalletDB::FindWalletTx(), CWalletDB::LoadWallet(), CWalletDB::ReadAccount(), CWalletDB::ReadBestBlock(), CWalletDB::ReadPool(), and ReadVersion().
ReadAtCursor()
int CDB::ReadAtCursor (Dbc * pcursor, CDataStream & ssKey, CDataStream & ssValue, bool setRange = false) inline protected
Definition at line 230 of file db.h.
References CDataStream::clear(), CDataStream::data(), memory_cleanse(), SER_DISK, CDataStream::SetType(), CDataStream::size(), and CDataStream::write().
Referenced by CWalletDB::FindWalletTx(), CWalletDB::ListAccountCreditDebit(), and CWalletDB::LoadWallet().
ReadVersion()
bool CDB::ReadVersion (int & nVersion) inline
Definition at line 295 of file db.h.
References Read().
Rewrite()
bool CDB::Rewrite (const std::string & strFile, const char * pszSkip = NULL) static
Definition at line 350 of file db.cpp.
References bitdb, CDBEnv::CheckpointLSN(), CDataStream::clear(), CLIENT_VERSION, CDBEnv::CloseDb(), CDBEnv::cs_db, CDataStream::data(), CDBEnv::dbenv, LOCK, LogPrintf, CDBEnv::mapFileUseCount, MilliSleep(), SER_DISK, CDataStream::size(), and strFile.
Referenced by CWallet::EncryptWallet(), CWallet::LoadWallet(), CWallet::ZapSelectTx(), and CWallet::ZapWalletTx().
TxnAbort()
bool CDB::TxnAbort () inline
Definition at line 286 of file db.h.
References activeTxn, and pdb.
Referenced by CWallet::EncryptWallet().
TxnBegin()
bool CDB::TxnBegin () inline
Definition at line 266 of file db.h.
References activeTxn, bitdb, pdb, and CDBEnv::TxnBegin().
Referenced by CWallet::AccountMove(), and CWallet::EncryptWallet().
TxnCommit()
bool CDB::TxnCommit () inline
Definition at line 277 of file db.h.
References activeTxn, and pdb.
Referenced by CWallet::AccountMove(), and CWallet::EncryptWallet().
Write()
template<typename K , typename T > bool CDB::Write (const K & key, const T & value, bool fOverwrite = true) inline protected
Definition at line 149 of file db.h.
References activeTxn, CLIENT_VERSION, CDataStream::data(), fReadOnly, memory_cleanse(), pdb, CDataStream::reserve(), SER_DISK, and CDataStream::size().
Referenced by CWalletDB::WriteAccount(), CWalletDB::WriteAccountingEntry(), CWalletDB::WriteBestBlock(), CWalletDB::WriteCryptedHDChain(), CWalletDB::WriteCryptedKey(), CWalletDB::WriteCScript(), CWalletDB::WriteDefaultKey(), CWalletDB::WriteDestData(), CWalletDB::WriteHDChain(), CWalletDB::WriteHDPubKey(), CWalletDB::WriteKey(), CWalletDB::WriteMasterKey(), CWalletDB::WriteMinVersion(), CWalletDB::WriteName(), CWalletDB::WriteOrderPosNext(), CWalletDB::WritePool(), CWalletDB::WritePurpose(), CWalletDB::WriteTx(), WriteVersion(), and CWalletDB::WriteWatchOnly().
WriteVersion()
bool CDB::WriteVersion (int nVersion) inline
Definition at line 301 of file db.h.
References Write().
Referenced by CDB(), and CWalletDB::LoadWallet().
Member Data Documentation
activeTxn
DbTxn* CDB::activeTxn protected
Definition at line 97 of file db.h.
Referenced by Close(), Erase(), Exists(), Flush(), Read(), TxnAbort(), TxnBegin(), TxnCommit(), and Write().
fFlushOnClose
bool CDB::fFlushOnClose protected
Definition at line 99 of file db.h.
Referenced by CDB(), and Close().
fReadOnly
bool CDB::fReadOnly protected
Definition at line 98 of file db.h.
Referenced by CDB(), Erase(), Flush(), and Write().
pdb
Db* CDB::pdb protected
Definition at line 95 of file db.h.
Referenced by CDB(), Close(), Erase(), Exists(), GetCursor(), Read(), TxnAbort(), TxnBegin(), TxnCommit(), and Write().
strFile
std::string CDB::strFile protected
Definition at line 96 of file db.h.
Referenced by CDB(), Close(), and Rewrite().
The documentation for this class was generated from the following files:
src/wallet/db.h
src/wallet/db.cpp
Released under the MIT license