Dash Core: CMasternodePayments Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CMasternodePayments Class Reference
#include <masternode-payments.h>
Public Member Functions
CMasternodePayments ()
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
void Clear ()
bool AddOrUpdatePaymentVote (const CMasternodePaymentVote &vote)
bool HasVerifiedPaymentVote (const uint256 &hashIn) const
bool ProcessBlock (int nBlockHeight, CConnman &connman)
void CheckBlockVotes (int nBlockHeight)
void Sync (CNode *node, CConnman &connman) const
void RequestLowDataPaymentBlocks (CNode *pnode, CConnman &connman) const
void CheckAndRemove ()
bool GetBlockTxOuts (int nBlockHeight, CAmount blockReward, std::vector< CTxOut > &voutMasternodePaymentsRet) const
bool IsTransactionValid (const CTransaction &txNew, int nBlockHeight, CAmount blockReward) const
bool IsScheduled (const masternode_info_t &mnInfo, int nNotBlockHeight) const
bool UpdateLastVote (const CMasternodePaymentVote &vote)
int GetMinMasternodePaymentsProto () const
void ProcessMessage (CNode *pfrom, const std::string &strCommand, CDataStream &vRecv, CConnman &connman)
std::string GetRequiredPaymentsString (int nBlockHeight) const
bool GetMasternodeTxOuts (int nBlockHeight, CAmount blockReward, std::vector< CTxOut > &voutMasternodePaymentsRet) const
GetMasternodeTxOuts.
std::string ToString () const
int GetBlockCount () const
int GetVoteCount () const
bool IsEnoughData () const
int GetStorageLimit () const
void UpdatedBlockTip (const CBlockIndex *pindex, CConnman &connman)
void DoMaintenance ()
Public Attributes
std::map< uint256, CMasternodePaymentVote > mapMasternodePaymentVotes
std::map< int, CMasternodeBlockPayees > mapMasternodeBlocks
std::map< COutPoint, int > mapMasternodesLastVote
std::map< COutPoint, int > mapMasternodesDidNotVote
ADD_SERIALIZE_METHODS
Private Attributes
const float nStorageCoeff
const int nMinBlocksToStore
int nCachedBlockHeight
Detailed Description
Definition at line 163 of file masternode-payments.h.
Constructor & Destructor Documentation
CMasternodePayments()
CMasternodePayments::CMasternodePayments () inline
Definition at line 180 of file masternode-payments.h.
Member Function Documentation
AddOrUpdatePaymentVote()
bool CMasternodePayments::AddOrUpdatePaymentVote (const CMasternodePaymentVote & vote)
Definition at line 677 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, cs_mapMasternodePaymentVotes, GetBlockHash(), CMasternodePaymentVote::GetHash(), HasVerifiedPaymentVote(), LOCK2, LogPrint, mapMasternodeBlocks, mapMasternodePaymentVotes, CMasternodePaymentVote::nBlockHeight, and base_blob< BITS >::ToString().
Referenced by ProcessBlock(), and ProcessMessage().
CheckAndRemove()
void CMasternodePayments::CheckAndRemove ()
Definition at line 864 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, cs_mapMasternodePaymentVotes, deterministicMNManager, GetStorageLimit(), CMasternodeSync::IsBlockchainSynced(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LOCK2, LogPrint, LogPrintf, mapMasternodeBlocks, mapMasternodePaymentVotes, masternodeSync, CMasternodePaymentVote::nBlockHeight, nCachedBlockHeight, and ToString().
Referenced by DoMaintenance().
CheckBlockVotes()
void CMasternodePayments::CheckBlockVotes (int nBlockHeight)
Definition at line 1018 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, cs_mapMasternodePaymentVotes, ExtractDestination(), CMasternodeMan::GetMasternodeRanks(), GetMinMasternodePaymentsProto(), CMasternodeSync::IsWinnersListSynced(), LOCK2, LogPrint, LogPrintf, mapMasternodeBlocks, mapMasternodePaymentVotes, mapMasternodesDidNotVote, masternodeSync, mnodeman, MNPAYMENTS_SIGNATURES_TOTAL, strprintf, and CBase58Data::ToString().
Referenced by UpdatedBlockTip().
Clear()
void CMasternodePayments::Clear ()
Definition at line 331 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, cs_mapMasternodePaymentVotes, LOCK2, mapMasternodeBlocks, and mapMasternodePaymentVotes.
DoMaintenance()
void CMasternodePayments::DoMaintenance ()
Definition at line 1308 of file masternode-payments.cpp.
References CheckAndRemove(), and ShutdownRequested().
Referenced by AppInitMain().
GetBlockCount()
int CMasternodePayments::GetBlockCount () const inline
Definition at line 213 of file masternode-payments.h.
References mapMasternodeBlocks.
Referenced by IsEnoughData().
GetBlockTxOuts()
bool CMasternodePayments::GetBlockTxOuts (int nBlockHeight, CAmount blockReward, std::vector< CTxOut > & voutMasternodePaymentsRet) const
Definition at line 589 of file masternode-payments.cpp.
References chainActive, cs_main, cs_mapMasternodeBlocks, deterministicMNManager, CDeterministicMNManager::GetListForBlock(), GetMasternodePayment(), CDeterministicMNList::GetMNPayee(), CChain::Height(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LOCK, and mapMasternodeBlocks.
Referenced by ComputeBlockVersion(), getblocktemplate(), GetMasternodeTxOuts(), IsScheduled(), and IsTransactionValid().
GetMasternodeTxOuts()
bool CMasternodePayments::GetMasternodeTxOuts (int nBlockHeight, CAmount blockReward, std::vector< CTxOut > & voutMasternodePaymentsRet) const
GetMasternodeTxOuts.
Get masternode payment tx outputs
Definition at line 364 of file masternode-payments.cpp.
References deterministicMNManager, ExtractDestination(), GetBlockTxOuts(), GetMasternodePayment(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetScriptForDestination(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), masternode_info_t::keyIDCollateralAddress, LogPrintf, mnodeman, and CBase58Data::ToString().
Referenced by FillBlockPayments().
GetMinMasternodePaymentsProto()
int CMasternodePayments::GetMinMasternodePaymentsProto () const
Definition at line 400 of file masternode-payments.cpp.
References CSporkManager::IsSporkActive(), MIN_MASTERNODE_PAYMENT_PROTO_VERSION_1, MIN_MASTERNODE_PAYMENT_PROTO_VERSION_2, SPORK_10_MASTERNODE_PAY_UPDATED_NODES, and sporkManager.
Referenced by CMasternode::Check(), CheckBlockVotes(), CMasternodeMan::CountEnabled(), CMasternodeMan::CountMasternodes(), CMasternodeMan::FindRandomNotInVec(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), CMasternodePaymentVote::IsValid(), CTxLockVote::IsValid(), ProcessBlock(), ProcessMessage(), CMasternodeSync::ProcessTick(), CMasternodeBroadcast::SimpleCheck(), and CInstantSend::Vote().
GetRequiredPaymentsString()
std::string CMasternodePayments::GetRequiredPaymentsString (int nBlockHeight) const
Definition at line 824 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, LOCK, and mapMasternodeBlocks.
Referenced by GetLegacyRequiredPaymentsString().
GetStorageLimit()
int CMasternodePayments::GetStorageLimit () const
Definition at line 1286 of file masternode-payments.cpp.
References mnodeman, nMinBlocksToStore, nStorageCoeff, and CMasternodeMan::size().
Referenced by CheckAndRemove(), IsEnoughData(), ProcessMessage(), RequestLowDataPaymentBlocks(), and CMasternodeMan::UpdateLastPaid().
GetVoteCount()
int CMasternodePayments::GetVoteCount () const inline
Definition at line 214 of file masternode-payments.h.
References mapMasternodePaymentVotes.
Referenced by IsEnoughData().
HasVerifiedPaymentVote()
bool CMasternodePayments::HasVerifiedPaymentVote (const uint256 & hashIn) const
Definition at line 698 of file masternode-payments.cpp.
References cs_mapMasternodePaymentVotes, LOCK, and mapMasternodePaymentVotes.
Referenced by AddOrUpdatePaymentVote(), ProcessGetData(), and Sync().
IsEnoughData()
bool CMasternodePayments::IsEnoughData () const
Definition at line 1279 of file masternode-payments.cpp.
References GetBlockCount(), GetStorageLimit(), GetVoteCount(), MNPAYMENTS_SIGNATURES_REQUIRED, and MNPAYMENTS_SIGNATURES_TOTAL.
Referenced by CMasternodeSync::ProcessTick().
IsScheduled()
bool CMasternodePayments::IsScheduled (const masternode_info_t & mnInfo, int nNotBlockHeight) const
Definition at line 644 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, deterministicMNManager, GetBlockTxOuts(), CDeterministicMNManager::GetListAtChainTip(), CDeterministicMNList::GetProjectedMNPayees(), GetScriptForDestination(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CMasternodeSync::IsMasternodeListSynced(), masternode_info_t::keyIDCollateralAddress, LOCK, masternodeSync, nCachedBlockHeight, and masternode_info_t::outpoint.
Referenced by CMasternodeMan::GetNextMasternodeInQueueForPayment(), CPrivateSendClientSession::JoinExistingQueue(), and CPrivateSendClientSession::StartNewQueue().
IsTransactionValid()
bool CMasternodePayments::IsTransactionValid (const CTransaction & txNew, int nBlockHeight, CAmount blockReward) const
Definition at line 831 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, deterministicMNManager, ExtractDestination(), GetBlockTxOuts(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LOCK, LogPrintf, mapMasternodeBlocks, ToString(), true, and CTransaction::vout.
Referenced by IsBlockPayeeValid().
ProcessBlock()
bool CMasternodePayments::ProcessBlock (int nBlockHeight, CConnman & connman)
Definition at line 949 of file masternode-payments.cpp.
References activeMasternodeInfo, AddOrUpdatePaymentVote(), deterministicMNManager, ExtractDestination(), fLiteMode, fMasternodeMode, CMasternodeMan::GetMasternodeRank(), GetMinMasternodePaymentsProto(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetScriptForDestination(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CMasternodeSync::IsMasternodeListSynced(), masternode_info_t::keyIDCollateralAddress, LogPrint, LogPrintf, masternodeSync, mnodeman, MNPAYMENTS_SIGNATURES_TOTAL, CActiveMasternodeInfo::outpoint, masternode_info_t::outpoint, CMasternodePaymentVote::Relay(), CMasternodePaymentVote::Sign(), CBase58Data::ToString(), and COutPoint::ToStringShort().
Referenced by UpdatedBlockTip().
ProcessMessage()
void CMasternodePayments::ProcessMessage (CNode * pfrom, const std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 406 of file masternode-payments.cpp.
References CNetFulfilledRequestManager::AddFulfilledRequest(), AddOrUpdatePaymentVote(), CNode::addr, CMasternodeMan::AskForMN(), CMasternodeSync::BumpAssetLastTime(), cs_main, cs_mapMasternodePaymentVotes, deterministicMNManager, ExtractDestination(), fLiteMode, CNode::GetId(), CMasternodeMan::GetMasternodeInfo(), GetMinMasternodePaymentsProto(), CNode::GetSendVersion(), GetStorageLimit(), CNetFulfilledRequestManager::HasFulfilledRequest(), CNode::id, CDeterministicMNManager::IsDeterministicMNsSporkActive(), CMasternodeSync::IsMasternodeListSynced(), CMasternodeSync::IsSynced(), masternode_info_t::legacyKeyIDOperator, LOCK, LogPrint, LogPrintf, mapMasternodePaymentVotes, NetMsgType::MASTERNODEPAYMENTSYNC, NetMsgType::MASTERNODEPAYMENTVOTE, masternodeSync, Misbehaving(), mnodeman, nCachedBlockHeight, netfulfilledman, CNode::nVersion, CConnman::PushMessage(), NetMsgType::REJECT, REJECT_OBSOLETE, CConnman::RemoveAskFor(), strprintf, Sync(), base_blob< BITS >::ToString(), CBase58Data::ToString(), and UpdateLastVote().
Referenced by ProcessMessage().
RequestLowDataPaymentBlocks()
void CMasternodePayments::RequestLowDataPaymentBlocks (CNode * pnode, CConnman & connman) const
Definition at line 1191 of file masternode-payments.cpp.
References chainActive, cs_main, cs_mapMasternodeBlocks, DBG, CBlockIndex::GetBlockHash(), GetBlockHash(), NetMsgType::GETDATA, CNode::GetSendVersion(), GetStorageLimit(), CNode::id, CMasternodeSync::IsMasternodeListSynced(), LOCK2, LogPrintf, mapMasternodeBlocks, masternodeSync, MAX_INV_SZ, MNPAYMENTS_SIGNATURES_REQUIRED, MNPAYMENTS_SIGNATURES_TOTAL, MSG_MASTERNODE_PAYMENT_BLOCK, nCachedBlockHeight, CBlockIndex::nHeight, CBlockIndex::pprev, tinyformat::printf(), CConnman::PushMessage(), and CChain::Tip().
Referenced by CMasternodeSync::ProcessTick().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodePayments::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 185 of file masternode-payments.h.
References mapMasternodeBlocks, mapMasternodePaymentVotes, and READWRITE.
Sync()
void CMasternodePayments::Sync (CNode * node, CConnman & connman) const
Definition at line 1163 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, CNode::GetSendVersion(), HasVerifiedPaymentVote(), CNode::id, CMasternodeSync::IsWinnersListSynced(), LOCK, LogPrintf, mapMasternodeBlocks, MASTERNODE_SYNC_MNW, masternodeSync, MSG_MASTERNODE_PAYMENT_VOTE, nCachedBlockHeight, CNode::PushInventory(), CConnman::PushMessage(), and NetMsgType::SYNCSTATUSCOUNT.
Referenced by ProcessMessage().
ToString()
std::string CMasternodePayments::ToString () const
Definition at line 1269 of file masternode-payments.cpp.
References mapMasternodeBlocks, and mapMasternodePaymentVotes.
Referenced by CheckAndRemove(), and IsTransactionValid().
UpdatedBlockTip()
void CMasternodePayments::UpdatedBlockTip (const CBlockIndex * pindex, CConnman & connman)
Definition at line 1291 of file masternode-payments.cpp.
References CheckBlockVotes(), deterministicMNManager, CDeterministicMNManager::IsDeterministicMNsSporkActive(), LogPrint, nCachedBlockHeight, CBlockIndex::nHeight, and ProcessBlock().
Referenced by CDSNotificationInterface::UpdatedBlockTip().
UpdateLastVote()
bool CMasternodePayments::UpdateLastVote (const CMasternodePaymentVote & vote)
Definition at line 338 of file masternode-payments.cpp.
References cs_mapMasternodePaymentVotes, deterministicMNManager, CDeterministicMNManager::IsDeterministicMNsSporkActive(), LOCK, mapMasternodesLastVote, CMasternodePaymentVote::masternodeOutpoint, and CMasternodePaymentVote::nBlockHeight.
Referenced by ProcessMessage().
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodePayments::ADD_SERIALIZE_METHODS
Definition at line 182 of file masternode-payments.h.
mapMasternodeBlocks
std::map<int, CMasternodeBlockPayees> CMasternodePayments::mapMasternodeBlocks
Definition at line 176 of file masternode-payments.h.
Referenced by AddOrUpdatePaymentVote(), AlreadyHave(), CheckAndRemove(), CheckBlockVotes(), Clear(), GetBlockCount(), GetBlockTxOuts(), GetRequiredPaymentsString(), IsTransactionValid(), ProcessGetData(), RequestLowDataPaymentBlocks(), SerializationOp(), Sync(), ToString(), and CMasternode::UpdateLastPaid().
mapMasternodePaymentVotes
std::map<uint256, CMasternodePaymentVote> CMasternodePayments::mapMasternodePaymentVotes
Definition at line 175 of file masternode-payments.h.
Referenced by AddOrUpdatePaymentVote(), AlreadyHave(), CheckAndRemove(), CheckBlockVotes(), Clear(), GetVoteCount(), HasVerifiedPaymentVote(), ProcessGetData(), ProcessMessage(), SerializationOp(), and ToString().
mapMasternodesDidNotVote
std::map<COutPoint, int> CMasternodePayments::mapMasternodesDidNotVote
Definition at line 178 of file masternode-payments.h.
Referenced by CheckBlockVotes().
mapMasternodesLastVote
std::map<COutPoint, int> CMasternodePayments::mapMasternodesLastVote
Definition at line 177 of file masternode-payments.h.
Referenced by UpdateLastVote().
nCachedBlockHeight
int CMasternodePayments::nCachedBlockHeight private
Definition at line 172 of file masternode-payments.h.
Referenced by CheckAndRemove(), IsScheduled(), ProcessMessage(), RequestLowDataPaymentBlocks(), Sync(), and UpdatedBlockTip().
nMinBlocksToStore
const int CMasternodePayments::nMinBlocksToStore private
Definition at line 169 of file masternode-payments.h.
Referenced by GetStorageLimit().
nStorageCoeff
const float CMasternodePayments::nStorageCoeff private
Definition at line 167 of file masternode-payments.h.
Referenced by GetStorageLimit().
The documentation for this class was generated from the following files:
src/masternode-payments.h
src/masternode-payments.cpp
Released under the MIT license