Dash Core: CMerkleTx Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CMerkleTx Class Reference
A transaction with a merkle branch linking it to the block chain.
#include <wallet.h>
Public Member Functions
CMerkleTx ()
CMerkleTx (CTransactionRef arg)
operator const CTransaction & () const
Helper conversion operator to allow passing CMerkleTx where CTransaction is expected.
void Init ()
void SetTx (CTransactionRef arg)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
void SetMerkleBranch (const CBlockIndex *pIndex, int posInBlock)
int GetDepthInMainChain (const CBlockIndex *&pindexRet) const
Return depth of transaction in blockchain: <0 : conflicts with a transaction this deep in the blockchain 0 : in memory pool, waiting to be included in a block >=1 : this many blocks deep in the main chain.
int GetDepthInMainChain () const
bool IsInMainChain () const
bool IsLockedByInstantSend () const
int GetBlocksToMaturity () const
bool AcceptToMemoryPool (const CAmount &nAbsurdFee, CValidationState &state)
Pass this transaction to the mempool.
bool hashUnset () const
bool isAbandoned () const
void setAbandoned ()
const uint256 & GetHash () const
bool IsCoinBase () const
Public Attributes
CTransactionRef tx
uint256 hashBlock
int nIndex
ADD_SERIALIZE_METHODS
Static Private Attributes
static const uint256 ABANDON_HASH
Constant used in hashBlock to indicate tx has been abandoned.
Detailed Description
A transaction with a merkle branch linking it to the block chain.
Definition at line 211 of file wallet.h.
Constructor & Destructor Documentation
CMerkleTx() [1/2]
CMerkleTx::CMerkleTx () inline
Definition at line 228 of file wallet.h.
References Init(), MakeTransactionRef(), and SetTx().
CMerkleTx() [2/2]
CMerkleTx::CMerkleTx (CTransactionRef arg) inline
Definition at line 234 of file wallet.h.
References Init(), and SetTx().
Member Function Documentation
AcceptToMemoryPool()
bool CMerkleTx::AcceptToMemoryPool (const CAmount & nAbsurdFee, CValidationState & state)
Pass this transaction to the mempool.
Fails if absolute fee exceeds absurd fee.
Definition at line 5435 of file wallet.cpp.
References AcceptToMemoryPool(), mempool, and tx.
Referenced by CWallet::CommitTransaction(), CWallet::ReacceptWalletTransactions(), and CWalletTx::RelayWalletTransaction().
GetBlocksToMaturity()
int CMerkleTx::GetBlocksToMaturity () const
Definition at line 5427 of file wallet.cpp.
References COINBASE_MATURITY, GetDepthInMainChain(), and IsCoinBase().
Referenced by CWallet::AvailableCoins(), CWallet::GetAccountBalance(), CWallet::GetAddressBalances(), CWalletTx::GetAnonymizedCredit(), CWalletTx::GetAvailableCredit(), CWalletTx::GetAvailableWatchOnlyCredit(), getbalance(), CWalletTx::GetCredit(), CWalletTx::GetDenominatedCredit(), CWalletTx::GetImmatureCredit(), CWalletTx::GetImmatureWatchOnlyCredit(), listaccounts(), ListTransactions(), CWallet::SelectCoinsGroupedByAddresses(), TransactionDesc::toHTML(), and TransactionRecord::updateStatus().
GetDepthInMainChain() [1/2]
int CMerkleTx::GetDepthInMainChain (const CBlockIndex *& pindexRet) const
Return depth of transaction in blockchain: <0 : conflicts with a transaction this deep in the blockchain 0 : in memory pool, waiting to be included in a block >=1 : this many blocks deep in the main chain.
Definition at line 5392 of file wallet.cpp.
References AssertLockHeld, chainActive, CChain::Contains(), cs_main, CTxMemPool::exists(), GetHash(), hashBlock, hashUnset(), CChain::Height(), mapBlockIndex, mempool, CBlockIndex::nHeight, and nIndex.
Referenced by CWallet::AvailableCoins(), CWallet::CountInputsWithAmount(), TransactionDesc::FormatTxStatus(), CWallet::GetAccountBalance(), CWallet::GetAddressBalances(), getbalance(), getreceivedbyaccount(), getreceivedbyaddress(), CWallet::GetUnconfirmedBalance(), CWallet::GetUnconfirmedWatchOnlyBalance(), listaccounts(), ListReceived(), listsinceblock(), ListTransactions(), CWallet::ReacceptWalletTransactions(), WalletModel::transactionCanBeAbandoned(), TransactionRecord::updateStatus(), and WalletTxToJSON().
GetDepthInMainChain() [2/2]
int CMerkleTx::GetDepthInMainChain () const inline
Definition at line 275 of file wallet.h.
References GetDepthInMainChain().
Referenced by GetBlocksToMaturity(), CWalletTx::GetDenominatedCredit(), GetDepthInMainChain(), IsInMainChain(), CWalletTx::IsTrusted(), and CWalletTx::RelayWalletTransaction().
GetHash()
const uint256& CMerkleTx::GetHash () const inline
Definition at line 285 of file wallet.h.
References tx.
Referenced by CWallet::AddToWallet(), BOOST_AUTO_TEST_CASE(), CWallet::CommitTransaction(), CWallet::CountInputsWithAmount(), CPrivateSendClientSession::CreateDenominated(), CWallet::CreateWalletFromFile(), TransactionRecord::decomposeTransaction(), TransactionDesc::FormatTxStatus(), CWalletTx::GetAmounts(), CWalletTx::GetAnonymizedCredit(), CWalletTx::GetAvailableCredit(), CWalletTx::GetAvailableWatchOnlyCredit(), CWalletTx::GetConflicts(), CWalletTx::GetDenominatedCredit(), GetDepthInMainChain(), CWallet::GetOutpointAndKeysFromOutput(), CWalletTx::GetRequestCount(), CWalletTx::InMempool(), IsLockedByInstantSend(), ListReceived(), listunspent(), CWallet::LoadToWallet(), CPrivateSendClientSession::MakeCollateralAmounts(), CWallet::ReacceptWalletTransactions(), CWalletTx::RelayWalletTransaction(), CWallet::ResendWalletTransactionsBefore(), CWallet::SelectCoins(), CWallet::SelectCoinsMinConf(), sendfrom(), sendmany(), COutput::ToString(), CoinControlDialog::updateLabels(), CoinControlDialog::updateView(), WalletTxToJSON(), and CWalletDB::WriteTx().
hashUnset()
bool CMerkleTx::hashUnset () const inline
Definition at line 281 of file wallet.h.
References ABANDON_HASH, hashBlock, and base_blob< BITS >::IsNull().
Referenced by CWallet::AddToWallet(), GetDepthInMainChain(), CWalletTx::GetRequestCount(), and CWallet::LoadToWallet().
Init()
void CMerkleTx::Init () inline
Definition at line 244 of file wallet.h.
References hashBlock, and nIndex.
Referenced by CMerkleTx(), CWalletTx::CWalletTx(), and CWalletTx::SerializationOp().
isAbandoned()
bool CMerkleTx::isAbandoned () const inline
Definition at line 282 of file wallet.h.
References ABANDON_HASH, and hashBlock.
Referenced by CWallet::AddToWallet(), TransactionDesc::FormatTxStatus(), ListTransactions(), CWallet::ReacceptWalletTransactions(), CWalletTx::RelayWalletTransaction(), WalletModel::transactionCanBeAbandoned(), and TransactionRecord::updateStatus().
IsCoinBase()
bool CMerkleTx::IsCoinBase () const inline
Definition at line 286 of file wallet.h.
References tx.
Referenced by CWallet::AvailableCoins(), TransactionRecord::decomposeTransaction(), CWallet::GetAddressBalances(), CWalletTx::GetAnonymizedCredit(), CWalletTx::GetAvailableCredit(), CWalletTx::GetAvailableWatchOnlyCredit(), GetBlocksToMaturity(), CWalletTx::GetCredit(), CWalletTx::GetDenominatedCredit(), CWalletTx::GetImmatureCredit(), CWalletTx::GetImmatureWatchOnlyCredit(), getreceivedbyaccount(), getreceivedbyaddress(), CWalletTx::GetRequestCount(), ListReceived(), ListTransactions(), CWallet::ReacceptWalletTransactions(), CWalletTx::RelayWalletTransaction(), CWallet::SelectCoinsGroupedByAddresses(), TransactionRecord::showTransaction(), TransactionDesc::toHTML(), TransactionRecord::updateStatus(), and WalletTxToJSON().
IsInMainChain()
bool CMerkleTx::IsInMainChain () const inline
Definition at line 276 of file wallet.h.
References GetDepthInMainChain().
Referenced by CWalletTx::GetImmatureCredit(), CWalletTx::GetImmatureWatchOnlyCredit(), TransactionRecord::showTransaction(), TransactionDesc::toHTML(), and TransactionRecord::updateStatus().
IsLockedByInstantSend()
bool CMerkleTx::IsLockedByInstantSend () const
Definition at line 5422 of file wallet.cpp.
References GetHash(), instantsend, and CInstantSend::IsLockedInstantSendTransaction().
Referenced by CWallet::GetAccountBalance(), CWallet::GetAddressBalances(), getbalance(), getreceivedbyaccount(), getreceivedbyaddress(), CWallet::GetUnconfirmedBalance(), CWallet::GetUnconfirmedWatchOnlyBalance(), CWalletTx::IsTrusted(), listaccounts(), ListReceived(), ListTransactions(), CWallet::ReacceptWalletTransactions(), WalletModel::transactionCanBeAbandoned(), and TransactionRecord::updateStatus().
operator const CTransaction &()
CMerkleTx::operator const CTransaction & () const inline
Helper conversion operator to allow passing CMerkleTx where CTransaction is expected.
TODO: adapt callers and remove this operator.
Definition at line 242 of file wallet.h.
References tx.
SerializationOp()
template<typename Stream , typename Operation > void CMerkleTx::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 258 of file wallet.h.
References hashBlock, nIndex, READWRITE, and tx.
setAbandoned()
void CMerkleTx::setAbandoned () inline
Definition at line 283 of file wallet.h.
References ABANDON_HASH, and hashBlock.
SetMerkleBranch()
void CMerkleTx::SetMerkleBranch (const CBlockIndex * pIndex, int posInBlock)
Definition at line 5383 of file wallet.cpp.
References CBlockIndex::GetBlockHash(), hashBlock, and nIndex.
Referenced by CWallet::AddToWalletIfInvolvingMe().
SetTx()
void CMerkleTx::SetTx (CTransactionRef arg) inline
Definition at line 250 of file wallet.h.
References tx.
Referenced by BOOST_AUTO_TEST_CASE(), CMerkleTx(), and CWallet::CreateTransaction().
Member Data Documentation
ABANDON_HASH
const uint256 CMerkleTx::ABANDON_HASH static private
Constant used in hashBlock to indicate tx has been abandoned.
Definition at line 215 of file wallet.h.
Referenced by hashUnset(), isAbandoned(), and setAbandoned().
ADD_SERIALIZE_METHODS
CMerkleTx::ADD_SERIALIZE_METHODS
Definition at line 255 of file wallet.h.
hashBlock
uint256 CMerkleTx::hashBlock
Definition at line 219 of file wallet.h.
Referenced by CWallet::AddToWallet(), GetDepthInMainChain(), CWallet::GetKeyBirthTimes(), CWalletTx::GetRequestCount(), hashUnset(), importprunedfunds(), Init(), isAbandoned(), CWallet::LoadToWallet(), SerializationOp(), setAbandoned(), SetMerkleBranch(), TransactionRecord::updateStatus(), and WalletTxToJSON().
nIndex
int CMerkleTx::nIndex
Definition at line 226 of file wallet.h.
Referenced by CWallet::AddToWallet(), GetDepthInMainChain(), importprunedfunds(), Init(), CWallet::LoadToWallet(), SerializationOp(), SetMerkleBranch(), and WalletTxToJSON().
tx
CTransactionRef CMerkleTx::tx
Definition at line 218 of file wallet.h.
Referenced by AcceptToMemoryPool(), CWallet::AddToWallet(), CWallet::AvailableCoins(), CWallet::CommitTransaction(), CWallet::ConvertList(), CWallet::CountInputsWithAmount(), CWallet::CreateTransaction(), TransactionRecord::decomposeTransaction(), TransactionDesc::FormatTxStatus(), CWallet::FundTransaction(), CWallet::GetAddressBalances(), CWallet::GetAddressGroupings(), CWalletTx::GetAmounts(), CWalletTx::GetAnonymizedCredit(), CWalletTx::GetAvailableCredit(), CWalletTx::GetAvailableWatchOnlyCredit(), WalletModel::getBalance(), CWallet::GetConflicts(), CWalletTx::GetDebit(), CWallet::GetDebit(), CWalletTx::GetDenominatedCredit(), GetHash(), CWallet::GetKeyBirthTimes(), CWallet::GetOutpointAndKeysFromOutput(), CWallet::GetRealOutpointPrivateSendRounds(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), WalletModelTransaction::getTransactionSize(), CWallet::IsAllFromMe(), IsCoinBase(), CWallet::IsDenominated(), CWalletTx::IsEquivalentTo(), CWallet::IsMine(), CWalletTx::IsTrusted(), less_then_denom(), WalletModel::listCoins(), ListReceived(), listunspent(), CWallet::LoadToWallet(), operator const CTransaction &(), WalletModel::prepareTransaction(), COutput::Priority(), WalletModelTransaction::reassignAmounts(), CWallet::SelectCoins(), CWallet::SelectCoinsGroupedByAddresses(), CWallet::SelectCoinsMinConf(), WalletModel::sendCoins(), SerializationOp(), SetTx(), TransactionDesc::toHTML(), COutput::ToString(), CoinControlDialog::updateLabels(), TransactionRecord::updateStatus(), and CoinControlDialog::updateView().
The documentation for this class was generated from the following files:
src/wallet/wallet.h
src/wallet/wallet.cpp
Released under the MIT license