Dash Core: CGovernanceObject Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CGovernanceObject Class Reference
Governance Object.
#include <governance-object.h>
Public Types
typedef std::map< COutPoint, vote_rec_t > vote_m_t
typedef vote_m_t::iterator vote_m_it
typedef vote_m_t::const_iterator vote_m_cit
typedef CacheMultiMap< COutPoint, vote_time_pair_t > vote_cmm_t
Public Member Functions
CGovernanceObject ()
CGovernanceObject (const uint256 &nHashParentIn, int nRevisionIn, int64_t nTime, const uint256 &nCollateralHashIn, const std::string &strDataHexIn)
CGovernanceObject (const CGovernanceObject &other)
int64_t GetCreationTime () const
int64_t GetDeletionTime () const
int GetObjectType () const
const uint256 & GetCollateralHash () const
const COutPoint & GetMasternodeOutpoint () const
bool IsSetCachedFunding () const
bool IsSetCachedValid () const
bool IsSetCachedDelete () const
bool IsSetCachedEndorsed () const
bool IsSetDirtyCache () const
bool IsSetExpired () const
const CGovernanceObjectVoteFile & GetVoteFile () const
void SetMasternodeOutpoint (const COutPoint &outpoint)
bool Sign (const CKey &key, const CKeyID &keyID)
bool CheckSignature (const CKeyID &keyID) const
bool Sign (const CBLSSecretKey &key)
bool CheckSignature (const CBLSPublicKey &pubKey) const
std::string GetSignatureMessage () const
uint256 GetSignatureHash () const
bool IsValidLocally (std::string &strError, bool fCheckCollateral) const
bool IsValidLocally (std::string &strError, bool &fMissingMasternode, bool &fMissingConfirmations, bool fCheckCollateral) const
bool IsCollateralValid (std::string &strError, bool &fMissingConfirmations) const
Check the collateral transaction for the budget proposal/finalized budget.
void UpdateLocalValidity ()
void UpdateSentinelVariables ()
CAmount GetMinCollateralFee () const
UniValue GetJSONObject ()
Return the actual object from the vchData JSON structure.
void Relay (CConnman &connman)
uint256 GetHash () const
int CountMatchingVotes (vote_signal_enum_t eVoteSignalIn, vote_outcome_enum_t eVoteOutcomeIn) const
int GetAbsoluteYesCount (vote_signal_enum_t eVoteSignalIn) const
Get specific vote counts for each outcome (funding, validity, etc)
int GetAbsoluteNoCount (vote_signal_enum_t eVoteSignalIn) const
int GetYesCount (vote_signal_enum_t eVoteSignalIn) const
int GetNoCount (vote_signal_enum_t eVoteSignalIn) const
int GetAbstainCount (vote_signal_enum_t eVoteSignalIn) const
bool GetCurrentMNVotes (const COutPoint &mnCollateralOutpoint, vote_rec_t &voteRecord) const
std::string GetDataAsHexString () const
GetData - As
std::string GetDataAsPlainString () const
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
Public Attributes
ADD_SERIALIZE_METHODS
Private Member Functions
void LoadData ()
LoadData
void GetData (UniValue &objResult)
GetData - Example usage:
bool ProcessVote (CNode *pfrom, const CGovernanceVote &vote, CGovernanceException &exception, CConnman &connman)
void ClearMasternodeVotes ()
Called when MN's which have voted on this object have been removed.
std::set< uint256 > RemoveInvalidProposalVotes (const COutPoint &mnOutpoint)
void CheckOrphanVotes (CConnman &connman)
std::vector< uint256 > RemoveOldVotes (unsigned int nMinTime)
Private Attributes
CCriticalSection cs
critical section to protect the inner data structures
int nObjectType
Object typecode.
uint256 nHashParent
parent object, 0 is root
int nRevision
object revision in the system
int64_t nTime
time this object was created
int64_t nDeletionTime
time this object was marked for deletion
uint256 nCollateralHash
fee-tx
std::vector< unsigned char > vchData
Data field - can be used for anything.
COutPoint masternodeOutpoint
Masternode info for signed objects.
std::vector< unsigned char > vchSig
bool fCachedLocalValidity
is valid by blockchain
std::string strLocalValidityError
bool fCachedFunding
true == minimum network support has been reached for this object to be funded (doesn't mean it will for sure though)
bool fCachedValid
true == minimum network has been reached flagging this object as a valid and understood governance object (e.g, the serialized data is correct format, etc)
bool fCachedDelete
true == minimum network support has been reached saying this object should be deleted from the system entirely
bool fCachedEndorsed
true == minimum network support has been reached flagging this object as endorsed by an elected representative body (e.g.
bool fDirtyCache
object was updated and cached values should be updated soon
bool fExpired
Object is no longer of interest.
bool fUnparsable
Failed to parse object data.
vote_m_t mapCurrentMNVotes
vote_cmm_t cmmapOrphanVotes
Limited map of votes orphaned by MN.
CGovernanceObjectVoteFile fileVotes
Friends
class CGovernanceManager
class CGovernanceTriggerManager
class CSuperblock
Detailed Description
Governance Object.
Definition at line 110 of file governance-object.h.
Member Typedef Documentation
vote_cmm_t
typedef CacheMultiMap<COutPoint, vote_time_pair_t> CGovernanceObject::vote_cmm_t
Definition at line 123 of file governance-object.h.
vote_m_cit
typedef vote_m_t::const_iterator CGovernanceObject::vote_m_cit
Definition at line 121 of file governance-object.h.
vote_m_it
typedef vote_m_t::iterator CGovernanceObject::vote_m_it
Definition at line 119 of file governance-object.h.
vote_m_t
typedef std::map<COutPoint, vote_rec_t> CGovernanceObject::vote_m_t
Definition at line 117 of file governance-object.h.
Constructor & Destructor Documentation
CGovernanceObject() [1/3]
CGovernanceObject::CGovernanceObject ()
Definition at line 20 of file governance-object.cpp.
References LoadData().
CGovernanceObject() [2/3]
CGovernanceObject::CGovernanceObject (const uint256 & nHashParentIn, int nRevisionIn, int64_t nTime, const uint256 & nCollateralHashIn, const std::string & strDataHexIn)
Definition at line 48 of file governance-object.cpp.
References LoadData().
CGovernanceObject() [3/3]
CGovernanceObject::CGovernanceObject (const CGovernanceObject & other)
Definition at line 76 of file governance-object.cpp.
Member Function Documentation
CheckOrphanVotes()
void CGovernanceObject::CheckOrphanVotes (CConnman & connman) private
Definition at line 812 of file governance-object.cpp.
References cmmapOrphanVotes, CacheMultiMap< K, V, Size >::Erase(), GetAdjustedTime(), CacheMultiMap< K, V, Size >::GetItemList(), CGovernanceVote::GetMasternodeOutpoint(), CMasternodeMan::Has(), LogPrintf, mnodeman, ProcessVote(), CGovernanceVote::Relay(), and CGovernanceException::what().
CheckSignature() [1/2]
bool CGovernanceObject::CheckSignature (const CKeyID & keyID) const
Definition at line 349 of file governance-object.cpp.
References GetSignatureHash(), GetSignatureMessage(), CSporkManager::IsSporkActive(), LogPrintf, SPORK_6_NEW_SIGS, sporkManager, vchSig, CHashSigner::VerifyHash(), and CMessageSigner::VerifyMessage().
Referenced by IsValidLocally().
CheckSignature() [2/2]
bool CGovernanceObject::CheckSignature (const CBLSPublicKey & pubKey) const
Definition at line 388 of file governance-object.cpp.
References GetSignatureHash(), LogPrintf, CBLSWrapper< ImplType, _SerSize, C >::SetBuf(), vchSig, and CBLSSignature::VerifyInsecure().
ClearMasternodeVotes()
void CGovernanceObject::ClearMasternodeVotes () private
Called when MN's which have voted on this object have been removed.
Definition at line 211 of file governance-object.cpp.
References cs, fileVotes, CMasternodeMan::Has(), LOCK, mapCurrentMNVotes, mnodeman, and CGovernanceObjectVoteFile::RemoveVotesFromMasternode().
CountMatchingVotes()
int CGovernanceObject::CountMatchingVotes (vote_signal_enum_t eVoteSignalIn, vote_outcome_enum_t eVoteOutcomeIn) const
Definition at line 710 of file governance-object.cpp.
References cs, LOCK, mapCurrentMNVotes, and vote_rec_t::mapInstances.
Referenced by GetAbstainCount(), GetNoCount(), and GetYesCount().
GetAbsoluteNoCount()
int CGovernanceObject::GetAbsoluteNoCount (vote_signal_enum_t eVoteSignalIn) const
Definition at line 734 of file governance-object.cpp.
References GetNoCount(), and GetYesCount().
Referenced by UpdateSentinelVariables().
GetAbsoluteYesCount()
int CGovernanceObject::GetAbsoluteYesCount (vote_signal_enum_t eVoteSignalIn) const
Get specific vote counts for each outcome (funding, validity, etc)
Definition at line 729 of file governance-object.cpp.
References GetNoCount(), and GetYesCount().
Referenced by CSuperblockManager::GetBestSuperblock(), gobject_get(), and UpdateSentinelVariables().
GetAbstainCount()
int CGovernanceObject::GetAbstainCount (vote_signal_enum_t eVoteSignalIn) const
Definition at line 749 of file governance-object.cpp.
References CountMatchingVotes(), and VOTE_OUTCOME_ABSTAIN.
Referenced by gobject_get().
GetCollateralHash()
const uint256& CGovernanceObject::GetCollateralHash () const inline
Definition at line 214 of file governance-object.h.
References nCollateralHash.
Referenced by gobject_get().
GetCreationTime()
int64_t CGovernanceObject::GetCreationTime () const inline
Definition at line 199 of file governance-object.h.
References nTime.
Referenced by CGovernanceManager::CheckPostponedObjects(), gobject_get(), CGovernanceManager::MasternodeRateCheck(), CGovernanceManager::MasternodeRateUpdate(), and CGovernanceManager::UpdateCachesAndClean().
GetCurrentMNVotes()
bool CGovernanceObject::GetCurrentMNVotes (const COutPoint & mnCollateralOutpoint, vote_rec_t & voteRecord) const
Definition at line 754 of file governance-object.cpp.
References cs, LOCK, and mapCurrentMNVotes.
Referenced by CGovernanceManager::GetCurrentVotes().
GetData()
void CGovernanceObject::GetData (UniValue & objResult) private
GetData - Example usage:
Decode governance object data into UniValue(VOBJ)
Definition at line 479 of file governance-object.cpp.
References GetDataAsPlainString(), UniValue::read(), and UniValue::VOBJ.
Referenced by GetJSONObject(), and LoadData().
GetDataAsHexString()
std::string CGovernanceObject::GetDataAsHexString () const
GetData - As
Definition at line 493 of file governance-object.cpp.
References HexStr(), and vchData.
Referenced by GetHash(), GetSignatureMessage(), gobject_get(), CSuperblock::IsValid(), IsValidLocally(), and CGovernanceManager::UpdateCachesAndClean().
GetDataAsPlainString()
std::string CGovernanceObject::GetDataAsPlainString () const
Definition at line 498 of file governance-object.cpp.
References vchData.
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceTriggerManager::CleanAndRemove(), CGovernanceTriggerManager::GetActiveTriggers(), GetData(), gobject_get(), gobject_submit(), CSuperblockManager::IsSuperblockTriggered(), and LoadData().
GetDeletionTime()
int64_t CGovernanceObject::GetDeletionTime () const inline
Definition at line 204 of file governance-object.h.
References nDeletionTime.
Referenced by CGovernanceManager::UpdateCachesAndClean().
GetHash()
uint256 CGovernanceObject::GetHash () const
Definition at line 284 of file governance-object.cpp.
References DBG, GetDataAsHexString(), CHashWriter::GetHash(), masternodeOutpoint, nHashParent, nRevision, nTime, tinyformat::printf(), PROTOCOL_VERSION, SER_GETHASH, and vchSig.
Referenced by CGovernanceManager::AddCachedTriggers(), CGovernanceManager::AddGovernanceObject(), CGovernanceManager::AddPostponedObject(), CGovernanceManager::CheckOrphanVotes(), CGovernanceManager::CheckPostponedObjects(), gobject_get(), gobject_submit(), IsCollateralValid(), CSuperblock::IsExpired(), CGovernanceManager::MasternodeRateCheck(), CGovernanceManager::MasternodeRateUpdate(), CZMQPublishRawGovernanceObjectNotifier::NotifyGovernanceObject(), ProcessVote(), Relay(), RemoveInvalidProposalVotes(), RemoveOldVotes(), SerializationOp(), and CGovernanceManager::UpdateCachesAndClean().
GetJSONObject()
UniValue CGovernanceObject::GetJSONObject ()
Return the actual object from the vchData JSON structure.
Returns an empty object on error.
Definition at line 404 of file governance-object.cpp.
References GetData(), UniValue::getValues(), UniValue::isObject(), vchData, and UniValue::VOBJ.
Referenced by LoadData().
GetMasternodeOutpoint()
const COutPoint& CGovernanceObject::GetMasternodeOutpoint () const inline
Definition at line 219 of file governance-object.h.
References masternodeOutpoint.
Referenced by CGovernanceManager::CheckMasternodeOrphanObjects(), gobject_get(), CGovernanceManager::MasternodeRateCheck(), and CGovernanceManager::MasternodeRateUpdate().
GetMinCollateralFee()
CAmount CGovernanceObject::GetMinCollateralFee () const
Definition at line 596 of file governance-object.cpp.
References GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, GOVERNANCE_OBJECT_WATCHDOG, GOVERNANCE_PROPOSAL_FEE_TX, MAX_MONEY, and nObjectType.
Referenced by IsCollateralValid().
GetNoCount()
int CGovernanceObject::GetNoCount (vote_signal_enum_t eVoteSignalIn) const
Definition at line 744 of file governance-object.cpp.
References CountMatchingVotes(), and VOTE_OUTCOME_NO.
Referenced by GetAbsoluteNoCount(), GetAbsoluteYesCount(), and gobject_get().
GetObjectType()
int CGovernanceObject::GetObjectType () const inline
Definition at line 209 of file governance-object.h.
References nObjectType.
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceManager::CheckPostponedObjects(), CGovernanceTriggerManager::CleanAndRemove(), gobject_check(), gobject_get(), gobject_submit(), gobject_vote_conf(), CGovernanceManager::MasternodeRateCheck(), CGovernanceManager::MasternodeRateUpdate(), CZMQPublishRawGovernanceObjectNotifier::NotifyGovernanceObject(), CGovernanceManager::SyncSingleObjAndItsVotes(), CGovernanceManager::UpdateCachesAndClean(), voteraw(), and VoteWithMasternodeList().
GetSignatureHash()
uint256 CGovernanceObject::GetSignatureHash () const
Definition at line 304 of file governance-object.cpp.
References SerializeHash().
Referenced by CheckSignature(), and Sign().
GetSignatureMessage()
std::string CGovernanceObject::GetSignatureMessage () const
Definition at line 271 of file governance-object.cpp.
References cs, GetDataAsHexString(), LOCK, masternodeOutpoint, nCollateralHash, nHashParent, nRevision, nTime, base_blob< BITS >::ToString(), and COutPoint::ToStringShort().
Referenced by CheckSignature(), and Sign().
GetVoteFile()
const CGovernanceObjectVoteFile& CGovernanceObject::GetVoteFile () const inline
Definition at line 254 of file governance-object.h.
References fileVotes.
Referenced by CGovernanceManager::HaveVoteForHash(), CGovernanceManager::RebuildIndexes(), CGovernanceManager::RequestGovernanceObject(), CGovernanceManager::SerializeVoteForHash(), and CGovernanceManager::SyncSingleObjAndItsVotes().
GetYesCount()
int CGovernanceObject::GetYesCount (vote_signal_enum_t eVoteSignalIn) const
Definition at line 739 of file governance-object.cpp.
References CountMatchingVotes(), and VOTE_OUTCOME_YES.
Referenced by GetAbsoluteNoCount(), GetAbsoluteYesCount(), and gobject_get().
IsCollateralValid()
bool CGovernanceObject::IsCollateralValid (std::string & strError, bool & fMissingConfirmations) const
Check the collateral transaction for the budget proposal/finalized budget.
Definition at line 611 of file governance-object.cpp.
References AssertLockHeld, chainActive, CChain::Contains(), cs_main, DBG, GetHash(), GetMinCollateralFee(), GetTransaction(), GOVERNANCE_FEE_CONFIRMATIONS, GOVERNANCE_MIN_RELAY_FEE_CONFIRMATIONS, CChain::Height(), instantsend, CInstantSend::IsLockedInstantSendTransaction(), LogPrintf, mapBlockIndex, nCollateralHash, CBlockIndex::nHeight, OP_RETURN, Params(), ScriptToAsmStr(), strprintf, ToByteVector(), and base_blob< BITS >::ToString().
Referenced by CGovernanceManager::CheckPostponedObjects(), and IsValidLocally().
IsSetCachedDelete()
bool CGovernanceObject::IsSetCachedDelete () const inline
Definition at line 234 of file governance-object.h.
References fCachedDelete.
Referenced by gobject_get(), CGovernanceManager::ProcessVote(), CGovernanceManager::SyncAll(), CGovernanceManager::SyncSingleObjAndItsVotes(), and CGovernanceManager::UpdateCachesAndClean().
IsSetCachedEndorsed()
bool CGovernanceObject::IsSetCachedEndorsed () const inline
Definition at line 239 of file governance-object.h.
References fCachedEndorsed.
Referenced by gobject_get().
IsSetCachedFunding()
bool CGovernanceObject::IsSetCachedFunding () const inline
Definition at line 224 of file governance-object.h.
References fCachedFunding.
Referenced by gobject_get(), and CSuperblockManager::IsSuperblockTriggered().
IsSetCachedValid()
bool CGovernanceObject::IsSetCachedValid () const inline
Definition at line 229 of file governance-object.h.
References fCachedValid.
Referenced by gobject_get().
IsSetDirtyCache()
bool CGovernanceObject::IsSetDirtyCache () const inline
Definition at line 244 of file governance-object.h.
References fDirtyCache.
Referenced by CGovernanceManager::UpdateCachesAndClean().
IsSetExpired()
bool CGovernanceObject::IsSetExpired () const inline
Definition at line 249 of file governance-object.h.
References fExpired.
Referenced by CGovernanceManager::ProcessVote(), CGovernanceManager::SyncAll(), CGovernanceManager::SyncSingleObjAndItsVotes(), and CGovernanceManager::UpdateCachesAndClean().
IsValidLocally() [1/2]
bool CGovernanceObject::IsValidLocally (std::string & strError, bool fCheckCollateral) const
Definition at line 511 of file governance-object.cpp.
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceManager::CheckMasternodeOrphanObjects(), CGovernanceManager::CheckPostponedObjects(), gobject_get(), gobject_submit(), and UpdateLocalValidity().
IsValidLocally() [2/2]
bool CGovernanceObject::IsValidLocally (std::string & strError, bool & fMissingMasternode, bool & fMissingConfirmations, bool fCheckCollateral) const
Definition at line 519 of file governance-object.cpp.
References masternode_info_t::blsPubKeyOperator, CMasternode::CheckCollateral(), CheckSignature(), CMasternode::COLLATERAL_INVALID_AMOUNT, CMasternode::COLLATERAL_INVALID_PUBKEY, CMasternode::COLLATERAL_OK, CMasternode::COLLATERAL_UTXO_NOT_FOUND, deterministicMNManager, fUnparsable, GetDataAsHexString(), CProposalValidator::GetErrorMessages(), CMasternodeMan::GetMasternodeInfo(), GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, GOVERNANCE_OBJECT_WATCHDOG, IsCollateralValid(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), masternode_info_t::legacyKeyIDOperator, masternodeOutpoint, mnodeman, nObjectType, strprintf, base_blob< BITS >::ToString(), CBLSWrapper< ImplType, _SerSize, C >::ToString(), COutPoint::ToStringShort(), and CProposalValidator::Validate().
LoadData()
void CGovernanceObject::LoadData () private
LoadData
Attempt to load data from vchData
Definition at line 433 of file governance-object.cpp.
References DBG, fUnparsable, GetData(), GetDataAsPlainString(), GetJSONObject(), LogPrintf, nObjectType, vchData, and UniValue::VOBJ.
Referenced by CGovernanceObject().
ProcessVote()
bool CGovernanceObject::ProcessVote (CNode * pfrom, const CGovernanceVote & vote, CGovernanceException & exception, CConnman & connman) private
Definition at line 102 of file governance-object.cpp.
References CMasternodeMan::AddGovernanceVote(), CGovernanceManager::AddInvalidVote(), CGovernanceObjectVoteFile::AddVote(), CGovernanceManager::AreRateChecksEnabled(), CMasternodeMan::AskForMN(), cmmapOrphanVotes, CGovernanceVoting::ConvertSignalToString(), cs, fDirtyCache, fileVotes, GetAdjustedTime(), CGovernanceVote::GetHash(), GetHash(), CGovernanceVote::GetMasternodeOutpoint(), CGovernanceVote::GetOutcome(), CGovernanceVote::GetParentHash(), CGovernanceVote::GetSignal(), CGovernanceVote::GetTimestamp(), governance, GOVERNANCE_EXCEPTION_NONE, GOVERNANCE_EXCEPTION_PERMANENT_ERROR, GOVERNANCE_EXCEPTION_TEMPORARY_ERROR, GOVERNANCE_EXCEPTION_WARNING, GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_ORPHAN_EXPIRATION_TIME, GOVERNANCE_UPDATE_MIN, CMasternodeMan::Has(), CGovernanceObjectVoteFile::HasVote(), CacheMultiMap< K, V, Size >::Insert(), CGovernanceVote::IsValid(), LOCK, LogPrint, LogPrintf, mapCurrentMNVotes, vote_rec_t::mapInstances, MAX_SUPPORTED_VOTE_SIGNAL, mnodeman, vote_instance_t::nCreationTime, nObjectType, vote_instance_t::nTime, base_blob< BITS >::ToString(), COutPoint::ToStringShort(), VOTE_SIGNAL_FUNDING, and VOTE_SIGNAL_NONE.
Referenced by CheckOrphanVotes(), CGovernanceManager::CheckOrphanVotes(), and CGovernanceManager::ProcessVote().
Relay()
void CGovernanceObject::Relay (CConnman & connman)
Definition at line 766 of file governance-object.cpp.
References GetHash(), CMasternodeSync::IsSynced(), LogPrint, masternodeSync, MIN_GOVERNANCE_PEER_PROTO_VERSION, MSG_GOVERNANCE_OBJECT, and CConnman::RelayInv().
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceManager::CheckPostponedObjects(), and gobject_submit().
RemoveInvalidProposalVotes()
std::set< uint256 > CGovernanceObject::RemoveInvalidProposalVotes (const COutPoint & mnOutpoint) private
Definition at line 226 of file governance-object.cpp.
References cs, fDirtyCache, fileVotes, CGovernanceVote::GetHash(), GetHash(), GOVERNANCE_OBJECT_PROPOSAL, LOCK, LogPrintf, mapCurrentMNVotes, nObjectType, CGovernanceObjectVoteFile::RemoveInvalidProposalVotes(), CGovernanceVote::SetTime(), strprintf, and COutPoint::ToString().
RemoveOldVotes()
std::vector< uint256 > CGovernanceObject::RemoveOldVotes (unsigned int nMinTime) private
Definition at line 842 of file governance-object.cpp.
References cs, fDirtyCache, fileVotes, GetHash(), LOCK, LogPrintf, mapCurrentMNVotes, CGovernanceObjectVoteFile::RemoveOldVotes(), strprintf, and base_blob< BITS >::ToString().
SerializationOp()
template<typename Stream , typename Operation > void CGovernanceObject::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 313 of file governance-object.h.
References fExpired, fileVotes, GetHash(), CGovernanceObjectVoteFile::GetVoteCount(), LogPrint, mapCurrentMNVotes, masternodeOutpoint, nCollateralHash, nDeletionTime, nHashParent, nObjectType, nRevision, nTime, READWRITE, SER_DISK, SER_GETHASH, vchData, and vchSig.
SetMasternodeOutpoint()
void CGovernanceObject::SetMasternodeOutpoint (const COutPoint & outpoint)
Definition at line 309 of file governance-object.cpp.
References masternodeOutpoint.
Referenced by gobject_submit().
Sign() [1/2]
bool CGovernanceObject::Sign (const CKey & key, const CKeyID & keyID)
Definition at line 314 of file governance-object.cpp.
References GetSignatureHash(), GetSignatureMessage(), CSporkManager::IsSporkActive(), LogPrint, LogPrintf, masternodeOutpoint, CHashSigner::SignHash(), CMessageSigner::SignMessage(), SPORK_6_NEW_SIGS, sporkManager, base_blob< BITS >::ToString(), COutPoint::ToStringShort(), vchSig, CHashSigner::VerifyHash(), and CMessageSigner::VerifyMessage().
Referenced by gobject_submit().
Sign() [2/2]
bool CGovernanceObject::Sign (const CBLSSecretKey & key)
Definition at line 378 of file governance-object.cpp.
References CBLSWrapper< ImplType, _SerSize, C >::GetBuf(), GetSignatureHash(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CBLSSecretKey::Sign(), and vchSig.
UpdateLocalValidity()
void CGovernanceObject::UpdateLocalValidity ()
Definition at line 503 of file governance-object.cpp.
References cs_main, fCachedLocalValidity, IsValidLocally(), LOCK, and strLocalValidityError.
Referenced by CGovernanceManager::UpdateCachesAndClean().
UpdateSentinelVariables()
void CGovernanceObject::UpdateSentinelVariables ()
Definition at line 778 of file governance-object.cpp.
References CMasternodeMan::CountEnabled(), fCachedDelete, fCachedEndorsed, fCachedFunding, fCachedValid, fDirtyCache, GetAbsoluteNoCount(), GetAbsoluteYesCount(), GetAdjustedTime(), mnodeman, nDeletionTime, Params(), VOTE_SIGNAL_DELETE, VOTE_SIGNAL_ENDORSED, VOTE_SIGNAL_FUNDING, and VOTE_SIGNAL_VALID.
Referenced by CGovernanceManager::AddGovernanceObject(), CSuperblockManager::IsSuperblockTriggered(), and CGovernanceManager::UpdateCachesAndClean().
Friends And Related Function Documentation
CGovernanceManager
friend class CGovernanceManager friend
Definition at line 112 of file governance-object.h.
CGovernanceTriggerManager
friend class CGovernanceTriggerManager friend
Definition at line 113 of file governance-object.h.
CSuperblock
friend class CSuperblock friend
Definition at line 114 of file governance-object.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CGovernanceObject::ADD_SERIALIZE_METHODS
Definition at line 310 of file governance-object.h.
cmmapOrphanVotes
vote_cmm_t CGovernanceObject::cmmapOrphanVotes private
Limited map of votes orphaned by MN.
Definition at line 186 of file governance-object.h.
Referenced by CheckOrphanVotes(), and ProcessVote().
cs
CCriticalSection CGovernanceObject::cs mutable private
critical section to protect the inner data structures
Definition at line 127 of file governance-object.h.
Referenced by ClearMasternodeVotes(), CountMatchingVotes(), GetCurrentMNVotes(), GetSignatureMessage(), ProcessVote(), RemoveInvalidProposalVotes(), and RemoveOldVotes().
fCachedDelete
bool CGovernanceObject::fCachedDelete private
true == minimum network support has been reached saying this object should be deleted from the system entirely
Definition at line 167 of file governance-object.h.
Referenced by CGovernanceManager::AddCachedTriggers(), CGovernanceManager::AddGovernanceObject(), CGovernanceTriggerManager::CleanAndRemove(), IsSetCachedDelete(), CGovernanceManager::UpdateCachesAndClean(), and UpdateSentinelVariables().
fCachedEndorsed
bool CGovernanceObject::fCachedEndorsed private
true == minimum network support has been reached flagging this object as endorsed by an elected representative body (e.g.
business review board / technecial review board /etc)
Definition at line 172 of file governance-object.h.
Referenced by IsSetCachedEndorsed(), and UpdateSentinelVariables().
fCachedFunding
bool CGovernanceObject::fCachedFunding private
true == minimum network support has been reached for this object to be funded (doesn't mean it will for sure though)
Definition at line 161 of file governance-object.h.
Referenced by IsSetCachedFunding(), and UpdateSentinelVariables().
fCachedLocalValidity
bool CGovernanceObject::fCachedLocalValidity private
is valid by blockchain
Definition at line 155 of file governance-object.h.
Referenced by UpdateLocalValidity().
fCachedValid
bool CGovernanceObject::fCachedValid private
true == minimum network has been reached flagging this object as a valid and understood governance object (e.g, the serialized data is correct format, etc)
Definition at line 164 of file governance-object.h.
Referenced by IsSetCachedValid(), and UpdateSentinelVariables().
fDirtyCache
bool CGovernanceObject::fDirtyCache private
object was updated and cached values should be updated soon
Definition at line 175 of file governance-object.h.
Referenced by IsSetDirtyCache(), ProcessVote(), RemoveInvalidProposalVotes(), RemoveOldVotes(), and UpdateSentinelVariables().
fExpired
bool CGovernanceObject::fExpired private
Object is no longer of interest.
Definition at line 178 of file governance-object.h.
Referenced by CSuperblock::IsExpired(), IsSetExpired(), and SerializationOp().
fileVotes
CGovernanceObjectVoteFile CGovernanceObject::fileVotes private
Definition at line 188 of file governance-object.h.
Referenced by ClearMasternodeVotes(), GetVoteFile(), ProcessVote(), RemoveInvalidProposalVotes(), RemoveOldVotes(), and SerializationOp().
fUnparsable
bool CGovernanceObject::fUnparsable private
Failed to parse object data.
Definition at line 181 of file governance-object.h.
Referenced by IsValidLocally(), and LoadData().
mapCurrentMNVotes
vote_m_t CGovernanceObject::mapCurrentMNVotes private
Definition at line 183 of file governance-object.h.
Referenced by ClearMasternodeVotes(), CountMatchingVotes(), GetCurrentMNVotes(), ProcessVote(), RemoveInvalidProposalVotes(), RemoveOldVotes(), and SerializationOp().
masternodeOutpoint
COutPoint CGovernanceObject::masternodeOutpoint private
Masternode info for signed objects.
Definition at line 151 of file governance-object.h.
Referenced by GetHash(), GetMasternodeOutpoint(), GetSignatureMessage(), IsValidLocally(), SerializationOp(), SetMasternodeOutpoint(), and Sign().
nCollateralHash
uint256 CGovernanceObject::nCollateralHash private
fee-tx
Definition at line 145 of file governance-object.h.
Referenced by GetCollateralHash(), GetSignatureMessage(), IsCollateralValid(), and SerializationOp().
nDeletionTime
int64_t CGovernanceObject::nDeletionTime private
time this object was marked for deletion
Definition at line 142 of file governance-object.h.
Referenced by CGovernanceManager::AddCachedTriggers(), CGovernanceTriggerManager::CleanAndRemove(), GetDeletionTime(), CSuperblock::IsExpired(), SerializationOp(), CGovernanceManager::UpdateCachesAndClean(), and UpdateSentinelVariables().
nHashParent
uint256 CGovernanceObject::nHashParent private
parent object, 0 is root
Definition at line 133 of file governance-object.h.
Referenced by GetHash(), GetSignatureMessage(), and SerializationOp().
nObjectType
int CGovernanceObject::nObjectType private
Object typecode.
Definition at line 130 of file governance-object.h.
Referenced by CGovernanceManager::AddCachedTriggers(), CGovernanceManager::AddGovernanceObject(), GetMinCollateralFee(), GetObjectType(), IsValidLocally(), LoadData(), ProcessVote(), RemoveInvalidProposalVotes(), and SerializationOp().
nRevision
int CGovernanceObject::nRevision private
object revision in the system
Definition at line 136 of file governance-object.h.
Referenced by GetHash(), GetSignatureMessage(), and SerializationOp().
nTime
int64_t CGovernanceObject::nTime private
time this object was created
Definition at line 139 of file governance-object.h.
Referenced by GetCreationTime(), GetHash(), GetSignatureMessage(), and SerializationOp().
strLocalValidityError
std::string CGovernanceObject::strLocalValidityError private
Definition at line 156 of file governance-object.h.
Referenced by UpdateLocalValidity().
vchData
std::vector<unsigned char> CGovernanceObject::vchData private
Data field - can be used for anything.
Definition at line 148 of file governance-object.h.
Referenced by GetDataAsHexString(), GetDataAsPlainString(), GetJSONObject(), LoadData(), and SerializationOp().
vchSig
std::vector<unsigned char> CGovernanceObject::vchSig private
Definition at line 152 of file governance-object.h.
Referenced by CheckSignature(), GetHash(), SerializationOp(), and Sign().
The documentation for this class was generated from the following files:
src/governance-object.h
src/governance-object.cpp
Released under the MIT license