Dash Core: llmq::CDummyContribution Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
llmq::CDummyContribution Class Reference
#include <quorums_dummydkg.h>
Public Member Functions
template<typename Stream , typename Operation >
ADD_SERIALIZE_METHODS void SerializationOp (Stream &s, Operation ser_action)
uint256 GetSignHash () const
Public Attributes
uint8_t llmqType {Consensus::LLMQ_NONE}
uint256 quorumHash
uint16_t signer {(uint16_t)-1}
CBLSSignature sig
Detailed Description
Definition at line 49 of file quorums_dummydkg.h.
Member Function Documentation
GetSignHash()
uint256 llmq::CDummyContribution::GetSignHash () const inline
Definition at line 70 of file quorums_dummydkg.h.
References SerializeHash(), and sig.
Referenced by llmq::CDummyDKG::CreateDummyContribution(), and llmq::CDummyDKG::ProcessDummyContribution().
SerializationOp()
template<typename Stream , typename Operation > ADD_SERIALIZE_METHODS void llmq::CDummyContribution::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 62 of file quorums_dummydkg.h.
References llmqType, quorumHash, READWRITE, sig, and signer.
Member Data Documentation
llmqType
uint8_t llmq::CDummyContribution::llmqType {Consensus::LLMQ_NONE}
Definition at line 52 of file quorums_dummydkg.h.
Referenced by llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::ProcessDummyContribution(), and SerializationOp().
quorumHash
uint256 llmq::CDummyContribution::quorumHash
Definition at line 53 of file quorums_dummydkg.h.
Referenced by llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::ProcessDummyContribution(), and SerializationOp().
sig
CBLSSignature llmq::CDummyContribution::sig
Definition at line 56 of file quorums_dummydkg.h.
Referenced by llmq::CDummyDKG::CreateDummyContribution(), GetSignHash(), llmq::CDummyDKG::ProcessDummyContribution(), and SerializationOp().
signer
uint16_t llmq::CDummyContribution::signer {(uint16_t)-1}
Definition at line 54 of file quorums_dummydkg.h.
Referenced by llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::ProcessDummyContribution(), and SerializationOp().
The documentation for this class was generated from the following file:
src/llmq/quorums_dummydkg.h
Released under the MIT license