Dash Core: CInstantSend Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CInstantSend Class Reference
Manages InstantSend.
#include <instantx.h>
Public Member Functions
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
void Clear ()
void ProcessMessage (CNode *pfrom, const std::string &strCommand, CDataStream &vRecv, CConnman &connman)
bool ProcessTxLockRequest (const CTxLockRequest &txLockRequest, CConnman &connman)
void Vote (const uint256 &txHash, CConnman &connman)
bool AlreadyHave (const uint256 &hash)
void AcceptLockRequest (const CTxLockRequest &txLockRequest)
void RejectLockRequest (const CTxLockRequest &txLockRequest)
bool HasTxLockRequest (const uint256 &txHash)
bool GetTxLockRequest (const uint256 &txHash, CTxLockRequest &txLockRequestRet)
bool GetTxLockVote (const uint256 &hash, CTxLockVote &txLockVoteRet)
bool GetLockedOutPointTxHash (const COutPoint &outpoint, uint256 &hashRet)
bool IsLockedInstantSendTransaction (const uint256 &txHash)
Verify if transaction is currently locked.
int GetTransactionLockSignatures (const uint256 &txHash)
Get the actual number of accepted lock signatures.
void CheckAndRemove ()
Remove expired entries from maps.
bool IsTxLockCandidateTimedOut (const uint256 &txHash)
Verify if transaction lock timed out.
void Relay (const uint256 &txHash, CConnman &connman)
void UpdatedBlockTip (const CBlockIndex *pindex)
void SyncTransaction (const CTransaction &tx, const CBlockIndex *pindex, int posInBlock)
std::string ToString () const
void DoMaintenance ()
Static Public Member Functions
static bool CanAutoLock ()
checks if we can automatically lock "simple" transactions
Public Attributes
CCriticalSection cs_instantsend
ADD_SERIALIZE_METHODS
Static Public Attributes
static std::atomic< bool > isAutoLockBip9Active {false}
flag of the AutoLock Bip9 activation
Private Member Functions
bool CreateTxLockCandidate (const CTxLockRequest &txLockRequest)
void CreateEmptyTxLockCandidate (const uint256 &txHash)
void Vote (CTxLockCandidate &txLockCandidate, CConnman &connman)
bool ProcessNewTxLockVote (CNode *pfrom, const CTxLockVote &vote, CConnman &connman)
Process consensus vote message.
void UpdateVotedOutpoints (const CTxLockVote &vote, CTxLockCandidate &txLockCandidate)
bool ProcessOrphanTxLockVote (const CTxLockVote &vote)
void ProcessOrphanTxLockVotes ()
int64_t GetAverageMasternodeOrphanVoteTime ()
void TryToFinalizeLockCandidate (const CTxLockCandidate &txLockCandidate)
void LockTransactionInputs (const CTxLockCandidate &txLockCandidate)
void UpdateLockedTransaction (const CTxLockCandidate &txLockCandidate)
Update UI and notify external script if any.
bool ResolveConflicts (const CTxLockCandidate &txLockCandidate)
Private Attributes
int nCachedBlockHeight
std::map< uint256, CTxLockRequest > mapLockRequestAccepted
Tx hash - Tx.
std::map< uint256, CTxLockRequest > mapLockRequestRejected
Tx hash - Tx.
std::map< uint256, CTxLockVote > mapTxLockVotes
Vote hash - Vote.
std::map< uint256, CTxLockVote > mapTxLockVotesOrphan
Vote hash - Vote.
std::map< uint256, CTxLockCandidate > mapTxLockCandidates
Tx hash - Lock candidate.
std::map< COutPoint, std::set< uint256 > > mapVotedOutpoints
UTXO - Tx hash set.
std::map< COutPoint, uint256 > mapLockedOutpoints
UTXO - Tx hash.
std::map< COutPoint, int64_t > mapMasternodeOrphanVotes
Track masternodes who voted with no txlockrequest (for DOS protection)
Static Private Attributes
static const std::string SERIALIZATION_VERSION_STRING = "CInstantSend-Version-1"
static const double AUTO_IX_MEMPOOL_THRESHOLD = 0.1
Automatic locks of "simple" transactions are only allowed when mempool usage is lower than this threshold.
Detailed Description
Manages InstantSend.
Processes lock requests, candidates, and votes.
Definition at line 46 of file instantx.h.
Member Function Documentation
AcceptLockRequest()
void CInstantSend::AcceptLockRequest (const CTxLockRequest & txLockRequest)
Definition at line 753 of file instantx.cpp.
References cs_instantsend, CTxLockRequest::GetHash(), LOCK, and mapLockRequestAccepted.
Referenced by ProcessMessage(), and CWalletTx::RelayWalletTransaction().
AlreadyHave()
bool CInstantSend::AlreadyHave (const uint256 & hash)
Definition at line 745 of file instantx.cpp.
References cs_instantsend, LOCK, mapLockRequestAccepted, mapLockRequestRejected, and mapTxLockVotes.
Referenced by AlreadyHave().
CanAutoLock()
bool CInstantSend::CanAutoLock () static
checks if we can automatically lock "simple" transactions
Definition at line 937 of file instantx.cpp.
References AUTO_IX_MEMPOOL_THRESHOLD, isAutoLockBip9Active, CSporkManager::IsSporkActive(), mempool, SPORK_16_INSTANTSEND_AUTOLOCKS, sporkManager, and CTxMemPool::UsedMemoryShare().
Referenced by CTxLockRequest::GetMinFee(), ProcessMessage(), and CWalletTx::RelayWalletTransaction().
CheckAndRemove()
void CInstantSend::CheckAndRemove ()
Remove expired entries from maps.
Definition at line 667 of file instantx.cpp.
References cs_instantsend, CTxLockCandidate::GetHash(), GetTime(), CTxLockCandidate::IsExpired(), CMasternodeSync::IsMasternodeListSynced(), LOCK, LogPrint, LogPrintf, mapLockedOutpoints, mapLockRequestAccepted, mapLockRequestRejected, mapMasternodeOrphanVotes, CTxLockCandidate::mapOutPointLocks, mapTxLockCandidates, mapTxLockVotes, mapTxLockVotesOrphan, mapVotedOutpoints, masternodeSync, nCachedBlockHeight, base_blob< BITS >::ToString(), and ToString().
Referenced by DoMaintenance(), and ResolveConflicts().
Clear()
void CInstantSend::Clear ()
Definition at line 793 of file instantx.cpp.
References cs_instantsend, LOCK, mapLockedOutpoints, mapLockRequestAccepted, mapLockRequestRejected, mapMasternodeOrphanVotes, mapTxLockCandidates, mapTxLockVotes, mapTxLockVotesOrphan, mapVotedOutpoints, and nCachedBlockHeight.
Referenced by SerializationOp().
CreateEmptyTxLockCandidate()
void CInstantSend::CreateEmptyTxLockCandidate (const uint256 & txHash) private
Definition at line 193 of file instantx.cpp.
References LogPrintf, mapTxLockCandidates, and base_blob< BITS >::ToString().
Referenced by ProcessNewTxLockVote().
CreateTxLockCandidate()
bool CInstantSend::CreateTxLockCandidate (const CTxLockRequest & txLockRequest) private
Definition at line 155 of file instantx.cpp.
References cs_instantsend, CTxLockRequest::GetHash(), CTxLockRequest::IsValid(), LOCK, LogPrint, LogPrintf, mapTxLockCandidates, base_blob< BITS >::ToString(), and CTxLockRequest::tx.
Referenced by ProcessTxLockRequest().
DoMaintenance()
void CInstantSend::DoMaintenance ()
Definition at line 930 of file instantx.cpp.
References CheckAndRemove(), and ShutdownRequested().
Referenced by AppInitMain().
GetAverageMasternodeOrphanVoteTime()
int64_t CInstantSend::GetAverageMasternodeOrphanVoteTime () private
Definition at line 653 of file instantx.cpp.
References cs_instantsend, LOCK, and mapMasternodeOrphanVotes.
Referenced by ProcessNewTxLockVote().
GetLockedOutPointTxHash()
bool CInstantSend::GetLockedOutPointTxHash (const COutPoint & outpoint, uint256 & hashRet)
Definition at line 568 of file instantx.cpp.
References cs_instantsend, LOCK, and mapLockedOutpoints.
Referenced by AcceptToMemoryPoolWorker(), ConnectBlock(), IsLockedInstantSendTransaction(), and ResolveConflicts().
GetTransactionLockSignatures()
int CInstantSend::GetTransactionLockSignatures (const uint256 & txHash)
Get the actual number of accepted lock signatures.
Definition at line 831 of file instantx.cpp.
References cs_instantsend, fEnableInstantSend, GetfLargeWorkForkFound(), GetfLargeWorkInvalidChainFound(), CSporkManager::IsSporkActive(), LOCK, mapTxLockCandidates, SPORK_2_INSTANTSEND_ENABLED, and sporkManager.
Referenced by TransactionDesc::FormatTxStatus().
GetTxLockRequest()
bool CInstantSend::GetTxLockRequest (const uint256 & txHash, CTxLockRequest & txLockRequestRet)
Definition at line 771 of file instantx.cpp.
References cs_instantsend, LOCK, and mapTxLockCandidates.
Referenced by HasTxLockRequest(), ProcessGetData(), and CTxLockVote::Relay().
GetTxLockVote()
bool CInstantSend::GetTxLockVote (const uint256 & hash, CTxLockVote & txLockVoteRet)
Definition at line 782 of file instantx.cpp.
References cs_instantsend, LOCK, and mapTxLockVotes.
Referenced by ProcessGetData().
HasTxLockRequest()
bool CInstantSend::HasTxLockRequest (const uint256 & txHash)
Definition at line 765 of file instantx.cpp.
References GetTxLockRequest().
Referenced by AcceptToMemoryPoolWorker(), entryToJSON(), TransactionDesc::FormatTxStatus(), and CConnman::RelayTransaction().
IsLockedInstantSendTransaction()
bool CInstantSend::IsLockedInstantSendTransaction (const uint256 & txHash)
Verify if transaction is currently locked.
Definition at line 808 of file instantx.cpp.
References cs_instantsend, fEnableInstantSend, GetfLargeWorkForkFound(), GetfLargeWorkInvalidChainFound(), GetLockedOutPointTxHash(), CSporkManager::IsSporkActive(), LOCK, mapTxLockCandidates, SPORK_3_INSTANTSEND_BLOCK_FILTERING, and sporkManager.
Referenced by entryToJSON(), CTxMemPool::Expire(), TransactionDesc::FormatTxStatus(), CGovernanceObject::IsCollateralValid(), CTxLockVote::IsFailed(), CMerkleTx::IsLockedByInstantSend(), TryToFinalizeLockCandidate(), TxToJSON(), UpdateLockedTransaction(), and WalletTxToJSON().
IsTxLockCandidateTimedOut()
bool CInstantSend::IsTxLockCandidateTimedOut (const uint256 & txHash)
Verify if transaction lock timed out.
Definition at line 847 of file instantx.cpp.
References cs_instantsend, fEnableInstantSend, LOCK, and mapTxLockCandidates.
Referenced by TransactionDesc::FormatTxStatus().
LockTransactionInputs()
void CInstantSend::LockTransactionInputs (const CTxLockCandidate & txLockCandidate) private
Definition at line 552 of file instantx.cpp.
References cs_instantsend, CTxLockCandidate::GetHash(), CTxLockCandidate::IsAllOutPointsReady(), CSporkManager::IsSporkActive(), LOCK, LogPrint, mapLockedOutpoints, CTxLockCandidate::mapOutPointLocks, SPORK_2_INSTANTSEND_ENABLED, sporkManager, and base_blob< BITS >::ToString().
Referenced by TryToFinalizeLockCandidate().
ProcessMessage()
void CInstantSend::ProcessMessage (CNode * pfrom, const std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 56 of file instantx.cpp.
References cs_instantsend, cs_main, fLiteMode, CNode::GetSendVersion(), CNode::id, CMasternodeSync::IsMasternodeListSynced(), CSporkManager::IsSporkActive(), LOCK, LogPrint, mapTxLockVotes, masternodeSync, MIN_INSTANTSEND_PROTO_VERSION, CNode::nVersion, ProcessNewTxLockVote(), CConnman::PushMessage(), NetMsgType::REJECT, REJECT_OBSOLETE, CConnman::RemoveAskFor(), SPORK_2_INSTANTSEND_ENABLED, sporkManager, strprintf, and NetMsgType::TXLOCKVOTE.
Referenced by ProcessMessage().
ProcessNewTxLockVote()
bool CInstantSend::ProcessNewTxLockVote (CNode * pfrom, const CTxLockVote & vote, CConnman & connman) private
Process consensus vote message.
Definition at line 326 of file instantx.cpp.
References CTxLockCandidate::AddVote(), CTxLockCandidate::CountVotes(), CreateEmptyTxLockCandidate(), CTxMemPool::cs, cs_instantsend, cs_main, CWallet::cs_wallet, GetAverageMasternodeOrphanVoteTime(), CTxLockVote::GetHash(), CTxLockVote::GetMasternodeOutpoint(), CTxLockRequest::GetMaxSignatures(), GetTime(), CTxLockVote::GetTxHash(), CTxLockCandidate::IsTimedOut(), CTxLockVote::IsValid(), LOCK, LOCK2, LogPrint, mapMasternodeOrphanVotes, mapTxLockCandidates, mapTxLockVotesOrphan, mempool, pwalletMain, CTxLockVote::Relay(), base_blob< BITS >::ToString(), COutPoint::ToStringShort(), TryToFinalizeLockCandidate(), CTxLockCandidate::txLockRequest, and UpdateVotedOutpoints().
Referenced by ProcessMessage().
ProcessOrphanTxLockVote()
bool CInstantSend::ProcessOrphanTxLockVote (const CTxLockVote & vote) private
Definition at line 408 of file instantx.cpp.
References CTxLockCandidate::AddVote(), AssertLockHeld, CTxLockCandidate::CountVotes(), cs_instantsend, cs_main, CWallet::cs_wallet, CTxLockVote::GetHash(), CTxLockRequest::GetMaxSignatures(), CTxLockVote::GetTxHash(), CTxLockCandidate::IsTimedOut(), LogPrint, mapTxLockCandidates, pwalletMain, base_blob< BITS >::ToString(), CTxLockCandidate::txLockRequest, and UpdateVotedOutpoints().
Referenced by ProcessOrphanTxLockVotes().
ProcessOrphanTxLockVotes()
void CInstantSend::ProcessOrphanTxLockVotes () private
Definition at line 486 of file instantx.cpp.
References AssertLockHeld, cs_instantsend, cs_main, mapTxLockVotesOrphan, and ProcessOrphanTxLockVote().
Referenced by ProcessTxLockRequest().
ProcessTxLockRequest()
bool CInstantSend::ProcessTxLockRequest (const CTxLockRequest & txLockRequest, CConnman & connman)
Definition at line 97 of file instantx.cpp.
References CreateTxLockCandidate(), CTxMemPool::cs, cs_instantsend, cs_main, CWallet::cs_wallet, CTxLockRequest::GetHash(), GetMainSignals(), LOCK, LOCK2, LogPrint, LogPrintf, mapLockedOutpoints, mapTxLockCandidates, mapVotedOutpoints, mempool, CMainSignals::NotifyInstantSendDoubleSpendAttempt, ProcessOrphanTxLockVotes(), pwalletMain, base_blob< BITS >::ToString(), TryToFinalizeLockCandidate(), and CTxLockRequest::tx.
Referenced by ProcessMessage(), CWalletTx::RelayWalletTransaction(), and sendrawtransaction().
RejectLockRequest()
void CInstantSend::RejectLockRequest (const CTxLockRequest & txLockRequest)
Definition at line 759 of file instantx.cpp.
References cs_instantsend, CTxLockRequest::GetHash(), LOCK, and mapLockRequestRejected.
Referenced by ProcessMessage(), and CWalletTx::RelayWalletTransaction().
Relay()
void CInstantSend::Relay (const uint256 & txHash, CConnman & connman)
Definition at line 862 of file instantx.cpp.
References cs_instantsend, LOCK, and mapTxLockCandidates.
ResolveConflicts()
bool CInstantSend::ResolveConflicts (const CTxLockCandidate & txLockCandidate) private
Definition at line 577 of file instantx.cpp.
References AssertLockHeld, CheckAndRemove(), indirectmap< K, T >::count(), CTxMemPool::cs, cs_instantsend, cs_main, indirectmap< K, T >::find(), CTxLockCandidate::GetHash(), GetLockedOutPointTxHash(), GetTransaction(), GetUTXOCoin(), CTxLockCandidate::IsAllOutPointsReady(), LogPrint, LogPrintf, mapLockRequestRejected, CTxMemPool::mapNextTx, mapTxLockCandidates, mempool, Params(), base_blob< BITS >::ToString(), CTxLockRequest::tx, and CTxLockCandidate::txLockRequest.
Referenced by TryToFinalizeLockCandidate().
SerializationOp()
template<typename Stream , typename Operation > void CInstantSend::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 95 of file instantx.h.
References Clear(), mapLockedOutpoints, mapLockRequestAccepted, mapLockRequestRejected, mapMasternodeOrphanVotes, mapTxLockCandidates, mapTxLockVotes, mapTxLockVotesOrphan, mapVotedOutpoints, nCachedBlockHeight, READWRITE, and SERIALIZATION_VERSION_STRING.
SyncTransaction()
void CInstantSend::SyncTransaction (const CTransaction & tx, const CBlockIndex * pindex, int posInBlock)
Definition at line 877 of file instantx.cpp.
References cs_instantsend, cs_main, CTransaction::GetHash(), CTransaction::IsCoinBase(), LOCK2, LogPrint, mapTxLockCandidates, mapTxLockVotes, mapTxLockVotesOrphan, CBlockIndex::nHeight, CMainSignals::SYNC_TRANSACTION_NOT_IN_BLOCK, and base_blob< BITS >::ToString().
Referenced by CDSNotificationInterface::SyncTransaction().
ToString()
std::string CInstantSend::ToString () const
Definition at line 924 of file instantx.cpp.
References cs_instantsend, LOCK, mapTxLockCandidates, mapTxLockVotes, and strprintf.
Referenced by CheckAndRemove().
TryToFinalizeLockCandidate()
void CInstantSend::TryToFinalizeLockCandidate (const CTxLockCandidate & txLockCandidate) private
Definition at line 501 of file instantx.cpp.
References AssertLockHeld, cs_instantsend, cs_main, CTxLockCandidate::IsAllOutPointsReady(), IsLockedInstantSendTransaction(), CSporkManager::IsSporkActive(), LockTransactionInputs(), LogPrint, ResolveConflicts(), SPORK_2_INSTANTSEND_ENABLED, sporkManager, base_blob< BITS >::ToString(), CTxLockRequest::tx, CTxLockCandidate::txLockRequest, and UpdateLockedTransaction().
Referenced by ProcessNewTxLockVote(), ProcessTxLockRequest(), and Vote().
UpdatedBlockTip()
void CInstantSend::UpdatedBlockTip (const CBlockIndex * pindex)
Definition at line 872 of file instantx.cpp.
References nCachedBlockHeight, and CBlockIndex::nHeight.
Referenced by CDSNotificationInterface::UpdatedBlockTip().
UpdateLockedTransaction()
void CInstantSend::UpdateLockedTransaction (const CTxLockCandidate & txLockCandidate) private
Update UI and notify external script if any.
Definition at line 519 of file instantx.cpp.
References AssertLockHeld, cs_instantsend, cs_main, CWallet::cs_wallet, GetArg(), CTxLockCandidate::GetHash(), base_blob< BITS >::GetHex(), GetMainSignals(), IsLockedInstantSendTransaction(), LogPrint, nCompleteTXLocks, CMainSignals::NotifyTransactionLock, pwalletMain, runCommand(), base_blob< BITS >::ToString(), CTxLockRequest::tx, CTxLockCandidate::txLockRequest, and CWallet::UpdatedTransaction().
Referenced by TryToFinalizeLockCandidate().
UpdateVotedOutpoints()
void CInstantSend::UpdateVotedOutpoints (const CTxLockVote & vote, CTxLockCandidate & txLockCandidate) private
Definition at line 449 of file instantx.cpp.
References AssertLockHeld, cs_instantsend, CTxLockVote::GetMasternodeOutpoint(), CTxLockVote::GetOutpoint(), CTxLockVote::GetTxHash(), LogPrintf, mapTxLockCandidates, mapVotedOutpoints, CTxLockCandidate::MarkOutpointAsAttacked(), mnodeman, CMasternodeMan::PoSeBan(), and COutPoint::ToStringShort().
Referenced by ProcessNewTxLockVote(), and ProcessOrphanTxLockVote().
Vote() [1/2]
void CInstantSend::Vote (CTxLockCandidate & txLockCandidate, CConnman & connman) private
Definition at line 224 of file instantx.cpp.
References activeMasternodeInfo, AssertLockHeld, CTxLockVote::CheckSignature(), cs_instantsend, cs_main, deterministicMNManager, fMasternodeMode, CChainParams::GetConsensus(), CTxLockVote::GetHash(), CTxLockCandidate::GetHash(), CMasternodeMan::GetMasternodeRank(), CMasternodePayments::GetMinMasternodePaymentsProto(), GetUTXOHeight(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CSporkManager::IsSporkActive(), LogPrint, LogPrintf, mapLockRequestAccepted, CTxLockCandidate::mapOutPointLocks, mapTxLockCandidates, mapTxLockVotes, mapVotedOutpoints, MIN_INSTANTSEND_PROTO_VERSION, mnodeman, mnpayments, Consensus::Params::nInstantSendConfirmationsRequired, CActiveMasternodeInfo::outpoint, Params(), CActiveMasternodeInfo::proTxHash, CTxLockVote::Relay(), CTxLockVote::Sign(), COutPointLock::SIGNATURES_TOTAL, SPORK_2_INSTANTSEND_ENABLED, sporkManager, base_blob< BITS >::ToString(), and COutPoint::ToStringShort().
Referenced by ProcessMessage(), and Vote().
Vote() [2/2]
void CInstantSend::Vote (const uint256 & txHash, CConnman & connman)
Definition at line 202 of file instantx.cpp.
References AssertLockHeld, CTxMemPool::cs, cs_instantsend, cs_main, CWallet::cs_wallet, LOCK, LOCK2, mapTxLockCandidates, mempool, pwalletMain, TryToFinalizeLockCandidate(), and Vote().
Member Data Documentation
ADD_SERIALIZE_METHODS
CInstantSend::ADD_SERIALIZE_METHODS
Definition at line 92 of file instantx.h.
AUTO_IX_MEMPOOL_THRESHOLD
const double CInstantSend::AUTO_IX_MEMPOOL_THRESHOLD = 0.1 static private
Automatic locks of "simple" transactions are only allowed when mempool usage is lower than this threshold.
Definition at line 52 of file instantx.h.
Referenced by CanAutoLock().
cs_instantsend
CCriticalSection CInstantSend::cs_instantsend mutable
Definition at line 90 of file instantx.h.
Referenced by AcceptLockRequest(), AlreadyHave(), CheckAndRemove(), Clear(), CreateTxLockCandidate(), GetAverageMasternodeOrphanVoteTime(), GetLockedOutPointTxHash(), GetTransactionLockSignatures(), GetTxLockRequest(), GetTxLockVote(), IsLockedInstantSendTransaction(), IsTxLockCandidateTimedOut(), LockTransactionInputs(), ProcessMessage(), ProcessNewTxLockVote(), ProcessOrphanTxLockVote(), ProcessOrphanTxLockVotes(), ProcessTxLockRequest(), RejectLockRequest(), Relay(), ResolveConflicts(), SyncTransaction(), ToString(), TryToFinalizeLockCandidate(), UpdateLockedTransaction(), UpdateVotedOutpoints(), and Vote().
isAutoLockBip9Active
std::atomic< bool > CInstantSend::isAutoLockBip9Active {false} static
flag of the AutoLock Bip9 activation
Definition at line 161 of file instantx.h.
Referenced by CanAutoLock(), DisconnectBlock(), and CDSNotificationInterface::UpdatedBlockTip().
mapLockedOutpoints
std::map<COutPoint, uint256> CInstantSend::mapLockedOutpoints private
UTXO - Tx hash.
Definition at line 66 of file instantx.h.
Referenced by CheckAndRemove(), Clear(), GetLockedOutPointTxHash(), LockTransactionInputs(), ProcessTxLockRequest(), and SerializationOp().
mapLockRequestAccepted
std::map<uint256, CTxLockRequest> CInstantSend::mapLockRequestAccepted private
Tx hash - Tx.
Definition at line 58 of file instantx.h.
Referenced by AcceptLockRequest(), AlreadyHave(), CheckAndRemove(), Clear(), SerializationOp(), and Vote().
mapLockRequestRejected
std::map<uint256, CTxLockRequest> CInstantSend::mapLockRequestRejected private
Tx hash - Tx.
Definition at line 59 of file instantx.h.
Referenced by AlreadyHave(), CheckAndRemove(), Clear(), RejectLockRequest(), ResolveConflicts(), and SerializationOp().
mapMasternodeOrphanVotes
std::map<COutPoint, int64_t> CInstantSend::mapMasternodeOrphanVotes private
Track masternodes who voted with no txlockrequest (for DOS protection)
MN outpoint - Time
Definition at line 69 of file instantx.h.
Referenced by CheckAndRemove(), Clear(), GetAverageMasternodeOrphanVoteTime(), ProcessNewTxLockVote(), and SerializationOp().
mapTxLockCandidates
std::map<uint256, CTxLockCandidate> CInstantSend::mapTxLockCandidates private
Tx hash - Lock candidate.
Definition at line 63 of file instantx.h.
Referenced by CheckAndRemove(), Clear(), CreateEmptyTxLockCandidate(), CreateTxLockCandidate(), GetTransactionLockSignatures(), GetTxLockRequest(), IsLockedInstantSendTransaction(), IsTxLockCandidateTimedOut(), ProcessNewTxLockVote(), ProcessOrphanTxLockVote(), ProcessTxLockRequest(), Relay(), ResolveConflicts(), SerializationOp(), SyncTransaction(), ToString(), UpdateVotedOutpoints(), and Vote().
mapTxLockVotes
std::map<uint256, CTxLockVote> CInstantSend::mapTxLockVotes private
Vote hash - Vote.
Definition at line 60 of file instantx.h.
Referenced by AlreadyHave(), CheckAndRemove(), Clear(), GetTxLockVote(), ProcessMessage(), SerializationOp(), SyncTransaction(), ToString(), and Vote().
mapTxLockVotesOrphan
std::map<uint256, CTxLockVote> CInstantSend::mapTxLockVotesOrphan private
Vote hash - Vote.
Definition at line 61 of file instantx.h.
Referenced by CheckAndRemove(), Clear(), ProcessNewTxLockVote(), ProcessOrphanTxLockVotes(), SerializationOp(), and SyncTransaction().
mapVotedOutpoints
std::map<COutPoint, std::set<uint256> > CInstantSend::mapVotedOutpoints private
UTXO - Tx hash set.
Definition at line 65 of file instantx.h.
Referenced by CheckAndRemove(), Clear(), ProcessTxLockRequest(), SerializationOp(), UpdateVotedOutpoints(), and Vote().
nCachedBlockHeight
int CInstantSend::nCachedBlockHeight private
Definition at line 55 of file instantx.h.
Referenced by CheckAndRemove(), Clear(), SerializationOp(), and UpdatedBlockTip().
SERIALIZATION_VERSION_STRING
const std::string CInstantSend::SERIALIZATION_VERSION_STRING = "CInstantSend-Version-1" static private
Definition at line 49 of file instantx.h.
Referenced by SerializationOp().
The documentation for this class was generated from the following files:
src/instantx.h
src/instantx.cpp
Released under the MIT license