Dash Core: CEvoDB Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CEvoDB Class Reference
#include <evodb.h>
Public Member Functions
CEvoDB (size_t nCacheSize, bool fMemory=false, bool fWipe=false)
std::unique_ptr< ScopedTransaction > BeginTransaction ()
template<typename K , typename V >
bool Read (const K &key, V &value)
template<typename K , typename V >
void Write (const K &key, const V &value)
template<typename K >
bool Exists (const K &key)
template<typename K >
void Erase (const K &key)
CDBWrapper & GetRawDB ()
bool CommitRootTransaction ()
bool VerifyBestBlock (const uint256 &hash)
void WriteBestBlock (const uint256 &hash)
Private Types
typedef CDBTransaction< CDBWrapper, CDBBatch > RootTransaction
typedef CDBTransaction< RootTransaction, RootTransaction > CurTransaction
typedef CScopedDBTransaction< RootTransaction, RootTransaction > ScopedTransaction
Private Attributes
CCriticalSection cs
CDBWrapper db
CDBBatch rootBatch
RootTransaction rootDBTransaction
CurTransaction curDBTransaction
Detailed Description
Definition at line 14 of file evodb.h.
Member Typedef Documentation
CurTransaction
typedef CDBTransaction<RootTransaction, RootTransaction> CEvoDB::CurTransaction private
Definition at line 21 of file evodb.h.
RootTransaction
typedef CDBTransaction<CDBWrapper, CDBBatch> CEvoDB::RootTransaction private
Definition at line 20 of file evodb.h.
ScopedTransaction
typedef CScopedDBTransaction<RootTransaction, RootTransaction> CEvoDB::ScopedTransaction private
Definition at line 22 of file evodb.h.
Constructor & Destructor Documentation
CEvoDB()
CEvoDB::CEvoDB (size_t nCacheSize, bool fMemory = false, bool fWipe = false)
Definition at line 9 of file evodb.cpp.
Member Function Documentation
BeginTransaction()
std::unique_ptr<ScopedTransaction> CEvoDB::BeginTransaction () inline
Definition at line 31 of file evodb.h.
References CScopedDBTransaction< Parent, CommitTarget >::Begin(), cs, curDBTransaction, and LOCK.
Referenced by ConnectTip(), DisconnectTip(), TestBlockValidity(), and CVerifyDB::VerifyDB().
CommitRootTransaction()
bool CEvoDB::CommitRootTransaction ()
Definition at line 17 of file evodb.cpp.
References CDBBatch::Clear(), CDBTransaction< Parent, CommitTarget >::Commit(), curDBTransaction, db, CDBTransaction< Parent, CommitTarget >::IsClean(), rootBatch, rootDBTransaction, and CDBWrapper::WriteBatch().
Referenced by FlushStateToDisk().
Erase()
template<typename K > void CEvoDB::Erase (const K & key) inline
Definition at line 60 of file evodb.h.
References cs, curDBTransaction, CDBTransaction< Parent, CommitTarget >::Erase(), and LOCK.
Referenced by llmq::CQuorumBlockProcessor::UndoBlock(), and CDeterministicMNManager::UndoBlock().
Exists()
template<typename K > bool CEvoDB::Exists (const K & key) inline
Definition at line 53 of file evodb.h.
References cs, curDBTransaction, CDBTransaction< Parent, CommitTarget >::Exists(), and LOCK.
Referenced by llmq::CQuorumBlockProcessor::HasMinedCommitment().
GetRawDB()
CDBWrapper& CEvoDB::GetRawDB () inline
Definition at line 66 of file evodb.h.
References db.
Read()
template<typename K , typename V > bool CEvoDB::Read (const K & key, V & value) inline
Definition at line 39 of file evodb.h.
References cs, curDBTransaction, LOCK, and CDBTransaction< Parent, CommitTarget >::Read().
Referenced by CDeterministicMNManager::GetListForBlock(), llmq::CQuorumBlockProcessor::GetMinedCommitment(), and VerifyBestBlock().
VerifyBestBlock()
bool CEvoDB::VerifyBestBlock (const uint256 & hash)
Definition at line 26 of file evodb.cpp.
References EVODB_BEST_BLOCK, and Read().
Referenced by ConnectBlock(), and DisconnectBlock().
Write()
template<typename K , typename V > void CEvoDB::Write (const K & key, const V & value) inline
Definition at line 46 of file evodb.h.
References cs, curDBTransaction, LOCK, and CDBTransaction< Parent, CommitTarget >::Write().
Referenced by CDeterministicMNManager::ProcessBlock(), llmq::CQuorumBlockProcessor::ProcessCommitment(), and WriteBestBlock().
WriteBestBlock()
void CEvoDB::WriteBestBlock (const uint256 & hash)
Definition at line 38 of file evodb.cpp.
References EVODB_BEST_BLOCK, and Write().
Referenced by ConnectBlock(), and DisconnectBlock().
Member Data Documentation
cs
CCriticalSection CEvoDB::cs private
Definition at line 17 of file evodb.h.
Referenced by BeginTransaction(), Erase(), Exists(), Read(), and Write().
curDBTransaction
CurTransaction CEvoDB::curDBTransaction private
Definition at line 26 of file evodb.h.
Referenced by BeginTransaction(), CommitRootTransaction(), Erase(), Exists(), Read(), and Write().
db
CDBWrapper CEvoDB::db private
Definition at line 18 of file evodb.h.
Referenced by CommitRootTransaction(), and GetRawDB().
rootBatch
CDBBatch CEvoDB::rootBatch private
Definition at line 24 of file evodb.h.
Referenced by CommitRootTransaction().
rootDBTransaction
RootTransaction CEvoDB::rootDBTransaction private
Definition at line 25 of file evodb.h.
Referenced by CommitRootTransaction().
The documentation for this class was generated from the following files:
src/evo/evodb.h
src/evo/evodb.cpp
Released under the MIT license