Dash Core: CMasternodePing Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CMasternodePing Class Reference
#include <masternode.h>
Public Member Functions
CMasternodePing ()=default
CMasternodePing (const COutPoint &outpoint)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
uint256 GetHash () const
uint256 GetSignatureHash () const
bool IsExpired () const
bool Sign (const CKey &keyMasternode, const CKeyID &keyIDOperator)
bool CheckSignature (CKeyID &keyIDOperator, int &nDos) const
bool SimpleCheck (int &nDos)
bool CheckAndUpdate (CMasternode *pmn, bool fFromNewBroadcast, int &nDos, CConnman &connman)
void Relay (CConnman &connman)
std::string GetSentinelString () const
std::string GetDaemonString () const
operator bool () const
Public Attributes
COutPoint masternodeOutpoint {}
uint256 blockHash {}
int64_t sigTime {}
std::vector< unsigned char > vchSig {}
bool fSentinelIsCurrent = false
uint32_t nSentinelVersion {DEFAULT_SENTINEL_VERSION}
uint32_t nDaemonVersion {DEFAULT_DAEMON_VERSION}
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 38 of file masternode.h.
Constructor & Destructor Documentation
CMasternodePing() [1/2]
CMasternodePing::CMasternodePing () default
CMasternodePing() [2/2]
CMasternodePing::CMasternodePing (const COutPoint & outpoint)
Definition at line 758 of file masternode.cpp.
References blockHash, chainActive, CLIENT_VERSION, cs_main, GetAdjustedTime(), CChain::Height(), LOCK, masternodeOutpoint, nDaemonVersion, sigTime, and CChain::Tip().
Member Function Documentation
CheckAndUpdate()
bool CMasternodePing::CheckAndUpdate (CMasternode * pmn, bool fFromNewBroadcast, int & nDos, CConnman & connman)
Definition at line 863 of file masternode.cpp.
References AssertLockHeld, blockHash, CMasternodeSync::BumpAssetLastTime(), chainActive, CMasternode::Check(), CheckSignature(), cs_main, CMasternodeBroadcast::GetHash(), CChain::Height(), CMasternode::IsEnabled(), CMasternode::IsExpired(), CMasternodeSync::IsMasternodeListSynced(), CMasternode::IsNewStartRequired(), CMasternode::IsPingedWithin(), CMasternode::IsSentinelPingExpired(), CMasternode::IsUpdateRequired(), CMasternode::lastPing, masternode_info_t::legacyKeyIDOperator, LogPrint, LogPrintf, mapBlockIndex, CMasternodeMan::mapSeenMasternodeBroadcast, MASTERNODE_EXPIRATION_SECONDS, MASTERNODE_MIN_MNP_SECONDS, masternodeOutpoint, masternodeSync, mnodeman, Relay(), sigTime, SimpleCheck(), base_blob< BITS >::ToString(), and COutPoint::ToStringShort().
Referenced by CMasternode::UpdateFromNewBroadcast().
CheckSignature()
bool CMasternodePing::CheckSignature (CKeyID & keyIDOperator, int & nDos) const
Definition at line 805 of file masternode.cpp.
References blockHash, GetSignatureHash(), CSporkManager::IsSporkActive(), LogPrintf, masternodeOutpoint, sigTime, SPORK_6_NEW_SIGS, sporkManager, base_blob< BITS >::ToString(), CTxIn::ToString(), COutPoint::ToStringShort(), vchSig, CHashSigner::VerifyHash(), and CMessageSigner::VerifyMessage().
Referenced by CheckAndUpdate().
GetDaemonString()
std::string CMasternodePing::GetDaemonString () const
Definition at line 962 of file masternode.cpp.
References DEFAULT_DAEMON_VERSION, FormatVersion(), and nDaemonVersion.
Referenced by masternodelist().
GetHash()
uint256 CMasternodePing::GetHash () const
Definition at line 733 of file masternode.cpp.
References blockHash, fSentinelIsCurrent, CHashWriter::GetHash(), CSporkManager::IsSporkActive(), masternodeOutpoint, nDaemonVersion, nSentinelVersion, PROTOCOL_VERSION, SER_GETHASH, sigTime, SPORK_6_NEW_SIGS, and sporkManager.
Referenced by GetSignatureHash(), CMasternodeMan::PushDsegInvs(), Relay(), CMasternodeMan::SetMasternodeLastPing(), and CMasternode::UpdateFromNewBroadcast().
GetSentinelString()
std::string CMasternodePing::GetSentinelString () const
Definition at line 957 of file masternode.cpp.
References DEFAULT_SENTINEL_VERSION, nSentinelVersion, and SafeIntVersionToString().
Referenced by masternodelist().
GetSignatureHash()
uint256 CMasternodePing::GetSignatureHash () const
Definition at line 753 of file masternode.cpp.
References GetHash().
Referenced by CheckSignature(), and Sign().
IsExpired()
bool CMasternodePing::IsExpired () const inline
Definition at line 72 of file masternode.h.
References GetAdjustedTime(), MASTERNODE_NEW_START_REQUIRED_SECONDS, and sigTime.
operator bool()
CMasternodePing::operator bool () const inline explicit
Definition at line 94 of file masternode.h.
Relay()
void CMasternodePing::Relay (CConnman & connman)
Definition at line 945 of file masternode.cpp.
References GetHash(), CMasternodeSync::IsSynced(), LogPrint, masternodeSync, MSG_MASTERNODE_PING, and CConnman::RelayInv().
Referenced by CheckAndUpdate(), and CActiveLegacyMasternodeManager::SendMasternodePing().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodePing::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 57 of file masternode.h.
References blockHash, fSentinelIsCurrent, masternodeOutpoint, nDaemonVersion, nSentinelVersion, READWRITE, SER_GETHASH, sigTime, and vchSig.
Sign()
bool CMasternodePing::Sign (const CKey & keyMasternode, const CKeyID & keyIDOperator)
Definition at line 769 of file masternode.cpp.
References blockHash, GetAdjustedTime(), GetSignatureHash(), CSporkManager::IsSporkActive(), LogPrintf, masternodeOutpoint, CHashSigner::SignHash(), CMessageSigner::SignMessage(), sigTime, SPORK_6_NEW_SIGS, sporkManager, base_blob< BITS >::ToString(), CTxIn::ToString(), vchSig, CHashSigner::VerifyHash(), and CMessageSigner::VerifyMessage().
Referenced by CActiveLegacyMasternodeManager::SendMasternodePing().
SimpleCheck()
bool CMasternodePing::SimpleCheck (int & nDos)
Definition at line 837 of file masternode.cpp.
References AssertLockHeld, blockHash, cs_main, GetAdjustedTime(), LogPrint, LogPrintf, mapBlockIndex, masternodeOutpoint, sigTime, base_blob< BITS >::ToString(), and COutPoint::ToStringShort().
Referenced by CheckAndUpdate(), and CMasternodeBroadcast::SimpleCheck().
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodePing::ADD_SERIALIZE_METHODS
Definition at line 54 of file masternode.h.
blockHash
uint256 CMasternodePing::blockHash {}
Definition at line 42 of file masternode.h.
Referenced by CheckAndUpdate(), CheckSignature(), CMasternodePing(), GetHash(), masternodebroadcast(), operator==(), SerializationOp(), Sign(), and SimpleCheck().
fSentinelIsCurrent
bool CMasternodePing::fSentinelIsCurrent = false
Definition at line 45 of file masternode.h.
Referenced by CMasternode::Check(), GetHash(), masternodelist(), CActiveLegacyMasternodeManager::SendMasternodePing(), SerializationOp(), and CMasternodeMan::SetMasternodeLastPing().
masternodeOutpoint
COutPoint CMasternodePing::masternodeOutpoint {}
Definition at line 41 of file masternode.h.
Referenced by CheckAndUpdate(), CheckSignature(), CMasternodePing(), GetHash(), masternodebroadcast(), operator==(), SerializationOp(), Sign(), and SimpleCheck().
nDaemonVersion
uint32_t CMasternodePing::nDaemonVersion {DEFAULT_DAEMON_VERSION}
Definition at line 48 of file masternode.h.
Referenced by CMasternodePing(), GetDaemonString(), GetHash(), masternodelist(), SerializationOp(), and MasternodeList::ShowQRCode().
nSentinelVersion
uint32_t CMasternodePing::nSentinelVersion {DEFAULT_SENTINEL_VERSION}
Definition at line 47 of file masternode.h.
Referenced by GetHash(), GetSentinelString(), CActiveLegacyMasternodeManager::SendMasternodePing(), SerializationOp(), and MasternodeList::ShowQRCode().
sigTime
int64_t CMasternodePing::sigTime {}
Definition at line 43 of file masternode.h.
Referenced by CMasternode::Check(), CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CheckSignature(), CMasternodePing(), GetHash(), CMasternode::GetInfo(), IsExpired(), CMasternode::IsPingedWithin(), masternodebroadcast(), masternodelist(), CActiveLegacyMasternodeManager::SendMasternodePing(), SerializationOp(), MasternodeList::ShowQRCode(), Sign(), SimpleCheck(), and MasternodeList::updateNodeList().
vchSig
std::vector<unsigned char> CMasternodePing::vchSig {}
Definition at line 44 of file masternode.h.
Referenced by CheckSignature(), masternodebroadcast(), SerializationOp(), and Sign().
The documentation for this class was generated from the following files:
src/masternode.h
src/masternode.cpp
Released under the MIT license