Dash Core: CDSNotificationInterface Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CDSNotificationInterface Class Reference
#include <dsnotificationinterface.h>
Public Member Functions
CDSNotificationInterface (CConnman &connmanIn)
virtual ~CDSNotificationInterface ()=default
void InitializeCurrentBlockTip ()
Protected Member Functions
void AcceptedBlockHeader (const CBlockIndex *pindexNew) override
void NotifyHeaderTip (const CBlockIndex *pindexNew, bool fInitialDownload) override
void UpdatedBlockTip (const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload) override
void SyncTransaction (const CTransaction &tx, const CBlockIndex *pindex, int posInBlock) override
Protected Member Functions inherited from CValidationInterface
virtual void NotifyTransactionLock (const CTransaction &tx)
virtual void NotifyGovernanceVote (const CGovernanceVote &vote)
virtual void NotifyGovernanceObject (const CGovernanceObject &object)
virtual void NotifyInstantSendDoubleSpendAttempt (const CTransaction &currentTx, const CTransaction &previousTx)
virtual void SetBestChain (const CBlockLocator &locator)
virtual bool UpdatedTransaction (const uint256 &hash)
virtual void Inventory (const uint256 &hash)
virtual void ResendWalletTransactions (int64_t nBestBlockTime, CConnman *connman)
virtual void BlockChecked (const CBlock &, const CValidationState &)
virtual void GetScriptForMining (boost::shared_ptr< CReserveScript > &)
virtual void ResetRequestCount (const uint256 &hash)
virtual void NewPoWValidBlock (const CBlockIndex *pindex, const std::shared_ptr< const CBlock > &block)
friend void ::RegisterValidationInterface (CValidationInterface *)
friend void ::UnregisterValidationInterface (CValidationInterface *)
friend void ::UnregisterAllValidationInterfaces ()
Private Attributes
CConnman & connman
Detailed Description
Definition at line 10 of file dsnotificationinterface.h.
Constructor & Destructor Documentation
CDSNotificationInterface()
CDSNotificationInterface::CDSNotificationInterface (CConnman & connmanIn) inline
Definition at line 13 of file dsnotificationinterface.h.
~CDSNotificationInterface()
virtual CDSNotificationInterface::~CDSNotificationInterface () virtual default
Member Function Documentation
AcceptedBlockHeader()
void CDSNotificationInterface::AcceptedBlockHeader (const CBlockIndex * pindexNew) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 27 of file dsnotificationinterface.cpp.
References CMasternodeSync::AcceptedBlockHeader(), and masternodeSync.
InitializeCurrentBlockTip()
void CDSNotificationInterface::InitializeCurrentBlockTip ()
Definition at line 21 of file dsnotificationinterface.cpp.
References chainActive, cs_main, IsInitialBlockDownload(), LOCK, CChain::Tip(), and UpdatedBlockTip().
Referenced by ThreadImport().
NotifyHeaderTip()
void CDSNotificationInterface::NotifyHeaderTip (const CBlockIndex * pindexNew, bool fInitialDownload) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 32 of file dsnotificationinterface.cpp.
References connman, masternodeSync, and CMasternodeSync::NotifyHeaderTip().
SyncTransaction()
void CDSNotificationInterface::SyncTransaction (const CTransaction & tx, const CBlockIndex * pindex, int posInBlock) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 69 of file dsnotificationinterface.cpp.
References instantsend, CInstantSend::SyncTransaction(), and CPrivateSend::SyncTransaction().
UpdatedBlockTip()
void CDSNotificationInterface::UpdatedBlockTip (const CBlockIndex * pindexNew, const CBlockIndex * pindexFork, bool fInitialDownload) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 37 of file dsnotificationinterface.cpp.
References connman, Consensus::DEPLOYMENT_DIP0003, deterministicMNManager, Consensus::Params::DIP0001Height, fDIP0001ActiveAtTip, fLiteMode, CChainParams::GetConsensus(), governance, instantsend, CInstantSend::isAutoLockBip9Active, masternodeSync, mnodeman, mnpayments, CBlockIndex::nHeight, Params(), privateSendClient, llmq::quorumDummyDKG, THRESHOLD_ACTIVE, CMasternodeSync::UpdatedBlockTip(), llmq::CDummyDKG::UpdatedBlockTip(), CInstantSend::UpdatedBlockTip(), CMasternodePayments::UpdatedBlockTip(), CMasternodeMan::UpdatedBlockTip(), CPrivateSendClientManager::UpdatedBlockTip(), CGovernanceManager::UpdatedBlockTip(), CPrivateSend::UpdatedBlockTip(), CDeterministicMNManager::UpdatedBlockTip(), versionbitscache, and VersionBitsState().
Referenced by InitializeCurrentBlockTip().
Member Data Documentation
connman
CConnman& CDSNotificationInterface::connman private
Definition at line 27 of file dsnotificationinterface.h.
Referenced by NotifyHeaderTip(), and UpdatedBlockTip().
The documentation for this class was generated from the following files:
src/dsnotificationinterface.h
src/dsnotificationinterface.cpp
Released under the MIT license