Dash Core: CGovernanceManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CGovernanceManager Class Reference
#include <governance.h>
Classes
struct last_object_rec
class ScopedLockBool
Public Types
typedef std::map< uint256, CGovernanceObject > object_m_t
typedef object_m_t::iterator object_m_it
typedef object_m_t::const_iterator object_m_cit
typedef CacheMap< uint256, CGovernanceObject * > object_ref_cm_t
typedef std::map< uint256, CGovernanceVote > vote_m_t
typedef vote_m_t::iterator vote_m_it
typedef vote_m_t::const_iterator vote_m_cit
typedef CacheMap< uint256, CGovernanceVote > vote_cm_t
typedef CacheMultiMap< uint256, vote_time_pair_t > vote_cmm_t
typedef object_m_t::size_type size_type
typedef std::map< COutPoint, last_object_rec > txout_m_t
typedef txout_m_t::iterator txout_m_it
typedef txout_m_t::const_iterator txout_m_cit
typedef std::map< COutPoint, int > txout_int_m_t
typedef std::set< uint256 > hash_s_t
typedef hash_s_t::iterator hash_s_it
typedef hash_s_t::const_iterator hash_s_cit
typedef std::map< uint256, object_info_pair_t > object_info_m_t
typedef object_info_m_t::iterator object_info_m_it
typedef object_info_m_t::const_iterator object_info_m_cit
typedef std::map< uint256, int64_t > hash_time_m_t
typedef hash_time_m_t::iterator hash_time_m_it
typedef hash_time_m_t::const_iterator hash_time_m_cit
Public Member Functions
CGovernanceManager ()
virtual ~CGovernanceManager ()
bool ConfirmInventoryRequest (const CInv &inv)
This is called by AlreadyHave in net_processing.cpp as part of the inventory retrieval process.
void SyncSingleObjAndItsVotes (CNode *pnode, const uint256 &nProp, const CBloomFilter &filter, CConnman &connman)
void SyncAll (CNode *pnode, CConnman &connman) const
void ProcessMessage (CNode *pfrom, const std::string &strCommand, CDataStream &vRecv, CConnman &connman)
void DoMaintenance (CConnman &connman)
CGovernanceObject * FindGovernanceObject (const uint256 &nHash)
std::vector< CGovernanceVote > GetMatchingVotes (const uint256 &nParentHash) const
std::vector< CGovernanceVote > GetCurrentVotes (const uint256 &nParentHash, const COutPoint &mnCollateralOutpointFilter) const
std::vector< const CGovernanceObject * > GetAllNewerThan (int64_t nMoreThanTime) const
void AddGovernanceObject (CGovernanceObject &govobj, CConnman &connman, CNode *pfrom=nullptr)
void UpdateCachesAndClean ()
void CheckAndRemove ()
void Clear ()
std::string ToString () const
UniValue ToJson () const
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
void UpdatedBlockTip (const CBlockIndex *pindex, CConnman &connman)
int64_t GetLastDiffTime () const
void UpdateLastDiffTime (int64_t nTimeIn)
int GetCachedBlockHeight () const
bool HaveObjectForHash (const uint256 &nHash) const
bool HaveVoteForHash (const uint256 &nHash) const
int GetVoteCount () const
bool SerializeObjectForHash (const uint256 &nHash, CDataStream &ss) const
bool SerializeVoteForHash (const uint256 &nHash, CDataStream &ss) const
void AddPostponedObject (const CGovernanceObject &govobj)
void AddSeenGovernanceObject (const uint256 &nHash, int status)
void AddSeenVote (const uint256 &nHash, int status)
void MasternodeRateUpdate (const CGovernanceObject &govobj)
bool MasternodeRateCheck (const CGovernanceObject &govobj, bool fUpdateFailStatus=false)
bool MasternodeRateCheck (const CGovernanceObject &govobj, bool fUpdateFailStatus, bool fForce, bool &fRateCheckBypassed)
bool ProcessVoteAndRelay (const CGovernanceVote &vote, CGovernanceException &exception, CConnman &connman)
void CheckMasternodeOrphanVotes (CConnman &connman)
void CheckMasternodeOrphanObjects (CConnman &connman)
void CheckPostponedObjects (CConnman &connman)
bool AreRateChecksEnabled () const
void InitOnLoad ()
int RequestGovernanceObjectVotes (CNode *pnode, CConnman &connman)
int RequestGovernanceObjectVotes (const std::vector< CNode *> &vNodesCopy, CConnman &connman)
Public Attributes
CCriticalSection cs
ADD_SERIALIZE_METHODS
Private Member Functions
void RequestGovernanceObject (CNode *pfrom, const uint256 &nHash, CConnman &connman, bool fUseFilter=false)
void AddInvalidVote (const CGovernanceVote &vote)
void AddOrphanVote (const CGovernanceVote &vote)
bool ProcessVote (CNode *pfrom, const CGovernanceVote &vote, CGovernanceException &exception, CConnman &connman)
bool AcceptObjectMessage (const uint256 &nHash)
Called to indicate a requested object has been received.
bool AcceptVoteMessage (const uint256 &nHash)
Called to indicate a requested vote has been received.
void CheckOrphanVotes (CGovernanceObject &govobj, CGovernanceException &exception, CConnman &connman)
void RebuildIndexes ()
void AddCachedTriggers ()
void RequestOrphanObjects (CConnman &connman)
void CleanOrphanObjects ()
void RemoveInvalidProposalVotes ()
unsigned int GetMinVoteTime ()
void ClearPreDIP3Votes ()
Static Private Member Functions
static bool AcceptMessage (const uint256 &nHash, hash_s_t &setHash)
Private Attributes
int64_t nTimeLastDiff
int nCachedBlockHeight
object_m_t mapObjects
hash_time_m_t mapErasedGovernanceObjects
object_info_m_t mapMasternodeOrphanObjects
txout_int_m_t mapMasternodeOrphanCounter
object_m_t mapPostponedObjects
hash_s_t setAdditionalRelayObjects
object_ref_cm_t cmapVoteToObject
vote_cm_t cmapInvalidVotes
vote_cmm_t cmmapOrphanVotes
txout_m_t mapLastMasternodeObject
hash_s_t setRequestedObjects
hash_s_t setRequestedVotes
bool fRateChecksEnabled
CDeterministicMNList lastMNListForVotingKeys
Static Private Attributes
static const int MAX_CACHE_SIZE = 1000000
static const std::string SERIALIZATION_VERSION_STRING = "CGovernanceManager-Version-14"
static const int MAX_TIME_FUTURE_DEVIATION = 60 * 60
static const int RELIABLE_PROPAGATION_TIME = 60
Friends
class CGovernanceObject
Detailed Description
Definition at line 153 of file governance.h.
Member Typedef Documentation
hash_s_cit
typedef hash_s_t::const_iterator CGovernanceManager::hash_s_cit
Definition at line 211 of file governance.h.
hash_s_it
typedef hash_s_t::iterator CGovernanceManager::hash_s_it
Definition at line 209 of file governance.h.
hash_s_t
typedef std::set<uint256> CGovernanceManager::hash_s_t
Definition at line 207 of file governance.h.
hash_time_m_cit
typedef hash_time_m_t::const_iterator CGovernanceManager::hash_time_m_cit
Definition at line 223 of file governance.h.
hash_time_m_it
typedef hash_time_m_t::iterator CGovernanceManager::hash_time_m_it
Definition at line 221 of file governance.h.
hash_time_m_t
typedef std::map<uint256, int64_t> CGovernanceManager::hash_time_m_t
Definition at line 219 of file governance.h.
object_info_m_cit
typedef object_info_m_t::const_iterator CGovernanceManager::object_info_m_cit
Definition at line 217 of file governance.h.
object_info_m_it
typedef object_info_m_t::iterator CGovernanceManager::object_info_m_it
Definition at line 215 of file governance.h.
object_info_m_t
typedef std::map<uint256, object_info_pair_t> CGovernanceManager::object_info_m_t
Definition at line 213 of file governance.h.
object_m_cit
typedef object_m_t::const_iterator CGovernanceManager::object_m_cit
Definition at line 183 of file governance.h.
object_m_it
typedef object_m_t::iterator CGovernanceManager::object_m_it
Definition at line 181 of file governance.h.
object_m_t
typedef std::map<uint256, CGovernanceObject> CGovernanceManager::object_m_t
Definition at line 179 of file governance.h.
object_ref_cm_t
typedef CacheMap<uint256, CGovernanceObject*> CGovernanceManager::object_ref_cm_t
Definition at line 185 of file governance.h.
size_type
typedef object_m_t::size_type CGovernanceManager::size_type
Definition at line 197 of file governance.h.
txout_int_m_t
typedef std::map<COutPoint, int> CGovernanceManager::txout_int_m_t
Definition at line 205 of file governance.h.
txout_m_cit
typedef txout_m_t::const_iterator CGovernanceManager::txout_m_cit
Definition at line 203 of file governance.h.
txout_m_it
typedef txout_m_t::iterator CGovernanceManager::txout_m_it
Definition at line 201 of file governance.h.
txout_m_t
typedef std::map<COutPoint, last_object_rec> CGovernanceManager::txout_m_t
Definition at line 199 of file governance.h.
vote_cm_t
typedef CacheMap<uint256, CGovernanceVote> CGovernanceManager::vote_cm_t
Definition at line 193 of file governance.h.
vote_cmm_t
typedef CacheMultiMap<uint256, vote_time_pair_t> CGovernanceManager::vote_cmm_t
Definition at line 195 of file governance.h.
vote_m_cit
typedef vote_m_t::const_iterator CGovernanceManager::vote_m_cit
Definition at line 191 of file governance.h.
vote_m_it
typedef vote_m_t::iterator CGovernanceManager::vote_m_it
Definition at line 189 of file governance.h.
vote_m_t
typedef std::map<uint256, CGovernanceVote> CGovernanceManager::vote_m_t
Definition at line 187 of file governance.h.
Constructor & Destructor Documentation
CGovernanceManager()
CGovernanceManager::CGovernanceManager ()
Definition at line 30 of file governance.cpp.
~CGovernanceManager()
virtual CGovernanceManager::~CGovernanceManager () inline virtual
Definition at line 295 of file governance.h.
Member Function Documentation
AcceptMessage()
bool CGovernanceManager::AcceptMessage (const uint256 & nHash, hash_s_t & setHash) static private
Definition at line 1174 of file governance.cpp.
Referenced by AcceptObjectMessage(), and AcceptVoteMessage().
AcceptObjectMessage()
bool CGovernanceManager::AcceptObjectMessage (const uint256 & nHash) private
Called to indicate a requested object has been received.
Definition at line 1162 of file governance.cpp.
References AcceptMessage(), cs, LOCK, and setRequestedObjects.
Referenced by ProcessMessage().
AcceptVoteMessage()
bool CGovernanceManager::AcceptVoteMessage (const uint256 & nHash) private
Called to indicate a requested vote has been received.
Definition at line 1168 of file governance.cpp.
References AcceptMessage(), cs, LOCK, and setRequestedVotes.
Referenced by ProcessMessage().
AddCachedTriggers()
void CGovernanceManager::AddCachedTriggers () private
Definition at line 1200 of file governance.cpp.
References CGovernanceTriggerManager::AddNewTrigger(), cs, CGovernanceObject::fCachedDelete, GetAdjustedTime(), CGovernanceObject::GetHash(), GOVERNANCE_OBJECT_TRIGGER, LOCK, mapObjects, CGovernanceObject::nDeletionTime, CGovernanceObject::nObjectType, and triggerman.
Referenced by InitOnLoad().
AddGovernanceObject()
void CGovernanceManager::AddGovernanceObject (CGovernanceObject & govobj, CConnman & connman, CNode * pfrom = nullptr)
Definition at line 302 of file governance.cpp.
References CGovernanceTriggerManager::AddNewTrigger(), CMasternodeSync::BumpAssetLastTime(), CheckOrphanVotes(), cs, cs_main, DBG, CGovernanceObject::fCachedDelete, CNode::GetAddrName(), GetAdjustedTime(), CGovernanceObject::GetDataAsPlainString(), CGovernanceObject::GetHash(), GetMainSignals(), CGovernanceObject::GetObjectType(), GOVERNANCE_OBJECT_TRIGGER, CGovernanceObject::IsValidLocally(), LOCK2, LogPrint, LogPrintf, mapObjects, MasternodeRateUpdate(), masternodeSync, nCachedBlockHeight, CGovernanceObject::nObjectType, CMainSignals::NotifyGovernanceObject, CGovernanceObject::Relay(), base_blob< BITS >::ToString(), triggerman, and CGovernanceObject::UpdateSentinelVariables().
Referenced by CheckMasternodeOrphanObjects(), CheckPostponedObjects(), gobject_submit(), and ProcessMessage().
AddInvalidVote()
void CGovernanceManager::AddInvalidVote (const CGovernanceVote & vote) inline private
Definition at line 428 of file governance.h.
References cmapInvalidVotes, CGovernanceVote::GetHash(), and CacheMap< K, V, Size >::Insert().
Referenced by CGovernanceObject::ProcessVote().
AddOrphanVote()
void CGovernanceManager::AddOrphanVote (const CGovernanceVote & vote) inline private
Definition at line 433 of file governance.h.
References cmmapOrphanVotes, GetAdjustedTime(), CGovernanceVote::GetHash(), GOVERNANCE_ORPHAN_EXPIRATION_TIME, and CacheMultiMap< K, V, Size >::Insert().
AddPostponedObject()
void CGovernanceManager::AddPostponedObject (const CGovernanceObject & govobj) inline
Definition at line 383 of file governance.h.
References cs, CGovernanceObject::GetHash(), LOCK, and mapPostponedObjects.
Referenced by gobject_submit(), and ProcessMessage().
AddSeenGovernanceObject()
void CGovernanceManager::AddSeenGovernanceObject (const uint256 & nHash, int status)
AddSeenVote()
void CGovernanceManager::AddSeenVote (const uint256 & nHash, int status)
AreRateChecksEnabled()
bool CGovernanceManager::AreRateChecksEnabled () const inline
Definition at line 414 of file governance.h.
References cs, fRateChecksEnabled, and LOCK.
Referenced by CGovernanceObject::ProcessVote().
CheckAndRemove()
void CGovernanceManager::CheckAndRemove () inline
Definition at line 322 of file governance.h.
References UpdateCachesAndClean().
CheckMasternodeOrphanObjects()
void CGovernanceManager::CheckMasternodeOrphanObjects (CConnman & connman)
Definition at line 911 of file governance.cpp.
References AddGovernanceObject(), cs, cs_main, fRateChecksEnabled, GetAdjustedTime(), CGovernanceObject::GetMasternodeOutpoint(), CGovernanceObject::IsValidLocally(), LOCK2, mapMasternodeOrphanCounter, mapMasternodeOrphanObjects, and Misbehaving().
Referenced by CMasternodeMan::NotifyMasternodeUpdates().
CheckMasternodeOrphanVotes()
void CGovernanceManager::CheckMasternodeOrphanVotes (CConnman & connman)
Definition at line 900 of file governance.cpp.
References cs, cs_main, fRateChecksEnabled, LOCK2, and mapObjects.
Referenced by CMasternodeMan::NotifyMasternodeUpdates().
CheckOrphanVotes()
void CGovernanceManager::CheckOrphanVotes (CGovernanceObject & govobj, CGovernanceException & exception, CConnman & connman) private
Definition at line 277 of file governance.cpp.
References cmmapOrphanVotes, cs, CacheMultiMap< K, V, Size >::Erase(), fRateChecksEnabled, GetAdjustedTime(), CacheMultiMap< K, V, Size >::GetAll(), CGovernanceObject::GetHash(), CGovernanceObject::ProcessVote(), and CGovernanceVote::Relay().
Referenced by AddGovernanceObject().
CheckPostponedObjects()
void CGovernanceManager::CheckPostponedObjects (CConnman & connman)
Definition at line 946 of file governance.cpp.
References AddGovernanceObject(), cs, cs_main, GetAdjustedTime(), CChainParams::GetConsensus(), CGovernanceObject::GetCreationTime(), CGovernanceObject::GetHash(), CGovernanceObject::GetObjectType(), GOVERNANCE_OBJECT_TRIGGER, CGovernanceObject::IsCollateralValid(), CMasternodeSync::IsSynced(), CGovernanceObject::IsValidLocally(), LOCK2, LogPrintf, mapObjects, mapPostponedObjects, masternodeSync, MAX_TIME_FUTURE_DEVIATION, Consensus::Params::nPowTargetSpacing, Consensus::Params::nSuperblockCycle, Params(), CGovernanceObject::Relay(), RELIABLE_PROPAGATION_TIME, setAdditionalRelayObjects, and base_blob< BITS >::ToString().
Referenced by UpdatedBlockTip().
CleanOrphanObjects()
void CGovernanceManager::CleanOrphanObjects () private
Definition at line 1344 of file governance.cpp.
References cmmapOrphanVotes, cs, CacheMultiMap< K, V, Size >::Erase(), GetAdjustedTime(), CacheMultiMap< K, V, Size >::GetItemList(), and LOCK.
Referenced by DoMaintenance().
Clear()
void CGovernanceManager::Clear () inline
Definition at line 324 of file governance.h.
References CacheMultiMap< K, V, Size >::Clear(), CacheMap< K, V, Size >::Clear(), cmapInvalidVotes, cmapVoteToObject, cmmapOrphanVotes, cs, LOCK, LogPrint, mapErasedGovernanceObjects, mapLastMasternodeObject, and mapObjects.
Referenced by SerializationOp().
ClearPreDIP3Votes()
void CGovernanceManager::ClearPreDIP3Votes () private
Definition at line 1411 of file governance.cpp.
References cmapInvalidVotes, cmapVoteToObject, cmmapOrphanVotes, cs, CacheMap< K, V, Size >::Erase(), CacheMultiMap< K, V, Size >::Erase(), GetMinVoteTime(), LOCK, mapObjects, and setRequestedVotes.
Referenced by DoMaintenance(), and UpdatedBlockTip().
ConfirmInventoryRequest()
bool CGovernanceManager::ConfirmInventoryRequest (const CInv & inv)
This is called by AlreadyHave in net_processing.cpp as part of the inventory retrieval process.
Returns true if we want to retrieve the object, otherwise false. (Note logic is inverted in AlreadyHave).
Definition at line 598 of file governance.cpp.
References cmapVoteToObject, cs, CInv::hash, CacheMap< K, V, Size >::HasKey(), CMasternodeSync::IsWinnersListSynced(), LOCK, LogPrint, mapObjects, mapPostponedObjects, masternodeSync, MSG_GOVERNANCE_OBJECT, MSG_GOVERNANCE_OBJECT_VOTE, setRequestedObjects, setRequestedVotes, CInv::ToString(), and CInv::type.
Referenced by AlreadyHave().
DoMaintenance()
void CGovernanceManager::DoMaintenance (CConnman & connman)
Definition at line 578 of file governance.cpp.
References CleanOrphanObjects(), ClearPreDIP3Votes(), deterministicMNManager, fLiteMode, CDeterministicMNManager::IsDeterministicMNsSporkActive(), CMasternodeSync::IsSynced(), masternodeSync, RemoveInvalidProposalVotes(), RequestOrphanObjects(), ShutdownRequested(), and UpdateCachesAndClean().
Referenced by AppInitMain().
FindGovernanceObject()
CGovernanceObject * CGovernanceManager::FindGovernanceObject (const uint256 & nHash)
Definition at line 486 of file governance.cpp.
References cs, LOCK, and mapObjects.
Referenced by CGovernanceTriggerManager::CleanAndRemove(), CGovernanceTriggerManager::GetActiveTriggers(), CSuperblock::GetGovernanceObject(), gobject_get(), gobject_getcurrentvotes(), gobject_getvotes(), gobject_vote_conf(), RequestGovernanceObject(), voteraw(), and VoteWithMasternodeList().
GetAllNewerThan()
std::vector< const CGovernanceObject * > CGovernanceManager::GetAllNewerThan (int64_t nMoreThanTime) const
Definition at line 547 of file governance.cpp.
References cs, LOCK, and mapObjects.
Referenced by ListObjects().
GetCachedBlockHeight()
int CGovernanceManager::GetCachedBlockHeight () const inline
Definition at line 370 of file governance.h.
References nCachedBlockHeight.
Referenced by CSuperblock::IsExpired().
GetCurrentVotes()
std::vector< CGovernanceVote > CGovernanceManager::GetCurrentVotes (const uint256 & nParentHash, const COutPoint & mnCollateralOutpointFilter) const
Definition at line 508 of file governance.cpp.
References cs, CMasternodeMan::Get(), CGovernanceObject::GetCurrentMNVotes(), CMasternodeMan::GetFullMasternodeMap(), COutPoint::IsNull(), LOCK, vote_rec_t::mapInstances, mapObjects, mnodeman, and CGovernanceVote::SetTime().
Referenced by gobject_getcurrentvotes().
GetLastDiffTime()
int64_t CGovernanceManager::GetLastDiffTime () const inline
Definition at line 367 of file governance.h.
References nTimeLastDiff.
Referenced by gobject_diff().
GetMatchingVotes()
std::vector< CGovernanceVote > CGovernanceManager::GetMatchingVotes (const uint256 & nParentHash) const
Definition at line 495 of file governance.cpp.
References cs, LOCK, and mapObjects.
Referenced by gobject_getvotes().
GetMinVoteTime()
unsigned int CGovernanceManager::GetMinVoteTime () private
Definition at line 1401 of file governance.cpp.
References chainActive, cs_main, deterministicMNManager, CSporkManager::GetSporkValue(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LOCK, SPORK_15_DETERMINISTIC_MNS_ENABLED, and sporkManager.
Referenced by ClearPreDIP3Votes(), and ProcessMessage().
GetVoteCount()
int CGovernanceManager::GetVoteCount () const
Definition at line 74 of file governance.cpp.
References cmapVoteToObject, cs, CacheMap< K, V, Size >::GetSize(), and LOCK.
Referenced by CMasternodeSync::ProcessTick().
HaveObjectForHash()
bool CGovernanceManager::HaveObjectForHash (const uint256 & nHash) const
Definition at line 47 of file governance.cpp.
References cs, LOCK, mapObjects, and mapPostponedObjects.
Referenced by ProcessGetData().
HaveVoteForHash()
bool CGovernanceManager::HaveVoteForHash (const uint256 & nHash) const
Definition at line 66 of file governance.cpp.
References cmapVoteToObject, cs, CacheMap< K, V, Size >::Get(), CGovernanceObject::GetVoteFile(), CGovernanceObjectVoteFile::HasVote(), and LOCK.
Referenced by ProcessGetData().
InitOnLoad()
void CGovernanceManager::InitOnLoad ()
Definition at line 1220 of file governance.cpp.
References AddCachedTriggers(), cs, GetTimeMillis(), LOCK, LogPrintf, RebuildIndexes(), and ToString().
Referenced by AppInitMain().
MasternodeRateCheck() [1/2]
bool CGovernanceManager::MasternodeRateCheck (const CGovernanceObject & govobj, bool fUpdateFailStatus = false)
Definition at line 776 of file governance.cpp.
Referenced by gobject_submit(), and ProcessMessage().
MasternodeRateCheck() [2/2]
bool CGovernanceManager::MasternodeRateCheck (const CGovernanceObject & govobj, bool fUpdateFailStatus, bool fForce, bool & fRateCheckBypassed)
Definition at line 782 of file governance.cpp.
References CRateCheckBuffer::AddTimestamp(), cs, fRateChecksEnabled, GetAdjustedTime(), CChainParams::GetConsensus(), CGovernanceObject::GetCreationTime(), CGovernanceObject::GetHash(), CGovernanceObject::GetMasternodeOutpoint(), CGovernanceObject::GetObjectType(), CRateCheckBuffer::GetRate(), GOVERNANCE_OBJECT_TRIGGER, CMasternodeSync::IsSynced(), LOCK, LogPrintf, mapLastMasternodeObject, masternodeSync, MAX_TIME_FUTURE_DEVIATION, Consensus::Params::nPowTargetSpacing, Consensus::Params::nSuperblockCycle, Params(), base_blob< BITS >::ToString(), and COutPoint::ToStringShort().
MasternodeRateUpdate()
void CGovernanceManager::MasternodeRateUpdate (const CGovernanceObject & govobj)
Definition at line 754 of file governance.cpp.
References CGovernanceObject::GetCreationTime(), CGovernanceObject::GetHash(), CGovernanceObject::GetMasternodeOutpoint(), CGovernanceObject::GetObjectType(), GetTime(), GOVERNANCE_OBJECT_TRIGGER, mapLastMasternodeObject, MAX_TIME_FUTURE_DEVIATION, RELIABLE_PROPAGATION_TIME, and setAdditionalRelayObjects.
Referenced by AddGovernanceObject().
ProcessMessage()
void CGovernanceManager::ProcessMessage (CNode * pfrom, const std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 88 of file governance.cpp.
References AcceptObjectMessage(), AcceptVoteMessage(), AddGovernanceObject(), AddPostponedObject(), CNode::addr, CNode::AskFor(), CMasternodeSync::BumpAssetLastTime(), CBloomFilter::clear(), count, cs, cs_main, fLiteMode, GetAdjustedTime(), CNode::GetId(), GetMainSignals(), GetMinVoteTime(), CGovernanceException::GetNodePenalty(), CNode::GetSendVersion(), GOVERNANCE_FILTER_PROTO_VERSION, GOVERNANCE_ORPHAN_EXPIRATION_TIME, CNode::id, CMasternodeSync::IsBlockchainSynced(), CMasternodeSync::IsMasternodeListSynced(), CMasternodeSync::IsSynced(), LOCK, LOCK2, LogPrint, LogPrintf, mapErasedGovernanceObjects, mapMasternodeOrphanCounter, mapMasternodeOrphanObjects, mapObjects, mapPostponedObjects, MasternodeRateCheck(), masternodeSync, MIN_GOVERNANCE_PEER_PROTO_VERSION, Misbehaving(), NetMsgType::MNGOVERNANCEOBJECT, NetMsgType::MNGOVERNANCEOBJECTVOTE, NetMsgType::MNGOVERNANCESYNC, MSG_GOVERNANCE_OBJECT, nCachedBlockHeight, CMainSignals::NotifyGovernanceVote, CNode::nVersion, ProcessVote(), CConnman::PushMessage(), NetMsgType::REJECT, REJECT_OBSOLETE, CConnman::RemoveAskFor(), strprintf, SyncAll(), SyncSingleObjAndItsVotes(), base_blob< BITS >::ToString(), CService::ToString(), CBloomFilter::UpdateEmptyFull(), and CGovernanceException::what().
Referenced by ProcessMessage().
ProcessVote()
bool CGovernanceManager::ProcessVote (CNode * pfrom, const CGovernanceVote & vote, CGovernanceException & exception, CConnman & connman) private
Definition at line 846 of file governance.cpp.
References cmapInvalidVotes, cmapVoteToObject, cmmapOrphanVotes, cs, ENTER_CRITICAL_SECTION, GetAdjustedTime(), CGovernanceVote::GetHash(), CGovernanceVote::GetMasternodeOutpoint(), CGovernanceVote::GetParentHash(), GOVERNANCE_EXCEPTION_PERMANENT_ERROR, GOVERNANCE_EXCEPTION_WARNING, GOVERNANCE_ORPHAN_EXPIRATION_TIME, CacheMap< K, V, Size >::HasKey(), CacheMultiMap< K, V, Size >::Insert(), CacheMap< K, V, Size >::Insert(), CGovernanceObject::IsSetCachedDelete(), CGovernanceObject::IsSetExpired(), LEAVE_CRITICAL_SECTION, LogPrint, LogPrintf, mapObjects, CGovernanceObject::ProcessVote(), RequestGovernanceObject(), base_blob< BITS >::ToString(), and COutPoint::ToStringShort().
Referenced by ProcessMessage(), and ProcessVoteAndRelay().
ProcessVoteAndRelay()
bool CGovernanceManager::ProcessVoteAndRelay (const CGovernanceVote & vote, CGovernanceException & exception, CConnman & connman) inline
Definition at line 399 of file governance.h.
References ProcessVote(), and CGovernanceVote::Relay().
Referenced by gobject_vote_conf(), voteraw(), and VoteWithMasternodeList().
RebuildIndexes()
void CGovernanceManager::RebuildIndexes () private
Definition at line 1186 of file governance.cpp.
References CacheMap< K, V, Size >::Clear(), cmapVoteToObject, cs, CGovernanceObject::GetVoteFile(), CGovernanceObjectVoteFile::GetVotes(), CacheMap< K, V, Size >::Insert(), LOCK, and mapObjects.
Referenced by InitOnLoad().
RemoveInvalidProposalVotes()
void CGovernanceManager::RemoveInvalidProposalVotes () private
Definition at line 1362 of file governance.cpp.
References CDeterministicMNList::BuildDiff(), cmapInvalidVotes, cmapVoteToObject, cmmapOrphanVotes, cs, deterministicMNManager, CacheMap< K, V, Size >::Erase(), CacheMultiMap< K, V, Size >::Erase(), CDeterministicMNManager::GetListAtChainTip(), CDeterministicMNList::GetMN(), lastMNListForVotingKeys, LOCK, mapObjects, and setRequestedVotes.
Referenced by DoMaintenance(), and UpdatedBlockTip().
RequestGovernanceObject()
void CGovernanceManager::RequestGovernanceObject (CNode * pfrom, const uint256 & nHash, CConnman & connman, bool fUseFilter = false) private
Definition at line 1011 of file governance.cpp.
References BLOOM_UPDATE_ALL, CBloomFilter::clear(), cs, FindGovernanceObject(), CNode::GetId(), GetRandInt(), CNode::GetSendVersion(), CGovernanceObject::GetVoteFile(), CGovernanceObjectVoteFile::GetVotes(), GOVERNANCE_FILTER_FP_RATE, GOVERNANCE_FILTER_PROTO_VERSION, CNode::id, CBloomFilter::insert(), LOCK, LogPrint, NetMsgType::MNGOVERNANCESYNC, CNode::nVersion, Params(), CConnman::PushMessage(), and base_blob< BITS >::ToString().
Referenced by ProcessVote(), RequestGovernanceObjectVotes(), and RequestOrphanObjects().
RequestGovernanceObjectVotes() [1/2]
int CGovernanceManager::RequestGovernanceObjectVotes (CNode * pnode, CConnman & connman)
Definition at line 1048 of file governance.cpp.
References MIN_GOVERNANCE_PEER_PROTO_VERSION, and CNode::nVersion.
Referenced by CMasternodeSync::ProcessTick().
RequestGovernanceObjectVotes() [2/2]
int CGovernanceManager::RequestGovernanceObjectVotes (const std::vector< CNode *> & vNodesCopy, CConnman & connman)
Definition at line 1056 of file governance.cpp.
References base_blob< BITS >::begin(), count, cs, cs_main, fMasternodeMode, GetTime(), GOVERNANCE_OBJECT_TRIGGER, LOCK, LOCK2, LogPrint, CBaseChainParams::MAIN, mapObjects, MIN_GOVERNANCE_PEER_PROTO_VERSION, mnodeman, Params(), RequestGovernanceObject(), SETASKFOR_MAX_SZ, and CMasternodeMan::size().
RequestOrphanObjects()
void CGovernanceManager::RequestOrphanObjects (CConnman & connman) private
Definition at line 1315 of file governance.cpp.
References cmmapOrphanVotes, CConnman::CopyNodeVector(), cs, CConnman::FullyConnectedOnly, CacheMultiMap< K, V, Size >::GetKeys(), LOCK, LogPrint, mapObjects, CConnman::ReleaseNodeVector(), and RequestGovernanceObject().
Referenced by DoMaintenance().
SerializationOp()
template<typename Stream , typename Operation > void CGovernanceManager::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 343 of file governance.h.
References Clear(), cmapInvalidVotes, cmmapOrphanVotes, cs, lastMNListForVotingKeys, LOCK, mapErasedGovernanceObjects, mapLastMasternodeObject, mapObjects, READWRITE, and SERIALIZATION_VERSION_STRING.
SerializeObjectForHash()
bool CGovernanceManager::SerializeObjectForHash (const uint256 & nHash, CDataStream & ss) const
Definition at line 53 of file governance.cpp.
References cs, LOCK, mapObjects, and mapPostponedObjects.
Referenced by ProcessGetData().
SerializeVoteForHash()
bool CGovernanceManager::SerializeVoteForHash (const uint256 & nHash, CDataStream & ss) const
Definition at line 80 of file governance.cpp.
References cmapVoteToObject, cs, CacheMap< K, V, Size >::Get(), CGovernanceObject::GetVoteFile(), LOCK, and CGovernanceObjectVoteFile::SerializeVoteToStream().
Referenced by ProcessGetData().
SyncAll()
void CGovernanceManager::SyncAll (CNode * pnode, CConnman & connman) const
Definition at line 705 of file governance.cpp.
References CNetFulfilledRequestManager::AddFulfilledRequest(), CNode::addr, cs, cs_main, CNode::GetId(), CNode::GetSendVersion(), CNetFulfilledRequestManager::HasFulfilledRequest(), CNode::id, CGovernanceObject::IsSetCachedDelete(), CGovernanceObject::IsSetExpired(), CMasternodeSync::IsSynced(), LOCK, LOCK2, LogPrint, LogPrintf, mapObjects, MASTERNODE_SYNC_GOVOBJ, MASTERNODE_SYNC_GOVOBJ_VOTE, masternodeSync, Misbehaving(), NetMsgType::MNGOVERNANCESYNC, MSG_GOVERNANCE_OBJECT, netfulfilledman, CNode::PushInventory(), CConnman::PushMessage(), NetMsgType::SYNCSTATUSCOUNT, and base_blob< BITS >::ToString().
Referenced by ProcessMessage().
SyncSingleObjAndItsVotes()
void CGovernanceManager::SyncSingleObjAndItsVotes (CNode * pnode, const uint256 & nProp, const CBloomFilter & filter, CConnman & connman)
Definition at line 651 of file governance.cpp.
References CBloomFilter::contains(), cs, cs_main, CGovernanceObject::GetObjectType(), CNode::GetSendVersion(), CGovernanceObject::GetVoteFile(), GOVERNANCE_OBJECT_PROPOSAL, CNode::id, CGovernanceObject::IsSetCachedDelete(), CGovernanceObject::IsSetExpired(), CMasternodeSync::IsSynced(), LOCK2, LogPrint, LogPrintf, mapObjects, MASTERNODE_SYNC_GOVOBJ, MASTERNODE_SYNC_GOVOBJ_VOTE, masternodeSync, MSG_GOVERNANCE_OBJECT, MSG_GOVERNANCE_OBJECT_VOTE, CNode::PushInventory(), CConnman::PushMessage(), NetMsgType::SYNCSTATUSCOUNT, base_blob< BITS >::ToString(), and VOTE_SIGNAL_FUNDING.
Referenced by ProcessMessage().
ToJson()
UniValue CGovernanceManager::ToJson () const
Definition at line 1259 of file governance.cpp.
References cmapVoteToObject, cs, CacheMap< K, V, Size >::GetSize(), GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, LOCK, mapErasedGovernanceObjects, mapObjects, Pair(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by gobject_count().
ToString()
std::string CGovernanceManager::ToString () const
Definition at line 1231 of file governance.cpp.
References cmapVoteToObject, cs, CacheMap< K, V, Size >::GetSize(), GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, LOCK, mapErasedGovernanceObjects, mapObjects, and strprintf.
Referenced by gobject_count(), InitOnLoad(), and UpdateCachesAndClean().
UpdateCachesAndClean()
void CGovernanceManager::UpdateCachesAndClean ()
Definition at line 375 of file governance.cpp.
References CGovernanceTriggerManager::CleanAndRemove(), cmapVoteToObject, cs, cs_main, CacheMap< K, V, Size >::Erase(), CGovernanceObject::fCachedDelete, fRateChecksEnabled, GetAdjustedTime(), CMasternodeMan::GetAndClearDirtyGovernanceObjectHashes(), CChainParams::GetConsensus(), CGovernanceObject::GetCreationTime(), CGovernanceObject::GetDataAsHexString(), CGovernanceObject::GetDeletionTime(), CGovernanceObject::GetHash(), CacheMap< K, V, Size >::GetItemList(), CGovernanceObject::GetObjectType(), GOVERNANCE_DELETION_DELAY, GOVERNANCE_OBJECT_PROPOSAL, CGovernanceObject::IsSetCachedDelete(), CGovernanceObject::IsSetDirtyCache(), CGovernanceObject::IsSetExpired(), LOCK2, LogPrint, LogPrintf, mapErasedGovernanceObjects, mapObjects, mnodeman, CGovernanceObject::nDeletionTime, Consensus::Params::nPowTargetSpacing, Consensus::Params::nSuperblockCycle, Params(), CMasternodeMan::RemoveGovernanceObject(), base_blob< BITS >::ToString(), ToString(), triggerman, CGovernanceObject::UpdateLocalValidity(), and CGovernanceObject::UpdateSentinelVariables().
Referenced by CheckAndRemove(), DoMaintenance(), and CMasternodeMan::NotifyMasternodeUpdates().
UpdatedBlockTip()
void CGovernanceManager::UpdatedBlockTip (const CBlockIndex * pindex, CConnman & connman)
Definition at line 1291 of file governance.cpp.
References CheckPostponedObjects(), ClearPreDIP3Votes(), deterministicMNManager, CSuperblockManager::ExecuteBestSuperblock(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LogPrint, nCachedBlockHeight, CBlockIndex::nHeight, and RemoveInvalidProposalVotes().
Referenced by CDSNotificationInterface::UpdatedBlockTip().
UpdateLastDiffTime()
void CGovernanceManager::UpdateLastDiffTime (int64_t nTimeIn) inline
Definition at line 368 of file governance.h.
References nTimeLastDiff.
Referenced by ListObjects().
Friends And Related Function Documentation
CGovernanceObject
friend class CGovernanceObject friend
Definition at line 155 of file governance.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CGovernanceManager::ADD_SERIALIZE_METHODS
Definition at line 340 of file governance.h.
cmapInvalidVotes
vote_cm_t CGovernanceManager::cmapInvalidVotes private
Definition at line 254 of file governance.h.
Referenced by AddInvalidVote(), Clear(), ClearPreDIP3Votes(), ProcessVote(), RemoveInvalidProposalVotes(), and SerializationOp().
cmapVoteToObject
object_ref_cm_t CGovernanceManager::cmapVoteToObject private
Definition at line 252 of file governance.h.
Referenced by Clear(), ClearPreDIP3Votes(), ConfirmInventoryRequest(), GetVoteCount(), HaveVoteForHash(), ProcessVote(), RebuildIndexes(), RemoveInvalidProposalVotes(), SerializeVoteForHash(), ToJson(), ToString(), and UpdateCachesAndClean().
cmmapOrphanVotes
vote_cmm_t CGovernanceManager::cmmapOrphanVotes private
Definition at line 256 of file governance.h.
Referenced by AddOrphanVote(), CheckOrphanVotes(), CleanOrphanObjects(), Clear(), ClearPreDIP3Votes(), ProcessVote(), RemoveInvalidProposalVotes(), RequestOrphanObjects(), and SerializationOp().
cs
CCriticalSection CGovernanceManager::cs mutable
Definition at line 291 of file governance.h.
Referenced by AcceptObjectMessage(), AcceptVoteMessage(), AddCachedTriggers(), AddGovernanceObject(), CGovernanceTriggerManager::AddNewTrigger(), AddPostponedObject(), AreRateChecksEnabled(), CheckMasternodeOrphanObjects(), CheckMasternodeOrphanVotes(), CheckOrphanVotes(), CheckPostponedObjects(), CGovernanceTriggerManager::CleanAndRemove(), CleanOrphanObjects(), Clear(), ClearPreDIP3Votes(), ConfirmInventoryRequest(), CSuperblockManager::ExecuteBestSuperblock(), FindGovernanceObject(), CGovernanceTriggerManager::GetActiveTriggers(), GetAllNewerThan(), CSuperblockManager::GetBestSuperblock(), GetCurrentVotes(), CSuperblock::GetGovernanceObject(), GetMatchingVotes(), CSuperblockManager::GetRequiredPaymentsString(), CSuperblockManager::GetSuperblockPayments(), GetVoteCount(), gobject_get(), gobject_getcurrentvotes(), gobject_getvotes(), gobject_vote_conf(), HaveObjectForHash(), HaveVoteForHash(), InitOnLoad(), CSuperblockManager::IsSuperblockTriggered(), CSuperblockManager::IsValid(), ListObjects(), MasternodeRateCheck(), ProcessMessage(), ProcessVote(), RebuildIndexes(), RemoveInvalidProposalVotes(), RequestGovernanceObject(), RequestGovernanceObjectVotes(), RequestOrphanObjects(), SerializationOp(), SerializeObjectForHash(), SerializeVoteForHash(), SyncAll(), SyncSingleObjAndItsVotes(), ToJson(), ToString(), UpdateCachesAndClean(), voteraw(), and VoteWithMasternodeList().
fRateChecksEnabled
bool CGovernanceManager::fRateChecksEnabled private
Definition at line 264 of file governance.h.
Referenced by AreRateChecksEnabled(), CheckMasternodeOrphanObjects(), CheckMasternodeOrphanVotes(), CheckOrphanVotes(), MasternodeRateCheck(), and UpdateCachesAndClean().
lastMNListForVotingKeys
CDeterministicMNList CGovernanceManager::lastMNListForVotingKeys private
Definition at line 267 of file governance.h.
Referenced by RemoveInvalidProposalVotes(), and SerializationOp().
mapErasedGovernanceObjects
hash_time_m_t CGovernanceManager::mapErasedGovernanceObjects private
Definition at line 244 of file governance.h.
Referenced by Clear(), ProcessMessage(), SerializationOp(), ToJson(), ToString(), and UpdateCachesAndClean().
mapLastMasternodeObject
txout_m_t CGovernanceManager::mapLastMasternodeObject private
Definition at line 258 of file governance.h.
Referenced by Clear(), MasternodeRateCheck(), MasternodeRateUpdate(), and SerializationOp().
mapMasternodeOrphanCounter
txout_int_m_t CGovernanceManager::mapMasternodeOrphanCounter private
Definition at line 247 of file governance.h.
Referenced by CheckMasternodeOrphanObjects(), and ProcessMessage().
mapMasternodeOrphanObjects
object_info_m_t CGovernanceManager::mapMasternodeOrphanObjects private
Definition at line 246 of file governance.h.
Referenced by CheckMasternodeOrphanObjects(), and ProcessMessage().
mapObjects
object_m_t CGovernanceManager::mapObjects private
Definition at line 239 of file governance.h.
Referenced by AddCachedTriggers(), AddGovernanceObject(), CheckMasternodeOrphanVotes(), CheckPostponedObjects(), Clear(), ClearPreDIP3Votes(), ConfirmInventoryRequest(), FindGovernanceObject(), GetAllNewerThan(), GetCurrentVotes(), GetMatchingVotes(), HaveObjectForHash(), ProcessMessage(), ProcessVote(), RebuildIndexes(), RemoveInvalidProposalVotes(), RequestGovernanceObjectVotes(), RequestOrphanObjects(), SerializationOp(), SerializeObjectForHash(), SyncAll(), SyncSingleObjAndItsVotes(), ToJson(), ToString(), and UpdateCachesAndClean().
mapPostponedObjects
object_m_t CGovernanceManager::mapPostponedObjects private
Definition at line 249 of file governance.h.
Referenced by AddPostponedObject(), CheckPostponedObjects(), ConfirmInventoryRequest(), HaveObjectForHash(), ProcessMessage(), and SerializeObjectForHash().
MAX_CACHE_SIZE
const int CGovernanceManager::MAX_CACHE_SIZE = 1000000 static private
Definition at line 226 of file governance.h.
MAX_TIME_FUTURE_DEVIATION
const int CGovernanceManager::MAX_TIME_FUTURE_DEVIATION = 60 * 60 static private
Definition at line 230 of file governance.h.
Referenced by CheckPostponedObjects(), MasternodeRateCheck(), and MasternodeRateUpdate().
nCachedBlockHeight
int CGovernanceManager::nCachedBlockHeight private
Definition at line 236 of file governance.h.
Referenced by AddGovernanceObject(), GetCachedBlockHeight(), ProcessMessage(), and UpdatedBlockTip().
nTimeLastDiff
int64_t CGovernanceManager::nTimeLastDiff private
Definition at line 233 of file governance.h.
Referenced by GetLastDiffTime(), and UpdateLastDiffTime().
RELIABLE_PROPAGATION_TIME
const int CGovernanceManager::RELIABLE_PROPAGATION_TIME = 60 static private
Definition at line 231 of file governance.h.
Referenced by CheckPostponedObjects(), and MasternodeRateUpdate().
SERIALIZATION_VERSION_STRING
const std::string CGovernanceManager::SERIALIZATION_VERSION_STRING = "CGovernanceManager-Version-14" static private
Definition at line 228 of file governance.h.
Referenced by SerializationOp().
setAdditionalRelayObjects
hash_s_t CGovernanceManager::setAdditionalRelayObjects private
Definition at line 250 of file governance.h.
Referenced by CheckPostponedObjects(), and MasternodeRateUpdate().
setRequestedObjects
hash_s_t CGovernanceManager::setRequestedObjects private
Definition at line 260 of file governance.h.
Referenced by AcceptObjectMessage(), and ConfirmInventoryRequest().
setRequestedVotes
hash_s_t CGovernanceManager::setRequestedVotes private
Definition at line 262 of file governance.h.
Referenced by AcceptVoteMessage(), ClearPreDIP3Votes(), ConfirmInventoryRequest(), and RemoveInvalidProposalVotes().
The documentation for this class was generated from the following files:
src/governance.h
src/governance.cpp
Released under the MIT license