Dash Core: CMasternode Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
CMasternode Class Reference
#include <masternode.h>
Public Types
enum state {
MASTERNODE_PRE_ENABLED, MASTERNODE_ENABLED, MASTERNODE_EXPIRED, MASTERNODE_OUTPOINT_SPENT,
MASTERNODE_UPDATE_REQUIRED, MASTERNODE_SENTINEL_PING_EXPIRED, MASTERNODE_NEW_START_REQUIRED, MASTERNODE_POSE_BAN
}
enum CollateralStatus { COLLATERAL_OK, COLLATERAL_UTXO_NOT_FOUND, COLLATERAL_INVALID_AMOUNT, COLLATERAL_INVALID_PUBKEY }
Public Member Functions
CMasternode ()
CMasternode (const CMasternode &other)
CMasternode (const CMasternodeBroadcast &mnb)
CMasternode (CService addrNew, COutPoint outpointNew, CPubKey pubKeyCollateralAddressNew, CPubKey pubKeyMasternodeNew, int nProtocolVersionIn)
CMasternode (const uint256 &proTxHash, const CDeterministicMNCPtr &dmn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
arith_uint256 CalculateScore (const uint256 &blockHash) const
bool UpdateFromNewBroadcast (CMasternodeBroadcast &mnb, CConnman &connman)
void Check (bool fForce=false)
bool IsBroadcastedWithin (int nSeconds)
bool IsPingedWithin (int nSeconds, int64_t nTimeToCheckAt=-1)
bool IsEnabled () const
bool IsPreEnabled () const
bool IsPoSeBanned () const
bool IsPoSeVerified () const
bool IsExpired () const
bool IsOutpointSpent () const
bool IsUpdateRequired () const
bool IsSentinelPingExpired () const
bool IsNewStartRequired () const
bool IsValidForPayment () const
bool IsValidForMixingTxes () const
bool IsValidNetAddr ()
void IncreasePoSeBanScore ()
void DecreasePoSeBanScore ()
void PoSeBan ()
masternode_info_t GetInfo () const
std::string GetStateString () const
std::string GetStatus () const
int GetLastPaidTime () const
int GetLastPaidBlock () const
void UpdateLastPaid (const CBlockIndex *pindex, int nMaxBlocksToScanBack)
void AddGovernanceVote (uint256 nGovernanceObjectHash)
void FlagGovernanceItemsAsDirty ()
FLAG GOVERNANCE ITEMS AS DIRTY.
void RemoveGovernanceObject (uint256 nGovernanceObjectHash)
CMasternode & operator= (CMasternode const &from)
Public Member Functions inherited from masternode_info_t
masternode_info_t ()=default
masternode_info_t (masternode_info_t const &)=default
masternode_info_t (int activeState, int protoVer, int64_t sTime)
masternode_info_t (int activeState, int protoVer, int64_t sTime, COutPoint const &outpnt, CService const &addr, CPubKey const &pkCollAddr, CPubKey const &pkMN)
masternode_info_t (int activeState, int protoVer, int64_t sTime, COutPoint const &outpnt, CService const &addr, CKeyID const &pkCollAddr, CKeyID const &pkOwner, CBLSPublicKey const &pkOperator, CKeyID const &pkVoting)
Static Public Member Functions
static CollateralStatus CheckCollateral (const COutPoint &outpoint, const CKeyID &keyID)
static CollateralStatus CheckCollateral (const COutPoint &outpoint, const CKeyID &keyID, int &nHeightRet)
static bool IsValidStateForAutoStart (int nActiveStateIn)
static bool IsValidNetAddr (CService addrIn)
static std::string StateToString (int nStateIn)
Public Attributes
CMasternodePing lastPing {}
std::vector< unsigned char > vchSig {}
uint256 nCollateralMinConfBlockHash {}
int nBlockLastPaid {}
int nPoSeBanScore {}
int nPoSeBanHeight {}
int nMixingTxCount {}
bool fUnitTest = false
std::map< uint256, int > mapGovernanceObjectsVotedOn
ADD_SERIALIZE_METHODS
Public Attributes inherited from masternode_info_t
int nActiveState = 0
int nProtocolVersion = 0
int64_t sigTime = 0
COutPoint outpoint {}
CService addr {}
CPubKey pubKeyCollateralAddress {}
CPubKey pubKeyMasternode {}
CKeyID keyIDCollateralAddress {}
CKeyID keyIDOwner {}
CKeyID legacyKeyIDOperator {}
CBLSPublicKey blsPubKeyOperator
CKeyID keyIDVoting {}
int64_t nLastDsq = 0
int64_t nTimeLastChecked = 0
int64_t nTimeLastPaid = 0
int64_t nTimeLastPing = 0
bool fInfoValid = false
Private Attributes
CCriticalSection cs
Detailed Description
Definition at line 150 of file masternode.h.
Member Enumeration Documentation
CollateralStatus
enum CMasternode::CollateralStatus
Enumerator
COLLATERAL_OK
COLLATERAL_UTXO_NOT_FOUND
COLLATERAL_INVALID_AMOUNT
COLLATERAL_INVALID_PUBKEY
Definition at line 168 of file masternode.h.
state
enum CMasternode::state
Enumerator
MASTERNODE_PRE_ENABLED
MASTERNODE_ENABLED
MASTERNODE_EXPIRED
MASTERNODE_OUTPOINT_SPENT
MASTERNODE_UPDATE_REQUIRED
MASTERNODE_SENTINEL_PING_EXPIRED
MASTERNODE_NEW_START_REQUIRED
MASTERNODE_POSE_BAN
Definition at line 157 of file masternode.h.
Constructor & Destructor Documentation
CMasternode() [1/5]
CMasternode::CMasternode ()
Definition at line 26 of file masternode.cpp.
References GetAdjustedTime(), MASTERNODE_ENABLED, and PROTOCOL_VERSION.
CMasternode() [2/5]
CMasternode::CMasternode (const CMasternode & other)
Definition at line 35 of file masternode.cpp.
CMasternode() [3/5]
CMasternode::CMasternode (const CMasternodeBroadcast & mnb)
Definition at line 47 of file masternode.cpp.
References masternode_info_t::addr, masternode_info_t::nActiveState, masternode_info_t::nProtocolVersion, masternode_info_t::outpoint, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, and masternode_info_t::sigTime.
CMasternode() [4/5]
CMasternode::CMasternode (CService addrNew, COutPoint outpointNew, CPubKey pubKeyCollateralAddressNew, CPubKey pubKeyMasternodeNew, int nProtocolVersionIn)
Definition at line 30 of file masternode.cpp.
References masternode_info_t::addr, GetAdjustedTime(), MASTERNODE_ENABLED, and masternode_info_t::outpoint.
CMasternode() [5/5]
CMasternode::CMasternode (const uint256 & proTxHash, const CDeterministicMNCPtr & dmn)
Definition at line 54 of file masternode.cpp.
References DMN_PROTO_VERSION, GetAdjustedTime(), and MASTERNODE_ENABLED.
Member Function Documentation
AddGovernanceVote()
void CMasternode::AddGovernanceVote (uint256 nGovernanceObjectHash)
Definition at line 967 of file masternode.cpp.
References mapGovernanceObjectsVotedOn.
Referenced by CMasternodeMan::AddGovernanceVote().
CalculateScore()
arith_uint256 CMasternode::CalculateScore (const uint256 & blockHash) const
Definition at line 104 of file masternode.cpp.
References CHashWriter::GetHash(), nCollateralMinConfBlockHash, masternode_info_t::outpoint, PROTOCOL_VERSION, SER_GETHASH, and UintToArith256().
Check()
void CMasternode::Check (bool fForce = false)
Definition at line 141 of file masternode.cpp.
References activeMasternodeInfo, AssertLockHeld, chainActive, cs, cs_main, DecreasePoSeBanScore(), CBaseChainParams::DEVNET, fMasternodeMode, CMasternodePing::fSentinelIsCurrent, fUnitTest, GetAdjustedTime(), CMasternodePayments::GetMinMasternodePaymentsProto(), GetStateString(), GetTime(), GetUTXOCoin(), CChain::Height(), IsExpired(), CMasternodeSync::IsMasternodeListSynced(), IsNewStartRequired(), IsOutpointSpent(), IsPingedWithin(), IsPoSeBanned(), CMasternodeMan::IsSentinelPingActive(), IsSentinelPingExpired(), CMasternodeSync::IsSynced(), lastPing, CActiveMasternodeInfo::legacyKeyIDOperator, masternode_info_t::legacyKeyIDOperator, LOCK, LogPrint, LogPrintf, MASTERNODE_CHECK_SECONDS, MASTERNODE_ENABLED, MASTERNODE_EXPIRATION_SECONDS, MASTERNODE_EXPIRED, MASTERNODE_MIN_MNP_SECONDS, MASTERNODE_NEW_START_REQUIRED, MASTERNODE_NEW_START_REQUIRED_SECONDS, MASTERNODE_OUTPOINT_SPENT, MASTERNODE_POSE_BAN, MASTERNODE_POSE_BAN_MAX_SCORE, MASTERNODE_PRE_ENABLED, MASTERNODE_SENTINEL_PING_EXPIRED, MASTERNODE_SENTINEL_PING_MAX_SECONDS, MASTERNODE_UPDATE_REQUIRED, masternodeSync, mnodeman, mnpayments, masternode_info_t::nActiveState, CChainParams::NetworkIDString(), nPoSeBanHeight, nPoSeBanScore, masternode_info_t::nProtocolVersion, masternode_info_t::nTimeLastChecked, masternode_info_t::outpoint, Params(), PROTOCOL_VERSION, CBaseChainParams::REGTEST, ShutdownRequested(), CMasternodePing::sigTime, masternode_info_t::sigTime, CMasternodeMan::size(), and COutPoint::ToStringShort().
Referenced by CMasternodePing::CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), and CMasternodeBroadcast::Update().
CheckCollateral() [1/2]
CMasternode::CollateralStatus CMasternode::CheckCollateral (const COutPoint & outpoint, const CKeyID & keyID) static
Definition at line 114 of file masternode.cpp.
References masternode_info_t::outpoint.
Referenced by CMasternodeBroadcast::CheckOutpoint(), and CGovernanceObject::IsValidLocally().
CheckCollateral() [2/2]
CMasternode::CollateralStatus CMasternode::CheckCollateral (const COutPoint & outpoint, const CKeyID & keyID, int & nHeightRet) static
Definition at line 120 of file masternode.cpp.
References AssertLockHeld, COIN, COLLATERAL_INVALID_AMOUNT, COLLATERAL_INVALID_PUBKEY, COLLATERAL_OK, COLLATERAL_UTXO_NOT_FOUND, cs_main, GetScriptForDestination(), GetUTXOCoin(), base_blob< BITS >::IsNull(), Coin::nHeight, CTxOut::nValue, Coin::out, masternode_info_t::outpoint, and CTxOut::scriptPubKey.
DecreasePoSeBanScore()
void CMasternode::DecreasePoSeBanScore () inline
Definition at line 288 of file masternode.h.
References MASTERNODE_POSE_BAN_MAX_SCORE, and nPoSeBanScore.
Referenced by Check(), CMasternodeMan::ProcessVerifyBroadcast(), and CMasternodeMan::ProcessVerifyReply().
FlagGovernanceItemsAsDirty()
void CMasternode::FlagGovernanceItemsAsDirty ()
FLAG GOVERNANCE ITEMS AS DIRTY.
When masternode come and go on the network, we must flag the items they voted on to recalc it's cached flags
Definition at line 987 of file masternode.cpp.
References CMasternodeMan::AddDirtyGovernanceObjectHash(), mapGovernanceObjectsVotedOn, and mnodeman.
GetInfo()
masternode_info_t CMasternode::GetInfo () const
Definition at line 292 of file masternode.cpp.
References lastPing, masternode_info_t::nTimeLastPing, and CMasternodePing::sigTime.
Referenced by CMasternodeMan::GetMasternodeInfo(), and CMasternodeMan::GetNextMasternodeInQueueForPayment().
GetLastPaidBlock()
int CMasternode::GetLastPaidBlock () const inline
Definition at line 298 of file masternode.h.
References nBlockLastPaid.
Referenced by masternodelist().
GetLastPaidTime()
int CMasternode::GetLastPaidTime () const inline
Definition at line 297 of file masternode.h.
References masternode_info_t::nTimeLastPaid.
Referenced by masternodelist().
GetStateString()
std::string CMasternode::GetStateString () const
Definition at line 315 of file masternode.cpp.
References masternode_info_t::nActiveState, and StateToString().
Referenced by Check(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), and GetStatus().
GetStatus()
std::string CMasternode::GetStatus () const
Definition at line 320 of file masternode.cpp.
References GetStateString().
Referenced by masternode_list_conf(), masternodelist(), and MasternodeList::updateNodeList().
IncreasePoSeBanScore()
void CMasternode::IncreasePoSeBanScore () inline
Definition at line 287 of file masternode.h.
References MASTERNODE_POSE_BAN_MAX_SCORE, and nPoSeBanScore.
IsBroadcastedWithin()
bool CMasternode::IsBroadcastedWithin (int nSeconds) inline
Definition at line 235 of file masternode.h.
References GetAdjustedTime(), and masternode_info_t::sigTime.
Referenced by CMasternodeBroadcast::Update().
IsEnabled()
bool CMasternode::IsEnabled () const inline
Definition at line 247 of file masternode.h.
References MASTERNODE_ENABLED, and masternode_info_t::nActiveState.
Referenced by CMasternodePing::CheckAndUpdate().
IsExpired()
bool CMasternode::IsExpired () const inline
Definition at line 252 of file masternode.h.
References MASTERNODE_EXPIRED, and masternode_info_t::nActiveState.
Referenced by Check(), and CMasternodePing::CheckAndUpdate().
IsNewStartRequired()
bool CMasternode::IsNewStartRequired () const inline
Definition at line 256 of file masternode.h.
References MASTERNODE_NEW_START_REQUIRED, and masternode_info_t::nActiveState.
Referenced by Check(), and CMasternodePing::CheckAndUpdate().
IsOutpointSpent()
bool CMasternode::IsOutpointSpent () const inline
Definition at line 253 of file masternode.h.
References MASTERNODE_OUTPOINT_SPENT, and masternode_info_t::nActiveState.
Referenced by Check().
IsPingedWithin()
bool CMasternode::IsPingedWithin (int nSeconds, int64_t nTimeToCheckAt = -1) inline
Definition at line 237 of file masternode.h.
References GetAdjustedTime(), lastPing, and CMasternodePing::sigTime.
Referenced by Check(), CMasternodePing::CheckAndUpdate(), and CMasternodeMan::IsMasternodePingedWithin().
IsPoSeBanned()
bool CMasternode::IsPoSeBanned () const inline
Definition at line 249 of file masternode.h.
References MASTERNODE_POSE_BAN, and masternode_info_t::nActiveState.
Referenced by Check(), and CMasternodeBroadcast::Update().
IsPoSeVerified()
bool CMasternode::IsPoSeVerified () const inline
Definition at line 251 of file masternode.h.
References MASTERNODE_POSE_BAN_MAX_SCORE, and nPoSeBanScore.
Referenced by CMasternodeMan::CheckSameAddr(), and CMasternodeMan::ProcessVerifyBroadcast().
IsPreEnabled()
bool CMasternode::IsPreEnabled () const inline
Definition at line 248 of file masternode.h.
References MASTERNODE_PRE_ENABLED, and masternode_info_t::nActiveState.
IsSentinelPingExpired()
bool CMasternode::IsSentinelPingExpired () const inline
Definition at line 255 of file masternode.h.
References MASTERNODE_SENTINEL_PING_EXPIRED, and masternode_info_t::nActiveState.
Referenced by Check(), and CMasternodePing::CheckAndUpdate().
IsUpdateRequired()
bool CMasternode::IsUpdateRequired () const inline
Definition at line 254 of file masternode.h.
References MASTERNODE_UPDATE_REQUIRED, and masternode_info_t::nActiveState.
Referenced by CMasternodePing::CheckAndUpdate().
IsValidForMixingTxes()
bool CMasternode::IsValidForMixingTxes () const inline
Definition at line 279 of file masternode.h.
References MASTERNODE_MAX_MIXING_TXES, and nMixingTxCount.
Referenced by ProcessMessage().
IsValidForPayment()
bool CMasternode::IsValidForPayment () const inline
Definition at line 266 of file masternode.h.
References CSporkManager::IsSporkActive(), MASTERNODE_ENABLED, MASTERNODE_SENTINEL_PING_EXPIRED, masternode_info_t::nActiveState, SPORK_14_REQUIRE_SENTINEL_FLAG, and sporkManager.
IsValidNetAddr() [1/2]
bool CMasternode::IsValidNetAddr ()
Definition at line 279 of file masternode.cpp.
References masternode_info_t::addr.
Referenced by CActiveDeterministicMasternodeManager::GetLocalAddress(), CActiveLegacyMasternodeManager::ManageStateInitial(), and CMasternodeBroadcast::SimpleCheck().
IsValidNetAddr() [2/2]
bool CMasternode::IsValidNetAddr (CService addrIn) static
Definition at line 284 of file masternode.cpp.
References CNetAddr::IsIPv4(), IsReachable(), CNetAddr::IsRoutable(), CChainParams::NetworkIDString(), Params(), and CBaseChainParams::REGTEST.
IsValidStateForAutoStart()
static bool CMasternode::IsValidStateForAutoStart (int nActiveStateIn) inline static
Definition at line 258 of file masternode.h.
References MASTERNODE_ENABLED, MASTERNODE_EXPIRED, MASTERNODE_PRE_ENABLED, and MASTERNODE_SENTINEL_PING_EXPIRED.
Referenced by CMasternodeMan::CheckMnbAndUpdateMasternodeList(), and CActiveLegacyMasternodeManager::ManageStateRemote().
operator=()
CMasternode& CMasternode::operator= (CMasternode const & from) inline
Definition at line 308 of file masternode.h.
References fUnitTest, lastPing, mapGovernanceObjectsVotedOn, nBlockLastPaid, nCollateralMinConfBlockHash, nMixingTxCount, nPoSeBanHeight, nPoSeBanScore, and vchSig.
PoSeBan()
void CMasternode::PoSeBan () inline
Definition at line 289 of file masternode.h.
References MASTERNODE_POSE_BAN_MAX_SCORE, and nPoSeBanScore.
Referenced by CMasternodeMan::PoSeBan().
RemoveGovernanceObject()
void CMasternode::RemoveGovernanceObject (uint256 nGovernanceObjectHash)
Definition at line 975 of file masternode.cpp.
References mapGovernanceObjectsVotedOn.
SerializationOp()
template<typename Stream , typename Operation > void CMasternode::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 198 of file masternode.h.
References masternode_info_t::addr, masternode_info_t::blsPubKeyOperator, cs, fUnitTest, masternode_info_t::keyIDCollateralAddress, masternode_info_t::keyIDOwner, masternode_info_t::keyIDVoting, lastPing, masternode_info_t::legacyKeyIDOperator, LOCK, mapGovernanceObjectsVotedOn, masternode_info_t::nActiveState, nBlockLastPaid, nCollateralMinConfBlockHash, masternode_info_t::nLastDsq, nMixingTxCount, nPoSeBanHeight, nPoSeBanScore, masternode_info_t::nProtocolVersion, masternode_info_t::nTimeLastChecked, masternode_info_t::nTimeLastPaid, masternode_info_t::outpoint, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, READWRITE, masternode_info_t::sigTime, and vchSig.
StateToString()
std::string CMasternode::StateToString (int nStateIn) static
Definition at line 300 of file masternode.cpp.
References MASTERNODE_ENABLED, MASTERNODE_EXPIRED, MASTERNODE_NEW_START_REQUIRED, MASTERNODE_OUTPOINT_SPENT, MASTERNODE_POSE_BAN, MASTERNODE_PRE_ENABLED, MASTERNODE_SENTINEL_PING_EXPIRED, and MASTERNODE_UPDATE_REQUIRED.
Referenced by GetStateString(), CActiveLegacyMasternodeManager::ManageStateRemote(), MasternodeList::ShowQRCode(), and MasternodeList::updateMyMasternodeInfo().
UpdateFromNewBroadcast()
bool CMasternode::UpdateFromNewBroadcast (CMasternodeBroadcast & mnb, CConnman & connman)
Definition at line 63 of file masternode.cpp.
References activeMasternodeInfo, masternode_info_t::addr, CMasternodePing::CheckAndUpdate(), fMasternodeMode, CMasternodeBroadcast::fRecovery, CMasternodePing::GetHash(), CPubKey::GetID(), masternode_info_t::keyIDOwner, masternode_info_t::keyIDVoting, lastPing, legacyActiveMasternodeManager, CActiveMasternodeInfo::legacyKeyIDOperator, masternode_info_t::legacyKeyIDOperator, LogPrintf, CActiveLegacyMasternodeManager::ManageState(), CMasternodeMan::mapSeenMasternodePing, MASTERNODE_POSE_BAN_MAX_SCORE, mnodeman, nPoSeBanHeight, nPoSeBanScore, masternode_info_t::nProtocolVersion, masternode_info_t::nTimeLastChecked, PROTOCOL_VERSION, masternode_info_t::pubKeyMasternode, masternode_info_t::sigTime, and vchSig.
Referenced by CMasternodeBroadcast::Update().
UpdateLastPaid()
void CMasternode::UpdateLastPaid (const CBlockIndex * pindex, int nMaxBlocksToScanBack)
Definition at line 326 of file masternode.cpp.
References AssertLockHeld, chainActive, cs_main, cs_mapMasternodeBlocks, deterministicMNManager, CBlockIndex::GetBlockHash(), CDeterministicMNManager::GetListForBlock(), GetMasternodePayment(), GetScriptForDestination(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), masternode_info_t::keyIDCollateralAddress, LOCK, LogPrint, CMasternodePayments::mapMasternodeBlocks, mnpayments, nBlockLastPaid, CBlockIndex::nHeight, CBlockIndex::nTime, masternode_info_t::nTimeLastPaid, masternode_info_t::outpoint, Params(), CBlockIndex::pprev, ReadBlockFromDisk(), COutPoint::ToStringShort(), and CBlock::vtx.
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternode::ADD_SERIALIZE_METHODS
Definition at line 195 of file masternode.h.
cs
CCriticalSection CMasternode::cs mutable private
Definition at line 154 of file masternode.h.
Referenced by Check(), and SerializationOp().
fUnitTest
bool CMasternode::fUnitTest = false
Definition at line 184 of file masternode.h.
Referenced by Check(), operator=(), and SerializationOp().
lastPing
CMasternodePing CMasternode::lastPing {}
Definition at line 176 of file masternode.h.
Referenced by Check(), CMasternodePing::CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), GetInfo(), IsPingedWithin(), masternodebroadcast(), masternodelist(), operator=(), CMasternodeMan::PushDsegInvs(), SerializationOp(), CMasternodeBroadcast::SerializationOp(), CMasternodeMan::SetMasternodeLastPing(), MasternodeList::ShowQRCode(), CMasternodeBroadcast::SimpleCheck(), UpdateFromNewBroadcast(), and MasternodeList::updateNodeList().
mapGovernanceObjectsVotedOn
std::map<uint256, int> CMasternode::mapGovernanceObjectsVotedOn
Definition at line 187 of file masternode.h.
Referenced by AddGovernanceVote(), FlagGovernanceItemsAsDirty(), operator=(), RemoveGovernanceObject(), and SerializationOp().
nBlockLastPaid
int CMasternode::nBlockLastPaid {}
Definition at line 180 of file masternode.h.
Referenced by GetLastPaidBlock(), operator=(), SerializationOp(), and UpdateLastPaid().
nCollateralMinConfBlockHash
uint256 CMasternode::nCollateralMinConfBlockHash {}
Definition at line 179 of file masternode.h.
Referenced by CalculateScore(), CMasternodeBroadcast::CheckOutpoint(), operator=(), and SerializationOp().
nMixingTxCount
int CMasternode::nMixingTxCount {}
Definition at line 183 of file masternode.h.
Referenced by CMasternodeMan::AllowMixing(), CMasternodeMan::DisallowMixing(), IsValidForMixingTxes(), operator=(), and SerializationOp().
nPoSeBanHeight
int CMasternode::nPoSeBanHeight {}
Definition at line 182 of file masternode.h.
Referenced by Check(), operator=(), SerializationOp(), and UpdateFromNewBroadcast().
nPoSeBanScore
int CMasternode::nPoSeBanScore {}
Definition at line 181 of file masternode.h.
Referenced by Check(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), DecreasePoSeBanScore(), IncreasePoSeBanScore(), IsPoSeVerified(), operator=(), PoSeBan(), SerializationOp(), and UpdateFromNewBroadcast().
vchSig
std::vector<unsigned char> CMasternode::vchSig {}
Definition at line 177 of file masternode.h.
Referenced by CMasternodeBroadcast::CheckSignature(), masternodebroadcast(), operator=(), SerializationOp(), CMasternodeBroadcast::SerializationOp(), CMasternodeBroadcast::Sign(), and UpdateFromNewBroadcast().
The documentation for this class was generated from the following files:
src/masternode.h
src/masternode.cpp
Released under the MIT license