Dash Core: benchmark::State Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
benchmark::State Class Reference
#include <bench.h>
Public Member Functions
State (std::string _name, double _maxElapsed)
bool KeepRunning ()
Private Attributes
std::string name
double maxElapsed
double beginTime
double lastTime
double minTime
double maxTime
double countMaskInv
uint64_t count
uint64_t countMask
uint64_t beginCycles
uint64_t lastCycles
uint64_t minCycles
uint64_t maxCycles
Detailed Description
Definition at line 39 of file bench.h.
Constructor & Destructor Documentation
State()
benchmark::State::State (std::string _name, double _maxElapsed) inline
Definition at line 51 of file bench.h.
References countMask, countMaskInv, maxCycles, maxTime, minCycles, and minTime.
Member Function Documentation
KeepRunning()
bool benchmark::State::KeepRunning ()
Definition at line 42 of file bench.cpp.
References count, gettimedouble(), name, and perf_cpucycles().
Referenced by Base58CheckEncode(), Base58Decode(), Base58Encode(), DKG::Bench_BuildQuorumVerificationVectors(), DKG::Bench_VerifyContributionShares(), BLSPubKeyAggregate_Normal(), BLSSecKeyAggregate_Normal(), BLSSign_Normal(), BLSVerify_Batched(), BLSVerify_BatchedParallel(), BLSVerify_LargeAggregatedBlock(), BLSVerify_LargeAggregatedBlock1000PreVerified(), BLSVerify_LargeBlock(), BLSVerify_LargeBlockSelfAggregated(), BLSVerify_Normal(), CCheckQueueSpeed(), CCheckQueueSpeedPrevectorJob(), CCoinsCaching(), CoinSelection(), DeserializeAndCheckBlockTest(), DeserializeBlockTest(), ECDSASign(), ECDSAVerify(), ECDSAVerify_LargeBlock(), HASH_DSHA256(), HASH_DSHA256_0032b(), HASH_DSHA256_0032b_single(), HASH_DSHA256_0080b_single(), HASH_DSHA256_0128b_single(), HASH_DSHA256_0512b_single(), HASH_DSHA256_1024b_single(), HASH_DSHA256_2048b_single(), HASH_RIPEMD160(), HASH_SHA1(), HASH_SHA256(), HASH_SHA256_0032b(), HASH_SHA512(), HASH_SipHash_0032b(), HASH_X11(), HASH_X11_0032b_single(), HASH_X11_0080b_single(), HASH_X11_0128b_single(), HASH_X11_0512b_single(), HASH_X11_1024b_single(), HASH_X11_2048b_single(), int_atoi(), int_lexical_cast(), LockedPool(), MempoolEviction(), RollingBloom(), Sleep100ms(), strings_1_itostr(), strings_1_lexical_cast(), strings_1_numberToString(), strings_1_to_string(), strings_2_multi_itostr(), strings_2_multi_lexical_cast(), strings_2_multi_numberToString(), strings_2_multi_to_string(), strings_2_strptintf(), and Trig().
Member Data Documentation
beginCycles
uint64_t benchmark::State::beginCycles private
Definition at line 46 of file bench.h.
beginTime
double benchmark::State::beginTime private
Definition at line 42 of file bench.h.
count
uint64_t benchmark::State::count private
Definition at line 44 of file bench.h.
countMask
uint64_t benchmark::State::countMask private
Definition at line 45 of file bench.h.
Referenced by State().
countMaskInv
double benchmark::State::countMaskInv private
Definition at line 43 of file bench.h.
Referenced by State().
lastCycles
uint64_t benchmark::State::lastCycles private
Definition at line 47 of file bench.h.
lastTime
double benchmark::State::lastTime private
Definition at line 43 of file bench.h.
maxCycles
uint64_t benchmark::State::maxCycles private
Definition at line 49 of file bench.h.
Referenced by State().
maxElapsed
double benchmark::State::maxElapsed private
Definition at line 41 of file bench.h.
maxTime
double benchmark::State::maxTime private
Definition at line 43 of file bench.h.
Referenced by State().
minCycles
uint64_t benchmark::State::minCycles private
Definition at line 48 of file bench.h.
Referenced by State().
minTime
double benchmark::State::minTime private
Definition at line 43 of file bench.h.
Referenced by State().
name
std::string benchmark::State::name private
Definition at line 40 of file bench.h.
The documentation for this class was generated from the following files:
src/bench/bench.h
src/bench/bench.cpp
Released under the MIT license