Dash Core: src/wallet/test/crypto_tests.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
crypto_tests.cpp File Reference
#include "test/test_random.h"
#include "utilstrencodings.h"
#include "test/test_dash.h"
#include "wallet/crypter.h"
#include <vector>
#include <boost/test/unit_test.hpp>
#include <openssl/aes.h>
#include <openssl/evp.h>
Classes
class TestCrypter
Functions
bool OldSetKeyFromPassphrase (const SecureString &strKeyData, const std::vector< unsigned char > &chSalt, const unsigned int nRounds, const unsigned int nDerivationMethod, unsigned char *chKey, unsigned char *chIV)
bool OldEncrypt (const CKeyingMaterial &vchPlaintext, std::vector< unsigned char > &vchCiphertext, const unsigned char chKey[32], const unsigned char chIV[16])
bool OldDecrypt (const std::vector< unsigned char > &vchCiphertext, CKeyingMaterial &vchPlaintext, const unsigned char chKey[32], const unsigned char chIV[16])
bool OldEncryptAES256 (const SecureString &sKey, const SecureString &sPlaintext, const std::string &sIV, std::string &sCiphertext)
bool OldDecryptAES256 (const SecureString &sKey, const std::string &sCiphertext, const std::string &sIV, SecureString &sPlaintext)
void TestAES256CBC (const std::string &hexkey, const std::string &hexiv, const std::string &hexin, const std::string &hexout)
BOOST_AUTO_TEST_CASE (passphrase)
BOOST_AUTO_TEST_CASE (encrypt)
BOOST_AUTO_TEST_CASE (decrypt)
BOOST_AUTO_TEST_CASE (aes_256_cbc_testvectors)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (passphrase)
Definition at line 276 of file crypto_tests.cpp.
References GetRandBytes(), GetRandHash(), ParseHex(), and TestCrypter::TestPassphrase().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (encrypt)
Definition at line 292 of file crypto_tests.cpp.
References base_blob< BITS >::begin(), base_blob< BITS >::end(), GetRandHash(), ParseHex(), CCrypter::SetKeyFromPassphrase(), TestCrypter::TestEncrypt(), and WALLET_CRYPTO_SALT_SIZE.
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (decrypt)
Definition at line 307 of file crypto_tests.cpp.
References base_blob< BITS >::begin(), base_blob< BITS >::end(), GetRandHash(), ParseHex(), CCrypter::SetKeyFromPassphrase(), TestCrypter::TestDecrypt(), and WALLET_CRYPTO_SALT_SIZE.
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (aes_256_cbc_testvectors)
Definition at line 328 of file crypto_tests.cpp.
References TestAES256CBC().
OldDecrypt()
bool OldDecrypt (const std::vector< unsigned char > & vchCiphertext, CKeyingMaterial & vchPlaintext, const unsigned char chKey[32], const unsigned char chIV[16])
Definition at line 65 of file crypto_tests.cpp.
References ctx.
Referenced by TestCrypter::TestDecrypt().
OldDecryptAES256()
bool OldDecryptAES256 (const SecureString & sKey, const std::string & sCiphertext, const std::string & sIV, SecureString & sPlaintext)
Definition at line 132 of file crypto_tests.cpp.
References ctx, and LogPrintf.
Referenced by TestAES256CBC().
OldEncrypt()
bool OldEncrypt (const CKeyingMaterial & vchPlaintext, std::vector< unsigned char > & vchCiphertext, const unsigned char chKey[32], const unsigned char chIV[16])
Definition at line 37 of file crypto_tests.cpp.
References ctx.
Referenced by TestCrypter::TestEncryptSingle().
OldEncryptAES256()
bool OldEncryptAES256 (const SecureString & sKey, const SecureString & sPlaintext, const std::string & sIV, std::string & sCiphertext)
Definition at line 94 of file crypto_tests.cpp.
References ctx, and LogPrintf.
Referenced by TestAES256CBC().
OldSetKeyFromPassphrase()
bool OldSetKeyFromPassphrase (const SecureString & strKeyData, const std::vector< unsigned char > & chSalt, const unsigned int nRounds, const unsigned int nDerivationMethod, unsigned char * chKey, unsigned char * chIV)
Definition at line 18 of file crypto_tests.cpp.
References memory_cleanse(), WALLET_CRYPTO_KEY_SIZE, and WALLET_CRYPTO_SALT_SIZE.
Referenced by TestCrypter::TestPassphraseSingle().
TestAES256CBC()
void TestAES256CBC (const std::string & hexkey, const std::string & hexiv, const std::string & hexin, const std::string & hexout)
Definition at line 166 of file crypto_tests.cpp.
References DecryptAES256(), EncryptAES256(), HexStr(), OldDecryptAES256(), OldEncryptAES256(), and ParseHex().
Referenced by BOOST_AUTO_TEST_CASE().
Released under the MIT license