Dash Core: MapWallet
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
MapWallet
Classes
struct CompareValueOnly
Functions
std::string COutput::ToString () const
int COutput::Priority () const
const CWalletTx * CWallet::GetWalletTx (const uint256 &hash) const
CPubKey CWallet::GenerateNewKey (uint32_t nAccountIndex, bool fInternal)
keystore implementation Generate a new key
void CWallet::DeriveNewChildKey (const CKeyMetadata &metadata, CKey &secretRet, uint32_t nAccountIndex, bool fInternal)
bool CWallet::GetPubKey (const CKeyID &address, CPubKey &vchPubKeyOut) const override
GetPubKey implementation that also checks the mapHdPubKeys.
bool CWallet::GetKey (const CKeyID &address, CKey &keyOut) const override
GetKey implementation that can derive a HD private key on the fly.
bool CWallet::HaveKey (const CKeyID &address) const override
HaveKey implementation that also checks the mapHdPubKeys.
bool CWallet::LoadHDPubKey (const CHDPubKey &hdPubKey)
loads a HDPubKey into the wallets memory
bool CWallet::AddHDPubKey (const CExtPubKey &extPubKey, bool fInternal)
Adds a HDPubKey into the wallet(database)
bool CWallet::AddKeyPubKey (const CKey &key, const CPubKey &pubkey) override
Adds a key to the store, and saves it to disk.
bool CWallet::AddCryptedKey (const CPubKey &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret) override
Adds an encrypted key to the store, and saves it to disk.
bool CWallet::LoadKeyMetadata (const CTxDestination &pubKey, const CKeyMetadata &metadata)
Load metadata (used by LoadWallet)
bool CWallet::LoadCryptedKey (const CPubKey &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret)
Adds an encrypted key to the store, without saving it to disk (used by LoadWallet)
void CWallet::UpdateTimeFirstKey (int64_t nCreateTime)
bool CWallet::AddCScript (const CScript &redeemScript) override
Support for BIP 0013 : see https://github.com/bitcoin/bips/blob/master/bip-0013.mediawiki.
bool CWallet::LoadCScript (const CScript &redeemScript)
bool CWallet::AddWatchOnly (const CScript &dest) override
Private version of AddWatchOnly method which does not accept a timestamp, and which will reset the wallet's nTimeFirstKey value to 1 if the watch key did not previously have a timestamp associated with it.
bool CWallet::AddWatchOnly (const CScript &dest, int64_t nCreateTime)
Adds a watch-only address to the store, and saves it to disk.
bool CWallet::RemoveWatchOnly (const CScript &dest) override
bool CWallet::LoadWatchOnly (const CScript &dest)
Adds a watch-only address to the store, without saving it to disk (used by LoadWallet)
bool CWallet::Unlock (const SecureString &strWalletPassphrase, bool fForMixingOnly=false)
bool CWallet::ChangeWalletPassphrase (const SecureString &strOldWalletPassphrase, const SecureString &strNewWalletPassphrase)
void CWallet::SetBestChain (const CBlockLocator &loc) override
bool CWallet::SetMinVersion (enum WalletFeature, CWalletDB *pwalletdbIn=NULL, bool fExplicit=false)
signify that a particular wallet feature is now used. this may change nWalletVersion and nWalletMaxVersion if those are lower
bool CWallet::SetMaxVersion (int nVersion)
change which version we're allowed to upgrade to (note that this does not immediately imply upgrading to that format)
std::set< uint256 > CWallet::GetConflicts (const uint256 &txid) const
Get wallet transactions that conflict with given transaction (spend same outputs)
void CWallet::Flush (bool shutdown=false)
Flush wallet (bitdb flush)
static bool CWallet::Verify ()
Verify the wallet database and perform salvage if required.
void CWallet::SyncMetaData (std::pair< TxSpends::iterator, TxSpends::iterator >)
bool CWallet::IsSpent (const uint256 &hash, unsigned int n) const
Outpoint is spent if any non-conflicted transaction spends it:
void CWallet::AddToSpends (const COutPoint &outpoint, const uint256 &wtxid)
void CWallet::AddToSpends (const uint256 &wtxid)
bool CWallet::EncryptWallet (const SecureString &strWalletPassphrase)
DBErrors CWallet::ReorderTransactions ()
int64_t CWallet::IncOrderPosNext (CWalletDB *pwalletdb=NULL)
Increment the next transaction order id.
bool CWallet::AccountMove (std::string strFrom, std::string strTo, CAmount nAmount, std::string strComment="")
bool CWallet::GetAccountPubkey (CPubKey &pubKey, std::string strAccount, bool bForceNew=false)
void CWallet::MarkDirty ()
bool CWallet::AddToWallet (const CWalletTx &wtxIn, bool fFlushOnClose=true)
bool CWallet::LoadToWallet (const CWalletTx &wtxIn)
bool CWallet::AddToWalletIfInvolvingMe (const CTransaction &tx, const CBlockIndex *pIndex, int posInBlock, bool fUpdate)
Add a transaction to the wallet, or update it.
bool CWallet::AbandonTransaction (const uint256 &hashTx)
void CWallet::MarkConflicted (const uint256 &hashBlock, const uint256 &hashTx)
void CWallet::SyncTransaction (const CTransaction &tx, const CBlockIndex *pindex, int posInBlock) override
isminetype CWallet::IsMine (const CTxIn &txin) const
CAmount CWallet::GetDebit (const CTxIn &txin, const isminefilter &filter) const
Returns amount of debit if the input matches the filter, otherwise returns 0.
int CWallet::GetRealOutpointPrivateSendRounds (const COutPoint &outpoint, int nRounds=0) const
int CWallet::GetCappedOutpointPrivateSendRounds (const COutPoint &outpoint) const
bool CWallet::IsDenominated (const COutPoint &outpoint) const
isminetype CWallet::IsMine (const CTxOut &txout) const
CAmount CWallet::GetCredit (const CTxOut &txout, const isminefilter &filter) const
bool CWallet::IsChange (const CTxOut &txout) const
CAmount CWallet::GetChange (const CTxOut &txout) const
void CWallet::GenerateNewHDChain ()
bool CWallet::SetHDChain (const CHDChain &chain, bool memonly)
bool CWallet::SetCryptedHDChain (const CHDChain &chain, bool memonly)
bool CWallet::GetDecryptedHDChain (CHDChain &hdChainRet)
bool CWallet::IsHDEnabled ()
HD Wallet Functions.
bool CWallet::IsMine (const CTransaction &tx) const
bool CWallet::IsFromMe (const CTransaction &tx) const
should probably be renamed to IsRelevantToMe
CAmount CWallet::GetDebit (const CTransaction &tx, const isminefilter &filter) const
bool CWallet::IsAllFromMe (const CTransaction &tx, const isminefilter &filter) const
Returns whether all of the inputs match the filter.
CAmount CWallet::GetCredit (const CTransaction &tx, const isminefilter &filter) const
CAmount CWallet::GetChange (const CTransaction &tx) const
int64_t CWalletTx::GetTxTime () const
int CWalletTx::GetRequestCount () const
void CWalletTx::GetAmounts (std::list< COutputEntry > &listReceived, std::list< COutputEntry > &listSent, CAmount &nFee, std::string &strSentAccount, const isminefilter &filter) const
void CWalletTx::GetAccountAmounts (const std::string &strAccount, CAmount &nReceived, CAmount &nSent, CAmount &nFee, const isminefilter &filter) const
CBlockIndex * CWallet::ScanForWalletTransactions (CBlockIndex *pindexStart, bool fUpdate=false)
Scan the block chain (starting in pindexStart) for transactions from or to us.
void CWallet::ReacceptWalletTransactions ()
bool CWalletTx::RelayWalletTransaction (CConnman *connman, const std::string &strCommand="tx")
std::set< uint256 > CWalletTx::GetConflicts () const
CAmount CWalletTx::GetDebit (const isminefilter &filter) const
filter decides which addresses will count towards the debit
CAmount CWalletTx::GetCredit (const isminefilter &filter) const
CAmount CWalletTx::GetImmatureCredit (bool fUseCache=true) const
CAmount CWalletTx::GetAvailableCredit (bool fUseCache=true) const
CAmount CWalletTx::GetImmatureWatchOnlyCredit (const bool &fUseCache=true) const
CAmount CWalletTx::GetAvailableWatchOnlyCredit (const bool &fUseCache=true) const
CAmount CWalletTx::GetAnonymizedCredit (bool fUseCache=true) const
CAmount CWalletTx::GetDenominatedCredit (bool unconfirmed, bool fUseCache=true) const
CAmount CWalletTx::GetChange () const
bool CWalletTx::InMempool () const
bool CWalletTx::IsTrusted () const
bool CWalletTx::IsEquivalentTo (const CWalletTx &tx) const
std::vector< uint256 > CWallet::ResendWalletTransactionsBefore (int64_t nTime, CConnman *connman)
void CWallet::ResendWalletTransactions (int64_t nBestBlockTime, CConnman *connman) override
Detailed Description
Function Documentation
AbandonTransaction()
bool CWallet::AbandonTransaction (const uint256 & hashTx)
Definition at line 1258 of file wallet.cpp.
References base_blob< BITS >::begin(), cs_main, CWallet::cs_wallet, CT_UPDATED, CWallet::fAnonymizableTallyCached, CWallet::fAnonymizableTallyCachedNonDenom, COutPoint::hash, LOCK2, CWallet::mapTxSpends, CWallet::mapWallet, CWallet::NotifyTransactionChanged, CTxIn::prevout, CWallet::strWalletFile, and CWalletDB::WriteTx().
Referenced by WalletModel::abandonTransaction(), and abandontransaction().
AccountMove()
bool CWallet::AccountMove (std::string strFrom, std::string strTo, CAmount nAmount, std::string strComment = "")
Definition at line 975 of file wallet.cpp.
References CWallet::AddAccountingEntry(), GetAdjustedTime(), CWallet::IncOrderPosNext(), CAccountingEntry::nCreditDebit, CAccountingEntry::nOrderPos, CAccountingEntry::nTime, CAccountingEntry::strAccount, CAccountingEntry::strComment, CAccountingEntry::strOtherAccount, CWallet::strWalletFile, CDB::TxnBegin(), and CDB::TxnCommit().
Referenced by movecmd().
AddCryptedKey()
bool CWallet::AddCryptedKey (const CPubKey & vchPubKey, const std::vector< unsigned char > & vchCryptedSecret) override virtual
Adds an encrypted key to the store, and saves it to disk.
Reimplemented from CCryptoKeyStore.
Definition at line 316 of file wallet.cpp.
References CCryptoKeyStore::AddCryptedKey(), CWallet::cs_wallet, CWallet::fFileBacked, CPubKey::GetID(), LOCK, CWallet::mapKeyMetadata, CWallet::pwalletdbEncryption, CWallet::strWalletFile, and CWalletDB::WriteCryptedKey().
AddCScript()
bool CWallet::AddCScript (const CScript & redeemScript) override virtual
Support for BIP 0013 : see https://github.com/bitcoin/bips/blob/master/bip-0013.mediawiki.
Reimplemented from CBasicKeyStore.
Definition at line 362 of file wallet.cpp.
References CBasicKeyStore::AddCScript(), CWallet::fFileBacked, Hash160(), CWallet::strWalletFile, and CWalletDB::WriteCScript().
Referenced by addmultisigaddress(), ImportScript(), and ProcessImport().
AddHDPubKey()
bool CWallet::AddHDPubKey (const CExtPubKey & extPubKey, bool fInternal)
Adds a HDPubKey into the wallet(database)
Definition at line 263 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, CHDPubKey::extPubKey, CWallet::fFileBacked, CCryptoKeyStore::GetHDChain(), CHDChain::GetID(), CPubKey::GetID(), GetScriptForDestination(), GetScriptForRawPubKey(), CBasicKeyStore::HaveWatchOnly(), CHDPubKey::hdchainID, CWallet::mapHdPubKeys, CWallet::mapKeyMetadata, CHDPubKey::nChangeIndex, CExtPubKey::pubkey, CWallet::RemoveWatchOnly(), CWallet::strWalletFile, and CWalletDB::WriteHDPubKey().
Referenced by CWallet::DeriveNewChildKey().
AddKeyPubKey()
bool CWallet::AddKeyPubKey (const CKey & key, const CPubKey & pubkey) override virtual
Adds a key to the store, and saves it to disk.
Reimplemented from CCryptoKeyStore.
Definition at line 291 of file wallet.cpp.
References CCryptoKeyStore::AddKeyPubKey(), AssertLockHeld, CWallet::cs_wallet, CWallet::fFileBacked, CPubKey::GetID(), CKey::GetPrivKey(), GetScriptForDestination(), GetScriptForRawPubKey(), CBasicKeyStore::HaveWatchOnly(), CCryptoKeyStore::IsCrypted(), CWallet::mapKeyMetadata, CWallet::RemoveWatchOnly(), CWallet::strWalletFile, and CWalletDB::WriteKey().
Referenced by BOOST_FIXTURE_TEST_CASE(), CWallet::GenerateNewKey(), importelectrumwallet(), importprivkey(), importwallet(), and ProcessImport().
AddToSpends() [1/2]
void CWallet::AddToSpends (const COutPoint & outpoint, const uint256 & wtxid) private
Definition at line 733 of file wallet.cpp.
References CWallet::mapTxSpends, CWallet::setWalletUTXO, and CWallet::SyncMetaData().
Referenced by CWallet::AddToSpends(), CWallet::AddToWallet(), and CWallet::LoadToWallet().
AddToSpends() [2/2]
void CWallet::AddToSpends (const uint256 & wtxid) private
Definition at line 744 of file wallet.cpp.
References CWallet::AddToSpends(), CWallet::mapWallet, and CTxIn::prevout.
AddToWallet()
bool CWallet::AddToWallet (const CWalletTx & wtxIn, bool fFlushOnClose = true)
Definition at line 1059 of file wallet.cpp.
References CWallet::AddToSpends(), CWalletTx::BindWallet(), CWallet::cs_wallet, CT_NEW, CT_UPDATED, deterministicMNManager, CWallet::fAnonymizableTallyCached, CWallet::fAnonymizableTallyCachedNonDenom, CWalletTx::fFromMe, GetAdjustedTime(), GetArg(), CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), CMerkleTx::hashBlock, CMerkleTx::hashUnset(), CDeterministicMNManager::HasMNCollateralAtChainTip(), CWallet::IncOrderPosNext(), CMerkleTx::isAbandoned(), CWallet::IsMine(), base_blob< BITS >::IsNull(), CDeterministicMNManager::IsProTxWithCollateral(), CWallet::IsSpent(), LOCK, CWallet::LockCoin(), LogPrintf, mapBlockIndex, CWallet::mapWallet, CWalletTx::MarkDirty(), CMerkleTx::nIndex, CWalletTx::nOrderPos, CWallet::NotifyTransactionChanged, CAccountingEntry::nTime, CWalletTx::nTimeReceived, CWalletTx::nTimeSmart, runCommand(), CWallet::setWalletUTXO, CWallet::strWalletFile, base_blob< BITS >::ToString(), CMerkleTx::tx, CWalletDB::WriteTx(), and CWallet::wtxOrdered.
Referenced by CWallet::AddToWalletIfInvolvingMe(), BOOST_AUTO_TEST_CASE(), CWallet::CommitTransaction(), and importprunedfunds().
AddToWalletIfInvolvingMe()
bool CWallet::AddToWalletIfInvolvingMe (const CTransaction & tx, const CBlockIndex * pIndex, int posInBlock, bool fUpdate)
Add a transaction to the wallet, or update it.
pIndex and posInBlock should be set when the transaction was known to be included in a block. When posInBlock = SYNC_TRANSACTION_NOT_IN_BLOCK (-1) , then wallet state is not updated in AddToWallet, but notifications happen and cached balances are marked dirty. If fUpdate is true, existing transactions will be updated. TODO: One exception to this is that the abandoned state is cleared under the assumption that any further notification of a transaction that was considered abandoned is an indication that it is not safe to be considered abandoned. Abandoned state should probably be more carefuly tracked via different posInBlock signals or by checking mempool presence when necessary.
Definition at line 1224 of file wallet.cpp.
References CWallet::AddToWallet(), AssertLockHeld, CWallet::cs_wallet, CBlockIndex::GetBlockHash(), CTransaction::GetHash(), CWallet::IsFromMe(), CWallet::IsMine(), LogPrintf, MakeTransactionRef(), CWallet::mapTxSpends, CWallet::mapWallet, CWallet::MarkConflicted(), CTxIn::prevout, CMerkleTx::SetMerkleBranch(), base_blob< BITS >::ToString(), and CTransaction::vin.
Referenced by CWallet::ScanForWalletTransactions(), and CWallet::SyncTransaction().
AddWatchOnly() [1/2]
bool CWallet::AddWatchOnly (const CScript & dest) override private virtual
Private version of AddWatchOnly method which does not accept a timestamp, and which will reset the wallet's nTimeFirstKey value to 1 if the watch key did not previously have a timestamp associated with it.
Because this is an inherited virtual method, it is accessible despite being marked private, but it is marked private anyway to encourage use of the other AddWatchOnly which accepts a timestamp and sets nTimeFirstKey more intelligently for more efficient rescans.
Reimplemented from CBasicKeyStore.
Definition at line 387 of file wallet.cpp.
References CBasicKeyStore::AddWatchOnly(), CWallet::fFileBacked, CWallet::mapKeyMetadata, CKeyMetadata::nCreateTime, CWallet::NotifyWatchonlyChanged, CWallet::strWalletFile, CWallet::UpdateTimeFirstKey(), and CWalletDB::WriteWatchOnly().
Referenced by CWallet::AddWatchOnly(), ImportScript(), and ProcessImport().
AddWatchOnly() [2/2]
bool CWallet::AddWatchOnly (const CScript & dest, int64_t nCreateTime)
Adds a watch-only address to the store, and saves it to disk.
Definition at line 399 of file wallet.cpp.
References CWallet::AddWatchOnly(), and CWallet::mapKeyMetadata.
ChangeWalletPassphrase()
bool CWallet::ChangeWalletPassphrase (const SecureString & strOldWalletPassphrase, const SecureString & strNewWalletPassphrase)
Definition at line 467 of file wallet.cpp.
References CWallet::cs_wallet, CCrypter::Decrypt(), CCrypter::Encrypt(), GetBoolArg(), GetTimeMillis(), CCryptoKeyStore::IsLocked(), keePassInt, LOCK, CCryptoKeyStore::Lock(), LogPrintf, CWallet::mapMasterKeys, CKeePassIntegrator::retrievePassphrase(), CCrypter::SetKeyFromPassphrase(), CWallet::strWalletFile, CCryptoKeyStore::Unlock(), CKeePassIntegrator::updatePassphrase(), CCryptoKeyStore::vMasterKey, and CWalletDB::WriteMasterKey().
Referenced by WalletModel::changePassphrase(), and walletpassphrasechange().
DeriveNewChildKey()
void CWallet::DeriveNewChildKey (const CKeyMetadata & metadata, CKey & secretRet, uint32_t nAccountIndex, bool fInternal) private
Definition at line 144 of file wallet.cpp.
References CWallet::AddHDPubKey(), CCryptoKeyStore::DecryptHDChain(), CHDChain::DeriveChildExtKey(), CHDChain::GetAccount(), CCryptoKeyStore::GetHDChain(), CHDChain::GetID(), CPubKey::GetID(), CKey::GetPubKey(), CHDChain::GetSeedHash(), CWallet::HaveKey(), CCryptoKeyStore::IsCrypted(), CExtKey::key, CWallet::mapKeyMetadata, CKeyMetadata::nCreateTime, CExtKey::Neuter(), CHDAccount::nExternalChainCounter, CHDAccount::nInternalChainCounter, CHDChain::SetAccount(), CWallet::SetCryptedHDChain(), CWallet::SetHDChain(), CWallet::UpdateTimeFirstKey(), and CKey::VerifyPubKey().
Referenced by CWallet::GenerateNewKey().
EncryptWallet()
bool CWallet::EncryptWallet (const SecureString & strWalletPassphrase)
Definition at line 755 of file wallet.cpp.
References CWallet::cs_wallet, DBG, CCrypter::Encrypt(), CCryptoKeyStore::EncryptHDChain(), CCryptoKeyStore::EncryptKeys(), FEATURE_WALLETCRYPT, CWallet::fFileBacked, GetBoolArg(), CCryptoKeyStore::GetHDChain(), CHDChain::GetID(), CHDChain::GetSeed(), CHDChain::GetSeedHash(), GetStrongRandBytes(), GetTimeMillis(), HexStr(), CCryptoKeyStore::IsCrypted(), CWallet::IsHDEnabled(), CHDChain::IsNull(), keePassInt, LOCK, CCryptoKeyStore::Lock(), LogPrintf, CWallet::mapMasterKeys, CMasterKey::nDerivationMethod, CMasterKey::nDeriveIterations, CWallet::NewKeyPool(), CWallet::nMasterKeyMaxID, CCryptoKeyStore::NotifyStatusChanged, tinyformat::printf(), CWallet::pwalletdbEncryption, CDB::Rewrite(), CWallet::SetCryptedHDChain(), CCrypter::SetKeyFromPassphrase(), CWallet::SetMinVersion(), CWallet::strWalletFile, CWallet::TopUpKeyPool(), CDB::TxnAbort(), CDB::TxnBegin(), CDB::TxnCommit(), CWallet::Unlock(), CKeePassIntegrator::updatePassphrase(), CMasterKey::vchCryptedKey, CMasterKey::vchSalt, CCryptoKeyStore::vMasterKey, WALLET_CRYPTO_KEY_SIZE, WALLET_CRYPTO_SALT_SIZE, and CWalletDB::WriteMasterKey().
Referenced by encryptwallet(), and WalletModel::setWalletEncrypted().
Flush()
void CWallet::Flush (bool shutdown = false)
Flush wallet (bitdb flush)
Definition at line 609 of file wallet.cpp.
References bitdb, and CDBEnv::Flush().
Referenced by PrepareShutdown().
GenerateNewHDChain()
void CWallet::GenerateNewHDChain ()
Definition at line 1580 of file wallet.cpp.
References CHDChain::Debug(), ForceRemoveArg(), GetArg(), IsArgSet(), IsHex(), LogPrintf, ParseHex(), CWallet::SetHDChain(), CHDChain::SetMnemonic(), and CHDChain::SetSeed().
Referenced by CWallet::CreateWalletFromFile().
GenerateNewKey()
CPubKey CWallet::GenerateNewKey (uint32_t nAccountIndex, bool fInternal)
keystore implementation Generate a new key
Definition at line 108 of file wallet.cpp.
References CWallet::AddKeyPubKey(), AssertLockHeld, CWallet::CanSupportFeature(), CWallet::cs_wallet, CWallet::DeriveNewChildKey(), FEATURE_COMPRPUBKEY, CPubKey::GetID(), CKey::GetPubKey(), GetTime(), CWallet::IsHDEnabled(), CKey::MakeNewKey(), CWallet::mapKeyMetadata, CWallet::SetMinVersion(), CWallet::UpdateTimeFirstKey(), and CKey::VerifyPubKey().
Referenced by CWallet::GetKeyFromPool(), and CWallet::TopUpKeyPool().
GetAccountAmounts()
void CWalletTx::GetAccountAmounts (const std::string & strAccount, CAmount & nReceived, CAmount & nSent, CAmount & nFee, const isminefilter & filter) const
Definition at line 1850 of file wallet.cpp.
References COutputEntry::amount, CWallet::cs_wallet, COutputEntry::destination, CWalletTx::GetAmounts(), LOCK, CWallet::mapAddressBook, and CWalletTx::pwallet.
Referenced by CWallet::GetAccountBalance().
GetAccountPubkey()
bool CWallet::GetAccountPubkey (CPubKey & pubKey, std::string strAccount, bool bForceNew = false)
Definition at line 1009 of file wallet.cpp.
References CPubKey::GetID(), CWallet::GetKeyFromPool(), GetScriptForDestination(), CPubKey::IsValid(), CWallet::mapWallet, CWalletDB::ReadAccount(), CTxOut::scriptPubKey, CWallet::SetAddressBook(), CWallet::strWalletFile, CAccount::vchPubKey, and CWalletDB::WriteAccount().
Referenced by GetAccountAddress().
GetAmounts()
void CWalletTx::GetAmounts (std::list< COutputEntry > & listReceived, std::list< COutputEntry > & listSent, CAmount & nFee, std::string & strSentAccount, const isminefilter & filter) const
Definition at line 1794 of file wallet.cpp.
References ExtractDestination(), CWalletTx::GetDebit(), CMerkleTx::GetHash(), CWallet::IsChange(), CWallet::IsMine(), CScript::IsUnspendable(), LogPrintf, CTxOut::nValue, CWalletTx::pwallet, CTxOut::scriptPubKey, CWalletTx::strFromAccount, and CMerkleTx::tx.
Referenced by CWalletTx::GetAccountAmounts(), getbalance(), listaccounts(), and ListTransactions().
GetAnonymizedCredit()
CAmount CWalletTx::GetAnonymizedCredit (bool fUseCache = true) const
Definition at line 2163 of file wallet.cpp.
References CWalletTx::fAnonymizedCreditCached, CMerkleTx::GetBlocksToMaturity(), CWallet::GetCappedOutpointPrivateSendRounds(), CWallet::GetCredit(), CMerkleTx::GetHash(), CMerkleTx::IsCoinBase(), CWallet::IsDenominated(), ISMINE_SPENDABLE, CWallet::IsSpent(), MoneyRange(), CWalletTx::nAnonymizedCreditCached, CPrivateSendClientManager::nPrivateSendRounds, privateSendClient, CWalletTx::pwallet, and CMerkleTx::tx.
GetAvailableCredit()
CAmount CWalletTx::GetAvailableCredit (bool fUseCache = true) const
Definition at line 2090 of file wallet.cpp.
References CWalletTx::fAvailableCreditCached, CMerkleTx::GetBlocksToMaturity(), CWallet::GetCredit(), CMerkleTx::GetHash(), CMerkleTx::IsCoinBase(), ISMINE_SPENDABLE, CWallet::IsSpent(), MoneyRange(), CWalletTx::nAvailableCreditCached, CWalletTx::pwallet, and CMerkleTx::tx.
Referenced by CWallet::GetBalance(), and CWallet::GetUnconfirmedBalance().
GetAvailableWatchOnlyCredit()
CAmount CWalletTx::GetAvailableWatchOnlyCredit (const bool & fUseCache = true) const
Definition at line 2134 of file wallet.cpp.
References CWalletTx::fAvailableWatchCreditCached, CMerkleTx::GetBlocksToMaturity(), CWallet::GetCredit(), CMerkleTx::GetHash(), CMerkleTx::IsCoinBase(), ISMINE_WATCH_ONLY, CWallet::IsSpent(), MoneyRange(), CWalletTx::nAvailableWatchCreditCached, CWalletTx::pwallet, and CMerkleTx::tx.
Referenced by CWallet::GetUnconfirmedWatchOnlyBalance(), and CWallet::GetWatchOnlyBalance().
GetCappedOutpointPrivateSendRounds()
int CWallet::GetCappedOutpointPrivateSendRounds (const COutPoint & outpoint) const
Definition at line 1517 of file wallet.cpp.
References CWallet::cs_wallet, CWallet::GetRealOutpointPrivateSendRounds(), LOCK, CPrivateSendClientManager::nPrivateSendRounds, and privateSendClient.
Referenced by CWalletTx::GetAnonymizedCredit(), CWallet::GetAverageAnonymizedRounds(), CWallet::GetNormalizedAnonymizedBalance(), listunspent(), CWallet::SelectCoins(), CWallet::SelectCoinsGroupedByAddresses(), and CWallet::SelectPrivateCoins().
GetChange() [1/3]
CAmount CWalletTx::GetChange () const
Definition at line 2242 of file wallet.cpp.
References CWalletTx::fChangeCached, CWallet::GetChange(), CWalletTx::nChangeCached, and CWalletTx::pwallet.
Referenced by TransactionRecord::decomposeTransaction(), and TransactionDesc::toHTML().
GetChange() [2/3]
CAmount CWallet::GetChange (const CTxOut & txout) const
Definition at line 1573 of file wallet.cpp.
References CWallet::IsChange(), MoneyRange(), and CTxOut::nValue.
Referenced by CWalletTx::GetChange(), and CWallet::GetChange().
GetChange() [3/3]
CAmount CWallet::GetChange (const CTransaction & tx) const
Definition at line 1737 of file wallet.cpp.
References CWallet::GetChange(), MoneyRange(), and CTransaction::vout.
GetConflicts() [1/2]
std::set< uint256 > CWalletTx::GetConflicts () const
Definition at line 2000 of file wallet.cpp.
References CWallet::GetConflicts(), CMerkleTx::GetHash(), and CWalletTx::pwallet.
Referenced by WalletTxToJSON().
GetConflicts() [2/2]
std::set< uint256 > CWallet::GetConflicts (const uint256 & txid) const
Get wallet transactions that conflict with given transaction (spend same outputs)
Definition at line 586 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, CWallet::mapTxSpends, CWallet::mapWallet, CTxIn::prevout, and CMerkleTx::tx.
Referenced by CWalletTx::GetConflicts().
GetCredit() [1/3]
CAmount CWalletTx::GetCredit (const isminefilter & filter) const
Definition at line 2043 of file wallet.cpp.
References CWalletTx::fCreditCached, CWalletTx::fWatchCreditCached, CMerkleTx::GetBlocksToMaturity(), CWallet::GetCredit(), CMerkleTx::IsCoinBase(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, CWalletTx::nCreditCached, CWalletTx::nWatchCreditCached, and CWalletTx::pwallet.
Referenced by TransactionRecord::decomposeTransaction(), gettransaction(), and TransactionDesc::toHTML().
GetCredit() [2/3]
CAmount CWallet::GetCredit (const CTxOut & txout, const isminefilter & filter) const
Definition at line 1544 of file wallet.cpp.
References CWallet::IsMine(), MoneyRange(), and CTxOut::nValue.
Referenced by CWalletTx::GetAnonymizedCredit(), CWalletTx::GetAvailableCredit(), CWalletTx::GetAvailableWatchOnlyCredit(), CWalletTx::GetCredit(), CWallet::GetCredit(), CWalletTx::GetDenominatedCredit(), CWalletTx::GetImmatureCredit(), CWalletTx::GetImmatureWatchOnlyCredit(), and TransactionDesc::toHTML().
GetCredit() [3/3]
CAmount CWallet::GetCredit (const CTransaction & tx, const isminefilter & filter) const
Definition at line 1725 of file wallet.cpp.
References CWallet::GetCredit(), MoneyRange(), and CTransaction::vout.
GetDebit() [1/3]
CAmount CWalletTx::GetDebit (const isminefilter & filter) const
filter decides which addresses will count towards the debit
Definition at line 2012 of file wallet.cpp.
References CWalletTx::fDebitCached, CWalletTx::fWatchDebitCached, CWallet::GetDebit(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, CWalletTx::nDebitCached, CWalletTx::nWatchDebitCached, CWalletTx::pwallet, and CMerkleTx::tx.
Referenced by TransactionRecord::decomposeTransaction(), CWalletTx::GetAmounts(), gettransaction(), CWalletTx::IsFromMe(), and TransactionDesc::toHTML().
GetDebit() [2/3]
CAmount CWallet::GetDebit (const CTxIn & txin, const isminefilter & filter) const
Returns amount of debit if the input matches the filter, otherwise returns 0.
Definition at line 1418 of file wallet.cpp.
References CWallet::cs_wallet, COutPoint::hash, CWallet::IsMine(), LOCK, CWallet::mapWallet, COutPoint::n, CTxIn::prevout, and CMerkleTx::tx.
Referenced by CWalletTx::GetDebit(), CWallet::GetDebit(), CWallet::IsFromMe(), and TransactionDesc::toHTML().
GetDebit() [3/3]
CAmount CWallet::GetDebit (const CTransaction & tx, const isminefilter & filter) const
Definition at line 1692 of file wallet.cpp.
References CWallet::GetDebit(), MoneyRange(), and CTransaction::vin.
GetDecryptedHDChain()
bool CWallet::GetDecryptedHDChain (CHDChain & hdChainRet)
Definition at line 1652 of file wallet.cpp.
References CWallet::cs_wallet, CCryptoKeyStore::DecryptHDChain(), CCryptoKeyStore::GetHDChain(), CHDChain::GetID(), CHDChain::GetSeedHash(), and LOCK.
Referenced by dumphdinfo(), and dumpwallet().
GetDenominatedCredit()
CAmount CWalletTx::GetDenominatedCredit (bool unconfirmed, bool fUseCache = true) const
Definition at line 2197 of file wallet.cpp.
References CWalletTx::fDenomConfCreditCached, CWalletTx::fDenomUnconfCreditCached, CMerkleTx::GetBlocksToMaturity(), CWallet::GetCredit(), CMerkleTx::GetDepthInMainChain(), CMerkleTx::GetHash(), CMerkleTx::IsCoinBase(), CPrivateSend::IsDenominatedAmount(), ISMINE_SPENDABLE, CWallet::IsSpent(), CWalletTx::IsTrusted(), MoneyRange(), CWalletTx::nDenomConfCreditCached, CWalletTx::nDenomUnconfCreditCached, CWalletTx::pwallet, and CMerkleTx::tx.
Referenced by CWallet::GetDenominatedBalance().
GetImmatureCredit()
CAmount CWalletTx::GetImmatureCredit (bool fUseCache = true) const
Definition at line 2076 of file wallet.cpp.
References CWalletTx::fImmatureCreditCached, CMerkleTx::GetBlocksToMaturity(), CWallet::GetCredit(), CMerkleTx::IsCoinBase(), CMerkleTx::IsInMainChain(), ISMINE_SPENDABLE, CWalletTx::nImmatureCreditCached, and CWalletTx::pwallet.
Referenced by CWallet::GetImmatureBalance().
GetImmatureWatchOnlyCredit()
CAmount CWalletTx::GetImmatureWatchOnlyCredit (const bool & fUseCache = true) const
Definition at line 2120 of file wallet.cpp.
References CWalletTx::fImmatureWatchCreditCached, CMerkleTx::GetBlocksToMaturity(), CWallet::GetCredit(), CMerkleTx::IsCoinBase(), CMerkleTx::IsInMainChain(), ISMINE_WATCH_ONLY, CWalletTx::nImmatureWatchCreditCached, and CWalletTx::pwallet.
Referenced by CWallet::GetImmatureWatchOnlyBalance().
GetKey()
bool CWallet::GetKey (const CKeyID & address, CKey & keyOut) const override virtual
GetKey implementation that can derive a HD private key on the fly.
Reimplemented from CCryptoKeyStore.
Definition at line 219 of file wallet.cpp.
References CWallet::cs_wallet, CCryptoKeyStore::DecryptHDChain(), CHDChain::DeriveChildExtKey(), CHDPubKey::extPubKey, CCryptoKeyStore::GetHDChain(), CHDChain::GetID(), CCryptoKeyStore::GetKey(), CHDChain::GetSeedHash(), CExtKey::key, LOCK, CWallet::mapHdPubKeys, CHDPubKey::nAccountIndex, CHDPubKey::nChangeIndex, and CExtPubKey::nChild.
Referenced by dumpprivkey(), dumpwallet(), CWallet::GetOutpointAndKeysFromOutput(), WalletModel::getPrivKey(), gobject_vote_alias(), gobject_vote_many(), ParsePrivKey(), and signmessage().
GetPubKey()
bool CWallet::GetPubKey (const CKeyID & address, CPubKey & vchPubKeyOut) const override virtual
GetPubKey implementation that also checks the mapHdPubKeys.
Reimplemented from CCryptoKeyStore.
Definition at line 205 of file wallet.cpp.
References CWallet::cs_wallet, CHDPubKey::extPubKey, CCryptoKeyStore::GetPubKey(), LOCK, CWallet::mapHdPubKeys, and CExtPubKey::pubkey.
Referenced by _createmultisig_redeemScript(), and WalletModel::getPubKey().
GetRealOutpointPrivateSendRounds()
int CWallet::GetRealOutpointPrivateSendRounds (const COutPoint & outpoint, int nRounds = 0) const
Definition at line 1435 of file wallet.cpp.
References CWallet::GetWalletTx(), COutPoint::hash, CPrivateSend::IsCollateralAmount(), CPrivateSend::IsDenominatedAmount(), CWallet::IsMine(), LogPrint, MAX_PRIVATESEND_ROUNDS, COutPoint::n, base_blob< BITS >::ToString(), and CMerkleTx::tx.
Referenced by CWallet::GetCappedOutpointPrivateSendRounds(), CWallet::SelectCoins(), CWallet::SelectCoinsMinConf(), CWallet::SelectPSInOutPairsByDenominations(), CoinControlDialog::updateView(), and CoinControlDialog::viewItemChanged().
GetRequestCount()
int CWalletTx::GetRequestCount () const
Definition at line 1755 of file wallet.cpp.
References CWallet::cs_wallet, CMerkleTx::GetHash(), CMerkleTx::hashBlock, CMerkleTx::hashUnset(), CMerkleTx::IsCoinBase(), LOCK, CWallet::mapRequestCount, and CWalletTx::pwallet.
Referenced by TransactionDesc::FormatTxStatus(), TransactionDesc::toHTML(), and TransactionRecord::updateStatus().
GetTxTime()
int64_t CWalletTx::GetTxTime () const
Definition at line 1749 of file wallet.cpp.
References CWalletTx::nTimeReceived, and CWalletTx::nTimeSmart.
Referenced by TransactionRecord::decomposeTransaction(), TransactionDesc::toHTML(), CoinControlDialog::updateView(), and WalletTxToJSON().
GetWalletTx()
const CWalletTx * CWallet::GetWalletTx (const uint256 & hash) const
Definition at line 99 of file wallet.cpp.
References CWallet::cs_wallet, LOCK, and CWallet::mapWallet.
Referenced by BOOST_FIXTURE_TEST_CASE(), CWallet::GetRealOutpointPrivateSendRounds(), CWalletTx::IsTrusted(), and WalletModel::transactionCanBeAbandoned().
HaveKey()
bool CWallet::HaveKey (const CKeyID & address) const override virtual
HaveKey implementation that also checks the mapHdPubKeys.
Reimplemented from CCryptoKeyStore.
Definition at line 247 of file wallet.cpp.
References CWallet::cs_wallet, CCryptoKeyStore::HaveKey(), LOCK, and CWallet::mapHdPubKeys.
Referenced by CheckWalletOwnsKey(), CheckWalletOwnsScript(), CWallet::DeriveNewChildKey(), CWallet::GetAllReserveKeys(), WalletModel::havePrivKey(), importelectrumwallet(), importprivkey(), importwallet(), ProcessImport(), CWallet::ReserveKeyFromKeyPool(), and MasternodeList::updateDIP3List().
IncOrderPosNext()
int64_t CWallet::IncOrderPosNext (CWalletDB * pwalletdb = NULL)
Increment the next transaction order id.
Returns
next transaction order id
Definition at line 963 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, CWallet::nOrderPosNext, CWallet::strWalletFile, and CWalletDB::WriteOrderPosNext().
Referenced by CWallet::AccountMove(), CWallet::AddToWallet(), and BOOST_AUTO_TEST_CASE().
InMempool()
bool CWalletTx::InMempool () const
Definition at line 2251 of file wallet.cpp.
References CTxMemPool::cs, CTxMemPool::exists(), CMerkleTx::GetHash(), LOCK, and mempool.
Referenced by CWallet::AvailableCoins(), TransactionDesc::FormatTxStatus(), CWallet::GetUnconfirmedBalance(), CWallet::GetUnconfirmedWatchOnlyBalance(), CWalletTx::IsTrusted(), CWalletTx::RelayWalletTransaction(), and WalletModel::transactionCanBeAbandoned().
IsAllFromMe()
bool CWallet::IsAllFromMe (const CTransaction & tx, const isminefilter & filter) const
Returns whether all of the inputs match the filter.
Definition at line 1704 of file wallet.cpp.
References CWallet::cs_wallet, COutPoint::hash, CWallet::IsMine(), LOCK, CWallet::mapWallet, COutPoint::n, CTxIn::prevout, CMerkleTx::tx, and CTransaction::vin.
IsChange()
bool CWallet::IsChange (const CTxOut & txout) const
Definition at line 1551 of file wallet.cpp.
References CWallet::cs_wallet, ExtractDestination(), CWallet::IsMine(), LOCK, CWallet::mapAddressBook, and CTxOut::scriptPubKey.
Referenced by CWallet::GetAddressGroupings(), CWalletTx::GetAmounts(), CWallet::GetChange(), and WalletModel::listCoins().
IsDenominated()
bool CWallet::IsDenominated (const COutPoint & outpoint) const
Definition at line 1524 of file wallet.cpp.
References CWallet::cs_wallet, COutPoint::hash, CPrivateSend::IsDenominatedAmount(), LOCK, CWallet::mapWallet, COutPoint::n, and CMerkleTx::tx.
Referenced by CWallet::CountInputsWithAmount(), TransactionRecord::decomposeTransaction(), CWalletTx::GetAnonymizedCredit(), CWallet::GetAverageAnonymizedRounds(), and CWallet::GetNormalizedAnonymizedBalance().
IsEquivalentTo()
bool CWalletTx::IsEquivalentTo (const CWalletTx & tx) const
Definition at line 2293 of file wallet.cpp.
References CMerkleTx::tx, and CMutableTransaction::vin.
Referenced by CWallet::SyncMetaData().
IsFromMe()
bool CWallet::IsFromMe (const CTransaction & tx) const
should probably be renamed to IsRelevantToMe
Definition at line 1687 of file wallet.cpp.
References CWallet::GetDebit(), and ISMINE_ALL.
Referenced by CWallet::AddToWalletIfInvolvingMe().
IsHDEnabled()
bool CWallet::IsHDEnabled ()
HD Wallet Functions.
Definition at line 1673 of file wallet.cpp.
References CCryptoKeyStore::GetHDChain().
Referenced by CWallet::CreateWalletFromFile(), CWallet::EncryptWallet(), CWallet::GenerateNewKey(), WalletModel::hdEnabled(), keypoolrefill(), CWallet::ReserveKeyFromKeyPool(), and CWallet::TopUpKeyPool().
IsMine() [1/3]
isminetype CWallet::IsMine (const CTxIn & txin) const
Definition at line 1401 of file wallet.cpp.
References CWallet::cs_wallet, COutPoint::hash, ISMINE_NO, LOCK, CWallet::mapWallet, COutPoint::n, CTxIn::prevout, and CMerkleTx::tx.
Referenced by CWallet::AddToWallet(), CWallet::AddToWalletIfInvolvingMe(), AppInitMain(), CWallet::AutoLockMasternodeCollaterals(), CWallet::AvailableCoins(), CWallet::CountInputsWithAmount(), TransactionRecord::decomposeTransaction(), CWallet::DelAddressBook(), CWallet::GetAddressBalances(), CWallet::GetAddressGroupings(), CWalletTx::GetAmounts(), CWallet::GetCredit(), CWallet::GetDebit(), CWallet::GetRealOutpointPrivateSendRounds(), importprunedfunds(), CWallet::IsAllFromMe(), CWallet::IsChange(), CWallet::IsMine(), CWalletTx::IsTrusted(), WalletModel::listCoins(), CWallet::LoadWallet(), CWallet::SelectCoinsGroupedByAddresses(), CWallet::SetAddressBook(), and TransactionDesc::toHTML().
IsMine() [2/3]
isminetype CWallet::IsMine (const CTxOut & txout) const
Definition at line 1539 of file wallet.cpp.
References IsMine(), and CTxOut::scriptPubKey.
IsMine() [3/3]
bool CWallet::IsMine (const CTransaction & tx) const
Definition at line 1679 of file wallet.cpp.
References CWallet::IsMine(), and CTransaction::vout.
IsSpent()
bool CWallet::IsSpent (const uint256 & hash, unsigned int n) const
Outpoint is spent if any non-conflicted transaction spends it:
Definition at line 714 of file wallet.cpp.
References CWallet::mapTxSpends, and CWallet::mapWallet.
Referenced by CWallet::AddToWallet(), CWallet::AutoLockMasternodeCollaterals(), CWallet::AvailableCoins(), CWallet::CountInputsWithAmount(), CWallet::GetAddressBalances(), CWalletTx::GetAnonymizedCredit(), CWalletTx::GetAvailableCredit(), CWalletTx::GetAvailableWatchOnlyCredit(), CWalletTx::GetDenominatedCredit(), WalletModel::isSpent(), CWallet::LoadWallet(), and CWallet::SelectCoinsGroupedByAddresses().
IsTrusted()
bool CWalletTx::IsTrusted () const
Definition at line 2260 of file wallet.cpp.
References bSpendZeroConfChange, CheckFinalTx(), CMerkleTx::GetDepthInMainChain(), CWallet::GetWalletTx(), COutPoint::hash, CWalletTx::InMempool(), CWalletTx::IsFromMe(), CMerkleTx::IsLockedByInstantSend(), CWallet::IsMine(), ISMINE_ALL, ISMINE_SPENDABLE, COutPoint::n, CTxIn::prevout, CWalletTx::pwallet, and CMerkleTx::tx.
Referenced by CWallet::AvailableCoins(), CWallet::CountInputsWithAmount(), CWallet::GetAddressBalances(), CWallet::GetBalance(), CWalletTx::GetDenominatedCredit(), CWallet::GetUnconfirmedBalance(), CWallet::GetUnconfirmedWatchOnlyBalance(), CWallet::GetWatchOnlyBalance(), CWallet::SelectCoinsGroupedByAddresses(), TransactionRecord::updateStatus(), and WalletTxToJSON().
LoadCryptedKey()
bool CWallet::LoadCryptedKey (const CPubKey & vchPubKey, const std::vector< unsigned char > & vchCryptedSecret)
Adds an encrypted key to the store, without saving it to disk (used by LoadWallet)
Definition at line 345 of file wallet.cpp.
References CCryptoKeyStore::AddCryptedKey().
Referenced by ReadKeyValue().
LoadCScript()
bool CWallet::LoadCScript (const CScript & redeemScript)
Definition at line 371 of file wallet.cpp.
References CBasicKeyStore::AddCScript(), LogPrintf, MAX_SCRIPT_ELEMENT_SIZE, prevector< N, T, Size, Diff >::size(), and CBase58Data::ToString().
Referenced by ReadKeyValue().
LoadHDPubKey()
bool CWallet::LoadHDPubKey (const CHDPubKey & hdPubKey)
loads a HDPubKey into the wallets memory
Definition at line 255 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, CHDPubKey::extPubKey, CPubKey::GetID(), CWallet::mapHdPubKeys, and CExtPubKey::pubkey.
Referenced by ReadKeyValue().
LoadKeyMetadata()
bool CWallet::LoadKeyMetadata (const CTxDestination & pubKey, const CKeyMetadata & metadata)
Load metadata (used by LoadWallet)
Definition at line 337 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, CWallet::mapKeyMetadata, CKeyMetadata::nCreateTime, and CWallet::UpdateTimeFirstKey().
Referenced by ReadKeyValue().
LoadToWallet()
bool CWallet::LoadToWallet (const CWalletTx & wtxIn)
Definition at line 1190 of file wallet.cpp.
References CWallet::AddToSpends(), CWalletTx::BindWallet(), CMerkleTx::GetHash(), COutPoint::hash, CMerkleTx::hashBlock, CMerkleTx::hashUnset(), CWallet::mapWallet, CWallet::MarkConflicted(), CMerkleTx::nIndex, CWalletTx::nOrderPos, CTxIn::prevout, CMerkleTx::tx, and CWallet::wtxOrdered.
Referenced by ReadKeyValue().
LoadWatchOnly()
bool CWallet::LoadWatchOnly (const CScript & dest)
Adds a watch-only address to the store, without saving it to disk (used by LoadWallet)
Definition at line 419 of file wallet.cpp.
References CBasicKeyStore::AddWatchOnly().
Referenced by ReadKeyValue().
MarkConflicted()
void CWallet::MarkConflicted (const uint256 & hashBlock, const uint256 & hashTx) private
Definition at line 1318 of file wallet.cpp.
References base_blob< BITS >::begin(), chainActive, CChain::Contains(), cs_main, CWallet::cs_wallet, CWallet::fAnonymizableTallyCached, CWallet::fAnonymizableTallyCachedNonDenom, COutPoint::hash, CChain::Height(), LOCK2, mapBlockIndex, CWallet::mapTxSpends, CWallet::mapWallet, CBlockIndex::nHeight, CTxIn::prevout, CWallet::strWalletFile, and CWalletDB::WriteTx().
Referenced by CWallet::AddToWalletIfInvolvingMe(), and CWallet::LoadToWallet().
MarkDirty()
void CWallet::MarkDirty ()
Definition at line 1047 of file wallet.cpp.
References CWallet::cs_wallet, CWallet::fAnonymizableTallyCached, CWallet::fAnonymizableTallyCachedNonDenom, LOCK, CWallet::mapWallet, CWalletTx::MarkDirty(), and PAIRTYPE.
Referenced by importprivkey(), ImportScript(), importwallet(), OptionsDialog::on_okButton_clicked(), ProcessImport(), and CWallet::ZapSelectTx().
Priority()
int COutput::Priority () const
Definition at line 87 of file wallet.cpp.
References COIN, CPrivateSend::GetStandardDenominations(), COutput::i, CMerkleTx::tx, and COutput::tx.
Referenced by CompareByPriority::operator()().
ReacceptWalletTransactions()
void CWallet::ReacceptWalletTransactions ()
Definition at line 1939 of file wallet.cpp.
References CMerkleTx::AcceptToMemoryPool(), CTxMemPool::cs, cs_main, CWallet::cs_wallet, CWallet::fBroadcastTransactions, CMerkleTx::GetDepthInMainChain(), CMerkleTx::GetHash(), CMerkleTx::isAbandoned(), CMerkleTx::IsCoinBase(), CMerkleTx::IsLockedByInstantSend(), LOCK, LOCK2, CWallet::mapWallet, maxTxFee, mempool, CWalletTx::nOrderPos, and PAIRTYPE.
Referenced by importaddress(), importmulti(), importpubkey(), and CWallet::postInitProcess().
RelayWalletTransaction()
bool CWalletTx::RelayWalletTransaction (CConnman * connman, const std::string & strCommand = "tx")
Definition at line 1972 of file wallet.cpp.
References CInstantSend::AcceptLockRequest(), CMerkleTx::AcceptToMemoryPool(), CInstantSend::CanAutoLock(), CWallet::GetBroadcastTransactions(), CMerkleTx::GetDepthInMainChain(), CMerkleTx::GetHash(), CWalletTx::InMempool(), instantsend, CMerkleTx::isAbandoned(), CMerkleTx::IsCoinBase(), CTxLockRequest::IsSimple(), LogPrintf, maxTxFee, CInstantSend::ProcessTxLockRequest(), CWalletTx::pwallet, CInstantSend::RejectLockRequest(), CConnman::RelayTransaction(), base_blob< BITS >::ToString(), and NetMsgType::TXLOCKREQUEST.
Referenced by CWallet::CommitTransaction(), and CWallet::ResendWalletTransactionsBefore().
RemoveWatchOnly()
bool CWallet::RemoveWatchOnly (const CScript & dest) override virtual
Reimplemented from CBasicKeyStore.
Definition at line 405 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, CWallet::fFileBacked, CBasicKeyStore::HaveWatchOnly(), CWallet::NotifyWatchonlyChanged, CBasicKeyStore::RemoveWatchOnly(), and CWallet::strWalletFile.
Referenced by CWallet::AddHDPubKey(), and CWallet::AddKeyPubKey().
ReorderTransactions()
DBErrors CWallet::ReorderTransactions ()
Definition at line 886 of file wallet.cpp.
References CWallet::cs_wallet, DB_LOAD_FAIL, DB_LOAD_OK, CWalletDB::ListAccountCreditDebit(), LOCK, CWallet::mapWallet, CAccountingEntry::nEntryNo, CWalletTx::nOrderPos, CAccountingEntry::nOrderPos, CWallet::nOrderPosNext, CAccountingEntry::nTime, CWalletTx::nTimeReceived, CWallet::strWalletFile, CWalletDB::WriteAccountingEntry(), CWalletDB::WriteOrderPosNext(), and CWalletDB::WriteTx().
Referenced by GetResults(), and CWalletDB::LoadWallet().
ResendWalletTransactions()
void CWallet::ResendWalletTransactions (int64_t nBestBlockTime, CConnman * connman) override virtual
Reimplemented from CValidationInterface.
Definition at line 2326 of file wallet.cpp.
References CWallet::fBroadcastTransactions, GetRand(), GetTime(), LogPrintf, CWallet::nLastResend, CWallet::nNextResend, and CWallet::ResendWalletTransactionsBefore().
ResendWalletTransactionsBefore()
std::vector< uint256 > CWallet::ResendWalletTransactionsBefore (int64_t nTime, CConnman * connman)
Definition at line 2302 of file wallet.cpp.
References CWallet::cs_wallet, CMerkleTx::GetHash(), LOCK, CWallet::mapWallet, CWalletTx::nTimeReceived, PAIRTYPE, and CWalletTx::RelayWalletTransaction().
Referenced by CWallet::ResendWalletTransactions(), and resendwallettransactions().
ScanForWalletTransactions()
CBlockIndex * CWallet::ScanForWalletTransactions (CBlockIndex * pindexStart, bool fUpdate = false)
Scan the block chain (starting in pindexStart) for transactions from or to us.
If fUpdate is true, found transactions that already exist in the wallet will be updated.
Returns pointer to the first block in the last contiguous range that was successfully scanned.
Definition at line 1894 of file wallet.cpp.
References _(), CWallet::AddToWalletIfInvolvingMe(), chainActive, cs_main, CWallet::cs_wallet, CBlockIndex::GetBlockTime(), GetTime(), GuessVerificationProgress(), LOCK2, LogPrintf, CChain::Next(), CBlockIndex::nHeight, CWallet::nTimeFirstKey, Params(), ReadBlockFromDisk(), CWallet::ShowProgress, CChain::Tip(), CChainParams::TxData(), and CBlock::vtx.
Referenced by BOOST_FIXTURE_TEST_CASE(), CWallet::CreateWalletFromFile(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importpubkey(), and importwallet().
SetBestChain()
void CWallet::SetBestChain (const CBlockLocator & loc) override virtual
Reimplemented from CValidationInterface.
Definition at line 541 of file wallet.cpp.
References CWallet::strWalletFile, and CWalletDB::WriteBestBlock().
Referenced by CWallet::CreateWalletFromFile().
SetCryptedHDChain()
bool CWallet::SetCryptedHDChain (const CHDChain & chain, bool memonly)
Definition at line 1630 of file wallet.cpp.
References CWallet::cs_wallet, CWallet::fFileBacked, LOCK, CWallet::pwalletdbEncryption, CCryptoKeyStore::SetCryptedHDChain(), CWallet::strWalletFile, and CWalletDB::WriteCryptedHDChain().
Referenced by CWallet::DeriveNewChildKey(), CWallet::EncryptWallet(), and ReadKeyValue().
SetHDChain()
bool CWallet::SetHDChain (const CHDChain & chain, bool memonly)
Definition at line 1617 of file wallet.cpp.
References CWallet::cs_wallet, LOCK, CCryptoKeyStore::SetHDChain(), and CWallet::strWalletFile.
Referenced by CWallet::DeriveNewChildKey(), CWallet::GenerateNewHDChain(), and ReadKeyValue().
SetMaxVersion()
bool CWallet::SetMaxVersion (int nVersion)
change which version we're allowed to upgrade to (note that this does not immediately imply upgrading to that format)
Definition at line 574 of file wallet.cpp.
References CWallet::cs_wallet, LOCK, CWallet::nWalletMaxVersion, and CWallet::nWalletVersion.
Referenced by CWallet::CreateWalletFromFile().
SetMinVersion()
bool CWallet::SetMinVersion (enum WalletFeature nVersion, CWalletDB * pwalletdbIn = NULL, bool fExplicit = false)
signify that a particular wallet feature is now used. this may change nWalletVersion and nWalletMaxVersion if those are lower
Definition at line 547 of file wallet.cpp.
References CWallet::cs_wallet, FEATURE_LATEST, CWallet::fFileBacked, LOCK, CWallet::nWalletMaxVersion, CWallet::nWalletVersion, CWallet::strWalletFile, and CWalletDB::WriteMinVersion().
Referenced by CWallet::CreateWalletFromFile(), CWallet::EncryptWallet(), and CWallet::GenerateNewKey().
SyncMetaData()
void CWallet::SyncMetaData (std::pair< TxSpends::iterator, TxSpends::iterator > range) private
Definition at line 673 of file wallet.cpp.
References CWalletTx::fFromMe, CWalletTx::IsEquivalentTo(), CWalletTx::mapValue, CWallet::mapWallet, CWalletTx::nTimeSmart, CWalletTx::strFromAccount, and CWalletTx::vOrderForm.
Referenced by CWallet::AddToSpends().
SyncTransaction()
void CWallet::SyncTransaction (const CTransaction & tx, const CBlockIndex * pindex, int posInBlock) override virtual
Reimplemented from CValidationInterface.
Definition at line 1380 of file wallet.cpp.
References CWallet::AddToWalletIfInvolvingMe(), cs_main, CWallet::cs_wallet, CWallet::fAnonymizableTallyCached, CWallet::fAnonymizableTallyCachedNonDenom, COutPoint::hash, LOCK2, CWallet::mapWallet, CTxIn::prevout, and CTransaction::vin.
ToString()
std::string COutput::ToString () const
Definition at line 82 of file wallet.cpp.
References FormatMoney(), CMerkleTx::GetHash(), COutput::i, COutput::nDepth, strprintf, base_blob< BITS >::ToString(), CMerkleTx::tx, and COutput::tx.
Unlock()
bool CWallet::Unlock (const SecureString & strWalletPassphrase, bool fForMixingOnly = false)
Definition at line 424 of file wallet.cpp.
References CWallet::cs_wallet, CCrypter::Decrypt(), GetArg(), GetBoolArg(), CCryptoKeyStore::IsLocked(), keePassInt, LOCK, LogPrintf, CWallet::mapMasterKeys, nWalletBackups, CKeePassIntegrator::retrievePassphrase(), CCrypter::SetKeyFromPassphrase(), CWallet::TopUpKeyPool(), CCryptoKeyStore::Unlock(), and CCryptoKeyStore::vMasterKey.
Referenced by CWallet::EncryptWallet(), WalletModel::setWalletLocked(), and walletpassphrase().
UpdateTimeFirstKey()
void CWallet::UpdateTimeFirstKey (int64_t nCreateTime)
Definition at line 350 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, and CWallet::nTimeFirstKey.
Referenced by CWallet::AddWatchOnly(), CWallet::DeriveNewChildKey(), CWallet::GenerateNewKey(), importelectrumwallet(), importprivkey(), importwallet(), CWallet::LoadKeyMetadata(), CWalletDB::LoadWallet(), and ProcessImport().
Verify()
bool CWallet::Verify () static
Verify the wallet database and perform salvage if required.
Definition at line 614 of file wallet.cpp.
References _(), bitdb, DEFAULT_DISABLE_WALLET, DEFAULT_WALLET_DAT, GetArg(), GetBoolArg(), GetDataDir(), GetTime(), InitError(), CClientUIInterface::InitMessage, InitWarning(), LogPrintf, CDBEnv::Open(), CWalletDB::Recover(), CDBEnv::RECOVER_FAIL, CDBEnv::RECOVER_OK, strprintf, uiInterface, and CDBEnv::Verify().
Referenced by AppInitMain().
Released under the MIT license