Dash Core: Actions
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
Actions
Classes
struct CompareByPriority
Functions
static void ApproximateBestSubset (std::vector< std::pair< CAmount, std::pair< const CWalletTx *, unsigned int > > >vValue, const CAmount &nTotalLower, const CAmount &nTargetValue, std::vector< char > &vfBest, CAmount &nBest, bool fUseInstantSend=false, int iterations=1000)
bool less_then_denom (const COutput &out1, const COutput &out2)
static int64_t GetOldestKeyInPool (const std::set< int64_t > &setKeyPool, CWalletDB &walletdb)
static void LoadReserveKeysToSet (std::set< CKeyID > &setAddress, const std::set< int64_t > &setKeyPool, CWalletDB &walletdb)
CAmount CWallet::GetBalance () const
CAmount CWallet::GetAnonymizableBalance (bool fSkipDenominated=false, bool fSkipUnconfirmed=true) const
CAmount CWallet::GetAnonymizedBalance () const
float CWallet::GetAverageAnonymizedRounds () const
CAmount CWallet::GetNormalizedAnonymizedBalance () const
CAmount CWallet::GetNeedsToBeAnonymizedBalance (CAmount nMinBalance=0) const
CAmount CWallet::GetDenominatedBalance (bool unconfirmed=false) const
CAmount CWallet::GetUnconfirmedBalance () const
CAmount CWallet::GetImmatureBalance () const
CAmount CWallet::GetWatchOnlyBalance () const
CAmount CWallet::GetUnconfirmedWatchOnlyBalance () const
CAmount CWallet::GetImmatureWatchOnlyBalance () const
void CWallet::AvailableCoins (std::vector< COutput > &vCoins, bool fOnlyConfirmed=true, const CCoinControl *coinControl=NULL, bool fIncludeZeroValue=false, AvailableCoinsType nCoinType=ALL_COINS, bool fUseInstantSend=false) const
populate vCoins with vector of available COutputs.
bool CWallet::SelectCoinsMinConf (const CAmount &nTargetValue, int nConfMine, int nConfTheirs, uint64_t nMaxAncestors, std::vector< COutput > vCoins, std::set< std::pair< const CWalletTx *, unsigned int > > &setCoinsRet, CAmount &nValueRet, AvailableCoinsType nCoinType=ALL_COINS, bool fUseInstantSend=false) const
Shuffle and select coins until nTargetValue is reached while avoiding small change; This method is stochastic for some inputs and upon completion the coin set and corresponding actual target value is assembled.
bool CWallet::SelectCoins (const std::vector< COutput > &vAvailableCoins, const CAmount &nTargetValue, std::set< std::pair< const CWalletTx *, unsigned int > > &setCoinsRet, CAmount &nValueRet, const CCoinControl *coinControl=NULL, AvailableCoinsType nCoinType=ALL_COINS, bool fUseInstantSend=true) const
Select a set of coins such that nValueRet >= nTargetValue and at least all coins from coinControl are selected; Never select unconfirmed coins if they are not ours.
bool CWallet::FundTransaction (CMutableTransaction &tx, CAmount &nFeeRet, bool overrideEstimatedFeeRate, const CFeeRate &specificFeeRate, int &nChangePosInOut, std::string &strFailReason, bool includeWatching, bool lockUnspents, const std::set< int > &setSubtractFeeFromOutputs, bool keepReserveKey=true, const CTxDestination &destChange=CNoDestination())
Insert additional inputs into the transaction by calling CreateTransaction();.
bool CWallet::SelectPSInOutPairsByDenominations (int nDenom, CAmount nValueMin, CAmount nValueMax, std::vector< std::pair< CTxDSIn, CTxOut > > &vecPSInOutPairsRet)
bool CWallet::SelectCoinsGroupedByAddresses (std::vector< CompactTallyItem > &vecTallyRet, bool fSkipDenominated=true, bool fAnonymizable=true, bool fSkipUnconfirmed=true, int nMaxOupointsPerAddress=-1) const
bool CWallet::SelectPrivateCoins (CAmount nValueMin, CAmount nValueMax, std::vector< CTxIn > &vecTxInRet, CAmount &nValueRet, int nPrivateSendRoundsMin, int nPrivateSendRoundsMax) const
bool CWallet::GetCollateralTxDSIn (CTxDSIn &txdsinRet, CAmount &nValueRet) const
bool CWallet::GetMasternodeOutpointAndKeys (COutPoint &outpointRet, CPubKey &pubKeyRet, CKey &keyRet, const std::string &strTxHash="", const std::string &strOutputIndex="")
Get 1000DASH output and keys which can be used for the Masternode.
bool CWallet::GetOutpointAndKeysFromOutput (const COutput &out, COutPoint &outpointRet, CPubKey &pubKeyRet, CKey &keyRet)
Extract txin information and keys from output.
int CWallet::CountInputsWithAmount (CAmount nInputAmount)
bool CWallet::HasCollateralInputs (bool fOnlyConfirmed=true) const
bool CWallet::CreateCollateralTransaction (CMutableTransaction &txCollateral, std::string &strReason)
bool CWallet::GetBudgetSystemCollateralTX (CWalletTx &tx, uint256 hash, CAmount amount, bool fUseInstantSend, const COutPoint &outpoint=COutPoint())
bool CWallet::ConvertList (std::vector< CTxIn > vecTxIn, std::vector< CAmount > &vecAmounts)
bool CWallet::CreateTransaction (const std::vector< CRecipient > &vecSend, CWalletTx &wtxNew, CReserveKey &reservekey, CAmount &nFeeRet, int &nChangePosInOut, std::string &strFailReason, const CCoinControl *coinControl=NULL, bool sign=true, AvailableCoinsType nCoinType=ALL_COINS, bool fUseInstantSend=false, int nExtraPayloadSize=0)
Create a new transaction paying the recipients with a set of coins selected by SelectCoins(); Also create the change output, when needed.
bool CWallet::CommitTransaction (CWalletTx &wtxNew, CReserveKey &reservekey, CConnman *connman, CValidationState &state, const std::string &strCommand="tx")
Call after CreateTransaction unless you want to abort.
void CWallet::ListAccountCreditDebit (const std::string &strAccount, std::list< CAccountingEntry > &entries)
bool CWallet::AddAccountingEntry (const CAccountingEntry &)
bool CWallet::AddAccountingEntry (const CAccountingEntry &, CWalletDB *pwalletdb)
static CAmount CWallet::GetRequiredFee (unsigned int nTxBytes)
Return the minimum required fee taking into account the floating relay fee and user set minimum transaction fee.
static CAmount CWallet::GetMinimumFee (unsigned int nTxBytes, unsigned int nConfirmTarget, const CTxMemPool &pool)
Estimate the minimum fee considering user set parameters and the required fee.
static CAmount CWallet::GetMinimumFee (unsigned int nTxBytes, unsigned int nConfirmTarget, const CTxMemPool &pool, CAmount targetFee)
Estimate the minimum fee considering required fee and targetFee or if 0 then fee estimation for nConfirmTarget.
DBErrors CWallet::LoadWallet (bool &fFirstRunRet)
void CWallet::AutoLockMasternodeCollaterals ()
DBErrors CWallet::ZapSelectTx (std::vector< uint256 > &vHashIn, std::vector< uint256 > &vHashOut)
DBErrors CWallet::ZapWalletTx (std::vector< CWalletTx > &vWtx)
bool CWallet::SetAddressBook (const CTxDestination &address, const std::string &strName, const std::string &purpose)
bool CWallet::DelAddressBook (const CTxDestination &address)
bool CWallet::SetDefaultKey (const CPubKey &vchPubKey)
bool CWallet::NewKeyPool ()
Mark old keypool keys as used, and generate all new keys.
size_t CWallet::KeypoolCountExternalKeys ()
size_t CWallet::KeypoolCountInternalKeys ()
bool CWallet::TopUpKeyPool (unsigned int kpSize=0)
void CWallet::ReserveKeyFromKeyPool (int64_t &nIndex, CKeyPool &keypool, bool fInternal)
void CWallet::KeepKey (int64_t nIndex)
void CWallet::ReturnKey (int64_t nIndex, bool fInternal)
bool CWallet::GetKeyFromPool (CPubKey &key, bool fInternal)
int64_t CWallet::GetOldestKeyPoolTime ()
std::map< CTxDestination, CAmount > CWallet::GetAddressBalances ()
std::set< std::set< CTxDestination > > CWallet::GetAddressGroupings ()
CAmount CWallet::GetAccountBalance (const std::string &strAccount, int nMinDepth, const isminefilter &filter, bool fAddLocked)
CAmount CWallet::GetAccountBalance (CWalletDB &walletdb, const std::string &strAccount, int nMinDepth, const isminefilter &filter, bool fAddLocked)
std::set< CTxDestination > CWallet::GetAccountAddresses (const std::string &strAccount) const
bool CReserveKey::GetReservedKey (CPubKey &pubkey, bool fInternalIn)
void CReserveKey::KeepKey ()
void CReserveKey::ReturnKey ()
void CWallet::GetAllReserveKeys (std::set< CKeyID > &setAddress) const
bool CWallet::UpdatedTransaction (const uint256 &hashTx) override
void CWallet::GetScriptForMining (boost::shared_ptr< CReserveScript > &script) override
void CWallet::LockCoin (const COutPoint &output)
void CWallet::UnlockCoin (const COutPoint &output)
void CWallet::UnlockAllCoins ()
bool CWallet::IsLockedCoin (uint256 hash, unsigned int n) const
void CWallet::ListLockedCoins (std::vector< COutPoint > &vOutpts)
void CWallet::ListProTxCoins (std::vector< COutPoint > &vOutpts)
Detailed Description
Function Documentation
AddAccountingEntry() [1/2]
bool CWallet::AddAccountingEntry (const CAccountingEntry & acentry)
Definition at line 3899 of file wallet.cpp.
References CWallet::strWalletFile.
Referenced by CWallet::AccountMove(), and BOOST_AUTO_TEST_CASE().
AddAccountingEntry() [2/2]
bool CWallet::AddAccountingEntry (const CAccountingEntry & acentry, CWalletDB * pwalletdb)
Definition at line 3906 of file wallet.cpp.
References CWallet::laccentries, CAccountingEntry::nOrderPos, CWalletDB::WriteAccountingEntry_Backend(), and CWallet::wtxOrdered.
ApproximateBestSubset()
static void ApproximateBestSubset (std::vector< std::pair< CAmount, std::pair< const CWalletTx *, unsigned int > > > vValue, const CAmount & nTotalLower, const CAmount & nTargetValue, std::vector< char > & vfBest, CAmount & nBest, bool fUseInstantSend = false, int iterations = 1000) static
Definition at line 2643 of file wallet.cpp.
References COIN, CSporkManager::GetSporkValue(), FastRandomContext::rand32(), SPORK_5_INSTANTSEND_MAX_VALUE, and sporkManager.
Referenced by CWallet::SelectCoinsMinConf().
AutoLockMasternodeCollaterals()
void CWallet::AutoLockMasternodeCollaterals ()
Definition at line 3990 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, deterministicMNManager, CDeterministicMNManager::HasMNCollateralAtChainTip(), CWallet::IsMine(), CDeterministicMNManager::IsProTxWithCollateral(), CWallet::IsSpent(), LOCK2, CWallet::LockCoin(), and CWallet::mapWallet.
Referenced by ThreadImport().
AvailableCoins()
void CWallet::AvailableCoins (std::vector< COutput > & vCoins, bool fOnlyConfirmed = true, const CCoinControl * coinControl = NULL, bool fIncludeZeroValue = false, AvailableCoinsType nCoinType = ALL_COINS, bool fUseInstantSend = false) const
populate vCoins with vector of available COutputs.
Definition at line 2581 of file wallet.cpp.
References CheckFinalTx(), COIN, cs_main, CWallet::cs_wallet, CCoinControl::fAllowOtherInputs, CCoinControl::fAllowWatchOnly, CMerkleTx::GetBlocksToMaturity(), CChainParams::GetConsensus(), CMerkleTx::GetDepthInMainChain(), CCoinControl::HasSelected(), CWalletTx::InMempool(), CMerkleTx::IsCoinBase(), CPrivateSend::IsCollateralAmount(), CPrivateSend::IsDenominatedAmount(), CWallet::IsLockedCoin(), CWallet::IsMine(), ISMINE_NO, ISMINE_SPENDABLE, ISMINE_WATCH_SOLVABLE, CCoinControl::IsSelected(), CWallet::IsSpent(), CWalletTx::IsTrusted(), LOCK2, CWallet::mapWallet, Consensus::Params::nInstantSendConfirmationsRequired, ONLY_1000, ONLY_DENOMINATED, ONLY_NONDENOMINATED, ONLY_PRIVATESEND_COLLATERAL, Params(), CMerkleTx::tx, and vCoins.
Referenced by CWallet::CreateTransaction(), WalletModel::getBalance(), CWallet::GetCollateralTxDSIn(), CWallet::GetMasternodeOutpointAndKeys(), CWallet::HasCollateralInputs(), WalletModel::listCoins(), listunspent(), CWallet::SelectPrivateCoins(), and CWallet::SelectPSInOutPairsByDenominations().
CommitTransaction()
bool CWallet::CommitTransaction (CWalletTx & wtxNew, CReserveKey & reservekey, CConnman * connman, CValidationState & state, const std::string & strCommand = "tx")
Call after CreateTransaction unless you want to abort.
Definition at line 3850 of file wallet.cpp.
References CMerkleTx::AcceptToMemoryPool(), CWallet::AddToWallet(), CWalletTx::BindWallet(), cs_main, CWallet::cs_wallet, CT_UPDATED, CWallet::fBroadcastTransactions, CMerkleTx::GetHash(), CValidationState::GetRejectReason(), COutPoint::hash, CReserveKey::KeepKey(), LOCK2, LogPrintf, CWallet::mapRequestCount, CWallet::mapWallet, maxTxFee, CWallet::NotifyTransactionChanged, CTxIn::prevout, CWalletTx::RelayWalletTransaction(), and CMerkleTx::tx.
Referenced by CPrivateSendClientSession::CreateDenominated(), CPrivateSendClientSession::MakeCollateralAmounts(), WalletModel::sendCoins(), sendmany(), and SendMoney().
ConvertList()
bool CWallet::ConvertList (std::vector< CTxIn > vecTxIn, std::vector< CAmount > & vecAmounts)
Definition at line 3392 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, LOCK2, LogPrintf, CWallet::mapWallet, and CMerkleTx::tx.
Referenced by CPrivateSendClientSession::StartNewQueue().
CountInputsWithAmount()
int CWallet::CountInputsWithAmount (CAmount nInputAmount)
Definition at line 3284 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CMerkleTx::GetDepthInMainChain(), CMerkleTx::GetHash(), COutput::i, CWallet::IsDenominated(), CPrivateSend::IsDenominatedAmount(), CWallet::IsMine(), ISMINE_SPENDABLE, CWallet::IsSpent(), CWalletTx::IsTrusted(), LOCK2, CWallet::mapWallet, CMerkleTx::tx, and COutput::tx.
Referenced by CPrivateSendClientSession::CreateDenominated().
CreateCollateralTransaction()
bool CWallet::CreateCollateralTransaction (CMutableTransaction & txCollateral, std::string & strReason)
Definition at line 3320 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CPrivateSend::GetCollateralAmount(), CWallet::GetCollateralTxDSIn(), CPubKey::GetID(), CReserveKey::GetReservedKey(), GetScriptForDestination(), CReserveKey::KeepKey(), LOCK2, OP_RETURN, CTxDSIn::prevPubKey, SignSignature(), CMutableTransaction::vin, and CMutableTransaction::vout.
Referenced by CPrivateSendClientSession::DoAutomaticDenominating().
CreateTransaction()
bool CWallet::CreateTransaction (const std::vector< CRecipient > & vecSend, CWalletTx & wtxNew, CReserveKey & reservekey, CAmount & nFeeRet, int & nChangePosInOut, std::string & strFailReason, const CCoinControl * coinControl = NULL, bool sign = true, AvailableCoinsType nCoinType = ALL_COINS, bool fUseInstantSend = false, int nExtraPayloadSize = 0)
Create a new transaction paying the recipients with a set of coins selected by SelectCoins(); Also create the change output, when needed.
Note
passing nChangePosInOut as -1 will result in setting a random position
Definition at line 3409 of file wallet.cpp.
References _(), AllowFree(), CWallet::AvailableCoins(), bBIP69Enabled, CWalletTx::BindWallet(), CTxMemPool::CalculateMemPoolAncestors(), chainActive, CPrivateSendClientManager::ClearSkippedDenominations(), COIN, CTransaction::ComputePriority(), cs_main, CWallet::cs_wallet, DEFAULT_ANCESTOR_LIMIT, DEFAULT_ANCESTOR_SIZE_LIMIT, DEFAULT_DESCENDANT_LIMIT, DEFAULT_DESCENDANT_SIZE_LIMIT, DEFAULT_WALLET_REJECT_LONG_CHAINS, CCoinControl::destChange, dustRelayFee, CTxMemPool::estimateSmartPriority(), CWalletTx::fFromMe, CCoinControl::fOverrideFeeRate, fSendFreeTransactions, CWalletTx::fTimeReceivedIsTxTime, GetArg(), GetBoolArg(), CChainParams::GetConsensus(), CTxOut::GetDustThreshold(), CFeeRate::GetFee(), CPubKey::GetID(), CTxLockRequest::GetMinFee(), CWallet::GetMinimumFee(), GetRandInt(), CReserveKey::GetReservedKey(), GetScriptForDestination(), GetSerializeSize(), GetSizeOfCompactSize(), CSporkManager::GetSporkValue(), CChain::Height(), CTxOut::IsDust(), LOCK2, LOCKTIME_THRESHOLD, MakeTransactionRef(), CWalletTx::mapValue, MAX_FREE_TRANSACTION_CREATE_SIZE, MAX_STANDARD_TX_SIZE, mempool, MIN_FINAL_CHANGE, minRelayTxFee, CCoinControl::nConfirmTarget, CCoinControl::nFeeRate, Consensus::Params::nInstantSendConfirmationsRequired, CMutableTransaction::nLockTime, CCoinControl::nMinimumTotalFee, nTxConfirmTarget, CTxOut::nValue, ONLY_DENOMINATED, ONLY_NONDENOMINATED, Params(), privateSendClient, ProduceSignature(), PROTOCOL_VERSION, CReserveKey::ReturnKey(), CWallet::SelectCoins(), SER_NETWORK, CMerkleTx::SetTx(), SIGHASH_ALL, SPORK_5_INSTANTSEND_MAX_VALUE, sporkManager, strprintf, CMerkleTx::tx, CMutableTransaction::vin, and CMutableTransaction::vout.
Referenced by CPrivateSendClientSession::CreateDenominated(), CWallet::FundTransaction(), CWallet::GetBudgetSystemCollateralTX(), CPrivateSendClientSession::MakeCollateralAmounts(), WalletModel::prepareTransaction(), sendmany(), and SendMoney().
DelAddressBook()
bool CWallet::DelAddressBook (const CTxDestination & address)
Definition at line 4077 of file wallet.cpp.
References CWallet::cs_wallet, CT_DELETED, CWalletDB::EraseDestData(), CWalletDB::EraseName(), CWalletDB::ErasePurpose(), CWallet::fFileBacked, CWallet::IsMine(), ISMINE_NO, LOCK, CWallet::mapAddressBook, CWallet::NotifyAddressBookChanged, PAIRTYPE, CWallet::strWalletFile, and CBase58Data::ToString().
Referenced by AddressTableModel::removeRows(), and AddressTableModel::setData().
FundTransaction()
bool CWallet::FundTransaction (CMutableTransaction & tx, CAmount & nFeeRet, bool overrideEstimatedFeeRate, const CFeeRate & specificFeeRate, int & nChangePosInOut, std::string & strFailReason, bool includeWatching, bool lockUnspents, const std::set< int > & setSubtractFeeFromOutputs, bool keepReserveKey = true, const CTxDestination & destChange = CNoDestination())
Insert additional inputs into the transaction by calling CreateTransaction();.
Definition at line 2960 of file wallet.cpp.
References ALL_COINS, CWallet::CreateTransaction(), cs_main, CWallet::cs_wallet, CCoinControl::destChange, CCoinControl::fAllowOtherInputs, CCoinControl::fAllowWatchOnly, CCoinControl::fOverrideFeeRate, CCoinControl::IsSelected(), CReserveKey::KeepKey(), LOCK2, CWallet::LockCoin(), CCoinControl::nFeeRate, CMutableTransaction::nType, CTxOut::nValue, CMutableTransaction::nVersion, CTxIn::prevout, CTxOut::scriptPubKey, CCoinControl::Select(), TRANSACTION_NORMAL, CMerkleTx::tx, CMutableTransaction::vExtraPayload, CMutableTransaction::vin, and CMutableTransaction::vout.
Referenced by fundrawtransaction().
GetAccountAddresses()
std::set< CTxDestination > CWallet::GetAccountAddresses (const std::string & strAccount) const
Definition at line 4492 of file wallet.cpp.
References CWallet::cs_wallet, LOCK, CWallet::mapAddressBook, CAddressBookData::name, and PAIRTYPE.
Referenced by PaymentServer::fetchPaymentACK(), and getreceivedbyaccount().
GetAccountBalance() [1/2]
CAmount CWallet::GetAccountBalance (const std::string & strAccount, int nMinDepth, const isminefilter & filter, bool fAddLocked)
Definition at line 4461 of file wallet.cpp.
References CWallet::strWalletFile.
Referenced by getbalance(), sendfrom(), and sendmany().
GetAccountBalance() [2/2]
CAmount CWallet::GetAccountBalance (CWalletDB & walletdb, const std::string & strAccount, int nMinDepth, const isminefilter & filter, bool fAddLocked)
Definition at line 4467 of file wallet.cpp.
References CheckFinalTx(), CWalletTx::GetAccountAmounts(), CWalletDB::GetAccountCreditDebit(), CMerkleTx::GetBlocksToMaturity(), CMerkleTx::GetDepthInMainChain(), CMerkleTx::IsLockedByInstantSend(), and CWallet::mapWallet.
GetAddressBalances()
std::map< CTxDestination, CAmount > CWallet::GetAddressBalances ()
Definition at line 4328 of file wallet.cpp.
References CWallet::cs_wallet, ExtractDestination(), CMerkleTx::GetBlocksToMaturity(), CMerkleTx::GetDepthInMainChain(), CMerkleTx::IsCoinBase(), CWalletTx::IsFromMe(), CMerkleTx::IsLockedByInstantSend(), CWallet::IsMine(), ISMINE_ALL, CWallet::IsSpent(), CWalletTx::IsTrusted(), LOCK, CWallet::mapWallet, PAIRTYPE, and CMerkleTx::tx.
Referenced by listaddressbalances(), and listaddressgroupings().
GetAddressGroupings()
std::set< std::set< CTxDestination > > CWallet::GetAddressGroupings ()
Definition at line 4368 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, ExtractDestination(), COutPoint::hash, CWallet::IsChange(), CWallet::IsMine(), CWallet::mapWallet, COutPoint::n, PAIRTYPE, CTxIn::prevout, CTxOut::scriptPubKey, and CMerkleTx::tx.
Referenced by listaddressgroupings().
GetAllReserveKeys()
void CWallet::GetAllReserveKeys (std::set< CKeyID > & setAddress) const
Definition at line 4556 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CWallet::HaveKey(), LoadReserveKeysToSet(), LOCK2, CWallet::setExternalKeyPool, CWallet::setInternalKeyPool, and CWallet::strWalletFile.
Referenced by dumpwallet().
GetAnonymizableBalance()
CAmount CWallet::GetAnonymizableBalance (bool fSkipDenominated = false, bool fSkipUnconfirmed = true) const
Definition at line 2376 of file wallet.cpp.
References fLiteMode, CPrivateSend::GetCollateralAmount(), CPrivateSend::GetSmallestDenomination(), CPrivateSend::IsDenominatedAmount(), and CWallet::SelectCoinsGroupedByAddresses().
Referenced by CPrivateSendClientSession::DoAutomaticDenominating(), CWallet::GetNeedsToBeAnonymizedBalance(), and OverviewPage::updatePrivateSendProgress().
GetAnonymizedBalance()
CAmount CWallet::GetAnonymizedBalance () const
Definition at line 2398 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, fLiteMode, LOCK2, CWallet::mapWallet, and CWallet::setWalletUTXO.
Referenced by WalletModel::getAnonymizedBalance(), getinfo(), CWallet::GetNeedsToBeAnonymizedBalance(), and getwalletinfo().
GetAverageAnonymizedRounds()
float CWallet::GetAverageAnonymizedRounds () const
Definition at line 2423 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, fLiteMode, CWallet::GetCappedOutpointPrivateSendRounds(), CWallet::IsDenominated(), LOCK2, and CWallet::setWalletUTXO.
Referenced by OverviewPage::updatePrivateSendProgress().
GetBalance()
CAmount CWallet::GetBalance () const
Definition at line 2360 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CWalletTx::GetAvailableCredit(), CWalletTx::IsTrusted(), LOCK2, and CWallet::mapWallet.
Referenced by WalletModel::getBalance(), getbalance(), getinfo(), getwalletinfo(), and SendMoney().
GetBudgetSystemCollateralTX()
bool CWallet::GetBudgetSystemCollateralTX (CWalletTx & tx, uint256 hash, CAmount amount, bool fUseInstantSend, const COutPoint & outpoint = COutPoint())
Definition at line 3364 of file wallet.cpp.
References ALL_COINS, CWallet::CreateTransaction(), COutPoint::IsNull(), LogPrintf, OP_RETURN, CCoinControl::Select(), and ToByteVector().
GetCollateralTxDSIn()
bool CWallet::GetCollateralTxDSIn (CTxDSIn & txdsinRet, CAmount & nValueRet) const
Definition at line 3206 of file wallet.cpp.
References CWallet::AvailableCoins(), cs_main, CWallet::cs_wallet, CPrivateSend::IsCollateralAmount(), LOCK2, and vCoins.
Referenced by CWallet::CreateCollateralTransaction().
GetDenominatedBalance()
CAmount CWallet::GetDenominatedBalance (bool unconfirmed = false) const
Definition at line 2489 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, fLiteMode, CWalletTx::GetDenominatedCredit(), LOCK2, and CWallet::mapWallet.
Referenced by CPrivateSendClientSession::DoAutomaticDenominating(), and OverviewPage::updatePrivateSendProgress().
GetImmatureBalance()
CAmount CWallet::GetImmatureBalance () const
Definition at line 2522 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CWalletTx::GetImmatureCredit(), LOCK2, and CWallet::mapWallet.
Referenced by BOOST_FIXTURE_TEST_CASE(), WalletModel::getImmatureBalance(), and getwalletinfo().
GetImmatureWatchOnlyBalance()
CAmount CWallet::GetImmatureWatchOnlyBalance () const
Definition at line 2567 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CWalletTx::GetImmatureWatchOnlyCredit(), LOCK2, and CWallet::mapWallet.
Referenced by WalletModel::getWatchImmatureBalance().
GetKeyFromPool()
bool CWallet::GetKeyFromPool (CPubKey & key, bool fInternal)
Definition at line 4277 of file wallet.cpp.
References CWallet::cs_wallet, CWallet::GenerateNewKey(), CCryptoKeyStore::IsLocked(), CWallet::KeepKey(), LOCK, CWallet::ReserveKeyFromKeyPool(), and CKeyPool::vchPubKey.
Referenced by AddressTableModel::addRow(), CWallet::CreateWalletFromFile(), PaymentServer::fetchPaymentACK(), CWallet::GetAccountPubkey(), and getnewaddress().
GetMasternodeOutpointAndKeys()
bool CWallet::GetMasternodeOutpointAndKeys (COutPoint & outpointRet, CPubKey & pubKeyRet, CKey & keyRet, const std::string & strTxHash = "", const std::string & strOutputIndex = "")
Get 1000DASH output and keys which can be used for the Masternode.
Definition at line 3227 of file wallet.cpp.
References atoi(), CWallet::AvailableCoins(), fImporting, fReindex, CWallet::GetOutpointAndKeysFromOutput(), LogPrintf, ONLY_1000, and uint256S().
GetMinimumFee() [1/2]
CAmount CWallet::GetMinimumFee (unsigned int nTxBytes, unsigned int nConfirmTarget, const CTxMemPool & pool) static
Estimate the minimum fee considering user set parameters and the required fee.
Definition at line 3923 of file wallet.cpp.
References CFeeRate::GetFee(), and payTxFee.
Referenced by CWallet::CreateTransaction(), and CoinControlDialog::updateLabels().
GetMinimumFee() [2/2]
CAmount CWallet::GetMinimumFee (unsigned int nTxBytes, unsigned int nConfirmTarget, const CTxMemPool & pool, CAmount targetFee) static
Estimate the minimum fee considering required fee and targetFee or if 0 then fee estimation for nConfirmTarget.
Definition at line 3929 of file wallet.cpp.
References CTxMemPool::estimateSmartFee(), CWallet::fallbackFee, CFeeRate::GetFee(), CWallet::GetRequiredFee(), and maxTxFee.
GetNeedsToBeAnonymizedBalance()
CAmount CWallet::GetNeedsToBeAnonymizedBalance (CAmount nMinBalance = 0) const
Definition at line 2465 of file wallet.cpp.
References COIN, fLiteMode, CWallet::GetAnonymizableBalance(), CWallet::GetAnonymizedBalance(), CPrivateSend::GetMaxPoolAmount(), CPrivateSendClientManager::nPrivateSendAmount, and privateSendClient.
Referenced by CPrivateSendClientSession::DoAutomaticDenominating().
GetNormalizedAnonymizedBalance()
CAmount CWallet::GetNormalizedAnonymizedBalance () const
Definition at line 2445 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, fLiteMode, CWallet::GetCappedOutpointPrivateSendRounds(), CWallet::IsDenominated(), LOCK2, CWallet::mapWallet, CPrivateSendClientManager::nPrivateSendRounds, privateSendClient, and CWallet::setWalletUTXO.
Referenced by OverviewPage::updatePrivateSendProgress().
GetOldestKeyInPool()
static int64_t GetOldestKeyInPool (const std::set< int64_t > & setKeyPool, CWalletDB & walletdb) static
Definition at line 4297 of file wallet.cpp.
References CPubKey::IsValid(), CKeyPool::nTime, CWalletDB::ReadPool(), and CKeyPool::vchPubKey.
Referenced by CWallet::GetOldestKeyPoolTime().
GetOldestKeyPoolTime()
int64_t CWallet::GetOldestKeyPoolTime ()
Definition at line 4307 of file wallet.cpp.
References CWallet::cs_wallet, GetOldestKeyInPool(), GetTime(), LOCK, CWallet::setExternalKeyPool, CWallet::setInternalKeyPool, and CWallet::strWalletFile.
Referenced by getinfo(), and getwalletinfo().
GetOutpointAndKeysFromOutput()
bool CWallet::GetOutpointAndKeysFromOutput (const COutput & out, COutPoint & outpointRet, CPubKey & pubKeyRet, CKey & keyRet)
Extract txin information and keys from output.
Definition at line 3255 of file wallet.cpp.
References ExtractDestination(), fImporting, fReindex, CMerkleTx::GetHash(), CWallet::GetKey(), CBitcoinAddress::GetKeyID(), CKey::GetPubKey(), COutput::i, LogPrintf, CMerkleTx::tx, and COutput::tx.
Referenced by CWallet::GetMasternodeOutpointAndKeys().
GetRequiredFee()
CAmount CWallet::GetRequiredFee (unsigned int nTxBytes) static
Return the minimum required fee taking into account the floating relay fee and user set minimum transaction fee.
Definition at line 3918 of file wallet.cpp.
References CFeeRate::GetFee(), minRelayTxFee, and CWallet::minTxFee.
Referenced by CWallet::GetMinimumFee(), SendCoinsDialog::setMinimumFee(), SendCoinsDialog::setModel(), CoinControlDialog::updateLabels(), SendCoinsDialog::updateMinFeeLabel(), and SendCoinsDialog::updateSmartFeeLabel().
GetReservedKey()
bool CReserveKey::GetReservedKey (CPubKey & pubkey, bool fInternalIn)
Definition at line 4506 of file wallet.cpp.
References CKeyPool::fInternal, CReserveKey::fInternal, CPubKey::IsValid(), CReserveKey::nIndex, CReserveKey::pwallet, CWallet::ReserveKeyFromKeyPool(), CKeyPool::vchPubKey, and CReserveKey::vchPubKey.
Referenced by CKeyHolder::CKeyHolder(), CWallet::CreateCollateralTransaction(), CWallet::CreateTransaction(), getrawchangeaddress(), and CPrivateSendClientSession::MakeCollateralAmounts().
GetScriptForMining()
void CWallet::GetScriptForMining (boost::shared_ptr< CReserveScript > & script) override virtual
Reimplemented from CValidationInterface.
Definition at line 4587 of file wallet.cpp.
References OP_CHECKSIG, and ToByteVector().
GetUnconfirmedBalance()
CAmount CWallet::GetUnconfirmedBalance () const
Definition at line 2507 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CWalletTx::GetAvailableCredit(), CMerkleTx::GetDepthInMainChain(), CWalletTx::InMempool(), CMerkleTx::IsLockedByInstantSend(), CWalletTx::IsTrusted(), LOCK2, and CWallet::mapWallet.
Referenced by WalletModel::getUnconfirmedBalance(), getunconfirmedbalance(), and getwalletinfo().
GetUnconfirmedWatchOnlyBalance()
CAmount CWallet::GetUnconfirmedWatchOnlyBalance () const
Definition at line 2552 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CWalletTx::GetAvailableWatchOnlyCredit(), CMerkleTx::GetDepthInMainChain(), CWalletTx::InMempool(), CMerkleTx::IsLockedByInstantSend(), CWalletTx::IsTrusted(), LOCK2, and CWallet::mapWallet.
Referenced by WalletModel::getWatchUnconfirmedBalance().
GetWatchOnlyBalance()
CAmount CWallet::GetWatchOnlyBalance () const
Definition at line 2536 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, CWalletTx::GetAvailableWatchOnlyCredit(), CWalletTx::IsTrusted(), LOCK2, and CWallet::mapWallet.
Referenced by WalletModel::getWatchBalance().
HasCollateralInputs()
bool CWallet::HasCollateralInputs (bool fOnlyConfirmed = true) const
Definition at line 3312 of file wallet.cpp.
References CWallet::AvailableCoins(), ONLY_PRIVATESEND_COLLATERAL, and vCoins.
Referenced by CPrivateSendClientSession::CreateDenominated(), and CPrivateSendClientSession::DoAutomaticDenominating().
IsLockedCoin()
bool CWallet::IsLockedCoin (uint256 hash, unsigned int n) const
Definition at line 4626 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, and CWallet::setLockedCoins.
Referenced by CWallet::AvailableCoins(), WalletModel::isLockedCoin(), and CWallet::SelectCoinsGroupedByAddresses().
KeepKey() [1/2]
void CWallet::KeepKey (int64_t nIndex)
Definition at line 4251 of file wallet.cpp.
References CWalletDB::ErasePool(), CWallet::fFileBacked, LogPrintf, CWallet::nKeysLeftSinceAutoBackup, nWalletBackups, and CWallet::strWalletFile.
Referenced by CWallet::GetKeyFromPool(), and CReserveKey::KeepKey().
KeepKey() [2/2]
void CReserveKey::KeepKey ()
Definition at line 4525 of file wallet.cpp.
References CWallet::KeepKey(), CReserveKey::nIndex, CReserveKey::pwallet, and CReserveKey::vchPubKey.
Referenced by CWallet::CommitTransaction(), CWallet::CreateCollateralTransaction(), CWallet::FundTransaction(), getrawchangeaddress(), CKeyHolder::KeepKey(), CReserveKey::KeepScript(), and CPrivateSendClientSession::MakeCollateralAmounts().
KeypoolCountExternalKeys()
size_t CWallet::KeypoolCountExternalKeys ()
Definition at line 4141 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, and CWallet::setExternalKeyPool.
Referenced by AutoBackupWallet(), CWallet::CreateWalletFromFile(), getwalletinfo(), and CWalletDB::LoadWallet().
KeypoolCountInternalKeys()
size_t CWallet::KeypoolCountInternalKeys ()
Definition at line 4147 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, and CWallet::setInternalKeyPool.
Referenced by CWallet::CreateWalletFromFile(), and getwalletinfo().
less_then_denom()
bool less_then_denom (const COutput & out1, const COutput & out2)
Definition at line 2702 of file wallet.cpp.
References CPrivateSend::GetStandardDenominations(), COutput::i, CMerkleTx::tx, and COutput::tx.
Referenced by CWallet::SelectCoinsMinConf().
ListAccountCreditDebit()
void CWallet::ListAccountCreditDebit (const std::string & strAccount, std::list< CAccountingEntry > & entries)
Definition at line 3894 of file wallet.cpp.
References CWalletDB::ListAccountCreditDebit(), and CWallet::strWalletFile.
Referenced by GetResults().
ListLockedCoins()
void CWallet::ListLockedCoins (std::vector< COutPoint > & vOutpts)
Definition at line 4634 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, and CWallet::setLockedCoins.
Referenced by WalletModel::listCoins(), WalletModel::listLockedCoins(), and listlockunspent().
ListProTxCoins()
void CWallet::ListProTxCoins (std::vector< COutPoint > & vOutpts)
Definition at line 4644 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, deterministicMNManager, CDeterministicMNManager::HasMNCollateralAtChainTip(), CDeterministicMNManager::IsProTxWithCollateral(), CWallet::mapWallet, and CWallet::setWalletUTXO.
Referenced by protx_list(), and MasternodeList::updateDIP3List().
LoadReserveKeysToSet()
static void LoadReserveKeysToSet (std::set< CKeyID > & setAddress, const std::set< int64_t > & setKeyPool, CWalletDB & walletdb) static
Definition at line 4543 of file wallet.cpp.
References CPubKey::GetID(), CPubKey::IsValid(), CWalletDB::ReadPool(), and CKeyPool::vchPubKey.
Referenced by CWallet::GetAllReserveKeys().
LoadWallet()
DBErrors CWallet::LoadWallet (bool & fFirstRunRet)
Definition at line 3948 of file wallet.cpp.
References cs_main, CWallet::cs_wallet, DB_LOAD_OK, DB_NEED_REWRITE, CWallet::fFileBacked, CWallet::IsMine(), CWallet::IsSpent(), CPubKey::IsValid(), CClientUIInterface::LoadWallet, CWalletDB::LoadWallet(), LOCK, LOCK2, CWallet::mapWallet, CWallet::nKeysLeftSinceAutoBackup, CDB::Rewrite(), CWallet::setExternalKeyPool, CWallet::setInternalKeyPool, CWallet::setWalletUTXO, CWallet::strWalletFile, uiInterface, and CWallet::vchDefaultKey.
Referenced by CWallet::CreateWalletFromFile(), and WalletTestingSetup::WalletTestingSetup().
LockCoin()
void CWallet::LockCoin (const COutPoint & output)
Definition at line 4598 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, CWallet::fAnonymizableTallyCached, CWallet::fAnonymizableTallyCachedNonDenom, COutPoint::hash, CWallet::mapWallet, and CWallet::setLockedCoins.
Referenced by CWallet::AddToWallet(), AppInitMain(), CWallet::AutoLockMasternodeCollaterals(), CWallet::FundTransaction(), WalletModel::lockCoin(), lockunspent(), and CPrivateSendClientSession::PrepareDenominate().
NewKeyPool()
bool CWallet::NewKeyPool ()
Mark old keypool keys as used, and generate all new keys.
Definition at line 4117 of file wallet.cpp.
References CWallet::cs_wallet, CWalletDB::ErasePool(), CPrivateSendClientManager::fEnablePrivateSend, LOCK, LogPrintf, CWallet::nKeysLeftSinceAutoBackup, privateSendClient, CWallet::setExternalKeyPool, CWallet::setInternalKeyPool, CWallet::strWalletFile, and CWallet::TopUpKeyPool().
Referenced by CWallet::EncryptWallet().
ReserveKeyFromKeyPool()
void CWallet::ReserveKeyFromKeyPool (int64_t & nIndex, CKeyPool & keypool, bool fInternal)
Definition at line 4215 of file wallet.cpp.
References CWallet::cs_wallet, CKeyPool::fInternal, CPubKey::GetID(), CWallet::HaveKey(), CWallet::IsHDEnabled(), CCryptoKeyStore::IsLocked(), CPubKey::IsValid(), LOCK, LogPrintf, CWalletDB::ReadPool(), CWallet::setExternalKeyPool, CWallet::setInternalKeyPool, CWallet::strWalletFile, CWallet::TopUpKeyPool(), and CKeyPool::vchPubKey.
Referenced by CWallet::GetKeyFromPool(), and CReserveKey::GetReservedKey().
ReturnKey() [1/2]
void CWallet::ReturnKey (int64_t nIndex, bool fInternal)
Definition at line 4263 of file wallet.cpp.
References CWallet::cs_wallet, LOCK, LogPrintf, CWallet::setExternalKeyPool, and CWallet::setInternalKeyPool.
Referenced by CReserveKey::ReturnKey().
ReturnKey() [2/2]
void CReserveKey::ReturnKey ()
Definition at line 4534 of file wallet.cpp.
References CReserveKey::fInternal, CReserveKey::nIndex, CReserveKey::pwallet, CWallet::ReturnKey(), and CReserveKey::vchPubKey.
Referenced by CWallet::CreateTransaction(), CPrivateSendClientSession::MakeCollateralAmounts(), CKeyHolder::ReturnKey(), and CReserveKey::~CReserveKey().
SelectCoins()
bool CWallet::SelectCoins (const std::vector< COutput > & vAvailableCoins, const CAmount & nTargetValue, std::set< std::pair< const CWalletTx *, unsigned int > > & setCoinsRet, CAmount & nValueRet, const CCoinControl * coinControl = NULL, AvailableCoinsType nCoinType = ALL_COINS, bool fUseInstantSend = true) const private
Select a set of coins such that nValueRet >= nTargetValue and at least all coins from coinControl are selected; Never select unconfirmed coins if they are not ours.
Definition at line 2870 of file wallet.cpp.
References bSpendZeroConfChange, DEFAULT_ANCESTOR_LIMIT, DEFAULT_DESCENDANT_LIMIT, DEFAULT_WALLET_REJECT_LONG_CHAINS, CCoinControl::fAllowOtherInputs, CCoinControl::fRequireAllInputs, COutput::fSpendable, GetArg(), GetBoolArg(), CWallet::GetCappedOutpointPrivateSendRounds(), CMerkleTx::GetHash(), CWallet::GetRealOutpointPrivateSendRounds(), COutPoint::hash, CCoinControl::HasSelected(), COutput::i, CCoinControl::ListSelected(), CWallet::mapWallet, COutPoint::n, CPrivateSendClientManager::nPrivateSendRounds, ONLY_DENOMINATED, privateSendClient, CWallet::SelectCoinsMinConf(), CMerkleTx::tx, COutput::tx, and vCoins.
Referenced by CWallet::CreateTransaction().
SelectCoinsGroupedByAddresses()
bool CWallet::SelectCoinsGroupedByAddresses (std::vector< CompactTallyItem > & vecTallyRet, bool fSkipDenominated = true, bool fAnonymizable = true, bool fSkipUnconfirmed = true, int nMaxOupointsPerAddress = -1) const
Definition at line 3068 of file wallet.cpp.
References COIN, cs_main, CWallet::cs_wallet, ExtractDestination(), CWallet::fAnonymizableTallyCached, CWallet::fAnonymizableTallyCachedNonDenom, fMasternodeMode, CMerkleTx::GetBlocksToMaturity(), CWallet::GetCappedOutpointPrivateSendRounds(), CPrivateSend::GetSmallestDenomination(), CMerkleTx::IsCoinBase(), CPrivateSend::IsCollateralAmount(), CPrivateSend::IsDenominatedAmount(), CWallet::IsLockedCoin(), CWallet::IsMine(), ISMINE_SPENDABLE, CWallet::IsSpent(), CWalletTx::IsTrusted(), LOCK2, LogAcceptCategory(), LogPrint, CWallet::mapWallet, CPrivateSendClientManager::nPrivateSendRounds, privateSendClient, CWallet::setWalletUTXO, strprintf, CBase58Data::ToString(), CMerkleTx::tx, CWallet::vecAnonymizableTallyCached, and CWallet::vecAnonymizableTallyCachedNonDenom.
Referenced by CPrivateSendClientSession::CreateDenominated(), CWallet::GetAnonymizableBalance(), and CPrivateSendClientSession::MakeCollateralAmounts().
SelectCoinsMinConf()
bool CWallet::SelectCoinsMinConf (const CAmount & nTargetValue, int nConfMine, int nConfTheirs, uint64_t nMaxAncestors, std::vector< COutput > vCoins, std::set< std::pair< const CWalletTx *, unsigned int > > & setCoinsRet, CAmount & nValueRet, AvailableCoinsType nCoinType = ALL_COINS, bool fUseInstantSend = false) const
Shuffle and select coins until nTargetValue is reached while avoiding small change; This method is stochastic for some inputs and upon completion the coin set and corresponding actual target value is assembled.
Definition at line 2717 of file wallet.cpp.
References ApproximateBestSubset(), COIN, FormatMoney(), COutput::fSpendable, CMerkleTx::GetHash(), GetRandInt(), CWallet::GetRealOutpointPrivateSendRounds(), CSporkManager::GetSporkValue(), COutput::i, CPrivateSend::IsDenominatedAmount(), CWalletTx::IsFromMe(), ISMINE_ALL, less_then_denom(), LogPrint, maxTxFee, mempool, MIN_CHANGE, COutput::nDepth, CPrivateSendClientManager::nPrivateSendRounds, ONLY_DENOMINATED, privateSendClient, SPORK_5_INSTANTSEND_MAX_VALUE, sporkManager, CTxMemPool::TransactionWithinChainLimit(), CMerkleTx::tx, COutput::tx, and vCoins.
Referenced by BOOST_AUTO_TEST_CASE(), CoinSelection(), and CWallet::SelectCoins().
SelectPrivateCoins()
bool CWallet::SelectPrivateCoins (CAmount nValueMin, CAmount nValueMax, std::vector< CTxIn > & vecTxInRet, CAmount & nValueRet, int nPrivateSendRoundsMin, int nPrivateSendRoundsMax) const
Definition at line 3170 of file wallet.cpp.
References CWallet::AvailableCoins(), COIN, fMasternodeMode, CWallet::GetCappedOutpointPrivateSendRounds(), CPrivateSend::IsCollateralAmount(), ONLY_DENOMINATED, ONLY_NONDENOMINATED, CTxIn::prevout, and vCoins.
Referenced by CPrivateSendClientSession::StartNewQueue().
SelectPSInOutPairsByDenominations()
bool CWallet::SelectPSInOutPairsByDenominations (int nDenom, CAmount nValueMin, CAmount nValueMax, std::vector< std::pair< CTxDSIn, CTxOut > > & vecPSInOutPairsRet)
Definition at line 3020 of file wallet.cpp.
References CWallet::AvailableCoins(), COIN, CPrivateSend::GetDenominationsBits(), GetRandInt(), CWallet::GetRealOutpointPrivateSendRounds(), CPrivateSend::GetStandardDenominations(), LogPrint, LogPrintf, CPrivateSendClientManager::nPrivateSendRounds, ONLY_DENOMINATED, CTxIn::prevout, privateSendClient, base_blob< BITS >::ToString(), and vCoins.
Referenced by CPrivateSendClientSession::JoinExistingQueue(), and CPrivateSendClientSession::SelectDenominate().
SetAddressBook()
bool CWallet::SetAddressBook (const CTxDestination & address, const std::string & strName, const std::string & purpose)
Definition at line 4057 of file wallet.cpp.
References CWallet::cs_wallet, CT_NEW, CT_UPDATED, CWallet::fFileBacked, CWallet::IsMine(), ISMINE_NO, LOCK, CWallet::mapAddressBook, CWallet::NotifyAddressBookChanged, CWallet::strWalletFile, CWalletDB::WriteName(), and CWalletDB::WritePurpose().
Referenced by addmultisigaddress(), AddressTableModel::addRow(), CWallet::CreateWalletFromFile(), PaymentServer::fetchPaymentACK(), CWallet::GetAccountPubkey(), getnewaddress(), ImportAddress(), importprivkey(), ImportScript(), importwallet(), ProcessImport(), WalletModel::sendCoins(), setaccount(), and AddressTableModel::setData().
SetDefaultKey()
bool CWallet::SetDefaultKey (const CPubKey & vchPubKey)
Definition at line 4102 of file wallet.cpp.
References CWallet::fFileBacked, CWallet::strWalletFile, and CWallet::vchDefaultKey.
Referenced by CWallet::CreateWalletFromFile().
TopUpKeyPool()
bool CWallet::TopUpKeyPool (unsigned int kpSize = 0)
Definition at line 4153 of file wallet.cpp.
References _(), CWallet::cs_wallet, DEFAULT_KEYPOOL_SIZE, CWallet::GenerateNewKey(), GetArg(), CClientUIInterface::InitMessage, CWallet::IsHDEnabled(), CCryptoKeyStore::IsLocked(), LOCK, LogPrintf, CWallet::setExternalKeyPool, CWallet::setInternalKeyPool, strprintf, CWallet::strWalletFile, uiInterface, and CWalletDB::WritePool().
Referenced by CWallet::EncryptWallet(), getnewaddress(), getrawchangeaddress(), keypoolrefill(), CWallet::NewKeyPool(), CWallet::ReserveKeyFromKeyPool(), CWallet::Unlock(), and walletpassphrase().
UnlockAllCoins()
void CWallet::UnlockAllCoins ()
Definition at line 4620 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, and CWallet::setLockedCoins.
Referenced by lockunspent().
UnlockCoin()
void CWallet::UnlockCoin (const COutPoint & output)
Definition at line 4609 of file wallet.cpp.
References AssertLockHeld, CWallet::cs_wallet, CWallet::fAnonymizableTallyCached, CWallet::fAnonymizableTallyCachedNonDenom, COutPoint::hash, CWallet::mapWallet, and CWallet::setLockedCoins.
Referenced by lockunspent(), CPrivateSendClientSession::PrepareDenominate(), WalletModel::unlockCoin(), and CPrivateSendClientSession::UnlockCoins().
UpdatedTransaction()
bool CWallet::UpdatedTransaction (const uint256 & hashTx) override virtual
Reimplemented from CValidationInterface.
Definition at line 4573 of file wallet.cpp.
References CWallet::cs_wallet, CT_UPDATED, LOCK, CWallet::mapWallet, and CWallet::NotifyTransactionChanged.
Referenced by CInstantSend::UpdateLockedTransaction().
ZapSelectTx()
DBErrors CWallet::ZapSelectTx (std::vector< uint256 > & vHashIn, std::vector< uint256 > & vHashOut)
Definition at line 4004 of file wallet.cpp.
References CWallet::cs_wallet, DB_LOAD_OK, DB_NEED_REWRITE, CWallet::fFileBacked, LOCK, CWallet::MarkDirty(), CDB::Rewrite(), CWallet::setExternalKeyPool, CWallet::setInternalKeyPool, CWallet::strWalletFile, and CWalletDB::ZapSelectTx().
Referenced by removeprunedfunds().
ZapWalletTx()
DBErrors CWallet::ZapWalletTx (std::vector< CWalletTx > & vWtx)
Definition at line 4031 of file wallet.cpp.
References CWallet::cs_wallet, DB_LOAD_OK, DB_NEED_REWRITE, CWallet::fFileBacked, LOCK, CWallet::nKeysLeftSinceAutoBackup, CDB::Rewrite(), CWallet::setExternalKeyPool, CWallet::setInternalKeyPool, CWallet::strWalletFile, and CWalletDB::ZapWalletTx().
Referenced by CWallet::CreateWalletFromFile().
Released under the MIT license