Dash Core: src/init.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
init.cpp File Reference
#include "init.h"
#include "addrman.h"
#include "amount.h"
#include "base58.h"
#include "chain.h"
#include "chainparams.h"
#include "checkpoints.h"
#include "compat/sanity.h"
#include "consensus/validation.h"
#include "httpserver.h"
#include "httprpc.h"
#include "key.h"
#include "validation.h"
#include "miner.h"
#include "netbase.h"
#include "net.h"
#include "netfulfilledman.h"
#include "net_processing.h"
#include "policy/policy.h"
#include "rpc/server.h"
#include "rpc/register.h"
#include "script/standard.h"
#include "script/sigcache.h"
#include "scheduler.h"
#include "timedata.h"
#include "txdb.h"
#include "txmempool.h"
#include "torcontrol.h"
#include "ui_interface.h"
#include "util.h"
#include "utilmoneystr.h"
#include "validationinterface.h"
#include "activemasternode.h"
#include "dsnotificationinterface.h"
#include "flat-database.h"
#include "governance.h"
#include "instantx.h"
#include "masternode-payments.h"
#include "masternode-sync.h"
#include "masternodeman.h"
#include "masternodeconfig.h"
#include "messagesigner.h"
#include "privatesend-server.h"
#include "spork.h"
#include "warnings.h"
#include "evo/deterministicmns.h"
#include "llmq/quorums_init.h"
#include <stdint.h>
#include <stdio.h>
#include <memory>
#include "bls/bls.h"
#include <signal.h>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/replace.hpp>
#include <boost/algorithm/string/split.hpp>
#include <boost/bind.hpp>
#include <boost/filesystem.hpp>
#include <boost/function.hpp>
#include <boost/interprocess/sync/file_lock.hpp>
#include <boost/thread.hpp>
#include <openssl/crypto.h>
Classes
class CCoinsViewErrorCatcher
This is a minimally invasive approach to shutdown on LevelDB read errors from the chainstate, while keeping user interface out of the common library, which is shared between bitcoind, and bitcoin-qt and non-server tools.
struct CImportingNow
Macros
#define MIN_CORE_FILEDESCRIPTORS 150
Enumerations
enum BindFlags { BF_NONE = 0, BF_EXPLICIT = (1U << 0), BF_REPORT_ERROR = (1U << 1), BF_WHITELIST = (1U << 2) }
Used to pass flags to the Bind() function.
Functions
void ThreadSendAlert (CConnman &connman)
std::atomic< bool > fRequestShutdown (false)
std::atomic< bool > fRequestRestart (false)
std::atomic< bool > fDumpMempoolLater (false)
void StartShutdown ()
void StartRestart ()
bool ShutdownRequested ()
void Interrupt (boost::thread_group &threadGroup)
Interrupt threads.
void PrepareShutdown ()
Preparing steps before shutting down or restarting the wallet.
void Shutdown ()
Shutdown is split into 2 parts: Part 1: shut down everything but the main wallet instance (done in PrepareShutdown()) Part 2: delete wallet instance.
void HandleSIGTERM (int)
Signal handlers are very limited in what they are allowed to do, so:
void HandleSIGHUP (int)
static bool Bind (CConnman &connman, const CService &addr, unsigned int flags)
void OnRPCStarted ()
void OnRPCStopped ()
void OnRPCPreCommand (const CRPCCommand &cmd)
std::string HelpMessage (HelpMessageMode mode)
Help for options shared between UI and daemon (for -help)
std::string LicenseInfo ()
Returns licensing information (for -version)
static void BlockNotifyCallback (bool initialSync, const CBlockIndex *pBlockIndex)
static void BlockNotifyGenesisWait (bool, const CBlockIndex *pBlockIndex)
void CleanupBlockRevFiles ()
void ThreadImport (std::vector< boost::filesystem::path > vImportFiles)
bool InitSanityCheck (void)
Sanity checks Ensure that Dash Core is running in a usable environment with all necessary library support.
bool AppInitServers (boost::thread_group &threadGroup)
void InitParameterInteraction ()
Parameter interaction: change current parameters depending on various rules.
static std::string ResolveErrMsg (const char *const optname, const std::string &strBind)
void InitLogging ()
Initialize the logging infrastructure.
static void new_handler_terminate ()
bool AppInitBasicSetup ()
Initialize bitcoin core: Basic context setup.
bool AppInitParameterInteraction ()
Initialization: parameter interaction.
static bool LockDataDirectory (bool probeOnly)
bool AppInitSanityChecks ()
Initialization sanity checks: ecc init, sanity checks, dir lock.
bool AppInitMain (boost::thread_group &threadGroup, CScheduler &scheduler)
Bitcoin core main initialization.
Variables
bool fFeeEstimatesInitialized = false
static const bool DEFAULT_PROXYRANDOMIZE = true
static const bool DEFAULT_REST_ENABLE = false
static const bool DEFAULT_DISABLE_SAFEMODE = false
static const bool DEFAULT_STOPAFTERBLOCKIMPORT = false
std::unique_ptr< CConnman > g_connman
std::unique_ptr< PeerLogicValidation > peerLogic
static CDSNotificationInterface * pdsNotificationInterface = NULL
static const char * FEE_ESTIMATES_FILENAME ="fee_estimates.dat"
static CCoinsViewErrorCatcher * pcoinscatcher = NULL
static std::unique_ptr< ECCVerifyHandle > globalVerifyHandle
static bool fHaveGenesis = false
static boost::mutex cs_GenesisWait
static CConditionVariable condvar_GenesisWait
Macro Definition Documentation
MIN_CORE_FILEDESCRIPTORS
#define MIN_CORE_FILEDESCRIPTORS 150
Definition at line 122 of file init.cpp.
Referenced by AppInitParameterInteraction().
Enumeration Type Documentation
BindFlags
enum BindFlags
Used to pass flags to the Bind() function.
Enumerator
BF_NONE
BF_EXPLICIT
BF_REPORT_ERROR
BF_WHITELIST
Definition at line 126 of file init.cpp.
Function Documentation
AppInitBasicSetup()
bool AppInitBasicSetup ()
Initialize bitcoin core: Basic context setup.
Note
This can be done before daemonization.
Precondition
Parameters should be parsed and config file should be read.
Definition at line 1038 of file init.cpp.
References GetBoolArg(), HandleSIGHUP(), HandleSIGTERM(), InitError(), new_handler_terminate(), and SetupNetworking().
Referenced by AppInit(), and BitcoinCore::initialize().
AppInitMain()
bool AppInitMain (boost::thread_group & threadGroup, CScheduler & scheduler)
Bitcoin core main initialization.
Note
This should only be done after daemonization.
Precondition
Parameters should be parsed and config file should be read, AppInitSanityChecks should have been called.
Definition at line 1406 of file init.cpp.
References _(), activeMasternodeInfo, activeMasternodeManager, AddLocal(), AppInitServers(), atoi(), BF_EXPLICIT, BF_NONE, BF_REPORT_ERROR, BF_WHITELIST, Bind(), BITCOIN_CONF_FILENAME, BlockNotifyCallback(), BlockNotifyGenesisWait(), CActiveMasternodeInfo::blsKeyOperator, CActiveMasternodeInfo::blsPubKeyOperator, CClientUIInterface::BTN_ABORT, chainActive, CheckDiskSpace(), CleanupBlockRevFiles(), CLIENT_NAME, CLIENT_VERSION, condvar_GenesisWait, CZMQNotificationInterface::Create(), CreatePidFile(), cs_GenesisWait, cs_main, CWallet::cs_wallet, DateTimeStrFormat(), DEFAULT_BLOCKSONLY, DEFAULT_CHECKBLOCKS, DEFAULT_CHECKLEVEL, DEFAULT_LISTEN, DEFAULT_LISTEN_ONION, DEFAULT_MAX_MEMPOOL_SIZE, DEFAULT_MAX_UPLOAD_TARGET, DEFAULT_MAXRECEIVEBUFFER, DEFAULT_MAXSENDBUFFER, DEFAULT_NAME_LOOKUP, DEFAULT_PRIVATESEND_AMOUNT, DEFAULT_PRIVATESEND_LIQUIDITY, DEFAULT_PRIVATESEND_MULTISESSION, DEFAULT_PRIVATESEND_ROUNDS, DEFAULT_PRIVATESEND_SESSIONS, DEFAULT_PROXYRANDOMIZE, DEFAULT_TXINDEX, DEFAULT_UPNP, llmq::DestroyLLMQSystem(), deterministicMNManager, CBaseChainParams::DEVNET, Discover(), CNetFulfilledRequestManager::DoMaintenance(), CMasternodeSync::DoMaintenance(), CPrivateSendServer::DoMaintenance(), CActiveLegacyMasternodeManager::DoMaintenance(), CInstantSend::DoMaintenance(), CMasternodePayments::DoMaintenance(), CMasternodeMan::DoMaintenance(), CPrivateSendClientManager::DoMaintenance(), CGovernanceManager::DoMaintenance(), evoDb, fDebug, fDiscover, FEE_ESTIMATES_FILENAME, fEnableInstantSend, CPrivateSendClientManager::fEnablePrivateSend, fFeeEstimatesInitialized, fHaveGenesis, fHavePruned, fListen, fLiteMode, fLogTimestamps, fMasternodeMode, fNameLookup, FormatSubVersion(), fPrintToDebugLog, CPrivateSendClientManager::fPrivateSendMultiSession, fPruneMode, fReindex, fRelayTxes, fRequestShutdown(), fTxIndex, g_connman, GetAdjustedTime(), GetArg(), GetBoolArg(), GetConfigFile(), CChainParams::GetConsensus(), CMasternodeConfig::getCount(), GetDataDir(), GetDefaultDataDir(), GetDevNetName(), CMasternodeConfig::getEntries(), CPubKey::GetID(), CMessageSigner::GetKeysFromSecret(), GetListenPort(), GetMasternodeConfigFile(), GetNodeSignals(), GetPidFile(), CService::GetPort(), CBLSSecretKey::GetPublicKey(), GetRand(), GetTime(), GetTimeMillis(), governance, Consensus::Params::hashDevnetGenesisBlock, Consensus::Params::hashGenesisBlock, CChain::Height(), CKeePassIntegrator::init(), CWallet::InitAutoBackup(), InitBlockIndex(), InitError(), llmq::InitLLMQSystem(), CWallet::InitLoadWallet(), CClientUIInterface::InitMessage, CGovernanceManager::InitOnLoad(), InitSignatureCache(), CPrivateSend::InitStandardDenominations(), InitWarning(), instantsend, IsArgSet(), CWallet::IsMine(), ISMINE_SPENDABLE, base_blob< BITS >::IsNull(), CAutoFile::IsNull(), proxyType::IsValid(), CNetAddr::IsValid(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CSubNet::IsValid(), keePassInt, legacyActiveMasternodeManager, CActiveMasternodeInfo::legacyKeyIDOperator, CActiveMasternodeInfo::legacyKeyOperator, CFlatDB< T >::Load(), LoadBlockIndex(), LOCAL_MANUAL, LOCK, CWallet::LockCoin(), LockDataDirectory(), LogPrintf, Lookup(), LookupNumeric(), LookupSubNet(), mapBlockIndex, mapMultiArgs, MapPort(), MASTERNODE_MIN_MNP_SECONDS, masternodeConfig, masternodeSync, MAX_ADDNODE_CONNECTIONS, MAX_OUTBOUND_CONNECTIONS, MAX_PRIVATESEND_AMOUNT, MAX_PRIVATESEND_LIQUIDITY, MAX_PRIVATESEND_ROUNDS, MAX_PRIVATESEND_SESSIONS, MAX_SUBVERSION_LENGTH, MAX_UPLOAD_TIMEFRAME, mempool, MIN_BLOCKS_TO_KEEP, MIN_PRIVATESEND_AMOUNT, MIN_PRIVATESEND_LIQUIDITY, MIN_PRIVATESEND_ROUNDS, MIN_PRIVATESEND_SESSIONS, mnodeman, mnpayments, CClientUIInterface::MSG_ERROR, CConnman::Options::nBestHeight, nCoinCacheUsage, nDefaultDbCache, NET_IPV4, NET_IPV6, NET_MAX, NET_TOR, NET_UNROUTABLE, netfulfilledman, CChainParams::NetworkIDString(), CPrivateSendClientManager::nLiquidityProvider, CConnman::Options::nLocalServices, CConnman::Options::nMaxAddnode, nMaxBlockDBAndTxIndexCache, nMaxBlockDBCache, nMaxCoinsDBCache, CConnman::Options::nMaxConnections, nMaxDbCache, CConnman::Options::nMaxFeeler, CConnman::Options::nMaxOutbound, CConnman::Options::nMaxOutboundLimit, CConnman::Options::nMaxOutboundTimeframe, nMinDbCache, NODE_NETWORK, CClientUIInterface::NotifyBlockTip, CPrivateSendClientManager::nPrivateSendAmount, CPrivateSendClientManager::nPrivateSendRounds, CPrivateSendClientManager::nPrivateSendSessions, CConnman::Options::nReceiveFloodSize, CConnman::Options::nRelevantServices, nScriptCheckThreads, CConnman::Options::nSendBufferMaxSize, CBlockIndex::nTime, OpenDebugLog(), Params(), ParseHex(), ParseNetwork(), pblocktree, pcoinscatcher, pcoinsdbview, pcoinsTip, pdsNotificationInterface, peerLogic, CWallet::postInitProcess(), privateSendClient, privateSendServer, PruneAndFlush(), pwalletMain, CTxMemPool::ReadFeeEstimates(), RegisterNodeSignals(), RegisterValidationInterface(), CBaseChainParams::REGTEST, ResolveErrMsg(), RPCNotifyBlockChange(), SAFE_CHARS_UA_COMMENT, SanitizeString(), CScheduler::scheduleEvery(), SER_DISK, CScheduler::serviceQueue(), CBLSWrapper< ImplType, _SerSize, C >::SetBuf(), base_blob< BITS >::SetHex(), SetLimited(), CPrivateSendClientManager::SetMinBlocksToWait(), CSporkManager::SetMinSporkKeys(), SetNameProxy(), CSporkManager::SetPrivKey(), SetProxy(), SetRPCWarmupFinished(), SetRPCWarmupStatus(), CSporkManager::SetSporkAddress(), ShrinkDebugFile(), CMasternodeMan::size(), source, CChainParams::SporkAddresses(), sporkManager, StartTorControl(), strprintf, strSubVersion, ThreadImport(), CClientUIInterface::ThreadSafeQuestion, ThreadScriptCheck(), ThreadSendAlert(), CChain::Tip(), CBase58Data::ToString(), CBLSWrapper< ImplType, _SerSize, C >::ToString(), uiInterface, CConnman::Options::uiInterface, UnloadBlockIndex(), CCoinsViewDB::Upgrade(), CWallet::Verify(), and CBlockTreeDB::WriteReindexing().
Referenced by AppInit(), and BitcoinCore::initialize().
AppInitParameterInteraction()
bool AppInitParameterInteraction ()
Initialization: parameter interaction.
Note
This can be done before daemonization.
Precondition
Parameters should be parsed and config file should be read, AppInitBasicSetup should have been called.
Definition at line 1096 of file init.cpp.
References _(), AmountErrMsg(), DEFAULT_ACCEPT_DATACARRIER, DEFAULT_ALERTS, DEFAULT_ALLOWPRIVATENET, DEFAULT_CHECKPOINTS_ENABLED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_DESCENDANT_SIZE_LIMIT, DEFAULT_LISTEN, DEFAULT_MAX_MEMPOOL_SIZE, DEFAULT_MAX_PEER_CONNECTIONS, DEFAULT_MAX_TIP_AGE, DEFAULT_PEERBLOOMFILTERS, DEFAULT_PERMIT_BAREMULTISIG, DEFAULT_SCRIPTCHECK_THREADS, DEFAULT_TXINDEX, Consensus::Params::defaultAssumeValid, CChainParams::DefaultConsistencyChecks(), CBaseChainParams::DEVNET, dustRelayFee, fAcceptDatacarrier, fAlerts, fAllowPrivateNet, fCheckBlockIndex, fCheckpointsEnabled, fDebug, fIsBareMultisigStd, fPruneMode, fRequireStandard, GetArg(), GetBoolArg(), CChainParams::GetConsensus(), base_blob< BITS >::GetHex(), GetNumCores(), hashAssumeValid, incrementalRelayFee, InitError(), InitWarning(), IsArgSet(), base_blob< BITS >::IsNull(), LogPrintf, mapMultiArgs, MAX_ADDNODE_CONNECTIONS, MAX_SCRIPTCHECK_THREADS, Consensus::MAX_VERSION_BITS_DEPLOYMENTS, mempool, MIN_CORE_FILEDESCRIPTORS, MIN_DISK_SPACE_FOR_BLOCK_FILES, CChainParams::MineBlocksOnDemand(), minRelayTxFee, name, nBytesPerSigOp, nConnectTimeout, CChainParams::NetworkIDString(), Consensus::Params::nHighSubsidyBlocks, Consensus::Params::nHighSubsidyFactor, nMaxDatacarrierBytes, nMaxTipAge, Consensus::Params::nMinimumDifficultyBlocks, NODE_BLOOM, nPruneTarget, nScriptCheckThreads, CWallet::ParameterInteraction(), Params(), ParseInt32(), ParseInt64(), ParseMoney(), RaiseFileDescriptorLimit(), RegisterAllCoreRPCCommands(), RegisterWalletRPCCommands(), CChainParams::RequireStandard(), SetMockTime(), CTxMemPool::setSanityCheck(), strprintf, tableRPC, CFeeRate::ToString(), uint256S(), UpdateDevnetSubsidyAndDiffParams(), UpdateRegtestBIP9Parameters(), UpdateRegtestBudgetParameters(), and VersionBitsDeploymentInfo.
Referenced by AppInit(), and BitcoinCore::initialize().
AppInitSanityChecks()
bool AppInitSanityChecks ()
Initialization sanity checks: ecc init, sanity checks, dir lock.
Note
This can be done before daemonization.
Precondition
Parameters should be parsed and config file should be read, AppInitParameterInteraction should have been called.
Definition at line 1390 of file init.cpp.
References _(), ECC_Start(), globalVerifyHandle, InitError(), InitSanityCheck(), LockDataDirectory(), and strprintf.
Referenced by AppInit(), and BitcoinCore::initialize().
AppInitServers()
bool AppInitServers (boost::thread_group & threadGroup)
Definition at line 870 of file init.cpp.
References DEFAULT_REST_ENABLE, GetBoolArg(), InitHTTPServer(), RPCServer::OnPreCommand(), OnRPCPreCommand(), OnRPCStarted(), OnRPCStopped(), RPCServer::OnStarted(), RPCServer::OnStopped(), StartHTTPRPC(), StartHTTPServer(), StartREST(), and StartRPC().
Referenced by AppInitMain().
Bind()
static bool Bind (CConnman & connman, const CService & addr, unsigned int flags) static
Definition at line 393 of file init.cpp.
References BF_EXPLICIT, BF_REPORT_ERROR, BF_WHITELIST, CConnman::BindListenPort(), flags, InitError(), and IsLimited().
Referenced by AppInitMain().
BlockNotifyCallback()
static void BlockNotifyCallback (bool initialSync, const CBlockIndex * pBlockIndex) static
Definition at line 675 of file init.cpp.
References GetArg(), CBlockIndex::GetBlockHash(), base_blob< BITS >::GetHex(), and runCommand().
Referenced by AppInitMain().
BlockNotifyGenesisWait()
static void BlockNotifyGenesisWait (bool , const CBlockIndex * pBlockIndex) static
Definition at line 690 of file init.cpp.
References condvar_GenesisWait, cs_GenesisWait, and fHaveGenesis.
Referenced by AppInitMain().
CleanupBlockRevFiles()
void CleanupBlockRevFiles ()
Definition at line 721 of file init.cpp.
References atoi(), GetDataDir(), LogPrintf, and PAIRTYPE.
Referenced by AppInitMain().
fDumpMempoolLater()
std::atomic<bool> fDumpMempoolLater (false)
Referenced by PrepareShutdown(), and ThreadImport().
fRequestRestart()
std::atomic<bool> fRequestRestart (false)
Referenced by Shutdown(), and StartRestart().
fRequestShutdown()
std::atomic<bool> fRequestShutdown (false)
Referenced by AppInitMain(), HandleSIGTERM(), ShutdownRequested(), StartRestart(), StartShutdown(), and ThreadImport().
HandleSIGHUP()
void HandleSIGHUP (int)
Definition at line 388 of file init.cpp.
References fReopenDebugLog.
Referenced by AppInitBasicSetup().
HandleSIGTERM()
void HandleSIGTERM (int)
Signal handlers are very limited in what they are allowed to do, so:
Definition at line 383 of file init.cpp.
References fRequestShutdown().
Referenced by AppInitBasicSetup().
HelpMessage()
std::string HelpMessage (HelpMessageMode mode)
Help for options shared between UI and daemon (for -help)
Definition at line 426 of file init.cpp.
References _(), AppendParamsHelpMessages(), BaseParams(), BITCOIN_CONF_FILENAME, BITCOIN_PID_FILENAME, CURRENCY_UNIT, DEFAULT_ACCEPT_DATACARRIER, DEFAULT_ADDRESSINDEX, DEFAULT_ALERTS, DEFAULT_ALLOWPRIVATENET, DEFAULT_ANCESTOR_LIMIT, DEFAULT_ANCESTOR_SIZE_LIMIT, DEFAULT_BANSCORE_THRESHOLD, DEFAULT_BLOCK_MAX_SIZE, DEFAULT_BLOCK_MIN_TX_FEE, DEFAULT_BLOCK_PRIORITY_SIZE, DEFAULT_BLOCK_RECONSTRUCTION_EXTRA_TXN, DEFAULT_BLOCKSONLY, DEFAULT_BYTES_PER_SIGOP, DEFAULT_CHECKBLOCKS, DEFAULT_CHECKLEVEL, DEFAULT_CHECKPOINTS_ENABLED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_DESCENDANT_LIMIT, DEFAULT_DESCENDANT_SIZE_LIMIT, DEFAULT_DISABLE_SAFEMODE, DEFAULT_FORCEDNSSEED, DEFAULT_HTTP_SERVER_TIMEOUT, DEFAULT_HTTP_THREADS, DEFAULT_HTTP_WORKQUEUE, DEFAULT_INCREMENTAL_RELAY_FEE, DEFAULT_LIMITFREERELAY, DEFAULT_LISTEN_ONION, DEFAULT_LOGIPS, DEFAULT_LOGTHREADNAMES, DEFAULT_LOGTIMEMICROS, DEFAULT_LOGTIMESTAMPS, DEFAULT_MAX_MEMPOOL_SIZE, DEFAULT_MAX_ORPHAN_TRANSACTIONS, DEFAULT_MAX_PEER_CONNECTIONS, DEFAULT_MAX_SIG_CACHE_SIZE, DEFAULT_MAX_TIME_ADJUSTMENT, DEFAULT_MAX_TIP_AGE, DEFAULT_MAX_UPLOAD_TARGET, DEFAULT_MAXRECEIVEBUFFER, DEFAULT_MAXSENDBUFFER, DEFAULT_MEMPOOL_EXPIRY, DEFAULT_MIN_RELAY_TX_FEE, DEFAULT_MISBEHAVING_BANTIME, DEFAULT_NAME_LOOKUP, DEFAULT_PEERBLOOMFILTERS, DEFAULT_PERMIT_BAREMULTISIG, DEFAULT_PRINTPRIORITY, DEFAULT_PRIVATESEND_AMOUNT, DEFAULT_PRIVATESEND_LIQUIDITY, DEFAULT_PRIVATESEND_MULTISESSION, DEFAULT_PRIVATESEND_ROUNDS, DEFAULT_PRIVATESEND_SESSIONS, DEFAULT_PROXYRANDOMIZE, DEFAULT_RELAYPRIORITY, DEFAULT_REST_ENABLE, DEFAULT_SCRIPTCHECK_THREADS, DEFAULT_SPENTINDEX, DEFAULT_STOPAFTERBLOCKIMPORT, DEFAULT_TESTSAFEMODE, DEFAULT_TIMESTAMPINDEX, DEFAULT_TOR_CONTROL, DEFAULT_TRANSACTION_MAXFEE, DEFAULT_TXINDEX, DEFAULT_WHITELISTFORCERELAY, DEFAULT_WHITELISTRELAY, Consensus::Params::defaultAssumeValid, DUST_RELAY_TX_FEE, FormatMoney(), GetBoolArg(), CChainParams::GetConsensus(), base_blob< BITS >::GetHex(), GetNumCores(), CWallet::GetWalletHelpString(), HelpMessageGroup(), HelpMessageOpt(), HMM_BITCOIN_QT, HMM_BITCOIND, CBaseChainParams::MAIN, MAX_OP_RETURN_RELAY, MAX_PRIVATESEND_AMOUNT, MAX_PRIVATESEND_LIQUIDITY, MAX_PRIVATESEND_ROUNDS, MAX_PRIVATESEND_SESSIONS, MAX_SCRIPTCHECK_THREADS, MIN_DISK_SPACE_FOR_BLOCK_FILES, MIN_PRIVATESEND_AMOUNT, MIN_PRIVATESEND_LIQUIDITY, MIN_PRIVATESEND_ROUNDS, MIN_PRIVATESEND_SESSIONS, nDefaultDbCache, nMaxDbCache, nMinDbCache, Params(), strprintf, and CBaseChainParams::TESTNET.
Referenced by AppInit(), and HelpMessageDialog::HelpMessageDialog().
InitLogging()
void InitLogging ()
Initialize the logging infrastructure.
Definition at line 1002 of file init.cpp.
References DEFAULT_LOGIPS, DEFAULT_LOGTHREADNAMES, DEFAULT_LOGTIMEMICROS, DEFAULT_LOGTIMESTAMPS, fLogIPs, fLogThreadNames, fLogTimeMicros, fLogTimestamps, FormatFullVersion(), fPrintToConsole, fPrintToDebugLog, GetBoolArg(), and LogPrintf.
Referenced by AppInit(), and BitcoinApplication::parameterSetup().
InitParameterInteraction()
void InitParameterInteraction ()
Parameter interaction: change current parameters depending on various rules.
Definition at line 889 of file init.cpp.
References DEFAULT_ADDRESSINDEX, DEFAULT_BLOCKSONLY, DEFAULT_CHECKLEVEL, DEFAULT_LISTEN, DEFAULT_MAX_PEER_CONNECTIONS, DEFAULT_PRIVATESEND_LIQUIDITY, DEFAULT_SPENTINDEX, DEFAULT_TIMESTAMPINDEX, DEFAULT_WHITELISTFORCERELAY, ForceRemoveArg(), ForceSetArg(), GetArg(), GetBoolArg(), IsArgSet(), IsHex(), itostr(), LogPrintf, mapMultiArgs, MAX_PRIVATESEND_AMOUNT, MIN_PRIVATESEND_SESSIONS, and SoftSetBoolArg().
Referenced by AppInit(), and BitcoinApplication::parameterSetup().
InitSanityCheck()
bool InitSanityCheck (void)
Sanity checks Ensure that Dash Core is running in a usable environment with all necessary library support.
Definition at line 854 of file init.cpp.
References BLSInit(), ECC_InitSanityCheck(), glibc_sanity_test(), glibcxx_sanity_test(), and InitError().
Referenced by AppInitSanityChecks().
Interrupt()
void Interrupt (boost::thread_group & threadGroup)
Interrupt threads.
Definition at line 210 of file init.cpp.
References g_connman, InterruptHTTPRPC(), InterruptHTTPServer(), InterruptREST(), InterruptRPC(), and InterruptTorControl().
Referenced by AppInit(), BitcoinCore::restart(), BitcoinCore::shutdown(), and WaitForShutdown().
LicenseInfo()
std::string LicenseInfo ()
Returns licensing information (for -version)
Definition at line 653 of file init.cpp.
References _(), COPYRIGHT_YEAR, CopyrightHolders(), and strprintf.
Referenced by AppInit(), and HelpMessageDialog::HelpMessageDialog().
LockDataDirectory()
static bool LockDataDirectory (bool probeOnly) static
Definition at line 1367 of file init.cpp.
References _(), GetDataDir(), InitError(), and strprintf.
Referenced by AppInitMain(), and AppInitSanityChecks().
new_handler_terminate()
static void new_handler_terminate () static
Definition at line 1025 of file init.cpp.
References LogPrintf.
Referenced by AppInitBasicSetup().
OnRPCPreCommand()
void OnRPCPreCommand (const CRPCCommand & cmd)
Definition at line 417 of file init.cpp.
References DEFAULT_DISABLE_SAFEMODE, GetBoolArg(), GetWarnings(), JSONRPCError(), CRPCCommand::okSafeMode, and RPC_FORBIDDEN_BY_SAFE_MODE.
Referenced by AppInitServers().
OnRPCStarted()
void OnRPCStarted ()
Definition at line 404 of file init.cpp.
References CClientUIInterface::NotifyBlockTip, RPCNotifyBlockChange(), and uiInterface.
Referenced by AppInitServers().
OnRPCStopped()
void OnRPCStopped ()
Definition at line 409 of file init.cpp.
References cvBlockChange, LogPrint, CClientUIInterface::NotifyBlockTip, RPCNotifyBlockChange(), and uiInterface.
Referenced by AppInitServers().
PrepareShutdown()
void PrepareShutdown ()
Preparing steps before shutting down or restarting the wallet.
Note: Shutdown() must be able to handle cases in which AppInit2() failed part of the way, for example if the data directory was found to be locked. Be sure that anything that writes files or flushes caches only does this if the respective module was initialized.
Definition at line 223 of file init.cpp.
References activeMasternodeInfo, activeMasternodeManager, CTxMemPool::AddTransactionsUpdated(), CActiveMasternodeInfo::blsKeyOperator, CActiveMasternodeInfo::blsPubKeyOperator, CLIENT_VERSION, cs_main, llmq::DestroyLLMQSystem(), deterministicMNManager, CFlatDB< T >::Dump(), DumpMempool(), evoDb, fDumpMempoolLater(), FEE_ESTIMATES_FILENAME, fEnableInstantSend, CPrivateSendClientManager::fEnablePrivateSend, fFeeEstimatesInitialized, fLiteMode, CWallet::Flush(), FlushStateToDisk(), fMasternodeMode, fRPCInWarmup, g_connman, GetDataDir(), GetNodeSignals(), GetPidFile(), governance, instantsend, CAutoFile::IsNull(), LOCK, LogPrintf, MapPort(), mempool, mnodeman, mnpayments, netfulfilledman, pblocktree, pcoinscatcher, pcoinsdbview, pcoinsTip, pdsNotificationInterface, peerLogic, privateSendClient, pwalletMain, RenameThread(), CPrivateSendClientManager::ResetPool(), RPCIsInWarmup(), SER_DISK, sporkManager, StopHTTPRPC(), StopHTTPServer(), StopREST(), StopRPC(), TRY_LOCK, UnregisterAllValidationInterfaces(), UnregisterNodeSignals(), UnregisterValidationInterface(), and CTxMemPool::WriteFeeEstimates().
Referenced by BitcoinCore::restart(), and Shutdown().
ResolveErrMsg()
static std::string ResolveErrMsg (const char *const optname, const std::string & strBind) static
Definition at line 997 of file init.cpp.
References _(), and strprintf.
Referenced by AppInitMain().
Shutdown()
void Shutdown ()
Shutdown is split into 2 parts: Part 1: shut down everything but the main wallet instance (done in PrepareShutdown()) Part 2: delete wallet instance.
In case of a restart PrepareShutdown() was already called before, but this method here gets called implicitly when the parent object is deleted. In this case we have to skip the PrepareShutdown() part because it was already executed and just delete the wallet instance.
Definition at line 363 of file init.cpp.
References ECC_Stop(), fRequestRestart(), globalVerifyHandle, LogPrintf, PrepareShutdown(), pwalletMain, and StopTorControl().
Referenced by AppInit(), and BitcoinCore::shutdown().
ShutdownRequested()
bool ShutdownRequested ()
Definition at line 177 of file init.cpp.
References fRequestShutdown().
Referenced by ActivateBestChain(), CMasternode::Check(), BitcoinGUI::detectShutdown(), CNetFulfilledRequestManager::DoMaintenance(), CPrivateSendServer::DoMaintenance(), CMasternodeSync::DoMaintenance(), CActiveLegacyMasternodeManager::DoMaintenance(), CInstantSend::DoMaintenance(), CMasternodePayments::DoMaintenance(), CMasternodeMan::DoMaintenance(), CPrivateSendClientManager::DoMaintenance(), CGovernanceManager::DoMaintenance(), BitcoinGUI::handleRestart(), LoadMempool(), OverviewPage::privateSendStatus(), ThreadSendAlert(), MasternodeList::updateDIP3List(), MasternodeList::updateMyNodeList(), MasternodeList::updateNodeList(), OverviewPage::updatePrivateSendProgress(), CCoinsViewDB::Upgrade(), CVerifyDB::VerifyDB(), and WaitForShutdown().
StartRestart()
void StartRestart ()
Definition at line 173 of file init.cpp.
References fRequestRestart(), and fRequestShutdown().
Referenced by BitcoinCore::restart().
StartShutdown()
void StartShutdown ()
Definition at line 169 of file init.cpp.
References fRequestShutdown().
Referenced by SplashScreen::closeEvent(), encryptwallet(), BitcoinApplication::requestShutdown(), stop(), ThreadImport(), and CCoinsViewDB::Upgrade().
ThreadImport()
void ThreadImport (std::vector< boost::filesystem::path > vImportFiles)
Definition at line 756 of file init.cpp.
References ActivateBestChain(), activeMasternodeManager, CWallet::AutoLockMasternodeCollaterals(), chainActive, cs_main, DEFAULT_STOPAFTERBLOCKIMPORT, Consensus::DEPLOYMENT_DIP0003, fDumpMempoolLater(), fReindex, fRequestShutdown(), GetBlockPosFilename(), GetBoolArg(), CChainParams::GetConsensus(), GetDataDir(), CActiveDeterministicMasternodeManager::Init(), InitBlockIndex(), CDSNotificationInterface::InitializeCurrentBlockTip(), LoadExternalBlockFile(), LoadMempool(), LOCK, LogPrintf, OpenBlockFile(), Params(), pblocktree, pdsNotificationInterface, CBlockIndex::pprev, pwalletMain, RenameOver(), RenameThread(), StartShutdown(), THRESHOLD_ACTIVE, CChain::Tip(), versionbitscache, VersionBitsState(), and CBlockTreeDB::WriteReindexing().
Referenced by AppInitMain().
ThreadSendAlert()
void ThreadSendAlert (CConnman & connman)
Definition at line 26 of file sendalert.cpp.
References CNode::addr, CLIENT_VERSION, CConnman::CONNECTIONS_ALL, CConnman::ForEachNode(), GetAdjustedTime(), CConnman::GetNodeCount(), HexStr(), IsArgSet(), LogPrintf, MilliSleep(), CUnsignedAlert::nCancel, CUnsignedAlert::nExpiration, CUnsignedAlert::nID, CUnsignedAlert::nMaxVer, CUnsignedAlert::nMinVer, CUnsignedAlert::nPriority, CUnsignedAlert::nRelayUntil, Params(), tinyformat::printf(), SER_NETWORK, ShutdownRequested(), CAlert::Sign(), CUnsignedAlert::strComment, CUnsignedAlert::strStatusBar, and CService::ToString().
Referenced by AppInitMain().
Variable Documentation
condvar_GenesisWait
CConditionVariable condvar_GenesisWait static
Definition at line 688 of file init.cpp.
Referenced by AppInitMain(), and BlockNotifyGenesisWait().
cs_GenesisWait
boost::mutex cs_GenesisWait static
Definition at line 687 of file init.cpp.
Referenced by AppInitMain(), and BlockNotifyGenesisWait().
DEFAULT_DISABLE_SAFEMODE
const bool DEFAULT_DISABLE_SAFEMODE = false static
Definition at line 103 of file init.cpp.
Referenced by HelpMessage(), and OnRPCPreCommand().
DEFAULT_PROXYRANDOMIZE
const bool DEFAULT_PROXYRANDOMIZE = true static
Definition at line 101 of file init.cpp.
Referenced by AppInitMain(), and HelpMessage().
DEFAULT_REST_ENABLE
const bool DEFAULT_REST_ENABLE = false static
Definition at line 102 of file init.cpp.
Referenced by AppInitServers(), and HelpMessage().
DEFAULT_STOPAFTERBLOCKIMPORT
const bool DEFAULT_STOPAFTERBLOCKIMPORT = false static
Definition at line 104 of file init.cpp.
Referenced by HelpMessage(), and ThreadImport().
FEE_ESTIMATES_FILENAME
const char* FEE_ESTIMATES_FILENAME ="fee_estimates.dat" static
Definition at line 133 of file init.cpp.
Referenced by AppInitMain(), and PrepareShutdown().
fFeeEstimatesInitialized
bool fFeeEstimatesInitialized = false
Definition at line 100 of file init.cpp.
Referenced by AppInitMain(), and PrepareShutdown().
fHaveGenesis
bool fHaveGenesis = false static
Definition at line 686 of file init.cpp.
Referenced by AppInitMain(), and BlockNotifyGenesisWait().
g_connman
std::unique_ptr<CConnman> g_connman
Definition at line 107 of file init.cpp.
Referenced by CMasternodeMan::AddDeterministicMasternodes(), llmq::CQuorumBlockProcessor::AddMinableCommitment(), addnode(), AppInitMain(), RPCConsole::banSelectedNode(), clearbanned(), disconnectnode(), RPCConsole::disconnectSelectedNode(), getaddednodeinfo(), getblocktemplate(), getconnectioncount(), getinfo(), CActiveDeterministicMasternodeManager::GetLocalAddress(), getnettotals(), ClientModel::getNetworkActive(), getnetworkinfo(), ClientModel::getNumConnections(), getpeerinfo(), ClientModel::getTotalBytesRecv(), ClientModel::getTotalBytesSent(), gobject_submit(), gobject_vote_conf(), Interrupt(), listbanned(), masternode_check(), masternode_connect(), masternodebroadcast(), mnsync(), ping(), PrepareShutdown(), OverviewPage::privateSendAuto(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), BanTablePriv::refreshBanlist(), PeerTablePriv::refreshPeers(), CMasternodeVerification::Relay(), CMasternodeMan::RemoveNonDeterministicMasternodes(), resendwallettransactions(), WalletModel::sendCoins(), sendmany(), SendMoney(), sendrawtransaction(), setban(), ClientModel::setNetworkActive(), setnetworkactive(), spork(), MasternodeList::StartAlias(), MasternodeList::StartAll(), RPCConsole::unbanSelectedNode(), voteraw(), and VoteWithMasternodeList().
globalVerifyHandle
std::unique_ptr<ECCVerifyHandle> globalVerifyHandle static
Definition at line 208 of file init.cpp.
Referenced by AppInitSanityChecks(), and Shutdown().
pcoinscatcher
CCoinsViewErrorCatcher* pcoinscatcher = NULL static
Definition at line 207 of file init.cpp.
Referenced by AppInitMain(), and PrepareShutdown().
pdsNotificationInterface
CDSNotificationInterface* pdsNotificationInterface = NULL static
Definition at line 114 of file init.cpp.
Referenced by AppInitMain(), PrepareShutdown(), and ThreadImport().
peerLogic
std::unique_ptr<PeerLogicValidation> peerLogic
Definition at line 108 of file init.cpp.
Referenced by AppInitMain(), and PrepareShutdown().
Released under the MIT license