Dash Core: src/masternode-payments.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
masternode-payments.cpp File Reference
#include "activemasternode.h"
#include "consensus/validation.h"
#include "governance-classes.h"
#include "init.h"
#include "masternode-payments.h"
#include "masternode-sync.h"
#include "masternodeman.h"
#include "messagesigner.h"
#include "netfulfilledman.h"
#include "netmessagemaker.h"
#include "spork.h"
#include "util.h"
#include "evo/deterministicmns.h"
#include <string>
Functions
bool IsOldBudgetBlockValueValid (const CBlock &block, int nBlockHeight, CAmount blockReward, std::string &strErrorRet)
bool IsBlockValueValid (const CBlock &block, int nBlockHeight, CAmount blockReward, std::string &strErrorRet)
IsBlockValueValid.
bool IsBlockPayeeValid (const CTransaction &txNew, int nBlockHeight, CAmount blockReward)
void FillBlockPayments (CMutableTransaction &txNew, int nBlockHeight, CAmount blockReward, std::vector< CTxOut > &voutMasternodePaymentsRet, std::vector< CTxOut > &voutSuperblockPaymentsRet)
std::string GetLegacyRequiredPaymentsString (int nBlockHeight)
std::string GetRequiredPaymentsString (int nBlockHeight, const CDeterministicMNCPtr &payee)
std::map< int, std::string > GetRequiredPaymentsStrings (int nStartHeight, int nEndHeight)
Variables
CMasternodePayments mnpayments
Object for who's going to get paid on which blocks.
CCriticalSection cs_vecPayees
CCriticalSection cs_mapMasternodeBlocks
CCriticalSection cs_mapMasternodePaymentVotes
Function Documentation
FillBlockPayments()
void FillBlockPayments (CMutableTransaction & txNew, int nBlockHeight, CAmount blockReward, std::vector< CTxOut > & voutMasternodePaymentsRet, std::vector< CTxOut > & voutSuperblockPaymentsRet)
Definition at line 234 of file masternode-payments.cpp.
References deterministicMNManager, CMasternodePayments::GetMasternodeTxOuts(), CSuperblockManager::GetSuperblockPayments(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CSporkManager::IsSporkActive(), CSuperblockManager::IsSuperblockTriggered(), LogPrint, mnpayments, SPORK_9_SUPERBLOCKS_ENABLED, sporkManager, CMutableTransaction::ToString(), and CMutableTransaction::vout.
Referenced by BlockAssembler::CreateNewBlock().
GetLegacyRequiredPaymentsString()
std::string GetLegacyRequiredPaymentsString (int nBlockHeight)
Definition at line 272 of file masternode-payments.cpp.
References CSuperblockManager::GetRequiredPaymentsString(), CMasternodePayments::GetRequiredPaymentsString(), CSuperblockManager::IsSuperblockTriggered(), and mnpayments.
Referenced by GetRequiredPaymentsStrings().
GetRequiredPaymentsString()
std::string GetRequiredPaymentsString (int nBlockHeight, const CDeterministicMNCPtr & payee)
Definition at line 283 of file masternode-payments.cpp.
References ExtractDestination(), CSuperblockManager::GetRequiredPaymentsString(), CSuperblockManager::IsSuperblockTriggered(), and CBase58Data::ToString().
Referenced by GetRequiredPaymentsStrings().
GetRequiredPaymentsStrings()
std::map<int, std::string> GetRequiredPaymentsStrings (int nStartHeight, int nEndHeight)
Definition at line 298 of file masternode-payments.cpp.
References chainActive, cs_main, deterministicMNManager, GetBlockHash(), GetLegacyRequiredPaymentsString(), CDeterministicMNManager::GetListAtChainTip(), CDeterministicMNManager::GetListForBlock(), CDeterministicMNList::GetMNPayee(), CDeterministicMNList::GetProjectedMNPayees(), GetRequiredPaymentsString(), CChain::Height(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), and LOCK.
Referenced by masternode_winners().
IsBlockPayeeValid()
bool IsBlockPayeeValid (const CTransaction & txNew, int nBlockHeight, CAmount blockReward)
Definition at line 168 of file masternode-payments.cpp.
References deterministicMNManager, fDebug, fLiteMode, CChainParams::GetConsensus(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CSporkManager::IsSporkActive(), CSuperblockManager::IsSuperblockTriggered(), CMasternodeSync::IsSynced(), CMasternodePayments::IsTransactionValid(), CSuperblockManager::IsValid(), LogPrint, LogPrintf, masternodeSync, mnpayments, Consensus::Params::nSuperblockStartBlock, Params(), SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT, SPORK_9_SUPERBLOCKS_ENABLED, sporkManager, and CTransaction::ToString().
Referenced by ConnectBlock().
IsBlockValueValid()
bool IsBlockValueValid (const CBlock & block, int nBlockHeight, CAmount blockReward, std::string & strErrorRet)
IsBlockValueValid.
TODO: all 4 functions do not belong here really, they should be refactored/moved somewhere (main.cpp ?)
Determine if coinbase outgoing created money is the correct value
Why is this needed?
In Dash some blocks are superblocks, which output much higher amounts of coins
Otherblocks are 10% lower in outgoing value, so in total, no extra coins are created
When non-superblocks are detected, the normal schedule should be maintained
Definition at line 83 of file masternode-payments.cpp.
References fDebug, fLiteMode, CChainParams::GetConsensus(), CSuperblock::GetPaymentsLimit(), IsOldBudgetBlockValueValid(), CSporkManager::IsSporkActive(), CSuperblockManager::IsSuperblockTriggered(), CMasternodeSync::IsSynced(), CSuperblockManager::IsValid(), CSuperblock::IsValidBlockHeight(), LogPrint, LogPrintf, masternodeSync, Consensus::Params::nBudgetPaymentsStartBlock, Consensus::Params::nSuperblockStartBlock, Params(), SPORK_9_SUPERBLOCKS_ENABLED, sporkManager, strprintf, and CBlock::vtx.
Referenced by ConnectBlock().
IsOldBudgetBlockValueValid()
bool IsOldBudgetBlockValueValid (const CBlock & block, int nBlockHeight, CAmount blockReward, std::string & strErrorRet)
Definition at line 29 of file masternode-payments.cpp.
References CChainParams::GetConsensus(), CMasternodeSync::IsSynced(), LogPrint, masternodeSync, Consensus::Params::nBudgetPaymentsCycleBlocks, Consensus::Params::nBudgetPaymentsStartBlock, Consensus::Params::nBudgetPaymentsWindowBlocks, Consensus::Params::nSuperblockStartBlock, Params(), strprintf, and CBlock::vtx.
Referenced by IsBlockValueValid().
Variable Documentation
cs_mapMasternodeBlocks
CCriticalSection cs_mapMasternodeBlocks
Definition at line 26 of file masternode-payments.cpp.
Referenced by CMasternodePayments::AddOrUpdatePaymentVote(), CMasternodePayments::CheckAndRemove(), CMasternodePayments::CheckBlockVotes(), CMasternodePayments::Clear(), CMasternodePayments::GetBlockTxOuts(), CMasternodePayments::GetRequiredPaymentsString(), CMasternodePayments::IsScheduled(), CMasternodePayments::IsTransactionValid(), ProcessGetData(), CMasternodePayments::RequestLowDataPaymentBlocks(), CMasternodePayments::Sync(), and CMasternode::UpdateLastPaid().
cs_mapMasternodePaymentVotes
CCriticalSection cs_mapMasternodePaymentVotes
Definition at line 27 of file masternode-payments.cpp.
Referenced by CMasternodePayments::AddOrUpdatePaymentVote(), CMasternodePayments::CheckAndRemove(), CMasternodePayments::CheckBlockVotes(), CMasternodePayments::Clear(), CMasternodePayments::HasVerifiedPaymentVote(), CMasternodePayments::ProcessMessage(), and CMasternodePayments::UpdateLastVote().
cs_vecPayees
CCriticalSection cs_vecPayees
Definition at line 25 of file masternode-payments.cpp.
Referenced by CMasternodeBlockPayees::AddPayee(), CMasternodeBlockPayees::GetBestPayee(), CMasternodeBlockPayees::GetRequiredPaymentsString(), CMasternodeBlockPayees::HasPayeeWithVotes(), and CMasternodeBlockPayees::IsTransactionValid().
mnpayments
CMasternodePayments mnpayments
Object for who's going to get paid on which blocks.
Definition at line 23 of file masternode-payments.cpp.
Referenced by AlreadyHave(), AppInitMain(), CMasternode::Check(), ComputeBlockVersion(), CMasternodeMan::CountEnabled(), CMasternodeMan::CountMasternodes(), FillBlockPayments(), CMasternodeMan::FindRandomNotInVec(), getblocktemplate(), GetLegacyRequiredPaymentsString(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), IsBlockPayeeValid(), CMasternodePaymentVote::IsValid(), CTxLockVote::IsValid(), CPrivateSendClientSession::JoinExistingQueue(), PrepareShutdown(), ProcessGetData(), ProcessMessage(), CMasternodeSync::ProcessTick(), CMasternodeBroadcast::SimpleCheck(), CPrivateSendClientSession::StartNewQueue(), CDSNotificationInterface::UpdatedBlockTip(), CMasternodeMan::UpdateLastPaid(), CMasternode::UpdateLastPaid(), and CInstantSend::Vote().
Released under the MIT license