Dash Core: src/rpc/mining.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
mining.cpp File Reference
#include "base58.h"
#include "amount.h"
#include "chain.h"
#include "chainparams.h"
#include "consensus/consensus.h"
#include "consensus/params.h"
#include "consensus/validation.h"
#include "core_io.h"
#include "init.h"
#include "validation.h"
#include "miner.h"
#include "net.h"
#include "pow.h"
#include "rpc/server.h"
#include "spork.h"
#include "txmempool.h"
#include "util.h"
#include "utilstrencodings.h"
#include "validationinterface.h"
#include "governance-classes.h"
#include "masternode-payments.h"
#include "masternode-sync.h"
#include "evo/deterministicmns.h"
#include "evo/specialtx.h"
#include "evo/cbtx.h"
#include <memory>
#include <stdint.h>
#include <boost/assign/list_of.hpp>
#include <boost/shared_ptr.hpp>
#include <univalue.h>
Classes
class submitblock_StateCatcher
Functions
UniValue GetNetworkHashPS (int lookup, int height)
Return average network hashes per second based on the last 'lookup' blocks, or from the last difficulty change if 'lookup' is nonpositive.
UniValue getnetworkhashps (const JSONRPCRequest &request)
UniValue generateBlocks (boost::shared_ptr< CReserveScript > coinbaseScript, int nGenerate, uint64_t nMaxTries, bool keepScript)
UniValue generate (const JSONRPCRequest &request)
UniValue generatetoaddress (const JSONRPCRequest &request)
UniValue getmininginfo (const JSONRPCRequest &request)
UniValue prioritisetransaction (const JSONRPCRequest &request)
static UniValue BIP22ValidationResult (const CValidationState &state)
std::string gbt_vb_name (const Consensus::DeploymentPos pos)
UniValue getblocktemplate (const JSONRPCRequest &request)
UniValue submitblock (const JSONRPCRequest &request)
UniValue estimatefee (const JSONRPCRequest &request)
UniValue estimatepriority (const JSONRPCRequest &request)
UniValue estimatesmartfee (const JSONRPCRequest &request)
UniValue estimatesmartpriority (const JSONRPCRequest &request)
void RegisterMiningRPCCommands (CRPCTable &t)
Register mining RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
BIP22ValidationResult()
static UniValue BIP22ValidationResult (const CValidationState & state) static
Definition at line 297 of file mining.cpp.
References CValidationState::GetRejectReason(), CValidationState::IsError(), CValidationState::IsInvalid(), CValidationState::IsValid(), JSONRPCError(), NullUniValue, and RPC_VERIFY_ERROR.
Referenced by getblocktemplate(), and submitblock().
estimatefee()
UniValue estimatefee (const JSONRPCRequest & request)
Definition at line 833 of file mining.cpp.
References CTxMemPool::estimateFee(), JSONRPCRequest::fHelp, UniValue::get_int(), CFeeRate::GetFeePerK(), HelpExampleCli(), mempool, JSONRPCRequest::params, RPCTypeCheck(), UniValue::size(), ValueFromAmount(), and UniValue::VNUM.
estimatepriority()
UniValue estimatepriority (const JSONRPCRequest & request)
Definition at line 866 of file mining.cpp.
References CTxMemPool::estimatePriority(), JSONRPCRequest::fHelp, UniValue::get_int(), HelpExampleCli(), mempool, JSONRPCRequest::params, RPCTypeCheck(), UniValue::size(), and UniValue::VNUM.
estimatesmartfee()
UniValue estimatesmartfee (const JSONRPCRequest & request)
Definition at line 893 of file mining.cpp.
References CURRENCY_UNIT, CTxMemPool::estimateSmartFee(), JSONRPCRequest::fHelp, UniValue::get_int(), CFeeRate::GetFeePerK(), HelpExampleCli(), mempool, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPCTypeCheck(), UniValue::size(), ValueFromAmount(), UniValue::VNUM, and UniValue::VOBJ.
estimatesmartpriority()
UniValue estimatesmartpriority (const JSONRPCRequest & request)
Definition at line 929 of file mining.cpp.
References CTxMemPool::estimateSmartPriority(), JSONRPCRequest::fHelp, UniValue::get_int(), HelpExampleCli(), mempool, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPCTypeCheck(), UniValue::size(), UniValue::VNUM, and UniValue::VOBJ.
gbt_vb_name()
std::string gbt_vb_name (const Consensus::DeploymentPos pos)
Definition at line 315 of file mining.cpp.
References BIP9DeploymentInfo::gbt_force, BIP9DeploymentInfo::name, and VersionBitsDeploymentInfo.
Referenced by getblocktemplate().
generate()
UniValue generate (const JSONRPCRequest & request)
Definition at line 157 of file mining.cpp.
References JSONRPCRequest::fHelp, generateBlocks(), UniValue::get_int(), GetMainSignals(), HelpExampleCli(), JSONRPCError(), JSONRPCRequest::params, RPC_INTERNAL_ERROR, RPC_WALLET_KEYPOOL_RAN_OUT, CMainSignals::ScriptForMining, and UniValue::size().
generateBlocks()
UniValue generateBlocks (boost::shared_ptr< CReserveScript > coinbaseScript, int nGenerate, uint64_t nMaxTries, bool keepScript)
Definition at line 107 of file mining.cpp.
References chainActive, CheckProofOfWork(), cs_main, CChainParams::GetConsensus(), CBlockHeader::GetHash(), CChain::Height(), IncrementExtraNonce(), JSONRPCError(), LOCK, CBlockHeader::nBits, CBlockHeader::nNonce, Params(), ProcessNewBlock(), UniValue::push_back(), RPC_INTERNAL_ERROR, CChain::Tip(), and UniValue::VARR.
Referenced by generate(), and generatetoaddress().
generatetoaddress()
UniValue generatetoaddress (const JSONRPCRequest & request)
Definition at line 193 of file mining.cpp.
References JSONRPCRequest::fHelp, generateBlocks(), UniValue::get_int(), UniValue::get_str(), GetScriptForDestination(), HelpExampleCli(), JSONRPCError(), JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, and UniValue::size().
getblocktemplate()
UniValue getblocktemplate (const JSONRPCRequest & request)
Definition at line 324 of file mining.cpp.
References atoi64(), prevector< N, T, Size, Diff >::begin(), BIP22ValidationResult(), Consensus::BIP9Deployment::bit, BLOCK_FAILED_MASK, BLOCK_VALID_SCRIPTS, chainActive, COINBASE_FLAGS, CConnman::CONNECTIONS_ALL, BlockAssembler::CreateNewBlock(), cs_main, csBestBlock, cvBlockChange, DecodeHexBlk(), deterministicMNManager, EncodeHexTx(), prevector< N, T, Size, Diff >::end(), ENTER_CRITICAL_SECTION, ExtractDestination(), fDIP0001ActiveAtTip, JSONRPCRequest::fHelp, find_value(), g_connman, BIP9DeploymentInfo::gbt_force, gbt_vb_name(), UniValue::get_int64(), UniValue::get_obj(), UniValue::get_str(), CBlockIndex::GetBlockHash(), CBlockHeader::GetBlockTime(), CMasternodePayments::GetBlockTxOuts(), CChainParams::GetConsensus(), CBlockHeader::GetHash(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), GetTime(), CTxMemPool::GetTransactionsUpdated(), COutPoint::hash, CBlockHeader::hashPrevBlock, CChain::Height(), HelpExampleCli(), HelpExampleRpc(), HexStr(), i64tostr(), UniValue::isArray(), CTransaction::IsCoinBase(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), IsInitialBlockDownload(), UniValue::isNull(), UniValue::isNum(), IsRPCRunning(), CSporkManager::IsSporkActive(), UniValue::isStr(), CMasternodeSync::IsSynced(), CBlockIndex::IsValid(), CSuperblock::IsValidBlockHeight(), CMasternodeSync::IsWinnersListSynced(), JSONRPCError(), LEAVE_CRITICAL_SECTION, LOCK, mapBlockIndex, masternodeSync, Consensus::MAX_VERSION_BITS_DEPLOYMENTS, MaxBlockSigOps(), MaxBlockSize(), mempool, mnpayments, BIP9DeploymentInfo::name, CBlockHeader::nBits, CBlockIndex::nHeight, Consensus::Params::nMasternodePaymentsStartBlock, CBlockHeader::nNonce, CBlockIndex::nStatus, Consensus::Params::nSuperblockStartBlock, NullUniValue, CBlockHeader::nVersion, OP_TRUE, Pair(), JSONRPCRequest::params, Params(), CTxIn::prevout, UniValue::push_back(), RPC_CLIENT_IN_INITIAL_DOWNLOAD, RPC_CLIENT_NOT_CONNECTED, RPC_CLIENT_P2P_DISABLED, RPC_DESERIALIZATION_ERROR, RPC_INVALID_PARAMETER, RPC_OUT_OF_MEMORY, RPC_TYPE_ERROR, arith_uint256::SetCompact(), base_blob< BITS >::SetHex(), UniValue::size(), SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT, SPORK_9_SUPERBLOCKS_ENABLED, sporkManager, strprintf, TestBlockValidity(), THRESHOLD_ACTIVE, THRESHOLD_DEFINED, THRESHOLD_FAILED, THRESHOLD_LOCKED_IN, THRESHOLD_STARTED, CChain::Tip(), CBase58Data::ToString(), UpdateTime(), UniValue::VARR, Consensus::Params::vDeployments, versionbitscache, VersionBitsDeploymentInfo, VersionBitsMask(), VersionBitsState(), CTransaction::vin, UniValue::VOBJ, and CBlock::vtx.
getmininginfo()
UniValue getmininginfo (const JSONRPCRequest & request)
Definition at line 226 of file mining.cpp.
References chainActive, cs_main, JSONRPCRequest::fHelp, GetDifficulty(), getnetworkhashps(), GetWarnings(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, mempool, nLastBlockSize, nLastBlockTx, Pair(), JSONRPCRequest::params, Params(), UniValue::push_back(), UniValue::size(), CTxMemPool::size(), and UniValue::VOBJ.
GetNetworkHashPS()
UniValue GetNetworkHashPS (int lookup, int height)
Return average network hashes per second based on the last 'lookup' blocks, or from the last difficulty change if 'lookup' is nonpositive.
If 'height' is nonnegative, compute the estimate at the time when a given block was found.
Definition at line 48 of file mining.cpp.
References chainActive, Consensus::Params::DifficultyAdjustmentInterval(), CBlockIndex::GetBlockTime(), CChainParams::GetConsensus(), base_uint< BITS >::getdouble(), CChain::Height(), CBlockIndex::nChainWork, CBlockIndex::nHeight, Params(), CBlockIndex::pprev, and CChain::Tip().
Referenced by getnetworkhashps().
getnetworkhashps()
UniValue getnetworkhashps (const JSONRPCRequest & request)
Definition at line 85 of file mining.cpp.
References cs_main, JSONRPCRequest::fHelp, UniValue::get_int(), GetNetworkHashPS(), HelpExampleCli(), HelpExampleRpc(), LOCK, JSONRPCRequest::params, and UniValue::size().
Referenced by getmininginfo().
prioritisetransaction()
UniValue prioritisetransaction (const JSONRPCRequest & request)
Definition at line 265 of file mining.cpp.
References cs_main, JSONRPCRequest::fHelp, UniValue::get_int64(), UniValue::get_real(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), LOCK, mempool, JSONRPCRequest::params, ParseHashStr(), CTxMemPool::PrioritiseTransaction(), and UniValue::size().
RegisterMiningRPCCommands()
void RegisterMiningRPCCommands (CRPCTable & t)
Register mining RPC commands.
Definition at line 983 of file mining.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
submitblock()
UniValue submitblock (const JSONRPCRequest & request)
Definition at line 767 of file mining.cpp.
References BIP22ValidationResult(), BLOCK_FAILED_MASK, BLOCK_VALID_SCRIPTS, cs_main, DecodeHexBlk(), JSONRPCRequest::fHelp, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), CBlockIndex::IsValid(), JSONRPCError(), LOCK, mapBlockIndex, CBlockIndex::nStatus, JSONRPCRequest::params, Params(), ProcessNewBlock(), RegisterValidationInterface(), RPC_DESERIALIZATION_ERROR, UniValue::size(), and UnregisterValidationInterface().
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "mining",             "getnetworkhashps",       &getnetworkhashps,       true,  {"nblocks","height"} },
    { "mining",             "getmininginfo",          &getmininginfo,          true,  {} },
    { "mining",             "prioritisetransaction",  &prioritisetransaction,  true,  {"txid","priority_delta","fee_delta"} },
    { "mining",             "getblocktemplate",       &getblocktemplate,       true,  {"template_request"} },
    { "mining",             "submitblock",            &submitblock,            true,  {"hexdata","parameters"} },
    { "generating",         "generate",               &generate,               true,  {"nblocks","maxtries"} },
    { "generating",         "generatetoaddress",      &generatetoaddress,      true,  {"nblocks","address","maxtries"} },
    { "util",               "estimatefee",            &estimatefee,            true,  {"nblocks"} },
    { "util",               "estimatepriority",       &estimatepriority,       true,  {"nblocks"} },
    { "util",               "estimatesmartfee",       &estimatesmartfee,       true,  {"nblocks"} },
    { "util",               "estimatesmartpriority",  &estimatesmartpriority,  true,  {"nblocks"} },
}
Definition at line 965 of file mining.cpp.
Referenced by RegisterMiningRPCCommands().
Released under the MIT license