Dash Core: src/rpc/misc.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
misc.cpp File Reference
#include "base58.h"
#include "clientversion.h"
#include "init.h"
#include "net.h"
#include "netbase.h"
#include "rpc/server.h"
#include "timedata.h"
#include "txmempool.h"
#include "util.h"
#include "utilstrencodings.h"
#include "validation.h"
#include "masternode-sync.h"
#include "spork.h"
#include <stdint.h>
#include <boost/assign/list_of.hpp>
#include <boost/algorithm/string.hpp>
#include <univalue.h>
Functions
UniValue getinfo (const JSONRPCRequest &request)
UniValue debug (const JSONRPCRequest &request)
UniValue mnsync (const JSONRPCRequest &request)
UniValue spork (const JSONRPCRequest &request)
UniValue validateaddress (const JSONRPCRequest &request)
CScript _createmultisig_redeemScript (const UniValue &params)
Used by addmultisigaddress / createmultisig:
UniValue createmultisig (const JSONRPCRequest &request)
UniValue verifymessage (const JSONRPCRequest &request)
UniValue signmessagewithprivkey (const JSONRPCRequest &request)
UniValue setmocktime (const JSONRPCRequest &request)
bool getAddressFromIndex (const int &type, const uint160 &hash, std::string &address)
bool getAddressesFromParams (const UniValue &params, std::vector< std::pair< uint160, int > > &addresses)
bool heightSort (std::pair< CAddressUnspentKey, CAddressUnspentValue > a, std::pair< CAddressUnspentKey, CAddressUnspentValue > b)
bool timestampSort (std::pair< CMempoolAddressDeltaKey, CMempoolAddressDelta > a, std::pair< CMempoolAddressDeltaKey, CMempoolAddressDelta > b)
UniValue getaddressmempool (const JSONRPCRequest &request)
UniValue getaddressutxos (const JSONRPCRequest &request)
UniValue getaddressdeltas (const JSONRPCRequest &request)
UniValue getaddressbalance (const JSONRPCRequest &request)
UniValue getaddresstxids (const JSONRPCRequest &request)
UniValue getspentinfo (const JSONRPCRequest &request)
static UniValue RPCLockedMemoryInfo ()
UniValue getmemoryinfo (const JSONRPCRequest &request)
UniValue echo (const JSONRPCRequest &request)
void RegisterMiscRPCCommands (CRPCTable &t)
Register miscellaneous RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
_createmultisig_redeemScript()
CScript _createmultisig_redeemScript (const UniValue & params)
Used by addmultisigaddress / createmultisig:
Definition at line 382 of file misc.cpp.
References UniValue::get_array(), UniValue::get_int(), UniValue::get_str(), CBitcoinAddress::GetKeyID(), CWallet::GetPubKey(), GetScriptForMultisig(), CPubKey::IsFullyValid(), IsHex(), CBitcoinAddress::IsValid(), MAX_SCRIPT_ELEMENT_SIZE, ParseHex(), pwalletMain, UniValue::size(), prevector< N, T, Size, Diff >::size(), and strprintf.
Referenced by addmultisigaddress(), and createmultisig().
createmultisig()
UniValue createmultisig (const JSONRPCRequest & request)
Definition at line 443 of file misc.cpp.
References _createmultisig_redeemScript(), prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), JSONRPCRequest::fHelp, HelpExampleCli(), HelpExampleRpc(), HexStr(), Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), CBase58Data::ToString(), and UniValue::VOBJ.
debug()
UniValue debug (const JSONRPCRequest & request)
Definition at line 118 of file misc.cpp.
References fDebug, JSONRPCRequest::fHelp, ForceSetArg(), ForceSetMultiArgs(), UniValue::get_str(), GetArg(), HelpExampleCli(), HelpExampleRpc(), JSONRPCRequest::params, and UniValue::size().
echo()
UniValue echo (const JSONRPCRequest & request)
Definition at line 1121 of file misc.cpp.
References JSONRPCRequest::fHelp, and JSONRPCRequest::params.
getaddressbalance()
UniValue getaddressbalance (const JSONRPCRequest & request)
Definition at line 893 of file misc.cpp.
References JSONRPCRequest::fHelp, getAddressesFromParams(), GetAddressIndex(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and UniValue::VOBJ.
getaddressdeltas()
UniValue getaddressdeltas (const JSONRPCRequest & request)
Definition at line 805 of file misc.cpp.
References JSONRPCRequest::fHelp, find_value(), UniValue::get_int(), UniValue::get_obj(), getAddressesFromParams(), getAddressFromIndex(), GetAddressIndex(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNum(), UniValue::isObject(), JSONRPCError(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
getAddressesFromParams()
bool getAddressesFromParams (const UniValue & params, std::vector< std::pair< uint160, int > > & addresses)
Definition at line 621 of file misc.cpp.
References find_value(), CBitcoinAddress::GetIndexKey(), UniValue::getValues(), UniValue::isArray(), JSONRPCError(), and RPC_INVALID_ADDRESS_OR_KEY.
Referenced by getaddressbalance(), getaddressdeltas(), getaddressmempool(), getaddresstxids(), and getaddressutxos().
getAddressFromIndex()
bool getAddressFromIndex (const int & type, const uint160 & hash, std::string & address)
Definition at line 609 of file misc.cpp.
References CBase58Data::ToString().
Referenced by getaddressdeltas(), getaddressmempool(), and getaddressutxos().
getaddressmempool()
UniValue getaddressmempool (const JSONRPCRequest & request)
Definition at line 667 of file misc.cpp.
References JSONRPCRequest::fHelp, getAddressesFromParams(), getAddressFromIndex(), CTxMemPool::getAddressIndex(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), mempool, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), timestampSort(), UniValue::VARR, and UniValue::VOBJ.
getaddresstxids()
UniValue getaddresstxids (const JSONRPCRequest & request)
Definition at line 949 of file misc.cpp.
References JSONRPCRequest::fHelp, find_value(), UniValue::get_int(), UniValue::get_obj(), getAddressesFromParams(), GetAddressIndex(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNum(), UniValue::isObject(), JSONRPCError(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and UniValue::VARR.
getaddressutxos()
UniValue getaddressutxos (const JSONRPCRequest & request)
Definition at line 738 of file misc.cpp.
References JSONRPCRequest::fHelp, getAddressesFromParams(), getAddressFromIndex(), GetAddressUnspent(), heightSort(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
getinfo()
UniValue getinfo (const JSONRPCRequest & request)
Note
Do not add or change anything in the information returned by this method. getinfo exists for backwards-compatibility only. It combines information from wildly different sources in the program, which is a mess, and is thus planned to be deprecated eventually.
Based on the source of the information, new information should be added to:
getblockchaininfo,
getnetworkinfo or
getwalletinfo
Or alternatively, create a specific query method for the information.
Definition at line 46 of file misc.cpp.
References chainActive, CLIENT_VERSION, CConnman::CONNECTIONS_ALL, cs_main, CWallet::cs_wallet, CURRENCY_UNIT, JSONRPCRequest::fHelp, fLiteMode, g_connman, CWallet::GetAnonymizedBalance(), CWallet::GetBalance(), GetDifficulty(), CFeeRate::GetFeePerK(), CWallet::GetKeyPoolSize(), CWallet::GetOldestKeyPoolTime(), GetProxy(), GetTimeOffset(), CWallet::GetVersion(), GetWarnings(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), proxyType::IsValid(), LOCK, LOCK2, minRelayTxFee, NET_IPV4, nWalletUnlockTime, Pair(), JSONRPCRequest::params, Params(), payTxFee, PROTOCOL_VERSION, proxyType::proxy, UniValue::push_back(), pwalletMain, UniValue::size(), CBaseChainParams::TESTNET, CService::ToStringIPPort(), ValueFromAmount(), and UniValue::VOBJ.
getmemoryinfo()
UniValue getmemoryinfo (const JSONRPCRequest & request)
Definition at line 1092 of file misc.cpp.
References JSONRPCRequest::fHelp, HelpExampleCli(), HelpExampleRpc(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPCLockedMemoryInfo(), UniValue::size(), and UniValue::VOBJ.
getspentinfo()
UniValue getspentinfo (const JSONRPCRequest & request)
Definition at line 1032 of file misc.cpp.
References CSpentIndexValue::blockHeight, JSONRPCRequest::fHelp, find_value(), UniValue::get_obj(), base_blob< BITS >::GetHex(), GetSpentIndex(), HelpExampleCli(), HelpExampleRpc(), CSpentIndexValue::inputIndex, UniValue::isObject(), UniValue::isStr(), JSONRPCError(), Pair(), JSONRPCRequest::params, ParseHashV(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), CSpentIndexValue::txid, and UniValue::VOBJ.
heightSort()
bool heightSort (std::pair< CAddressUnspentKey, CAddressUnspentValue > a, std::pair< CAddressUnspentKey, CAddressUnspentValue > b)
Definition at line 657 of file misc.cpp.
Referenced by getaddressutxos().
mnsync()
UniValue mnsync (const JSONRPCRequest & request)
Definition at line 143 of file misc.cpp.
References JSONRPCRequest::fHelp, g_connman, UniValue::get_str(), CMasternodeSync::GetAssetID(), CMasternodeSync::GetAssetName(), CMasternodeSync::GetAssetStartTime(), CMasternodeSync::GetAttempt(), CMasternodeSync::IsBlockchainSynced(), CMasternodeSync::IsFailed(), CMasternodeSync::IsMasternodeListSynced(), CMasternodeSync::IsSynced(), CMasternodeSync::IsWinnersListSynced(), masternodeSync, Pair(), JSONRPCRequest::params, UniValue::push_back(), CMasternodeSync::Reset(), UniValue::size(), CMasternodeSync::SwitchToNextAsset(), and UniValue::VOBJ.
RegisterMiscRPCCommands()
void RegisterMiscRPCCommands (CRPCTable & t)
Register miscellaneous RPC commands.
Definition at line 1163 of file misc.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RPCLockedMemoryInfo()
static UniValue RPCLockedMemoryInfo () static
Definition at line 1079 of file misc.cpp.
References LockedPool::Stats::chunks_free, LockedPool::Stats::chunks_used, LockedPool::Stats::free, LockedPoolManager::Instance(), LockedPool::Stats::locked, Pair(), UniValue::push_back(), LockedPool::stats(), LockedPool::Stats::total, LockedPool::Stats::used, and UniValue::VOBJ.
Referenced by getmemoryinfo().
setmocktime()
UniValue setmocktime (const JSONRPCRequest & request)
Definition at line 582 of file misc.cpp.
References cs_main, JSONRPCRequest::fHelp, UniValue::get_int64(), LOCK, CChainParams::MineBlocksOnDemand(), NullUniValue, JSONRPCRequest::params, Params(), RPCTypeCheck(), SetMockTime(), UniValue::size(), and UniValue::VNUM.
signmessagewithprivkey()
UniValue signmessagewithprivkey (const JSONRPCRequest & request)
Definition at line 540 of file misc.cpp.
References EncodeBase64(), JSONRPCRequest::fHelp, UniValue::get_str(), CHashWriter::GetHash(), CBitcoinSecret::GetKey(), HelpExampleCli(), HelpExampleRpc(), CKey::IsValid(), JSONRPCError(), JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, SER_GETHASH, CBitcoinSecret::SetString(), CKey::SignCompact(), UniValue::size(), and strMessageMagic.
spork()
UniValue spork (const JSONRPCRequest & request)
Definition at line 225 of file misc.cpp.
References CSporkManager::ExecuteSpork(), JSONRPCRequest::fHelp, g_connman, UniValue::get_int64(), UniValue::get_str(), CSporkManager::GetSporkIDByName(), CSporkManager::GetSporkNameByID(), CSporkManager::GetSporkValue(), HelpExampleCli(), HelpExampleRpc(), CSporkManager::IsSporkActive(), JSONRPCError(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_CLIENT_P2P_DISABLED, RPC_INVALID_PARAMETER, UniValue::size(), SPORK_END, SPORK_START, sporkManager, CSporkManager::UpdateSpork(), and UniValue::VOBJ.
Referenced by AlreadyHave(), ProcessGetData(), CSporkManager::ProcessSpork(), CSporkManager::SetPrivKey(), and CSporkManager::UpdateSpork().
timestampSort()
bool timestampSort (std::pair< CMempoolAddressDeltaKey, CMempoolAddressDelta > a, std::pair< CMempoolAddressDeltaKey, CMempoolAddressDelta > b)
Definition at line 662 of file misc.cpp.
Referenced by getaddressmempool().
validateaddress()
UniValue validateaddress (const JSONRPCRequest & request)
Definition at line 301 of file misc.cpp.
References prevector< N, T, Size, Diff >::begin(), cs_main, CWallet::cs_wallet, prevector< N, T, Size, Diff >::end(), JSONRPCRequest::fHelp, UniValue::get_str(), CCryptoKeyStore::GetHDChain(), base_blob< BITS >::GetHex(), CHDChain::GetID(), GetScriptForDestination(), HelpExampleCli(), HelpExampleRpc(), HexStr(), IsMine(), ISMINE_NO, ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, base_blob< BITS >::IsNull(), CBitcoinAddress::IsValid(), LOCK, LOCK2, CWallet::mapAddressBook, CWallet::mapHdPubKeys, CWallet::mapKeyMetadata, Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::pushKVs(), pwalletMain, UniValue::size(), and UniValue::VOBJ.
verifymessage()
UniValue verifymessage (const JSONRPCRequest & request)
Definition at line 486 of file misc.cpp.
References cs_main, DecodeBase64(), JSONRPCRequest::fHelp, UniValue::get_str(), CHashWriter::GetHash(), CPubKey::GetID(), CBitcoinAddress::GetKeyID(), HelpExampleCli(), HelpExampleRpc(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK, JSONRPCRequest::params, CPubKey::RecoverCompact(), RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, SER_GETHASH, UniValue::size(), and strMessageMagic.
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "control",            "debug",                  &debug,                  true,  {} },
    { "control",            "getinfo",                &getinfo,                true,  {} },
    { "control",            "getmemoryinfo",          &getmemoryinfo,          true,  {} },
    { "util",               "validateaddress",        &validateaddress,        true,  {"address"} },
    { "util",               "createmultisig",         &createmultisig,         true,  {"nrequired","keys"} },
    { "util",               "verifymessage",          &verifymessage,          true,  {"address","signature","message"} },
    { "util",               "signmessagewithprivkey", &signmessagewithprivkey, true,  {"privkey","message"} },
    { "blockchain",         "getspentinfo",           &getspentinfo,           false, {"json"} },
    { "addressindex",       "getaddressmempool",      &getaddressmempool,      true,  {"addresses"}  },
    { "addressindex",       "getaddressutxos",        &getaddressutxos,        false, {"addresses"} },
    { "addressindex",       "getaddressdeltas",       &getaddressdeltas,       false, {"addresses"} },
    { "addressindex",       "getaddresstxids",        &getaddresstxids,        false, {"addresses"} },
    { "addressindex",       "getaddressbalance",      &getaddressbalance,      false, {"addresses"} },
    { "dash",               "mnsync",                 &mnsync,                 true,  {} },
    { "dash",               "spork",                  &spork,                  true,  {"value"} },
    { "hidden",             "setmocktime",            &setmocktime,            true,  {"timestamp"}},
    { "hidden",             "echo",                   &echo,                   true,  {"arg0","arg1","arg2","arg3","arg4","arg5","arg6","arg7","arg8","arg9"}},
    { "hidden",             "echojson",               &echo,                   true,  {"arg0","arg1","arg2","arg3","arg4","arg5","arg6","arg7","arg8","arg9"}},
}
Definition at line 1134 of file misc.cpp.
Referenced by RegisterMiscRPCCommands().
Released under the MIT license