Dash Core: llmq Namespace Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
llmq Namespace Reference
Implementation of an insecure dummy DKG.
Classes
class CDummyCommitment
class CDummyContribution
class CDummyDKG
class CDummyDKGSession
class CFinalCommitment
class CFinalCommitmentTxPayload
class CLLMQUtils
class CQuorumBlockProcessor
Functions
bool CheckLLMQCommitment (const CTransaction &tx, const CBlockIndex *pindexPrev, CValidationState &state)
void InitLLMQSystem (CEvoDB &evoDb)
void DestroyLLMQSystem ()
Variables
CQuorumBlockProcessor * quorumBlockProcessor
static const std::string DB_MINED_COMMITMENT = "q_mc"
CDummyDKG * quorumDummyDKG
Detailed Description
Implementation of an insecure dummy DKG.
This is only used on testnet/devnet/regtest and will NEVER be used on mainnet. It is NOT SECURE AT ALL! It will actually be removed later when the real DKG is introduced.
It works by using a deterministic secure vector as the secure polynomial. Everyone can calculate this polynomial by himself, which makes it insecure by definition.
The purpose of this dummy implementation is to test final LLMQ commitments and simple PoSe on-chain. The dummy DKG first creates dummy commitments and propagates these to all nodes. They can then create a valid LLMQ commitment from these, which validates with the normal commitment validation code.
After these have been mined on-chain, they are indistinguishable from commitments created from the real DKG, making them good enough for testing.
The validMembers bitset is created from information of past dummy DKG sessions. If nodes failed to provide the dummy commitments, they will be marked as bad in the next session. This might create some chaos and finalizable commitments, but this is ok and will sort itself out after some sessions.
Function Documentation
CheckLLMQCommitment()
bool llmq::CheckLLMQCommitment (const CTransaction & tx, const CBlockIndex * pindexPrev, CValidationState & state)
Definition at line 158 of file quorums_commitment.cpp.
References llmq::CFinalCommitmentTxPayload::commitment, llmq::CFinalCommitmentTxPayload::CURRENT_VERSION, CValidationState::DoS(), llmq::CLLMQUtils::GetAllQuorumMembers(), CBlockIndex::GetAncestor(), CChainParams::GetConsensus(), GetTxPayload(), llmq::CFinalCommitment::IsNull(), Consensus::Params::llmqs, llmq::CFinalCommitment::llmqType, mapBlockIndex, llmq::CFinalCommitmentTxPayload::nHeight, CBlockIndex::nHeight, llmq::CFinalCommitmentTxPayload::nVersion, Params(), llmq::CFinalCommitment::quorumHash, REJECT_INVALID, llmq::CFinalCommitment::Verify(), and llmq::CFinalCommitment::VerifyNull().
Referenced by CheckSpecialTx().
DestroyLLMQSystem()
void llmq::DestroyLLMQSystem ()
Definition at line 20 of file quorums_init.cpp.
References quorumBlockProcessor, and quorumDummyDKG.
Referenced by AppInitMain(), and PrepareShutdown().
InitLLMQSystem()
void llmq::InitLLMQSystem (CEvoDB & evoDb)
Definition at line 14 of file quorums_init.cpp.
References evoDb, quorumBlockProcessor, and quorumDummyDKG.
Referenced by AppInitMain().
Variable Documentation
DB_MINED_COMMITMENT
const std::string llmq::DB_MINED_COMMITMENT = "q_mc" static
Definition at line 24 of file quorums_blockprocessor.cpp.
Referenced by llmq::CQuorumBlockProcessor::GetMinedCommitment(), llmq::CQuorumBlockProcessor::HasMinedCommitment(), llmq::CQuorumBlockProcessor::ProcessCommitment(), and llmq::CQuorumBlockProcessor::UndoBlock().
quorumBlockProcessor
CQuorumBlockProcessor * llmq::quorumBlockProcessor
Definition at line 22 of file quorums_blockprocessor.cpp.
Referenced by AlreadyHave(), llmq::CDummyDKG::CreateFinalCommitment(), BlockAssembler::CreateNewBlock(), DestroyLLMQSystem(), InitLLMQSystem(), ProcessGetData(), ProcessMessage(), ProcessSpecialTxsInBlock(), and UndoSpecialTxsInBlock().
quorumDummyDKG
CDummyDKG * llmq::quorumDummyDKG
Definition at line 26 of file quorums_dummydkg.cpp.
Referenced by AlreadyHave(), DestroyLLMQSystem(), InitLLMQSystem(), ProcessGetData(), ProcessMessage(), and CDSNotificationInterface::UpdatedBlockTip().
Released under the MIT license