Dash Core: immer::detail::hamts Namespace Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
immer::detail::hamts Namespace Reference
Classes
struct champ
struct champ_iterator
struct node
Typedefs
using bits_t = std::uint32_t
using bitmap_t = std::uint32_t
using count_t = std::uint32_t
using shift_t = std::uint32_t
using size_t = std::size_t
using hash_t = std::size_t
Functions
count_t popcount (bitmap_t x)
Variables
template<bits_t B, typename T = count_t>
constexpr T branches = T{1} << B
template<bits_t B, typename T = size_t>
constexpr T mask = branches<B, T> - 1
template<bits_t B, typename T = count_t>
constexpr T max_depth = (sizeof(hash_t) * 8 + B - 1) / B
template<bits_t B, typename T = count_t>
constexpr T max_shift = max_depth<B, count_t> * B
Typedef Documentation
bitmap_t
using immer::detail::hamts::bitmap_t = typedef std::uint32_t
Definition at line 18 of file bits.hpp.
bits_t
using immer::detail::hamts::bits_t = typedef std::uint32_t
Definition at line 17 of file bits.hpp.
count_t
using immer::detail::hamts::count_t = typedef std::uint32_t
Definition at line 19 of file bits.hpp.
hash_t
using immer::detail::hamts::hash_t = typedef std::size_t
Definition at line 22 of file bits.hpp.
shift_t
using immer::detail::hamts::shift_t = typedef std::uint32_t
Definition at line 20 of file bits.hpp.
size_t
using immer::detail::hamts::size_t = typedef std::size_t
Definition at line 21 of file bits.hpp.
Function Documentation
popcount()
count_t immer::detail::hamts::popcount (bitmap_t x) inline
Definition at line 38 of file bits.hpp.
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep_shift(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::equals_tree(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::for_each_chunk_traversal(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::get(), immer::detail::hamts::champ_iterator< T, Hash, Eq, MP, B >::step_down(), and immer::detail::hamts::champ_iterator< T, Hash, Eq, MP, B >::step_right().
Variable Documentation
branches
template<bits_t B, typename T = count_t> constexpr T immer::detail::hamts::branches = T{1} << B
Definition at line 25 of file bits.hpp.
mask
template<bits_t B, typename T = size_t> constexpr T immer::detail::hamts::mask = branches<B, T> - 1
Definition at line 28 of file bits.hpp.
Referenced by CSubNet::CSubNet(), GUIUtil::formatServicesStr(), CRollingBloomFilter::insert(), and secp256k1_scalar_cond_negate().
max_depth
template<bits_t B, typename T = count_t> constexpr T immer::detail::hamts::max_depth = (sizeof(hash_t) * 8 + B - 1) / B
Definition at line 31 of file bits.hpp.
max_shift
template<bits_t B, typename T = count_t> constexpr T immer::detail::hamts::max_shift = max_depth<B, count_t> * B
Definition at line 34 of file bits.hpp.
Released under the MIT license