Dash Core: src/net_processing.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
net_processing.h File Reference
#include "net.h"
#include "validationinterface.h"
Classes
class PeerLogicValidation
struct CNodeStateStats
Functions
void RegisterNodeSignals (CNodeSignals &nodeSignals)
Register with a network node to receive its signals.
void UnregisterNodeSignals (CNodeSignals &nodeSignals)
Unregister a network node.
bool GetNodeStateStats (NodeId nodeid, CNodeStateStats &stats)
Get statistics from node state.
void Misbehaving (NodeId nodeid, int howmuch)
Increase a node's misbehavior score.
bool ProcessMessages (CNode *pfrom, CConnman &connman, const std::atomic< bool > &interrupt)
Process protocol messages received from a given node.
bool SendMessages (CNode *pto, CConnman &connman, const std::atomic< bool > &interrupt)
Send queued protocol messages to be sent to a give node.
Variables
static const unsigned int DEFAULT_MAX_ORPHAN_TRANSACTIONS = 100
Default for -maxorphantx, maximum number of orphan transactions kept in memory.
static const int64_t ORPHAN_TX_EXPIRE_TIME = 20 * 60
Expiration time for orphan transactions in seconds.
static const int64_t ORPHAN_TX_EXPIRE_INTERVAL = 5 * 60
Minimum time between orphan transactions expire time checks in seconds.
static constexpr int64_t HEADERS_DOWNLOAD_TIMEOUT_BASE = 15 * 60 * 1000000
Headers download timeout expressed in microseconds Timeout = base + per_header * (expected number of headers)
static constexpr int64_t HEADERS_DOWNLOAD_TIMEOUT_PER_HEADER = 1000
static const unsigned int DEFAULT_BLOCK_RECONSTRUCTION_EXTRA_TXN = 100
Default number of orphan+recently-replaced txn to keep around for block reconstruction.
Function Documentation
GetNodeStateStats()
bool GetNodeStateStats (NodeId nodeid, CNodeStateStats & stats)
Get statistics from node state.
Definition at line 566 of file net_processing.cpp.
References cs_main, LOCK, CNodeStateStats::nCommonHeight, CNodeStateStats::nMisbehavior, CNodeStateStats::nSyncHeight, and CNodeStateStats::vHeightInFlight.
Referenced by getpeerinfo(), and PeerTablePriv::refreshPeers().
Misbehaving()
void Misbehaving (NodeId nodeid, int howmuch)
Increase a node's misbehavior score.
Definition at line 717 of file net_processing.cpp.
References DEFAULT_BANSCORE_THRESHOLD, GetArg(), and LogPrintf.
Referenced by PeerLogicValidation::BlockChecked(), CGovernanceManager::CheckMasternodeOrphanObjects(), CMasternodePaymentVote::IsValid(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), llmq::CDummyDKG::ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), ProcessMessage(), CSporkManager::ProcessSpork(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), SendBlockTransactions(), CMasternodeMan::SendVerifyReply(), CMasternodeMan::SyncAll(), and CGovernanceManager::SyncAll().
ProcessMessages()
bool ProcessMessages (CNode * pfrom, CConnman & connman, const std::atomic< bool > & interrupt)
Process protocol messages received from a given node.
Definition at line 3026 of file net_processing.cpp.
References base_blob< BITS >::begin(), CMessageHeader::CHECKSUM_SIZE, cs_main, CNode::cs_vProcessMsg, CNode::fDisconnect, CNode::fPauseRecv, CNode::fPauseSend, CMessageHeader::GetCommand(), CChainParams::GetConsensus(), CConnman::GetReceiveFloodSize(), CNode::GetRecvVersion(), CMessageHeader::HEADER_SIZE, HexStr(), CNode::id, INIT_PROTO_VERSION, CMessageHeader::IsValid(), LOCK, LogPrintf, CMessageHeader::MESSAGE_START_SIZE, CChainParams::MessageStart(), CMessageHeader::nMessageSize, CNode::nProcessQueueSize, Params(), CMessageHeader::pchChecksum, PrintExceptionContinue(), ProcessGetData(), ProcessMessage(), CConnman::PushMessage(), NetMsgType::REJECT, REJECT_MALFORMED, SanitizeString(), SendRejectsAndCheckIfBanned(), CNetMessage::SetVersion(), CNode::vProcessMsg, and CNode::vRecvGetData.
Referenced by RegisterNodeSignals(), and UnregisterNodeSignals().
RegisterNodeSignals()
void RegisterNodeSignals (CNodeSignals & nodeSignals)
Register with a network node to receive its signals.
Definition at line 581 of file net_processing.cpp.
References CNodeSignals::FinalizeNode, CNodeSignals::InitializeNode, CNodeSignals::ProcessMessages, ProcessMessages(), CNodeSignals::SendMessages, and SendMessages().
Referenced by AppInitMain().
SendMessages()
bool SendMessages (CNode * pto, CConnman & connman, const std::atomic< bool > & interrupt)
Send queued protocol messages to be sent to a give node.
Parameters
[in] pto The node which we are sending messages to.
[in] connman The connection manager for that node.
[in] interrupt Interrupt condition for processing threads
Returns
True if there is more work to be done
Definition at line 3163 of file net_processing.cpp.
References NetMsgType::ADDR, CNode::addrKnown, AdvertiseLocal(), AlreadyHave(), AVG_ADDRESS_BROADCAST_INTERVAL, AVG_LOCAL_ADDRESS_BROADCAST_INTERVAL, BIP0031_VERSION, BLOCK_DOWNLOAD_TIMEOUT_BASE, BLOCK_DOWNLOAD_TIMEOUT_PER_PEER, BLOCK_STALLING_TIMEOUT, CMainSignals::Broadcast, chainActive, NetMsgType::CMPCTBLOCK, CRollingBloomFilter::contains(), CNode::cs_filter, CNode::cs_inventory, cs_main, cs_most_recent_block, CNode::fClient, CNode::fDisconnect, CNode::filterInventoryKnown, fImporting, CNode::fInbound, CNode::fMasternode, fMasternodeMode, CNode::fOneShot, CNode::fPingQueued, fReindex, CNode::fRelayTxes, CNode::fSendMempool, CNode::fSuccessfullyConnected, CNode::fWhitelisted, GetAdjustedTime(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockTime(), CChainParams::GetConsensus(), NetMsgType::GETDATA, NetMsgType::GETHEADERS, CNode::GetId(), CService::GetKey(), CChain::GetLocator(), GetMainSignals(), GetRandBytes(), CNode::GetSendVersion(), GetTime(), GetTimeMicros(), CInv::hash, Consensus::Params::hashDevnetGenesisBlock, NetMsgType::HEADERS, HEADERS_DOWNLOAD_TIMEOUT_BASE, HEADERS_DOWNLOAD_TIMEOUT_PER_HEADER, CNode::id, CTxMemPool::info(), CTxMemPool::infoAll(), CRollingBloomFilter::insert(), NetMsgType::INV, INVENTORY_BROADCAST_INTERVAL, INVENTORY_BROADCAST_MAX_PER_1MB_BLOCK, IsInitialBlockDownload(), base_blob< BITS >::IsNull(), CBloomFilter::IsRelevantAndUpdate(), LOCK, LogPrint, LogPrintf, CNode::mapAskFor, mapBlockIndex, MAX_BLOCKS_IN_TRANSIT_PER_PEER, MAX_BLOCKS_TO_ANNOUNCE, MAX_INV_SZ, MaxBlockSize(), mempool, most_recent_block, most_recent_block_hash, MSG_BLOCK, MSG_TX, CBlockIndex::nHeight, nMaxTipAge, CNode::nNextAddrSend, CNode::nNextInvSend, CNode::nNextLocalAddrSend, CNode::nPingNonceSent, CNode::nPingUsecStart, Consensus::Params::nPowTargetSpacing, CNode::nStartingHeight, nTimeBestReceived(), CNode::nVersion, Params(), CNode::pfilter, pindexBestHeader, NetMsgType::PING, PING_INTERVAL, PoissonNextSend(), CBlockIndex::pprev, CNode::PushInventory(), CConnman::PushMessage(), ReadBlockFromDisk(), SendRejectsAndCheckIfBanned(), CNode::setAskFor, CNode::setInventoryTxToSend, CNode::timeLastMempoolReq, CChain::Tip(), base_blob< BITS >::ToString(), CInv::ToString(), TRY_LOCK, CNode::vAddrToSend, CNode::vBlockHashesToAnnounce, CNode::vInventoryBlockToSend, and CNode::vInventoryOtherToSend.
Referenced by RegisterNodeSignals(), and UnregisterNodeSignals().
UnregisterNodeSignals()
void UnregisterNodeSignals (CNodeSignals & nodeSignals)
Unregister a network node.
Definition at line 589 of file net_processing.cpp.
References CNodeSignals::FinalizeNode, CNodeSignals::InitializeNode, CNodeSignals::ProcessMessages, ProcessMessages(), CNodeSignals::SendMessages, and SendMessages().
Referenced by PrepareShutdown().
Variable Documentation
DEFAULT_BLOCK_RECONSTRUCTION_EXTRA_TXN
const unsigned int DEFAULT_BLOCK_RECONSTRUCTION_EXTRA_TXN = 100 static
Default number of orphan+recently-replaced txn to keep around for block reconstruction.
Definition at line 25 of file net_processing.h.
Referenced by AddToCompactExtraTransactions(), and HelpMessage().
DEFAULT_MAX_ORPHAN_TRANSACTIONS
const unsigned int DEFAULT_MAX_ORPHAN_TRANSACTIONS = 100 static
Default for -maxorphantx, maximum number of orphan transactions kept in memory.
Definition at line 13 of file net_processing.h.
Referenced by HelpMessage(), and ProcessMessage().
HEADERS_DOWNLOAD_TIMEOUT_BASE
constexpr int64_t HEADERS_DOWNLOAD_TIMEOUT_BASE = 15 * 60 * 1000000 static
Headers download timeout expressed in microseconds Timeout = base + per_header * (expected number of headers)
Definition at line 21 of file net_processing.h.
Referenced by ProcessMessage(), and SendMessages().
HEADERS_DOWNLOAD_TIMEOUT_PER_HEADER
constexpr int64_t HEADERS_DOWNLOAD_TIMEOUT_PER_HEADER = 1000 static
Definition at line 22 of file net_processing.h.
Referenced by ProcessMessage(), and SendMessages().
ORPHAN_TX_EXPIRE_INTERVAL
const int64_t ORPHAN_TX_EXPIRE_INTERVAL = 5 * 60 static
Minimum time between orphan transactions expire time checks in seconds.
Definition at line 17 of file net_processing.h.
Referenced by LimitOrphanTxSize().
ORPHAN_TX_EXPIRE_TIME
const int64_t ORPHAN_TX_EXPIRE_TIME = 20 * 60 static
Expiration time for orphan transactions in seconds.
Definition at line 15 of file net_processing.h.
Referenced by AddOrphanTx(), and LimitOrphanTxSize().
Released under the MIT license