Dash Core: src/random.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
random.cpp File Reference
#include "random.h"
#include "crypto/sha512.h"
#include "support/cleanse.h"
#include "util.h"
#include "utilstrencodings.h"
#include <stdlib.h>
#include <limits>
#include <sys/time.h>
#include <openssl/err.h>
#include <openssl/rand.h>
Functions
static void RandFailure ()
static int64_t GetPerformanceCounter ()
void RandAddSeed ()
static void RandAddSeedPerfmon ()
static void GetOSRand (unsigned char *ent32)
Get 32 bytes of system entropy.
void GetRandBytes (unsigned char *buf, int num)
Functions to gather random data via the OpenSSL PRNG.
void GetStrongRandBytes (unsigned char *out, int num)
Function to gather random data from multiple sources, failing whenever any of those source fail to provide a result.
uint64_t GetRand (uint64_t nMax)
int GetRandInt (int nMax)
uint256 GetRandHash ()
Function Documentation
GetOSRand()
static void GetOSRand (unsigned char * ent32) static
Get 32 bytes of system entropy.
Definition at line 95 of file random.cpp.
References RandFailure().
Referenced by GetStrongRandBytes().
GetPerformanceCounter()
static int64_t GetPerformanceCounter () inline static
Definition at line 33 of file random.cpp.
Referenced by RandAddSeed().
GetRand()
uint64_t GetRand (uint64_t nMax)
Definition at line 153 of file random.cpp.
References GetRandBytes().
Referenced by AdvertiseLocal(), AppInitMain(), CTxMemPool::check(), ConnectSocketByName(), convertSeed6(), GetRandInt(), PoissonNextSend(), ProcessMessage(), CWallet::ResendWalletTransactions(), CRollingBloomFilter::reset(), and CConnman::ThreadDNSAddressSeed().
GetRandBytes()
void GetRandBytes (unsigned char * buf, int num)
Functions to gather random data via the OpenSSL PRNG.
Definition at line 125 of file random.cpp.
References RandFailure().
Referenced by BOOST_AUTO_TEST_CASE(), CDBWrapper::CreateObfuscateKey(), ECC_Start(), FastRandomContext::FastRandomContext(), GenerateAuthCookie(), GetRand(), GetRandHash(), GetStrongRandBytes(), TorController::protocolinfo_cb(), SendMessages(), CKey::VerifyPubKey(), CAddrDB::Write(), and CBanDB::Write().
GetRandHash()
uint256 GetRandHash ()
Definition at line 173 of file random.cpp.
References GetRandBytes().
Referenced by BLSSign_Normal(), BOOST_AUTO_TEST_CASE(), BuildTestVectors(), CAddrMan::Clear(), and LimitOrphanTxSize().
GetRandInt()
int GetRandInt (int nMax)
Definition at line 168 of file random.cpp.
References GetRand().
Referenced by DKG::Bench_VerifyContributionShares(), BLSVerify_LargeAggregatedBlock1000PreVerified(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CMasternodeMan::CheckAndRemove(), CPrivateSendServer::CreateNewSession(), CWallet::CreateTransaction(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientManager::DoMaintenance(), CPrivateSend::GetDenominations(), CPrivateSendClientSession::PrepareDenominate(), CMasternodeMan::PrepareVerifyRequest(), CAddrMan::RandomInt(), CGovernanceManager::RequestGovernanceObject(), CWallet::SelectCoinsMinConf(), CWallet::SelectPSInOutPairsByDenominations(), and CConnman::ThreadOpenConnections().
GetStrongRandBytes()
void GetStrongRandBytes (unsigned char * out, int num)
Function to gather random data from multiple sources, failing whenever any of those source fail to provide a result.
Definition at line 132 of file random.cpp.
References CSHA512::Finalize(), GetOSRand(), GetRandBytes(), memcpy(), memory_cleanse(), RandAddSeedPerfmon(), and CSHA512::Write().
Referenced by CBLSIESEncryptedBlob::Encrypt(), CWallet::EncryptWallet(), CMnemonic::Generate(), CKeePassIntegrator::generateRandomKey(), CBLSIESMultiRecipientBlobs::InitEncrypt(), CKey::MakeNewKey(), and CBLSSecretKey::MakeNewKey().
RandAddSeed()
void RandAddSeed ()
Definition at line 46 of file random.cpp.
References GetPerformanceCounter(), and memory_cleanse().
Referenced by CInit::CInit(), and RandAddSeedPerfmon().
RandAddSeedPerfmon()
static void RandAddSeedPerfmon () static
Definition at line 54 of file random.cpp.
References GetTime(), LogPrint, LogPrintf, memory_cleanse(), and RandAddSeed().
Referenced by GetStrongRandBytes().
RandFailure()
static void RandFailure () static
Definition at line 27 of file random.cpp.
References LogPrintf.
Referenced by GetOSRand(), and GetRandBytes().
Released under the MIT license