Dash Core: src/rpc/rawtransaction.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
rawtransaction.cpp File Reference
#include "base58.h"
#include "chain.h"
#include "coins.h"
#include "consensus/validation.h"
#include "core_io.h"
#include "init.h"
#include "keystore.h"
#include "validation.h"
#include "merkleblock.h"
#include "net.h"
#include "policy/policy.h"
#include "primitives/transaction.h"
#include "rpc/server.h"
#include "script/script.h"
#include "script/script_error.h"
#include "script/sign.h"
#include "script/standard.h"
#include "txmempool.h"
#include "uint256.h"
#include "utilstrencodings.h"
#include "instantx.h"
#include "evo/specialtx.h"
#include "evo/providertx.h"
#include "evo/cbtx.h"
#include "llmq/quorums_commitment.h"
#include <stdint.h>
#include <boost/assign/list_of.hpp>
#include <univalue.h>
Functions
void ScriptPubKeyToJSON (const CScript &scriptPubKey, UniValue &out, bool fIncludeHex)
void TxToJSON (const CTransaction &tx, const uint256 hashBlock, UniValue &entry)
UniValue getrawtransaction (const JSONRPCRequest &request)
UniValue gettxoutproof (const JSONRPCRequest &request)
UniValue verifytxoutproof (const JSONRPCRequest &request)
UniValue createrawtransaction (const JSONRPCRequest &request)
UniValue decoderawtransaction (const JSONRPCRequest &request)
UniValue decodescript (const JSONRPCRequest &request)
static void TxInErrorToJSON (const CTxIn &txin, UniValue &vErrorsRet, const std::string &strMessage)
Pushes a JSON object for script verification or signing errors to vErrorsRet.
UniValue signrawtransaction (const JSONRPCRequest &request)
UniValue sendrawtransaction (const JSONRPCRequest &request)
void RegisterRawTransactionRPCCommands (CRPCTable &t)
Register raw transaction RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
createrawtransaction()
UniValue createrawtransaction (const JSONRPCRequest & request)
Definition at line 435 of file rawtransaction.cpp.
References AmountFromValue(), CURRENCY_UNIT, EncodeHexTx(), JSONRPCRequest::fHelp, find_value(), CBitcoinAddress::Get(), UniValue::get_array(), UniValue::get_int(), UniValue::get_int64(), UniValue::get_obj(), UniValue::getKeys(), GetScriptForDestination(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNull(), UniValue::isNum(), CBitcoinAddress::IsValid(), JSONRPCError(), CMutableTransaction::nLockTime, OP_RETURN, JSONRPCRequest::params, ParseHashO(), ParseHexV(), RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPCTypeCheck(), UniValue::size(), UniValue::VARR, CMutableTransaction::vin, UniValue::VNUM, UniValue::VOBJ, and CMutableTransaction::vout.
decoderawtransaction()
UniValue decoderawtransaction (const JSONRPCRequest & request)
Definition at line 548 of file rawtransaction.cpp.
References cs_main, CURRENCY_UNIT, DecodeHexTx(), JSONRPCRequest::fHelp, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, JSONRPCRequest::params, RPC_DESERIALIZATION_ERROR, RPCTypeCheck(), UniValue::size(), TxToJSON(), UniValue::VOBJ, and UniValue::VSTR.
decodescript()
UniValue decodescript (const JSONRPCRequest & request)
Definition at line 617 of file rawtransaction.cpp.
References JSONRPCRequest::fHelp, find_value(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), UniValue::isStr(), Pair(), JSONRPCRequest::params, ParseHexV(), UniValue::push_back(), RPCTypeCheck(), ScriptPubKeyToJSON(), UniValue::size(), UniValue::VOBJ, and UniValue::VSTR.
getrawtransaction()
UniValue getrawtransaction (const JSONRPCRequest & request)
Definition at line 199 of file rawtransaction.cpp.
References cs_main, CURRENCY_UNIT, EncodeHexTx(), JSONRPCRequest::fHelp, fTxIndex, UniValue::get_int(), GetTransaction(), HelpExampleCli(), HelpExampleRpc(), UniValue::isBool(), UniValue::isNum(), UniValue::isTrue(), JSONRPCError(), LOCK, Pair(), JSONRPCRequest::params, Params(), ParseHashV(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, UniValue::size(), TxToJSON(), and UniValue::VOBJ.
gettxoutproof()
UniValue gettxoutproof (const JSONRPCRequest & request)
Definition at line 311 of file rawtransaction.cpp.
References AccessByTxid(), CDataStream::begin(), chainActive, cs_main, CDataStream::end(), JSONRPCRequest::fHelp, UniValue::get_array(), UniValue::get_str(), GetTransaction(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), HexStr(), IsHex(), base_blob< BITS >::IsNull(), Coin::IsSpent(), JSONRPCError(), LOCK, mapBlockIndex, Coin::nHeight, JSONRPCRequest::params, Params(), pcoinsTip, PROTOCOL_VERSION, ReadBlockFromDisk(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, SER_NETWORK, UniValue::size(), uint256S(), and CBlock::vtx.
RegisterRawTransactionRPCCommands()
void RegisterRawTransactionRPCCommands (CRPCTable & t)
Register raw transaction RPC commands.
Definition at line 1033 of file rawtransaction.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
ScriptPubKeyToJSON()
void ScriptPubKeyToJSON (const CScript & scriptPubKey, UniValue & out, bool fIncludeHex)
Definition at line 43 of file rawtransaction.cpp.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), ExtractDestinations(), GetTxnOutputType(), HexStr(), Pair(), UniValue::push_back(), ScriptToAsmStr(), and UniValue::VARR.
Referenced by decodescript(), gettxout(), rest_getutxos(), and TxToJSON().
sendrawtransaction()
UniValue sendrawtransaction (const JSONRPCRequest & request)
Definition at line 937 of file rawtransaction.cpp.
References AcceptToMemoryPool(), CCoinsViewCache::AccessCoin(), cs_main, DecodeHexTx(), CTxMemPool::exists(), JSONRPCRequest::fHelp, g_connman, UniValue::get_bool(), UniValue::get_str(), base_blob< BITS >::GetHex(), CValidationState::GetRejectCode(), CValidationState::GetRejectReason(), HelpExampleCli(), HelpExampleRpc(), instantsend, CValidationState::IsInvalid(), Coin::IsSpent(), JSONRPCError(), LOCK, MakeTransactionRef(), maxTxFee, mempool, JSONRPCRequest::params, pcoinsTip, CInstantSend::ProcessTxLockRequest(), RPC_CLIENT_P2P_DISABLED, RPC_DESERIALIZATION_ERROR, RPC_TRANSACTION_ALREADY_IN_CHAIN, RPC_TRANSACTION_ERROR, RPC_TRANSACTION_REJECTED, RPCTypeCheck(), UniValue::size(), strprintf, UniValue::VBOOL, and UniValue::VSTR.
signrawtransaction()
UniValue signrawtransaction (const JSONRPCRequest & request)
Definition at line 679 of file rawtransaction.cpp.
References CCoinsViewCache::AccessCoin(), CCoinsViewCache::AddCoin(), CBasicKeyStore::AddCScript(), CKeyStore::AddKey(), CScript::clear(), CombineSignatures(), CTxMemPool::cs, cs_main, CWallet::cs_wallet, UniValue::empty(), CDataStream::empty(), EncodeHexTx(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, find_value(), UniValue::get_array(), UniValue::get_int(), UniValue::get_obj(), UniValue::get_str(), CBitcoinSecret::GetKey(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), UniValue::isNull(), UniValue::isObject(), Coin::IsSpent(), CKey::IsValid(), JSONRPCError(), LOCK, LOCK2, mempool, Coin::nHeight, CTxOut::nValue, Coin::out, Pair(), JSONRPCRequest::params, ParseHashO(), ParseHexO(), ParseHexV(), pcoinsTip, CTxIn::prevout, PROTOCOL_VERSION, UniValue::push_back(), pwalletMain, RPC_DESERIALIZATION_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPCTypeCheck(), RPCTypeCheckObj(), SCRIPT_ERR_OK, ScriptErrorString(), CTxOut::scriptPubKey, CTxIn::scriptSig, ScriptToAsmStr(), SER_NETWORK, CCoinsViewBacked::SetBackend(), CBitcoinSecret::SetString(), SIGHASH_ALL, SIGHASH_ANYONECANPAY, SIGHASH_NONE, SIGHASH_SINGLE, SignSignature(), UniValue::size(), STANDARD_SCRIPT_VERIFY_FLAGS, TxInErrorToJSON(), UniValue::VARR, VerifyScript(), CMutableTransaction::vin, UniValue::VNUM, UniValue::VOBJ, CMutableTransaction::vout, and UniValue::VSTR.
TxInErrorToJSON()
static void TxInErrorToJSON (const CTxIn & txin, UniValue & vErrorsRet, const std::string & strMessage) static
Pushes a JSON object for script verification or signing errors to vErrorsRet.
Definition at line 668 of file rawtransaction.cpp.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), COutPoint::hash, HexStr(), COutPoint::n, CTxIn::nSequence, Pair(), CTxIn::prevout, UniValue::push_back(), CTxIn::scriptSig, base_blob< BITS >::ToString(), and UniValue::VOBJ.
Referenced by signrawtransaction().
TxToJSON()
void TxToJSON (const CTransaction & tx, const uint256 hashBlock, UniValue & entry)
Definition at line 67 of file rawtransaction.cpp.
References CSpentIndexValue::addressHash, CSpentIndexValue::addressType, prevector< N, T, Size, Diff >::begin(), CSpentIndexValue::blockHeight, chainActive, CChain::Contains(), prevector< N, T, Size, Diff >::end(), CBlockIndex::GetBlockTime(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), GetSerializeSize(), GetSpentIndex(), GetTxPayload(), COutPoint::hash, CChain::Height(), HexStr(), CSpentIndexValue::inputIndex, instantsend, CTransaction::IsCoinBase(), CInstantSend::IsLockedInstantSendTransaction(), base_blob< BITS >::IsNull(), mapBlockIndex, COutPoint::n, CBlockIndex::nHeight, CTransaction::nLockTime, CTxIn::nSequence, CTransaction::nType, CTxOut::nValue, CTransaction::nVersion, Pair(), CTxIn::prevout, PROTOCOL_VERSION, UniValue::push_back(), CSpentIndexValue::satoshis, CTxOut::scriptPubKey, ScriptPubKeyToJSON(), CTxIn::scriptSig, ScriptToAsmStr(), SER_NETWORK, CCbTx::ToJson(), CProRegTx::ToJson(), CProUpServTx::ToJson(), llmq::CFinalCommitmentTxPayload::ToJson(), CProUpRegTx::ToJson(), CProUpRevTx::ToJson(), CBase58Data::ToString(), TRANSACTION_COINBASE, TRANSACTION_PROVIDER_REGISTER, TRANSACTION_PROVIDER_UPDATE_REGISTRAR, TRANSACTION_PROVIDER_UPDATE_REVOKE, TRANSACTION_PROVIDER_UPDATE_SERVICE, TRANSACTION_QUORUM_COMMITMENT, CSpentIndexValue::txid, ValueFromAmount(), UniValue::VARR, CTransaction::vExtraPayload, CTransaction::vin, UniValue::VOBJ, and CTransaction::vout.
Referenced by blockToJSON(), decoderawtransaction(), getrawtransaction(), getspecialtxes(), and rest_tx().
verifytxoutproof()
UniValue verifytxoutproof (const JSONRPCRequest & request)
Definition at line 397 of file rawtransaction.cpp.
References chainActive, CChain::Contains(), cs_main, JSONRPCRequest::fHelp, base_blob< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, mapBlockIndex, JSONRPCRequest::params, ParseHexV(), PROTOCOL_VERSION, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, UniValue::size(), and UniValue::VARR.
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "rawtransactions",    "getrawtransaction",      &getrawtransaction,      true,  {"txid","verbose"} },
    { "rawtransactions",    "createrawtransaction",   &createrawtransaction,   true,  {"inputs","outputs","locktime"} },
    { "rawtransactions",    "decoderawtransaction",   &decoderawtransaction,   true,  {"hexstring"} },
    { "rawtransactions",    "decodescript",           &decodescript,           true,  {"hexstring"} },
    { "rawtransactions",    "sendrawtransaction",     &sendrawtransaction,     false, {"hexstring","allowhighfees","instantsend","bypasslimits"} },
    { "rawtransactions",    "signrawtransaction",     &signrawtransaction,     false, {"hexstring","prevtxs","privkeys","sighashtype"} },
    { "blockchain",         "gettxoutproof",          &gettxoutproof,          true,  {"txids", "blockhash"} },
    { "blockchain",         "verifytxoutproof",       &verifytxoutproof,       true,  {"proof"} },
}
Definition at line 1019 of file rawtransaction.cpp.
Referenced by RegisterRawTransactionRPCCommands().
Released under the MIT license