Dash Core: src/rest.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
rest.cpp File Reference
#include "chain.h"
#include "chainparams.h"
#include "primitives/block.h"
#include "primitives/transaction.h"
#include "validation.h"
#include "httpserver.h"
#include "rpc/server.h"
#include "streams.h"
#include "sync.h"
#include "txmempool.h"
#include "utilstrencodings.h"
#include "version.h"
#include <boost/algorithm/string.hpp>
#include <univalue.h>
Classes
struct CCoin
Enumerations
enum RetFormat { RF_UNDEF, RF_BINARY, RF_HEX, RF_JSON }
Functions
void TxToJSON (const CTransaction &tx, const uint256 hashBlock, UniValue &entry)
UniValue blockToJSON (const CBlock &block, const CBlockIndex *blockindex, bool txDetails=false)
UniValue mempoolInfoToJSON ()
UniValue mempoolToJSON (bool fVerbose=false)
void ScriptPubKeyToJSON (const CScript &scriptPubKey, UniValue &out, bool fIncludeHex)
UniValue blockheaderToJSON (const CBlockIndex *blockindex)
static bool RESTERR (HTTPRequest *req, enum HTTPStatusCode status, std::string message)
static enum RetFormat ParseDataFormat (std::string &param, const std::string &strReq)
static std::string AvailableDataFormatsString ()
static bool ParseHashStr (const std::string &strReq, uint256 &v)
static bool CheckWarmup (HTTPRequest *req)
static bool rest_headers (HTTPRequest *req, const std::string &strURIPart)
static bool rest_block (HTTPRequest *req, const std::string &strURIPart, bool showTxDetails)
static bool rest_block_extended (HTTPRequest *req, const std::string &strURIPart)
static bool rest_block_notxdetails (HTTPRequest *req, const std::string &strURIPart)
UniValue getblockchaininfo (const JSONRPCRequest &request)
static bool rest_chaininfo (HTTPRequest *req, const std::string &strURIPart)
static bool rest_mempool_info (HTTPRequest *req, const std::string &strURIPart)
static bool rest_mempool_contents (HTTPRequest *req, const std::string &strURIPart)
static bool rest_tx (HTTPRequest *req, const std::string &strURIPart)
static bool rest_getutxos (HTTPRequest *req, const std::string &strURIPart)
bool StartREST ()
Start HTTP REST subsystem.
void InterruptREST ()
Interrupt RPC REST subsystem.
void StopREST ()
Stop HTTP REST subsystem.
Variables
static const size_t MAX_GETUTXOS_OUTPOINTS = 15
struct {
enum RetFormat rf
const char * name
} rf_names []
struct {
const char * prefix
bool(* handler)(HTTPRequest *req, const
std::string &strReq)
} uri_prefixes []
Enumeration Type Documentation
RetFormat
enum RetFormat
Enumerator
RF_UNDEF
RF_BINARY
RF_HEX
RF_JSON
Definition at line 25 of file rest.cpp.
Function Documentation
AvailableDataFormatsString()
static std::string AvailableDataFormatsString () static
Definition at line 96 of file rest.cpp.
References ARRAYLEN, name, and rf_names.
Referenced by rest_block(), rest_getutxos(), and rest_tx().
blockheaderToJSON()
UniValue blockheaderToJSON (const CBlockIndex * blockindex)
Definition at line 83 of file blockchain.cpp.
References chainActive, CChain::Contains(), CBlockIndex::GetBlockHash(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), CBlockIndex::hashMerkleRoot, CChain::Height(), CBlockIndex::nBits, CBlockIndex::nChainWork, CChain::Next(), CBlockIndex::nHeight, CBlockIndex::nNonce, CBlockIndex::nTime, CBlockIndex::nVersion, Pair(), CBlockIndex::pprev, UniValue::push_back(), strprintf, and UniValue::VOBJ.
Referenced by getblockheader(), getblockheaders(), and rest_headers().
blockToJSON()
UniValue blockToJSON (const CBlock & block, const CBlockIndex * blockindex, bool txDetails = false)
Definition at line 111 of file blockchain.cpp.
References chainActive, CChain::Contains(), CBlockIndex::GetBlockHash(), CBlockHeader::GetBlockTime(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), GetSerializeSize(), GetTxPayload(), CBlockHeader::hashMerkleRoot, CChain::Height(), CBlockHeader::nBits, CBlockIndex::nChainWork, CChain::Next(), CBlockIndex::nHeight, CBlockHeader::nNonce, CBlockHeader::nVersion, Pair(), CBlockIndex::pprev, PROTOCOL_VERSION, UniValue::push_back(), SER_NETWORK, strprintf, CCbTx::ToJson(), TxToJSON(), UniValue::VARR, UniValue::VOBJ, and CBlock::vtx.
Referenced by getblock(), and rest_block().
CheckWarmup()
static bool CheckWarmup (HTTPRequest * req) static
Definition at line 121 of file rest.cpp.
References HTTP_SERVICE_UNAVAILABLE, RESTERR(), and RPCIsInWarmup().
Referenced by rest_block(), rest_chaininfo(), rest_getutxos(), rest_headers(), rest_mempool_contents(), rest_mempool_info(), and rest_tx().
getblockchaininfo()
UniValue getblockchaininfo (const JSONRPCRequest & request)
Definition at line 1248 of file blockchain.cpp.
References BIP9SoftForkDescPushBack(), BLOCK_HAVE_DATA, chainActive, cs_main, Consensus::DEPLOYMENT_BIP147, Consensus::DEPLOYMENT_CSV, Consensus::DEPLOYMENT_DIP0001, Consensus::DEPLOYMENT_DIP0003, JSONRPCRequest::fHelp, fPruneMode, CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), GuessVerificationProgress(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, CBlockIndex::nChainWork, CBlockIndex::nHeight, CBlockIndex::nStatus, Pair(), JSONRPCRequest::params, Params(), pindexBestHeader, CBlockIndex::pprev, UniValue::push_back(), UniValue::size(), SoftForkDesc(), CChain::Tip(), UniValue::VARR, and UniValue::VOBJ.
Referenced by rest_chaininfo().
InterruptREST()
void InterruptREST ()
Interrupt RPC REST subsystem.
Definition at line 615 of file rest.cpp.
Referenced by Interrupt().
mempoolInfoToJSON()
UniValue mempoolInfoToJSON ()
Definition at line 1476 of file blockchain.cpp.
References DEFAULT_MAX_MEMPOOL_SIZE, CTxMemPool::DynamicMemoryUsage(), GetArg(), CFeeRate::GetFeePerK(), CTxMemPool::GetMinFee(), CTxMemPool::GetTotalTxSize(), mempool, Pair(), UniValue::push_back(), CTxMemPool::size(), ValueFromAmount(), and UniValue::VOBJ.
Referenced by getmempoolinfo(), and rest_mempool_info().
mempoolToJSON()
UniValue mempoolToJSON (bool fVerbose = false)
Definition at line 402 of file blockchain.cpp.
References CTxMemPool::cs, entryToJSON(), CTransaction::GetHash(), CTxMemPoolEntry::GetTx(), LOCK, CTxMemPool::mapTx, mempool, Pair(), UniValue::push_back(), CTxMemPool::queryHashes(), base_blob< BITS >::ToString(), UniValue::VARR, and UniValue::VOBJ.
Referenced by getrawmempool(), and rest_mempool_contents().
ParseDataFormat()
static enum RetFormat ParseDataFormat (std::string & param, const std::string & strReq) static
Definition at line 75 of file rest.cpp.
References ARRAYLEN, name, and rf_names.
Referenced by rest_block(), rest_chaininfo(), rest_getutxos(), rest_headers(), rest_mempool_contents(), rest_mempool_info(), and rest_tx().
ParseHashStr()
static bool ParseHashStr (const std::string & strReq, uint256 & v) static
Definition at line 112 of file rest.cpp.
References IsHex(), and base_blob< BITS >::SetHex().
Referenced by rest_block(), rest_headers(), and rest_tx().
rest_block()
static bool rest_block (HTTPRequest * req, const std::string & strURIPart, bool showTxDetails) static
Definition at line 203 of file rest.cpp.
References AvailableDataFormatsString(), CDataStream::begin(), BLOCK_HAVE_DATA, blockToJSON(), CheckWarmup(), cs_main, CDataStream::end(), fHavePruned, HexStr(), HTTP_BAD_REQUEST, HTTP_NOT_FOUND, HTTP_OK, LOCK, mapBlockIndex, CBlockIndex::nStatus, CBlockIndex::nTx, Params(), ParseDataFormat(), ParseHashStr(), PROTOCOL_VERSION, ReadBlockFromDisk(), RESTERR(), rf, RF_BINARY, RF_HEX, RF_JSON, SER_NETWORK, CDataStream::str(), UniValue::write(), HTTPRequest::WriteHeader(), and HTTPRequest::WriteReply().
Referenced by rest_block_extended(), and rest_block_notxdetails().
rest_block_extended()
static bool rest_block_extended (HTTPRequest * req, const std::string & strURIPart) static
Definition at line 266 of file rest.cpp.
References rest_block().
rest_block_notxdetails()
static bool rest_block_notxdetails (HTTPRequest * req, const std::string & strURIPart) static
Definition at line 271 of file rest.cpp.
References rest_block().
rest_chaininfo()
static bool rest_chaininfo (HTTPRequest * req, const std::string & strURIPart) static
Definition at line 279 of file rest.cpp.
References CheckWarmup(), getblockchaininfo(), HTTP_NOT_FOUND, HTTP_OK, JSONRPCRequest::params, ParseDataFormat(), RESTERR(), rf, RF_JSON, UniValue::VARR, UniValue::write(), HTTPRequest::WriteHeader(), and HTTPRequest::WriteReply().
rest_getutxos()
static bool rest_getutxos (HTTPRequest * req, const std::string & strURIPart) static
Definition at line 407 of file rest.cpp.
References AvailableDataFormatsString(), CDataStream::begin(), chainActive, CheckWarmup(), CTxMemPool::cs, cs_main, CDataStream::end(), CBlockIndex::GetBlockHash(), CCoinsViewCache::GetCoin(), base_blob< BITS >::GetHex(), CChain::Height(), HexStr(), HTTP_BAD_REQUEST, HTTP_NOT_FOUND, HTTP_OK, IsHex(), CTxMemPool::isSpent(), LOCK2, MAX_GETUTXOS_OUTPOINTS, mempool, CCoin::nHeight, CTxOut::nValue, CCoin::out, Pair(), ParseDataFormat(), ParseHex(), ParseInt32(), pcoinsTip, PROTOCOL_VERSION, UniValue::push_back(), HTTPRequest::ReadBody(), RESTERR(), rf, RF_BINARY, RF_HEX, RF_JSON, CTxOut::scriptPubKey, ScriptPubKeyToJSON(), SER_NETWORK, CCoinsViewBacked::SetBackend(), base_blob< BITS >::SetHex(), CDataStream::str(), strprintf, CChain::Tip(), ValueFromAmount(), UniValue::VARR, UniValue::VOBJ, UniValue::write(), HTTPRequest::WriteHeader(), and HTTPRequest::WriteReply().
rest_headers()
static bool rest_headers (HTTPRequest * req, const std::string & strURIPart) static
Definition at line 129 of file rest.cpp.
References CDataStream::begin(), blockheaderToJSON(), chainActive, CheckWarmup(), CChain::Contains(), count, cs_main, CDataStream::end(), CBlockIndex::GetBlockHeader(), HexStr(), HTTP_BAD_REQUEST, HTTP_NOT_FOUND, HTTP_OK, LOCK, mapBlockIndex, CChain::Next(), ParseDataFormat(), ParseHashStr(), PROTOCOL_VERSION, UniValue::push_back(), RESTERR(), rf, RF_BINARY, RF_HEX, RF_JSON, SER_NETWORK, CDataStream::str(), UniValue::VARR, UniValue::write(), HTTPRequest::WriteHeader(), and HTTPRequest::WriteReply().
rest_mempool_contents()
static bool rest_mempool_contents (HTTPRequest * req, const std::string & strURIPart) static
Definition at line 330 of file rest.cpp.
References CheckWarmup(), HTTP_NOT_FOUND, HTTP_OK, mempoolToJSON(), ParseDataFormat(), RESTERR(), rf, RF_JSON, UniValue::write(), HTTPRequest::WriteHeader(), and HTTPRequest::WriteReply().
rest_mempool_info()
static bool rest_mempool_info (HTTPRequest * req, const std::string & strURIPart) static
Definition at line 305 of file rest.cpp.
References CheckWarmup(), HTTP_NOT_FOUND, HTTP_OK, mempoolInfoToJSON(), ParseDataFormat(), RESTERR(), rf, RF_JSON, UniValue::write(), HTTPRequest::WriteHeader(), and HTTPRequest::WriteReply().
rest_tx()
static bool rest_tx (HTTPRequest * req, const std::string & strURIPart) static
Definition at line 355 of file rest.cpp.
References AvailableDataFormatsString(), CDataStream::begin(), CheckWarmup(), CDataStream::end(), GetTransaction(), HexStr(), HTTP_BAD_REQUEST, HTTP_NOT_FOUND, HTTP_OK, Params(), ParseDataFormat(), ParseHashStr(), PROTOCOL_VERSION, RESTERR(), rf, RF_BINARY, RF_HEX, RF_JSON, SER_NETWORK, CDataStream::str(), TxToJSON(), UniValue::VOBJ, UniValue::write(), HTTPRequest::WriteHeader(), and HTTPRequest::WriteReply().
RESTERR()
static bool RESTERR (HTTPRequest * req, enum HTTPStatusCode status, std::string message) static
Definition at line 68 of file rest.cpp.
References HTTPRequest::WriteHeader(), and HTTPRequest::WriteReply().
Referenced by CheckWarmup(), rest_block(), rest_chaininfo(), rest_getutxos(), rest_headers(), rest_mempool_contents(), rest_mempool_info(), and rest_tx().
ScriptPubKeyToJSON()
void ScriptPubKeyToJSON (const CScript & scriptPubKey, UniValue & out, bool fIncludeHex)
Definition at line 43 of file rawtransaction.cpp.
Referenced by rest_getutxos().
StartREST()
bool StartREST ()
Start HTTP REST subsystem.
Precondition; HTTP and RPC has been started.
Definition at line 608 of file rest.cpp.
References ARRAYLEN, handler, prefix, RegisterHTTPHandler(), and uri_prefixes.
Referenced by AppInitServers().
StopREST()
void StopREST ()
Stop HTTP REST subsystem.
Precondition; HTTP and RPC has been stopped.
Definition at line 619 of file rest.cpp.
References ARRAYLEN, prefix, UnregisterHTTPHandler(), and uri_prefixes.
Referenced by PrepareShutdown().
TxToJSON()
void TxToJSON (const CTransaction & tx, const uint256 hashBlock, UniValue & entry)
Definition at line 67 of file rawtransaction.cpp.
Referenced by rest_tx().
Variable Documentation
handler
bool(* handler) (HTTPRequest *req, const std::string &strReq)
Definition at line 596 of file rest.cpp.
Referenced by RegisterHTTPHandler(), and StartREST().
MAX_GETUTXOS_OUTPOINTS
const size_t MAX_GETUTXOS_OUTPOINTS = 15 static
Definition at line 23 of file rest.cpp.
Referenced by rest_getutxos().
name
const char* name
Definition at line 34 of file rest.cpp.
Referenced by WalletFrame::addWallet(), CRPCTable::appendCommand(), AppInitParameterInteraction(), AvailableDataFormatsString(), benchmark::BenchRunner::BenchRunner(), BIP9SoftForkDescPushBack(), CRPCConvertTable::convert(), find_value(), FormatSubVersion(), GetThreadName(), ipcServerName(), benchmark::State::KeepRunning(), CRPCTable::operator[](), ParseDataFormat(), ParseScript(), PaymentServer::PaymentServer(), CBlockTreeDB::ReadFlag(), RegisterEvoRPCCommands(), WalletFrame::removeWallet(), RenameThread(), RPCConvertNamedValues(), RPCRunLater(), run_benchmark(), WalletFrame::setCurrentWallet(), SoftForkDesc(), CNetAddr::ToStringIP(), TraceThread(), and CBlockTreeDB::WriteFlag().
prefix
const char* prefix
Definition at line 595 of file rest.cpp.
Referenced by TransactionView::changedPrefix(), GetBlockPosFilename(), OpenDiskFile(), RegisterHTTPHandler(), runtest(), StartREST(), StopREST(), and UnregisterHTTPHandler().
rf
enum RetFormat rf
Definition at line 33 of file rest.cpp.
Referenced by rest_block(), rest_chaininfo(), rest_getutxos(), rest_headers(), rest_mempool_contents(), rest_mempool_info(), and rest_tx().
rf_names
const { ... } rf_names[]
Initial value:
= {
      {RF_UNDEF, ""},
      {RF_BINARY, "bin"},
      {RF_HEX, "hex"},
      {RF_JSON, "json"},
}
Referenced by AvailableDataFormatsString(), and ParseDataFormat().
uri_prefixes
const { ... } uri_prefixes[]
Initial value:
= {
      {"/rest/tx/", rest_tx},
      {"/rest/block/notxdetails/", rest_block_notxdetails},
      {"/rest/block/", rest_block_extended},
      {"/rest/chaininfo", rest_chaininfo},
      {"/rest/mempool/info", rest_mempool_info},
      {"/rest/mempool/contents", rest_mempool_contents},
      {"/rest/headers/", rest_headers},
      {"/rest/getutxos", rest_getutxos},
}
Referenced by StartREST(), and StopREST().
Released under the MIT license