Dash Core: src/rpc/protocol.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
protocol.cpp File Reference
#include "rpc/protocol.h"
#include "random.h"
#include "tinyformat.h"
#include "util.h"
#include "utilstrencodings.h"
#include "utiltime.h"
#include "version.h"
#include <stdint.h>
#include <fstream>
Functions
UniValue JSONRPCRequestObj (const std::string &strMethod, const UniValue &params, const UniValue &id)
JSON-RPC protocol.
UniValue JSONRPCReplyObj (const UniValue &result, const UniValue &error, const UniValue &id)
std::string JSONRPCReply (const UniValue &result, const UniValue &error, const UniValue &id)
UniValue JSONRPCError (int code, const std::string &message)
boost::filesystem::path GetAuthCookieFile ()
Get name of RPC authentication cookie file.
bool GenerateAuthCookie (std::string *cookie_out)
Generate a new RPC authentication cookie and write it to disk.
bool GetAuthCookie (std::string *cookie_out)
Read the RPC authentication cookie from disk.
void DeleteAuthCookie ()
Delete RPC authentication cookie from disk.
Variables
static const std::string COOKIEAUTH_USER = "__cookie__"
Username used when cookie authentication is in use (arbitrary, only for recognizability in debugging/logging purposes)
static const std::string COOKIEAUTH_FILE = ".cookie"
Default name for auth cookie file.
Function Documentation
DeleteAuthCookie()
void DeleteAuthCookie ()
Delete RPC authentication cookie from disk.
Definition at line 120 of file protocol.cpp.
References GetAuthCookieFile(), and LogPrintf.
Referenced by StopRPC().
GenerateAuthCookie()
bool GenerateAuthCookie (std::string * cookie_out)
Generate a new RPC authentication cookie and write it to disk.
the umask determines what permissions are used to create this file - these are set to 077 in init.cpp unless overridden with -sysperms.
Definition at line 77 of file protocol.cpp.
References COOKIEAUTH_USER, GetAuthCookieFile(), GetRandBytes(), HexStr(), and LogPrintf.
Referenced by InitRPCAuthentication().
GetAuthCookie()
bool GetAuthCookie (std::string * cookie_out)
Read the RPC authentication cookie from disk.
Definition at line 104 of file protocol.cpp.
References GetAuthCookieFile().
Referenced by CallRPC().
GetAuthCookieFile()
boost::filesystem::path GetAuthCookieFile ()
Get name of RPC authentication cookie file.
Definition at line 70 of file protocol.cpp.
References COOKIEAUTH_FILE, GetArg(), and GetDataDir().
Referenced by DeleteAuthCookie(), GenerateAuthCookie(), and GetAuthCookie().
JSONRPCError()
UniValue JSONRPCError (int code, const std::string & message)
Definition at line 55 of file protocol.cpp.
References error(), Pair(), and UniValue::VOBJ.
Referenced by abandontransaction(), AccountFromValue(), addnode(), AmountFromValue(), backupwallet(), BIP22ValidationResult(), clearbanned(), createrawtransaction(), decoderawtransaction(), disconnectnode(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), CRPCTable::execute(), fundrawtransaction(), generate(), generateBlocks(), generatetoaddress(), getaccount(), GetAccountAddress(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getAddressesFromParams(), getaddressmempool(), getaddresstxids(), getaddressutxos(), getblock(), getblockhash(), getblockhashes(), getblockheader(), getblockheaders(), getblocktemplate(), getconnectioncount(), GetImportTimestamp(), getmempoolancestors(), getmempooldescendants(), getmempoolentry(), getnettotals(), getnewaddress(), getpeerinfo(), getrawchangeaddress(), getrawtransaction(), getreceivedbyaddress(), getspecialtxes(), getspentinfo(), getsuperblockbudget(), gettransaction(), gettxoutproof(), gettxoutsetinfo(), gobject_check(), gobject_get(), gobject_getcurrentvotes(), gobject_getvotes(), gobject_submit(), gobject_vote_alias(), gobject_vote_conf(), gobject_vote_many(), HTTPReq_JSONRPC(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), ImportScript(), importwallet(), instantsendtoaddress(), invalidateblock(), JSONRPCExecOne(), keypoolrefill(), listaddressbalances(), listbanned(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), masternode(), masternode_connect(), masternode_count(), masternode_status(), masternode_winners(), masternodebroadcast(), movecmd(), OnRPCPreCommand(), JSONRPCRequest::parse(), ParseBLSPubKey(), ParseBLSSecretKey(), ParseBoolV(), ParseDoubleV(), ParseHashV(), ParseHexV(), ParseInt32V(), ParseInt64V(), ParsePubKeyIDFromAddress(), ping(), preciousblock(), ProcessImport(), protx_info(), protx_list(), pruneblockchain(), reconsiderblock(), removeprunedfunds(), resendwallettransactions(), RPCRunLater(), RPCTypeCheckArgument(), RPCTypeCheckObj(), sendfrom(), sendmany(), SendMoney(), sendrawtransaction(), sendtoaddress(), setaccount(), setban(), setnetworkactive(), setprivatesendamount(), setprivatesendrounds(), signmessage(), signmessagewithprivkey(), signrawtransaction(), spork(), submitblock(), transformNamedArguments(), verifymessage(), verifytxoutproof(), voteraw(), VoteWithMasternodeList(), walletlock(), walletpassphrase(), and walletpassphrasechange().
JSONRPCReply()
std::string JSONRPCReply (const UniValue & result, const UniValue & error, const UniValue & id)
Definition at line 49 of file protocol.cpp.
References error(), JSONRPCReplyObj(), and UniValue::write().
Referenced by HTTPReq_JSONRPC(), and JSONErrorReply().
JSONRPCReplyObj()
UniValue JSONRPCReplyObj (const UniValue & result, const UniValue & error, const UniValue & id)
Definition at line 37 of file protocol.cpp.
References error(), NullUniValue, Pair(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by JSONRPCExecOne(), and JSONRPCReply().
JSONRPCRequestObj()
UniValue JSONRPCRequestObj (const std::string & strMethod, const UniValue & params, const UniValue & id)
JSON-RPC protocol.
Bitcoin speaks version 1.0 for maximum compatibility, but uses JSON-RPC 1.1/2.0 standards for parts of the 1.0 standard that were unspecified (HTTP errors and contents of 'error').
1.0 spec: http://json-rpc.org/wiki/specification 1.2 spec: http://jsonrpc.org/historical/json-rpc-over-http.html
Definition at line 28 of file protocol.cpp.
References Pair(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by CallRPC().
Variable Documentation
COOKIEAUTH_FILE
const std::string COOKIEAUTH_FILE = ".cookie" static
Default name for auth cookie file.
Definition at line 68 of file protocol.cpp.
Referenced by GetAuthCookieFile().
COOKIEAUTH_USER
const std::string COOKIEAUTH_USER = "__cookie__" static
Username used when cookie authentication is in use (arbitrary, only for recognizability in debugging/logging purposes)
Definition at line 66 of file protocol.cpp.
Referenced by GenerateAuthCookie().
Released under the MIT license