Dash Core: src/rpc/net.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
net.cpp File Reference
#include "rpc/server.h"
#include "chainparams.h"
#include "clientversion.h"
#include "validation.h"
#include "net.h"
#include "net_processing.h"
#include "netbase.h"
#include "policy/policy.h"
#include "protocol.h"
#include "sync.h"
#include "timedata.h"
#include "ui_interface.h"
#include "util.h"
#include "utilstrencodings.h"
#include "version.h"
#include <boost/foreach.hpp>
#include <univalue.h>
Functions
UniValue getconnectioncount (const JSONRPCRequest &request)
UniValue ping (const JSONRPCRequest &request)
UniValue getpeerinfo (const JSONRPCRequest &request)
UniValue addnode (const JSONRPCRequest &request)
UniValue disconnectnode (const JSONRPCRequest &request)
UniValue getaddednodeinfo (const JSONRPCRequest &request)
UniValue getnettotals (const JSONRPCRequest &request)
static UniValue GetNetworksInfo ()
UniValue getnetworkinfo (const JSONRPCRequest &request)
UniValue setban (const JSONRPCRequest &request)
UniValue listbanned (const JSONRPCRequest &request)
UniValue clearbanned (const JSONRPCRequest &request)
UniValue setnetworkactive (const JSONRPCRequest &request)
void RegisterNetRPCCommands (CRPCTable &t)
Register P2P networking RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
addnode()
UniValue addnode (const JSONRPCRequest & request)
Definition at line 191 of file net.cpp.
References JSONRPCRequest::fHelp, g_connman, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), NullUniValue, JSONRPCRequest::params, RPC_CLIENT_NODE_ALREADY_ADDED, RPC_CLIENT_NODE_NOT_ADDED, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
clearbanned()
UniValue clearbanned (const JSONRPCRequest & request)
Definition at line 566 of file net.cpp.
References JSONRPCRequest::fHelp, g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), NullUniValue, JSONRPCRequest::params, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
disconnectnode()
UniValue disconnectnode (const JSONRPCRequest & request)
Definition at line 236 of file net.cpp.
References JSONRPCRequest::fHelp, g_connman, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), NullUniValue, JSONRPCRequest::params, RPC_CLIENT_NODE_NOT_CONNECTED, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
getaddednodeinfo()
UniValue getaddednodeinfo (const JSONRPCRequest & request)
Definition at line 259 of file net.cpp.
References JSONRPCRequest::fHelp, g_connman, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_CLIENT_NODE_NOT_ADDED, RPC_CLIENT_P2P_DISABLED, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
getconnectioncount()
UniValue getconnectioncount (const JSONRPCRequest & request)
Definition at line 27 of file net.cpp.
References CConnman::CONNECTIONS_ALL, JSONRPCRequest::fHelp, g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), JSONRPCRequest::params, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
getnettotals()
UniValue getnettotals (const JSONRPCRequest & request)
Definition at line 327 of file net.cpp.
References JSONRPCRequest::fHelp, g_connman, GetTimeMillis(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_CLIENT_P2P_DISABLED, UniValue::size(), and UniValue::VOBJ.
getnetworkinfo()
UniValue getnetworkinfo (const JSONRPCRequest & request)
Definition at line 393 of file net.cpp.
References CLIENT_VERSION, CConnman::CONNECTIONS_ALL, cs_main, cs_mapLocalHost, CURRENCY_UNIT, JSONRPCRequest::fHelp, fRelayTxes, g_connman, CFeeRate::GetFeePerK(), GetNetworksInfo(), GetTimeOffset(), GetWarnings(), HelpExampleCli(), HelpExampleRpc(), incrementalRelayFee, LOCK, mapLocalHost, minRelayTxFee, LocalServiceInfo::nPort, LocalServiceInfo::nScore, Pair(), PAIRTYPE, JSONRPCRequest::params, PROTOCOL_VERSION, UniValue::push_back(), UniValue::size(), strprintf, strSubVersion, ValueFromAmount(), UniValue::VARR, and UniValue::VOBJ.
GetNetworksInfo()
static UniValue GetNetworksInfo () static
Definition at line 372 of file net.cpp.
References GetNetworkName(), GetProxy(), IsLimited(), IsReachable(), proxyType::IsValid(), NET_MAX, NET_UNROUTABLE, Pair(), proxyType::proxy, UniValue::push_back(), proxyType::randomize_credentials, CService::ToStringIPPort(), UniValue::VARR, and UniValue::VOBJ.
Referenced by getnetworkinfo().
getpeerinfo()
UniValue getpeerinfo (const JSONRPCRequest & request)
Definition at line 69 of file net.cpp.
References CNodeStats::addrLocal, CNodeStats::addrName, CNodeStats::cleanSubVer, CNodeStats::dMinPing, CNodeStats::dPingTime, CNodeStats::dPingWait, CNodeStats::fAddnode, JSONRPCRequest::fHelp, CNodeStats::fInbound, CNodeStats::fRelayTxes, CNodeStats::fWhitelisted, g_connman, GetNodeStateStats(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), CNodeStats::mapRecvBytesPerMsgCmd, CNodeStats::mapSendBytesPerMsgCmd, CNodeStateStats::nCommonHeight, CNodeStats::nLastRecv, CNodeStats::nLastSend, CNodeStateStats::nMisbehavior, CNodeStats::nodeid, CNodeStats::nRecvBytes, CNodeStats::nSendBytes, CNodeStats::nServices, CNodeStats::nStartingHeight, CNodeStateStats::nSyncHeight, CNodeStats::nTimeConnected, CNodeStats::nTimeOffset, CNodeStats::nVersion, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_CLIENT_P2P_DISABLED, UniValue::size(), strprintf, UniValue::VARR, CNodeStateStats::vHeightInFlight, and UniValue::VOBJ.
listbanned()
UniValue listbanned (const JSONRPCRequest & request)
Definition at line 533 of file net.cpp.
References CBanEntry::banReasonToString(), JSONRPCRequest::fHelp, g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), CBanEntry::nBanUntil, CBanEntry::nCreateTime, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_CLIENT_P2P_DISABLED, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
ping()
UniValue ping (const JSONRPCRequest & request)
Definition at line 46 of file net.cpp.
References JSONRPCRequest::fHelp, CNode::fPingQueued, g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), NullUniValue, JSONRPCRequest::params, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
RegisterNetRPCCommands()
void RegisterNetRPCCommands (CRPCTable & t)
Register P2P networking RPC commands.
Definition at line 621 of file net.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
setban()
UniValue setban (const JSONRPCRequest & request)
Definition at line 469 of file net.cpp.
References BanReasonManuallyAdded, JSONRPCRequest::fHelp, g_connman, UniValue::get_int64(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNull(), UniValue::isTrue(), CNetAddr::IsValid(), CSubNet::IsValid(), JSONRPCError(), LookupHost(), LookupSubNet(), NullUniValue, JSONRPCRequest::params, RPC_CLIENT_NODE_ALREADY_ADDED, RPC_CLIENT_P2P_DISABLED, RPC_MISC_ERROR, and UniValue::size().
setnetworkactive()
UniValue setnetworkactive (const JSONRPCRequest & request)
Definition at line 584 of file net.cpp.
References JSONRPCRequest::fHelp, g_connman, UniValue::get_bool(), JSONRPCError(), JSONRPCRequest::params, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "network",            "getconnectioncount",     &getconnectioncount,     true,  {} },
    { "network",            "ping",                   &ping,                   true,  {} },
    { "network",            "getpeerinfo",            &getpeerinfo,            true,  {} },
    { "network",            "addnode",                &addnode,                true,  {"node","command"} },
    { "network",            "disconnectnode",         &disconnectnode,         true,  {"address"} },
    { "network",            "getaddednodeinfo",       &getaddednodeinfo,       true,  {"node"} },
    { "network",            "getnettotals",           &getnettotals,           true,  {} },
    { "network",            "getnetworkinfo",         &getnetworkinfo,         true,  {} },
    { "network",            "setban",                 &setban,                 true,  {"subnet", "command", "bantime", "absolute"} },
    { "network",            "listbanned",             &listbanned,             true,  {} },
    { "network",            "clearbanned",            &clearbanned,            true,  {} },
    { "network",            "setnetworkactive",       &setnetworkactive,       true,  {"state"} },
}
Definition at line 604 of file net.cpp.
Referenced by RegisterNetRPCCommands().
Released under the MIT license