Dash Core: src/rpc/protocol.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
protocol.h File Reference
#include <list>
#include <map>
#include <stdint.h>
#include <string>
#include <boost/filesystem.hpp>
#include <univalue.h>
Enumerations
enum HTTPStatusCode {
HTTP_OK = 200, HTTP_BAD_REQUEST = 400, HTTP_UNAUTHORIZED = 401, HTTP_FORBIDDEN = 403,
HTTP_NOT_FOUND = 404, HTTP_BAD_METHOD = 405, HTTP_INTERNAL_SERVER_ERROR = 500, HTTP_SERVICE_UNAVAILABLE = 503
}
HTTP status codes.
enum RPCErrorCode {
RPC_INVALID_REQUEST = -32600, RPC_METHOD_NOT_FOUND = -32601, RPC_INVALID_PARAMS = -32602, RPC_INTERNAL_ERROR = -32603,
RPC_PARSE_ERROR = -32700, RPC_MISC_ERROR = -1, RPC_FORBIDDEN_BY_SAFE_MODE = -2, RPC_TYPE_ERROR = -3,
RPC_INVALID_ADDRESS_OR_KEY = -5, RPC_OUT_OF_MEMORY = -7, RPC_INVALID_PARAMETER = -8, RPC_DATABASE_ERROR = -20,
RPC_DESERIALIZATION_ERROR = -22, RPC_VERIFY_ERROR = -25, RPC_VERIFY_REJECTED = -26, RPC_VERIFY_ALREADY_IN_CHAIN = -27,
RPC_IN_WARMUP = -28, RPC_TRANSACTION_ERROR = RPC_VERIFY_ERROR, RPC_TRANSACTION_REJECTED = RPC_VERIFY_REJECTED, RPC_TRANSACTION_ALREADY_IN_CHAIN = RPC_VERIFY_ALREADY_IN_CHAIN,
RPC_CLIENT_NOT_CONNECTED = -9, RPC_CLIENT_IN_INITIAL_DOWNLOAD = -10, RPC_CLIENT_NODE_ALREADY_ADDED = -23, RPC_CLIENT_NODE_NOT_ADDED = -24,
RPC_CLIENT_NODE_NOT_CONNECTED = -29, RPC_CLIENT_INVALID_IP_OR_SUBNET = -30, RPC_CLIENT_P2P_DISABLED = -31, RPC_WALLET_ERROR = -4,
RPC_WALLET_INSUFFICIENT_FUNDS = -6, RPC_WALLET_INVALID_ACCOUNT_NAME = -11, RPC_WALLET_KEYPOOL_RAN_OUT = -12, RPC_WALLET_UNLOCK_NEEDED = -13,
RPC_WALLET_PASSPHRASE_INCORRECT = -14, RPC_WALLET_WRONG_ENC_STATE = -15, RPC_WALLET_ENCRYPTION_FAILED = -16, RPC_WALLET_ALREADY_UNLOCKED = -17
}
Dash Core RPC error codes.
Functions
UniValue JSONRPCRequestObj (const std::string &strMethod, const UniValue &params, const UniValue &id)
JSON-RPC protocol.
UniValue JSONRPCReplyObj (const UniValue &result, const UniValue &error, const UniValue &id)
std::string JSONRPCReply (const UniValue &result, const UniValue &error, const UniValue &id)
UniValue JSONRPCError (int code, const std::string &message)
boost::filesystem::path GetAuthCookieFile ()
Get name of RPC authentication cookie file.
bool GenerateAuthCookie (std::string *cookie_out)
Generate a new RPC authentication cookie and write it to disk.
bool GetAuthCookie (std::string *cookie_out)
Read the RPC authentication cookie from disk.
void DeleteAuthCookie ()
Delete RPC authentication cookie from disk.
Enumeration Type Documentation
HTTPStatusCode
enum HTTPStatusCode
HTTP status codes.
Enumerator
HTTP_OK
HTTP_BAD_REQUEST
HTTP_UNAUTHORIZED
HTTP_FORBIDDEN
HTTP_NOT_FOUND
HTTP_BAD_METHOD
HTTP_INTERNAL_SERVER_ERROR
HTTP_SERVICE_UNAVAILABLE
Definition at line 18 of file protocol.h.
RPCErrorCode
enum RPCErrorCode
Dash Core RPC error codes.
Enumerator
RPC_INVALID_REQUEST
Standard JSON-RPC 2.0 errors.
RPC_METHOD_NOT_FOUND
RPC_INVALID_PARAMS
RPC_INTERNAL_ERROR
RPC_PARSE_ERROR
RPC_MISC_ERROR
General application defined errors.
std::exception thrown in command handling
RPC_FORBIDDEN_BY_SAFE_MODE
Server is in safe mode, and command is not allowed in safe mode.
RPC_TYPE_ERROR
Unexpected type was passed as parameter.
RPC_INVALID_ADDRESS_OR_KEY
Invalid address or key.
RPC_OUT_OF_MEMORY
Ran out of memory during operation.
RPC_INVALID_PARAMETER
Invalid, missing or duplicate parameter.
RPC_DATABASE_ERROR
Database error.
RPC_DESERIALIZATION_ERROR
Error parsing or validating structure in raw format.
RPC_VERIFY_ERROR
General error during transaction or block submission.
RPC_VERIFY_REJECTED
Transaction or block was rejected by network rules.
RPC_VERIFY_ALREADY_IN_CHAIN
Transaction already in chain.
RPC_IN_WARMUP
Client still warming up.
RPC_TRANSACTION_ERROR
Aliases for backward compatibility.
RPC_TRANSACTION_REJECTED
RPC_TRANSACTION_ALREADY_IN_CHAIN
RPC_CLIENT_NOT_CONNECTED
P2P client errors.
Dash is not connected
RPC_CLIENT_IN_INITIAL_DOWNLOAD
Still downloading initial blocks.
RPC_CLIENT_NODE_ALREADY_ADDED
Node is already added.
RPC_CLIENT_NODE_NOT_ADDED
Node has not been added before.
RPC_CLIENT_NODE_NOT_CONNECTED
Node to disconnect not found in connected nodes.
RPC_CLIENT_INVALID_IP_OR_SUBNET
Invalid IP/Subnet.
RPC_CLIENT_P2P_DISABLED
No valid connection manager instance found.
RPC_WALLET_ERROR
Wallet errors.
Unspecified problem with wallet (key not found etc.)
RPC_WALLET_INSUFFICIENT_FUNDS
Not enough funds in wallet or account.
RPC_WALLET_INVALID_ACCOUNT_NAME
Invalid account name.
RPC_WALLET_KEYPOOL_RAN_OUT
Keypool ran out, call keypoolrefill first.
RPC_WALLET_UNLOCK_NEEDED
Enter the wallet passphrase with walletpassphrase first.
RPC_WALLET_PASSPHRASE_INCORRECT
The wallet passphrase entered was incorrect.
RPC_WALLET_WRONG_ENC_STATE
Command given in wrong wallet encryption state (encrypting an encrypted wallet etc.)
RPC_WALLET_ENCRYPTION_FAILED
Failed to encrypt the wallet.
RPC_WALLET_ALREADY_UNLOCKED
Wallet is already unlocked.
Definition at line 31 of file protocol.h.
Function Documentation
DeleteAuthCookie()
void DeleteAuthCookie ()
Delete RPC authentication cookie from disk.
Definition at line 120 of file protocol.cpp.
References GetAuthCookieFile(), and LogPrintf.
Referenced by StopRPC().
GenerateAuthCookie()
bool GenerateAuthCookie (std::string * cookie_out)
Generate a new RPC authentication cookie and write it to disk.
the umask determines what permissions are used to create this file - these are set to 077 in init.cpp unless overridden with -sysperms.
Definition at line 77 of file protocol.cpp.
References COOKIEAUTH_USER, GetAuthCookieFile(), GetRandBytes(), HexStr(), and LogPrintf.
Referenced by InitRPCAuthentication().
GetAuthCookie()
bool GetAuthCookie (std::string * cookie_out)
Read the RPC authentication cookie from disk.
Definition at line 104 of file protocol.cpp.
References GetAuthCookieFile().
Referenced by CallRPC().
GetAuthCookieFile()
boost::filesystem::path GetAuthCookieFile ()
Get name of RPC authentication cookie file.
Definition at line 70 of file protocol.cpp.
References COOKIEAUTH_FILE, GetArg(), and GetDataDir().
Referenced by DeleteAuthCookie(), GenerateAuthCookie(), and GetAuthCookie().
JSONRPCError()
UniValue JSONRPCError (int code, const std::string & message)
Definition at line 55 of file protocol.cpp.
References error(), Pair(), and UniValue::VOBJ.
Referenced by abandontransaction(), AccountFromValue(), addnode(), AmountFromValue(), backupwallet(), BIP22ValidationResult(), clearbanned(), createrawtransaction(), decoderawtransaction(), disconnectnode(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), CRPCTable::execute(), fundrawtransaction(), generate(), generateBlocks(), generatetoaddress(), getaccount(), GetAccountAddress(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getAddressesFromParams(), getaddressmempool(), getaddresstxids(), getaddressutxos(), getblock(), getblockhash(), getblockhashes(), getblockheader(), getblockheaders(), getblocktemplate(), getconnectioncount(), GetImportTimestamp(), getmempoolancestors(), getmempooldescendants(), getmempoolentry(), getnettotals(), getnewaddress(), getpeerinfo(), getrawchangeaddress(), getrawtransaction(), getreceivedbyaddress(), getspecialtxes(), getspentinfo(), getsuperblockbudget(), gettransaction(), gettxoutproof(), gettxoutsetinfo(), gobject_check(), gobject_get(), gobject_getcurrentvotes(), gobject_getvotes(), gobject_submit(), gobject_vote_alias(), gobject_vote_conf(), gobject_vote_many(), HTTPReq_JSONRPC(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), ImportScript(), importwallet(), instantsendtoaddress(), invalidateblock(), JSONRPCExecOne(), keypoolrefill(), listaddressbalances(), listbanned(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), masternode(), masternode_connect(), masternode_count(), masternode_status(), masternode_winners(), masternodebroadcast(), movecmd(), OnRPCPreCommand(), JSONRPCRequest::parse(), ParseBLSPubKey(), ParseBLSSecretKey(), ParseBoolV(), ParseDoubleV(), ParseHashV(), ParseHexV(), ParseInt32V(), ParseInt64V(), ParsePubKeyIDFromAddress(), ping(), preciousblock(), ProcessImport(), protx_info(), protx_list(), pruneblockchain(), reconsiderblock(), removeprunedfunds(), resendwallettransactions(), RPCRunLater(), RPCTypeCheckArgument(), RPCTypeCheckObj(), sendfrom(), sendmany(), SendMoney(), sendrawtransaction(), sendtoaddress(), setaccount(), setban(), setnetworkactive(), setprivatesendamount(), setprivatesendrounds(), signmessage(), signmessagewithprivkey(), signrawtransaction(), spork(), submitblock(), transformNamedArguments(), verifymessage(), verifytxoutproof(), voteraw(), VoteWithMasternodeList(), walletlock(), walletpassphrase(), and walletpassphrasechange().
JSONRPCReply()
std::string JSONRPCReply (const UniValue & result, const UniValue & error, const UniValue & id)
Definition at line 49 of file protocol.cpp.
References error(), JSONRPCReplyObj(), and UniValue::write().
Referenced by HTTPReq_JSONRPC(), and JSONErrorReply().
JSONRPCReplyObj()
UniValue JSONRPCReplyObj (const UniValue & result, const UniValue & error, const UniValue & id)
Definition at line 37 of file protocol.cpp.
References error(), NullUniValue, Pair(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by JSONRPCExecOne(), and JSONRPCReply().
JSONRPCRequestObj()
UniValue JSONRPCRequestObj (const std::string & strMethod, const UniValue & params, const UniValue & id)
JSON-RPC protocol.
Bitcoin speaks version 1.0 for maximum compatibility, but uses JSON-RPC 1.1/2.0 standards for parts of the 1.0 standard that were unspecified (HTTP errors and contents of 'error').
1.0 spec: http://json-rpc.org/wiki/specification 1.2 spec: http://jsonrpc.org/historical/json-rpc-over-http.html
Definition at line 28 of file protocol.cpp.
References Pair(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by CallRPC().
Released under the MIT license