Dash Core: src/rpc/masternode.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
masternode.cpp File Reference
#include "activemasternode.h"
#include "base58.h"
#include "clientversion.h"
#include "init.h"
#include "netbase.h"
#include "validation.h"
#include "masternode-payments.h"
#include "masternode-sync.h"
#include "masternodeconfig.h"
#include "masternodeman.h"
#include "privatesend-server.h"
#include "rpc/server.h"
#include "util.h"
#include "utilmoneystr.h"
#include "txmempool.h"
#include "evo/specialtx.h"
#include "evo/deterministicmns.h"
#include <fstream>
#include <iomanip>
#include <univalue.h>
Functions
UniValue masternodelist (const JSONRPCRequest &request)
bool EnsureWalletIsAvailable (bool avoidException)
UniValue getpoolinfo (const JSONRPCRequest &request)
void masternode_list_help ()
UniValue masternode_list (const JSONRPCRequest &request)
void masternode_connect_help ()
UniValue masternode_connect (const JSONRPCRequest &request)
void masternode_count_help ()
UniValue masternode_count (const JSONRPCRequest &request)
UniValue GetNextMasternodeForPayment (int heightShift)
void masternode_winner_help ()
UniValue masternode_winner (const JSONRPCRequest &request)
void masternode_current_help ()
UniValue masternode_current (const JSONRPCRequest &request)
void masternode_genkey_help ()
UniValue masternode_genkey (const JSONRPCRequest &request)
void masternode_list_conf_help ()
UniValue masternode_list_conf (const JSONRPCRequest &request)
void masternode_status_help ()
UniValue masternode_status (const JSONRPCRequest &request)
void masternode_winners_help ()
UniValue masternode_winners (const JSONRPCRequest &request)
void masternode_check_help ()
UniValue masternode_check (const JSONRPCRequest &request)
void masternode_help ()
UniValue masternode (const JSONRPCRequest &request)
bool DecodeHexVecMnb (std::vector< CMasternodeBroadcast > &vecMnb, std::string strHexMnb)
UniValue masternodebroadcast (const JSONRPCRequest &request)
UniValue sentinelping (const JSONRPCRequest &request)
void RegisterMasternodeRPCCommands (CRPCTable &t)
Register masternode RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
DecodeHexVecMnb()
bool DecodeHexVecMnb (std::vector< CMasternodeBroadcast > & vecMnb, std::string strHexMnb)
Definition at line 1035 of file masternode.cpp.
References IsHex(), ParseHex(), PROTOCOL_VERSION, and SER_NETWORK.
Referenced by masternodebroadcast().
EnsureWalletIsAvailable()
bool EnsureWalletIsAvailable (bool avoidException)
Definition at line 41 of file rpcwallet.cpp.
Referenced by masternodebroadcast().
GetNextMasternodeForPayment()
UniValue GetNextMasternodeForPayment (int heightShift)
Definition at line 273 of file masternode.cpp.
References masternode_info_t::addr, chainActive, cs_main, deterministicMNManager, ExtractDestination(), CDeterministicMNManager::GetListAtChainTip(), CMasternodeMan::GetMasternodeInfo(), CDeterministicMNList::GetMNPayee(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetScriptForDestination(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CBitcoinAddress::IsValid(), masternode_info_t::keyIDCollateralAddress, LOCK, mnodeman, CBlockIndex::nHeight, masternode_info_t::nProtocolVersion, masternode_info_t::nTimeLastPing, masternode_info_t::outpoint, Pair(), UniValue::push_back(), masternode_info_t::sigTime, CChain::Tip(), CBase58Data::ToString(), CService::ToString(), COutPoint::ToStringShort(), CMasternodeMan::UpdateLastPaid(), and UniValue::VOBJ.
Referenced by masternode_current(), and masternode_winner().
getpoolinfo()
UniValue getpoolinfo (const JSONRPCRequest & request)
Definition at line 85 of file masternode.cpp.
References JSONRPCRequest::fHelp, fMasternodeMode, CPrivateSendBaseSession::GetEntriesCount(), CPrivateSendClientManager::GetMixingMasternodesInfo(), CPrivateSendBaseManager::GetQueueSize(), CPrivateSendBaseSession::GetStateString(), CPrivateSendClientManager::GetStatuses(), CWallet::nKeysLeftSinceAutoBackup, Pair(), JSONRPCRequest::params, PRIVATESEND_KEYS_THRESHOLD_WARNING, privateSendClient, privateSendServer, UniValue::push_back(), pwalletMain, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
masternode()
UniValue masternode (const JSONRPCRequest & request)
Definition at line 795 of file masternode.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), JSONRPCError(), masternode_check(), masternode_connect(), masternode_count(), masternode_current(), masternode_genkey(), masternode_help(), masternode_list(), masternode_list_conf(), masternode_status(), masternode_winner(), masternode_winners(), JSONRPCRequest::params, RPC_INVALID_PARAMETER, and UniValue::size().
masternode_check()
UniValue masternode_check (const JSONRPCRequest & request)
Definition at line 746 of file masternode.cpp.
References CMasternodeMan::CheckAndRemove(), CMasternodeMan::CountEnabled(), CMasternodeMan::CountMasternodes(), JSONRPCRequest::fHelp, g_connman, masternode_check_help(), mnodeman, Pair(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by masternode().
masternode_check_help()
void masternode_check_help ()
Definition at line 738 of file masternode.cpp.
Referenced by masternode_check().
masternode_connect()
UniValue masternode_connect (const JSONRPCRequest & request)
Definition at line 187 of file masternode.cpp.
References CConnman::AllNodes, JSONRPCRequest::fHelp, g_connman, UniValue::get_str(), JSONRPCError(), Lookup(), masternode_connect_help(), NODE_NETWORK, JSONRPCRequest::params, RPC_INTERNAL_ERROR, UniValue::size(), and strprintf.
Referenced by masternode().
masternode_connect_help()
void masternode_connect_help ()
Definition at line 177 of file masternode.cpp.
Referenced by masternode_connect().
masternode_count()
UniValue masternode_count (const JSONRPCRequest & request)
Definition at line 224 of file masternode.cpp.
References CMasternodeMan::CountEnabled(), CMasternodeMan::CountMasternodes(), deterministicMNManager, JSONRPCRequest::fHelp, UniValue::get_str(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), JSONRPCError(), masternode_count_help(), MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_PARAMETER, UniValue::size(), strprintf, and UniValue::VOBJ.
Referenced by masternode().
masternode_count_help()
void masternode_count_help ()
Definition at line 206 of file masternode.cpp.
Referenced by masternode_count().
masternode_current()
UniValue masternode_current (const JSONRPCRequest & request)
Definition at line 341 of file masternode.cpp.
References JSONRPCRequest::fHelp, GetNextMasternodeForPayment(), and masternode_current_help().
Referenced by masternode().
masternode_current_help()
void masternode_current_help ()
Definition at line 333 of file masternode.cpp.
Referenced by masternode_current().
masternode_genkey()
UniValue masternode_genkey (const JSONRPCRequest & request)
Definition at line 594 of file masternode.cpp.
References JSONRPCRequest::fHelp, CKey::MakeNewKey(), masternode_genkey_help(), JSONRPCRequest::params, ParseBoolV(), UniValue::size(), and CBase58Data::ToString().
Referenced by masternode().
masternode_genkey_help()
void masternode_genkey_help ()
Definition at line 584 of file masternode.cpp.
Referenced by masternode_genkey().
masternode_help()
void masternode_help ()
Definition at line 770 of file masternode.cpp.
Referenced by masternode().
masternode_list()
UniValue masternode_list (const JSONRPCRequest & request)
Definition at line 164 of file masternode.cpp.
References JSONRPCRequest::fHelp, masternode_list_help(), masternodelist(), JSONRPCRequest::params, UniValue::push_back(), UniValue::setArray(), and UniValue::size().
Referenced by masternode().
masternode_list_conf()
UniValue masternode_list_conf (const JSONRPCRequest & request)
Definition at line 618 of file masternode.cpp.
References atoi(), JSONRPCRequest::fHelp, CMasternodeMan::Get(), CMasternodeConfig::getEntries(), CMasternode::GetStatus(), masternode_list_conf_help(), masternodeConfig, mnodeman, Pair(), UniValue::push_back(), uint256S(), and UniValue::VOBJ.
Referenced by masternode().
masternode_list_conf_help()
void masternode_list_conf_help ()
Definition at line 610 of file masternode.cpp.
Referenced by masternode_list_conf().
masternode_list_help()
void masternode_list_help ()
Definition at line 129 of file masternode.cpp.
Referenced by masternode_list(), and masternodelist().
masternode_status()
UniValue masternode_status (const JSONRPCRequest & request)
Definition at line 653 of file masternode.cpp.
References activeMasternodeInfo, activeMasternodeManager, deterministicMNManager, JSONRPCRequest::fHelp, fMasternodeMode, CMasternodeMan::Get(), CActiveDeterministicMasternodeManager::GetDMN(), CActiveDeterministicMasternodeManager::GetStateString(), CActiveDeterministicMasternodeManager::GetStatus(), CActiveLegacyMasternodeManager::GetStatus(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), JSONRPCError(), masternode_info_t::keyIDCollateralAddress, legacyActiveMasternodeManager, masternode_status_help(), mnodeman, CActiveMasternodeInfo::outpoint, Pair(), UniValue::push_back(), RPC_INTERNAL_ERROR, CActiveMasternodeInfo::service, CBase58Data::ToString(), CService::ToString(), COutPoint::ToStringShort(), and UniValue::VOBJ.
Referenced by masternode().
masternode_status_help()
void masternode_status_help ()
Definition at line 645 of file masternode.cpp.
Referenced by masternode_status().
masternode_winner()
UniValue masternode_winner (const JSONRPCRequest & request)
Definition at line 325 of file masternode.cpp.
References JSONRPCRequest::fHelp, GetNextMasternodeForPayment(), and masternode_winner_help().
Referenced by masternode().
masternode_winner_help()
void masternode_winner_help ()
Definition at line 317 of file masternode.cpp.
Referenced by masternode_winner().
masternode_winners()
UniValue masternode_winners (const JSONRPCRequest & request)
Definition at line 701 of file masternode.cpp.
References atoi(), chainActive, cs_main, JSONRPCRequest::fHelp, UniValue::get_str(), GetRequiredPaymentsStrings(), JSONRPCError(), LOCK, masternode_winners_help(), CBlockIndex::nHeight, NullUniValue, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_PARAMETER, UniValue::size(), strprintf, CChain::Tip(), and UniValue::VOBJ.
Referenced by masternode().
masternode_winners_help()
void masternode_winners_help ()
Definition at line 690 of file masternode.cpp.
Referenced by masternode_winners().
masternodebroadcast()
UniValue masternodebroadcast (const JSONRPCRequest & request)
Definition at line 1051 of file masternode.cpp.
References masternode_info_t::addr, CDataStream::begin(), CMasternodePing::blockHash, CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckSignature(), CMasternodeBroadcast::Create(), CWallet::cs_wallet, DecodeHexVecMnb(), EncodeBase64(), CDataStream::end(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, fImporting, fReindex, g_connman, UniValue::get_str(), CMasternodeConfig::getEntries(), CMasternodeBroadcast::GetHash(), HexStr(), JSONRPCError(), masternode_info_t::keyIDCollateralAddress, CMasternode::lastPing, masternode_info_t::legacyKeyIDOperator, LOCK, masternodeConfig, CMasternodePing::masternodeOutpoint, mnodeman, masternode_info_t::nLastDsq, CMasternodeMan::NotifyMasternodeUpdates(), masternode_info_t::nProtocolVersion, NullUniValue, masternode_info_t::outpoint, Pair(), JSONRPCRequest::params, PROTOCOL_VERSION, UniValue::push_back(), pwalletMain, RPC_DESERIALIZATION_ERROR, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, SER_NETWORK, CMasternodePing::sigTime, masternode_info_t::sigTime, UniValue::size(), strprintf, base_blob< BITS >::ToString(), CBase58Data::ToString(), CService::ToString(), COutPoint::ToStringShort(), CMasternodePing::vchSig, CMasternode::vchSig, and UniValue::VOBJ.
masternodelist()
UniValue masternodelist (const JSONRPCRequest & request)
Definition at line 850 of file masternode.cpp.
References masternode_info_t::addr, chainActive, cs_main, deterministicMNManager, ExtractDestination(), JSONRPCRequest::fHelp, CMasternodePing::fSentinelIsCurrent, UniValue::get_str(), CMasternodePing::GetDaemonString(), CMasternodeMan::GetFullMasternodeMap(), CMasternode::GetLastPaidBlock(), CMasternode::GetLastPaidTime(), CDeterministicMNManager::GetListAtChainTip(), CMasternodeMan::GetMasternodeRanks(), CDeterministicMNList::GetMNByCollateral(), GetScriptForDestination(), CMasternodePing::GetSentinelString(), CMasternode::GetStatus(), GetUTXOCoin(), HexStr(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), masternode_info_t::keyIDCollateralAddress, masternode_info_t::keyIDOwner, masternode_info_t::keyIDVoting, CMasternode::lastPing, masternode_info_t::legacyKeyIDOperator, LOCK, masternode_list_help(), mnodeman, CMasternodePing::nDaemonVersion, masternode_info_t::nProtocolVersion, Coin::out, masternode_info_t::outpoint, Pair(), JSONRPCRequest::params, UniValue::push_back(), CTxOut::scriptPubKey, CMasternodePing::sigTime, masternode_info_t::sigTime, UniValue::size(), strprintf, CChain::Tip(), CBase58Data::ToString(), CService::ToString(), CMasternodeMan::UpdateLastPaid(), and UniValue::VOBJ.
Referenced by masternode_list().
RegisterMasternodeRPCCommands()
void RegisterMasternodeRPCCommands (CRPCTable & t)
Register masternode RPC commands.
Definition at line 1312 of file masternode.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
sentinelping()
UniValue sentinelping (const JSONRPCRequest & request)
Definition at line 1279 of file masternode.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), legacyActiveMasternodeManager, JSONRPCRequest::params, UniValue::size(), StringVersionToInt(), and CActiveLegacyMasternodeManager::UpdateSentinelPing().
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "dash",               "masternode",             &masternode,             true,  {} },
    { "dash",               "masternodelist",         &masternodelist,         true,  {} },
    { "dash",               "masternodebroadcast",    &masternodebroadcast,    true,  {} },
    { "dash",               "getpoolinfo",            &getpoolinfo,            true,  {} },
    { "dash",               "sentinelping",           &sentinelping,           true,  {} },
}
Definition at line 1299 of file masternode.cpp.
Referenced by RegisterMasternodeRPCCommands().
Released under the MIT license