Dash Core: src/rpc/governance.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
governance.cpp File Reference
#include "activemasternode.h"
#include "consensus/validation.h"
#include "governance.h"
#include "governance-vote.h"
#include "governance-classes.h"
#include "governance-validators.h"
#include "init.h"
#include "validation.h"
#include "masternode.h"
#include "masternode-sync.h"
#include "masternodeconfig.h"
#include "masternodeman.h"
#include "messagesigner.h"
#include "rpc/server.h"
#include "util.h"
#include "utilmoneystr.h"
Functions
bool EnsureWalletIsAvailable (bool avoidException)
void gobject_count_help ()
UniValue gobject_count (const JSONRPCRequest &request)
void gobject_deserialize_help ()
UniValue gobject_deserialize (const JSONRPCRequest &request)
void gobject_check_help ()
UniValue gobject_check (const JSONRPCRequest &request)
void gobject_submit_help ()
UniValue gobject_submit (const JSONRPCRequest &request)
void gobject_vote_conf_help ()
UniValue gobject_vote_conf (const JSONRPCRequest &request)
UniValue VoteWithMasternodeList (const std::vector< CMasternodeConfig::CMasternodeEntry > &entries, const uint256 &hash, vote_signal_enum_t eVoteSignal, vote_outcome_enum_t eVoteOutcome)
void gobject_vote_many_help ()
UniValue gobject_vote_many (const JSONRPCRequest &request)
void gobject_vote_alias_help ()
UniValue gobject_vote_alias (const JSONRPCRequest &request)
UniValue ListObjects (const std::string &strCachedSignal, const std::string &strType, int nStartTime)
void gobject_list_help ()
UniValue gobject_list (const JSONRPCRequest &request)
void gobject_diff_help ()
UniValue gobject_diff (const JSONRPCRequest &request)
void gobject_get_help ()
UniValue gobject_get (const JSONRPCRequest &request)
void gobject_getvotes_help ()
UniValue gobject_getvotes (const JSONRPCRequest &request)
void gobject_getcurrentvotes_help ()
UniValue gobject_getcurrentvotes (const JSONRPCRequest &request)
void gobject_help ()
UniValue gobject (const JSONRPCRequest &request)
UniValue voteraw (const JSONRPCRequest &request)
UniValue getgovernanceinfo (const JSONRPCRequest &request)
UniValue getsuperblockbudget (const JSONRPCRequest &request)
void RegisterGovernanceRPCCommands (CRPCTable &t)
Register governance RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
EnsureWalletIsAvailable()
bool EnsureWalletIsAvailable (bool avoidException)
Definition at line 41 of file rpcwallet.cpp.
getgovernanceinfo()
UniValue getgovernanceinfo (const JSONRPCRequest & request)
Definition at line 1161 of file governance.cpp.
References chainActive, cs_main, CURRENCY_UNIT, JSONRPCRequest::fHelp, CSuperblock::GetNearestSuperblocksHeights(), GOVERNANCE_PROPOSAL_FEE_TX, CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, MASTERNODE_SENTINEL_PING_MAX_SECONDS, Pair(), JSONRPCRequest::params, Params(), UniValue::push_back(), UniValue::size(), ValueFromAmount(), and UniValue::VOBJ.
getsuperblockbudget()
UniValue getsuperblockbudget (const JSONRPCRequest & request)
Definition at line 1202 of file governance.cpp.
References CURRENCY_UNIT, JSONRPCRequest::fHelp, FormatMoney(), UniValue::get_int(), CSuperblock::GetPaymentsLimit(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), JSONRPCRequest::params, RPC_INVALID_PARAMETER, and UniValue::size().
gobject()
UniValue gobject (const JSONRPCRequest & request)
Definition at line 1033 of file governance.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), gobject_check(), gobject_count(), gobject_deserialize(), gobject_diff(), gobject_get(), gobject_getcurrentvotes(), gobject_getvotes(), gobject_help(), gobject_list(), gobject_submit(), gobject_vote_alias(), gobject_vote_conf(), gobject_vote_many(), JSONRPCRequest::params, and UniValue::size().
gobject_check()
UniValue gobject_check (const JSONRPCRequest & request)
Definition at line 92 of file governance.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), GetAdjustedTime(), CProposalValidator::GetErrorMessages(), CGovernanceObject::GetObjectType(), gobject_check_help(), GOVERNANCE_OBJECT_PROPOSAL, JSONRPCError(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_PARAMETER, UniValue::size(), CProposalValidator::Validate(), and UniValue::VOBJ.
Referenced by gobject().
gobject_check_help()
void gobject_check_help ()
Definition at line 82 of file governance.cpp.
Referenced by gobject_check().
gobject_count()
UniValue gobject_count (const JSONRPCRequest & request)
Definition at line 39 of file governance.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), gobject_count_help(), governance, JSONRPCRequest::params, UniValue::size(), CGovernanceManager::ToJson(), and CGovernanceManager::ToString().
Referenced by gobject().
gobject_count_help()
void gobject_count_help ()
Definition at line 29 of file governance.cpp.
Referenced by gobject_count().
gobject_deserialize()
UniValue gobject_deserialize (const JSONRPCRequest & request)
Definition at line 66 of file governance.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), gobject_deserialize_help(), JSONRPCRequest::params, ParseHex(), UniValue::size(), and UniValue::VOBJ.
Referenced by gobject().
gobject_deserialize_help()
void gobject_deserialize_help ()
Definition at line 56 of file governance.cpp.
Referenced by gobject_deserialize().
gobject_diff()
UniValue gobject_diff (const JSONRPCRequest & request)
Definition at line 810 of file governance.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), CGovernanceManager::GetLastDiffTime(), gobject_diff_help(), governance, ListObjects(), JSONRPCRequest::params, and UniValue::size().
Referenced by gobject().
gobject_diff_help()
void gobject_diff_help ()
Definition at line 799 of file governance.cpp.
Referenced by gobject_diff().
gobject_get()
UniValue gobject_get (const JSONRPCRequest & request)
Definition at line 838 of file governance.cpp.
References CGovernanceManager::cs, cs_main, JSONRPCRequest::fHelp, CGovernanceManager::FindGovernanceObject(), CGovernanceObject::GetAbsoluteYesCount(), CGovernanceObject::GetAbstainCount(), CGovernanceObject::GetCollateralHash(), CGovernanceObject::GetCreationTime(), CGovernanceObject::GetDataAsHexString(), CGovernanceObject::GetDataAsPlainString(), CGovernanceObject::GetHash(), CGovernanceObject::GetMasternodeOutpoint(), CGovernanceObject::GetNoCount(), CGovernanceObject::GetObjectType(), CGovernanceObject::GetYesCount(), gobject_get_help(), governance, CGovernanceObject::IsSetCachedDelete(), CGovernanceObject::IsSetCachedEndorsed(), CGovernanceObject::IsSetCachedFunding(), CGovernanceObject::IsSetCachedValid(), CGovernanceObject::IsValidLocally(), JSONRPCError(), LOCK2, Pair(), JSONRPCRequest::params, ParseHashV(), UniValue::push_back(), RPC_INVALID_PARAMETER, UniValue::size(), base_blob< BITS >::ToString(), COutPoint::ToStringShort(), UniValue::VOBJ, VOTE_SIGNAL_DELETE, VOTE_SIGNAL_ENDORSED, VOTE_SIGNAL_FUNDING, and VOTE_SIGNAL_VALID.
Referenced by gobject().
gobject_get_help()
void gobject_get_help ()
Definition at line 828 of file governance.cpp.
Referenced by gobject_get().
gobject_getcurrentvotes()
UniValue gobject_getcurrentvotes (const JSONRPCRequest & request)
Definition at line 969 of file governance.cpp.
References atoi(), CGovernanceManager::cs, JSONRPCRequest::fHelp, CGovernanceManager::FindGovernanceObject(), UniValue::get_str(), CGovernanceManager::GetCurrentVotes(), gobject_getcurrentvotes_help(), governance, JSONRPCError(), LOCK, Pair(), JSONRPCRequest::params, ParseHashV(), UniValue::push_back(), RPC_INVALID_PARAMETER, UniValue::size(), and UniValue::VOBJ.
Referenced by gobject().
gobject_getcurrentvotes_help()
void gobject_getcurrentvotes_help ()
Definition at line 957 of file governance.cpp.
Referenced by gobject_getcurrentvotes().
gobject_getvotes()
UniValue gobject_getvotes (const JSONRPCRequest & request)
Definition at line 924 of file governance.cpp.
References CGovernanceManager::cs, JSONRPCRequest::fHelp, CGovernanceManager::FindGovernanceObject(), CGovernanceManager::GetMatchingVotes(), gobject_getvotes_help(), governance, JSONRPCError(), LOCK, Pair(), JSONRPCRequest::params, ParseHashV(), UniValue::push_back(), RPC_INVALID_PARAMETER, UniValue::size(), and UniValue::VOBJ.
Referenced by gobject().
gobject_getvotes_help()
void gobject_getvotes_help ()
Definition at line 914 of file governance.cpp.
Referenced by gobject_getvotes().
gobject_help()
void gobject_help ()
Definition at line 1009 of file governance.cpp.
Referenced by gobject().
gobject_list()
UniValue gobject_list (const JSONRPCRequest & request)
Definition at line 781 of file governance.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), gobject_list_help(), ListObjects(), JSONRPCRequest::params, and UniValue::size().
Referenced by gobject().
gobject_list_help()
void gobject_list_help ()
Definition at line 770 of file governance.cpp.
Referenced by gobject_list().
gobject_submit()
UniValue gobject_submit (const JSONRPCRequest & request)
Definition at line 255 of file governance.cpp.
References activeMasternodeInfo, CGovernanceManager::AddGovernanceObject(), CGovernanceManager::AddPostponedObject(), atoi(), atoi64(), CActiveMasternodeInfo::blsKeyOperator, cs_main, DBG, deterministicMNManager, JSONRPCRequest::fHelp, g_connman, UniValue::get_str(), CGovernanceObject::GetDataAsPlainString(), CProposalValidator::GetErrorMessages(), CGovernanceObject::GetHash(), base_blob< BITS >::GetHex(), CGovernanceObject::GetObjectType(), gobject_submit_help(), governance, GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, GOVERNANCE_OBJECT_WATCHDOG, CMasternodeMan::Has(), CMasternodeSync::IsBlockchainSynced(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), CGovernanceObject::IsValidLocally(), JSONRPCError(), CActiveMasternodeInfo::legacyKeyIDOperator, CActiveMasternodeInfo::legacyKeyOperator, LOCK, LogPrintf, CGovernanceManager::MasternodeRateCheck(), masternodeSync, mnodeman, CActiveMasternodeInfo::outpoint, JSONRPCRequest::params, ParseHashV(), CGovernanceObject::Relay(), RPC_CLIENT_IN_INITIAL_DOWNLOAD, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, CGovernanceObject::SetMasternodeOutpoint(), CGovernanceObject::Sign(), UniValue::size(), base_blob< BITS >::ToString(), COutPoint::ToStringShort(), and CProposalValidator::Validate().
Referenced by gobject().
gobject_submit_help()
void gobject_submit_help ()
Definition at line 241 of file governance.cpp.
Referenced by gobject_submit().
gobject_vote_alias()
UniValue gobject_vote_alias (const JSONRPCRequest & request)
Definition at line 658 of file governance.cpp.
References CGovernanceVoting::ConvertVoteOutcome(), CGovernanceVoting::ConvertVoteSignal(), deterministicMNManager, JSONRPCRequest::fHelp, UniValue::get_str(), CMasternodeConfig::getEntries(), CWallet::GetKey(), CDeterministicMNManager::GetListAtChainTip(), CDeterministicMNList::GetValidMN(), gobject_vote_alias_help(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), itostr(), JSONRPCError(), masternodeConfig, JSONRPCRequest::params, ParseHashV(), pwalletMain, RPC_INVALID_PARAMETER, UniValue::size(), strprintf, CBase58Data::ToString(), VOTE_OUTCOME_NONE, VOTE_SIGNAL_NONE, and VoteWithMasternodeList().
Referenced by gobject().
gobject_vote_alias_help()
void gobject_vote_alias_help ()
Definition at line 645 of file governance.cpp.
Referenced by gobject_vote_alias().
gobject_vote_conf()
UniValue gobject_vote_conf (const JSONRPCRequest & request)
Definition at line 374 of file governance.cpp.
References activeMasternodeInfo, CActiveMasternodeInfo::blsKeyOperator, CGovernanceVoting::ConvertVoteOutcome(), CGovernanceVoting::ConvertVoteSignal(), CGovernanceManager::cs, deterministicMNManager, JSONRPCRequest::fHelp, CGovernanceManager::FindGovernanceObject(), g_connman, CMasternodeMan::Get(), UniValue::get_str(), CGovernanceException::GetMessage(), CGovernanceObject::GetObjectType(), gobject_vote_conf_help(), governance, GOVERNANCE_OBJECT_PROPOSAL, CDeterministicMNManager::IsDeterministicMNsSporkActive(), JSONRPCError(), CActiveMasternodeInfo::legacyKeyIDOperator, CActiveMasternodeInfo::legacyKeyOperator, LOCK, mnodeman, CActiveMasternodeInfo::outpoint, masternode_info_t::outpoint, Pair(), JSONRPCRequest::params, ParseHashV(), CGovernanceManager::ProcessVoteAndRelay(), UniValue::push_back(), RPC_INVALID_PARAMETER, CGovernanceVote::Sign(), UniValue::size(), strprintf, UniValue::VOBJ, VOTE_OUTCOME_NONE, VOTE_SIGNAL_FUNDING, and VOTE_SIGNAL_NONE.
Referenced by gobject().
gobject_vote_conf_help()
void gobject_vote_conf_help ()
Definition at line 362 of file governance.cpp.
Referenced by gobject_vote_conf().
gobject_vote_many()
UniValue gobject_vote_many (const JSONRPCRequest & request)
Definition at line 574 of file governance.cpp.
References CGovernanceVoting::ConvertVoteOutcome(), CGovernanceVoting::ConvertVoteSignal(), deterministicMNManager, JSONRPCRequest::fHelp, CDeterministicMNList::ForEachMN(), UniValue::get_str(), CMasternodeConfig::getEntries(), CWallet::GetKey(), CDeterministicMNManager::GetListAtChainTip(), gobject_vote_many_help(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), itostr(), JSONRPCError(), masternodeConfig, JSONRPCRequest::params, ParseHashV(), ParseInt32(), pwalletMain, RPC_INVALID_PARAMETER, base_blob< BITS >::SetHex(), UniValue::size(), CBase58Data::ToString(), VOTE_OUTCOME_NONE, VOTE_SIGNAL_NONE, and VoteWithMasternodeList().
Referenced by gobject().
gobject_vote_many_help()
void gobject_vote_many_help ()
Definition at line 562 of file governance.cpp.
Referenced by gobject_vote_many().
ListObjects()
UniValue ListObjects (const std::string & strCachedSignal, const std::string & strType, int nStartTime)
Definition at line 715 of file governance.cpp.
References CGovernanceManager::cs, cs_main, CGovernanceManager::GetAllNewerThan(), GetTime(), governance, GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, LOCK2, Pair(), UniValue::push_back(), COutPoint::ToStringShort(), CGovernanceManager::UpdateLastDiffTime(), UniValue::VOBJ, and VOTE_SIGNAL_FUNDING.
Referenced by gobject_diff(), and gobject_list().
RegisterGovernanceRPCCommands()
void RegisterGovernanceRPCCommands (CRPCTable & t)
Register governance RPC commands.
Definition at line 1240 of file governance.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
voteraw()
UniValue voteraw (const JSONRPCRequest & request)
Definition at line 1089 of file governance.cpp.
References CGovernanceVoting::ConvertVoteOutcome(), CGovernanceVoting::ConvertVoteSignal(), CGovernanceManager::cs, DecodeBase64(), JSONRPCRequest::fHelp, CGovernanceManager::FindGovernanceObject(), g_connman, CMasternodeMan::Get(), UniValue::get_int(), UniValue::get_int64(), UniValue::get_str(), CGovernanceException::GetMessage(), CGovernanceObject::GetObjectType(), CGovernanceVote::GetSignal(), governance, GOVERNANCE_OBJECT_PROPOSAL, CGovernanceVote::IsValid(), JSONRPCError(), LOCK, mnodeman, JSONRPCRequest::params, ParseHashV(), CGovernanceManager::ProcessVoteAndRelay(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, CGovernanceVote::SetSignature(), CGovernanceVote::SetTime(), UniValue::size(), COutPoint::ToStringShort(), VOTE_OUTCOME_NONE, VOTE_SIGNAL_FUNDING, and VOTE_SIGNAL_NONE.
VoteWithMasternodeList()
UniValue VoteWithMasternodeList (const std::vector< CMasternodeConfig::CMasternodeEntry > & entries, const uint256 & hash, vote_signal_enum_t eVoteSignal, vote_outcome_enum_t eVoteOutcome)
Definition at line 469 of file governance.cpp.
References CGovernanceManager::cs, deterministicMNManager, CGovernanceManager::FindGovernanceObject(), g_connman, CMasternodeMan::Get(), CPubKey::GetID(), CMessageSigner::GetKeysFromSecret(), CGovernanceException::GetMessage(), CGovernanceObject::GetObjectType(), governance, GOVERNANCE_OBJECT_PROPOSAL, CDeterministicMNManager::IsDeterministicMNsSporkActive(), JSONRPCError(), masternode_info_t::keyIDVoting, LOCK, mnodeman, masternode_info_t::outpoint, Pair(), ParseInt32(), CGovernanceManager::ProcessVoteAndRelay(), UniValue::push_back(), RPC_INVALID_PARAMETER, base_blob< BITS >::SetHex(), CGovernanceVote::Sign(), strprintf, and UniValue::VOBJ.
Referenced by gobject_vote_alias(), and gobject_vote_many().
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "dash",               "getgovernanceinfo",      &getgovernanceinfo,      true,  {} },
    { "dash",               "getsuperblockbudget",    &getsuperblockbudget,    true,  {"index"} },
    { "dash",               "gobject",                &gobject,                true,  {} },
    { "dash",               "voteraw",                &voteraw,                true,  {} },
}
Definition at line 1229 of file governance.cpp.
Referenced by RegisterGovernanceRPCCommands().
Released under the MIT license