Dash Core: src/wallet/rpcdump.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
rpcdump.cpp File Reference
#include "base58.h"
#include "chain.h"
#include "rpc/server.h"
#include "init.h"
#include "validation.h"
#include "script/script.h"
#include "script/standard.h"
#include "sync.h"
#include "util.h"
#include "utiltime.h"
#include "wallet.h"
#include "merkleblock.h"
#include "core_io.h"
#include <fstream>
#include <stdint.h>
#include <boost/algorithm/string.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <univalue.h>
#include <boost/assign/list_of.hpp>
#include <boost/foreach.hpp>
Functions
void EnsureWalletIsUnlocked ()
bool EnsureWalletIsAvailable (bool avoidException)
static std::string EncodeDumpTime (int64_t nTime)
static int64_t DecodeDumpTime (const std::string &str)
static std::string EncodeDumpString (const std::string &str)
std::string DecodeDumpString (const std::string &str)
UniValue importprivkey (const JSONRPCRequest &request)
void ImportAddress (const CBitcoinAddress &address, const std::string &strLabel)
void ImportScript (const CScript &script, const std::string &strLabel, bool isRedeemScript)
UniValue importaddress (const JSONRPCRequest &request)
UniValue importprunedfunds (const JSONRPCRequest &request)
UniValue removeprunedfunds (const JSONRPCRequest &request)
UniValue importpubkey (const JSONRPCRequest &request)
UniValue importwallet (const JSONRPCRequest &request)
UniValue importelectrumwallet (const JSONRPCRequest &request)
UniValue dumpprivkey (const JSONRPCRequest &request)
UniValue dumphdinfo (const JSONRPCRequest &request)
UniValue dumpwallet (const JSONRPCRequest &request)
UniValue ProcessImport (const UniValue &data, const int64_t timestamp)
int64_t GetImportTimestamp (const UniValue &data, int64_t now)
UniValue importmulti (const JSONRPCRequest &mainRequest)
Function Documentation
DecodeDumpString()
std::string DecodeDumpString (const std::string & str)
Definition at line 63 of file rpcdump.cpp.
Referenced by importwallet().
DecodeDumpTime()
static int64_t DecodeDumpTime (const std::string & str) static
Definition at line 38 of file rpcdump.cpp.
Referenced by importwallet().
dumphdinfo()
UniValue dumphdinfo (const JSONRPCRequest & request)
Definition at line 684 of file rpcdump.cpp.
References CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, CWallet::GetDecryptedHDChain(), CCryptoKeyStore::GetHDChain(), CHDChain::GetMnemonic(), CHDChain::GetSeed(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK, NullUniValue, Pair(), JSONRPCRequest::params, UniValue::push_back(), pwalletMain, RPC_INTERNAL_ERROR, RPC_WALLET_ERROR, UniValue::size(), and UniValue::VOBJ.
dumpprivkey()
UniValue dumpprivkey (const JSONRPCRequest & request)
Definition at line 647 of file rpcdump.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, UniValue::get_str(), CWallet::GetKey(), CBitcoinAddress::GetKeyID(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, RPC_WALLET_ERROR, CBase58Data::SetString(), UniValue::size(), and CBase58Data::ToString().
dumpwallet()
UniValue dumpwallet (const JSONRPCRequest & request)
Definition at line 727 of file rpcdump.cpp.
References _(), chainActive, CLIENT_BUILD, CHDChain::CountAccounts(), cs_main, CWallet::cs_wallet, EncodeDumpString(), EncodeDumpTime(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, UniValue::get_str(), CHDChain::GetAccount(), CWallet::GetAllReserveKeys(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockTime(), CWallet::GetDecryptedHDChain(), CCryptoKeyStore::GetHDChain(), CWallet::GetKey(), CWallet::GetKeyBirthTimes(), CHDChain::GetMnemonic(), CHDChain::GetSeed(), GetTime(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, CWallet::mapHdPubKeys, CExtKey::Neuter(), CHDAccount::nExternalChainCounter, CHDAccount::nInternalChainCounter, NullUniValue, Pair(), JSONRPCRequest::params, UniValue::push_back(), pwalletMain, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, CBitcoinExtKeyBase< K, Size, Type >::SetKey(), CExtKey::SetMaster(), UniValue::size(), strprintf, CChain::Tip(), base_blob< BITS >::ToString(), CBase58Data::ToString(), and UniValue::VOBJ.
Referenced by BOOST_FIXTURE_TEST_CASE().
EncodeDumpString()
static std::string EncodeDumpString (const std::string & str) static
Definition at line 51 of file rpcdump.cpp.
References HexStr().
Referenced by dumpwallet().
EncodeDumpTime()
static std::string EncodeDumpTime (int64_t nTime) static
Definition at line 34 of file rpcdump.cpp.
References DateTimeStrFormat().
Referenced by dumpwallet().
EnsureWalletIsAvailable()
bool EnsureWalletIsAvailable (bool avoidException)
Definition at line 41 of file rpcwallet.cpp.
References JSONRPCError(), pwalletMain, and RPC_METHOD_NOT_FOUND.
Referenced by abandontransaction(), addmultisigaddress(), backupwallet(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), fundrawtransaction(), getaccount(), getaccountaddress(), getaddressesbyaccount(), getbalance(), getnewaddress(), getrawchangeaddress(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), getunconfirmedbalance(), getwalletinfo(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), instantsendtoaddress(), keepass(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), movecmd(), removeprunedfunds(), resendwallettransactions(), sendfrom(), sendmany(), sendtoaddress(), setaccount(), setbip69enabled(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), walletlock(), walletpassphrase(), and walletpassphrasechange().
EnsureWalletIsUnlocked()
void EnsureWalletIsUnlocked ()
Definition at line 53 of file rpcwallet.cpp.
References CCryptoKeyStore::IsLocked(), JSONRPCError(), pwalletMain, and RPC_WALLET_UNLOCK_NEEDED.
Referenced by dumphdinfo(), dumpprivkey(), dumpwallet(), importelectrumwallet(), importmulti(), importprivkey(), importwallet(), instantsendtoaddress(), keypoolrefill(), sendfrom(), sendmany(), sendtoaddress(), and signmessage().
GetImportTimestamp()
int64_t GetImportTimestamp (const UniValue & data, int64_t now)
Definition at line 1172 of file rpcdump.cpp.
References UniValue::exists(), UniValue::get_int64(), UniValue::get_str(), UniValue::isNum(), UniValue::isStr(), JSONRPCError(), RPC_TYPE_ERROR, strprintf, UniValue::type(), and uvTypeName().
Referenced by importmulti().
ImportAddress()
void ImportAddress (const CBitcoinAddress & address, const std::string & strLabel)
Definition at line 180 of file rpcdump.cpp.
References CBitcoinAddress::Get(), GetScriptForDestination(), ImportScript(), CBitcoinAddress::IsValid(), pwalletMain, and CWallet::SetAddressBook().
Referenced by importaddress(), importpubkey(), and ImportScript().
importaddress()
UniValue importaddress (const JSONRPCRequest & request)
Definition at line 189 of file rpcdump.cpp.
References chainActive, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, fPruneMode, CChain::Genesis(), UniValue::get_bool(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), ImportAddress(), ImportScript(), IsHex(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, ParseHex(), pwalletMain, CWallet::ReacceptWalletTransactions(), RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), and UniValue::size().
importelectrumwallet()
UniValue importelectrumwallet (const JSONRPCRequest & request)
Definition at line 514 of file rpcdump.cpp.
References _(), CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, fPruneMode, UniValue::get_int(), UniValue::get_str(), CPubKey::GetID(), CBitcoinSecret::GetKey(), UniValue::getKeys(), CKey::GetPubKey(), CWallet::HaveKey(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, LogPrintf, NullUniValue, JSONRPCRequest::params, pwalletMain, UniValue::read(), RPC_INVALID_PARAMETER, RPC_TYPE_ERROR, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), CBitcoinSecret::SetString(), CWallet::ShowProgress, UniValue::size(), CWallet::UpdateTimeFirstKey(), CKey::VerifyPubKey(), and UniValue::VOBJ.
importmulti()
UniValue importmulti (const JSONRPCRequest & mainRequest)
Definition at line 1186 of file rpcdump.cpp.
References chainActive, UniValue::clear(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), UniValue::exists(), JSONRPCRequest::fHelp, CChain::FindEarliestAtLeast(), CChain::Genesis(), UniValue::get_bool(), CBlockIndex::GetBlockTime(), CBlockIndex::GetBlockTimeMax(), GetImportTimestamp(), CBlockIndex::GetMedianTimePast(), UniValue::getValues(), HelpExampleCli(), JSONRPCError(), LOCK2, CBlockIndex::nHeight, NullUniValue, JSONRPCRequest::params, ProcessImport(), UniValue::push_back(), UniValue::pushKV(), pwalletMain, CWallet::ReacceptWalletTransactions(), RPC_MISC_ERROR, RPCTypeCheck(), CWallet::ScanForWalletTransactions(), UniValue::setArray(), UniValue::size(), strprintf, CChain::Tip(), UniValue::VARR, and UniValue::VOBJ.
Referenced by BOOST_FIXTURE_TEST_CASE().
importprivkey()
UniValue importprivkey (const JSONRPCRequest & request)
Definition at line 77 of file rpcdump.cpp.
References CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, fPruneMode, CChain::Genesis(), UniValue::get_bool(), UniValue::get_str(), CPubKey::GetID(), CBitcoinSecret::GetKey(), CKey::GetPubKey(), CWallet::HaveKey(), HelpExampleCli(), HelpExampleRpc(), CKey::IsValid(), JSONRPCError(), LOCK2, CWallet::mapKeyMetadata, CWallet::MarkDirty(), NullUniValue, JSONRPCRequest::params, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), CWallet::SetAddressBook(), CBitcoinSecret::SetString(), UniValue::size(), CWallet::UpdateTimeFirstKey(), and CKey::VerifyPubKey().
importprunedfunds()
UniValue importprunedfunds (const JSONRPCRequest & request)
Definition at line 257 of file rpcdump.cpp.
References CWallet::AddToWallet(), chainActive, CChain::Contains(), cs_main, CWallet::cs_wallet, DecodeHexTx(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), CMutableTransaction::GetHash(), CMerkleTx::hashBlock, CWallet::IsMine(), JSONRPCError(), LOCK, LOCK2, MakeTransactionRef(), mapBlockIndex, CMerkleTx::nIndex, NullUniValue, JSONRPCRequest::params, ParseHexV(), PROTOCOL_VERSION, pwalletMain, RPC_DESERIALIZATION_ERROR, RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, and UniValue::size().
importpubkey()
UniValue importpubkey (const JSONRPCRequest & request)
Definition at line 352 of file rpcdump.cpp.
References chainActive, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, fPruneMode, CChain::Genesis(), UniValue::get_bool(), UniValue::get_str(), GetScriptForRawPubKey(), HelpExampleCli(), HelpExampleRpc(), ImportAddress(), ImportScript(), IsHex(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, ParseHex(), pwalletMain, CWallet::ReacceptWalletTransactions(), RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), and UniValue::size().
ImportScript()
void ImportScript (const CScript & script, const std::string & strLabel, bool isRedeemScript)
Definition at line 158 of file rpcdump.cpp.
References CWallet::AddCScript(), CWallet::AddWatchOnly(), ExtractDestination(), CBasicKeyStore::HaveCScript(), CBasicKeyStore::HaveWatchOnly(), ImportAddress(), IsMine(), ISMINE_SPENDABLE, JSONRPCError(), CWallet::MarkDirty(), pwalletMain, RPC_WALLET_ERROR, and CWallet::SetAddressBook().
Referenced by ImportAddress(), importaddress(), and importpubkey().
importwallet()
UniValue importwallet (const JSONRPCRequest & request)
Definition at line 410 of file rpcdump.cpp.
References _(), CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, DecodeDumpString(), DecodeDumpTime(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, CChain::FindEarliestAtLeast(), fPruneMode, UniValue::get_str(), CBlockIndex::GetBlockTime(), CPubKey::GetID(), CBitcoinSecret::GetKey(), CKey::GetPubKey(), CWallet::HaveKey(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, LogPrintf, CWallet::mapKeyMetadata, CWallet::MarkDirty(), CBlockIndex::nHeight, NullUniValue, JSONRPCRequest::params, pwalletMain, RPC_INVALID_PARAMETER, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), CWallet::SetAddressBook(), CBitcoinSecret::SetString(), CWallet::ShowProgress, UniValue::size(), CChain::Tip(), CWallet::UpdateTimeFirstKey(), and CKey::VerifyPubKey().
Referenced by BOOST_FIXTURE_TEST_CASE().
ProcessImport()
UniValue ProcessImport (const UniValue & data, const int64_t timestamp)
Definition at line 855 of file rpcdump.cpp.
References CWallet::AddCScript(), CWallet::AddKeyPubKey(), CWallet::AddWatchOnly(), UniValue::exists(), ExtractDestination(), CBitcoinAddress::Get(), UniValue::get_array(), UniValue::get_bool(), UniValue::get_str(), CPubKey::GetID(), CBitcoinSecret::GetKey(), CKey::GetPubKey(), GetScriptForDestination(), GetScriptForRawPubKey(), UniValue::getType(), CBasicKeyStore::HaveCScript(), CWallet::HaveKey(), CBasicKeyStore::HaveWatchOnly(), IsHex(), IsMine(), ISMINE_SPENDABLE, CScript::IsPayToScriptHash(), CKey::IsValid(), CBitcoinAddress::IsValid(), JSONRPCError(), CWallet::mapKeyMetadata, CWallet::MarkDirty(), ParseHex(), UniValue::pushKV(), pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPC_MISC_ERROR, RPC_WALLET_ERROR, CWallet::SetAddressBook(), CBitcoinSecret::SetString(), UniValue::size(), CWallet::UpdateTimeFirstKey(), CKey::VerifyPubKey(), UniValue::VOBJ, and UniValue::VSTR.
Referenced by importmulti().
removeprunedfunds()
UniValue removeprunedfunds (const JSONRPCRequest & request)
Definition at line 316 of file rpcdump.cpp.
References cs_main, CWallet::cs_wallet, DB_LOAD_OK, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, pwalletMain, RPC_INTERNAL_ERROR, base_blob< BITS >::SetHex(), UniValue::size(), and CWallet::ZapSelectTx().
Released under the MIT license