Dash Core: src/rpc/server.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
server.h File Reference
#include "amount.h"
#include "rpc/protocol.h"
#include "uint256.h"
#include <list>
#include <map>
#include <stdint.h>
#include <string>
#include <boost/function.hpp>
#include <univalue.h>
Classes
struct UniValueType
Wrapper for UniValue::VType, which includes typeAny: Used to denote don't care type.
class JSONRPCRequest
class RPCTimerBase
Opaque base class for timers returned by NewTimerFunc.
class RPCTimerInterface
RPC timer "driver".
class CRPCCommand
class CRPCTable
Dash RPC command dispatcher.
Namespaces
RPCServer
Typedefs
typedef UniValue(* rpcfn_type) (const JSONRPCRequest &jsonRequest)
Functions
void RPCServer::OnStarted (boost::function< void()> slot)
void RPCServer::OnStopped (boost::function< void()> slot)
void RPCServer::OnPreCommand (boost::function< void(const CRPCCommand &)> slot)
void RPCServer::OnPostCommand (boost::function< void(const CRPCCommand &)> slot)
bool IsRPCRunning ()
Query whether RPC is running.
void SetRPCWarmupStatus (const std::string &newStatus)
Set the RPC warmup status.
void SetRPCWarmupFinished ()
bool RPCIsInWarmup (std::string *statusOut)
void RPCTypeCheck (const UniValue &params, const std::list< UniValue::VType > &typesExpected, bool fAllowNull=false)
Type-check arguments; throws JSONRPCError if wrong type given.
void RPCTypeCheckArgument (const UniValue &value, UniValue::VType typeExpected)
Type-check one argument; throws JSONRPCError if wrong type given.
void RPCTypeCheckObj (const UniValue &o, const std::map< std::string, UniValueType > &typesExpected, bool fAllowNull=false, bool fStrict=false)
void RPCSetTimerInterface (RPCTimerInterface *iface)
Set the factory function for timers.
void RPCSetTimerInterfaceIfUnset (RPCTimerInterface *iface)
Set the factory function for timer, but only, if unset.
void RPCUnsetTimerInterface (RPCTimerInterface *iface)
Unset factory function for timers.
void RPCRunLater (const std::string &name, boost::function< void(void)> func, int64_t nSeconds)
Run func nSeconds from now.
uint256 ParseHashV (const UniValue &v, std::string strName)
Utilities: convert hex-encoded Values (throws error if not hex).
uint256 ParseHashO (const UniValue &o, std::string strKey)
std::vector< unsigned char > ParseHexV (const UniValue &v, std::string strName)
std::vector< unsigned char > ParseHexO (const UniValue &o, std::string strKey)
int32_t ParseInt32V (const UniValue &v, const std::string &strName)
int64_t ParseInt64V (const UniValue &v, const std::string &strName)
double ParseDoubleV (const UniValue &v, const std::string &strName)
bool ParseBoolV (const UniValue &v, const std::string &strName)
CAmount AmountFromValue (const UniValue &value)
UniValue ValueFromAmount (const CAmount &amount)
double GetDifficulty (const CBlockIndex *blockindex=NULL)
std::string HelpRequiringPassphrase ()
std::string HelpExampleCli (const std::string &methodname, const std::string &args)
std::string HelpExampleRpc (const std::string &methodname, const std::string &args)
void EnsureWalletIsUnlocked ()
bool StartRPC ()
void InterruptRPC ()
void StopRPC ()
std::string JSONRPCExecBatch (const UniValue &vReq)
void RPCNotifyBlockChange (bool ibd, const CBlockIndex *)
Variables
CRPCTable tableRPC
int64_t nWalletUnlockTime
Typedef Documentation
rpcfn_type
typedef UniValue(* rpcfn_type) (const JSONRPCRequest &jsonRequest)
Definition at line 133 of file server.h.
Function Documentation
AmountFromValue()
CAmount AmountFromValue (const UniValue & value)
Definition at line 125 of file server.cpp.
References UniValue::getValStr(), UniValue::isNum(), UniValue::isStr(), JSONRPCError(), MoneyRange(), ParseFixedPoint(), and RPC_TYPE_ERROR.
Referenced by createrawtransaction(), fundrawtransaction(), instantsendtoaddress(), listaddressbalances(), movecmd(), sendfrom(), sendmany(), sendtoaddress(), and settxfee().
EnsureWalletIsUnlocked()
void EnsureWalletIsUnlocked ()
Definition at line 53 of file rpcwallet.cpp.
Referenced by masternodebroadcast(), and signrawtransaction().
GetDifficulty()
double GetDifficulty (const CBlockIndex * blockindex = NULL)
Definition at line 52 of file blockchain.cpp.
References chainActive, CBlockIndex::nBits, and CChain::Tip().
Referenced by blockheaderToJSON(), blockToJSON(), getblockchaininfo(), getchaintips(), getdifficulty(), getinfo(), and getmininginfo().
HelpExampleCli()
std::string HelpExampleCli (const std::string & methodname, const std::string & args)
Definition at line 576 of file server.cpp.
Referenced by abandontransaction(), addmultisigaddress(), addnode(), backupwallet(), bls_generate_help(), clearbanned(), createmultisig(), createrawtransaction(), debug(), decoderawtransaction(), decodescript(), disconnectnode(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), estimatefee(), estimatepriority(), estimatesmartfee(), estimatesmartpriority(), fundrawtransaction(), generate(), generatetoaddress(), getaccount(), getaccountaddress(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getaddressesbyaccount(), getaddressmempool(), getaddresstxids(), getaddressutxos(), getbalance(), getbestblockhash(), getblock(), getblockchaininfo(), getblockcount(), getblockhash(), getblockhashes(), getblockheader(), getblockheaders(), getblocktemplate(), getchaintips(), getconnectioncount(), getdifficulty(), getgovernanceinfo(), getinfo(), getmemoryinfo(), getmempoolancestors(), getmempooldescendants(), getmempoolentry(), getmempoolinfo(), getmininginfo(), getnettotals(), getnetworkhashps(), getnetworkinfo(), getnewaddress(), getpeerinfo(), getrawchangeaddress(), getrawmempool(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), getspecialtxes(), getspentinfo(), getsuperblockbudget(), gettransaction(), gettxout(), gettxoutproof(), gettxoutsetinfo(), getwalletinfo(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importpubkey(), importwallet(), instantsendtoaddress(), invalidateblock(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listbanned(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), movecmd(), ping(), preciousblock(), prioritisetransaction(), protx_info_help(), pruneblockchain(), reconsiderblock(), removeprunedfunds(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), sentinelping(), setaccount(), setban(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), signmessagewithprivkey(), signrawtransaction(), spork(), submitblock(), validateaddress(), verifychain(), verifymessage(), verifytxoutproof(), waitforblock(), waitforblockheight(), waitfornewblock(), walletlock(), walletpassphrase(), and walletpassphrasechange().
HelpExampleRpc()
std::string HelpExampleRpc (const std::string & methodname, const std::string & args)
Definition at line 581 of file server.cpp.
References BaseParams(), GetArg(), and strprintf.
Referenced by abandontransaction(), addmultisigaddress(), addnode(), backupwallet(), clearbanned(), createmultisig(), createrawtransaction(), debug(), decoderawtransaction(), decodescript(), disconnectnode(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), getaccount(), getaccountaddress(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getaddressesbyaccount(), getaddressmempool(), getaddresstxids(), getaddressutxos(), getbalance(), getbestblockhash(), getblock(), getblockchaininfo(), getblockcount(), getblockhash(), getblockhashes(), getblockheader(), getblockheaders(), getblocktemplate(), getchaintips(), getconnectioncount(), getdifficulty(), getgovernanceinfo(), getinfo(), getmemoryinfo(), getmempoolancestors(), getmempooldescendants(), getmempoolentry(), getmempoolinfo(), getmininginfo(), getnettotals(), getnetworkhashps(), getnetworkinfo(), getnewaddress(), getpeerinfo(), getrawchangeaddress(), getrawmempool(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), getspecialtxes(), getspentinfo(), getsuperblockbudget(), gettransaction(), gettxout(), gettxoutproof(), gettxoutsetinfo(), getwalletinfo(), importaddress(), importelectrumwallet(), importprivkey(), importpubkey(), importwallet(), instantsendtoaddress(), invalidateblock(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listbanned(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), movecmd(), ping(), preciousblock(), prioritisetransaction(), pruneblockchain(), reconsiderblock(), removeprunedfunds(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), sentinelping(), setaccount(), setban(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), signmessagewithprivkey(), signrawtransaction(), spork(), submitblock(), validateaddress(), verifychain(), verifymessage(), verifytxoutproof(), waitforblock(), waitforblockheight(), waitfornewblock(), walletlock(), walletpassphrase(), and walletpassphrasechange().
HelpRequiringPassphrase()
std::string HelpRequiringPassphrase ()
Definition at line 34 of file rpcwallet.cpp.
References CCryptoKeyStore::IsCrypted(), and pwalletMain.
Referenced by instantsendtoaddress(), keypoolrefill(), sendfrom(), sendmany(), sendtoaddress(), signmessage(), and signrawtransaction().
InterruptRPC()
void InterruptRPC ()
Definition at line 378 of file server.cpp.
References fRPCRunning, and LogPrint.
Referenced by Interrupt().
IsRPCRunning()
bool IsRPCRunning ()
Query whether RPC is running.
Definition at line 393 of file server.cpp.
References fRPCRunning.
Referenced by CRPCTable::appendCommand(), getblocktemplate(), waitforblock(), waitforblockheight(), and waitfornewblock().
JSONRPCExecBatch()
std::string JSONRPCExecBatch (const UniValue & vReq)
Definition at line 473 of file server.cpp.
References JSONRPCExecOne(), UniValue::push_back(), UniValue::size(), UniValue::VARR, and UniValue::write().
Referenced by HTTPReq_JSONRPC().
ParseBoolV()
bool ParseBoolV (const UniValue & v, const std::string & strName)
Definition at line 205 of file server.cpp.
References UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), UniValue::isBool(), UniValue::isNum(), UniValue::isStr(), itostr(), JSONRPCError(), and RPC_INVALID_PARAMETER.
Referenced by masternode_genkey(), and protx_list().
ParseDoubleV()
double ParseDoubleV (const UniValue & v, const std::string & strName)
Definition at line 196 of file server.cpp.
References UniValue::getValStr(), JSONRPCError(), ParseDouble(), and RPC_INVALID_PARAMETER.
ParseHashO()
uint256 ParseHashO (const UniValue & o, std::string strKey)
Definition at line 160 of file server.cpp.
References find_value(), and ParseHashV().
Referenced by createrawtransaction(), and signrawtransaction().
ParseHashV()
uint256 ParseHashV (const UniValue & v, std::string strName)
Utilities: convert hex-encoded Values (throws error if not hex).
Definition at line 147 of file server.cpp.
References UniValue::get_str(), IsHex(), UniValue::isStr(), JSONRPCError(), RPC_INVALID_PARAMETER, base_blob< BITS >::SetHex(), and strprintf.
Referenced by getmempoolancestors(), getmempooldescendants(), getmempoolentry(), getrawtransaction(), getspentinfo(), gobject_get(), gobject_getcurrentvotes(), gobject_getvotes(), gobject_submit(), gobject_vote_alias(), gobject_vote_conf(), gobject_vote_many(), ParseBlock(), ParseHashO(), protx_info(), and voteraw().
ParseHexO()
std::vector<unsigned char> ParseHexO (const UniValue & o, std::string strKey)
Definition at line 173 of file server.cpp.
References find_value(), and ParseHexV().
Referenced by signrawtransaction().
ParseHexV()
std::vector<unsigned char> ParseHexV (const UniValue & v, std::string strName)
Definition at line 164 of file server.cpp.
References UniValue::get_str(), IsHex(), UniValue::isStr(), JSONRPCError(), ParseHex(), and RPC_INVALID_PARAMETER.
Referenced by createrawtransaction(), decodescript(), importprunedfunds(), ParseHexO(), signrawtransaction(), and verifytxoutproof().
ParseInt32V()
int32_t ParseInt32V (const UniValue & v, const std::string & strName)
Definition at line 178 of file server.cpp.
References UniValue::getValStr(), JSONRPCError(), ParseInt32(), and RPC_INVALID_PARAMETER.
Referenced by ParseBlock(), and protx_list().
ParseInt64V()
int64_t ParseInt64V (const UniValue & v, const std::string & strName)
Definition at line 187 of file server.cpp.
References UniValue::getValStr(), JSONRPCError(), ParseInt64(), and RPC_INVALID_PARAMETER.
RPCIsInWarmup()
bool RPCIsInWarmup (std::string * statusOut)
Definition at line 411 of file server.cpp.
References cs_rpcWarmup, fRPCInWarmup, LOCK, and rpcWarmupStatus().
Referenced by CheckWarmup(), and PrepareShutdown().
RPCNotifyBlockChange()
void RPCNotifyBlockChange (bool ibd, const CBlockIndex *)
Definition at line 195 of file blockchain.cpp.
References cond_blockchange, cs_blockchange, CBlockIndex::GetBlockHash(), CUpdatedBlock::hash, CUpdatedBlock::height, latestblock, and CBlockIndex::nHeight.
Referenced by AppInitMain(), OnRPCStarted(), and OnRPCStopped().
RPCRunLater()
void RPCRunLater (const std::string & name, boost::function< void(void)> func, int64_t nSeconds)
Run func nSeconds from now.
Overrides previous timer <name> (if any).
Definition at line 605 of file server.cpp.
References deadlineTimers, JSONRPCError(), LogPrint, name, RPCTimerInterface::Name(), RPCTimerInterface::NewTimer(), RPC_INTERNAL_ERROR, and timerInterface.
Referenced by walletpassphrase().
RPCSetTimerInterface()
void RPCSetTimerInterface (RPCTimerInterface * iface)
Set the factory function for timers.
Definition at line 594 of file server.cpp.
References timerInterface.
Referenced by StartHTTPRPC().
RPCSetTimerInterfaceIfUnset()
void RPCSetTimerInterfaceIfUnset (RPCTimerInterface * iface)
Set the factory function for timer, but only, if unset.
Definition at line 588 of file server.cpp.
References timerInterface.
Referenced by RPCConsole::RPCConsole().
RPCTypeCheck()
void RPCTypeCheck (const UniValue & params, const std::list< UniValue::VType > & typesExpected, bool fAllowNull = false)
Type-check arguments; throws JSONRPCError if wrong type given.
Does not check that the right number of arguments are passed, just that any passed are the correct type.
Definition at line 70 of file server.cpp.
References UniValue::isNull(), RPCTypeCheckArgument(), and UniValue::size().
Referenced by createrawtransaction(), decoderawtransaction(), decodescript(), estimatefee(), estimatepriority(), estimatesmartfee(), estimatesmartpriority(), fundrawtransaction(), importmulti(), lockunspent(), sendrawtransaction(), setmocktime(), and signrawtransaction().
RPCTypeCheckArgument()
void RPCTypeCheckArgument (const UniValue & value, UniValue::VType typeExpected)
Type-check one argument; throws JSONRPCError if wrong type given.
Definition at line 88 of file server.cpp.
References JSONRPCError(), RPC_TYPE_ERROR, strprintf, UniValue::type(), and uvTypeName().
Referenced by listunspent(), and RPCTypeCheck().
RPCTypeCheckObj()
void RPCTypeCheckObj (const UniValue & o, const std::map< std::string, UniValueType > & typesExpected, bool fAllowNull = false, bool fStrict = false)
Definition at line 95 of file server.cpp.
References find_value(), UniValue::getKeys(), UniValue::isNull(), JSONRPCError(), RPC_TYPE_ERROR, strprintf, UniValue::type(), and uvTypeName().
Referenced by fundrawtransaction(), lockunspent(), and signrawtransaction().
RPCUnsetTimerInterface()
void RPCUnsetTimerInterface (RPCTimerInterface * iface)
Unset factory function for timers.
Definition at line 599 of file server.cpp.
References timerInterface.
Referenced by StopHTTPRPC(), and RPCConsole::~RPCConsole().
SetRPCWarmupFinished()
void SetRPCWarmupFinished ()
Definition at line 404 of file server.cpp.
References cs_rpcWarmup, fRPCInWarmup, and LOCK.
Referenced by AppInitMain().
SetRPCWarmupStatus()
void SetRPCWarmupStatus (const std::string & newStatus)
Set the RPC warmup status.
When this is done, all RPC calls will error out immediately with RPC_IN_WARMUP.
Definition at line 398 of file server.cpp.
References cs_rpcWarmup, LOCK, and rpcWarmupStatus().
Referenced by AppInitMain().
StartRPC()
bool StartRPC ()
Definition at line 370 of file server.cpp.
References fRPCRunning, g_rpcSignals, LogPrint, and CRPCSignals::Started.
Referenced by AppInitServers().
StopRPC()
void StopRPC ()
Definition at line 385 of file server.cpp.
References deadlineTimers, DeleteAuthCookie(), g_rpcSignals, LogPrint, and CRPCSignals::Stopped.
Referenced by PrepareShutdown().
ValueFromAmount()
UniValue ValueFromAmount (const CAmount & amount)
Definition at line 137 of file server.cpp.
References COIN, strprintf, and UniValue::VNUM.
Referenced by AcentryToJSON(), entryToJSON(), estimatefee(), estimatesmartfee(), fundrawtransaction(), getbalance(), getgovernanceinfo(), getinfo(), getnetworkinfo(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), gettxout(), gettxoutsetinfo(), getunconfirmedbalance(), getwalletinfo(), listaccounts(), listaddressbalances(), listaddressgroupings(), ListReceived(), ListTransactions(), listunspent(), mempoolInfoToJSON(), rest_getutxos(), and TxToJSON().
Variable Documentation
nWalletUnlockTime
int64_t nWalletUnlockTime
Definition at line 31 of file rpcwallet.cpp.
Referenced by getinfo(), getwalletinfo(), LockWallet(), walletlock(), and walletpassphrase().
tableRPC
CRPCTable tableRPC
Definition at line 614 of file server.cpp.
Referenced by AppInitParameterInteraction(), CRPCTable::execute(), help(), HTTPReq_JSONRPC(), JSONRPCExecOne(), RegisterEvoRPCCommands(), RPCConsole::RPCParseCommandLine(), RPCConsole::setClientModel(), and WalletTestingSetup::WalletTestingSetup().
Released under the MIT license