Dash Core: src/script/standard.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
standard.h File Reference
#include "script/interpreter.h"
#include "uint256.h"
#include <boost/variant.hpp>
#include <stdint.h>
Classes
class CScriptID
A reference to a CScript: the Hash160 of its serialization (see script.h)
class CNoDestination
Typedefs
typedef boost::variant< CNoDestination, CKeyID, CScriptID > CTxDestination
A txout script template with a specific destination.
Enumerations
enum txnouttype {
TX_NONSTANDARD, TX_PUBKEY, TX_PUBKEYHASH, TX_SCRIPTHASH,
TX_MULTISIG, TX_NULL_DATA
}
Functions
const char * GetTxnOutputType (txnouttype t)
bool Solver (const CScript &scriptPubKey, txnouttype &typeRet, std::vector< std::vector< unsigned char > > &vSolutionsRet)
Return public keys or hashes from scriptPubKey, for 'standard' transaction types.
bool ExtractDestination (const CScript &scriptPubKey, CTxDestination &addressRet)
bool ExtractDestinations (const CScript &scriptPubKey, txnouttype &typeRet, std::vector< CTxDestination > &addressRet, int &nRequiredRet)
CScript GetScriptForDestination (const CTxDestination &dest)
CScript GetScriptForRawPubKey (const CPubKey &pubkey)
CScript GetScriptForMultisig (int nRequired, const std::vector< CPubKey > &keys)
Variables
static const bool DEFAULT_ACCEPT_DATACARRIER = true
static const unsigned int MAX_OP_RETURN_RELAY = 83
bytes (+1 for OP_RETURN, +2 for the pushdata opcodes)
bool fAcceptDatacarrier
unsigned nMaxDatacarrierBytes
static const unsigned int MANDATORY_SCRIPT_VERIFY_FLAGS = SCRIPT_VERIFY_P2SH
Mandatory script verification flags that all new blocks must comply with for them to be valid.
Typedef Documentation
CTxDestination
typedef boost::variant<CNoDestination, CKeyID, CScriptID> CTxDestination
A txout script template with a specific destination.
It is either:
CNoDestination: no destination set
CKeyID: TX_PUBKEYHASH destination
CScriptID: TX_SCRIPTHASH destination A CTxDestination is the internal data type encoded in a CBitcoinAddress
Definition at line 69 of file standard.h.
Enumeration Type Documentation
txnouttype
enum txnouttype
Enumerator
TX_NONSTANDARD
TX_PUBKEY
TX_PUBKEYHASH
TX_SCRIPTHASH
TX_MULTISIG
TX_NULL_DATA
Definition at line 45 of file standard.h.
Function Documentation
ExtractDestination()
bool ExtractDestination (const CScript & scriptPubKey, CTxDestination & addressRet)
Definition at line 162 of file standard.cpp.
References CPubKey::GetID(), CPubKey::IsValid(), Solver(), TX_PUBKEY, TX_PUBKEYHASH, and TX_SCRIPTHASH.
Referenced by CMasternodePayments::CheckBlockVotes(), CheckProRegTx(), CheckProUpRegTx(), CheckWalletOwnsScript(), TransactionRecord::decomposeTransaction(), ExtractDestinations(), CWallet::GetAddressBalances(), CWallet::GetAddressGroupings(), CWalletTx::GetAmounts(), getblocktemplate(), CMasternodeMan::GetMasternodeInfo(), CMasternodePayments::GetMasternodeTxOuts(), GetNextMasternodeForPayment(), CWallet::GetOutpointAndKeysFromOutput(), getreceivedbyaccount(), CSuperblockManager::GetRequiredPaymentsString(), CMasternodeBlockPayees::GetRequiredPaymentsString(), GetRequiredPaymentsString(), CSuperblockManager::GetSuperblockPayments(), ImportScript(), CWallet::IsChange(), CMasternodeBlockPayees::IsTransactionValid(), CMasternodePayments::IsTransactionValid(), CSuperblock::IsValid(), WalletModel::listCoins(), ListReceived(), listunspent(), CProRegTx::MakeSignString(), masternodelist(), CMasternodePayments::ProcessBlock(), ProcessImport(), CMasternodePayments::ProcessMessage(), PaymentServer::processPaymentRequest(), CWallet::SelectCoinsGroupedByAddresses(), TransactionDesc::toHTML(), CProRegTx::ToJson(), CProUpServTx::ToJson(), CProUpRegTx::ToJson(), CDeterministicMNState::ToJson(), CDeterministicMN::ToJson(), CProRegTx::ToString(), CProUpServTx::ToString(), CProUpRegTx::ToString(), CDeterministicMNState::ToString(), MasternodeList::updateDIP3List(), CoinControlDialog::updateLabels(), and CoinControlDialog::updateView().
ExtractDestinations()
bool ExtractDestinations (const CScript & scriptPubKey, txnouttype & typeRet, std::vector< CTxDestination > & addressRet, int & nRequiredRet)
Definition at line 192 of file standard.cpp.
References ExtractDestination(), CPubKey::GetID(), CPubKey::IsValid(), Solver(), TX_MULTISIG, TX_NONSTANDARD, and TX_NULL_DATA.
Referenced by CAffectedKeysVisitor::Process(), ScriptPubKeyToJSON(), and ScriptPubKeyToUniv().
GetScriptForDestination()
CScript GetScriptForDestination (const CTxDestination & dest)
Definition at line 260 of file standard.cpp.
Referenced by CWallet::AddHDPubKey(), CWallet::AddKeyPubKey(), CGovernancePayment::CGovernancePayment(), CMasternode::CheckCollateral(), CWallet::CreateCollateralTransaction(), createrawtransaction(), CWallet::CreateTransaction(), PaymentServer::fetchPaymentACK(), generatetoaddress(), CWallet::GetAccountPubkey(), CMasternodePayments::GetMasternodeTxOuts(), GetNextMasternodeForPayment(), getreceivedbyaddress(), CKeyHolder::GetScriptForDestination(), ImportAddress(), GUIUtil::isDust(), IsMine(), CMasternodePayments::IsScheduled(), CPrivateSendClientSession::MakeCollateralAmounts(), masternodelist(), MutateTxAddOutAddr(), MutateTxAddOutMultiSig(), MutateTxAddOutPubKey(), MutateTxAddOutScript(), WalletModel::prepareTransaction(), CMasternodePayments::ProcessBlock(), ProcessImport(), WalletModelTransaction::reassignAmounts(), sendmany(), SendMoney(), SetupDummyInputs(), CMasternodeBroadcast::SimpleCheck(), CMasternode::UpdateLastPaid(), and validateaddress().
GetScriptForMultisig()
CScript GetScriptForMultisig (int nRequired, const std::vector< CPubKey > & keys)
Definition at line 273 of file standard.cpp.
References CScript::EncodeOP_N(), OP_CHECKMULTISIG, and ToByteVector().
Referenced by _createmultisig_redeemScript(), and MutateTxAddOutMultiSig().
GetScriptForRawPubKey()
CScript GetScriptForRawPubKey (const CPubKey & pubkey)
Definition at line 268 of file standard.cpp.
References CPubKey::begin(), CPubKey::end(), and OP_CHECKSIG.
Referenced by CWallet::AddHDPubKey(), CWallet::AddKeyPubKey(), BOOST_FIXTURE_TEST_CASE(), importpubkey(), MutateTxAddOutPubKey(), and ProcessImport().
GetTxnOutputType()
const char* GetTxnOutputType (txnouttype t)
Definition at line 22 of file standard.cpp.
References TX_MULTISIG, TX_NONSTANDARD, TX_NULL_DATA, TX_PUBKEY, TX_PUBKEYHASH, and TX_SCRIPTHASH.
Referenced by ScriptPubKeyToJSON(), and ScriptPubKeyToUniv().
Solver()
bool Solver (const CScript & scriptPubKey, txnouttype & typeRet, std::vector< std::vector< unsigned char > > & vSolutionsRet)
Return public keys or hashes from scriptPubKey, for 'standard' transaction types.
Definition at line 39 of file standard.cpp.
References prevector< N, T, Size, Diff >::begin(), CScript::clear(), CScript::DecodeOP_N(), prevector< N, T, Size, Diff >::end(), prevector< N, T, Size, Diff >::front(), CScript::GetOp(), CScript::IsPayToScriptHash(), CScript::IsPushOnly(), OP_0, OP_1, OP_16, OP_CHECKMULTISIG, OP_CHECKSIG, OP_DUP, OP_EQUALVERIFY, OP_HASH160, OP_PUBKEY, OP_PUBKEYHASH, OP_PUBKEYS, OP_RETURN, OP_SMALLINTEGER, PAIRTYPE, prevector< N, T, Size, Diff >::size(), TX_MULTISIG, TX_NONSTANDARD, TX_NULL_DATA, TX_PUBKEY, TX_PUBKEYHASH, and TX_SCRIPTHASH.
Referenced by AreInputsStandard(), CombineSignatures(), ExtractDestination(), ExtractDestinations(), IsMine(), CBloomFilter::IsRelevantAndUpdate(), IsStandard(), and SignStep().
Variable Documentation
DEFAULT_ACCEPT_DATACARRIER
const bool DEFAULT_ACCEPT_DATACARRIER = true static
Definition at line 16 of file standard.h.
Referenced by AppInitParameterInteraction(), and HelpMessage().
fAcceptDatacarrier
bool fAcceptDatacarrier
Definition at line 17 of file standard.cpp.
Referenced by AppInitParameterInteraction(), and IsStandard().
MANDATORY_SCRIPT_VERIFY_FLAGS
const unsigned int MANDATORY_SCRIPT_VERIFY_FLAGS = SCRIPT_VERIFY_P2SH static
Mandatory script verification flags that all new blocks must comply with for them to be valid.
(but old blocks may not comply with) Currently just P2SH, but in the future other flags may be added, such as a soft-fork to enforce strict DER encoding.
Failing one of these tests may trigger a DoS ban - see CheckInputs() for details.
Definition at line 43 of file standard.h.
Referenced by AcceptToMemoryPoolWorker().
MAX_OP_RETURN_RELAY
const unsigned int MAX_OP_RETURN_RELAY = 83 static
bytes (+1 for OP_RETURN, +2 for the pushdata opcodes)
Definition at line 30 of file standard.h.
Referenced by HelpMessage().
nMaxDatacarrierBytes
unsigned nMaxDatacarrierBytes
Definition at line 18 of file standard.cpp.
Referenced by AppInitParameterInteraction(), and IsStandard().
Released under the MIT license