Dash Core: src/univalue/include/univalue.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
univalue.h File Reference
#include <stdint.h>
#include <string>
#include <vector>
#include <map>
#include <cassert>
#include <sstream>
#include <utility>
Classes
class UniValue
Enumerations
enum jtokentype {
JTOK_ERR = -1, JTOK_NONE = 0, JTOK_OBJ_OPEN, JTOK_OBJ_CLOSE,
JTOK_ARR_OPEN, JTOK_ARR_CLOSE, JTOK_COLON, JTOK_COMMA,
JTOK_KW_NULL, JTOK_KW_TRUE, JTOK_KW_FALSE, JTOK_NUMBER,
JTOK_STRING
}
Functions
static std::pair< std::string, UniValue > Pair (const char *cKey, const char *cVal)
static std::pair< std::string, UniValue > Pair (const char *cKey, std::string strVal)
static std::pair< std::string, UniValue > Pair (const char *cKey, uint64_t u64Val)
static std::pair< std::string, UniValue > Pair (const char *cKey, int64_t i64Val)
static std::pair< std::string, UniValue > Pair (const char *cKey, bool iVal)
static std::pair< std::string, UniValue > Pair (const char *cKey, int iVal)
static std::pair< std::string, UniValue > Pair (const char *cKey, double dVal)
static std::pair< std::string, UniValue > Pair (const char *cKey, const UniValue &uVal)
static std::pair< std::string, UniValue > Pair (std::string key, const UniValue &uVal)
enum jtokentype getJsonToken (std::string &tokenVal, unsigned int &consumed, const char *raw)
const char * uvTypeName (UniValue::VType t)
static bool jsonTokenIsValue (enum jtokentype jtt)
static bool json_isspace (int ch)
const UniValue & find_value (const UniValue &obj, const std::string &name)
Variables
const UniValue NullUniValue
Enumeration Type Documentation
jtokentype
enum jtokentype
Enumerator
JTOK_ERR
JTOK_NONE
JTOK_OBJ_OPEN
JTOK_OBJ_CLOSE
JTOK_ARR_OPEN
JTOK_ARR_CLOSE
JTOK_COLON
JTOK_COMMA
JTOK_KW_NULL
JTOK_KW_TRUE
JTOK_KW_FALSE
JTOK_NUMBER
JTOK_STRING
Definition at line 226 of file univalue.h.
Function Documentation
find_value()
const UniValue& find_value (const UniValue & obj, const std::string & name)
Definition at line 277 of file univalue.cpp.
References UniValue::keys, name, NullUniValue, and UniValue::values.
Referenced by CommandLineRPC(), createrawtransaction(), decodescript(), getaddressdeltas(), getAddressesFromParams(), getaddresstxids(), getblocktemplate(), getspentinfo(), JSONErrorReply(), lockunspent(), JSONRPCRequest::parse(), ParseHashO(), ParseHexO(), RPCExecutor::request(), RPCConsole::RPCParseCommandLine(), RPCTypeCheckObj(), and signrawtransaction().
getJsonToken()
enum jtokentype getJsonToken (std::string & tokenVal, unsigned int & consumed, const char * raw)
Referenced by validNumStr().
json_isspace()
static bool json_isspace (int ch) inline static
Definition at line 263 of file univalue.h.
Referenced by getJsonToken().
jsonTokenIsValue()
static bool jsonTokenIsValue (enum jtokentype jtt) inline static
Definition at line 246 of file univalue.h.
References JTOK_KW_FALSE, JTOK_KW_NULL, JTOK_KW_TRUE, JTOK_NUMBER, and JTOK_STRING.
Referenced by UniValue::read().
Pair() [1/9]
static std::pair<std::string,UniValue> Pair (const char * cKey, const char * cVal) inline static
Definition at line 166 of file univalue.h.
Referenced by AcentryToJSON(), CKeePassIntegrator::CKeePassRequest::addStrParameter(), BIP9SoftForkDesc(), BIP9SoftForkDescPushBack(), blockheaderToJSON(), blockToJSON(), bls_generate(), BuildDMNListEntry(), createmultisig(), decodescript(), dumphdinfo(), dumpwallet(), entryToJSON(), estimatesmartfee(), estimatesmartpriority(), fundrawtransaction(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getaddressmempool(), getaddressutxos(), getblockchaininfo(), getblocktemplate(), getchaintips(), getgovernanceinfo(), getinfo(), getmemoryinfo(), getmempoolancestors(), getmempooldescendants(), getmininginfo(), getnettotals(), getnetworkinfo(), GetNetworksInfo(), GetNextMasternodeForPayment(), getpeerinfo(), getpoolinfo(), getrawtransaction(), getspentinfo(), gettransaction(), gettxout(), gettxoutsetinfo(), getwalletinfo(), gobject_check(), gobject_get(), gobject_getcurrentvotes(), gobject_getvotes(), gobject_vote_conf(), JSONRPCError(), JSONRPCReplyObj(), JSONRPCRequestObj(), listaccounts(), listaddressbalances(), listbanned(), listlockunspent(), ListObjects(), ListReceived(), listsinceblock(), ListTransactions(), listunspent(), masternode_check(), masternode_count(), masternode_list_conf(), masternode_status(), masternode_winners(), masternodebroadcast(), masternodelist(), MaybePushAddress(), mempoolInfoToJSON(), mempoolToJSON(), mnsync(), rest_getutxos(), RPCLockedMemoryInfo(), ScriptPubKeyToJSON(), signrawtransaction(), SoftForkDesc(), SoftForkMajorityDesc(), spork(), CCbTx::ToJson(), llmq::CFinalCommitment::ToJson(), CProRegTx::ToJson(), CSimplifiedMNListEntry::ToJson(), CProUpServTx::ToJson(), llmq::CFinalCommitmentTxPayload::ToJson(), CSimplifiedMNListDiff::ToJson(), CProUpRegTx::ToJson(), CDeterministicMNState::ToJson(), CDeterministicMN::ToJson(), CProUpRevTx::ToJson(), CGovernanceManager::ToJson(), TxInErrorToJSON(), TxToJSON(), validateaddress(), VoteWithMasternodeList(), waitforblock(), waitforblockheight(), waitfornewblock(), and WalletTxToJSON().
Pair() [2/9]
static std::pair<std::string,UniValue> Pair (const char * cKey, std::string strVal) inline static
Definition at line 173 of file univalue.h.
Pair() [3/9]
static std::pair<std::string,UniValue> Pair (const char * cKey, uint64_t u64Val) inline static
Definition at line 180 of file univalue.h.
Pair() [4/9]
static std::pair<std::string,UniValue> Pair (const char * cKey, int64_t i64Val) inline static
Definition at line 187 of file univalue.h.
Pair() [5/9]
static std::pair<std::string,UniValue> Pair (const char * cKey, bool iVal) inline static
Definition at line 194 of file univalue.h.
Pair() [6/9]
static std::pair<std::string,UniValue> Pair (const char * cKey, int iVal) inline static
Definition at line 201 of file univalue.h.
Pair() [7/9]
static std::pair<std::string,UniValue> Pair (const char * cKey, double dVal) inline static
Definition at line 208 of file univalue.h.
Pair() [8/9]
static std::pair<std::string,UniValue> Pair (const char * cKey, const UniValue & uVal) inline static
Definition at line 215 of file univalue.h.
Pair() [9/9]
static std::pair<std::string,UniValue> Pair (std::string key, const UniValue & uVal) inline static
Definition at line 221 of file univalue.h.
uvTypeName()
const char* uvTypeName (UniValue::VType t)
Definition at line 262 of file univalue.cpp.
References UniValue::VARR, UniValue::VBOOL, UniValue::VNULL, UniValue::VNUM, UniValue::VOBJ, and UniValue::VSTR.
Referenced by GetImportTimestamp(), RPCTypeCheckArgument(), and RPCTypeCheckObj().
Variable Documentation
NullUniValue
const UniValue NullUniValue
Definition at line 78 of file univalue.cpp.
Referenced by abandontransaction(), addmultisigaddress(), addnode(), backupwallet(), BIP22ValidationResult(), clearbanned(), disconnectnode(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), find_value(), fundrawtransaction(), getaccount(), getaccountaddress(), getaddressesbyaccount(), getbalance(), getblocktemplate(), getnewaddress(), getrawchangeaddress(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), gettxout(), getunconfirmedbalance(), getwalletinfo(), HTTPReq_JSONRPC(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), instantsendtoaddress(), invalidateblock(), JSONErrorReply(), JSONRPCExecOne(), JSONRPCReplyObj(), JSONRPCRequest::JSONRPCRequest(), keepass(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), masternode_winners(), masternodebroadcast(), movecmd(), UniValue::operator[](), ping(), preciousblock(), reconsiderblock(), removeprunedfunds(), resendwallettransactions(), sendfrom(), sendmany(), sendtoaddress(), setaccount(), setban(), setbip69enabled(), setmocktime(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), walletlock(), walletpassphrase(), and walletpassphrasechange().
Released under the MIT license