Dash Core: src/util.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
util.cpp File Reference
#include "util.h"
#include "support/allocators/secure.h"
#include "chainparamsbase.h"
#include "ctpl.h"
#include "random.h"
#include "serialize.h"
#include "sync.h"
#include "utilstrencodings.h"
#include "utiltime.h"
#include <stdarg.h>
#include <algorithm>
#include <fcntl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/algorithm/string/join.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/split.hpp>
#include <boost/algorithm/string/classification.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/foreach.hpp>
#include <boost/program_options/detail/config_file.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/thread.hpp>
#include <openssl/crypto.h>
#include <openssl/rand.h>
#include <openssl/conf.h>
Classes
class CInit
Functions
std::atomic< bool > fReopenDebugLog (false)
void locking_callback (int mode, int i, const char *file, int line) NO_THREAD_SAFETY_ANALYSIS
static int FileWriteStr (const std::string &str, FILE *fp)
static void DebugPrintInit ()
void OpenDebugLog ()
bool LogAcceptCategory (const char *category)
Return true if log accepts specified category.
static std::string LogTimestampStr (const std::string &str, std::atomic_bool *fStartedNewLine)
fStartedNewLine is a state variable held by the calling context that will suppress printing of the timestamp when multiple calls are made that don't end in a newline.
static std::string LogThreadNameStr (const std::string &str, std::atomic_bool *fStartedNewLine)
fStartedNewLine is a state variable held by the calling context that will suppress printing of the thread name when multiple calls are made that don't end in a newline.
int LogPrintStr (const std::string &str)
Send a string to the log output.
static bool InterpretBool (const std::string &strValue)
Interpret string as boolean, for argument parsing.
static void InterpretNegativeSetting (std::string &strKey, std::string &strValue)
Turn -noX into -X=0.
void ParseParameters (int argc, const char *const argv[])
bool IsArgSet (const std::string &strArg)
Return true if the given argument has been manually set.
std::string GetArg (const std::string &strArg, const std::string &strDefault)
Return string argument or default value.
int64_t GetArg (const std::string &strArg, int64_t nDefault)
Return integer argument or default value.
bool GetBoolArg (const std::string &strArg, bool fDefault)
Return boolean argument or default value.
bool SoftSetArg (const std::string &strArg, const std::string &strValue)
Set an argument if it doesn't already have a value.
bool SoftSetBoolArg (const std::string &strArg, bool fValue)
Set a boolean argument if it doesn't already have a value.
void ForceSetArg (const std::string &strArg, const std::string &strValue)
void ForceSetMultiArgs (const std::string &strArg, const std::vector< std::string > &values)
void ForceRemoveArg (const std::string &strArg)
std::string HelpMessageGroup (const std::string &message)
Format a string to be used as group of options in help messages.
std::string HelpMessageOpt (const std::string &option, const std::string &message)
Format a string to be used as option description in help messages.
static std::string FormatException (const std::exception *pex, const char *pszThread)
void PrintExceptionContinue (const std::exception *pex, const char *pszThread)
boost::filesystem::path GetDefaultDataDir ()
const boost::filesystem::path & GetDataDir (bool fNetSpecific)
boost::filesystem::path GetBackupsDir ()
void ClearDatadirCache ()
boost::filesystem::path GetConfigFile (const std::string &confPath)
boost::filesystem::path GetMasternodeConfigFile ()
void ReadConfigFile (const std::string &confPath)
boost::filesystem::path GetPidFile ()
void CreatePidFile (const boost::filesystem::path &path, pid_t pid)
bool RenameOver (boost::filesystem::path src, boost::filesystem::path dest)
bool TryCreateDirectory (const boost::filesystem::path &p)
Ignores exceptions thrown by Boost's create_directory if the requested directory exists.
void FileCommit (FILE *file)
bool TruncateFile (FILE *file, unsigned int length)
int RaiseFileDescriptorLimit (int nMinFD)
this function tries to raise the file descriptor limit to the requested number.
void AllocateFileRange (FILE *file, unsigned int offset, unsigned int length)
this function tries to make a particular range of a file allocated (corresponding to disk space) it is advisory, and the range specified in the arguments will never contain live data
void ShrinkDebugFile ()
void runCommand (const std::string &strCommand)
void RenameThread (const char *name)
std::string GetThreadName ()
void RenameThreadPool (ctpl::thread_pool &tp, const char *baseName)
void SetupEnvironment ()
bool SetupNetworking ()
int GetNumCores ()
Return the number of physical cores available on the current system.
std::string CopyrightHolders (const std::string &strPrefix, unsigned int nStartYear, unsigned int nEndYear)
uint32_t StringVersionToInt (const std::string &strVersion)
Converts version strings to 4-byte unsigned integer.
std::string IntVersionToString (uint32_t nVersion)
Converts version as 4-byte unsigned integer to string.
std::string SafeIntVersionToString (uint32_t nVersion)
Copy of the IntVersionToString, that returns "Invalid version" string instead of throwing std::bad_cast.
Variables
bool fMasternodeMode = false
bool fLiteMode = false
int nWalletBackups = 10
nWalletBackups: 1..10 - number of automatic backups to keep 0 - disabled by command-line -1 - disabled because of some error during run-time -2 - disabled because wallet was locked and we were not able to replenish keypool
const char *const BITCOIN_CONF_FILENAME = "dash.conf"
const char *const BITCOIN_PID_FILENAME = "dashd.pid"
CCriticalSection cs_args
std::map< std::string, std::string > mapArgs
static std::map< std::string, std::vector< std::string > > _mapMultiArgs
const std::map< std::string, std::vector< std::string > > & mapMultiArgs = _mapMultiArgs
bool fDebug = false
bool fPrintToConsole = false
bool fPrintToDebugLog = true
bool fLogTimestamps = DEFAULT_LOGTIMESTAMPS
bool fLogTimeMicros = DEFAULT_LOGTIMEMICROS
bool fLogThreadNames = DEFAULT_LOGTHREADNAMES
bool fLogIPs = DEFAULT_LOGIPS
CTranslationInterface translationInterface
static CCriticalSection ** ppmutexOpenSSL
Init OpenSSL library multithreading support.
class CInit instance_of_cinit
static boost::once_flag debugPrintInitFlag = BOOST_ONCE_INIT
LogPrintf() has been broken a couple of times now by well-meaning people adding mutexes in the most straightforward way.
static FILE * fileout = NULL
We use boost::call_once() to make sure mutexDebugLog and vMsgsBeforeOpenLog are initialized in a thread-safe manner.
static boost::mutex * mutexDebugLog = NULL
static std::list< std::string > * vMsgsBeforeOpenLog
static const int screenWidth = 79
static const int optIndent = 2
static const int msgIndent = 7
static boost::filesystem::path pathCached
static boost::filesystem::path pathCachedNetSpecific
static CCriticalSection csPathCached
Function Documentation
AllocateFileRange()
void AllocateFileRange (FILE * file, unsigned int offset, unsigned int length)
this function tries to make a particular range of a file allocated (corresponding to disk space) it is advisory, and the range specified in the arguments will never contain live data
Definition at line 784 of file util.cpp.
Referenced by FindBlockPos(), and FindUndoPos().
ClearDatadirCache()
void ClearDatadirCache ()
Definition at line 627 of file util.cpp.
References csPathCached, LOCK, pathCached, and pathCachedNetSpecific.
Referenced by ReadConfigFile().
CopyrightHolders()
std::string CopyrightHolders (const std::string & strPrefix, unsigned int nStartYear, unsigned int nEndYear)
Definition at line 978 of file util.cpp.
References _(), and strprintf.
Referenced by LicenseInfo(), and SplashScreen::SplashScreen().
CreatePidFile()
void CreatePidFile (const boost::filesystem::path & path, pid_t pid)
Definition at line 691 of file util.cpp.
Referenced by AppInitMain().
DebugPrintInit()
static void DebugPrintInit () static
Definition at line 224 of file util.cpp.
References mutexDebugLog, and vMsgsBeforeOpenLog.
Referenced by LogPrintStr(), and OpenDebugLog().
FileCommit()
void FileCommit (FILE * file)
Definition at line 732 of file util.cpp.
Referenced by DumpMempool(), FlushBlockFile(), CAddrDB::Write(), and CBanDB::Write().
FileWriteStr()
static int FileWriteStr (const std::string & str, FILE * fp) static
Definition at line 219 of file util.cpp.
Referenced by LogPrintStr(), and OpenDebugLog().
ForceRemoveArg()
void ForceRemoveArg (const std::string & strArg)
Definition at line 511 of file util.cpp.
References _mapMultiArgs, cs_args, LOCK, and mapArgs.
Referenced by CWallet::GenerateNewHDChain(), InitParameterInteraction(), and CWallet::ParameterInteraction().
ForceSetArg()
void ForceSetArg (const std::string & strArg, const std::string & strValue)
Definition at line 499 of file util.cpp.
References cs_args, LOCK, and mapArgs.
Referenced by debug(), and InitParameterInteraction().
ForceSetMultiArgs()
void ForceSetMultiArgs (const std::string & strArg, const std::vector< std::string > & values)
Definition at line 505 of file util.cpp.
References _mapMultiArgs, cs_args, and LOCK.
Referenced by debug().
FormatException()
static std::string FormatException (const std::exception * pex, const char * pszThread) static
Definition at line 533 of file util.cpp.
References MAX_PATH, and strprintf.
Referenced by PrintExceptionContinue().
fReopenDebugLog()
std::atomic<bool> fReopenDebugLog (false)
Referenced by LogPrintStr().
GetArg() [1/2]
std::string GetArg (const std::string & strArg, const std::string & strDefault)
Return string argument or default value.
Parameters
strArg Argument to get (e.g. "-foo")
default (e.g. "1")
Returns
command-line argument or default value
Definition at line 458 of file util.cpp.
References cs_args, LOCK, and mapArgs.
Referenced by AcceptToMemoryPoolWorker(), ActivateBestChainStep(), OptionsModel::addOverriddenOption(), BlockAssembler::addPriorityTxs(), AddTimeData(), AddToCompactExtraTransactions(), CWallet::AddToWallet(), AppInit(), AppInitMain(), AppInitParameterInteraction(), AppInitRPC(), TorController::auth_cb(), CConnman::Ban(), BitcoinApplication::BitcoinApplication(), BitcoinGUI::BitcoinGUI(), BlockAssembler::BlockAssembler(), BlockNotifyCallback(), CallRPC(), CZMQNotificationInterface::Create(), BlockAssembler::CreateNewBlock(), CWallet::CreateTransaction(), CWallet::CreateWalletFromFile(), debug(), CBlockPolicyEstimator::estimateSmartFee(), CBlockPolicyEstimator::estimateSmartPriority(), CDB::Flush(), FlushStateToDisk(), CWallet::GenerateNewHDChain(), GetAuthCookieFile(), GetBackupsDir(), GetDataDir(), GetDevNetName(), GetLangTerritory(), GetListenPort(), GetMasternodeConfigFile(), GetPidFile(), HelpExampleRpc(), HTTPBindAddresses(), OptionsModel::Init(), CKeePassIntegrator::init(), CWallet::InitAutoBackup(), InitHTTPServer(), CWallet::InitLoadWallet(), InitParameterInteraction(), InitRPCAuthentication(), InitSignatureCache(), Intro::Intro(), InvalidateBlock(), LoadMempool(), PaymentServer::LoadRootCAs(), main(), mempoolInfoToJSON(), Misbehaving(), CAlert::Notify(), GUIUtil::openConfigfile(), CWallet::ParameterInteraction(), Intro::pickDataDirectory(), ProcessMessage(), TorController::protocolinfo_cb(), RPCConsole::RPCConsole(), CWallet::SelectCoins(), CAlert::Sign(), StartHTTPServer(), CWallet::TopUpKeyPool(), TorControlThread(), CWallet::Unlock(), CInstantSend::UpdateLockedTransaction(), CTxMemPool::UsedMemoryShare(), CWallet::Verify(), and verifychain().
GetArg() [2/2]
int64_t GetArg (const std::string & strArg, int64_t nDefault)
Return integer argument or default value.
Parameters
strArg Argument to get (e.g. "-foo")
default (e.g. 1)
Returns
command-line argument (0 if invalid number) or default value
Definition at line 466 of file util.cpp.
References atoi64(), cs_args, LOCK, and mapArgs.
GetBackupsDir()
boost::filesystem::path GetBackupsDir ()
Definition at line 617 of file util.cpp.
References GetArg(), GetDataDir(), and IsArgSet().
Referenced by AutoBackupWallet(), and GUIUtil::showBackups().
GetBoolArg()
bool GetBoolArg (const std::string & strArg, bool fDefault)
Return boolean argument or default value.
Parameters
strArg Argument to get (e.g. "-foo")
default (true or false)
Returns
command-line argument or default value
Definition at line 474 of file util.cpp.
References cs_args, InterpretBool(), LOCK, and mapArgs.
Referenced by AcceptToMemoryPoolWorker(), BlockAssembler::AddToBlock(), AppInit(), AppInitBasicSetup(), AppInitMain(), AppInitParameterInteraction(), AppInitRawTx(), AppInitRPC(), AppInitServers(), CDBWrapper::CDBWrapper(), ChainNameFromCommandLine(), CWallet::ChangeWalletPassphrase(), CommandLineRPC(), CWallet::CreateTransaction(), CWallet::CreateWalletFromFile(), CWallet::EncryptWallet(), PaymentRequestPlus::getMerchant(), GetWarnings(), HelpMessage(), HelpMessageDialog::HelpMessageDialog(), CKeePassIntegrator::init(), CWallet::InitAutoBackup(), InitBlockIndex(), InitHTTPServer(), BitcoinApplication::initializeResult(), CWallet::InitLoadWallet(), InitLogging(), InitParameterInteraction(), WalletModel::isWalletEnabled(), main(), OnRPCPreCommand(), CDBEnv::Open(), OutputTx(), CWallet::ParameterInteraction(), Intro::pickDataDirectory(), ProcessMessage(), RegisterWalletRPCCommands(), CWallet::SelectCoins(), SplashScreen::SplashScreen(), CConnman::Start(), CConnman::ThreadDNSAddressSeed(), ThreadFlushWalletDB(), ThreadImport(), CWallet::Unlock(), and CWallet::Verify().
GetConfigFile()
boost::filesystem::path GetConfigFile (const std::string & confPath)
Definition at line 635 of file util.cpp.
References GetDataDir().
Referenced by AppInitMain(), CallRPC(), GUIUtil::openConfigfile(), and ReadConfigFile().
GetDataDir()
const boost::filesystem::path& GetDataDir (bool fNetSpecific)
Definition at line 587 of file util.cpp.
References BaseParams(), csPathCached, CBaseChainParams::DataDir(), GetArg(), GetDefaultDataDir(), IsArgSet(), LOCK, pathCached, and pathCachedNetSpecific.
Referenced by AppInit(), AppInitMain(), AppInitRPC(), AutoBackupWallet(), CWallet::BackupWallet(), CAddrDB::CAddrDB(), CBanDB::CBanDB(), CDB::CDB(), CFlatDB< T >::CFlatDB(), CheckDiskSpace(), CleanupBlockRevFiles(), ClientModel::dataDir(), DumpMempool(), GetAuthCookieFile(), GetBackupsDir(), GetBlockPosFilename(), GetConfigFile(), GetMasternodeConfigFile(), GetPidFile(), TorController::GetPrivateKeyFile(), ipcServerName(), LoadMempool(), LockDataDirectory(), LogPrintStr(), main(), OpenDebugLog(), GUIUtil::openDebugLogfile(), PrepareShutdown(), RPCConsole::RPCConsole(), ShrinkDebugFile(), ThreadImport(), CWallet::Verify(), CAddrDB::Write(), and CBanDB::Write().
GetDefaultDataDir()
boost::filesystem::path GetDefaultDataDir ()
Definition at line 556 of file util.cpp.
Referenced by AppInitMain(), GetDataDir(), and Intro::getDefaultDataDirectory().
GetMasternodeConfigFile()
boost::filesystem::path GetMasternodeConfigFile ()
Definition at line 644 of file util.cpp.
References GetArg(), and GetDataDir().
Referenced by AppInitMain(), GUIUtil::openMNConfigfile(), and CMasternodeConfig::read().
GetNumCores()
int GetNumCores ()
Return the number of physical cores available on the current system.
Note
This does not count virtual cores, such as those provided by HyperThreading when boost is newer than 1.56.
Definition at line 969 of file util.cpp.
Referenced by AppInitParameterInteraction(), CCheckQueueSpeed(), CCheckQueueSpeedPrevectorJob(), HelpMessage(), and OptionsDialog::OptionsDialog().
GetPidFile()
boost::filesystem::path GetPidFile ()
Definition at line 684 of file util.cpp.
References BITCOIN_PID_FILENAME, GetArg(), and GetDataDir().
Referenced by AppInitMain(), and PrepareShutdown().
GetThreadName()
std::string GetThreadName ()
Definition at line 894 of file util.cpp.
References name.
Referenced by LogAcceptCategory(), and LogThreadNameStr().
HelpMessageGroup()
std::string HelpMessageGroup (const std::string & message)
Format a string to be used as group of options in help messages.
Parameters
message Group name (e.g. "RPC server options:")
Returns
the formatted string
Definition at line 522 of file util.cpp.
Referenced by AppendParamsHelpMessages(), AppInitRawTx(), CWallet::GetWalletHelpString(), HelpMessage(), HelpMessageCli(), and HelpMessageDialog::HelpMessageDialog().
HelpMessageOpt()
std::string HelpMessageOpt (const std::string & option, const std::string & message)
Format a string to be used as option description in help messages.
Parameters
option Option message (e.g. "-rpcuser=<user>")
message Option description (e.g. "Username for JSON-RPC connections")
Returns
the formatted string
Definition at line 526 of file util.cpp.
References FormatParagraph(), msgIndent, optIndent, and screenWidth.
Referenced by AppendParamsHelpMessages(), AppInitRawTx(), CWallet::GetWalletHelpString(), HelpMessage(), HelpMessageCli(), and HelpMessageDialog::HelpMessageDialog().
InterpretBool()
static bool InterpretBool (const std::string & strValue) static
Interpret string as boolean, for argument parsing.
Definition at line 399 of file util.cpp.
References atoi().
Referenced by GetBoolArg(), and InterpretNegativeSetting().
InterpretNegativeSetting()
static void InterpretNegativeSetting (std::string & strKey, std::string & strValue) static
Turn -noX into -X=0.
Definition at line 407 of file util.cpp.
References InterpretBool().
Referenced by ParseParameters(), and ReadConfigFile().
IntVersionToString()
std::string IntVersionToString (uint32_t nVersion)
Converts version as 4-byte unsigned integer to string.
Parameters
nVersion 4-byte unsigned integer, most significant byte is always 0
Returns
version string in "x.x.x" format (last 3 bytes as version parts) Throws std::bad_cast if format doesn match.
Definition at line 1009 of file util.cpp.
Referenced by SafeIntVersionToString().
IsArgSet()
bool IsArgSet (const std::string & strArg)
Return true if the given argument has been manually set.
Parameters
strArg Argument to get (e.g. "-foo")
Returns
true if the argument has been set
Definition at line 452 of file util.cpp.
References cs_args, LOCK, and mapArgs.
Referenced by AppInit(), AppInitMain(), AppInitParameterInteraction(), AppInitRawTx(), AppInitRPC(), BlockAssembler::BlockAssembler(), ChainNameFromCommandLine(), CMasternodeMan::CheckAndRemove(), CZMQNotificationInterface::Create(), CWallet::CreateWalletFromFile(), CWallet::GenerateNewHDChain(), GetBackupsDir(), GetDataDir(), GetDevNetName(), HTTPBindAddresses(), InitParameterInteraction(), main(), CWallet::ParameterInteraction(), ProcessMessage(), SplashScreen::SplashScreen(), CConnman::ThreadOpenMasternodeConnections(), and ThreadSendAlert().
locking_callback()
void locking_callback (int mode, int i, const char * file, int line)
Definition at line 144 of file util.cpp.
References ENTER_CRITICAL_SECTION, LEAVE_CRITICAL_SECTION, and ppmutexOpenSSL.
Referenced by CInit::CInit().
LogAcceptCategory()
bool LogAcceptCategory (const char * category)
Return true if log accepts specified category.
Definition at line 253 of file util.cpp.
References fDebug, GetThreadName(), LogPrintf, and mapMultiArgs.
Referenced by InitHTTPServer(), CBitcoinLevelDBLogger::Logv(), and CWallet::SelectCoinsGroupedByAddresses().
LogPrintStr()
int LogPrintStr (const std::string & str)
Send a string to the log output.
Definition at line 352 of file util.cpp.
References DebugPrintInit(), debugPrintInitFlag, fileout, FileWriteStr(), fPrintToConsole, fPrintToDebugLog, fReopenDebugLog(), GetDataDir(), LogThreadNameStr(), LogTimestampStr(), mutexDebugLog, and vMsgsBeforeOpenLog.
Referenced by error(), and CBitcoinLevelDBLogger::Logv().
LogThreadNameStr()
static std::string LogThreadNameStr (const std::string & str, std::atomic_bool * fStartedNewLine) static
fStartedNewLine is a state variable held by the calling context that will suppress printing of the thread name when multiple calls are made that don't end in a newline.
Initialize it to true, and hold/manage it, in the calling context.
Definition at line 335 of file util.cpp.
References fLogThreadNames, GetThreadName(), and strprintf.
Referenced by LogPrintStr().
LogTimestampStr()
static std::string LogTimestampStr (const std::string & str, std::atomic_bool * fStartedNewLine) static
fStartedNewLine is a state variable held by the calling context that will suppress printing of the timestamp when multiple calls are made that don't end in a newline.
Initialize it to true, and hold/manage it, in the calling context.
Definition at line 311 of file util.cpp.
References DateTimeStrFormat(), fLogTimeMicros, fLogTimestamps, GetLogTimeMicros(), and strprintf.
Referenced by LogPrintStr().
OpenDebugLog()
void OpenDebugLog ()
Definition at line 231 of file util.cpp.
References DebugPrintInit(), debugPrintInitFlag, fileout, FileWriteStr(), GetDataDir(), mutexDebugLog, and vMsgsBeforeOpenLog.
Referenced by AppInitMain().
ParseParameters()
void ParseParameters (int argc, const char *const argv[])
Definition at line 416 of file util.cpp.
References _mapMultiArgs, cs_args, InterpretNegativeSetting(), LOCK, and mapArgs.
Referenced by AppInit(), AppInitRawTx(), AppInitRPC(), and main().
PrintExceptionContinue()
void PrintExceptionContinue (const std::exception * pex, const char * pszThread)
Definition at line 549 of file util.cpp.
References FormatException(), and LogPrintf.
Referenced by AppInit(), CommandLineRawTx(), CommandLineRPC(), BitcoinCore::handleRunawayException(), main(), ProcessMessages(), and TraceThread().
RaiseFileDescriptorLimit()
int RaiseFileDescriptorLimit (int nMinFD)
this function tries to raise the file descriptor limit to the requested number.
It returns the actual file descriptor limit (which may be more or less than nMinFD)
Definition at line 761 of file util.cpp.
Referenced by AppInitParameterInteraction().
ReadConfigFile()
void ReadConfigFile (const std::string & confPath)
Definition at line 652 of file util.cpp.
References _mapMultiArgs, ClearDatadirCache(), cs_args, GetConfigFile(), InterpretNegativeSetting(), LOCK, and mapArgs.
Referenced by AppInit(), AppInitRPC(), and main().
RenameOver()
bool RenameOver (boost::filesystem::path src, boost::filesystem::path dest)
Definition at line 702 of file util.cpp.
Referenced by DumpMempool(), ThreadImport(), CAddrDB::Write(), and CBanDB::Write().
RenameThread()
void RenameThread (const char * name)
Definition at line 878 of file util.cpp.
References name.
Referenced by HTTPWorkQueueRun(), PrepareShutdown(), RenameThreadPool(), ThreadFlushWalletDB(), ThreadHTTP(), ThreadImport(), ThreadScriptCheck(), and TraceThread().
RenameThreadPool()
void RenameThreadPool (ctpl::thread_pool & tp, const char * baseName)
Definition at line 909 of file util.cpp.
References MilliSleep(), ctpl::thread_pool::push(), RenameThread(), ctpl::thread_pool::size(), and strprintf.
Referenced by CBLSWorker::CBLSWorker().
runCommand()
void runCommand (const std::string & strCommand)
Definition at line 871 of file util.cpp.
References LogPrintf.
Referenced by CWallet::AddToWallet(), BlockNotifyCallback(), CAlert::Notify(), and CInstantSend::UpdateLockedTransaction().
SafeIntVersionToString()
std::string SafeIntVersionToString (uint32_t nVersion)
Copy of the IntVersionToString, that returns "Invalid version" string instead of throwing std::bad_cast.
Parameters
nVersion 4-byte unsigned integer, most significant byte is always 0
Returns
version string in "x.x.x" format (last 3 bytes as version parts) or "Invalid version" if can't cast the given value
Definition at line 1025 of file util.cpp.
References IntVersionToString().
Referenced by CMasternodePing::GetSentinelString(), and MasternodeList::ShowQRCode().
SetupEnvironment()
void SetupEnvironment ()
Definition at line 928 of file util.cpp.
Referenced by main().
SetupNetworking()
bool SetupNetworking ()
Definition at line 957 of file util.cpp.
Referenced by AppInitBasicSetup(), and main().
ShrinkDebugFile()
void ShrinkDebugFile ()
Definition at line 826 of file util.cpp.
References GetDataDir().
Referenced by AppInitMain().
SoftSetArg()
bool SoftSetArg (const std::string & strArg, const std::string & strValue)
Set an argument if it doesn't already have a value.
Parameters
strArg Argument to set (e.g. "-foo")
strValue Value (e.g. "1")
Returns
true if argument gets set, false if it already had a value
Definition at line 482 of file util.cpp.
References cs_args, LOCK, and mapArgs.
Referenced by OptionsModel::Init(), Intro::pickDataDirectory(), and SoftSetBoolArg().
SoftSetBoolArg()
bool SoftSetBoolArg (const std::string & strArg, bool fValue)
Set a boolean argument if it doesn't already have a value.
Parameters
strArg Argument to set (e.g. "-foo")
fValue Value (e.g. false)
Returns
true if argument gets set, false if it already had a value
Definition at line 491 of file util.cpp.
References SoftSetArg().
Referenced by AppInit(), OptionsModel::Init(), InitParameterInteraction(), CWalletDB::LoadWallet(), and CWallet::ParameterInteraction().
StringVersionToInt()
uint32_t StringVersionToInt (const std::string & strVersion)
Converts version strings to 4-byte unsigned integer.
Parameters
strVersion version in "x.x.x" format (decimal digits only)
Returns
4-byte unsigned integer, most significant byte is always 0 Throws std::bad_cast if format doesn match.
Definition at line 989 of file util.cpp.
Referenced by sentinelping().
TruncateFile()
bool TruncateFile (FILE * file, unsigned int length)
Definition at line 749 of file util.cpp.
Referenced by FlushBlockFile().
TryCreateDirectory()
bool TryCreateDirectory (const boost::filesystem::path & p)
Ignores exceptions thrown by Boost's create_directory if the requested directory exists.
Specifically handles case where path p exists, but it wasn't possible for the user to write to the parent directory.
Definition at line 718 of file util.cpp.
Referenced by CDBWrapper::CDBWrapper(), CDBEnv::Open(), and Intro::pickDataDirectory().
Variable Documentation
_mapMultiArgs
std::map<std::string, std::vector<std::string> > _mapMultiArgs static
Definition at line 129 of file util.cpp.
Referenced by ForceRemoveArg(), ForceSetMultiArgs(), ParseParameters(), and ReadConfigFile().
BITCOIN_CONF_FILENAME
const char* const BITCOIN_CONF_FILENAME = "dash.conf"
Definition at line 124 of file util.cpp.
Referenced by AppInit(), AppInitMain(), AppInitRPC(), CallRPC(), HelpMessage(), HelpMessageCli(), main(), and GUIUtil::openConfigfile().
BITCOIN_PID_FILENAME
const char* const BITCOIN_PID_FILENAME = "dashd.pid"
Definition at line 125 of file util.cpp.
Referenced by GetPidFile(), and HelpMessage().
cs_args
CCriticalSection cs_args
Definition at line 127 of file util.cpp.
Referenced by ForceRemoveArg(), ForceSetArg(), ForceSetMultiArgs(), GetArg(), GetBoolArg(), IsArgSet(), ParseParameters(), ReadConfigFile(), and SoftSetArg().
csPathCached
CCriticalSection csPathCached static
Definition at line 585 of file util.cpp.
Referenced by ClearDatadirCache(), and GetDataDir().
debugPrintInitFlag
boost::once_flag debugPrintInitFlag = BOOST_ONCE_INIT static
LogPrintf() has been broken a couple of times now by well-meaning people adding mutexes in the most straightforward way.
It breaks because it may be called by global destructors during shutdown. Since the order of destruction of static/global objects is undefined, defining a mutex as a global object doesn't work (the mutex gets destroyed, and then some later destructor calls OutputDebugStringF, maybe indirectly, and you get a core dump at shutdown trying to lock the mutex).
Definition at line 204 of file util.cpp.
Referenced by LogPrintStr(), and OpenDebugLog().
fDebug
bool fDebug = false
Definition at line 131 of file util.cpp.
Referenced by AppInitMain(), AppInitParameterInteraction(), debug(), IsBlockPayeeValid(), IsBlockValueValid(), LogAcceptCategory(), ProcessMessage(), CConnman::SetNetworkActive(), TransactionDesc::toHTML(), and CoinControlDialog::updateView().
fileout
FILE* fileout = NULL static
We use boost::call_once() to make sure mutexDebugLog and vMsgsBeforeOpenLog are initialized in a thread-safe manner.
NOTE: fileout, mutexDebugLog and sometimes vMsgsBeforeOpenLog are leaked on exit. This is ugly, but will be cleaned up by the OS/libc. When the shutdown sequence is fully audited and tested, explicit destruction of these objects can be implemented.
Definition at line 215 of file util.cpp.
Referenced by LogPrintStr(), OpenDebugLog(), CFlatDB< T >::Write(), CAddrDB::Write(), CBanDB::Write(), TxConfirmStats::Write(), CBlockPolicyEstimator::Write(), WriteBlockToDisk(), and CTxMemPool::WriteFeeEstimates().
fLiteMode
bool fLiteMode = false
Definition at line 114 of file util.cpp.
Referenced by AppInitMain(), CheckProRegTx(), CheckProUpRegTx(), BitcoinGUI::createActions(), BitcoinGUI::createToolBars(), CPrivateSendServer::DoMaintenance(), CMasternodeMan::DoMaintenance(), CPrivateSendClientManager::DoMaintenance(), CGovernanceManager::DoMaintenance(), CWallet::GetAnonymizableBalance(), CWallet::GetAnonymizedBalance(), CWallet::GetAverageAnonymizedRounds(), CWallet::GetDenominatedBalance(), getinfo(), CWallet::GetNeedsToBeAnonymizedBalance(), CWallet::GetNormalizedAnonymizedBalance(), getwalletinfo(), WalletView::gotoMasternodePage(), IsBlockPayeeValid(), IsBlockValueValid(), OverviewPage::OverviewPage(), PrepareShutdown(), CMasternodePayments::ProcessBlock(), CPrivateSendServer::ProcessMessage(), CInstantSend::ProcessMessage(), CPrivateSendClientSession::ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), CGovernanceManager::ProcessMessage(), CSporkManager::ProcessSpork(), SendCoinsDialog::SendCoinsDialog(), WalletView::setClientModel(), BitcoinGUI::setNumBlocks(), BitcoinGUI::setWalletActionsEnabled(), OverviewPage::setWalletModel(), WalletView::setWalletModel(), OverviewPage::updateAdvancedPSUI(), CDSNotificationInterface::UpdatedBlockTip(), CMasternodeSync::UpdatedBlockTip(), CPrivateSend::UpdatedBlockTip(), CMasternodeMan::UpdateLastPaid(), and WalletView::WalletView().
fLogIPs
bool fLogIPs = DEFAULT_LOGIPS
Definition at line 138 of file util.cpp.
Referenced by CNode::CNode(), InitLogging(), and ProcessMessage().
fLogThreadNames
bool fLogThreadNames = DEFAULT_LOGTHREADNAMES
Definition at line 137 of file util.cpp.
Referenced by InitLogging(), and LogThreadNameStr().
fLogTimeMicros
bool fLogTimeMicros = DEFAULT_LOGTIMEMICROS
Definition at line 136 of file util.cpp.
Referenced by InitLogging(), and LogTimestampStr().
fLogTimestamps
bool fLogTimestamps = DEFAULT_LOGTIMESTAMPS
Definition at line 135 of file util.cpp.
Referenced by AppInitMain(), InitLogging(), and LogTimestampStr().
fMasternodeMode
bool fMasternodeMode = false
Definition at line 113 of file util.cpp.
Referenced by CConnman::AcceptConnection(), CPrivateSendServer::AddEntry(), CPrivateSendServer::AddUserToExistingSession(), AppInitMain(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CMasternode::Check(), CPrivateSendServer::CheckForCompleteQueue(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), CPrivateSendServer::CheckPool(), CPrivateSendClientSession::CheckPoolStateUpdate(), CPrivateSendServer::CheckTimeout(), CPrivateSendClientSession::CheckTimeout(), CPrivateSendClientManager::CheckTimeout(), CPrivateSendServer::CommitFinalTransaction(), CPrivateSendClientSession::CompletedTransaction(), CPrivateSendServer::CreateNewSession(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientManager::DoAutomaticDenominating(), CPrivateSendServer::DoMaintenance(), CMasternodeMan::DoMaintenance(), CPrivateSendClientManager::DoMaintenance(), getpoolinfo(), CActiveDeterministicMasternodeManager::Init(), CPrivateSendServer::IsAcceptableDSA(), CMasternodePaymentVote::IsValid(), CActiveLegacyMasternodeManager::ManageState(), masternode_status(), OverviewPage::OverviewPage(), PrepareShutdown(), CMasternodePayments::ProcessBlock(), CPrivateSendServer::ProcessMessage(), CPrivateSendClientSession::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), CMasternodeSync::ProcessTick(), CGovernanceManager::RequestGovernanceObjectVotes(), CWallet::SelectCoinsGroupedByAddresses(), CWallet::SelectPrivateCoins(), CPrivateSendClientSession::SendDenominate(), SendMessages(), CMasternodeMan::SendVerifyReply(), CPrivateSendServer::SetState(), CPrivateSendQueue::Sign(), CPrivateSendBroadcastTx::Sign(), CPrivateSendClientSession::SignFinalTransaction(), CMasternodeBroadcast::Update(), CActiveDeterministicMasternodeManager::UpdatedBlockTip(), llmq::CDummyDKG::UpdatedBlockTip(), CMasternodeMan::UpdatedBlockTip(), CPrivateSendClientManager::UpdatedSuccessBlock(), CMasternode::UpdateFromNewBroadcast(), and CInstantSend::Vote().
fPrintToConsole
bool fPrintToConsole = false
Definition at line 132 of file util.cpp.
Referenced by InitLogging(), and LogPrintStr().
fPrintToDebugLog
bool fPrintToDebugLog = true
Definition at line 133 of file util.cpp.
Referenced by AppInitMain(), InitLogging(), LogPrintStr(), and main().
instance_of_cinit
class CInit instance_of_cinit
mapArgs
std::map<std::string, std::string> mapArgs
Definition at line 128 of file util.cpp.
Referenced by ForceRemoveArg(), ForceSetArg(), GetArg(), GetBoolArg(), IsArgSet(), ParseParameters(), ReadConfigFile(), and SoftSetArg().
mapMultiArgs
const std::map<std::string, std::vector<std::string> >& mapMultiArgs = _mapMultiArgs
Definition at line 130 of file util.cpp.
Referenced by AppInitMain(), AppInitParameterInteraction(), HTTPBindAddresses(), InitHTTPAllowList(), InitParameterInteraction(), LogAcceptCategory(), multiUserAuthorized(), CConnman::Start(), CConnman::ThreadOpenAddedConnections(), CConnman::ThreadOpenConnections(), and CConnman::ThreadOpenMasternodeConnections().
msgIndent
const int msgIndent = 7 static
Definition at line 520 of file util.cpp.
Referenced by HelpMessageOpt().
mutexDebugLog
boost::mutex* mutexDebugLog = NULL static
Definition at line 216 of file util.cpp.
Referenced by DebugPrintInit(), LogPrintStr(), and OpenDebugLog().
nWalletBackups
int nWalletBackups = 10
nWalletBackups: 1..10 - number of automatic backups to keep 0 - disabled by command-line -1 - disabled because of some error during run-time -2 - disabled because wallet was locked and we were not able to replenish keypool
Definition at line 122 of file util.cpp.
Referenced by AutoBackupWallet(), CPrivateSendClientManager::CheckAutomaticBackup(), OverviewPage::DisablePrivateSendCompletely(), CWallet::GetWalletHelpString(), CWallet::InitAutoBackup(), CWallet::KeepKey(), OverviewPage::OverviewPage(), OverviewPage::privateSendStatus(), and CWallet::Unlock().
optIndent
const int optIndent = 2 static
Definition at line 519 of file util.cpp.
Referenced by HelpMessageOpt().
pathCached
boost::filesystem::path pathCached static
Definition at line 583 of file util.cpp.
Referenced by ClearDatadirCache(), and GetDataDir().
pathCachedNetSpecific
boost::filesystem::path pathCachedNetSpecific static
Definition at line 584 of file util.cpp.
Referenced by ClearDatadirCache(), and GetDataDir().
ppmutexOpenSSL
CCriticalSection** ppmutexOpenSSL static
Init OpenSSL library multithreading support.
Definition at line 143 of file util.cpp.
Referenced by CInit::CInit(), locking_callback(), and CInit::~CInit().
screenWidth
const int screenWidth = 79 static
Definition at line 518 of file util.cpp.
Referenced by HelpMessageOpt().
translationInterface
CTranslationInterface translationInterface
Definition at line 140 of file util.cpp.
Referenced by _(), and main().
vMsgsBeforeOpenLog
std::list<std::string>* vMsgsBeforeOpenLog static
Definition at line 217 of file util.cpp.
Referenced by DebugPrintInit(), LogPrintStr(), and OpenDebugLog().
Released under the MIT license