Dash Core: src/util.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
util.h File Reference
#include "compat.h"
#include "tinyformat.h"
#include "utiltime.h"
#include "amount.h"
#include <atomic>
#include <exception>
#include <map>
#include <stdint.h>
#include <string>
#include <vector>
#include <boost/filesystem/path.hpp>
#include <boost/signals2/signal.hpp>
#include <boost/thread/exceptions.hpp>
Classes
class CTranslationInterface
Signals for translation.
Namespaces
ctpl
Macros
#define DBG(x)
Server/client environment: argument handling, config file parsing, logging, thread wrappers.
#define LogPrint(category, ...)
#define LogPrintf(...)
Functions
std::string _ (const char *psz)
Translation function: Call Translate signal on UI interface, which returns a boost::optional result.
void SetupEnvironment ()
bool SetupNetworking ()
bool LogAcceptCategory (const char *category)
Return true if log accepts specified category.
int LogPrintStr (const std::string &str)
Send a string to the log output.
template<typename... Args>
std::string SafeStringFormat (const std::string &fmt, const Args &... args)
Formats a string without throwing exceptions.
template<typename... Args>
bool error (const char *fmt, const Args &... args)
void PrintExceptionContinue (const std::exception *pex, const char *pszThread)
void ParseParameters (int argc, const char *const argv[])
void FileCommit (FILE *file)
bool TruncateFile (FILE *file, unsigned int length)
int RaiseFileDescriptorLimit (int nMinFD)
this function tries to raise the file descriptor limit to the requested number.
void AllocateFileRange (FILE *file, unsigned int offset, unsigned int length)
this function tries to make a particular range of a file allocated (corresponding to disk space) it is advisory, and the range specified in the arguments will never contain live data
bool RenameOver (boost::filesystem::path src, boost::filesystem::path dest)
bool TryCreateDirectory (const boost::filesystem::path &p)
Ignores exceptions thrown by Boost's create_directory if the requested directory exists.
boost::filesystem::path GetDefaultDataDir ()
const boost::filesystem::path & GetDataDir (bool fNetSpecific=true)
boost::filesystem::path GetBackupsDir ()
void ClearDatadirCache ()
boost::filesystem::path GetConfigFile (const std::string &confPath)
boost::filesystem::path GetMasternodeConfigFile ()
boost::filesystem::path GetPidFile ()
void CreatePidFile (const boost::filesystem::path &path, pid_t pid)
void ReadConfigFile (const std::string &confPath)
void OpenDebugLog ()
void ShrinkDebugFile ()
void runCommand (const std::string &strCommand)
bool IsSwitchChar (char c)
bool IsArgSet (const std::string &strArg)
Return true if the given argument has been manually set.
std::string GetArg (const std::string &strArg, const std::string &strDefault)
Return string argument or default value.
int64_t GetArg (const std::string &strArg, int64_t nDefault)
Return integer argument or default value.
bool GetBoolArg (const std::string &strArg, bool fDefault)
Return boolean argument or default value.
bool SoftSetArg (const std::string &strArg, const std::string &strValue)
Set an argument if it doesn't already have a value.
bool SoftSetBoolArg (const std::string &strArg, bool fValue)
Set a boolean argument if it doesn't already have a value.
void ForceSetArg (const std::string &strArg, const std::string &strValue)
void ForceSetMultiArgs (const std::string &strArg, const std::vector< std::string > &values)
void ForceRemoveArg (const std::string &strArg)
std::string HelpMessageGroup (const std::string &message)
Format a string to be used as group of options in help messages.
std::string HelpMessageOpt (const std::string &option, const std::string &message)
Format a string to be used as option description in help messages.
int GetNumCores ()
Return the number of physical cores available on the current system.
void RenameThread (const char *name)
std::string GetThreadName ()
void RenameThreadPool (ctpl::thread_pool &tp, const char *baseName)
template<typename Callable >
void TraceThread (const char *name, Callable func)
std::string CopyrightHolders (const std::string &strPrefix, unsigned int nStartYear, unsigned int nEndYear)
uint32_t StringVersionToInt (const std::string &strVersion)
Converts version strings to 4-byte unsigned integer.
std::string IntVersionToString (uint32_t nVersion)
Converts version as 4-byte unsigned integer to string.
std::string SafeIntVersionToString (uint32_t nVersion)
Copy of the IntVersionToString, that returns "Invalid version" string instead of throwing std::bad_cast.
Variables
bool fMasternodeMode
bool fLiteMode
int nWalletBackups
nWalletBackups: 1..10 - number of automatic backups to keep 0 - disabled by command-line -1 - disabled because of some error during run-time -2 - disabled because wallet was locked and we were not able to replenish keypool
static const bool DEFAULT_LOGTIMEMICROS = false
static const bool DEFAULT_LOGIPS = false
static const bool DEFAULT_LOGTIMESTAMPS = true
static const bool DEFAULT_LOGTHREADNAMES = false
const std::map< std::string, std::vector< std::string > > & mapMultiArgs
bool fDebug
bool fPrintToConsole
bool fPrintToDebugLog
bool fLogTimestamps
bool fLogTimeMicros
bool fLogThreadNames
bool fLogIPs
std::atomic< bool > fReopenDebugLog
CTranslationInterface translationInterface
const char *const BITCOIN_CONF_FILENAME
const char *const BITCOIN_PID_FILENAME
Macro Definition Documentation
DBG
#define DBG (x)
Server/client environment: argument handling, config file parsing, logging, thread wrappers.
Definition at line 42 of file util.h.
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceTriggerManager::AddNewTrigger(), CGovernanceTriggerManager::CleanAndRemove(), CSuperblock::CSuperblock(), CHDChain::Debug(), CWallet::EncryptWallet(), CGovernanceTriggerManager::GetActiveTriggers(), CSuperblockManager::GetBestSuperblock(), CGovernanceObject::GetHash(), CSuperblockManager::GetSuperblockPayments(), gobject_submit(), CGovernanceObject::IsCollateralValid(), CSuperblockManager::IsSuperblockTriggered(), CGovernanceObject::LoadData(), ParsePaymentAmount(), CSuperblock::ParsePaymentSchedule(), and CMasternodePayments::RequestLowDataPaymentBlocks().
LogPrint
#define LogPrint (category, ...)
Value:
do { \
    if (LogAcceptCategory((category))) { \
        LogPrintStr(SafeStringFormat(__VA_ARGS__)); \
    } \
} while(0)
Definition at line 110 of file util.h.
Referenced by CConnman::AcceptConnection(), CMasternodeSync::AcceptedBlockHeader(), AcceptToMemoryPoolWithTime(), AcceptToMemoryPoolWorker(), CMasternodeMan::Add(), CAddrMan::Add(), TorController::add_onion_cb(), CPrivateSendServer::AddEntry(), CGovernanceManager::AddGovernanceObject(), AddOrphanTx(), CMasternodePayments::AddOrUpdatePaymentVote(), CPrivateSendServer::AddScriptSig(), AddTimeData(), AdvertiseLocal(), CNode::AskFor(), TorController::auth_cb(), TorController::authchallenge_cb(), CCoinsViewDB::BatchWrite(), CMasternodeSync::BumpAssetLastTime(), CMasternode::Check(), CTxMemPool::check(), CInstantSend::CheckAndRemove(), CMasternodeMan::CheckAndRemove(), CMasternodePayments::CheckAndRemove(), CMasternodePing::CheckAndUpdate(), CPrivateSendClientManager::CheckAutomaticBackup(), CMasternodePayments::CheckBlockVotes(), CPrivateSend::CheckDSTXes(), CPrivateSendServer::CheckForCompleteQueue(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), CPrivateSendServer::CheckPool(), CPrivateSendClientSession::CheckPool(), CPrivateSendBaseManager::CheckQueue(), CGovernanceVote::CheckSignature(), CPrivateSendServer::CheckTimeout(), CPrivateSendClientSession::CheckTimeout(), CMasternodeMan::CheckVerifyRequestAddr(), CGovernanceTriggerManager::CleanAndRemove(), CGovernanceManager::Clear(), CNode::CloseSocketDisconnect(), CNode::CNode(), CPrivateSendServer::CommitFinalTransaction(), CGovernanceManager::ConfirmInventoryRequest(), ConnectBlock(), CConnman::ConnectNode(), ConnectSocketDirectly(), ConnectTip(), CPrivateSendClientSession::CreateDenominated(), CPrivateSendServer::CreateFinalTransaction(), BlockAssembler::CreateNewBlock(), CPrivateSendServer::CreateNewSession(), CInstantSend::CreateTxLockCandidate(), CSuperblock::CSuperblock(), DebugMessageHandler(), TorController::disconnected_cb(), DisconnectTip(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientManager::DoAutomaticDenominating(), CMasternodeMan::DoFullVerificationStep(), CKeePassIntegrator::doHTTPPost(), CMasternodeMan::DsegUpdate(), CConnman::DumpAddresses(), CConnman::DumpBanlist(), EraseOrphansFor(), TxConfirmStats::EstimateMedianVal(), TorControlConnection::eventcb(), CSporkManager::ExecuteSpork(), PartiallyDownloadedBlock::FillBlock(), FillBlockPayments(), FindFilesToPrune(), CMasternodeMan::FindRandomNotInVec(), CDBEnv::Flush(), CMasternodeBlockPayees::GetBestPayee(), CSuperblock::GetPaymentsLimit(), CWallet::GetRealOutpointPrivateSendRounds(), CSuperblockManager::GetRequiredPaymentsString(), CSporkManager::GetSporkIDByName(), CSporkManager::GetSporkNameByID(), CSporkManager::GetSporkValue(), CSuperblockManager::GetSuperblockPayments(), CAddrMan::Good_(), CMasternodeBlockPayees::HasPayeeWithVotes(), http_reject_request_cb(), http_request_cb(), HTTPBindAddresses(), PartiallyDownloadedBlock::InitData(), InitHTTPAllowList(), InitHTTPServer(), CZMQNotificationInterface::Initialize(), CZMQAbstractPublishNotifier::Initialize(), InterruptHTTPRPC(), InterruptHTTPServer(), InterruptRPC(), CPrivateSendServer::IsAcceptableDSA(), IsBlockPayeeValid(), IsBlockValueValid(), CPrivateSend::IsCollateralValid(), CSuperblock::IsExpired(), CPrivateSendServer::IsInputScriptSigValid(), IsOldBudgetBlockValueValid(), CSporkManager::IsSporkActive(), CSuperblockManager::IsSuperblockTriggered(), CMasternodeBlockPayees::IsTransactionValid(), CGovernanceVote::IsValid(), CMasternodePaymentVote::IsValid(), CSuperblock::IsValid(), CTxLockRequest::IsValid(), CTxLockVote::IsValid(), CPrivateSendClientSession::JoinExistingQueue(), libevent_log_cb(), LimitMempoolSize(), LimitOrphanTxSize(), LoadExternalBlockFile(), CInstantSend::LockTransactionInputs(), CPrivateSendClientSession::MakeCollateralAmounts(), CDBEnv::MakeMock(), CActiveLegacyMasternodeManager::ManageState(), CActiveLegacyMasternodeManager::ManageStateInitial(), CActiveLegacyMasternodeManager::ManageStateRemote(), PeerLogicValidation::NewPoWValidBlock(), CZMQPublishHashBlockNotifier::NotifyBlock(), CZMQPublishRawBlockNotifier::NotifyBlock(), CZMQPublishHashGovernanceObjectNotifier::NotifyGovernanceObject(), CZMQPublishRawGovernanceObjectNotifier::NotifyGovernanceObject(), CZMQPublishHashGovernanceVoteNotifier::NotifyGovernanceVote(), CZMQPublishRawGovernanceVoteNotifier::NotifyGovernanceVote(), CMasternodeSync::NotifyHeaderTip(), CZMQPublishHashInstantSendDoubleSpendNotifier::NotifyInstantSendDoubleSpendAttempt(), CZMQPublishRawInstantSendDoubleSpendNotifier::NotifyInstantSendDoubleSpendAttempt(), CZMQPublishHashTransactionNotifier::NotifyTransaction(), CZMQPublishRawTransactionNotifier::NotifyTransaction(), CZMQPublishHashTransactionLockNotifier::NotifyTransactionLock(), CZMQPublishRawTransactionLockNotifier::NotifyTransactionLock(), OnRPCStopped(), JSONRPCRequest::parse(), CAlert::ProcessAlert(), CMasternodePayments::ProcessBlock(), CBlockPolicyEstimator::processBlock(), CBlockPolicyEstimator::processBlockTx(), ProcessGetData(), CPrivateSendServer::ProcessMessage(), CInstantSend::ProcessMessage(), CPrivateSendClientSession::ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), CGovernanceManager::ProcessMessage(), ProcessMessage(), CInstantSend::ProcessNewTxLockVote(), CInstantSend::ProcessOrphanTxLockVote(), CPrivateSendClientSession::ProcessPendingDsaRequest(), CMasternodeMan::ProcessPendingMnbRequests(), CMasternodeMan::ProcessPendingMnvRequests(), CSporkManager::ProcessSpork(), CMasternodeSync::ProcessTick(), CBlockPolicyEstimator::processTransaction(), CInstantSend::ProcessTxLockRequest(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), CGovernanceObject::ProcessVote(), CGovernanceManager::ProcessVote(), TorController::protocolinfo_cb(), pruneblockchain(), CNode::PushInventory(), CConnman::PushMessage(), RandAddSeedPerfmon(), TxConfirmStats::Read(), TorControlConnection::readcb(), CNode::ReceiveMsgBytes(), RegisterHTTPHandler(), CMasternodePing::Relay(), CGovernanceVote::Relay(), CMasternodePaymentVote::Relay(), CGovernanceObject::Relay(), CMasternodeBroadcast::Relay(), CPrivateSendServer::RelayCompletedTransaction(), CPrivateSendServer::RelayFinalTransaction(), TxConfirmStats::removeTx(), CGovernanceManager::RequestGovernanceObject(), CGovernanceManager::RequestGovernanceObjectVotes(), CGovernanceManager::RequestOrphanObjects(), CInstantSend::ResolveConflicts(), CKeePassIntegrator::rpcAssociate(), CKeePassIntegrator::rpcGetLogins(), RPCRunLater(), CKeePassIntegrator::rpcSetLogin(), CKeePassIntegrator::rpcTestAssociation(), CWallet::SelectCoinsGroupedByAddresses(), CWallet::SelectCoinsMinConf(), CWallet::SelectPSInOutPairsByDenominations(), CActiveLegacyMasternodeManager::SendMasternodePing(), SendMessages(), CGovernanceObject::SerializationOp(), CConnman::SetNetworkActive(), CPrivateSendServer::SetState(), CZMQNotificationInterface::Shutdown(), CZMQAbstractPublishNotifier::Shutdown(), CGovernanceObject::Sign(), CPrivateSendClientSession::SignFinalTransaction(), CMasternodePing::SimpleCheck(), Socks5(), CConnman::Start(), StartHTTPRPC(), StartHTTPServer(), StartRPC(), StopHTTPRPC(), StopHTTPServer(), StopRPC(), CPrivateSendClientSession::SubmitDenominate(), CConnman::SweepBanned(), CMasternodeMan::SyncAll(), CGovernanceManager::SyncAll(), CMasternodeMan::SyncSingle(), CGovernanceManager::SyncSingleObjAndItsVotes(), PeerLogicValidation::SyncTransaction(), CInstantSend::SyncTransaction(), CPrivateSend::SyncTransaction(), ThreadFlushWalletDB(), ThreadHTTP(), CConnman::ThreadOpenConnections(), CConnman::ThreadSocketHandler(), OverviewPage::togglePrivateSend(), TorController::TorController(), CTxMemPool::TrimToSize(), CInstantSend::TryToFinalizeLockCandidate(), UnregisterHTTPHandler(), CAddrMan::Unserialize(), CGovernanceManager::UpdateCachesAndClean(), CMasternodeSync::UpdatedBlockTip(), CMasternodePayments::UpdatedBlockTip(), CMasternodeMan::UpdatedBlockTip(), CPrivateSendClientManager::UpdatedBlockTip(), CGovernanceManager::UpdatedBlockTip(), CMasternodeMan::UpdateLastPaid(), CMasternode::UpdateLastPaid(), CInstantSend::UpdateLockedTransaction(), CInstantSend::Vote(), CWalletDB::ZapSelectTx(), and zmqError().
LogPrintf
#define LogPrintf (...)
Value:
do { \
    LogPrintStr(SafeStringFormat(__VA_ARGS__)); \
} while(0)
Definition at line 116 of file util.h.
Referenced by CConnman::AcceptConnection(), TorController::add_onion_cb(), CGovernanceManager::AddGovernanceObject(), CKeyHolderStorage::AddKey(), AddLocal(), CGovernanceTriggerManager::AddNewTrigger(), CPrivateSendServer::AddScriptSig(), BlockAssembler::AddToBlock(), CWallet::AddToWallet(), CWallet::AddToWalletIfInvolvingMe(), CPrivateSendServer::AddUserToExistingSession(), AppInitMain(), AppInitParameterInteraction(), CNode::AskFor(), CMasternodeMan::AskForMN(), TorController::auth_cb(), TorController::authchallenge_cb(), AutoBackupWallet(), CWallet::BackupWallet(), CConnman::BindListenPort(), CDeterministicMNManager::BuildNewListFromBlock(), CDBWrapper::CDBWrapper(), CGovernancePayment::CGovernancePayment(), CWallet::ChangeWalletPassphrase(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CMasternode::Check(), CAddrMan::Check(), CInstantSend::CheckAndRemove(), CMasternodeMan::CheckAndRemove(), CMasternodePayments::CheckAndRemove(), CMasternodePing::CheckAndUpdate(), CPrivateSendClientManager::CheckAutomaticBackup(), CMasternodePayments::CheckBlockVotes(), CheckForkWarningConditions(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CGovernanceObject::CheckOrphanVotes(), CMasternodeBroadcast::CheckOutpoint(), CPrivateSendClientSession::CheckPoolStateUpdate(), CGovernanceManager::CheckPostponedObjects(), CMasternodeMan::CheckSameAddr(), CMasternodePing::CheckSignature(), CGovernanceVote::CheckSignature(), CSporkMessage::CheckSignature(), CPrivateSendQueue::CheckSignature(), CGovernanceObject::CheckSignature(), CTxLockVote::CheckSignature(), CPrivateSendBroadcastTx::CheckSignature(), CMasternodeBroadcast::CheckSignature(), CleanupBlockRevFiles(), CPrivateSendServer::CommitFinalTransaction(), CWallet::CommitTransaction(), CPrivateSendClientSession::CompletedTransaction(), TorControlConnection::Connect(), ConnectBlock(), TorController::connected_cb(), CConnman::ConnectNode(), ConnectSocketDirectly(), CWallet::ConvertList(), CGovernanceVoting::ConvertOutcomeToString(), CGovernanceVoting::ConvertSignalToString(), CGovernanceVoting::ConvertVoteOutcome(), CGovernanceVoting::ConvertVoteSignal(), CPrivateSendClientSession::CreateDenominated(), CInstantSend::CreateEmptyTxLockCandidate(), llmq::CDummyDKG::CreateFinalCommitment(), BlockAssembler::CreateNewBlock(), CPrivateSendServer::CreateNewSession(), CInstantSend::CreateTxLockCandidate(), CWallet::CreateWalletFromFile(), DecryptAES256(), DeleteAuthCookie(), DisconnectBlocks(), Discover(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientManager::DoAutomaticDenominating(), CMasternodeMan::DsegUpdate(), CFlatDB< T >::Dump(), DumpMempool(), EncryptAES256(), CWallet::EncryptWallet(), CDBEnv::EnvShutdown(), CSporkManager::ExecuteSpork(), CDBWrapper::Exists(), CTxMemPool::existsProviderTxConflict(), FindBlockPos(), FindFilesToPruneManual(), CMasternodeMan::FindRandomNotInVec(), FindUndoPos(), CWalletDB::FindWalletTx(), GenerateAuthCookie(), CWallet::GenerateNewHDChain(), CWalletTx::GetAmounts(), CWallet::GetBudgetSystemCollateralTX(), CCoinsViewErrorCatcher::GetCoin(), CActiveDeterministicMasternodeManager::GetLocalAddress(), CWallet::GetMasternodeOutpointAndKeys(), CMasternodeMan::GetMasternodeRank(), CMasternodeMan::GetMasternodeRanks(), CMasternodePayments::GetMasternodeTxOuts(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), CWallet::GetOutpointAndKeysFromOutput(), CSuperblockManager::GetSuperblockPayments(), gobject_submit(), dbwrapper_private::HandleError(), http_request_cb(), HTTPBindAddresses(), HTTPReq_JSONRPC(), importelectrumwallet(), importwallet(), CActiveDeterministicMasternodeManager::Init(), InitBlockIndex(), InitHTTPServer(), CWallet::InitLoadWallet(), InitLogging(), InitMessage(), CGovernanceManager::InitOnLoad(), InitParameterInteraction(), InitRPCAuthentication(), InitSignatureCache(), InterruptTorControl(), InvalidChainFound(), IsBlockPayeeValid(), IsBlockValueValid(), CGovernanceObject::IsCollateralValid(), CPrivateSend::IsCollateralValid(), CPrivateSendServer::IsOutputsCompatibleWithSessionDenom(), CSuperblockManager::IsSuperblockTriggered(), CMasternodeBlockPayees::IsTransactionValid(), CMasternodePayments::IsTransactionValid(), CMessageHeader::IsValid(), CMasternodePaymentVote::IsValid(), CSuperblock::IsValid(), CTxLockVote::IsValid(), CPrivateSendClientSession::JoinExistingQueue(), CKeyHolderStorage::KeepAll(), CWallet::KeepKey(), libevent_log_cb(), CFlatDB< T >::Load(), LoadBlockIndexDB(), CWallet::LoadCScript(), CGovernanceObject::LoadData(), LoadExternalBlockFile(), LoadMempool(), CWalletDB::LoadWallet(), LogAcceptCategory(), CPrivateSendClientSession::MakeCollateralAmounts(), CActiveLegacyMasternodeManager::ManageState(), CActiveLegacyMasternodeManager::ManageStateInitial(), CActiveLegacyMasternodeManager::ManageStateRemote(), CGovernanceManager::MasternodeRateCheck(), Misbehaving(), new_handler_terminate(), CWallet::NewKeyPool(), noui_InitMessage(), noui_ThreadSafeMessageBox(), OldDecryptAES256(), OldEncryptAES256(), CDBEnv::Open(), OpenDiskFile(), CWallet::ParameterInteraction(), CSuperblock::ParsePaymentSchedule(), CDeterministicMNList::PoSePunish(), PrepareShutdown(), CMasternodeMan::PrepareVerifyRequest(), PrintExceptionContinue(), CTxMemPool::PrioritiseTransaction(), OverviewPage::privateSendStatus(), CMasternodePayments::ProcessBlock(), CDeterministicMNManager::ProcessBlock(), llmq::CQuorumBlockProcessor::ProcessCommitment(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), ProcessGetData(), CMasternodeMan::ProcessMasternodeConnections(), llmq::CQuorumBlockProcessor::ProcessMessage(), CMasternodeSync::ProcessMessage(), CPrivateSendServer::ProcessMessage(), CMasternodePayments::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), CGovernanceManager::ProcessMessage(), ProcessMessage(), ProcessMessages(), ProcessNewBlock(), CSporkManager::ProcessSpork(), CMasternodeSync::ProcessTick(), CInstantSend::ProcessTxLockRequest(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), CGovernanceObject::ProcessVote(), CGovernanceManager::ProcessVote(), TorController::protocolinfo_cb(), RandAddSeedPerfmon(), RandFailure(), CFlatDB< T >::Read(), CDBWrapper::Read(), TorControlConnection::readcb(), CTxMemPool::ReadFeeEstimates(), TorController::Reconnect(), CWalletDB::Recover(), CPrivateSendServer::RelayStatus(), CWalletTx::RelayWalletTransaction(), CGovernanceObject::RemoveInvalidProposalVotes(), RemoveLocal(), CGovernanceObject::RemoveOldVotes(), CTxMemPool::removeProTxConflicts(), CTxMemPool::removeProTxSpentCollateralConflicts(), ReprocessBlocks(), CMasternodePayments::RequestLowDataPaymentBlocks(), CWallet::ResendWalletTransactions(), CWallet::ReserveKeyFromKeyPool(), CInstantSend::ResolveConflicts(), CKeyHolderStorage::ReturnAll(), CWallet::ReturnKey(), CDB::Rewrite(), runCommand(), CDBEnv::Salvage(), CWallet::ScanForWalletTransactions(), CWallet::SelectPSInOutPairsByDenominations(), SendBlockTransactions(), CPrivateSendClientSession::SendDenominate(), CActiveLegacyMasternodeManager::SendMasternodePing(), SendMessages(), SendRejectsAndCheckIfBanned(), CMasternodeMan::SendVerifyReply(), CSporkManager::SetMinSporkKeys(), CSporkManager::SetPrivKey(), CSporkManager::SetSporkAddress(), CPrivateSendServer::SetState(), CPrivateSendClientSession::SetState(), Shutdown(), CMasternodePing::Sign(), CGovernanceVote::Sign(), CSporkMessage::Sign(), CMasternodePaymentVote::Sign(), CPrivateSendQueue::Sign(), CGovernanceObject::Sign(), CTxLockVote::Sign(), CPrivateSendBroadcastTx::Sign(), CMasternodeBroadcast::Sign(), CPrivateSendClientSession::SignFinalTransaction(), CMasternodePing::SimpleCheck(), CMasternodeBroadcast::SimpleCheck(), CConnman::SocketSendData(), Socks5(), CConnman::Start(), StartHTTPServer(), CPrivateSendClientSession::StartNewQueue(), StartTorControl(), CConnman::Stop(), StopHTTPServer(), CPrivateSendClientSession::SubmitDenominate(), CMasternodeSync::SwitchToNextAsset(), CMasternodePayments::Sync(), CMasternodeMan::SyncAll(), CGovernanceManager::SyncAll(), CMasternodeMan::SyncSingle(), CGovernanceManager::SyncSingleObjAndItsVotes(), CConnman::ThreadDNSAddressSeed(), ThreadImport(), CConnman::ThreadOpenConnections(), ThreadSendAlert(), CConnman::ThreadSocketHandler(), CWallet::TopUpKeyPool(), TorController::TorController(), TraceThread(), CDeterministicMNManager::UndoBlock(), UnlinkPrunedFiles(), CCryptoKeyStore::Unlock(), CWallet::Unlock(), CMasternodeBroadcast::Update(), CGovernanceManager::UpdateCachesAndClean(), CMasternode::UpdateFromNewBroadcast(), CSporkManager::UpdateSpork(), UpdateTip(), CInstantSend::UpdateVotedOutpoints(), CCoinsViewDB::Upgrade(), CWallet::Verify(), CVerifyDB::VerifyDB(), CInstantSend::Vote(), CFlatDB< T >::Write(), CTxMemPool::WriteFeeEstimates(), and HTTPRequest::~HTTPRequest().
Function Documentation
_()
std::string _ (const char * psz) inline
Translation function: Call Translate signal on UI interface, which returns a boost::optional result.
If no translation slot is registered, nothing is returned, and simply return the input.
Definition at line 83 of file util.h.
References CTranslationInterface::Translate, and translationInterface.
Referenced by AddTimeData(), AmountErrMsg(), AmountHighWarn(), AppendParamsHelpMessages(), AppInit(), AppInitMain(), AppInitParameterInteraction(), AppInitRawTx(), AppInitRPC(), AppInitSanityChecks(), AutoBackupWallet(), CConnman::BindListenPort(), CallRPC(), CPrivateSendClientManager::CheckAutomaticBackup(), CheckDiskSpace(), CPrivateSendClientSession::CheckPoolStateUpdate(), CPrivateSendClientManager::CheckTimeout(), compress_big(), compress_small(), CopyrightHolders(), CPrivateSendClientSession::CreateDenominated(), CWallet::CreateTransaction(), CWallet::CreateWalletFromFile(), CVerifyDB::CVerifyDB(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientManager::DoAutomaticDenominating(), dumpwallet(), CCoinsViewErrorCatcher::GetCoin(), CPrivateSend::GetMessageByID(), CPrivateSendClientSession::GetStatus(), CMasternodeSync::GetSyncStatus(), CWallet::GetWalletHelpString(), GetWarnings(), HelpMessage(), HelpMessageCli(), importelectrumwallet(), importwallet(), InitRPCAuthentication(), CPrivateSendClientSession::JoinExistingQueue(), LicenseInfo(), LockDataDirectory(), noui_ThreadSafeMessageBox(), CWallet::ParameterInteraction(), CPrivateSendClientManager::ProcessPendingDsaRequest(), CMasternodeConfig::read(), ResolveErrMsg(), CWallet::ScanForWalletTransactions(), CConnman::Start(), CPrivateSendClientSession::StartNewQueue(), CWallet::TopUpKeyPool(), UpdateTip(), CCoinsViewDB::Upgrade(), CWallet::Verify(), CVerifyDB::VerifyDB(), and CMasternodeMan::WarnMasternodeDaemonUpdates().
AllocateFileRange()
void AllocateFileRange (FILE * file, unsigned int offset, unsigned int length)
this function tries to make a particular range of a file allocated (corresponding to disk space) it is advisory, and the range specified in the arguments will never contain live data
Definition at line 784 of file util.cpp.
Referenced by FindBlockPos(), and FindUndoPos().
ClearDatadirCache()
void ClearDatadirCache ()
Definition at line 627 of file util.cpp.
References csPathCached, LOCK, pathCached, and pathCachedNetSpecific.
Referenced by ReadConfigFile().
CopyrightHolders()
std::string CopyrightHolders (const std::string & strPrefix, unsigned int nStartYear, unsigned int nEndYear)
Definition at line 978 of file util.cpp.
References _(), and strprintf.
Referenced by LicenseInfo(), and SplashScreen::SplashScreen().
CreatePidFile()
void CreatePidFile (const boost::filesystem::path & path, pid_t pid)
Definition at line 691 of file util.cpp.
Referenced by AppInitMain().
error()
template<typename... Args> bool error (const char * fmt, const Args &... args)
Definition at line 121 of file util.h.
References LogPrintStr(), and SafeStringFormat().
Referenced by AcceptBlock(), AcceptBlockHeader(), AcceptToMemoryPoolWorker(), CBasicKeyStore::AddCScript(), AddGenesisBlock(), AutoBackupWallet(), CheckBlockHeader(), CheckIndexAgainstCheckpoint(), CheckSequenceLocks(), CAlert::CheckSignature(), CMasternodePaymentVote::CheckSignature(), CommandLineRPC(), ConnectBlock(), ConnectSocketDirectly(), ConnectTip(), ContextualCheckBlockHeader(), DisconnectBlock(), DisconnectTip(), FindDevNetGenesisBlock(), GetAddressIndex(), GetAddressUnspent(), PaymentRequestPlus::getMerchant(), CNode::GetSendVersion(), GetTimestampIndex(), GetTransaction(), GetUTXOStats(), InitBlockIndex(), JSONRPCError(), JSONRPCReply(), JSONRPCReplyObj(), CBlockTreeDB::LoadBlockIndexGuts(), CDBEnv::Open(), ProcessMessage(), ProcessNewBlock(), CFlatDB< T >::Read(), CAddrDB::Read(), CBanDB::Read(), CBlockTreeDB::ReadAddressIndex(), CBlockTreeDB::ReadAddressUnspentIndex(), ReadBlockFromDisk(), CTxMemPool::ReadFeeEstimates(), RegisterLoad(), CNode::SetAddrLocal(), CNode::SetSendVersion(), Socks5(), TestBlockValidity(), CCoinsViewDB::Upgrade(), CVerifyDB::VerifyDB(), CFlatDB< T >::Write(), CAddrDB::Write(), CBanDB::Write(), and WriteBlockToDisk().
FileCommit()
void FileCommit (FILE * file)
Definition at line 732 of file util.cpp.
Referenced by DumpMempool(), FlushBlockFile(), CAddrDB::Write(), and CBanDB::Write().
ForceRemoveArg()
void ForceRemoveArg (const std::string & strArg)
Definition at line 511 of file util.cpp.
References _mapMultiArgs, cs_args, LOCK, and mapArgs.
Referenced by CWallet::GenerateNewHDChain(), InitParameterInteraction(), and CWallet::ParameterInteraction().
ForceSetArg()
void ForceSetArg (const std::string & strArg, const std::string & strValue)
Definition at line 499 of file util.cpp.
References cs_args, LOCK, and mapArgs.
Referenced by debug(), and InitParameterInteraction().
ForceSetMultiArgs()
void ForceSetMultiArgs (const std::string & strArg, const std::vector< std::string > & values)
Definition at line 505 of file util.cpp.
References _mapMultiArgs, cs_args, and LOCK.
Referenced by debug().
GetArg() [1/2]
std::string GetArg (const std::string & strArg, const std::string & strDefault)
Return string argument or default value.
Parameters
strArg Argument to get (e.g. "-foo")
default (e.g. "1")
Returns
command-line argument or default value
Definition at line 458 of file util.cpp.
References cs_args, LOCK, and mapArgs.
Referenced by AcceptToMemoryPoolWorker(), ActivateBestChainStep(), OptionsModel::addOverriddenOption(), BlockAssembler::addPriorityTxs(), AddTimeData(), AddToCompactExtraTransactions(), CWallet::AddToWallet(), AppInit(), AppInitMain(), AppInitParameterInteraction(), AppInitRPC(), TorController::auth_cb(), CConnman::Ban(), BitcoinApplication::BitcoinApplication(), BitcoinGUI::BitcoinGUI(), BlockAssembler::BlockAssembler(), BlockNotifyCallback(), CallRPC(), CZMQNotificationInterface::Create(), BlockAssembler::CreateNewBlock(), CWallet::CreateTransaction(), CWallet::CreateWalletFromFile(), debug(), CBlockPolicyEstimator::estimateSmartFee(), CBlockPolicyEstimator::estimateSmartPriority(), CDB::Flush(), FlushStateToDisk(), CWallet::GenerateNewHDChain(), GetAuthCookieFile(), GetBackupsDir(), GetDataDir(), GetDevNetName(), GetLangTerritory(), GetListenPort(), GetMasternodeConfigFile(), GetPidFile(), HelpExampleRpc(), HTTPBindAddresses(), OptionsModel::Init(), CKeePassIntegrator::init(), CWallet::InitAutoBackup(), InitHTTPServer(), CWallet::InitLoadWallet(), InitParameterInteraction(), InitRPCAuthentication(), InitSignatureCache(), Intro::Intro(), InvalidateBlock(), LoadMempool(), PaymentServer::LoadRootCAs(), main(), mempoolInfoToJSON(), Misbehaving(), CAlert::Notify(), GUIUtil::openConfigfile(), CWallet::ParameterInteraction(), Intro::pickDataDirectory(), ProcessMessage(), TorController::protocolinfo_cb(), RPCConsole::RPCConsole(), CWallet::SelectCoins(), CAlert::Sign(), StartHTTPServer(), CWallet::TopUpKeyPool(), TorControlThread(), CWallet::Unlock(), CInstantSend::UpdateLockedTransaction(), CTxMemPool::UsedMemoryShare(), CWallet::Verify(), and verifychain().
GetArg() [2/2]
int64_t GetArg (const std::string & strArg, int64_t nDefault)
Return integer argument or default value.
Parameters
strArg Argument to get (e.g. "-foo")
default (e.g. 1)
Returns
command-line argument (0 if invalid number) or default value
Definition at line 466 of file util.cpp.
References atoi64(), cs_args, LOCK, and mapArgs.
GetBackupsDir()
boost::filesystem::path GetBackupsDir ()
Definition at line 617 of file util.cpp.
References GetArg(), GetDataDir(), and IsArgSet().
Referenced by AutoBackupWallet(), and GUIUtil::showBackups().
GetBoolArg()
bool GetBoolArg (const std::string & strArg, bool fDefault)
Return boolean argument or default value.
Parameters
strArg Argument to get (e.g. "-foo")
default (true or false)
Returns
command-line argument or default value
Definition at line 474 of file util.cpp.
References cs_args, InterpretBool(), LOCK, and mapArgs.
Referenced by AcceptToMemoryPoolWorker(), BlockAssembler::AddToBlock(), AppInit(), AppInitBasicSetup(), AppInitMain(), AppInitParameterInteraction(), AppInitRawTx(), AppInitRPC(), AppInitServers(), CDBWrapper::CDBWrapper(), ChainNameFromCommandLine(), CWallet::ChangeWalletPassphrase(), CommandLineRPC(), CWallet::CreateTransaction(), CWallet::CreateWalletFromFile(), CWallet::EncryptWallet(), PaymentRequestPlus::getMerchant(), GetWarnings(), HelpMessage(), HelpMessageDialog::HelpMessageDialog(), CKeePassIntegrator::init(), CWallet::InitAutoBackup(), InitBlockIndex(), InitHTTPServer(), BitcoinApplication::initializeResult(), CWallet::InitLoadWallet(), InitLogging(), InitParameterInteraction(), WalletModel::isWalletEnabled(), main(), OnRPCPreCommand(), CDBEnv::Open(), OutputTx(), CWallet::ParameterInteraction(), Intro::pickDataDirectory(), ProcessMessage(), RegisterWalletRPCCommands(), CWallet::SelectCoins(), SplashScreen::SplashScreen(), CConnman::Start(), CConnman::ThreadDNSAddressSeed(), ThreadFlushWalletDB(), ThreadImport(), CWallet::Unlock(), and CWallet::Verify().
GetConfigFile()
boost::filesystem::path GetConfigFile (const std::string & confPath)
Definition at line 635 of file util.cpp.
References GetDataDir().
Referenced by AppInitMain(), CallRPC(), GUIUtil::openConfigfile(), and ReadConfigFile().
GetDataDir()
const boost::filesystem::path& GetDataDir (bool fNetSpecific = true)
Definition at line 587 of file util.cpp.
References BaseParams(), csPathCached, CBaseChainParams::DataDir(), GetArg(), GetDefaultDataDir(), IsArgSet(), LOCK, pathCached, and pathCachedNetSpecific.
Referenced by AppInit(), AppInitMain(), AppInitRPC(), AutoBackupWallet(), CWallet::BackupWallet(), CAddrDB::CAddrDB(), CBanDB::CBanDB(), CDB::CDB(), CFlatDB< T >::CFlatDB(), CheckDiskSpace(), CleanupBlockRevFiles(), ClientModel::dataDir(), DumpMempool(), GetAuthCookieFile(), GetBackupsDir(), GetBlockPosFilename(), GetConfigFile(), GetMasternodeConfigFile(), GetPidFile(), TorController::GetPrivateKeyFile(), ipcServerName(), LoadMempool(), LockDataDirectory(), LogPrintStr(), main(), OpenDebugLog(), GUIUtil::openDebugLogfile(), PrepareShutdown(), RPCConsole::RPCConsole(), ShrinkDebugFile(), ThreadImport(), CWallet::Verify(), CAddrDB::Write(), and CBanDB::Write().
GetDefaultDataDir()
boost::filesystem::path GetDefaultDataDir ()
Definition at line 556 of file util.cpp.
Referenced by AppInitMain(), GetDataDir(), and Intro::getDefaultDataDirectory().
GetMasternodeConfigFile()
boost::filesystem::path GetMasternodeConfigFile ()
Definition at line 644 of file util.cpp.
References GetArg(), and GetDataDir().
Referenced by AppInitMain(), GUIUtil::openMNConfigfile(), and CMasternodeConfig::read().
GetNumCores()
int GetNumCores ()
Return the number of physical cores available on the current system.
Note
This does not count virtual cores, such as those provided by HyperThreading when boost is newer than 1.56.
Definition at line 969 of file util.cpp.
Referenced by AppInitParameterInteraction(), CCheckQueueSpeed(), CCheckQueueSpeedPrevectorJob(), HelpMessage(), and OptionsDialog::OptionsDialog().
GetPidFile()
boost::filesystem::path GetPidFile ()
Definition at line 684 of file util.cpp.
References BITCOIN_PID_FILENAME, GetArg(), and GetDataDir().
Referenced by AppInitMain(), and PrepareShutdown().
GetThreadName()
std::string GetThreadName ()
Definition at line 894 of file util.cpp.
References name.
Referenced by LogAcceptCategory(), and LogThreadNameStr().
HelpMessageGroup()
std::string HelpMessageGroup (const std::string & message)
Format a string to be used as group of options in help messages.
Parameters
message Group name (e.g. "RPC server options:")
Returns
the formatted string
Definition at line 522 of file util.cpp.
Referenced by AppendParamsHelpMessages(), AppInitRawTx(), CWallet::GetWalletHelpString(), HelpMessage(), HelpMessageCli(), and HelpMessageDialog::HelpMessageDialog().
HelpMessageOpt()
std::string HelpMessageOpt (const std::string & option, const std::string & message)
Format a string to be used as option description in help messages.
Parameters
option Option message (e.g. "-rpcuser=<user>")
message Option description (e.g. "Username for JSON-RPC connections")
Returns
the formatted string
Definition at line 526 of file util.cpp.
References FormatParagraph(), msgIndent, optIndent, and screenWidth.
Referenced by AppendParamsHelpMessages(), AppInitRawTx(), CWallet::GetWalletHelpString(), HelpMessage(), HelpMessageCli(), and HelpMessageDialog::HelpMessageDialog().
IntVersionToString()
std::string IntVersionToString (uint32_t nVersion)
Converts version as 4-byte unsigned integer to string.
Parameters
nVersion 4-byte unsigned integer, most significant byte is always 0
Returns
version string in "x.x.x" format (last 3 bytes as version parts) Throws std::bad_cast if format doesn match.
Definition at line 1009 of file util.cpp.
Referenced by SafeIntVersionToString().
IsArgSet()
bool IsArgSet (const std::string & strArg)
Return true if the given argument has been manually set.
Parameters
strArg Argument to get (e.g. "-foo")
Returns
true if the argument has been set
Definition at line 452 of file util.cpp.
References cs_args, LOCK, and mapArgs.
Referenced by AppInit(), AppInitMain(), AppInitParameterInteraction(), AppInitRawTx(), AppInitRPC(), BlockAssembler::BlockAssembler(), ChainNameFromCommandLine(), CMasternodeMan::CheckAndRemove(), CZMQNotificationInterface::Create(), CWallet::CreateWalletFromFile(), CWallet::GenerateNewHDChain(), GetBackupsDir(), GetDataDir(), GetDevNetName(), HTTPBindAddresses(), InitParameterInteraction(), main(), CWallet::ParameterInteraction(), ProcessMessage(), SplashScreen::SplashScreen(), CConnman::ThreadOpenMasternodeConnections(), and ThreadSendAlert().
IsSwitchChar()
bool IsSwitchChar (char c) inline
Definition at line 153 of file util.h.
Referenced by AppInit(), CommandLineRawTx(), and CommandLineRPC().
LogAcceptCategory()
bool LogAcceptCategory (const char * category)
Return true if log accepts specified category.
Definition at line 253 of file util.cpp.
References fDebug, GetThreadName(), LogPrintf, and mapMultiArgs.
Referenced by InitHTTPServer(), CBitcoinLevelDBLogger::Logv(), and CWallet::SelectCoinsGroupedByAddresses().
LogPrintStr()
int LogPrintStr (const std::string & str)
Send a string to the log output.
Definition at line 352 of file util.cpp.
References DebugPrintInit(), debugPrintInitFlag, fileout, FileWriteStr(), fPrintToConsole, fPrintToDebugLog, fReopenDebugLog(), GetDataDir(), LogThreadNameStr(), LogTimestampStr(), mutexDebugLog, and vMsgsBeforeOpenLog.
Referenced by error(), and CBitcoinLevelDBLogger::Logv().
OpenDebugLog()
void OpenDebugLog ()
Definition at line 231 of file util.cpp.
References DebugPrintInit(), debugPrintInitFlag, fileout, FileWriteStr(), GetDataDir(), mutexDebugLog, and vMsgsBeforeOpenLog.
Referenced by AppInitMain().
ParseParameters()
void ParseParameters (int argc, const char *const argv[])
Definition at line 416 of file util.cpp.
References _mapMultiArgs, cs_args, InterpretNegativeSetting(), LOCK, and mapArgs.
Referenced by AppInit(), AppInitRawTx(), AppInitRPC(), and main().
PrintExceptionContinue()
void PrintExceptionContinue (const std::exception * pex, const char * pszThread)
Definition at line 549 of file util.cpp.
References FormatException(), and LogPrintf.
Referenced by AppInit(), CommandLineRawTx(), CommandLineRPC(), BitcoinCore::handleRunawayException(), main(), ProcessMessages(), and TraceThread().
RaiseFileDescriptorLimit()
int RaiseFileDescriptorLimit (int nMinFD)
this function tries to raise the file descriptor limit to the requested number.
It returns the actual file descriptor limit (which may be more or less than nMinFD)
Definition at line 761 of file util.cpp.
Referenced by AppInitParameterInteraction().
ReadConfigFile()
void ReadConfigFile (const std::string & confPath)
Definition at line 652 of file util.cpp.
References _mapMultiArgs, ClearDatadirCache(), cs_args, GetConfigFile(), InterpretNegativeSetting(), LOCK, and mapArgs.
Referenced by AppInit(), AppInitRPC(), and main().
RenameOver()
bool RenameOver (boost::filesystem::path src, boost::filesystem::path dest)
Definition at line 702 of file util.cpp.
Referenced by DumpMempool(), ThreadImport(), CAddrDB::Write(), and CBanDB::Write().
RenameThread()
void RenameThread (const char * name)
Definition at line 878 of file util.cpp.
References name.
Referenced by HTTPWorkQueueRun(), PrepareShutdown(), RenameThreadPool(), ThreadFlushWalletDB(), ThreadHTTP(), ThreadImport(), ThreadScriptCheck(), and TraceThread().
RenameThreadPool()
void RenameThreadPool (ctpl::thread_pool & tp, const char * baseName)
Definition at line 909 of file util.cpp.
References MilliSleep(), ctpl::thread_pool::push(), RenameThread(), ctpl::thread_pool::size(), and strprintf.
Referenced by CBLSWorker::CBLSWorker().
runCommand()
void runCommand (const std::string & strCommand)
Definition at line 871 of file util.cpp.
References LogPrintf.
Referenced by CWallet::AddToWallet(), BlockNotifyCallback(), CAlert::Notify(), and CInstantSend::UpdateLockedTransaction().
SafeIntVersionToString()
std::string SafeIntVersionToString (uint32_t nVersion)
Copy of the IntVersionToString, that returns "Invalid version" string instead of throwing std::bad_cast.
Parameters
nVersion 4-byte unsigned integer, most significant byte is always 0
Returns
version string in "x.x.x" format (last 3 bytes as version parts) or "Invalid version" if can't cast the given value
Definition at line 1025 of file util.cpp.
References IntVersionToString().
Referenced by CMasternodePing::GetSentinelString(), and MasternodeList::ShowQRCode().
SafeStringFormat()
template<typename... Args> std::string SafeStringFormat (const std::string & fmt, const Args &... args)
Formats a string without throwing exceptions.
Instead, it'll return an error string instead of formatted string.
Definition at line 99 of file util.h.
References tinyformat::format().
Referenced by error().
SetupEnvironment()
void SetupEnvironment ()
Definition at line 928 of file util.cpp.
Referenced by main().
SetupNetworking()
bool SetupNetworking ()
Definition at line 957 of file util.cpp.
Referenced by AppInitBasicSetup(), and main().
ShrinkDebugFile()
void ShrinkDebugFile ()
Definition at line 826 of file util.cpp.
References GetDataDir().
Referenced by AppInitMain().
SoftSetArg()
bool SoftSetArg (const std::string & strArg, const std::string & strValue)
Set an argument if it doesn't already have a value.
Parameters
strArg Argument to set (e.g. "-foo")
strValue Value (e.g. "1")
Returns
true if argument gets set, false if it already had a value
Definition at line 482 of file util.cpp.
References cs_args, LOCK, and mapArgs.
Referenced by OptionsModel::Init(), Intro::pickDataDirectory(), and SoftSetBoolArg().
SoftSetBoolArg()
bool SoftSetBoolArg (const std::string & strArg, bool fValue)
Set a boolean argument if it doesn't already have a value.
Parameters
strArg Argument to set (e.g. "-foo")
fValue Value (e.g. false)
Returns
true if argument gets set, false if it already had a value
Definition at line 491 of file util.cpp.
References SoftSetArg().
Referenced by AppInit(), OptionsModel::Init(), InitParameterInteraction(), CWalletDB::LoadWallet(), and CWallet::ParameterInteraction().
StringVersionToInt()
uint32_t StringVersionToInt (const std::string & strVersion)
Converts version strings to 4-byte unsigned integer.
Parameters
strVersion version in "x.x.x" format (decimal digits only)
Returns
4-byte unsigned integer, most significant byte is always 0 Throws std::bad_cast if format doesn match.
Definition at line 989 of file util.cpp.
Referenced by sentinelping().
TraceThread()
template<typename Callable > void TraceThread (const char * name, Callable func)
. and a wrapper that just calls func once
Definition at line 255 of file util.h.
References LogPrintf, name, PrintExceptionContinue(), RenameThread(), and strprintf.
Referenced by CConnman::Start(), and StartTorControl().
TruncateFile()
bool TruncateFile (FILE * file, unsigned int length)
Definition at line 749 of file util.cpp.
Referenced by FlushBlockFile().
TryCreateDirectory()
bool TryCreateDirectory (const boost::filesystem::path & p)
Ignores exceptions thrown by Boost's create_directory if the requested directory exists.
Specifically handles case where path p exists, but it wasn't possible for the user to write to the parent directory.
Definition at line 718 of file util.cpp.
Referenced by CDBWrapper::CDBWrapper(), CDBEnv::Open(), and Intro::pickDataDirectory().
Variable Documentation
BITCOIN_CONF_FILENAME
const char* const BITCOIN_CONF_FILENAME
Definition at line 124 of file util.cpp.
Referenced by AppInit(), AppInitMain(), AppInitRPC(), CallRPC(), HelpMessage(), HelpMessageCli(), main(), and GUIUtil::openConfigfile().
BITCOIN_PID_FILENAME
const char* const BITCOIN_PID_FILENAME
Definition at line 125 of file util.cpp.
Referenced by GetPidFile(), and HelpMessage().
DEFAULT_LOGIPS
const bool DEFAULT_LOGIPS = false static
Definition at line 52 of file util.h.
Referenced by HelpMessage(), and InitLogging().
DEFAULT_LOGTHREADNAMES
const bool DEFAULT_LOGTHREADNAMES = false static
Definition at line 54 of file util.h.
Referenced by HelpMessage(), and InitLogging().
DEFAULT_LOGTIMEMICROS
const bool DEFAULT_LOGTIMEMICROS = false static
Definition at line 51 of file util.h.
Referenced by HelpMessage(), and InitLogging().
DEFAULT_LOGTIMESTAMPS
const bool DEFAULT_LOGTIMESTAMPS = true static
Definition at line 53 of file util.h.
Referenced by HelpMessage(), and InitLogging().
fDebug
bool fDebug
Definition at line 131 of file util.cpp.
Referenced by AppInitMain(), AppInitParameterInteraction(), debug(), IsBlockPayeeValid(), IsBlockValueValid(), LogAcceptCategory(), ProcessMessage(), CConnman::SetNetworkActive(), TransactionDesc::toHTML(), and CoinControlDialog::updateView().
fLiteMode
bool fLiteMode
Definition at line 114 of file util.cpp.
Referenced by AppInitMain(), CheckProRegTx(), CheckProUpRegTx(), BitcoinGUI::createActions(), BitcoinGUI::createToolBars(), CPrivateSendServer::DoMaintenance(), CMasternodeMan::DoMaintenance(), CPrivateSendClientManager::DoMaintenance(), CGovernanceManager::DoMaintenance(), CWallet::GetAnonymizableBalance(), CWallet::GetAnonymizedBalance(), CWallet::GetAverageAnonymizedRounds(), CWallet::GetDenominatedBalance(), getinfo(), CWallet::GetNeedsToBeAnonymizedBalance(), CWallet::GetNormalizedAnonymizedBalance(), getwalletinfo(), WalletView::gotoMasternodePage(), IsBlockPayeeValid(), IsBlockValueValid(), OverviewPage::OverviewPage(), PrepareShutdown(), CMasternodePayments::ProcessBlock(), CPrivateSendServer::ProcessMessage(), CInstantSend::ProcessMessage(), CPrivateSendClientSession::ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), CGovernanceManager::ProcessMessage(), CSporkManager::ProcessSpork(), SendCoinsDialog::SendCoinsDialog(), WalletView::setClientModel(), BitcoinGUI::setNumBlocks(), BitcoinGUI::setWalletActionsEnabled(), OverviewPage::setWalletModel(), WalletView::setWalletModel(), OverviewPage::updateAdvancedPSUI(), CDSNotificationInterface::UpdatedBlockTip(), CMasternodeSync::UpdatedBlockTip(), CPrivateSend::UpdatedBlockTip(), CMasternodeMan::UpdateLastPaid(), and WalletView::WalletView().
fLogIPs
bool fLogIPs
Definition at line 138 of file util.cpp.
Referenced by CNode::CNode(), InitLogging(), and ProcessMessage().
fLogThreadNames
bool fLogThreadNames
Definition at line 137 of file util.cpp.
Referenced by InitLogging(), and LogThreadNameStr().
fLogTimeMicros
bool fLogTimeMicros
Definition at line 136 of file util.cpp.
Referenced by InitLogging(), and LogTimestampStr().
fLogTimestamps
bool fLogTimestamps
Definition at line 135 of file util.cpp.
Referenced by AppInitMain(), InitLogging(), and LogTimestampStr().
fMasternodeMode
bool fMasternodeMode
Definition at line 113 of file util.cpp.
Referenced by CConnman::AcceptConnection(), CPrivateSendServer::AddEntry(), CPrivateSendServer::AddUserToExistingSession(), AppInitMain(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CMasternode::Check(), CPrivateSendServer::CheckForCompleteQueue(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), CPrivateSendServer::CheckPool(), CPrivateSendClientSession::CheckPoolStateUpdate(), CPrivateSendServer::CheckTimeout(), CPrivateSendClientSession::CheckTimeout(), CPrivateSendClientManager::CheckTimeout(), CPrivateSendServer::CommitFinalTransaction(), CPrivateSendClientSession::CompletedTransaction(), CPrivateSendServer::CreateNewSession(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientManager::DoAutomaticDenominating(), CPrivateSendServer::DoMaintenance(), CMasternodeMan::DoMaintenance(), CPrivateSendClientManager::DoMaintenance(), getpoolinfo(), CActiveDeterministicMasternodeManager::Init(), CPrivateSendServer::IsAcceptableDSA(), CMasternodePaymentVote::IsValid(), CActiveLegacyMasternodeManager::ManageState(), masternode_status(), OverviewPage::OverviewPage(), PrepareShutdown(), CMasternodePayments::ProcessBlock(), CPrivateSendServer::ProcessMessage(), CPrivateSendClientSession::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), CMasternodeSync::ProcessTick(), CGovernanceManager::RequestGovernanceObjectVotes(), CWallet::SelectCoinsGroupedByAddresses(), CWallet::SelectPrivateCoins(), CPrivateSendClientSession::SendDenominate(), SendMessages(), CMasternodeMan::SendVerifyReply(), CPrivateSendServer::SetState(), CPrivateSendQueue::Sign(), CPrivateSendBroadcastTx::Sign(), CPrivateSendClientSession::SignFinalTransaction(), CMasternodeBroadcast::Update(), CActiveDeterministicMasternodeManager::UpdatedBlockTip(), llmq::CDummyDKG::UpdatedBlockTip(), CMasternodeMan::UpdatedBlockTip(), CPrivateSendClientManager::UpdatedSuccessBlock(), CMasternode::UpdateFromNewBroadcast(), and CInstantSend::Vote().
fPrintToConsole
bool fPrintToConsole
Definition at line 132 of file util.cpp.
Referenced by InitLogging(), and LogPrintStr().
fPrintToDebugLog
bool fPrintToDebugLog
Definition at line 133 of file util.cpp.
Referenced by AppInitMain(), InitLogging(), LogPrintStr(), and main().
fReopenDebugLog
std::atomic<bool> fReopenDebugLog
Referenced by HandleSIGHUP().
mapMultiArgs
const std::map<std::string, std::vector<std::string> >& mapMultiArgs
Definition at line 130 of file util.cpp.
Referenced by AppInitMain(), AppInitParameterInteraction(), HTTPBindAddresses(), InitHTTPAllowList(), InitParameterInteraction(), LogAcceptCategory(), multiUserAuthorized(), CConnman::Start(), CConnman::ThreadOpenAddedConnections(), CConnman::ThreadOpenConnections(), and CConnman::ThreadOpenMasternodeConnections().
nWalletBackups
int nWalletBackups
nWalletBackups: 1..10 - number of automatic backups to keep 0 - disabled by command-line -1 - disabled because of some error during run-time -2 - disabled because wallet was locked and we were not able to replenish keypool
Definition at line 122 of file util.cpp.
Referenced by AutoBackupWallet(), CPrivateSendClientManager::CheckAutomaticBackup(), OverviewPage::DisablePrivateSendCompletely(), CWallet::GetWalletHelpString(), CWallet::InitAutoBackup(), CWallet::KeepKey(), OverviewPage::OverviewPage(), OverviewPage::privateSendStatus(), and CWallet::Unlock().
translationInterface
CTranslationInterface translationInterface
Definition at line 140 of file util.cpp.
Referenced by _(), and main().
Released under the MIT license