Dash Core: src/utilstrencodings.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
utilstrencodings.h File Reference
#include <stdint.h>
#include <string>
#include <vector>
Macros
#define BEGIN(a) ((char*)&(a))
Utilities for converting data from/to strings.
#define END(a) ((char*)&((&(a))[1]))
#define UBEGIN(a) ((unsigned char*)&(a))
#define UEND(a) ((unsigned char*)&((&(a))[1]))
#define ARRAYLEN(array) (sizeof(array)/sizeof((array)[0]))
#define PAIRTYPE(t1, t2) std::pair<t1, t2>
This is needed because the foreach macro can't get over the comma in pair<t1, t2>
Enumerations
enum SafeChars { SAFE_CHARS_DEFAULT, SAFE_CHARS_UA_COMMENT }
Used by SanitizeString()
Functions
std::string SanitizeString (const std::string &str, int rule=SAFE_CHARS_DEFAULT)
Remove unsafe chars.
std::vector< unsigned char > ParseHex (const char *psz)
std::vector< unsigned char > ParseHex (const std::string &str)
signed char HexDigit (char c)
bool IsHex (const std::string &str)
std::vector< unsigned char > DecodeBase64 (const char *p, bool *pfInvalid=NULL)
std::string DecodeBase64 (const std::string &str)
std::string EncodeBase64 (const unsigned char *pch, size_t len)
std::string EncodeBase64 (const std::string &str)
std::vector< unsigned char > DecodeBase32 (const char *p, bool *pfInvalid=NULL)
std::string DecodeBase32 (const std::string &str)
std::string EncodeBase32 (const unsigned char *pch, size_t len)
std::string EncodeBase32 (const std::string &str)
std::string i64tostr (int64_t n)
std::string itostr (int n)
int64_t atoi64 (const char *psz)
int64_t atoi64 (const std::string &str)
int atoi (const std::string &str)
bool ParseInt32 (const std::string &str, int32_t *out)
Convert string to signed 32-bit integer with strict parse error feedback.
bool ParseInt64 (const std::string &str, int64_t *out)
Convert string to signed 64-bit integer with strict parse error feedback.
bool ParseUInt32 (const std::string &str, uint32_t *out)
Convert decimal string to unsigned 32-bit integer with strict parse error feedback.
bool ParseUInt64 (const std::string &str, uint64_t *out)
Convert decimal string to unsigned 64-bit integer with strict parse error feedback.
bool ParseDouble (const std::string &str, double *out)
Convert string to double with strict parse error feedback.
template<typename T >
std::string HexStr (const T itbegin, const T itend, bool fSpaces=false)
template<typename T >
std::string HexStr (const T &vch, bool fSpaces=false)
std::string FormatParagraph (const std::string &in, size_t width=79, size_t indent=0)
Format a paragraph of text to a fixed width, adding spaces for indentation to any added line.
template<typename T >
bool TimingResistantEqual (const T &a, const T &b)
Timing-attack-resistant comparison.
bool ParseFixedPoint (const std::string &val, int decimals, int64_t *amount_out)
Parse number as fixed point according to JSON number syntax.
Macro Definition Documentation
ARRAYLEN
#define ARRAYLEN (array) (sizeof(array)/sizeof((array)[0]))
Definition at line 20 of file utilstrencodings.h.
Referenced by AvailableDataFormatsString(), CInv::CInv(), CMainParams::CMainParams(), CTestNetParams::CTestNetParams(), CInv::IsKnownType(), ParseDataFormat(), RegisterBlockchainRPCCommands(), RegisterEvoRPCCommands(), RegisterGovernanceRPCCommands(), RegisterMasternodeRPCCommands(), RegisterMiningRPCCommands(), RegisterMiscRPCCommands(), RegisterNetRPCCommands(), RegisterRawTransactionRPCCommands(), RegisterWalletRPCCommands(), StartREST(), and StopREST().
BEGIN
#define BEGIN (a) ((char*)&(a))
Utilities for converting data from/to strings.
Definition at line 16 of file utilstrencodings.h.
Referenced by CPartialMerkleTree::CalcHash(), ComputeMerkleRootFromBranch(), and CPartialMerkleTree::TraverseAndExtract().
END
#define END (a) ((char*)&((&(a))[1]))
Definition at line 17 of file utilstrencodings.h.
Referenced by CPartialMerkleTree::CalcHash(), ComputeMerkleRootFromBranch(), and CPartialMerkleTree::TraverseAndExtract().
PAIRTYPE
#define PAIRTYPE (t1, t2) std::pair<t1, t2>
This is needed because the foreach macro can't get over the comma in pair<t1, t2>
Definition at line 23 of file utilstrencodings.h.
Referenced by AutoBackupWallet(), CleanupBlockRevFiles(), CWallet::DelAddressBook(), CWallet::GetAccountAddresses(), CWallet::GetAddressBalances(), getaddressesbyaccount(), CWallet::GetAddressGroupings(), getchaintips(), getnetworkinfo(), CRPCTable::help(), listaccounts(), ListReceived(), LoadBlockIndexDB(), WalletModel::loadReceiveRequests(), CWallet::MarkDirty(), ProcessMessage(), PaymentServer::processPaymentRequest(), CWallet::ReacceptWalletTransactions(), AddressTablePriv::refreshAddressTable(), CWallet::ResendWalletTransactionsBefore(), Solver(), TransactionDesc::toHTML(), CoinControlDialog::updateView(), and WalletTxToJSON().
UBEGIN
#define UBEGIN (a) ((unsigned char*)&(a))
Definition at line 18 of file utilstrencodings.h.
UEND
#define UEND (a) ((unsigned char*)&((&(a))[1]))
Definition at line 19 of file utilstrencodings.h.
Enumeration Type Documentation
SafeChars
enum SafeChars
Used by SanitizeString()
Enumerator
SAFE_CHARS_DEFAULT
The full set of allowed chars.
SAFE_CHARS_UA_COMMENT
BIP-0014 subset.
Definition at line 26 of file utilstrencodings.h.
Function Documentation
atoi()
int atoi (const std::string & str)
Definition at line 579 of file utilstrencodings.cpp.
References atoi().
Referenced by AppInitMain(), atoi(), CleanupBlockRevFiles(), CWallet::GetMasternodeOutpointAndKeys(), gobject_getcurrentvotes(), gobject_submit(), int_atoi(), InterpretBool(), masternode_list_conf(), masternode_winners(), MutateTxAddInput(), MutateTxDelInput(), MutateTxDelOutput(), MutateTxSign(), TorControlConnection::readcb(), RPCConsole::RPCParseCommandLine(), and MasternodeList::ShowQRCode().
atoi64() [1/2]
int64_t atoi64 (const char * psz)
Definition at line 561 of file utilstrencodings.cpp.
Referenced by GetArg(), getblocktemplate(), gobject_submit(), MutateTxLocktime(), MutateTxVersion(), ParseMoney(), ParseScript(), ReadOrderPos(), and CWalletTx::SerializationOp().
atoi64() [2/2]
int64_t atoi64 (const std::string & str)
Definition at line 570 of file utilstrencodings.cpp.
DecodeBase32() [1/2]
std::vector<unsigned char> DecodeBase32 (const char * p, bool * pfInvalid = NULL)
Definition at line 297 of file utilstrencodings.cpp.
Referenced by DecodeBase32(), and CNetAddr::SetSpecial().
DecodeBase32() [2/2]
std::string DecodeBase32 (const std::string & str)
Definition at line 414 of file utilstrencodings.cpp.
References DecodeBase32().
DecodeBase64() [1/2]
std::vector<unsigned char> DecodeBase64 (const char * p, bool * pfInvalid = NULL)
Definition at line 144 of file utilstrencodings.cpp.
Referenced by DecodeBase64(), CKeePassIntegrator::CKeePassResponse::decrypt(), SignVerifyMessageDialog::on_verifyMessageButton_VM_clicked(), CKeePassIntegrator::CKeePassResponse::parseResponse(), RPCAuthorized(), verifymessage(), and voteraw().
DecodeBase64() [2/2]
std::string DecodeBase64 (const std::string & str)
Definition at line 227 of file utilstrencodings.cpp.
References DecodeBase64().
EncodeBase32() [1/2]
std::string EncodeBase32 (const unsigned char * pch, size_t len)
Definition at line 233 of file utilstrencodings.cpp.
Referenced by EncodeBase32(), and CNetAddr::ToStringIP().
EncodeBase32() [2/2]
std::string EncodeBase32 (const std::string & str)
Definition at line 292 of file utilstrencodings.cpp.
References EncodeBase32().
EncodeBase64() [1/2]
std::string EncodeBase64 (const unsigned char * pch, size_t len)
Definition at line 93 of file utilstrencodings.cpp.
Referenced by CKeePassIntegrator::CKeePassRequest::addStrParameter(), CallRPC(), EncodeBase64(), masternodebroadcast(), SignVerifyMessageDialog::on_signMessageButton_SM_clicked(), signmessage(), signmessagewithprivkey(), and CHashSigner::VerifyHash().
EncodeBase64() [2/2]
std::string EncodeBase64 (const std::string & str)
Definition at line 139 of file utilstrencodings.cpp.
References EncodeBase64().
FormatParagraph()
std::string FormatParagraph (const std::string & in, size_t width = 79, size_t indent = 0)
Format a paragraph of text to a fixed width, adding spaces for indentation to any added line.
Definition at line 510 of file utilstrencodings.cpp.
Referenced by AppInit(), and HelpMessageOpt().
HexDigit()
signed char HexDigit (char c)
Definition at line 52 of file utilstrencodings.cpp.
References p_util_hexdigit.
Referenced by IsHex(), ParseHex(), and base_blob< 512 >::SetHex().
HexStr() [1/2]
template<typename T > std::string HexStr (const T itbegin, const T itend, bool fSpaces = false)
Definition at line 95 of file utilstrencodings.h.
References immer::detail::T.
Referenced by TorController::authchallenge_cb(), BOOST_FIXTURE_TEST_CASE(), CDBWrapper::CDBWrapper(), createmultisig(), CHDChain::Debug(), dumphdinfo(), dumpwallet(), EncodeDumpString(), EncodeHexTx(), CWallet::EncryptWallet(), FormatScript(), GenerateAuthCookie(), getaddressutxos(), getblock(), getblockheader(), getblockheaders(), getblocktemplate(), CGovernanceObject::GetDataAsHexString(), gettxoutproof(), HexStr(), listunspent(), CProRegTx::MakeSignString(), masternodebroadcast(), masternodelist(), multiUserAuthorized(), ProcessMessages(), TorController::protocolinfo_cb(), rest_block(), rest_getutxos(), rest_headers(), rest_tx(), ScriptPubKeyToJSON(), ScriptPubKeyToUniv(), ScriptToAsmStr(), TestAES256CBC(), TestCrypter::TestDecrypt(), TestCrypter::TestPassphraseSingle(), ThreadSendAlert(), CSimplifiedMNListDiff::ToJson(), CTxIn::ToString(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::ToString(), CTxOut::ToString(), TxInErrorToJSON(), TxToJSON(), TxToUniv(), and validateaddress().
HexStr() [2/2]
template<typename T > std::string HexStr (const T & vch, bool fSpaces = false) inline
Definition at line 114 of file utilstrencodings.h.
References HexStr().
i64tostr()
std::string i64tostr (int64_t n)
Definition at line 551 of file utilstrencodings.cpp.
References strprintf.
Referenced by getblocktemplate(), and WriteOrderPos().
IsHex()
bool IsHex (const std::string & str)
Definition at line 57 of file utilstrencodings.cpp.
References HexDigit().
Referenced by _createmultisig_redeemScript(), DecodeHexBlk(), DecodeHexTx(), DecodeHexVecMnb(), CWallet::GenerateNewHDChain(), gettxoutproof(), importaddress(), importpubkey(), InitParameterInteraction(), lockunspent(), MutateTxAddInput(), MutateTxAddOutData(), ParseHashStr(), ParseHashV(), ParseHexUV(), ParseHexV(), ParseScript(), ProcessImport(), and rest_getutxos().
itostr()
std::string itostr (int n)
Definition at line 556 of file utilstrencodings.cpp.
References strprintf.
Referenced by gobject_vote_alias(), gobject_vote_many(), InitParameterInteraction(), keypoolrefill(), ParseBoolV(), ProcessMessage(), CKeePassIntegrator::rpcAssociate(), CKeePassIntegrator::rpcGetLogins(), CKeePassIntegrator::rpcSetLogin(), strings_1_itostr(), and strings_2_multi_itostr().
ParseDouble()
bool ParseDouble (const std::string & str, double * out)
Convert string to double with strict parse error feedback.
Returns
true if the entire string could be parsed as valid double, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 496 of file utilstrencodings.cpp.
References ParsePrechecks().
Referenced by UniValue::get_real(), and ParseDoubleV().
ParseFixedPoint()
bool ParseFixedPoint (const std::string & val, int decimals, int64_t * amount_out)
Parse number as fixed point according to JSON number syntax.
See http://json.org/number.gif
Returns
true on success, false on error.
Note
The result must be in the range (-10^18,10^18), otherwise an overflow error will trigger.
Definition at line 611 of file utilstrencodings.cpp.
References ProcessMantissaDigit(), and UPPER_BOUND.
Referenced by AmountFromValue(), and ParsePaymentAmount().
ParseHex() [1/2]
std::vector<unsigned char> ParseHex (const char * psz)
Definition at line 67 of file utilstrencodings.cpp.
References HexDigit().
Referenced by _createmultisig_redeemScript(), AppInitMain(), TorController::authchallenge_cb(), BOOST_AUTO_TEST_CASE(), CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CreateGenesisBlock(), CTestNetParams::CTestNetParams(), DecodeHexBlk(), DecodeHexTx(), DecodeHexVecMnb(), CWallet::GenerateNewHDChain(), gobject_deserialize(), importaddress(), importpubkey(), MutateTxAddOutData(), MutateTxAddOutMultiSig(), MutateTxAddOutPubKey(), ParseBLSPubKey(), ParseBLSSecretKey(), ParseHex(), ParseHexUV(), ParseHexV(), ParseScript(), CProposalValidator::ParseStrHexData(), ProcessImport(), rest_getutxos(), CDBEnv::Salvage(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetHexStr(), and TestAES256CBC().
ParseHex() [2/2]
std::vector<unsigned char> ParseHex (const std::string & str)
Definition at line 88 of file utilstrencodings.cpp.
References ParseHex().
ParseInt32()
bool ParseInt32 (const std::string & str, int32_t * out)
Convert string to signed 32-bit integer with strict parse error feedback.
Returns
true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 431 of file utilstrencodings.cpp.
References ParsePrechecks().
Referenced by AppInitParameterInteraction(), UniValue::get_int(), gobject_vote_many(), LookupSubNet(), ParseInt32V(), rest_getutxos(), SplitHostPort(), MasternodeList::StartAll(), MasternodeList::updateMyNodeList(), and VoteWithMasternodeList().
ParseInt64()
bool ParseInt64 (const std::string & str, int64_t * out)
Convert string to signed 64-bit integer with strict parse error feedback.
Returns
true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 447 of file utilstrencodings.cpp.
References ParsePrechecks().
Referenced by AppInitParameterInteraction(), UniValue::get_int64(), and ParseInt64V().
ParseUInt32()
bool ParseUInt32 (const std::string & str, uint32_t * out)
Convert decimal string to unsigned 32-bit integer with strict parse error feedback.
Returns
true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 462 of file utilstrencodings.cpp.
References ParsePrechecks().
ParseUInt64()
bool ParseUInt64 (const std::string & str, uint64_t * out)
Convert decimal string to unsigned 64-bit integer with strict parse error feedback.
Returns
true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 479 of file utilstrencodings.cpp.
References ParsePrechecks().
SanitizeString()
std::string SanitizeString (const std::string & str, int rule = SAFE_CHARS_DEFAULT)
Remove unsafe chars.
Safe chars chosen to allow simple messages/URLs/email addresses, but avoid anything even possibly remotely dangerous like & or >
Parameters
[in] str The string to sanitize
[in] rule The set of safe chars to choose (default: least restrictive)
Returns
A new string without unsafe chars
Definition at line 23 of file utilstrencodings.cpp.
References SAFE_CHARS.
Referenced by AppInitMain(), CAlert::Notify(), JSONRPCRequest::parse(), ProcessMessage(), ProcessMessages(), and CConnman::PushMessage().
TimingResistantEqual()
template<typename T > bool TimingResistantEqual (const T & a, const T & b)
Timing-attack-resistant comparison.
Takes time proportional to length of first argument.
Definition at line 131 of file utilstrencodings.h.
Referenced by multiUserAuthorized(), and RPCAuthorized().
Released under the MIT license