Dash Core: src/validation.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
validation.cpp File Reference
#include "validation.h"
#include "alert.h"
#include "arith_uint256.h"
#include "blockencodings.h"
#include "chainparams.h"
#include "checkpoints.h"
#include "checkqueue.h"
#include "consensus/consensus.h"
#include "consensus/merkle.h"
#include "consensus/validation.h"
#include "hash.h"
#include "init.h"
#include "policy/policy.h"
#include "pow.h"
#include "primitives/block.h"
#include "primitives/transaction.h"
#include "script/script.h"
#include "script/sigcache.h"
#include "script/standard.h"
#include "timedata.h"
#include "tinyformat.h"
#include "txdb.h"
#include "txmempool.h"
#include "ui_interface.h"
#include "undo.h"
#include "util.h"
#include "spork.h"
#include "utilmoneystr.h"
#include "utilstrencodings.h"
#include "validationinterface.h"
#include "versionbits.h"
#include "warnings.h"
#include "instantx.h"
#include "masternodeman.h"
#include "masternode-payments.h"
#include "evo/specialtx.h"
#include "evo/providertx.h"
#include "evo/deterministicmns.h"
#include "evo/cbtx.h"
#include <atomic>
#include <sstream>
#include <boost/algorithm/string/replace.hpp>
#include <boost/algorithm/string/join.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/math/distributions/poisson.hpp>
#include <boost/thread.hpp>
Classes
class MemPoolConflictRemovalTracker
class WarningBitsConditionChecker
Threshold condition checker that triggers when unknown versionbits are seen on the network.
struct ConnectTrace
Used to track blocks whose transactions were applied to the UTXO state as a part of a single ActivateBestChainStep call.
class CMainCleanup
Namespaces
Consensus
Enumerations
enum FlushStateMode { FLUSH_STATE_NONE, FLUSH_STATE_IF_NEEDED, FLUSH_STATE_PERIODIC, FLUSH_STATE_ALWAYS }
enum DisconnectResult { DISCONNECT_OK, DISCONNECT_UNCLEAN, DISCONNECT_FAILED }
Functions
std::atomic_bool fImporting (false)
std::map< uint256, int64_t > mapRejectedBlocks GUARDED_BY (cs_main)
static void CheckBlockIndex (const Consensus::Params &consensusParams)
CBlockIndex * FindForkInGlobalIndex (const CChain &chain, const CBlockLocator &locator)
Find the last common block between the parameter chain and a locator.
static bool FlushStateToDisk (CValidationState &state, FlushStateMode mode, int nManualPruneHeight)
Update the on-disk chain state.
void FindFilesToPruneManual (std::set< int > &setFilesToPrune, int nManualPruneHeight)
bool IsFinalTx (const CTransaction &tx, int nBlockHeight, int64_t nBlockTime)
Check if transaction is final and can be included in a block with the specified height and time.
bool CheckFinalTx (const CTransaction &tx, int flags)
Check if transaction will be final in the next block to be created.
static std::pair< int, int64_t > CalculateSequenceLocks (const CTransaction &tx, int flags, std::vector< int > *prevHeights, const CBlockIndex &block)
Calculates the block height and previous block's median time past at which the transaction will be considered final in the context of BIP 68.
static bool EvaluateSequenceLocks (const CBlockIndex &block, std::pair< int, int64_t > lockPair)
bool SequenceLocks (const CTransaction &tx, int flags, std::vector< int > *prevHeights, const CBlockIndex &block)
Check if transaction is final per BIP 68 sequence numbers and can be included in a block.
bool TestLockPointValidity (const LockPoints *lp)
Test whether the LockPoints height and time are still valid on the current chain.
bool CheckSequenceLocks (const CTransaction &tx, int flags, LockPoints *lp, bool useExistingLockPoints)
Check if transaction will be BIP 68 final in the next block to be created.
unsigned int GetLegacySigOpCount (const CTransaction &tx)
Count ECDSA signature operations the old-fashioned (pre-0.6) way.
unsigned int GetP2SHSigOpCount (const CTransaction &tx, const CCoinsViewCache &inputs)
Count ECDSA signature operations in pay-to-script-hash inputs.
bool GetUTXOCoin (const COutPoint &outpoint, Coin &coin)
int GetUTXOHeight (const COutPoint &outpoint)
int GetUTXOConfirmations (const COutPoint &outpoint)
bool CheckTransaction (const CTransaction &tx, CValidationState &state)
Transaction validation functions.
bool ContextualCheckTransaction (const CTransaction &tx, CValidationState &state, const Consensus::Params &consensusParams, const CBlockIndex *pindexPrev)
void LimitMempoolSize (CTxMemPool &pool, size_t limit, unsigned long age)
std::string FormatStateMessage (const CValidationState &state)
Convert CValidationState to a human-readable message for logging.
static bool IsCurrentForFeeEstimation ()
bool AcceptToMemoryPoolWorker (CTxMemPool &pool, CValidationState &state, const CTransactionRef &ptx, bool fLimitFree, bool *pfMissingInputs, int64_t nAcceptTime, bool fOverrideMempoolLimit, const CAmount &nAbsurdFee, std::vector< COutPoint > &coins_to_uncache, bool fDryRun)
bool AcceptToMemoryPoolWithTime (CTxMemPool &pool, CValidationState &state, const CTransactionRef &tx, bool fLimitFree, bool *pfMissingInputs, int64_t nAcceptTime, bool fOverrideMempoolLimit, const CAmount nAbsurdFee, bool fDryRun)
(try to) add transaction to memory pool with a specified acceptance time
bool AcceptToMemoryPool (CTxMemPool &pool, CValidationState &state, const CTransactionRef &tx, bool fLimitFree, bool *pfMissingInputs, bool fOverrideMempoolLimit, const CAmount nAbsurdFee, bool fDryRun)
(try to) add transaction to memory pool
bool GetTimestampIndex (const unsigned int &high, const unsigned int &low, std::vector< uint256 > &hashes)
bool GetSpentIndex (CSpentIndexKey &key, CSpentIndexValue &value)
bool GetAddressIndex (uint160 addressHash, int type, std::vector< std::pair< CAddressIndexKey, CAmount > > &addressIndex, int start, int end)
bool GetAddressUnspent (uint160 addressHash, int type, std::vector< std::pair< CAddressUnspentKey, CAddressUnspentValue > > &unspentOutputs)
bool GetTransaction (const uint256 &hash, CTransactionRef &txOut, const Consensus::Params &consensusParams, uint256 &hashBlock, bool fAllowSlow)
Return transaction in txOut, and if it was found inside a block, its hash is placed in hashBlock.
bool WriteBlockToDisk (const CBlock &block, CDiskBlockPos &pos, const CMessageHeader::MessageStartChars &messageStart)
Functions for disk access for blocks.
bool ReadBlockFromDisk (CBlock &block, const CDiskBlockPos &pos, const Consensus::Params &consensusParams)
bool ReadBlockFromDisk (CBlock &block, const CBlockIndex *pindex, const Consensus::Params &consensusParams)
double ConvertBitsToDouble (unsigned int nBits)
CAmount GetBlockSubsidy (int nPrevBits, int nPrevHeight, const Consensus::Params &consensusParams, bool fSuperblockPartOnly)
CAmount GetMasternodePayment (int nHeight, CAmount blockValue)
bool IsInitialBlockDownload ()
Check whether we are doing an initial block download (synchronizing from disk or network)
void CheckForkWarningConditions ()
void CheckForkWarningConditionsOnNewFork (CBlockIndex *pindexNewForkTip)
static void InvalidChainFound (CBlockIndex *pindexNew)
static void InvalidBlockFound (CBlockIndex *pindex, const CValidationState &state)
void UpdateCoins (const CTransaction &tx, CCoinsViewCache &inputs, CTxUndo &txundo, int nHeight)
void UpdateCoins (const CTransaction &tx, CCoinsViewCache &inputs, int nHeight)
Apply the effects of this transaction on the UTXO set represented by view.
int GetSpendHeight (const CCoinsViewCache &inputs)
Return the spend height, which is one more than the inputs.GetBestBlock().
bool Consensus::CheckTxInputs (const CTransaction &tx, CValidationState &state, const CCoinsViewCache &inputs, int nSpendHeight)
Check whether all inputs of this transaction are valid (no double spends and amounts) This does not modify the UTXO set.
bool CheckInputs (const CTransaction &tx, CValidationState &state, const CCoinsViewCache &inputs, bool fScriptChecks, unsigned int flags, bool cacheStore, std::vector< CScriptCheck > *pvChecks)
Check whether all inputs of this transaction are valid (no double spends, scripts & sigs, amounts) This does not modify the UTXO set.
int ApplyTxInUndo (Coin &&undo, CCoinsViewCache &view, const COutPoint &out)
Restore the UTXO in a Coin at a given COutPoint.
static DisconnectResult DisconnectBlock (const CBlock &block, CValidationState &state, const CBlockIndex *pindex, CCoinsViewCache &view)
Undo the effects of this block (with given index) on the UTXO set represented by coins.
static void FlushBlockFile (bool fFinalize=false)
bool FindUndoPos (CValidationState &state, int nFile, CDiskBlockPos &pos, unsigned int nAddSize)
void ThreadScriptCheck ()
Run an instance of the script checking thread.
int32_t ComputeBlockVersion (const CBlockIndex *pindexPrev, const Consensus::Params &params, bool fCheckMasternodesUpgraded)
Determine what nVersion a new block should use.
bool GetBlockHash (uint256 &hashRet, int nBlockHeight)
Return true if hash can be found in chainActive at nBlockHeight height.
static bool ConnectBlock (const CBlock &block, CValidationState &state, CBlockIndex *pindex, CCoinsViewCache &view, const CChainParams &chainparams, bool fJustCheck=false)
Apply the effects of this block (with given index) on the UTXO set represented by coins.
void FlushStateToDisk ()
Flush all state, indexes and buffers to disk.
void PruneAndFlush ()
Prune block files and flush state to disk.
static void UpdateTip (CBlockIndex *pindexNew, const CChainParams &chainParams)
Update chainActive and related internal data structures.
static bool DisconnectTip (CValidationState &state, const CChainParams &chainparams)
Disconnect chainActive's tip.
static bool ConnectTip (CValidationState &state, const CChainParams &chainparams, CBlockIndex *pindexNew, const std::shared_ptr< const CBlock > &pblock, ConnectTrace &connectTrace)
Connect a new block to chainActive.
bool DisconnectBlocks (int blocks)
Functions for validating blocks and updating the block tree.
void ReprocessBlocks (int nBlocks)
static CBlockIndex * FindMostWorkChain ()
Return the tip of the chain with the most work in it, that isn't known to be invalid (it's however far from certain to be valid).
static void PruneBlockIndexCandidates ()
Delete all entries in setBlockIndexCandidates that are worse than the current tip.
static bool ActivateBestChainStep (CValidationState &state, const CChainParams &chainparams, CBlockIndex *pindexMostWork, const std::shared_ptr< const CBlock > &pblock, bool &fInvalidFound, ConnectTrace &connectTrace)
Try to make some progress towards making pindexMostWork the active block.
static void NotifyHeaderTip ()
bool ActivateBestChain (CValidationState &state, const CChainParams &chainparams, std::shared_ptr< const CBlock > pblock)
Make the best chain active, in multiple steps.
bool PreciousBlock (CValidationState &state, const CChainParams &params, CBlockIndex *pindex)
Mark a block as precious and reorganize.
bool InvalidateBlock (CValidationState &state, const CChainParams &chainparams, CBlockIndex *pindex)
Mark a block as invalid.
bool ResetBlockFailureFlags (CBlockIndex *pindex)
Remove invalidity status from a block and its descendants.
CBlockIndex * AddToBlockIndex (const CBlockHeader &block)
bool ReceivedBlockTransactions (const CBlock &block, CValidationState &state, CBlockIndex *pindexNew, const CDiskBlockPos &pos)
Mark a block as having its data received and checked (up to BLOCK_VALID_TRANSACTIONS).
bool FindBlockPos (CValidationState &state, CDiskBlockPos &pos, unsigned int nAddSize, unsigned int nHeight, uint64_t nTime, bool fKnown=false)
bool CheckBlockHeader (const CBlockHeader &block, CValidationState &state, const Consensus::Params &consensusParams, bool fCheckPOW)
Context-independent validity checks.
bool CheckBlock (const CBlock &block, CValidationState &state, const Consensus::Params &consensusParams, bool fCheckPOW, bool fCheckMerkleRoot)
static bool CheckIndexAgainstCheckpoint (const CBlockIndex *pindexPrev, CValidationState &state, const CChainParams &chainparams, const uint256 &hash)
bool ContextualCheckBlockHeader (const CBlockHeader &block, CValidationState &state, const Consensus::Params &consensusParams, const CBlockIndex *pindexPrev, int64_t nAdjustedTime)
Context-dependent validity checks.
bool ContextualCheckBlock (const CBlock &block, CValidationState &state, const Consensus::Params &consensusParams, const CBlockIndex *pindexPrev)
static bool AcceptBlockHeader (const CBlockHeader &block, CValidationState &state, const CChainParams &chainparams, CBlockIndex **ppindex)
bool ProcessNewBlockHeaders (const std::vector< CBlockHeader > &headers, CValidationState &state, const CChainParams &chainparams, const CBlockIndex **ppindex)
Process incoming block headers.
static bool AcceptBlock (const std::shared_ptr< const CBlock > &pblock, CValidationState &state, const CChainParams &chainparams, CBlockIndex **ppindex, bool fRequested, const CDiskBlockPos *dbp, bool *fNewBlock)
Store block on disk.
bool ProcessNewBlock (const CChainParams &chainparams, const std::shared_ptr< const CBlock > pblock, bool fForceProcessing, bool *fNewBlock)
Process an incoming block.
bool TestBlockValidity (CValidationState &state, const CChainParams &chainparams, const CBlock &block, CBlockIndex *pindexPrev, bool fCheckPOW, bool fCheckMerkleRoot)
Check a block is completely valid from start to finish (only works on top of our current best block, with cs_main held)
uint64_t CalculateCurrentUsage ()
BLOCK PRUNING CODE.
void PruneOneBlockFile (const int fileNumber)
Mark one block file as pruned.
void UnlinkPrunedFiles (const std::set< int > &setFilesToPrune)
Actually unlink the specified files.
void PruneBlockFilesManual (int nManualPruneHeight)
Prune block files up to a given height.
void FindFilesToPrune (std::set< int > &setFilesToPrune, uint64_t nPruneAfterHeight)
Prune block and undo files (blk???.dat and undo???.dat) so that the disk space used is less than a user-defined target.
bool CheckDiskSpace (uint64_t nAdditionalBytes)
Check whether enough disk space is available for an incoming block.
FILE * OpenDiskFile (const CDiskBlockPos &pos, const char *prefix, bool fReadOnly)
FILE * OpenBlockFile (const CDiskBlockPos &pos, bool fReadOnly)
Open a block file (blk?????.dat)
FILE * OpenUndoFile (const CDiskBlockPos &pos, bool fReadOnly)
Open an undo file (rev?????.dat)
boost::filesystem::path GetBlockPosFilename (const CDiskBlockPos &pos, const char *prefix)
Translation to a filesystem path.
CBlockIndex * InsertBlockIndex (uint256 hash)
Create a new block index entry for a given block hash.
static bool LoadBlockIndexDB (const CChainParams &chainparams)
void UnloadBlockIndex ()
Unload database information.
bool LoadBlockIndex (const CChainParams &chainparams)
Load the block tree and coins database from disk.
static bool AddGenesisBlock (const CChainParams &chainparams, const CBlock &block, CValidationState &state)
bool InitBlockIndex (const CChainParams &chainparams)
Initialize a new block tree database + block data on disk.
bool LoadExternalBlockFile (const CChainParams &chainparams, FILE *fileIn, CDiskBlockPos *dbp)
Import blocks from an external file.
CBlockFileInfo * GetBlockFileInfo (size_t n)
Get block file info entry for one block file.
ThresholdState VersionBitsTipState (const Consensus::Params &params, Consensus::DeploymentPos pos)
Get the BIP9 state for a given deployment at the current tip.
int VersionBitsTipStateSinceHeight (const Consensus::Params &params, Consensus::DeploymentPos pos)
Get the block height at which the BIP9 deployment switched into the state for the block building on the current tip.
bool LoadMempool (void)
Load the mempool from disk.
void DumpMempool (void)
Dump the mempool to disk.
double GuessVerificationProgress (const ChainTxData &data, CBlockIndex *pindex)
Guess how far we are in the verification process at the given block index.
Variables
CCriticalSection cs_main
Global state.
BlockMap mapBlockIndex
CChain chainActive
The currently-connected chain of blocks (protected by cs_main).
CBlockIndex * pindexBestHeader = NULL
Best header we've seen so far (used for getheaders queries' starting points).
CWaitableCriticalSection csBestBlock
CConditionVariable cvBlockChange
int nScriptCheckThreads = 0
bool fReindex = false
bool fTxIndex = true
bool fAddressIndex = false
bool fTimestampIndex = false
bool fSpentIndex = false
bool fHavePruned = false
Pruning-related variables and constants.
bool fPruneMode = false
True if we're running in -prune mode.
bool fIsBareMultisigStd = DEFAULT_PERMIT_BAREMULTISIG
bool fRequireStandard = true
unsigned int nBytesPerSigOp = DEFAULT_BYTES_PER_SIGOP
bool fCheckBlockIndex = false
bool fCheckpointsEnabled = DEFAULT_CHECKPOINTS_ENABLED
size_t nCoinCacheUsage = 5000 * 300
uint64_t nPruneTarget = 0
Number of MiB of block files that we're trying to stay below.
bool fAlerts = DEFAULT_ALERTS
int64_t nMaxTipAge = DEFAULT_MAX_TIP_AGE
If the tip is older than this (in seconds), the node is considered to be in initial block download.
std::atomic< bool > fDIP0001ActiveAtTip {false}
std::atomic< bool > fDIP0003ActiveAtTip {false}
uint256 hashAssumeValid
Block hash whose ancestors we will assume to have valid scripts without checking them.
CFeeRate minRelayTxFee = CFeeRate(DEFAULT_MIN_RELAY_TX_FEE)
A fee rate smaller than this is considered zero fee (for relaying, mining and transaction creation)
CAmount maxTxFee = DEFAULT_TRANSACTION_MAXFEE
Absolute maximum transaction fee (in duffs) used by wallet and mempool (rejects high fee in sendrawtransaction)
CTxMemPool mempool (::minRelayTxFee)
CScript COINBASE_FLAGS
Constant stuff for coinbase transactions we create:
const std::string strMessageMagic = "DarkCoin Signed Message:\n"
CCoinsViewDB * pcoinsdbview = NULL
Global variable that points to the coins database (protected by cs_main)
CCoinsViewCache * pcoinsTip = NULL
Global variable that points to the active CCoinsView (protected by cs_main)
CBlockTreeDB * pblocktree = NULL
Global variable that points to the active block tree (protected by cs_main)
CBlockIndex * pindexBestForkTip = NULL
CBlockIndex * pindexBestForkBase = NULL
static CCheckQueue< CScriptCheck > scriptcheckqueue (128)
VersionBitsCache versionbitscache
static ThresholdConditionCache warningcache [VERSIONBITS_NUM_BITS]
static int64_t nTimeCheck = 0
static int64_t nTimeForks = 0
static int64_t nTimeVerify = 0
static int64_t nTimePayeeAndSpecial = 0
static int64_t nTimeConnect = 0
static int64_t nTimeIndex = 0
static int64_t nTimeCallbacks = 0
static int64_t nTimeTotal = 0
static int64_t nTimeReadFromDisk = 0
static int64_t nTimeConnectTotal = 0
static int64_t nTimeFlush = 0
static int64_t nTimeChainState = 0
static int64_t nTimePostConnect = 0
static const uint64_t MEMPOOL_DUMP_VERSION = 1
class CMainCleanup instance_of_cmaincleanup
Enumeration Type Documentation
DisconnectResult
enum DisconnectResult
Enumerator
DISCONNECT_OK
DISCONNECT_UNCLEAN
DISCONNECT_FAILED
Definition at line 1577 of file validation.cpp.
FlushStateMode
enum FlushStateMode
Enumerator
FLUSH_STATE_NONE
FLUSH_STATE_IF_NEEDED
FLUSH_STATE_PERIODIC
FLUSH_STATE_ALWAYS
Definition at line 230 of file validation.cpp.
Function Documentation
AcceptBlock()
static bool AcceptBlock (const std::shared_ptr< const CBlock > & pblock, CValidationState & state, const CChainParams & chainparams, CBlockIndex ** ppindex, bool fRequested, const CDiskBlockPos * dbp, bool * fNewBlock) static
Store block on disk.
If dbp is non-NULL, the file is known to already reside on disk
Definition at line 3506 of file validation.cpp.
References AcceptBlockHeader(), AssertLockHeld, BLOCK_FAILED_VALID, BLOCK_HAVE_DATA, chainActive, CheckBlock(), CLIENT_VERSION, ContextualCheckBlock(), CValidationState::CorruptionPossible(), cs_main, error(), FindBlockPos(), FLUSH_STATE_NONE, FlushStateToDisk(), FormatStateMessage(), CBlockHeader::GetBlockTime(), CChainParams::GetConsensus(), GetMainSignals(), GetSerializeSize(), CChain::Height(), IsInitialBlockDownload(), CValidationState::IsInvalid(), CChainParams::MessageStart(), MIN_BLOCKS_TO_KEEP, CBlockIndex::nChainWork, CMainSignals::NewPoWValidBlock, CBlockIndex::nHeight, CBlockIndex::nStatus, CBlockIndex::nTx, CBlockIndex::pprev, ReceivedBlockTransactions(), SER_DISK, CChain::Tip(), and WriteBlockToDisk().
Referenced by LoadExternalBlockFile(), and ProcessNewBlock().
AcceptBlockHeader()
static bool AcceptBlockHeader (const CBlockHeader & block, CValidationState & state, const CChainParams & chainparams, CBlockIndex ** ppindex) static
Definition at line 3432 of file validation.cpp.
References CMainSignals::AcceptedBlockHeader, AddToBlockIndex(), AssertLockHeld, BLOCK_FAILED_MASK, CheckBlockHeader(), CheckBlockIndex(), CheckIndexAgainstCheckpoint(), ContextualCheckBlockHeader(), cs_main, CValidationState::DoS(), error(), fCheckpointsEnabled, FormatStateMessage(), GetAdjustedTime(), CChainParams::GetConsensus(), CBlockHeader::GetHash(), GetMainSignals(), CValidationState::GetRejectReason(), Consensus::Params::hashGenesisBlock, CBlockHeader::hashPrevBlock, CValidationState::Invalid(), mapBlockIndex, CBlockIndex::nStatus, REJECT_INVALID, and base_blob< BITS >::ToString().
Referenced by AcceptBlock(), and ProcessNewBlockHeaders().
AcceptToMemoryPool()
bool AcceptToMemoryPool (CTxMemPool & pool, CValidationState & state, const CTransactionRef & tx, bool fLimitFree, bool * pfMissingInputs, bool fOverrideMempoolLimit, const CAmount nAbsurdFee, bool fDryRun)
(try to) add transaction to memory pool
Definition at line 944 of file validation.cpp.
References AcceptToMemoryPoolWithTime(), and GetTime().
Referenced by CMerkleTx::AcceptToMemoryPool(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CPrivateSendServer::CommitFinalTransaction(), DisconnectTip(), CPrivateSend::IsCollateralValid(), ProcessMessage(), and sendrawtransaction().
AcceptToMemoryPoolWithTime()
bool AcceptToMemoryPoolWithTime (CTxMemPool & pool, CValidationState & state, const CTransactionRef & tx, bool fLimitFree, bool * pfMissingInputs, int64_t nAcceptTime, bool fOverrideMempoolLimit, const CAmount nAbsurdFee, bool fDryRun)
(try to) add transaction to memory pool with a specified acceptance time
Definition at line 927 of file validation.cpp.
References AcceptToMemoryPoolWorker(), FLUSH_STATE_PERIODIC, FlushStateToDisk(), CValidationState::GetDebugMessage(), CValidationState::GetRejectReason(), LogPrint, pcoinsTip, and CCoinsViewCache::Uncache().
Referenced by AcceptToMemoryPool(), and LoadMempool().
AcceptToMemoryPoolWorker()
bool AcceptToMemoryPoolWorker (CTxMemPool & pool, CValidationState & state, const CTransactionRef & ptx, bool fLimitFree, bool * pfMissingInputs, int64_t nAcceptTime, bool fOverrideMempoolLimit, const CAmount & nAbsurdFee, std::vector< COutPoint > & coins_to_uncache, bool fDryRun)
Definition at line 638 of file validation.cpp.
References CCoinsViewCache::AccessCoin(), CTxMemPool::addAddressIndex(), CTxMemPool::addSpentIndex(), CTxMemPool::addUnchecked(), AllowFree(), CTxMemPool::ApplyDeltas(), AreInputsStandard(), AssertLockHeld, CTxMemPool::CalculateMemPoolAncestors(), chainActive, CheckFinalTx(), CheckInputs(), CheckSequenceLocks(), CheckSpecialTx(), CheckTransaction(), ContextualCheckTransaction(), CTxMemPool::cs, cs_main, DEFAULT_ANCESTOR_LIMIT, DEFAULT_ANCESTOR_SIZE_LIMIT, DEFAULT_DESCENDANT_LIMIT, DEFAULT_DESCENDANT_SIZE_LIMIT, DEFAULT_LIMITFREERELAY, DEFAULT_MAX_MEMPOOL_SIZE, DEFAULT_MEMPOOL_EXPIRY, DEFAULT_RELAYPRIORITY, CValidationState::DoS(), indirectmap< K, T >::end(), error(), CTxMemPool::exists(), CTxMemPool::existsProviderTxConflict(), fAddressIndex, indirectmap< K, T >::find(), FormatStateMessage(), fRequireStandard, fSpentIndex, GetArg(), CCoinsViewCache::GetBestBlock(), GetBoolArg(), CFeeRate::GetFee(), CTransaction::GetHash(), GetLegacySigOpCount(), CInstantSend::GetLockedOutPointTxHash(), GetMainSignals(), CTxMemPool::GetMinFee(), GetP2SHSigOpCount(), CCoinsViewCache::GetPriority(), GetTime(), CTxMemPoolEntry::GetTxSize(), CCoinsViewCache::GetValueIn(), CTransaction::GetValueOut(), CTxMemPool::HasNoInputsOf(), CInstantSend::HasTxLockRequest(), CCoinsViewCache::HaveCoin(), CCoinsViewCache::HaveCoinInCache(), CChain::Height(), instantsend, CValidationState::Invalid(), Coin::IsCoinBase(), CTransaction::IsCoinBase(), IsCurrentForFeeEstimation(), IsStandardTx(), CTxLockRequest::IsValid(), LimitMempoolSize(), LOCK, LogPrint, MANDATORY_SCRIPT_VERIFY_FLAGS, CTxMemPool::mapNextTx, MAX_STANDARD_TX_SIGOPS, minRelayTxFee, nBytesPerSigOp, CTransaction::nType, CTransaction::nVersion, Params(), pcoinsTip, CTxIn::prevout, REJECT_ALREADY_KNOWN, REJECT_CONFLICT, REJECT_DUPLICATE, REJECT_HIGHFEE, REJECT_INSUFFICIENTFEE, REJECT_INVALID, REJECT_NONSTANDARD, CCoinsViewBacked::SetBackend(), STANDARD_LOCKTIME_VERIFY_FLAGS, STANDARD_SCRIPT_VERIFY_FLAGS, strprintf, CMainSignals::SYNC_TRANSACTION_NOT_IN_BLOCK, CMainSignals::SyncTransaction, CChain::Tip(), base_blob< BITS >::ToString(), TRANSACTION_QUORUM_COMMITMENT, CTransaction::vin, and CTransaction::vout.
Referenced by AcceptToMemoryPoolWithTime().
ActivateBestChain()
bool ActivateBestChain (CValidationState & state, const CChainParams & chainparams, std::shared_ptr< const CBlock > pblock)
Make the best chain active, in multiple steps.
Find the best known block, and make it the tip of the block chain.
The result is either failure or an activated best chain. pblock is either NULL or a pointer to a block that is already loaded (to avoid loading it again from disk).
Definition at line 2879 of file validation.cpp.
References ActivateBestChainStep(), ConnectTrace::blocksConnected, chainActive, CheckBlockIndex(), cs_main, CChain::FindFork(), FindMostWorkChain(), FLUSH_STATE_PERIODIC, FlushStateToDisk(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), GetMainSignals(), IsInitialBlockDownload(), LOCK, mempool, CClientUIInterface::NotifyBlockTip, ShutdownRequested(), CMainSignals::SyncTransaction, CChain::Tip(), uiInterface, CMainSignals::UpdatedBlockTip, and CBlock::vtx.
Referenced by invalidateblock(), LoadExternalBlockFile(), PreciousBlock(), ProcessGetData(), ProcessMessage(), ProcessNewBlock(), reconsiderblock(), ReprocessBlocks(), and ThreadImport().
ActivateBestChainStep()
static bool ActivateBestChainStep (CValidationState & state, const CChainParams & chainparams, CBlockIndex * pindexMostWork, const std::shared_ptr< const CBlock > & pblock, bool & fInvalidFound, ConnectTrace & connectTrace) static
Try to make some progress towards making pindexMostWork the active block.
pblock is either NULL or a pointer to a CBlock corresponding to pindexMostWork.
Definition at line 2778 of file validation.cpp.
References AssertLockHeld, ConnectTrace::blocksConnected, chainActive, CTxMemPool::check(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), ConnectTip(), CValidationState::CorruptionPossible(), cs_main, DEFAULT_MAX_MEMPOOL_SIZE, DEFAULT_MEMPOOL_EXPIRY, DisconnectTip(), CChain::FindFork(), CBlockIndex::GetAncestor(), GetArg(), InvalidChainFound(), CValidationState::IsInvalid(), LimitMempoolSize(), mempool, CBlockIndex::nChainWork, CBlockIndex::nHeight, pcoinsTip, CBlockIndex::pprev, PruneBlockIndexCandidates(), CTxMemPool::removeForReorg(), STANDARD_LOCKTIME_VERIFY_FLAGS, and CChain::Tip().
Referenced by ActivateBestChain().
AddGenesisBlock()
static bool AddGenesisBlock (const CChainParams & chainparams, const CBlock & block, CValidationState & state) static
Definition at line 4115 of file validation.cpp.
References AddToBlockIndex(), CLIENT_VERSION, error(), FindBlockPos(), CBlockHeader::GetBlockTime(), GetSerializeSize(), CChainParams::MessageStart(), ReceivedBlockTransactions(), SER_DISK, and WriteBlockToDisk().
Referenced by InitBlockIndex().
AddToBlockIndex()
CBlockIndex* AddToBlockIndex (const CBlockHeader & block)
Definition at line 3074 of file validation.cpp.
References BLOCK_VALID_TREE, GetBlockProof(), CBlockHeader::GetHash(), CBlockHeader::hashPrevBlock, mapBlockIndex, CBlockIndex::nChainWork, and pindexBestHeader.
Referenced by AcceptBlockHeader(), and AddGenesisBlock().
ApplyTxInUndo()
int ApplyTxInUndo (Coin && undo, CCoinsViewCache & view, const COutPoint & out)
Restore the UTXO in a Coin at a given COutPoint.
Parameters
undo The Coin to be restored.
view The coins view to which to apply the changes.
out The out point that corresponds to the tx input.
Returns
A DisconnectResult as an int
Definition at line 1591 of file validation.cpp.
References AccessByTxid(), CCoinsViewCache::AddCoin(), DISCONNECT_FAILED, DISCONNECT_OK, DISCONNECT_UNCLEAN, Coin::fCoinBase, COutPoint::hash, CCoinsViewCache::HaveCoin(), Coin::IsSpent(), and Coin::nHeight.
Referenced by DisconnectBlock().
CalculateCurrentUsage()
uint64_t CalculateCurrentUsage ()
BLOCK PRUNING CODE.
Definition at line 3652 of file validation.cpp.
References CBlockFileInfo::nSize, and CBlockFileInfo::nUndoSize.
Referenced by FindFilesToPrune().
CalculateSequenceLocks()
static std::pair<int, int64_t> CalculateSequenceLocks (const CTransaction & tx, int flags, std::vector< int > * prevHeights, const CBlockIndex & block) static
Calculates the block height and previous block's median time past at which the transaction will be considered final in the context of BIP 68.
Also removes from the vector of input heights any entries which did not correspond to sequence locked inputs as they do not affect the calculation.
Definition at line 292 of file validation.cpp.
References flags, CBlockIndex::GetAncestor(), CBlockIndex::GetMedianTimePast(), LOCKTIME_VERIFY_SEQUENCE, CTxIn::nSequence, CTransaction::nVersion, CTxIn::SEQUENCE_LOCKTIME_DISABLE_FLAG, CTxIn::SEQUENCE_LOCKTIME_GRANULARITY, CTxIn::SEQUENCE_LOCKTIME_MASK, CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG, and CTransaction::vin.
Referenced by CheckSequenceLocks(), and SequenceLocks().
CheckBlock()
bool CheckBlock (const CBlock & block, CValidationState & state, const Consensus::Params & consensusParams, bool fCheckPOW, bool fCheckMerkleRoot)
Definition at line 3260 of file validation.cpp.
References BlockMerkleRoot(), CheckBlockHeader(), CheckTransaction(), CValidationState::DoS(), CBlock::fChecked, CValidationState::GetDebugMessage(), GetLegacySigOpCount(), CValidationState::GetRejectCode(), CValidationState::GetRejectReason(), GetSerializeSize(), CBlockHeader::hashMerkleRoot, CValidationState::Invalid(), MaxBlockSigOps(), MaxBlockSize(), PROTOCOL_VERSION, REJECT_INVALID, SER_NETWORK, strprintf, and CBlock::vtx.
Referenced by AcceptBlock(), ConnectBlock(), DeserializeAndCheckBlockTest(), PartiallyDownloadedBlock::FillBlock(), ProcessNewBlock(), TestBlockValidity(), and CVerifyDB::VerifyDB().
CheckBlockHeader()
bool CheckBlockHeader (const CBlockHeader & block, CValidationState & state, const Consensus::Params & consensusParams, bool fCheckPOW)
Context-independent validity checks.
Definition at line 3243 of file validation.cpp.
References CheckProofOfWork(), CValidationState::DoS(), error(), CBlockHeader::GetHash(), Consensus::Params::hashDevnetGenesisBlock, Consensus::Params::hashGenesisBlock, CBlockHeader::hashPrevBlock, base_blob< BITS >::IsNull(), CBlockHeader::nBits, and REJECT_INVALID.
Referenced by AcceptBlockHeader(), and CheckBlock().
CheckBlockIndex()
static void CheckBlockIndex (const Consensus::Params & consensusParams) static
Definition at line 4298 of file validation.cpp.
References BLOCK_FAILED_MASK, BLOCK_FAILED_VALID, BLOCK_HAVE_DATA, BLOCK_HAVE_UNDO, BLOCK_VALID_CHAIN, BLOCK_VALID_MASK, BLOCK_VALID_SCRIPTS, BLOCK_VALID_TRANSACTIONS, BLOCK_VALID_TREE, chainActive, cs_main, fCheckBlockIndex, fHavePruned, CChain::Genesis(), CBlockIndex::GetBlockHash(), Consensus::Params::hashGenesisBlock, CChain::Height(), LOCK, mapBlockIndex, CBlockIndex::nChainTx, CBlockIndex::nChainWork, CBlockIndex::nHeight, CBlockIndex::nSequenceId, CBlockIndex::nStatus, CBlockIndex::nTx, CBlockIndex::pprev, CBlockIndex::pskip, and CChain::Tip().
Referenced by AcceptBlockHeader(), ActivateBestChain(), and ProcessNewBlock().
CheckDiskSpace()
bool CheckDiskSpace (uint64_t nAdditionalBytes)
Check whether enough disk space is available for an incoming block.
Definition at line 3781 of file validation.cpp.
References _(), GetDataDir(), and nMinDiskSpace.
Referenced by AppInitMain(), FindBlockPos(), FindUndoPos(), FlushStateToDisk(), CPrivateSendClientManager::ProcessMessage(), and CPrivateSendClientSession::SendDenominate().
CheckFinalTx()
bool CheckFinalTx (const CTransaction & tx, int flags = -1)
Check if transaction will be final in the next block to be created.
Calls IsFinalTx() with current block height and appropriate block time.
See consensus/consensus.h for flag definitions.
Definition at line 254 of file validation.cpp.
References AssertLockHeld, chainActive, cs_main, flags, GetAdjustedTime(), CBlockIndex::GetMedianTimePast(), CChain::Height(), IsFinalTx(), LOCKTIME_MEDIAN_TIME_PAST, and CChain::Tip().
Referenced by AcceptToMemoryPoolWorker(), CWallet::AvailableCoins(), TransactionDesc::FormatTxStatus(), CWallet::GetAccountBalance(), getbalance(), getreceivedbyaccount(), getreceivedbyaddress(), CWalletTx::IsTrusted(), CTxLockRequest::IsValid(), ListReceived(), CTxMemPool::removeForReorg(), and TransactionRecord::updateStatus().
CheckForkWarningConditions()
void CheckForkWarningConditions ()
Definition at line 1246 of file validation.cpp.
References AssertLockHeld, chainActive, cs_main, GetBlockProof(), GetfLargeWorkForkFound(), CChain::Height(), IsInitialBlockDownload(), LogPrintf, CBlockIndex::nChainWork, CBlockIndex::nHeight, CAlert::Notify(), CBlockIndex::phashBlock, pindexBestForkBase, pindexBestForkTip, SetfLargeWorkForkFound(), SetfLargeWorkInvalidChainFound(), CChain::Tip(), and base_blob< BITS >::ToString().
Referenced by ActivateBestChainStep(), CheckForkWarningConditionsOnNewFork(), and InvalidChainFound().
CheckForkWarningConditionsOnNewFork()
void CheckForkWarningConditionsOnNewFork (CBlockIndex * pindexNewForkTip)
Definition at line 1294 of file validation.cpp.
References AssertLockHeld, chainActive, CheckForkWarningConditions(), cs_main, GetBlockProof(), CChain::Height(), CBlockIndex::nChainWork, CBlockIndex::nHeight, pindexBestForkBase, pindexBestForkTip, CBlockIndex::pprev, and CChain::Tip().
Referenced by ActivateBestChainStep().
CheckIndexAgainstCheckpoint()
static bool CheckIndexAgainstCheckpoint (const CBlockIndex * pindexPrev, CValidationState & state, const CChainParams & chainparams, const uint256 & hash) static
Definition at line 3322 of file validation.cpp.
References CChainParams::Checkpoints(), CValidationState::DoS(), error(), CChainParams::GetConsensus(), Checkpoints::GetLastCheckpoint(), Consensus::Params::hashGenesisBlock, CBlockIndex::nHeight, and CBlockIndex::phashBlock.
Referenced by AcceptBlockHeader(), and TestBlockValidity().
CheckInputs()
bool CheckInputs (const CTransaction & tx, CValidationState & state, const CCoinsViewCache & view, bool fScriptChecks, unsigned int flags, bool cacheStore, std::vector< CScriptCheck > * pvChecks = NULL)
Check whether all inputs of this transaction are valid (no double spends, scripts & sigs, amounts) This does not modify the UTXO set.
If pvChecks is not NULL, script checks are pushed onto it instead of being performed inline.
Definition at line 1435 of file validation.cpp.
References CCoinsViewCache::AccessCoin(), Consensus::CheckTxInputs(), CValidationState::DoS(), flags, CScriptCheck::GetScriptError(), GetSpendHeight(), CValidationState::Invalid(), CTransaction::IsCoinBase(), Coin::IsSpent(), CTxOut::nValue, Coin::out, REJECT_INVALID, REJECT_NONSTANDARD, ScriptErrorString(), CTxOut::scriptPubKey, STANDARD_NOT_MANDATORY_VERIFY_FLAGS, strprintf, CScriptCheck::swap(), and CTransaction::vin.
Referenced by AcceptToMemoryPoolWorker(), and ConnectBlock().
CheckSequenceLocks()
bool CheckSequenceLocks (const CTransaction & tx, int flags, LockPoints * lp = NULL, bool useExistingLockPoints = false)
Check if transaction will be BIP 68 final in the next block to be created.
Simulates calling SequenceLocks() with data from the tip of the current active chain. Optionally stores in LockPoints the resulting height and time calculated and the hash of the block needed for calculation or skips the calculation and uses the LockPoints passed in for evaluation. The LockPoints should not be considered valid if CheckSequenceLocks returns false.
See consensus/consensus.h for flag definitions.
Definition at line 387 of file validation.cpp.
References AssertLockHeld, CalculateSequenceLocks(), chainActive, CTxMemPool::cs, cs_main, error(), EvaluateSequenceLocks(), flags, CBlockIndex::GetAncestor(), CCoinsViewMemPool::GetCoin(), LockPoints::height, LockPoints::maxInputBlock, mempool, MEMPOOL_HEIGHT, Coin::nHeight, CBlockIndex::nHeight, pcoinsTip, CBlockIndex::pprev, CTxIn::prevout, LockPoints::time, CChain::Tip(), and CTransaction::vin.
Referenced by AcceptToMemoryPoolWorker(), and CTxMemPool::removeForReorg().
CheckTransaction()
bool CheckTransaction (const CTransaction & tx, CValidationState & state)
Transaction validation functions.
Context-independent validity checks
Definition at line 515 of file validation.cpp.
References CValidationState::DoS(), GetSerializeSize(), CTransaction::IsCoinBase(), MAX_LEGACY_BLOCK_SIZE, MAX_MONEY, MAX_TX_EXTRA_PAYLOAD, MoneyRange(), CTransaction::nType, PROTOCOL_VERSION, REJECT_INVALID, SER_NETWORK, TRANSACTION_COINBASE, TRANSACTION_QUORUM_COMMITMENT, CTransaction::vExtraPayload, CTransaction::vin, and CTransaction::vout.
Referenced by AcceptToMemoryPoolWorker(), CheckBlock(), and ReadKeyValue().
ComputeBlockVersion()
int32_t ComputeBlockVersion (const CBlockIndex * pindexPrev, const Consensus::Params & params, bool fCheckMasternodesUpgraded)
Determine what nVersion a new block should use.
Definition at line 1824 of file validation.cpp.
References BIP9DeploymentInfo::check_mn_protocol, cs_main, deterministicMNManager, DMN_PROTO_VERSION, CBlockIndex::GetBlockHash(), CMasternodePayments::GetBlockTxOuts(), CDeterministicMNManager::GetListForBlock(), CMasternodeMan::GetMasternodeInfo(), CDeterministicMNList::GetMNPayee(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LOCK, Consensus::MAX_VERSION_BITS_DEPLOYMENTS, mnodeman, mnpayments, CBlockIndex::nHeight, masternode_info_t::nProtocolVersion, THRESHOLD_LOCKED_IN, THRESHOLD_STARTED, VERSIONBITS_TOP_BITS, versionbitscache, VersionBitsDeploymentInfo, VersionBitsMask(), and VersionBitsState().
Referenced by WarningBitsConditionChecker::Condition(), BlockAssembler::CreateNewBlock(), and UpdateTip().
ConnectBlock()
static bool ConnectBlock (const CBlock & block, CValidationState & state, CBlockIndex * pindex, CCoinsViewCache & view, const CChainParams & chainparams, bool fJustCheck = false) static
Apply the effects of this block (with given index) on the UTXO set represented by coins.
Validity checks that depend on the UTXO set are also done; ConnectBlock() can fail if those validity checks fail (among other reasons).
DASH: Check superblock start
END DASH
Definition at line 1921 of file validation.cpp.
References CCoinsViewCache::AccessCoin(), CCheckQueueControl< T >::Add(), AssertLockHeld, prevector< N, T, Size, Diff >::begin(), Consensus::Params::BIP34Hash, Consensus::Params::BIP34Height, Consensus::Params::BIP65Height, Consensus::Params::BIP66Height, BLOCK_HAVE_UNDO, BLOCK_VALID_SCRIPTS, CheckBlock(), CheckInputs(), CLIENT_VERSION, cs_main, Consensus::DEPLOYMENT_BIP147, Consensus::DEPLOYMENT_CSV, Consensus::DEPLOYMENT_DIP0003, Consensus::Params::DIP0001Height, CValidationState::DoS(), prevector< N, T, Size, Diff >::end(), error(), evoDb, fAddressIndex, FindUndoPos(), flags, FormatStateMessage(), fSpentIndex, fTimestampIndex, fTxIndex, CBlockIndex::GetAncestor(), CCoinsViewCache::GetBestBlock(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockPos(), GetBlockProofEquivalentTime(), GetBlockSubsidy(), CBlockIndex::GetBlockTime(), CChainParams::GetConsensus(), CBlockHeader::GetHash(), CTransaction::GetHash(), GetLegacySigOpCount(), CInstantSend::GetLockedOutPointTxHash(), GetMainSignals(), GetP2SHSigOpCount(), GetSerializeSize(), GetSizeOfCompactSize(), GetTime(), GetTimeMicros(), CBlockIndex::GetUndoPos(), CCoinsViewCache::GetValueIn(), CTransaction::GetValueOut(), COutPoint::hash, Hash160(), hashAssumeValid, Consensus::Params::hashGenesisBlock, CCoinsViewCache::HaveCoin(), CCoinsViewCache::HaveInputs(), instantsend, IsBlockPayeeValid(), IsBlockValueValid(), CTransaction::IsCoinBase(), base_blob< BITS >::IsNull(), CDiskBlockPos::IsNull(), CScript::IsPayToPublicKey(), CScript::IsPayToPublicKeyHash(), CScript::IsPayToScriptHash(), CSporkManager::IsSporkActive(), CBlockIndex::IsValid(), LOCK, LOCKTIME_VERIFY_SEQUENCE, LogPrint, LogPrintf, mapBlockIndex, mapRejectedBlocks, MaxBlockSigOps(), CChainParams::MessageStart(), COutPoint::n, CBlockIndex::nBits, CBlockIndex::nChainWork, CBlockIndex::nFile, Coin::nHeight, CBlockIndex::nHeight, Consensus::Params::nMinimumChainWork, CDiskBlockPos::nPos, nScriptCheckThreads, CBlockIndex::nStatus, Consensus::Params::nSuperblockStartBlock, Consensus::Params::nSuperblockStartHash, CBlockIndex::nTime, nTimeCallbacks, nTimeCheck, nTimeConnect, nTimeForks, nTimeIndex, nTimePayeeAndSpecial, nTimeVerify, CDiskTxPos::nTxOffset, CBlockIndex::nUndoPos, CTxOut::nValue, Coin::out, Params(), pblocktree, CBlockIndex::phashBlock, pindexBestHeader, CBlockIndex::pprev, CTxIn::prevout, ProcessSpecialTxsInBlock(), CBlockIndex::RaiseValidity(), REJECT_INVALID, SCRIPT_VERIFY_CHECKLOCKTIMEVERIFY, SCRIPT_VERIFY_CHECKSEQUENCEVERIFY, SCRIPT_VERIFY_DERSIG, SCRIPT_VERIFY_NONE, SCRIPT_VERIFY_NULLDUMMY, SCRIPT_VERIFY_P2SH, scriptcheckqueue, CTxOut::scriptPubKey, SequenceLocks(), SER_DISK, CCoinsViewCache::SetBestBlock(), base_blob< BITS >::SetNull(), SPORK_3_INSTANTSEND_BLOCK_FILTERING, sporkManager, THRESHOLD_ACTIVE, base_blob< BITS >::ToString(), uint256S(), UintToArith256(), CBlockTreeDB::UpdateAddressUnspentIndex(), UpdateCoins(), CMainSignals::UpdatedTransaction, CBlockTreeDB::UpdateSpentIndex(), CEvoDB::VerifyBestBlock(), versionbitscache, VersionBitsState(), CTransaction::vin, CTransaction::vout, CBlock::vtx, CBlockUndo::vtxundo, CCheckQueueControl< T >::Wait(), CBlockTreeDB::WriteAddressIndex(), CEvoDB::WriteBestBlock(), CBlockTreeDB::WriteTimestampIndex(), and CBlockTreeDB::WriteTxIndex().
Referenced by ConnectTip(), TestBlockValidity(), and CVerifyDB::VerifyDB().
ConnectTip()
static bool ConnectTip (CValidationState & state, const CChainParams & chainparams, CBlockIndex * pindexNew, const std::shared_ptr< const CBlock > & pblock, ConnectTrace & connectTrace) static
Connect a new block to chainActive.
pblock is either NULL or a pointer to a CBlock corresponding to pindexNew, to bypass loading it again from disk.
The block is always added to connectTrace (either after loading from disk or by copying pblock) - if that is not intended, care must be taken to remove the last entry in blocksConnected in case of failure.
Definition at line 2608 of file validation.cpp.
References CEvoDB::BeginTransaction(), CMainSignals::BlockChecked, ConnectTrace::blocksConnected, chainActive, ConnectBlock(), error(), evoDb, CCoinsViewCache::Flush(), FLUSH_STATE_IF_NEEDED, FlushStateToDisk(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), GetMainSignals(), GetTimeMicros(), InvalidBlockFound(), CValidationState::IsInvalid(), LogPrint, mempool, CBlockIndex::nHeight, nTimeChainState, nTimeConnectTotal, nTimeFlush, nTimePostConnect, nTimeReadFromDisk, nTimeTotal, pcoinsTip, CBlockIndex::pprev, ReadBlockFromDisk(), CTxMemPool::removeForBlock(), CChain::Tip(), base_blob< BITS >::ToString(), UpdateTip(), and CBlock::vtx.
Referenced by ActivateBestChainStep().
ContextualCheckBlock()
bool ContextualCheckBlock (const CBlock & block, CValidationState & state, const Consensus::Params & consensusParams, const CBlockIndex * pindexPrev)
Definition at line 3372 of file validation.cpp.
References Consensus::Params::BIP34Height, ContextualCheckTransaction(), Consensus::DEPLOYMENT_CSV, Consensus::DEPLOYMENT_DIP0003, Consensus::Params::DIP0001Height, CValidationState::DoS(), expect, CBlockHeader::GetBlockTime(), CChainParams::GetConsensus(), GetLegacySigOpCount(), CBlockIndex::GetMedianTimePast(), GetSerializeSize(), IsFinalTx(), LOCKTIME_MEDIAN_TIME_PAST, MaxBlockSigOps(), MaxBlockSize(), CBlockIndex::nHeight, Params(), PROTOCOL_VERSION, REJECT_INVALID, SER_NETWORK, THRESHOLD_ACTIVE, TRANSACTION_COINBASE, versionbitscache, VersionBitsState(), and CBlock::vtx.
Referenced by AcceptBlock(), and TestBlockValidity().
ContextualCheckBlockHeader()
bool ContextualCheckBlockHeader (const CBlockHeader & block, CValidationState & state, const Consensus::Params & consensusParams, const CBlockIndex * pindexPrev, int64_t nAdjustedTime)
Context-dependent validity checks.
By "context", we mean only the previous block headers, but not the UTXO set; UTXO-related validity checks are done in ConnectBlock().
Definition at line 3336 of file validation.cpp.
References Consensus::Params::BIP34Height, Consensus::Params::BIP65Height, Consensus::Params::BIP66Height, ConvertBitsToDouble(), CValidationState::DoS(), error(), CBlockHeader::GetBlockTime(), CBlockIndex::GetMedianTimePast(), GetNextWorkRequired(), CValidationState::Invalid(), CBaseChainParams::MAIN, CBlockHeader::nBits, CBlockIndex::nHeight, CBlockHeader::nVersion, Params(), REJECT_INVALID, REJECT_OBSOLETE, and strprintf.
Referenced by AcceptBlockHeader(), and TestBlockValidity().
ContextualCheckTransaction()
bool ContextualCheckTransaction (const CTransaction & tx, CValidationState & state, const Consensus::Params & consensusParams, const CBlockIndex * pindexPrev)
Definition at line 574 of file validation.cpp.
References Consensus::DEPLOYMENT_DIP0003, Consensus::Params::DIP0001Height, CValidationState::DoS(), GetSerializeSize(), CTransaction::IsCoinBase(), MAX_STANDARD_TX_SIZE, CBlockIndex::nHeight, CTransaction::nType, CTransaction::nVersion, PROTOCOL_VERSION, REJECT_INVALID, SER_NETWORK, THRESHOLD_ACTIVE, TRANSACTION_COINBASE, TRANSACTION_NORMAL, TRANSACTION_PROVIDER_REGISTER, TRANSACTION_PROVIDER_UPDATE_REGISTRAR, TRANSACTION_PROVIDER_UPDATE_REVOKE, TRANSACTION_PROVIDER_UPDATE_SERVICE, TRANSACTION_QUORUM_COMMITMENT, versionbitscache, and VersionBitsState().
Referenced by AcceptToMemoryPoolWorker(), and ContextualCheckBlock().
ConvertBitsToDouble()
double ConvertBitsToDouble (unsigned int nBits)
Definition at line 1123 of file validation.cpp.
Referenced by ContextualCheckBlockHeader(), and GetBlockSubsidy().
DisconnectBlock()
static DisconnectResult DisconnectBlock (const CBlock & block, CValidationState & state, const CBlockIndex * pindex, CCoinsViewCache & view) static
Undo the effects of this block (with given index) on the UTXO set represented by coins.
When UNCLEAN or FAILED is returned, view is left in an indeterminate state.
Definition at line 1616 of file validation.cpp.
References CCoinsViewCache::AccessCoin(), ApplyTxInUndo(), prevector< N, T, Size, Diff >::begin(), Consensus::DEPLOYMENT_DIP0003, DISCONNECT_FAILED, DISCONNECT_OK, DISCONNECT_UNCLEAN, prevector< N, T, Size, Diff >::end(), CBlockTreeDB::EraseAddressIndex(), error(), evoDb, fAddressIndex, Coin::fCoinBase, fSpentIndex, CCoinsViewCache::GetBestBlock(), CBlockIndex::GetBlockHash(), CTransaction::GetHash(), CBlockIndex::GetUndoPos(), COutPoint::hash, Hash160(), instantsend, CInstantSend::isAutoLockBip9Active, CTransaction::IsCoinBase(), CDiskBlockPos::IsNull(), CScript::IsPayToPublicKey(), CScript::IsPayToPublicKeyHash(), CScript::IsPayToScriptHash(), COutPoint::n, Coin::nHeight, CBlockIndex::nHeight, CTxOut::nValue, Coin::out, Params(), pblocktree, CBlockIndex::pprev, CTxIn::prevout, CTxOut::scriptPubKey, CCoinsViewCache::SetBestBlock(), CCoinsViewCache::SpendCoin(), THRESHOLD_ACTIVE, UndoSpecialTxsInBlock(), CBlockTreeDB::UpdateAddressUnspentIndex(), CEvoDB::VerifyBestBlock(), versionbitscache, VersionBitsState(), CTransaction::vin, CTransaction::vout, CTxUndo::vprevout, CBlock::vtx, CBlockUndo::vtxundo, and CEvoDB::WriteBestBlock().
Referenced by DisconnectTip(), and CVerifyDB::VerifyDB().
DisconnectBlocks()
bool DisconnectBlocks (int blocks)
Functions for validating blocks and updating the block tree.
Reprocess a number of blocks to try and get on the correct chain again
Definition at line 2661 of file validation.cpp.
References cs_main, DisconnectTip(), CValidationState::IsValid(), LOCK, LogPrintf, and Params().
Referenced by ReprocessBlocks().
DisconnectTip()
static bool DisconnectTip (CValidationState & state, const CChainParams & chainparams) static
Disconnect chainActive's tip.
You probably want to call mempool.removeForReorg and manually re-limit mempool size after this, with cs_main held.
Definition at line 2534 of file validation.cpp.
References AcceptToMemoryPool(), CEvoDB::BeginTransaction(), chainActive, DISCONNECT_OK, DisconnectBlock(), error(), evoDb, CTxMemPool::exists(), CCoinsViewCache::Flush(), FLUSH_STATE_IF_NEEDED, FlushStateToDisk(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), CTransaction::GetHash(), GetMainSignals(), GetTimeMicros(), CTransaction::IsCoinBase(), LogPrint, mempool, pcoinsTip, CBlockIndex::pprev, ReadBlockFromDisk(), CTxMemPool::removeRecursive(), REORG, CMainSignals::SYNC_TRANSACTION_NOT_IN_BLOCK, CMainSignals::SyncTransaction, CChain::Tip(), base_blob< BITS >::ToString(), UpdateTip(), CTxMemPool::UpdateTransactionsFromBlock(), and CBlock::vtx.
Referenced by ActivateBestChainStep(), DisconnectBlocks(), and InvalidateBlock().
DumpMempool()
void DumpMempool ()
Dump the mempool to disk.
Definition at line 4571 of file validation.cpp.
References CLIENT_VERSION, CTxMemPool::cs, CAutoFile::fclose(), FileCommit(), CAutoFile::Get(), GetDataDir(), GetTimeMicros(), CTxMemPool::infoAll(), LOCK, LogPrintf, CTxMemPool::mapDeltas, mempool, MEMPOOL_DUMP_VERSION, RenameOver(), and SER_DISK.
Referenced by PrepareShutdown().
EvaluateSequenceLocks()
static bool EvaluateSequenceLocks (const CBlockIndex & block, std::pair< int, int64_t > lockPair) static
Definition at line 354 of file validation.cpp.
References CBlockIndex::GetMedianTimePast(), CBlockIndex::nHeight, and CBlockIndex::pprev.
Referenced by CheckSequenceLocks(), and SequenceLocks().
fImporting()
std::atomic_bool fImporting (false)
Referenced by IsInitialBlockDownload().
FindBlockPos()
bool FindBlockPos (CValidationState & state, CDiskBlockPos & pos, unsigned int nAddSize, unsigned int nHeight, uint64_t nTime, bool fKnown = false)
Definition at line 3155 of file validation.cpp.
References AllocateFileRange(), BLOCKFILE_CHUNK_SIZE, CheckDiskSpace(), CValidationState::Error(), FlushBlockFile(), fPruneMode, LOCK, LogPrintf, MAX_BLOCKFILE_SIZE, CDiskBlockPos::nFile, CDiskBlockPos::nPos, and OpenBlockFile().
Referenced by AcceptBlock(), and AddGenesisBlock().
FindFilesToPrune()
void FindFilesToPrune (std::set< int > & setFilesToPrune, uint64_t nPruneAfterHeight)
Prune block and undo files (blk???.dat and undo???.dat) so that the disk space used is less than a user-defined target.
The user sets the target (in MB) on the command line or in config file. This will be run on startup and whenever new space is allocated in a block or undo file, staying below the target. Changing back to unpruned requires a reindex (which in this case means the blockchain must be re-downloaded.)
Pruning functions are called from FlushStateToDisk when the global fCheckForPruning flag has been set. Block and undo files are deleted in lock-step (when blk00003.dat is deleted, so is rev00003.dat.) Pruning cannot take place until the longest chain is at least a certain length (100000 on mainnet, 1000 on testnet, 1000 on regtest). Pruning will never delete a block within a defined distance (currently 288) from the active chain's tip. The block index is updated by unsetting HAVE_DATA and HAVE_UNDO for any blocks that were stored in the deleted files. A db flag records the fact that at least some block files have been pruned.
Parameters
[out] setFilesToPrune The set of file indices that can be unlinked will be returned
Definition at line 3734 of file validation.cpp.
References BLOCKFILE_CHUNK_SIZE, CalculateCurrentUsage(), chainActive, count, cs_main, LOCK2, LogPrint, MIN_BLOCKS_TO_KEEP, CBlockIndex::nHeight, nPruneTarget, PruneOneBlockFile(), CChain::Tip(), and UNDOFILE_CHUNK_SIZE.
Referenced by FlushStateToDisk().
FindFilesToPruneManual()
void FindFilesToPruneManual (std::set< int > & setFilesToPrune, int nManualPruneHeight)
Definition at line 3705 of file validation.cpp.
References chainActive, count, cs_main, fPruneMode, LOCK2, LogPrintf, MIN_BLOCKS_TO_KEEP, CBlockIndex::nHeight, PruneOneBlockFile(), and CChain::Tip().
Referenced by FlushStateToDisk().
FindForkInGlobalIndex()
CBlockIndex* FindForkInGlobalIndex (const CChain & chain, const CBlockLocator & locator)
Find the last common block between the parameter chain and a locator.
Definition at line 211 of file validation.cpp.
References CChain::Contains(), CChain::Genesis(), mapBlockIndex, and CBlockLocator::vHave.
Referenced by CWallet::CreateWalletFromFile(), and ProcessMessage().
FindMostWorkChain()
static CBlockIndex* FindMostWorkChain () static
Return the tip of the chain with the most work in it, that isn't known to be invalid (it's however far from certain to be valid).
Definition at line 2708 of file validation.cpp.
References BLOCK_FAILED_CHILD, BLOCK_FAILED_MASK, BLOCK_HAVE_DATA, chainActive, CChain::Contains(), CBlockIndex::nChainTx, CBlockIndex::nChainWork, CBlockIndex::nHeight, CBlockIndex::nStatus, and CBlockIndex::pprev.
Referenced by ActivateBestChain().
FindUndoPos()
bool FindUndoPos (CValidationState & state, int nFile, CDiskBlockPos & pos, unsigned int nAddSize)
Definition at line 3212 of file validation.cpp.
References AllocateFileRange(), CheckDiskSpace(), CValidationState::Error(), fPruneMode, LOCK, LogPrintf, CDiskBlockPos::nFile, CDiskBlockPos::nPos, OpenUndoFile(), and UNDOFILE_CHUNK_SIZE.
Referenced by ConnectBlock().
FlushBlockFile()
static void FlushBlockFile (bool fFinalize = false) static
Definition at line 1789 of file validation.cpp.
References FileCommit(), LOCK, OpenBlockFile(), OpenUndoFile(), and TruncateFile().
Referenced by FindBlockPos(), and FlushStateToDisk().
FlushStateToDisk() [1/2]
static bool FlushStateToDisk (CValidationState & state, FlushStateMode mode, int nManualPruneHeight) static
Update the on-disk chain state.
The caches and indexes are flushed depending on the mode we're called with if they're too large, if it's been a while since the last write, or always and in all cases if we're in prune mode and are deleting files.
Definition at line 2353 of file validation.cpp.
References chainActive, CheckDiskSpace(), CEvoDB::CommitRootTransaction(), cs_main, DATABASE_FLUSH_INTERVAL, DATABASE_WRITE_INTERVAL, DB_PEAK_USAGE_FACTOR, DEFAULT_MAX_MEMPOOL_SIZE, CCoinsViewCache::DynamicMemoryUsage(), CTxMemPool::DynamicMemoryUsage(), CValidationState::Error(), evoDb, fHavePruned, FindFilesToPrune(), FindFilesToPruneManual(), CCoinsViewCache::Flush(), FLUSH_STATE_ALWAYS, FLUSH_STATE_IF_NEEDED, FLUSH_STATE_PERIODIC, FlushBlockFile(), fPruneMode, fReindex, GetArg(), CCoinsViewCache::GetCacheSize(), CChain::GetLocator(), GetMainSignals(), GetTimeMicros(), LOCK2, MAX_BLOCK_COINSDB_USAGE, mempool, nCoinCacheUsage, Params(), pblocktree, pcoinsTip, CChainParams::PruneAfterHeight(), CMainSignals::SetBestChain, UnlinkPrunedFiles(), CBlockTreeDB::WriteBatchSync(), and CBlockTreeDB::WriteFlag().
Referenced by AcceptBlock(), AcceptToMemoryPoolWithTime(), ActivateBestChain(), ConnectTip(), DisconnectTip(), FlushStateToDisk(), gettxoutsetinfo(), InitBlockIndex(), PrepareShutdown(), PruneAndFlush(), and PruneBlockFilesManual().
FlushStateToDisk() [2/2]
void FlushStateToDisk ()
Flush all state, indexes and buffers to disk.
Definition at line 2460 of file validation.cpp.
References FLUSH_STATE_ALWAYS, and FlushStateToDisk().
FormatStateMessage()
std::string FormatStateMessage (const CValidationState & state)
Convert CValidationState to a human-readable message for logging.
Definition at line 618 of file validation.cpp.
References CValidationState::GetDebugMessage(), CValidationState::GetRejectCode(), CValidationState::GetRejectReason(), and strprintf.
Referenced by AcceptBlock(), AcceptBlockHeader(), AcceptToMemoryPoolWorker(), ConnectBlock(), BlockAssembler::CreateNewBlock(), ProcessMessage(), ProcessNewBlock(), TestBlockValidity(), and CVerifyDB::VerifyDB().
GetAddressIndex()
bool GetAddressIndex (uint160 addressHash, int type, std::vector< std::pair< CAddressIndexKey, CAmount > > & addressIndex, int start, int end)
Definition at line 975 of file validation.cpp.
References error(), fAddressIndex, pblocktree, and CBlockTreeDB::ReadAddressIndex().
Referenced by getaddressbalance(), getaddressdeltas(), and getaddresstxids().
GetAddressUnspent()
bool GetAddressUnspent (uint160 addressHash, int type, std::vector< std::pair< CAddressUnspentKey, CAddressUnspentValue > > & unspentOutputs)
Definition at line 987 of file validation.cpp.
References error(), fAddressIndex, pblocktree, and CBlockTreeDB::ReadAddressUnspentIndex().
Referenced by getaddressutxos().
GetBlockFileInfo()
CBlockFileInfo* GetBlockFileInfo (size_t n)
Get block file info entry for one block file.
Definition at line 4486 of file validation.cpp.
Referenced by BOOST_FIXTURE_TEST_CASE().
GetBlockHash()
bool GetBlockHash (uint256 & hashRet, int nBlockHeight = -1)
Return true if hash can be found in chainActive at nBlockHeight height.
Fills hashRet with found hash, if no nBlockHeight is specified - chainActive.Height() is used.
Definition at line 1872 of file validation.cpp.
References chainActive, cs_main, CChain::Height(), LOCK, and CChain::Tip().
Referenced by CMasternodePayments::AddOrUpdatePaymentVote(), CMasternodeMan::GetMasternodeRank(), CMasternodeMan::GetMasternodeRanks(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), llmq::CQuorumBlockProcessor::GetQuorumBlockHash(), GetRequiredPaymentsStrings(), ProcessMessage(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), protx_list(), CMasternodePayments::RequestLowDataPaymentBlocks(), and CMasternodeMan::SendVerifyReply().
GetBlockPosFilename()
boost::filesystem::path GetBlockPosFilename (const CDiskBlockPos & pos, const char * prefix)
Translation to a filesystem path.
Definition at line 3823 of file validation.cpp.
References GetDataDir(), CDiskBlockPos::nFile, prefix, and strprintf.
Referenced by OpenDiskFile(), ThreadImport(), and UnlinkPrunedFiles().
GetBlockSubsidy()
CAmount GetBlockSubsidy (int nPrevBits, int nPrevHeight, const Consensus::Params & consensusParams, bool fSuperblockPartOnly)
Definition at line 1148 of file validation.cpp.
References COIN, ConvertBitsToDouble(), CBaseChainParams::MAIN, Consensus::Params::nBudgetPaymentsStartBlock, Consensus::Params::nHighSubsidyBlocks, Consensus::Params::nHighSubsidyFactor, Consensus::Params::nSubsidyHalvingInterval, and Params().
Referenced by ConnectBlock(), BlockAssembler::CreateNewBlock(), and CSuperblock::GetPaymentsLimit().
GetLegacySigOpCount()
unsigned int GetLegacySigOpCount (const CTransaction & tx)
Count ECDSA signature operations the old-fashioned (pre-0.6) way.
Returns
number of sigops this transaction's outputs will produce when spent
See also
CTransaction::FetchInputs
Definition at line 458 of file validation.cpp.
References CTransaction::vin, and CTransaction::vout.
Referenced by AcceptToMemoryPoolWorker(), CheckBlock(), ConnectBlock(), ContextualCheckBlock(), and BlockAssembler::CreateNewBlock().
GetMasternodePayment()
CAmount GetMasternodePayment (int nHeight, CAmount blockValue)
Definition at line 1199 of file validation.cpp.
References CChainParams::GetConsensus(), Consensus::Params::nMasternodePaymentsIncreaseBlock, Consensus::Params::nMasternodePaymentsIncreasePeriod, and Params().
Referenced by CMasternodePayments::GetBlockTxOuts(), CMasternodePayments::GetMasternodeTxOuts(), CMasternodeBlockPayees::IsTransactionValid(), and CMasternode::UpdateLastPaid().
GetP2SHSigOpCount()
unsigned int GetP2SHSigOpCount (const CTransaction & tx, const CCoinsViewCache & mapInputs)
Count ECDSA signature operations in pay-to-script-hash inputs.
Parameters
[in] mapInputs Map of previous transactions that have outputs we're spending
Returns
maximum number of sigops required to validate this transaction's inputs
See also
CTransaction::FetchInputs
Definition at line 472 of file validation.cpp.
References CCoinsViewCache::AccessCoin(), CScript::GetSigOpCount(), CTransaction::IsCoinBase(), Coin::IsSpent(), Coin::out, CTxOut::scriptPubKey, and CTransaction::vin.
Referenced by AcceptToMemoryPoolWorker(), and ConnectBlock().
GetSpendHeight()
int GetSpendHeight (const CCoinsViewCache & inputs)
Return the spend height, which is one more than the inputs.GetBestBlock().
While checking, GetBestBlock() refers to the parent block. (protected by cs_main) This is also true for mempool checks.
Definition at line 1382 of file validation.cpp.
References cs_main, CCoinsViewCache::GetBestBlock(), LOCK, mapBlockIndex, and CBlockIndex::nHeight.
Referenced by CTxMemPool::check(), and CheckInputs().
GetSpentIndex()
bool GetSpentIndex (CSpentIndexKey & key, CSpentIndexValue & value)
Definition at line 961 of file validation.cpp.
References fSpentIndex, CTxMemPool::getSpentIndex(), mempool, pblocktree, and CBlockTreeDB::ReadSpentIndex().
Referenced by getspentinfo(), and TxToJSON().
GetTimestampIndex()
bool GetTimestampIndex (const unsigned int & high, const unsigned int & low, std::vector< uint256 > & hashes)
Definition at line 950 of file validation.cpp.
References error(), fTimestampIndex, high, low, pblocktree, and CBlockTreeDB::ReadTimestampIndex().
Referenced by getblockhashes().
GetTransaction()
bool GetTransaction (const uint256 & hash, CTransactionRef & txOut, const Consensus::Params & consensusParams, uint256 & hashBlock, bool fAllowSlow)
Return transaction in txOut, and if it was found inside a block, its hash is placed in hashBlock.
Retrieve a transaction (from memory pool, or from disk, if possible)
Definition at line 1000 of file validation.cpp.
References AccessByTxid(), chainActive, CLIENT_VERSION, cs_main, error(), fTxIndex, CAutoFile::Get(), CTxMemPool::get(), CBlockIndex::GetBlockHash(), CBlockHeader::GetHash(), CAutoFile::IsNull(), Coin::IsSpent(), LOCK, mempool, Coin::nHeight, CDiskTxPos::nTxOffset, OpenBlockFile(), pblocktree, pcoinsTip, ReadBlockFromDisk(), CBlockTreeDB::ReadTxIndex(), SER_DISK, and CBlock::vtx.
Referenced by BuildDMNListEntry(), getrawtransaction(), gettxoutproof(), CGovernanceObject::IsCollateralValid(), CInstantSend::ResolveConflicts(), and rest_tx().
GetUTXOCoin()
bool GetUTXOCoin (const COutPoint & outpoint, Coin & coin)
Definition at line 489 of file validation.cpp.
References cs_main, CCoinsViewCache::GetCoin(), Coin::IsSpent(), LOCK, and pcoinsTip.
Referenced by CDeterministicMNManager::BuildNewListFromBlock(), CMasternode::Check(), CMasternode::CheckCollateral(), CheckProRegTx(), CheckProUpRegTx(), GetUTXOHeight(), CPrivateSend::IsCollateralValid(), CTxLockRequest::IsValid(), CTxLockVote::IsValid(), masternodelist(), CPrivateSendServer::ProcessMessage(), CInstantSend::ResolveConflicts(), and CDeterministicMN::ToJson().
GetUTXOConfirmations()
int GetUTXOConfirmations (const COutPoint & outpoint)
Definition at line 506 of file validation.cpp.
References chainActive, cs_main, GetUTXOHeight(), CChain::Height(), LOCK, and CChain::Tip().
Referenced by BuildDMNListEntry(), and CMasternodeMan::GetNextMasternodeInQueueForPayment().
GetUTXOHeight()
int GetUTXOHeight (const COutPoint & outpoint)
Definition at line 499 of file validation.cpp.
References GetUTXOCoin(), and Coin::nHeight.
Referenced by GetUTXOConfirmations(), and CInstantSend::Vote().
GUARDED_BY()
std::map<uint256, int64_t> mapRejectedBlocks GUARDED_BY (cs_main)
GuessVerificationProgress()
double GuessVerificationProgress (const ChainTxData & data, CBlockIndex * pindex)
Guess how far we are in the verification process at the given block index.
Guess verification progress (as a fraction between 0.0=genesis and 1.0=current tip).
Definition at line 4619 of file validation.cpp.
References ChainTxData::dTxRate, CBlockIndex::GetBlockTime(), CBlockIndex::nChainTx, ChainTxData::nTime, and ChainTxData::nTxCount.
Referenced by getblockchaininfo(), ClientModel::getVerificationProgress(), LoadBlockIndexDB(), CWallet::ScanForWalletTransactions(), and UpdateTip().
InitBlockIndex()
bool InitBlockIndex (const CChainParams & chainparams)
Initialize a new block tree database + block data on disk.
Definition at line 4130 of file validation.cpp.
References AddGenesisBlock(), chainActive, cs_main, DEFAULT_ADDRESSINDEX, DEFAULT_SPENTINDEX, DEFAULT_TIMESTAMPINDEX, DEFAULT_TXINDEX, CBaseChainParams::DEVNET, CChainParams::DevNetGenesisBlock(), error(), fAddressIndex, FLUSH_STATE_ALWAYS, FlushStateToDisk(), fReindex, fSpentIndex, fTimestampIndex, fTxIndex, CChain::Genesis(), CChainParams::GenesisBlock(), GetBoolArg(), LOCK, LogPrintf, CChainParams::NetworkIDString(), pblocktree, ProcessNewBlock(), and CBlockTreeDB::WriteFlag().
Referenced by AppInitMain(), and ThreadImport().
InsertBlockIndex()
CBlockIndex* InsertBlockIndex (uint256 hash)
Create a new block index entry for a given block hash.
Definition at line 3828 of file validation.cpp.
References base_blob< BITS >::IsNull(), and mapBlockIndex.
Referenced by LoadBlockIndexDB().
InvalidateBlock()
bool InvalidateBlock (CValidationState & state, const CChainParams & chainparams, CBlockIndex * pindex)
Mark a block as invalid.
Definition at line 2991 of file validation.cpp.
References AssertLockHeld, BLOCK_FAILED_CHILD, BLOCK_FAILED_VALID, BLOCK_VALID_TRANSACTIONS, chainActive, CChain::Contains(), cs_main, DEFAULT_MAX_MEMPOOL_SIZE, DEFAULT_MEMPOOL_EXPIRY, DisconnectTip(), GetArg(), GetMainSignals(), InvalidChainFound(), IsInitialBlockDownload(), LimitMempoolSize(), mapBlockIndex, mempool, CBlockIndex::nHeight, CClientUIInterface::NotifyBlockTip, CBlockIndex::nStatus, pcoinsTip, pindexBestHeader, CBlockIndex::pprev, CTxMemPool::removeForReorg(), STANDARD_LOCKTIME_VERIFY_FLAGS, CChain::Tip(), uiInterface, and CMainSignals::UpdatedBlockTip.
Referenced by invalidateblock().
InvalidBlockFound()
static void InvalidBlockFound (CBlockIndex * pindex, const CValidationState & state) static
Definition at line 1344 of file validation.cpp.
References BLOCK_FAILED_VALID, CValidationState::CorruptionPossible(), InvalidChainFound(), and CBlockIndex::nStatus.
Referenced by ConnectTip().
InvalidChainFound()
static void InvalidChainFound (CBlockIndex * pindexNew) static
Definition at line 1327 of file validation.cpp.
References chainActive, CheckForkWarningConditions(), DateTimeStrFormat(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockTime(), base_uint< BITS >::getdouble(), CChain::Height(), LogPrintf, CBlockIndex::nChainWork, CBlockIndex::nHeight, CChain::Tip(), and base_blob< BITS >::ToString().
Referenced by ActivateBestChainStep(), InvalidateBlock(), and InvalidBlockFound().
IsCurrentForFeeEstimation()
static bool IsCurrentForFeeEstimation () static
Definition at line 626 of file validation.cpp.
References AssertLockHeld, chainActive, cs_main, CBlockIndex::GetBlockTime(), GetTime(), CChain::Height(), IsInitialBlockDownload(), MAX_FEE_ESTIMATION_TIP_AGE, CBlockIndex::nHeight, pindexBestHeader, and CChain::Tip().
Referenced by AcceptToMemoryPoolWorker().
IsFinalTx()
bool IsFinalTx (const CTransaction & tx, int nBlockHeight, int64_t nBlockTime)
Check if transaction is final and can be included in a block with the specified height and time.
Consensus critical.
Definition at line 241 of file validation.cpp.
References LOCKTIME_THRESHOLD, CTransaction::nLockTime, CTxIn::SEQUENCE_FINAL, and CTransaction::vin.
Referenced by CheckFinalTx(), ContextualCheckBlock(), BlockAssembler::TestForBlock(), and BlockAssembler::TestPackageTransactions().
IsInitialBlockDownload()
bool IsInitialBlockDownload ()
Check whether we are doing an initial block download (synchronizing from disk or network)
Definition at line 1220 of file validation.cpp.
References chainActive, cs_main, fImporting(), fReindex, CBlockIndex::GetBlockTime(), CChainParams::GetConsensus(), GetTime(), LOCK, CBlockIndex::nChainWork, nMaxTipAge, Consensus::Params::nMinimumChainWork, Params(), CChain::Tip(), and UintToArith256().
Referenced by AcceptBlock(), ActivateBestChain(), PeerLogicValidation::BlockChecked(), CheckForkWarningConditions(), getblocktemplate(), ClientModel::inInitialBlockDownload(), CDSNotificationInterface::InitializeCurrentBlockTip(), InvalidateBlock(), IsCurrentForFeeEstimation(), NotifyHeaderTip(), ProcessMessage(), SendMessages(), and UpdateTip().
LimitMempoolSize()
void LimitMempoolSize (CTxMemPool & pool, size_t limit, unsigned long age)
Definition at line 606 of file validation.cpp.
References CTxMemPool::Expire(), GetTime(), LogPrint, pcoinsTip, CTxMemPool::TrimToSize(), and CCoinsViewCache::Uncache().
Referenced by AcceptToMemoryPoolWorker(), ActivateBestChainStep(), and InvalidateBlock().
LoadBlockIndex()
bool LoadBlockIndex (const CChainParams & chainparams)
Load the block tree and coins database from disk.
Definition at line 4107 of file validation.cpp.
References fReindex, and LoadBlockIndexDB().
Referenced by AppInitMain().
LoadBlockIndexDB()
static bool LoadBlockIndexDB (const CChainParams & chainparams) static
Definition at line 3848 of file validation.cpp.
References BLOCK_FAILED_MASK, BLOCK_HAVE_DATA, BLOCK_VALID_TRANSACTIONS, BLOCK_VALID_TREE, CBlockIndex::BuildSkip(), chainActive, CLIENT_VERSION, DateTimeStrFormat(), fAddressIndex, fHavePruned, fReindex, fSpentIndex, fTimestampIndex, fTxIndex, CCoinsViewCache::GetBestBlock(), CBlockIndex::GetBlockHash(), GetBlockProof(), CBlockIndex::GetBlockTime(), GuessVerificationProgress(), CChain::Height(), InsertBlockIndex(), CBlockIndex::IsValid(), CBlockTreeDB::LoadBlockIndexGuts(), LogPrintf, mapBlockIndex, CBlockIndex::nChainTx, CBlockIndex::nChainWork, CBlockIndex::nFile, CBlockIndex::nHeight, CBlockIndex::nStatus, CBlockIndex::nTime, CBlockIndex::nTimeMax, CBlockIndex::nTx, OpenBlockFile(), PAIRTYPE, pblocktree, pcoinsTip, pindexBestHeader, CBlockIndex::pprev, PruneBlockIndexCandidates(), CBlockTreeDB::ReadBlockFileInfo(), CBlockTreeDB::ReadFlag(), CBlockTreeDB::ReadLastBlockFile(), CBlockTreeDB::ReadReindexing(), SER_DISK, CChain::SetTip(), CChain::Tip(), base_blob< BITS >::ToString(), and CChainParams::TxData().
Referenced by LoadBlockIndex().
LoadExternalBlockFile()
bool LoadExternalBlockFile (const CChainParams & chainparams, FILE * fileIn, CDiskBlockPos * dbp)
Import blocks from an external file.
Definition at line 4180 of file validation.cpp.
References AcceptBlock(), ActivateBestChain(), BLOCK_HAVE_DATA, CLIENT_VERSION, cs_main, CBufferedFile::eof(), CBufferedFile::FindByte(), FLATDATA, CChainParams::GetConsensus(), CBufferedFile::GetPos(), GetTimeMillis(), Consensus::Params::hashGenesisBlock, CValidationState::IsError(), LOCK, LogPrint, LogPrintf, mapBlockIndex, MaxBlockSize(), CMessageHeader::MESSAGE_START_SIZE, CChainParams::MessageStart(), NotifyHeaderTip(), CDiskBlockPos::nPos, ReadBlockFromDisk(), SER_DISK, CBufferedFile::SetLimit(), CBufferedFile::SetPos(), and base_blob< BITS >::ToString().
Referenced by ThreadImport().
LoadMempool()
bool LoadMempool ()
Load the mempool from disk.
Definition at line 4505 of file validation.cpp.
References AcceptToMemoryPoolWithTime(), CLIENT_VERSION, count, cs_main, DEFAULT_MEMPOOL_EXPIRY, GetArg(), GetDataDir(), GetTime(), CAutoFile::IsNull(), CValidationState::IsValid(), LOCK, LogPrintf, mempool, MEMPOOL_DUMP_VERSION, CTxMemPool::PrioritiseTransaction(), SER_DISK, and ShutdownRequested().
Referenced by ThreadImport().
NotifyHeaderTip()
static void NotifyHeaderTip () static
Definition at line 2852 of file validation.cpp.
References cs_main, GetMainSignals(), IsInitialBlockDownload(), LOCK, CMainSignals::NotifyHeaderTip, CClientUIInterface::NotifyHeaderTip, pindexBestHeader, and uiInterface.
Referenced by LoadExternalBlockFile(), ProcessNewBlock(), and ProcessNewBlockHeaders().
OpenBlockFile()
FILE* OpenBlockFile (const CDiskBlockPos & pos, bool fReadOnly)
Open a block file (blk?????.dat)
Definition at line 3815 of file validation.cpp.
References OpenDiskFile().
Referenced by FindBlockPos(), FlushBlockFile(), GetTransaction(), LoadBlockIndexDB(), ReadBlockFromDisk(), ThreadImport(), and WriteBlockToDisk().
OpenDiskFile()
FILE* OpenDiskFile (const CDiskBlockPos & pos, const char * prefix, bool fReadOnly)
Definition at line 3792 of file validation.cpp.
References GetBlockPosFilename(), CDiskBlockPos::IsNull(), LogPrintf, CDiskBlockPos::nPos, and prefix.
Referenced by OpenBlockFile(), and OpenUndoFile().
OpenUndoFile()
FILE* OpenUndoFile (const CDiskBlockPos & pos, bool fReadOnly)
Open an undo file (rev?????.dat)
Definition at line 3819 of file validation.cpp.
References OpenDiskFile().
Referenced by FindUndoPos(), and FlushBlockFile().
PreciousBlock()
bool PreciousBlock (CValidationState & state, const CChainParams & params, CBlockIndex * pindex)
Mark a block as precious and reorganize.
Definition at line 2962 of file validation.cpp.
References ActivateBestChain(), BLOCK_VALID_TRANSACTIONS, chainActive, cs_main, CBlockIndex::IsValid(), LOCK, CBlockIndex::nChainTx, CBlockIndex::nChainWork, CBlockIndex::nSequenceId, PruneBlockIndexCandidates(), and CChain::Tip().
Referenced by preciousblock().
ProcessNewBlock()
bool ProcessNewBlock (const CChainParams & chainparams, const std::shared_ptr< const CBlock > pblock, bool fForceProcessing, bool * fNewBlock)
Process an incoming block.
This only returns after the best known valid block is made active. Note that it does not, however, guarantee that the specific block passed to it has been checked for validity!
If you want to possibly get feedback on whether pblock is valid, you must install a CValidationInterface (see validationinterface.h) - this will have its BlockChecked method called whenever any block completes validation.
Note that we guarantee that either the proof-of-work is valid on pblock, or (and possibly also) BlockChecked will have been called.
Call without cs_main held.
Parameters
[in] pblock The block we want to process.
[in] fForceProcessing Process this block even if unrequested; used for non-network block sources and whitelisted peers.
[out] fNewBlock A boolean which is set to indicate if the block was first received via this call
Returns
True if state.IsValid()
Definition at line 3585 of file validation.cpp.
References AcceptBlock(), ActivateBestChain(), CMainSignals::BlockChecked, CheckBlock(), CheckBlockIndex(), cs_main, error(), FormatStateMessage(), CChainParams::GetConsensus(), GetMainSignals(), LOCK, LogPrintf, and NotifyHeaderTip().
Referenced by generateBlocks(), InitBlockIndex(), ProcessMessage(), and submitblock().
ProcessNewBlockHeaders()
bool ProcessNewBlockHeaders (const std::vector< CBlockHeader > & block, CValidationState & state, const CChainParams & chainparams, const CBlockIndex ** ppindex = NULL)
Process incoming block headers.
Call without cs_main held.
Parameters
[in] block The block headers themselves
[out] state This may be set to an Error state if any error occurred processing them
[in] chainparams The params for the chain we want to connect to
[out] ppindex If set, the pointer will be set to point to the last new block index object for the given headers
Definition at line 3487 of file validation.cpp.
References AcceptBlockHeader(), cs_main, LOCK, and NotifyHeaderTip().
Referenced by ProcessMessage().
PruneAndFlush()
void PruneAndFlush ()
Prune block files and flush state to disk.
Definition at line 2465 of file validation.cpp.
References FLUSH_STATE_NONE, and FlushStateToDisk().
Referenced by AppInitMain().
PruneBlockFilesManual()
void PruneBlockFilesManual (int nManualPruneHeight)
Prune block files up to a given height.
Definition at line 3727 of file validation.cpp.
References FLUSH_STATE_NONE, and FlushStateToDisk().
Referenced by pruneblockchain().
PruneBlockIndexCandidates()
static void PruneBlockIndexCandidates () static
Delete all entries in setBlockIndexCandidates that are worse than the current tip.
Definition at line 2763 of file validation.cpp.
References chainActive, and CChain::Tip().
Referenced by ActivateBestChainStep(), LoadBlockIndexDB(), and PreciousBlock().
PruneOneBlockFile()
void PruneOneBlockFile (const int fileNumber)
Mark one block file as pruned.
Definition at line 3662 of file validation.cpp.
References BLOCK_HAVE_DATA, BLOCK_HAVE_UNDO, mapBlockIndex, CBlockIndex::nDataPos, CBlockIndex::nFile, CBlockIndex::nStatus, CBlockIndex::nUndoPos, and CBlockIndex::pprev.
Referenced by BOOST_FIXTURE_TEST_CASE(), FindFilesToPrune(), and FindFilesToPruneManual().
ReadBlockFromDisk() [1/2]
bool ReadBlockFromDisk (CBlock & block, const CDiskBlockPos & pos, const Consensus::Params & consensusParams)
Definition at line 1089 of file validation.cpp.
References CheckProofOfWork(), CLIENT_VERSION, error(), CBlockHeader::GetHash(), CAutoFile::IsNull(), CBlockHeader::nBits, OpenBlockFile(), SER_DISK, CBlock::SetNull(), and CDiskBlockPos::ToString().
Referenced by BuildSimplifiedMNListDiff(), ConnectTip(), DisconnectTip(), getblock(), getspecialtxes(), GetTransaction(), gettxoutproof(), LoadExternalBlockFile(), CZMQPublishRawBlockNotifier::NotifyBlock(), ProcessGetData(), ProcessMessage(), ReadBlockFromDisk(), rest_block(), CWallet::ScanForWalletTransactions(), SendMessages(), CMasternode::UpdateLastPaid(), and CVerifyDB::VerifyDB().
ReadBlockFromDisk() [2/2]
bool ReadBlockFromDisk (CBlock & block, const CBlockIndex * pindex, const Consensus::Params & consensusParams)
Definition at line 1113 of file validation.cpp.
References error(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockPos(), CBlockHeader::GetHash(), ReadBlockFromDisk(), CDiskBlockPos::ToString(), and CBlockIndex::ToString().
ReceivedBlockTransactions()
bool ReceivedBlockTransactions (const CBlock & block, CValidationState & state, CBlockIndex * pindexNew, const CDiskBlockPos & pos)
Mark a block as having its data received and checked (up to BLOCK_VALID_TRANSACTIONS).
Definition at line 3110 of file validation.cpp.
References BLOCK_HAVE_DATA, BLOCK_VALID_TRANSACTIONS, chainActive, LOCK, CBlockIndex::nChainTx, CBlockIndex::nDataPos, CDiskBlockPos::nFile, CBlockIndex::nFile, CDiskBlockPos::nPos, CBlockIndex::nSequenceId, CBlockIndex::nStatus, CBlockIndex::nTx, CBlockIndex::nUndoPos, CBlockIndex::pprev, CBlockIndex::RaiseValidity(), CChain::Tip(), and CBlock::vtx.
Referenced by AcceptBlock(), and AddGenesisBlock().
ReprocessBlocks()
void ReprocessBlocks (int nBlocks)
Definition at line 2678 of file validation.cpp.
References ActivateBestChain(), cs_main, DisconnectBlocks(), GetTime(), LOCK, LogPrintf, mapBlockIndex, mapRejectedBlocks, Params(), and ResetBlockFailureFlags().
Referenced by CSporkManager::ExecuteSpork().
ResetBlockFailureFlags()
bool ResetBlockFailureFlags (CBlockIndex * pindex)
Remove invalidity status from a block and its descendants.
Definition at line 3041 of file validation.cpp.
References AssertLockHeld, BLOCK_FAILED_MASK, BLOCK_VALID_TRANSACTIONS, chainActive, cs_main, mapBlockIndex, CBlockIndex::nHeight, CBlockIndex::nStatus, CBlockIndex::pprev, and CChain::Tip().
Referenced by reconsiderblock(), and ReprocessBlocks().
SequenceLocks()
bool SequenceLocks (const CTransaction & tx, int flags, std::vector< int > * prevHeights, const CBlockIndex & block)
Check if transaction is final per BIP 68 sequence numbers and can be included in a block.
Consensus critical. Takes as input a list of heights at which tx's inputs (in order) confirmed.
Definition at line 364 of file validation.cpp.
References CalculateSequenceLocks(), EvaluateSequenceLocks(), and flags.
Referenced by ConnectBlock().
TestBlockValidity()
bool TestBlockValidity (CValidationState & state, const CChainParams & chainparams, const CBlock & block, CBlockIndex * pindexPrev, bool fCheckPOW, bool fCheckMerkleRoot)
Check a block is completely valid from start to finish (only works on top of our current best block, with cs_main held)
Definition at line 3618 of file validation.cpp.
References AssertLockHeld, CEvoDB::BeginTransaction(), chainActive, CheckBlock(), CheckIndexAgainstCheckpoint(), ConnectBlock(), ContextualCheckBlock(), ContextualCheckBlockHeader(), cs_main, error(), evoDb, fCheckpointsEnabled, FormatStateMessage(), GetAdjustedTime(), CChainParams::GetConsensus(), CBlockHeader::GetHash(), CValidationState::GetRejectReason(), CValidationState::IsValid(), CBlockIndex::nHeight, pcoinsTip, CBlockIndex::pprev, and CChain::Tip().
Referenced by BlockAssembler::CreateNewBlock(), and getblocktemplate().
TestLockPointValidity()
bool TestLockPointValidity (const LockPoints * lp)
Test whether the LockPoints height and time are still valid on the current chain.
Definition at line 369 of file validation.cpp.
References AssertLockHeld, chainActive, CChain::Contains(), cs_main, and LockPoints::maxInputBlock.
Referenced by CTxMemPool::removeForReorg().
ThreadScriptCheck()
void ThreadScriptCheck ()
Run an instance of the script checking thread.
Definition at line 1816 of file validation.cpp.
References RenameThread(), and scriptcheckqueue.
Referenced by AppInitMain().
UnlinkPrunedFiles()
void UnlinkPrunedFiles (const std::set< int > & setFilesToPrune)
Actually unlink the specified files.
Definition at line 3694 of file validation.cpp.
References GetBlockPosFilename(), and LogPrintf.
Referenced by BOOST_FIXTURE_TEST_CASE(), and FlushStateToDisk().
UnloadBlockIndex()
void UnloadBlockIndex ()
Unload database information.
Definition at line 4081 of file validation.cpp.
References chainActive, VersionBitsCache::Clear(), CTxMemPool::clear(), cs_main, fHavePruned, LOCK, mapBlockIndex, mempool, pindexBestHeader, CChain::SetTip(), VERSIONBITS_NUM_BITS, versionbitscache, and warningcache.
Referenced by AppInitMain().
UpdateCoins() [1/2]
void UpdateCoins (const CTransaction & tx, CCoinsViewCache & inputs, CTxUndo & txundo, int nHeight)
Definition at line 1353 of file validation.cpp.
References AddCoins(), CTransaction::IsCoinBase(), CTxIn::prevout, CCoinsViewCache::SpendCoin(), CTransaction::vin, and CTxUndo::vprevout.
Referenced by CTxMemPool::check(), ConnectBlock(), and UpdateCoins().
UpdateCoins() [2/2]
void UpdateCoins (const CTransaction & tx, CCoinsViewCache & inputs, int nHeight)
Apply the effects of this transaction on the UTXO set represented by view.
Definition at line 1368 of file validation.cpp.
References UpdateCoins().
UpdateTip()
static void UpdateTip (CBlockIndex * pindexNew, const CChainParams & chainParams) static
Update chainActive and related internal data structures.
Definition at line 2472 of file validation.cpp.
References _(), CTxMemPool::AddTransactionsUpdated(), chainActive, ComputeBlockVersion(), cvBlockChange, DateTimeStrFormat(), CCoinsViewCache::DynamicMemoryUsage(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockTime(), CCoinsViewCache::GetCacheSize(), CChainParams::GetConsensus(), base_uint< BITS >::getdouble(), AbstractThresholdConditionChecker::GetStateFor(), GuessVerificationProgress(), CChain::Height(), IsInitialBlockDownload(), LogPrintf, mempool, CBlockIndex::nChainTx, CBlockIndex::nChainWork, CAlert::Notify(), CBlockIndex::nVersion, pcoinsTip, CBlockIndex::pprev, SetMiscWarning(), CChain::SetTip(), strprintf, THRESHOLD_ACTIVE, THRESHOLD_LOCKED_IN, CChain::Tip(), base_blob< BITS >::ToString(), CChainParams::TxData(), VERSIONBITS_LAST_OLD_BLOCK_VERSION, VERSIONBITS_NUM_BITS, and warningcache.
Referenced by ConnectTip(), and DisconnectTip().
VersionBitsTipState()
ThresholdState VersionBitsTipState (const Consensus::Params & params, Consensus::DeploymentPos pos)
Get the BIP9 state for a given deployment at the current tip.
Definition at line 4491 of file validation.cpp.
References AssertLockHeld, chainActive, cs_main, CChain::Tip(), versionbitscache, and VersionBitsState().
Referenced by BIP9SoftForkDesc().
VersionBitsTipStateSinceHeight()
int VersionBitsTipStateSinceHeight (const Consensus::Params & params, Consensus::DeploymentPos pos)
Get the block height at which the BIP9 deployment switched into the state for the block building on the current tip.
Definition at line 4497 of file validation.cpp.
References chainActive, cs_main, LOCK, CChain::Tip(), versionbitscache, and VersionBitsStateSinceHeight().
Referenced by BIP9SoftForkDesc().
WriteBlockToDisk()
bool WriteBlockToDisk (const CBlock & block, CDiskBlockPos & pos, const CMessageHeader::MessageStartChars & messageStart)
Functions for disk access for blocks.
Definition at line 1068 of file validation.cpp.
References CLIENT_VERSION, error(), fileout, FLATDATA, GetSerializeSize(), CDiskBlockPos::nPos, OpenBlockFile(), and SER_DISK.
Referenced by AcceptBlock(), and AddGenesisBlock().
Variable Documentation
chainActive
CChain chainActive
The currently-connected chain of blocks (protected by cs_main).
Definition at line 72 of file validation.cpp.
Referenced by AcceptBlock(), AcceptToMemoryPoolWorker(), ActivateBestChain(), ActivateBestChainStep(), AlreadyHave(), AppInitMain(), BIP9SoftForkDesc(), blockheaderToJSON(), blockToJSON(), BOOST_FIXTURE_TEST_CASE(), BuildSimplifiedMNListDiff(), CMasternode::Check(), CMasternodePing::CheckAndUpdate(), CheckBlockIndex(), CheckFinalTx(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), CMasternodeBroadcast::CheckOutpoint(), CheckSequenceLocks(), CMasternodePing::CMasternodePing(), ConnectTip(), llmq::CDummyDKG::CreateDummyCommitment(), llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::CreateFinalCommitment(), BlockAssembler::CreateNewBlock(), CWallet::CreateTransaction(), CWallet::CreateWalletFromFile(), DisconnectTip(), dumpwallet(), entryToJSON(), FindFilesToPrune(), FindFilesToPruneManual(), FindMostWorkChain(), FlushStateToDisk(), TransactionDesc::FormatTxStatus(), generateBlocks(), getbestblockhash(), getblockchaininfo(), getblockcount(), GetBlockHash(), getblockhash(), getblockheaders(), getblocktemplate(), CMasternodePayments::GetBlockTxOuts(), getchaintips(), CMerkleTx::GetDepthInMainChain(), GetDifficulty(), getgovernanceinfo(), getinfo(), CWallet::GetKeyBirthTimes(), ClientModel::getLastBlockDate(), getmininginfo(), CGovernanceManager::GetMinVoteTime(), GetNetworkHashPS(), GetNextMasternodeForPayment(), ClientModel::getNumBlocks(), GetRequiredPaymentsStrings(), GetTransaction(), gettxoutproof(), GetUTXOConfirmations(), ClientModel::getVerificationProgress(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), InitBlockIndex(), CDSNotificationInterface::InitializeCurrentBlockTip(), InvalidateBlock(), InvalidChainFound(), CGovernanceObject::IsCollateralValid(), IsCurrentForFeeEstimation(), IsInitialBlockDownload(), CTxLockRequest::IsValid(), listsinceblock(), LoadBlockIndexDB(), CWallet::MarkConflicted(), masternode_winners(), masternodelist(), ParseBlock(), WalletModel::pollBalanceChanged(), PreciousBlock(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), ProcessMessage(), CSporkManager::ProcessSpork(), protx_list(), pruneblockchain(), PruneBlockIndexCandidates(), ReceivedBlockTransactions(), CMasternodePayments::RequestLowDataPaymentBlocks(), ResetBlockFailureFlags(), rest_getutxos(), rest_headers(), CWallet::ScanForWalletTransactions(), SendMessages(), TransactionRecord::statusUpdateNeeded(), TestBlockValidity(), TestLockPointValidity(), ThreadImport(), TxToJSON(), UnloadBlockIndex(), llmq::CDummyDKG::UpdatedBlockTip(), CMasternode::UpdateLastPaid(), TransactionRecord::updateStatus(), UpdateTip(), CVerifyDB::VerifyDB(), verifytxoutproof(), VersionBitsTipState(), and VersionBitsTipStateSinceHeight().
COINBASE_FLAGS
CScript COINBASE_FLAGS
Constant stuff for coinbase transactions we create:
Definition at line 109 of file validation.cpp.
Referenced by getblocktemplate(), and IncrementExtraNonce().
cs_main
CCriticalSection cs_main
Global state.
Definition at line 69 of file validation.cpp.
Referenced by WalletModel::abandonTransaction(), CWallet::AbandonTransaction(), abandontransaction(), AcceptBlock(), AcceptBlockHeader(), AcceptToMemoryPoolWorker(), ActivateBestChain(), ActivateBestChainStep(), CGovernanceManager::AddGovernanceObject(), addmultisigaddress(), AppInitMain(), AutoBackupWallet(), CWallet::AutoLockMasternodeCollaterals(), CWallet::AvailableCoins(), backupwallet(), PeerLogicValidation::BlockChecked(), BOOST_FIXTURE_TEST_CASE(), BuildSimplifiedMNListDiff(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CMasternodeMan::Check(), CMasternode::Check(), CMasternodeMan::CheckAndRemove(), CMasternodePing::CheckAndUpdate(), CheckBlockIndex(), CMasternode::CheckCollateral(), CheckFinalTx(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), CMasternodeMan::CheckMasternode(), CGovernanceManager::CheckMasternodeOrphanObjects(), CGovernanceManager::CheckMasternodeOrphanVotes(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), CGovernanceManager::CheckPostponedObjects(), CheckSequenceLocks(), CMasternodePing::CMasternodePing(), CPrivateSendServer::CommitFinalTransaction(), CWallet::CommitTransaction(), ComputeBlockVersion(), ConnectBlock(), CWallet::ConvertList(), CWallet::CountInputsWithAmount(), CWallet::CreateCollateralTransaction(), CPrivateSendClientSession::CreateDenominated(), llmq::CDummyDKG::CreateDummyCommitment(), llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::CreateFinalCommitment(), BlockAssembler::CreateNewBlock(), CWallet::CreateTransaction(), decoderawtransaction(), TransactionTablePriv::describe(), DisconnectBlocks(), CPrivateSendClientSession::DoAutomaticDenominating(), dumpprivkey(), dumpwallet(), encryptwallet(), FindFilesToPrune(), FindFilesToPruneManual(), FlushStateToDisk(), TransactionDesc::FormatTxStatus(), CWallet::FundTransaction(), generateBlocks(), getaccount(), getaccountaddress(), getaddressesbyaccount(), CWallet::GetAllReserveKeys(), CWallet::GetAnonymizedBalance(), CWallet::GetAverageAnonymizedRounds(), getbalance(), CWallet::GetBalance(), getbestblockhash(), getblock(), getblockchaininfo(), getblockcount(), GetBlockHash(), getblockhash(), getblockheader(), getblockheaders(), getblocktemplate(), CMasternodePayments::GetBlockTxOuts(), getchaintips(), CWallet::GetCollateralTxDSIn(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), CWallet::GetDenominatedBalance(), CMerkleTx::GetDepthInMainChain(), getdifficulty(), getgovernanceinfo(), ClientModel::getHeaderTipHeight(), ClientModel::getHeaderTipTime(), CWallet::GetImmatureBalance(), CWallet::GetImmatureWatchOnlyBalance(), getinfo(), ClientModel::getLastBlockDate(), llmq::CQuorumBlockProcessor::GetMinableCommitment(), llmq::CQuorumBlockProcessor::GetMinableCommitmentTx(), getmininginfo(), CGovernanceManager::GetMinVoteTime(), getnetworkhashps(), getnetworkinfo(), getnewaddress(), GetNextMasternodeForPayment(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetNodeStateStats(), CWallet::GetNormalizedAnonymizedBalance(), ClientModel::getNumBlocks(), WalletModel::getOutputs(), llmq::CQuorumBlockProcessor::GetQuorumBlockHash(), getrawchangeaddress(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), GetRequiredPaymentsStrings(), getspecialtxes(), GetSpendHeight(), GetTransaction(), gettransaction(), TransactionTablePriv::getTxHex(), gettxout(), gettxoutproof(), getunconfirmedbalance(), CWallet::GetUnconfirmedBalance(), CWallet::GetUnconfirmedWatchOnlyBalance(), GetUTXOCoin(), GetUTXOConfirmations(), GetUTXOStats(), ClientModel::getVerificationProgress(), getwalletinfo(), CWallet::GetWatchOnlyBalance(), gobject_get(), gobject_submit(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), TransactionTablePriv::index(), CActiveDeterministicMasternodeManager::Init(), InitBlockIndex(), CDSNotificationInterface::InitializeCurrentBlockTip(), instantsendtoaddress(), InvalidateBlock(), invalidateblock(), CGovernanceObject::IsCollateralValid(), CPrivateSend::IsCollateralValid(), IsCurrentForFeeEstimation(), IsInitialBlockDownload(), WalletModel::isLockedCoin(), WalletModel::isSpent(), CMasternodePaymentVote::IsValid(), CTxLockRequest::IsValid(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), WalletModel::listCoins(), WalletModel::listLockedCoins(), listlockunspent(), ListObjects(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), LoadExternalBlockFile(), LoadMempool(), CWallet::LoadWallet(), WalletModel::lockCoin(), lockunspent(), CPrivateSendClientSession::MakeCollateralAmounts(), CWallet::MarkConflicted(), masternode_winners(), masternodelist(), movecmd(), PeerLogicValidation::NewPoWValidBlock(), CZMQPublishRawBlockNotifier::NotifyBlock(), NotifyHeaderTip(), ParseBlock(), WalletModel::pollBalanceChanged(), PreciousBlock(), preciousblock(), PrepareShutdown(), WalletModel::prepareTransaction(), prioritisetransaction(), llmq::CQuorumBlockProcessor::ProcessBlock(), CDeterministicMNManager::ProcessBlock(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), CInstantSend::ProcessMessage(), llmq::CDummyDKG::ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), ProcessMessage(), ProcessMessages(), ProcessNewBlock(), ProcessNewBlockHeaders(), CInstantSend::ProcessNewTxLockVote(), CInstantSend::ProcessOrphanTxLockVote(), CInstantSend::ProcessOrphanTxLockVotes(), CSporkManager::ProcessSpork(), CInstantSend::ProcessTxLockRequest(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), protx_diff(), protx_list(), pruneblockchain(), CWallet::ReacceptWalletTransactions(), reconsiderblock(), PeerTablePriv::refreshPeers(), TransactionTablePriv::refreshWallet(), removeprunedfunds(), ReprocessBlocks(), CGovernanceManager::RequestGovernanceObjectVotes(), CMasternodePayments::RequestLowDataPaymentBlocks(), resendwallettransactions(), ResetBlockFailureFlags(), CInstantSend::ResolveConflicts(), rest_block(), rest_getutxos(), rest_headers(), CWallet::ScanForWalletTransactions(), CWallet::SelectCoinsGroupedByAddresses(), SendBlockTransactions(), WalletModel::sendCoins(), sendfrom(), sendmany(), SendMessages(), sendrawtransaction(), SendRejectsAndCheckIfBanned(), sendtoaddress(), CMasternodeMan::SendVerifyReply(), setaccount(), setmocktime(), settxfee(), signmessage(), signrawtransaction(), CMasternodePing::SimpleCheck(), CMasternodeBroadcast::SimpleCheck(), TransactionRecord::statusUpdateNeeded(), submitblock(), CPrivateSendClientSession::SubmitDenominate(), CMasternodeMan::SyncAll(), CGovernanceManager::SyncAll(), CGovernanceManager::SyncSingleObjAndItsVotes(), PeerLogicValidation::SyncTransaction(), CInstantSend::SyncTransaction(), CPrivateSend::SyncTransaction(), CWallet::SyncTransaction(), TestBlockValidity(), TestLockPointValidity(), ThreadImport(), TransactionDesc::toHTML(), WalletModel::transactionCanBeAbandoned(), CInstantSend::TryToFinalizeLockCandidate(), llmq::CQuorumBlockProcessor::UndoBlock(), UnloadBlockIndex(), WalletModel::unlockCoin(), CMasternodeBroadcast::Update(), CGovernanceManager::UpdateCachesAndClean(), CActiveDeterministicMasternodeManager::UpdatedBlockTip(), CMasternodeMan::UpdateLastPaid(), CMasternode::UpdateLastPaid(), CGovernanceObject::UpdateLocalValidity(), CInstantSend::UpdateLockedTransaction(), TransactionRecord::updateStatus(), TransactionTablePriv::updateWallet(), validateaddress(), verifychain(), CVerifyDB::VerifyDB(), verifymessage(), verifytxoutproof(), VersionBitsTipState(), VersionBitsTipStateSinceHeight(), CInstantSend::Vote(), walletlock(), walletpassphrase(), and walletpassphrasechange().
csBestBlock
CWaitableCriticalSection csBestBlock
Definition at line 74 of file validation.cpp.
Referenced by getblocktemplate().
cvBlockChange
CConditionVariable cvBlockChange
Definition at line 75 of file validation.cpp.
Referenced by getblocktemplate(), OnRPCStopped(), and UpdateTip().
fAddressIndex
bool fAddressIndex = false
Definition at line 80 of file validation.cpp.
Referenced by AcceptToMemoryPoolWorker(), ConnectBlock(), DisconnectBlock(), GetAddressIndex(), GetAddressUnspent(), InitBlockIndex(), and LoadBlockIndexDB().
fAlerts
bool fAlerts = DEFAULT_ALERTS
Definition at line 92 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and ProcessMessage().
fCheckBlockIndex
bool fCheckBlockIndex = false
Definition at line 88 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and CheckBlockIndex().
fCheckpointsEnabled
bool fCheckpointsEnabled = DEFAULT_CHECKPOINTS_ENABLED
Definition at line 89 of file validation.cpp.
Referenced by AcceptBlockHeader(), AppInitParameterInteraction(), and TestBlockValidity().
fDIP0001ActiveAtTip
std::atomic<bool> fDIP0001ActiveAtTip {false}
Definition at line 95 of file validation.cpp.
Referenced by BlockAssembler::BlockAssembler(), getblocktemplate(), CConnman::OutboundTargetReached(), BlockAssembler::TestForBlock(), BlockAssembler::TestPackage(), and CDSNotificationInterface::UpdatedBlockTip().
fDIP0003ActiveAtTip
std::atomic<bool> fDIP0003ActiveAtTip {false}
Definition at line 96 of file validation.cpp.
fHavePruned
bool fHavePruned = false
Pruning-related variables and constants.
True if any block files have ever been pruned.
Definition at line 83 of file validation.cpp.
Referenced by AppInitMain(), CheckBlockIndex(), FlushStateToDisk(), getblock(), getspecialtxes(), LoadBlockIndexDB(), rest_block(), and UnloadBlockIndex().
fIsBareMultisigStd
bool fIsBareMultisigStd = DEFAULT_PERMIT_BAREMULTISIG
Definition at line 85 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and IsStandardTx().
fPruneMode
bool fPruneMode = false
True if we're running in -prune mode.
Definition at line 84 of file validation.cpp.
Referenced by AppInitMain(), AppInitParameterInteraction(), CWallet::CreateWalletFromFile(), FindBlockPos(), FindFilesToPruneManual(), FindUndoPos(), FlushStateToDisk(), getblockchaininfo(), importaddress(), importelectrumwallet(), importprivkey(), importpubkey(), importwallet(), ProcessMessage(), pruneblockchain(), and CVerifyDB::VerifyDB().
fReindex
bool fReindex = false
Definition at line 78 of file validation.cpp.
Referenced by AppInitMain(), FlushStateToDisk(), ClientModel::getBlockSource(), CWallet::GetMasternodeOutpointAndKeys(), CWallet::GetOutpointAndKeysFromOutput(), InitBlockIndex(), IsInitialBlockDownload(), LoadBlockIndex(), LoadBlockIndexDB(), masternodebroadcast(), ProcessMessage(), SendMessages(), and ThreadImport().
fRequireStandard
bool fRequireStandard = true
Definition at line 86 of file validation.cpp.
Referenced by AcceptToMemoryPoolWorker(), and AppInitParameterInteraction().
fSpentIndex
bool fSpentIndex = false
Definition at line 82 of file validation.cpp.
Referenced by AcceptToMemoryPoolWorker(), ConnectBlock(), DisconnectBlock(), GetSpentIndex(), InitBlockIndex(), and LoadBlockIndexDB().
fTimestampIndex
bool fTimestampIndex = false
Definition at line 81 of file validation.cpp.
Referenced by ConnectBlock(), GetTimestampIndex(), InitBlockIndex(), and LoadBlockIndexDB().
fTxIndex
bool fTxIndex = true
Definition at line 79 of file validation.cpp.
Referenced by AppInitMain(), ConnectBlock(), getrawtransaction(), GetTransaction(), InitBlockIndex(), and LoadBlockIndexDB().
hashAssumeValid
uint256 hashAssumeValid
Block hash whose ancestors we will assume to have valid scripts without checking them.
Definition at line 98 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and ConnectBlock().
instance_of_cmaincleanup
class CMainCleanup instance_of_cmaincleanup
mapBlockIndex
BlockMap mapBlockIndex
Definition at line 71 of file validation.cpp.
Referenced by AcceptBlockHeader(), AddToBlockIndex(), CWallet::AddToWallet(), AlreadyHave(), AppInitMain(), BuildSimplifiedMNListDiff(), CMasternodePing::CheckAndUpdate(), CheckBlockIndex(), llmq::CheckLLMQCommitment(), ConnectBlock(), FindForkInGlobalIndex(), getblock(), getblockheader(), getblockheaders(), getblocktemplate(), getchaintips(), CMerkleTx::GetDepthInMainChain(), CWallet::GetKeyBirthTimes(), Checkpoints::GetLastCheckpoint(), getspecialtxes(), GetSpendHeight(), gettxout(), gettxoutproof(), GetUTXOStats(), importprunedfunds(), InsertBlockIndex(), InvalidateBlock(), invalidateblock(), CGovernanceObject::IsCollateralValid(), listsinceblock(), LoadBlockIndexDB(), LoadExternalBlockFile(), CWallet::MarkConflicted(), preciousblock(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), ProcessMessage(), PruneOneBlockFile(), reconsiderblock(), ReprocessBlocks(), ResetBlockFailureFlags(), rest_block(), rest_headers(), SendMessages(), CMasternodePing::SimpleCheck(), submitblock(), TxToJSON(), UnloadBlockIndex(), TransactionRecord::updateStatus(), verifytxoutproof(), WalletTxToJSON(), and CMainCleanup::~CMainCleanup().
maxTxFee
CAmount maxTxFee = DEFAULT_TRANSACTION_MAXFEE
Absolute maximum transaction fee (in duffs) used by wallet and mempool (rejects high fee in sendrawtransaction)
Definition at line 101 of file validation.cpp.
Referenced by CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CPrivateSendServer::CommitFinalTransaction(), CWallet::CommitTransaction(), CWallet::GetMinimumFee(), CPrivateSend::IsCollateralValid(), CWallet::ParameterInteraction(), WalletModel::prepareTransaction(), SendCoinsDialog::processSendCoinsReturn(), CWallet::ReacceptWalletTransactions(), CWalletTx::RelayWalletTransaction(), CWallet::SelectCoinsMinConf(), and sendrawtransaction().
mempool
CTxMemPool mempool(::minRelayTxFee)
Referenced by CMerkleTx::AcceptToMemoryPool(), ActivateBestChain(), ActivateBestChainStep(), BlockAssembler::addPackageTxs(), BlockAssembler::addPriorityTxs(), BlockAssembler::AddToBlock(), AlreadyHave(), AppInitMain(), AppInitParameterInteraction(), CInstantSend::CanAutoLock(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CheckSequenceLocks(), CPrivateSendServer::CommitFinalTransaction(), ConnectTip(), BlockAssembler::CreateNewBlock(), CWallet::CreateTransaction(), DisconnectTip(), DumpMempool(), entryToJSON(), estimatefee(), estimatepriority(), estimatesmartfee(), estimatesmartpriority(), FlushStateToDisk(), getaddressmempool(), getblocktemplate(), CMerkleTx::GetDepthInMainChain(), getmempoolancestors(), getmempooldescendants(), ClientModel::getMempoolDynamicUsage(), getmempoolentry(), ClientModel::getMempoolSize(), getmininginfo(), GetSpentIndex(), GetTransaction(), gettxout(), CWalletTx::InMempool(), InvalidateBlock(), CPrivateSend::IsCollateralValid(), BlockAssembler::isStillDependent(), LoadMempool(), mempoolInfoToJSON(), mempoolToJSON(), PrepareShutdown(), prioritisetransaction(), ProcessGetData(), ProcessMessage(), CInstantSend::ProcessNewTxLockVote(), CInstantSend::ProcessTxLockRequest(), CWallet::ReacceptWalletTransactions(), CInstantSend::ResolveConflicts(), rest_getutxos(), CWallet::SelectCoinsMinConf(), SendMessages(), sendrawtransaction(), signrawtransaction(), BlockAssembler::SkipMapTxEntry(), UnloadBlockIndex(), CoinControlDialog::updateLabels(), BlockAssembler::UpdatePackagesForAdded(), SendCoinsDialog::updateSmartFeeLabel(), UpdateTip(), and CInstantSend::Vote().
MEMPOOL_DUMP_VERSION
const uint64_t MEMPOOL_DUMP_VERSION = 1 static
Definition at line 4503 of file validation.cpp.
Referenced by DumpMempool(), and LoadMempool().
minRelayTxFee
CFeeRate minRelayTxFee = CFeeRate(DEFAULT_MIN_RELAY_TX_FEE)
A fee rate smaller than this is considered zero fee (for relaying, mining and transaction creation)
Definition at line 100 of file validation.cpp.
Referenced by AcceptToMemoryPoolWorker(), AppInitParameterInteraction(), CWallet::CreateTransaction(), CTxOut::GetDustThreshold(), getinfo(), getnetworkinfo(), CWallet::GetRequiredFee(), CTxOut::IsDust(), and CWallet::ParameterInteraction().
nBytesPerSigOp
unsigned int nBytesPerSigOp = DEFAULT_BYTES_PER_SIGOP
Definition at line 87 of file validation.cpp.
Referenced by AcceptToMemoryPoolWorker(), and AppInitParameterInteraction().
nCoinCacheUsage
size_t nCoinCacheUsage = 5000 * 300
Definition at line 90 of file validation.cpp.
Referenced by AppInitMain(), FlushStateToDisk(), and CVerifyDB::VerifyDB().
nMaxTipAge
int64_t nMaxTipAge = DEFAULT_MAX_TIP_AGE
If the tip is older than this (in seconds), the node is considered to be in initial block download.
Definition at line 93 of file validation.cpp.
Referenced by AppInitParameterInteraction(), IsInitialBlockDownload(), ProcessMessage(), and SendMessages().
nPruneTarget
uint64_t nPruneTarget = 0
Number of MiB of block files that we're trying to stay below.
Definition at line 91 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and FindFilesToPrune().
nScriptCheckThreads
int nScriptCheckThreads = 0
Definition at line 76 of file validation.cpp.
Referenced by AppInitMain(), AppInitParameterInteraction(), and ConnectBlock().
nTimeCallbacks
int64_t nTimeCallbacks = 0 static
Definition at line 1915 of file validation.cpp.
Referenced by ConnectBlock().
nTimeChainState
int64_t nTimeChainState = 0 static
Definition at line 2589 of file validation.cpp.
Referenced by ConnectTip().
nTimeCheck
int64_t nTimeCheck = 0 static
Definition at line 1909 of file validation.cpp.
Referenced by ConnectBlock().
nTimeConnect
int64_t nTimeConnect = 0 static
Definition at line 1913 of file validation.cpp.
Referenced by ConnectBlock().
nTimeConnectTotal
int64_t nTimeConnectTotal = 0 static
Definition at line 2587 of file validation.cpp.
Referenced by ConnectTip().
nTimeFlush
int64_t nTimeFlush = 0 static
Definition at line 2588 of file validation.cpp.
Referenced by ConnectTip().
nTimeForks
int64_t nTimeForks = 0 static
Definition at line 1910 of file validation.cpp.
Referenced by ConnectBlock().
nTimeIndex
int64_t nTimeIndex = 0 static
Definition at line 1914 of file validation.cpp.
Referenced by ConnectBlock().
nTimePayeeAndSpecial
int64_t nTimePayeeAndSpecial = 0 static
Definition at line 1912 of file validation.cpp.
Referenced by ConnectBlock().
nTimePostConnect
int64_t nTimePostConnect = 0 static
Definition at line 2590 of file validation.cpp.
Referenced by ConnectTip().
nTimeReadFromDisk
int64_t nTimeReadFromDisk = 0 static
Definition at line 2586 of file validation.cpp.
Referenced by ConnectTip().
nTimeTotal
int64_t nTimeTotal = 0 static
Definition at line 1916 of file validation.cpp.
Referenced by ConnectTip().
nTimeVerify
int64_t nTimeVerify = 0 static
Definition at line 1911 of file validation.cpp.
Referenced by ConnectBlock().
pblocktree
CBlockTreeDB* pblocktree = NULL
Global variable that points to the active block tree (protected by cs_main)
Definition at line 228 of file validation.cpp.
Referenced by AppInitMain(), ConnectBlock(), DisconnectBlock(), FlushStateToDisk(), GetAddressIndex(), GetAddressUnspent(), GetSpentIndex(), GetTimestampIndex(), GetTransaction(), InitBlockIndex(), LoadBlockIndexDB(), PrepareShutdown(), and ThreadImport().
pcoinsdbview
CCoinsViewDB* pcoinsdbview = NULL
Global variable that points to the coins database (protected by cs_main)
Definition at line 226 of file validation.cpp.
Referenced by AppInitMain(), gettxoutsetinfo(), and PrepareShutdown().
pcoinsTip
CCoinsViewCache* pcoinsTip = NULL
Global variable that points to the active CCoinsView (protected by cs_main)
Definition at line 227 of file validation.cpp.
Referenced by AcceptToMemoryPoolWithTime(), AcceptToMemoryPoolWorker(), ActivateBestChainStep(), AlreadyHave(), AppInitMain(), CheckSequenceLocks(), ConnectTip(), DisconnectTip(), FlushStateToDisk(), GetTransaction(), gettxout(), gettxoutproof(), GetUTXOCoin(), InvalidateBlock(), LimitMempoolSize(), LoadBlockIndexDB(), PrepareShutdown(), ProcessMessage(), rest_getutxos(), sendrawtransaction(), signrawtransaction(), TestBlockValidity(), TransactionDesc::toHTML(), UpdateTip(), verifychain(), and CVerifyDB::VerifyDB().
pindexBestForkBase
CBlockIndex * pindexBestForkBase = NULL
Definition at line 1244 of file validation.cpp.
Referenced by CheckForkWarningConditions(), and CheckForkWarningConditionsOnNewFork().
pindexBestForkTip
CBlockIndex* pindexBestForkTip = NULL
Definition at line 1244 of file validation.cpp.
Referenced by CheckForkWarningConditions(), and CheckForkWarningConditionsOnNewFork().
pindexBestHeader
CBlockIndex* pindexBestHeader = NULL
Best header we've seen so far (used for getheaders queries' starting points).
Definition at line 73 of file validation.cpp.
Referenced by AddToBlockIndex(), ConnectBlock(), getblockchaininfo(), ClientModel::getHeaderTipHeight(), ClientModel::getHeaderTipTime(), InvalidateBlock(), IsCurrentForFeeEstimation(), LoadBlockIndexDB(), CMasternodeSync::NotifyHeaderTip(), NotifyHeaderTip(), ProcessGetData(), ProcessMessage(), SendMessages(), UnloadBlockIndex(), and CMasternodeSync::UpdatedBlockTip().
scriptcheckqueue
CCheckQueue<CScriptCheck> scriptcheckqueue(128) static
Referenced by ConnectBlock(), and ThreadScriptCheck().
strMessageMagic
const std::string strMessageMagic = "DarkCoin Signed Message:\n"
Definition at line 111 of file validation.cpp.
Referenced by CSporkMessage::GetSignerKeyID(), SignVerifyMessageDialog::on_signMessageButton_SM_clicked(), SignVerifyMessageDialog::on_verifyMessageButton_VM_clicked(), CMessageSigner::SignMessage(), signmessage(), signmessagewithprivkey(), CMessageSigner::VerifyMessage(), and verifymessage().
versionbitscache
VersionBitsCache versionbitscache
Definition at line 1822 of file validation.cpp.
Referenced by CheckSpecialTx(), ComputeBlockVersion(), ConnectBlock(), ContextualCheckBlock(), ContextualCheckTransaction(), BlockAssembler::CreateNewBlock(), DisconnectBlock(), getblocktemplate(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), llmq::CQuorumBlockProcessor::ProcessBlock(), CDeterministicMNManager::ProcessBlock(), ProcessMessage(), ThreadImport(), UnloadBlockIndex(), CDSNotificationInterface::UpdatedBlockTip(), llmq::CDummyDKG::UpdatedBlockTip(), VersionBitsTipState(), and VersionBitsTipStateSinceHeight().
warningcache
ThresholdConditionCache warningcache[VERSIONBITS_NUM_BITS] static
Definition at line 1907 of file validation.cpp.
Referenced by UnloadBlockIndex(), and UpdateTip().
Released under the MIT license