Dash Core: src/validation.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
validation.h File Reference
#include "amount.h"
#include "chain.h"
#include "coins.h"
#include "protocol.h"
#include "script/script_error.h"
#include "sync.h"
#include "versionbits.h"
#include "spentindex.h"
#include <algorithm>
#include <exception>
#include <map>
#include <set>
#include <stdint.h>
#include <string>
#include <utility>
#include <vector>
#include <atomic>
#include <boost/unordered_map.hpp>
#include <boost/filesystem/path.hpp>
Classes
struct BlockHasher
class CScriptCheck
Closure representing one script verification Note that this stores references to the spending transaction.
class CVerifyDB
RAII wrapper for VerifyDB: Verify consistency of the block and coin databases.
Namespaces
Consensus
Typedefs
typedef boost::unordered_map< uint256, CBlockIndex *, BlockHasher > BlockMap
Functions
bool ProcessNewBlock (const CChainParams &chainparams, const std::shared_ptr< const CBlock > pblock, bool fForceProcessing, bool *fNewBlock)
Process an incoming block.
bool ProcessNewBlockHeaders (const std::vector< CBlockHeader > &block, CValidationState &state, const CChainParams &chainparams, const CBlockIndex **ppindex=NULL)
Process incoming block headers.
bool CheckDiskSpace (uint64_t nAdditionalBytes=0)
Check whether enough disk space is available for an incoming block.
FILE * OpenBlockFile (const CDiskBlockPos &pos, bool fReadOnly=false)
Open a block file (blk?????.dat)
FILE * OpenUndoFile (const CDiskBlockPos &pos, bool fReadOnly=false)
Open an undo file (rev?????.dat)
boost::filesystem::path GetBlockPosFilename (const CDiskBlockPos &pos, const char *prefix)
Translation to a filesystem path.
bool LoadExternalBlockFile (const CChainParams &chainparams, FILE *fileIn, CDiskBlockPos *dbp=NULL)
Import blocks from an external file.
bool InitBlockIndex (const CChainParams &chainparams)
Initialize a new block tree database + block data on disk.
bool LoadBlockIndex (const CChainParams &chainparams)
Load the block tree and coins database from disk.
void UnloadBlockIndex ()
Unload database information.
void ThreadScriptCheck ()
Run an instance of the script checking thread.
bool IsInitialBlockDownload ()
Check whether we are doing an initial block download (synchronizing from disk or network)
std::string GetWarnings (const std::string &strFor)
Format a string that describes several potential problems detected by the core.
bool GetTransaction (const uint256 &hash, CTransactionRef &tx, const Consensus::Params &params, uint256 &hashBlock, bool fAllowSlow=false)
Retrieve a transaction (from memory pool, or from disk, if possible)
bool ActivateBestChain (CValidationState &state, const CChainParams &chainparams, std::shared_ptr< const CBlock > pblock=std::shared_ptr< const CBlock >())
Find the best known block, and make it the tip of the block chain.
double ConvertBitsToDouble (unsigned int nBits)
CAmount GetBlockSubsidy (int nBits, int nHeight, const Consensus::Params &consensusParams, bool fSuperblockPartOnly=false)
CAmount GetMasternodePayment (int nHeight, CAmount blockValue)
double GuessVerificationProgress (const ChainTxData &data, CBlockIndex *pindex)
Guess verification progress (as a fraction between 0.0=genesis and 1.0=current tip).
void FindFilesToPrune (std::set< int > &setFilesToPrune, uint64_t nPruneAfterHeight)
Prune block and undo files (blk???.dat and undo???.dat) so that the disk space used is less than a user-defined target.
void PruneOneBlockFile (const int fileNumber)
Mark one block file as pruned.
void UnlinkPrunedFiles (const std::set< int > &setFilesToPrune)
Actually unlink the specified files.
CBlockIndex * InsertBlockIndex (uint256 hash)
Create a new block index entry for a given block hash.
void FlushStateToDisk ()
Flush all state, indexes and buffers to disk.
void PruneAndFlush ()
Prune block files and flush state to disk.
void PruneBlockFilesManual (int nPruneUpToHeight)
Prune block files up to a given height.
bool AcceptToMemoryPool (CTxMemPool &pool, CValidationState &state, const CTransactionRef &tx, bool fLimitFree, bool *pfMissingInputs, bool fOverrideMempoolLimit=false, const CAmount nAbsurdFee=0, bool fDryRun=false)
(try to) add transaction to memory pool
bool AcceptToMemoryPoolWithTime (CTxMemPool &pool, CValidationState &state, const CTransactionRef &tx, bool fLimitFree, bool *pfMissingInputs, int64_t nAcceptTime, bool fOverrideMempoolLimit=false, const CAmount nAbsurdFee=0, bool fDryRun=false)
(try to) add transaction to memory pool with a specified acceptance time
bool GetUTXOCoin (const COutPoint &outpoint, Coin &coin)
int GetUTXOHeight (const COutPoint &outpoint)
int GetUTXOConfirmations (const COutPoint &outpoint)
std::string FormatStateMessage (const CValidationState &state)
Convert CValidationState to a human-readable message for logging.
ThresholdState VersionBitsTipState (const Consensus::Params &params, Consensus::DeploymentPos pos)
Get the BIP9 state for a given deployment at the current tip.
int VersionBitsTipStateSinceHeight (const Consensus::Params &params, Consensus::DeploymentPos pos)
Get the block height at which the BIP9 deployment switched into the state for the block building on the current tip.
unsigned int GetLegacySigOpCount (const CTransaction &tx)
Count ECDSA signature operations the old-fashioned (pre-0.6) way.
unsigned int GetP2SHSigOpCount (const CTransaction &tx, const CCoinsViewCache &mapInputs)
Count ECDSA signature operations in pay-to-script-hash inputs.
bool CheckInputs (const CTransaction &tx, CValidationState &state, const CCoinsViewCache &view, bool fScriptChecks, unsigned int flags, bool cacheStore, std::vector< CScriptCheck > *pvChecks=NULL)
Check whether all inputs of this transaction are valid (no double spends, scripts & sigs, amounts) This does not modify the UTXO set.
void UpdateCoins (const CTransaction &tx, CCoinsViewCache &inputs, int nHeight)
Apply the effects of this transaction on the UTXO set represented by view.
bool CheckTransaction (const CTransaction &tx, CValidationState &state)
Transaction validation functions.
bool Consensus::CheckTxInputs (const CTransaction &tx, CValidationState &state, const CCoinsViewCache &inputs, int nSpendHeight)
Check whether all inputs of this transaction are valid (no double spends and amounts) This does not modify the UTXO set.
bool IsFinalTx (const CTransaction &tx, int nBlockHeight, int64_t nBlockTime)
Check if transaction is final and can be included in a block with the specified height and time.
bool CheckFinalTx (const CTransaction &tx, int flags=-1)
Check if transaction will be final in the next block to be created.
bool TestLockPointValidity (const LockPoints *lp)
Test whether the LockPoints height and time are still valid on the current chain.
bool SequenceLocks (const CTransaction &tx, int flags, std::vector< int > *prevHeights, const CBlockIndex &block)
Check if transaction is final per BIP 68 sequence numbers and can be included in a block.
bool CheckSequenceLocks (const CTransaction &tx, int flags, LockPoints *lp=NULL, bool useExistingLockPoints=false)
Check if transaction will be BIP 68 final in the next block to be created.
bool GetTimestampIndex (const unsigned int &high, const unsigned int &low, std::vector< uint256 > &hashes)
bool GetSpentIndex (CSpentIndexKey &key, CSpentIndexValue &value)
bool GetAddressIndex (uint160 addressHash, int type, std::vector< std::pair< CAddressIndexKey, CAmount > > &addressIndex, int start=0, int end=0)
bool GetAddressUnspent (uint160 addressHash, int type, std::vector< std::pair< CAddressUnspentKey, CAddressUnspentValue > > &unspentOutputs)
bool WriteBlockToDisk (const CBlock &block, CDiskBlockPos &pos, const CMessageHeader::MessageStartChars &messageStart)
Functions for disk access for blocks.
bool ReadBlockFromDisk (CBlock &block, const CDiskBlockPos &pos, const Consensus::Params &consensusParams)
bool ReadBlockFromDisk (CBlock &block, const CBlockIndex *pindex, const Consensus::Params &consensusParams)
bool DisconnectBlocks (int blocks)
Functions for validating blocks and updating the block tree.
void ReprocessBlocks (int nBlocks)
bool CheckBlockHeader (const CBlockHeader &block, CValidationState &state, const Consensus::Params &consensusParams, bool fCheckPOW=true)
Context-independent validity checks.
bool CheckBlock (const CBlock &block, CValidationState &state, const Consensus::Params &consensusParams, bool fCheckPOW=true, bool fCheckMerkleRoot=true)
bool ContextualCheckBlockHeader (const CBlockHeader &block, CValidationState &state, const Consensus::Params &consensusParams, const CBlockIndex *pindexPrev, int64_t nAdjustedTime)
Context-dependent validity checks.
bool ContextualCheckBlock (const CBlock &block, CValidationState &state, const Consensus::Params &consensusParams, const CBlockIndex *pindexPrev)
bool TestBlockValidity (CValidationState &state, const CChainParams &chainparams, const CBlock &block, CBlockIndex *pindexPrev, bool fCheckPOW=true, bool fCheckMerkleRoot=true)
Check a block is completely valid from start to finish (only works on top of our current best block, with cs_main held)
CBlockIndex * FindForkInGlobalIndex (const CChain &chain, const CBlockLocator &locator)
Find the last common block between the parameter chain and a locator.
bool PreciousBlock (CValidationState &state, const CChainParams &params, CBlockIndex *pindex)
Mark a block as precious and reorganize.
bool InvalidateBlock (CValidationState &state, const CChainParams &chainparams, CBlockIndex *pindex)
Mark a block as invalid.
bool ResetBlockFailureFlags (CBlockIndex *pindex)
Remove invalidity status from a block and its descendants.
int GetSpendHeight (const CCoinsViewCache &inputs)
Return the spend height, which is one more than the inputs.GetBestBlock().
int32_t ComputeBlockVersion (const CBlockIndex *pindexPrev, const Consensus::Params &params, bool fCheckMasternodesUpgraded=false)
Determine what nVersion a new block should use.
bool GetBlockHash (uint256 &hashRet, int nBlockHeight=-1)
Return true if hash can be found in chainActive at nBlockHeight height.
CBlockFileInfo * GetBlockFileInfo (size_t n)
Get block file info entry for one block file.
void DumpMempool ()
Dump the mempool to disk.
bool LoadMempool ()
Load the mempool from disk.
Variables
static const bool DEFAULT_ALERTS = true
Default for accepting alerts from the P2P network.
static const bool DEFAULT_WHITELISTRELAY = true
Default for DEFAULT_WHITELISTRELAY.
static const bool DEFAULT_WHITELISTFORCERELAY = true
Default for DEFAULT_WHITELISTFORCERELAY.
static const unsigned int DEFAULT_MIN_RELAY_TX_FEE = 1000
Default for -minrelaytxfee, minimum relay fee for transactions.
static const CAmount DEFAULT_TRANSACTION_MAXFEE = 0.1 * COIN
-maxtxfee default
static const CAmount HIGH_TX_FEE_PER_KB = 0.01 * COIN
Discourage users to set fees higher than this amount (in duffs) per kB.
static const CAmount HIGH_MAX_TX_FEE = 100 * HIGH_TX_FEE_PER_KB
-maxtxfee will warn if called with a higher fee than this amount (in duffs)
static const unsigned int DEFAULT_ANCESTOR_LIMIT = 25
Default for -limitancestorcount, max number of in-mempool ancestors.
static const unsigned int DEFAULT_ANCESTOR_SIZE_LIMIT = 101
Default for -limitancestorsize, maximum kilobytes of tx + all in-mempool ancestors.
static const unsigned int DEFAULT_DESCENDANT_LIMIT = 25
Default for -limitdescendantcount, max number of in-mempool descendants.
static const unsigned int DEFAULT_DESCENDANT_SIZE_LIMIT = 101
Default for -limitdescendantsize, maximum kilobytes of in-mempool descendants.
static const unsigned int DEFAULT_MEMPOOL_EXPIRY = 336
Default for -mempoolexpiry, expiration time for mempool transactions in hours.
static const unsigned int MAX_BLOCKFILE_SIZE = 0x8000000
The maximum size of a blk?????.dat file (since 0.8)
static const unsigned int BLOCKFILE_CHUNK_SIZE = 0x1000000
The pre-allocation chunk size for blk?????.dat files (since 0.8)
static const unsigned int UNDOFILE_CHUNK_SIZE = 0x100000
The pre-allocation chunk size for rev?????.dat files (since 0.8)
static const int MAX_SCRIPTCHECK_THREADS = 16
Maximum number of script-checking threads allowed.
static const int DEFAULT_SCRIPTCHECK_THREADS = 0
-par default (number of script-checking threads, 0 = auto)
static const int MAX_BLOCKS_IN_TRANSIT_PER_PEER = 16
Number of blocks that can be requested at any given time from a single peer.
static const unsigned int BLOCK_STALLING_TIMEOUT = 2
Timeout in seconds during which a peer must stall block download progress before being disconnected.
static const unsigned int MAX_HEADERS_RESULTS = 2000
Number of headers sent in one getheaders result.
static const int MAX_CMPCTBLOCK_DEPTH = 5
Maximum depth of blocks we're willing to serve as compact blocks to peers when requested.
static const int MAX_BLOCKTXN_DEPTH = 10
Maximum depth of blocks we're willing to respond to GETBLOCKTXN requests for.
static const unsigned int BLOCK_DOWNLOAD_WINDOW = 1024
Size of the "block download window": how far ahead of our current height do we fetch? Larger windows tolerate larger download speed differences between peer, but increase the potential degree of disordering of blocks on disk (which make reindexing and in the future perhaps pruning harder).
static const unsigned int DATABASE_WRITE_INTERVAL = 60 * 60
Time to wait (in seconds) between writing blocks/block index to disk.
static const unsigned int DATABASE_FLUSH_INTERVAL = 24 * 60 * 60
Time to wait (in seconds) between flushing chainstate to disk.
static const unsigned int MAX_REJECT_MESSAGE_LENGTH = 111
Maximum length of reject messages.
static const unsigned int AVG_LOCAL_ADDRESS_BROADCAST_INTERVAL = 24 * 24 * 60
Average delay between local address broadcasts in seconds.
static const unsigned int AVG_ADDRESS_BROADCAST_INTERVAL = 30
Average delay between peer address broadcasts in seconds.
static const unsigned int INVENTORY_BROADCAST_INTERVAL = 5
Average delay between trickled inventory transmissions in seconds.
static const unsigned int INVENTORY_BROADCAST_MAX_PER_1MB_BLOCK = 4 * 7 * INVENTORY_BROADCAST_INTERVAL
Maximum number of inventory items to send per transmission.
static const int64_t BLOCK_DOWNLOAD_TIMEOUT_BASE = 1000000
Block download timeout base, expressed in millionths of the block interval (i.e.
static const int64_t BLOCK_DOWNLOAD_TIMEOUT_PER_PEER = 500000
Additional block download timeout per parallel downloading peer (i.e.
static const unsigned int DEFAULT_LIMITFREERELAY = 0
static const bool DEFAULT_RELAYPRIORITY = true
static const int64_t DEFAULT_MAX_TIP_AGE = 6 * 60 * 60
static const int64_t MAX_FEE_ESTIMATION_TIP_AGE = 3 * 60 * 60
Maximum age of our tip in seconds for us to be considered current for fee estimation.
static const bool DEFAULT_PERMIT_BAREMULTISIG = true
Default for -permitbaremultisig.
static const unsigned int DEFAULT_BYTES_PER_SIGOP = 20
static const bool DEFAULT_CHECKPOINTS_ENABLED = true
static const bool DEFAULT_TXINDEX = true
static const bool DEFAULT_ADDRESSINDEX = false
static const bool DEFAULT_TIMESTAMPINDEX = false
static const bool DEFAULT_SPENTINDEX = false
static const unsigned int DEFAULT_BANSCORE_THRESHOLD = 100
static const unsigned int MAX_BLOCKS_TO_ANNOUNCE = 8
Maximum number of headers to announce when relaying blocks with headers message.
static const int MAX_UNCONNECTING_HEADERS = 10
Maximum number of unconnecting headers announcements before DoS score.
static const bool DEFAULT_PEERBLOOMFILTERS = true
CScript COINBASE_FLAGS
Constant stuff for coinbase transactions we create:
CCriticalSection cs_main
Global state.
CTxMemPool mempool
BlockMap mapBlockIndex
uint64_t nLastBlockTx
uint64_t nLastBlockSize
const std::string strMessageMagic
CWaitableCriticalSection csBestBlock
CConditionVariable cvBlockChange
std::atomic_bool fImporting
bool fReindex
int nScriptCheckThreads
bool fTxIndex
bool fIsBareMultisigStd
bool fRequireStandard
unsigned int nBytesPerSigOp
bool fCheckBlockIndex
bool fCheckpointsEnabled
size_t nCoinCacheUsage
CFeeRate minRelayTxFee
A fee rate smaller than this is considered zero fee (for relaying, mining and transaction creation)
CAmount maxTxFee
Absolute maximum transaction fee (in duffs) used by wallet and mempool (rejects high fee in sendrawtransaction)
bool fAlerts
int64_t nMaxTipAge
If the tip is older than this (in seconds), the node is considered to be in initial block download.
bool fLargeWorkForkFound
bool fLargeWorkInvalidChainFound
std::map< uint256, int64_t > mapRejectedBlocks
std::atomic< bool > fDIP0001ActiveAtTip
uint256 hashAssumeValid
Block hash whose ancestors we will assume to have valid scripts without checking them.
CBlockIndex * pindexBestHeader
Best header we've seen so far (used for getheaders queries' starting points).
static const uint64_t nMinDiskSpace = 52428800
Minimum disk space required - used in CheckDiskSpace()
bool fHavePruned
Pruning-related variables and constants.
bool fPruneMode
True if we're running in -prune mode.
uint64_t nPruneTarget
Number of MiB of block files that we're trying to stay below.
static const unsigned int MIN_BLOCKS_TO_KEEP = 288
Block files containing a block-height within MIN_BLOCKS_TO_KEEP of chainActive.Tip() will not be pruned.
static const signed int DEFAULT_CHECKBLOCKS = 6
static const unsigned int DEFAULT_CHECKLEVEL = 3
static const uint64_t MIN_DISK_SPACE_FOR_BLOCK_FILES = 945 * 1024 * 1024
CChain chainActive
The currently-connected chain of blocks (protected by cs_main).
CCoinsViewDB * pcoinsdbview
Global variable that points to the coins database (protected by cs_main)
CCoinsViewCache * pcoinsTip
Global variable that points to the active CCoinsView (protected by cs_main)
CBlockTreeDB * pblocktree
Global variable that points to the active block tree (protected by cs_main)
VersionBitsCache versionbitscache
static const unsigned int REJECT_INTERNAL = 0x100
Reject codes greater or equal to this can be returned by AcceptToMemPool for transactions, to signal internal conditions.
static const unsigned int REJECT_HIGHFEE = 0x100
Too high fee.
static const unsigned int REJECT_ALREADY_KNOWN = 0x101
Transaction is already known (either in mempool or blockchain)
static const unsigned int REJECT_CONFLICT = 0x102
Transaction conflicts with a transaction already known.
Typedef Documentation
BlockMap
typedef boost::unordered_map<uint256, CBlockIndex*, BlockHasher> BlockMap
Definition at line 159 of file validation.h.
Function Documentation
AcceptToMemoryPool()
bool AcceptToMemoryPool (CTxMemPool & pool, CValidationState & state, const CTransactionRef & tx, bool fLimitFree, bool * pfMissingInputs, bool fOverrideMempoolLimit = false, const CAmount nAbsurdFee = 0, bool fDryRun = false)
(try to) add transaction to memory pool
Definition at line 944 of file validation.cpp.
References AcceptToMemoryPoolWithTime(), and GetTime().
Referenced by CMerkleTx::AcceptToMemoryPool(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CPrivateSendServer::CommitFinalTransaction(), DisconnectTip(), CPrivateSend::IsCollateralValid(), ProcessMessage(), and sendrawtransaction().
AcceptToMemoryPoolWithTime()
bool AcceptToMemoryPoolWithTime (CTxMemPool & pool, CValidationState & state, const CTransactionRef & tx, bool fLimitFree, bool * pfMissingInputs, int64_t nAcceptTime, bool fOverrideMempoolLimit = false, const CAmount nAbsurdFee = 0, bool fDryRun = false)
(try to) add transaction to memory pool with a specified acceptance time
Definition at line 927 of file validation.cpp.
References AcceptToMemoryPoolWorker(), FLUSH_STATE_PERIODIC, FlushStateToDisk(), CValidationState::GetDebugMessage(), CValidationState::GetRejectReason(), LogPrint, pcoinsTip, and CCoinsViewCache::Uncache().
Referenced by AcceptToMemoryPool(), and LoadMempool().
ActivateBestChain()
bool ActivateBestChain (CValidationState & state, const CChainParams & chainparams, std::shared_ptr< const CBlock > pblock)
Find the best known block, and make it the tip of the block chain.
Find the best known block, and make it the tip of the block chain.
The result is either failure or an activated best chain. pblock is either NULL or a pointer to a block that is already loaded (to avoid loading it again from disk).
Definition at line 2879 of file validation.cpp.
References ActivateBestChainStep(), ConnectTrace::blocksConnected, chainActive, CheckBlockIndex(), cs_main, CChain::FindFork(), FindMostWorkChain(), FLUSH_STATE_PERIODIC, FlushStateToDisk(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), GetMainSignals(), IsInitialBlockDownload(), LOCK, mempool, CClientUIInterface::NotifyBlockTip, ShutdownRequested(), CMainSignals::SyncTransaction, CChain::Tip(), uiInterface, CMainSignals::UpdatedBlockTip, and CBlock::vtx.
Referenced by invalidateblock(), LoadExternalBlockFile(), PreciousBlock(), ProcessGetData(), ProcessMessage(), ProcessNewBlock(), reconsiderblock(), ReprocessBlocks(), and ThreadImport().
CheckBlock()
bool CheckBlock (const CBlock & block, CValidationState & state, const Consensus::Params & consensusParams, bool fCheckPOW = true, bool fCheckMerkleRoot = true)
Definition at line 3260 of file validation.cpp.
References BlockMerkleRoot(), CheckBlockHeader(), CheckTransaction(), CValidationState::DoS(), CBlock::fChecked, CValidationState::GetDebugMessage(), GetLegacySigOpCount(), CValidationState::GetRejectCode(), CValidationState::GetRejectReason(), GetSerializeSize(), CBlockHeader::hashMerkleRoot, CValidationState::Invalid(), MaxBlockSigOps(), MaxBlockSize(), PROTOCOL_VERSION, REJECT_INVALID, SER_NETWORK, strprintf, and CBlock::vtx.
Referenced by AcceptBlock(), ConnectBlock(), DeserializeAndCheckBlockTest(), PartiallyDownloadedBlock::FillBlock(), ProcessNewBlock(), TestBlockValidity(), and CVerifyDB::VerifyDB().
CheckBlockHeader()
bool CheckBlockHeader (const CBlockHeader & block, CValidationState & state, const Consensus::Params & consensusParams, bool fCheckPOW = true)
Context-independent validity checks.
Definition at line 3243 of file validation.cpp.
References CheckProofOfWork(), CValidationState::DoS(), error(), CBlockHeader::GetHash(), Consensus::Params::hashDevnetGenesisBlock, Consensus::Params::hashGenesisBlock, CBlockHeader::hashPrevBlock, base_blob< BITS >::IsNull(), CBlockHeader::nBits, and REJECT_INVALID.
Referenced by AcceptBlockHeader(), and CheckBlock().
CheckDiskSpace()
bool CheckDiskSpace (uint64_t nAdditionalBytes = 0)
Check whether enough disk space is available for an incoming block.
Definition at line 3781 of file validation.cpp.
References _(), GetDataDir(), and nMinDiskSpace.
Referenced by AppInitMain(), FindBlockPos(), FindUndoPos(), FlushStateToDisk(), CPrivateSendClientManager::ProcessMessage(), and CPrivateSendClientSession::SendDenominate().
CheckFinalTx()
bool CheckFinalTx (const CTransaction & tx, int flags = -1)
Check if transaction will be final in the next block to be created.
Calls IsFinalTx() with current block height and appropriate block time.
See consensus/consensus.h for flag definitions.
Definition at line 254 of file validation.cpp.
References AssertLockHeld, chainActive, cs_main, flags, GetAdjustedTime(), CBlockIndex::GetMedianTimePast(), CChain::Height(), IsFinalTx(), LOCKTIME_MEDIAN_TIME_PAST, and CChain::Tip().
Referenced by AcceptToMemoryPoolWorker(), CWallet::AvailableCoins(), TransactionDesc::FormatTxStatus(), CWallet::GetAccountBalance(), getbalance(), getreceivedbyaccount(), getreceivedbyaddress(), CWalletTx::IsTrusted(), CTxLockRequest::IsValid(), ListReceived(), CTxMemPool::removeForReorg(), and TransactionRecord::updateStatus().
CheckInputs()
bool CheckInputs (const CTransaction & tx, CValidationState & state, const CCoinsViewCache & view, bool fScriptChecks, unsigned int flags, bool cacheStore, std::vector< CScriptCheck > * pvChecks = NULL)
Check whether all inputs of this transaction are valid (no double spends, scripts & sigs, amounts) This does not modify the UTXO set.
If pvChecks is not NULL, script checks are pushed onto it instead of being performed inline.
Definition at line 1435 of file validation.cpp.
References CCoinsViewCache::AccessCoin(), Consensus::CheckTxInputs(), CValidationState::DoS(), flags, CScriptCheck::GetScriptError(), GetSpendHeight(), CValidationState::Invalid(), CTransaction::IsCoinBase(), Coin::IsSpent(), CTxOut::nValue, Coin::out, REJECT_INVALID, REJECT_NONSTANDARD, ScriptErrorString(), CTxOut::scriptPubKey, STANDARD_NOT_MANDATORY_VERIFY_FLAGS, strprintf, CScriptCheck::swap(), and CTransaction::vin.
Referenced by AcceptToMemoryPoolWorker(), and ConnectBlock().
CheckSequenceLocks()
bool CheckSequenceLocks (const CTransaction & tx, int flags, LockPoints * lp = NULL, bool useExistingLockPoints = false)
Check if transaction will be BIP 68 final in the next block to be created.
Simulates calling SequenceLocks() with data from the tip of the current active chain. Optionally stores in LockPoints the resulting height and time calculated and the hash of the block needed for calculation or skips the calculation and uses the LockPoints passed in for evaluation. The LockPoints should not be considered valid if CheckSequenceLocks returns false.
See consensus/consensus.h for flag definitions.
Definition at line 387 of file validation.cpp.
References AssertLockHeld, CalculateSequenceLocks(), chainActive, CTxMemPool::cs, cs_main, error(), EvaluateSequenceLocks(), flags, CBlockIndex::GetAncestor(), CCoinsViewMemPool::GetCoin(), LockPoints::height, LockPoints::maxInputBlock, mempool, MEMPOOL_HEIGHT, Coin::nHeight, CBlockIndex::nHeight, pcoinsTip, CBlockIndex::pprev, CTxIn::prevout, LockPoints::time, CChain::Tip(), and CTransaction::vin.
Referenced by AcceptToMemoryPoolWorker(), and CTxMemPool::removeForReorg().
CheckTransaction()
bool CheckTransaction (const CTransaction & tx, CValidationState & state)
Transaction validation functions.
Context-independent validity checks
Definition at line 515 of file validation.cpp.
References CValidationState::DoS(), GetSerializeSize(), CTransaction::IsCoinBase(), MAX_LEGACY_BLOCK_SIZE, MAX_MONEY, MAX_TX_EXTRA_PAYLOAD, MoneyRange(), CTransaction::nType, PROTOCOL_VERSION, REJECT_INVALID, SER_NETWORK, TRANSACTION_COINBASE, TRANSACTION_QUORUM_COMMITMENT, CTransaction::vExtraPayload, CTransaction::vin, and CTransaction::vout.
Referenced by AcceptToMemoryPoolWorker(), CheckBlock(), and ReadKeyValue().
ComputeBlockVersion()
int32_t ComputeBlockVersion (const CBlockIndex * pindexPrev, const Consensus::Params & params, bool fCheckMasternodesUpgraded = false)
Determine what nVersion a new block should use.
Definition at line 1824 of file validation.cpp.
References BIP9DeploymentInfo::check_mn_protocol, cs_main, deterministicMNManager, DMN_PROTO_VERSION, CBlockIndex::GetBlockHash(), CMasternodePayments::GetBlockTxOuts(), CDeterministicMNManager::GetListForBlock(), CMasternodeMan::GetMasternodeInfo(), CDeterministicMNList::GetMNPayee(), CDeterministicMNManager::IsDeterministicMNsSporkActive(), LOCK, Consensus::MAX_VERSION_BITS_DEPLOYMENTS, mnodeman, mnpayments, CBlockIndex::nHeight, masternode_info_t::nProtocolVersion, THRESHOLD_LOCKED_IN, THRESHOLD_STARTED, VERSIONBITS_TOP_BITS, versionbitscache, VersionBitsDeploymentInfo, VersionBitsMask(), and VersionBitsState().
Referenced by WarningBitsConditionChecker::Condition(), BlockAssembler::CreateNewBlock(), and UpdateTip().
ContextualCheckBlock()
bool ContextualCheckBlock (const CBlock & block, CValidationState & state, const Consensus::Params & consensusParams, const CBlockIndex * pindexPrev)
Definition at line 3372 of file validation.cpp.
References Consensus::Params::BIP34Height, ContextualCheckTransaction(), Consensus::DEPLOYMENT_CSV, Consensus::DEPLOYMENT_DIP0003, Consensus::Params::DIP0001Height, CValidationState::DoS(), expect, CBlockHeader::GetBlockTime(), CChainParams::GetConsensus(), GetLegacySigOpCount(), CBlockIndex::GetMedianTimePast(), GetSerializeSize(), IsFinalTx(), LOCKTIME_MEDIAN_TIME_PAST, MaxBlockSigOps(), MaxBlockSize(), CBlockIndex::nHeight, Params(), PROTOCOL_VERSION, REJECT_INVALID, SER_NETWORK, THRESHOLD_ACTIVE, TRANSACTION_COINBASE, versionbitscache, VersionBitsState(), and CBlock::vtx.
Referenced by AcceptBlock(), and TestBlockValidity().
ContextualCheckBlockHeader()
bool ContextualCheckBlockHeader (const CBlockHeader & block, CValidationState & state, const Consensus::Params & consensusParams, const CBlockIndex * pindexPrev, int64_t nAdjustedTime)
Context-dependent validity checks.
By "context", we mean only the previous block headers, but not the UTXO set; UTXO-related validity checks are done in ConnectBlock().
Definition at line 3336 of file validation.cpp.
References Consensus::Params::BIP34Height, Consensus::Params::BIP65Height, Consensus::Params::BIP66Height, ConvertBitsToDouble(), CValidationState::DoS(), error(), CBlockHeader::GetBlockTime(), CBlockIndex::GetMedianTimePast(), GetNextWorkRequired(), CValidationState::Invalid(), CBaseChainParams::MAIN, CBlockHeader::nBits, CBlockIndex::nHeight, CBlockHeader::nVersion, Params(), REJECT_INVALID, REJECT_OBSOLETE, and strprintf.
Referenced by AcceptBlockHeader(), and TestBlockValidity().
ConvertBitsToDouble()
double ConvertBitsToDouble (unsigned int nBits)
Definition at line 1123 of file validation.cpp.
Referenced by ContextualCheckBlockHeader(), and GetBlockSubsidy().
DisconnectBlocks()
bool DisconnectBlocks (int blocks)
Functions for validating blocks and updating the block tree.
Reprocess a number of blocks to try and get on the correct chain again
Definition at line 2661 of file validation.cpp.
References cs_main, DisconnectTip(), CValidationState::IsValid(), LOCK, LogPrintf, and Params().
Referenced by ReprocessBlocks().
DumpMempool()
void DumpMempool ()
Dump the mempool to disk.
Definition at line 4571 of file validation.cpp.
References CLIENT_VERSION, CTxMemPool::cs, CAutoFile::fclose(), FileCommit(), CAutoFile::Get(), GetDataDir(), GetTimeMicros(), CTxMemPool::infoAll(), LOCK, LogPrintf, CTxMemPool::mapDeltas, mempool, MEMPOOL_DUMP_VERSION, RenameOver(), and SER_DISK.
Referenced by PrepareShutdown().
FindFilesToPrune()
void FindFilesToPrune (std::set< int > & setFilesToPrune, uint64_t nPruneAfterHeight)
Prune block and undo files (blk???.dat and undo???.dat) so that the disk space used is less than a user-defined target.
The user sets the target (in MB) on the command line or in config file. This will be run on startup and whenever new space is allocated in a block or undo file, staying below the target. Changing back to unpruned requires a reindex (which in this case means the blockchain must be re-downloaded.)
Pruning functions are called from FlushStateToDisk when the global fCheckForPruning flag has been set. Block and undo files are deleted in lock-step (when blk00003.dat is deleted, so is rev00003.dat.) Pruning cannot take place until the longest chain is at least a certain length (100000 on mainnet, 1000 on testnet, 1000 on regtest). Pruning will never delete a block within a defined distance (currently 288) from the active chain's tip. The block index is updated by unsetting HAVE_DATA and HAVE_UNDO for any blocks that were stored in the deleted files. A db flag records the fact that at least some block files have been pruned.
Parameters
[out] setFilesToPrune The set of file indices that can be unlinked will be returned
Definition at line 3734 of file validation.cpp.
References BLOCKFILE_CHUNK_SIZE, CalculateCurrentUsage(), chainActive, count, cs_main, LOCK2, LogPrint, MIN_BLOCKS_TO_KEEP, CBlockIndex::nHeight, nPruneTarget, PruneOneBlockFile(), CChain::Tip(), and UNDOFILE_CHUNK_SIZE.
Referenced by FlushStateToDisk().
FindForkInGlobalIndex()
CBlockIndex* FindForkInGlobalIndex (const CChain & chain, const CBlockLocator & locator)
Find the last common block between the parameter chain and a locator.
Definition at line 211 of file validation.cpp.
References CChain::Contains(), CChain::Genesis(), mapBlockIndex, and CBlockLocator::vHave.
Referenced by CWallet::CreateWalletFromFile(), and ProcessMessage().
FlushStateToDisk()
void FlushStateToDisk ()
Flush all state, indexes and buffers to disk.
Definition at line 2460 of file validation.cpp.
References FLUSH_STATE_ALWAYS, and FlushStateToDisk().
FormatStateMessage()
std::string FormatStateMessage (const CValidationState & state)
Convert CValidationState to a human-readable message for logging.
Definition at line 618 of file validation.cpp.
References CValidationState::GetDebugMessage(), CValidationState::GetRejectCode(), CValidationState::GetRejectReason(), and strprintf.
Referenced by AcceptBlock(), AcceptBlockHeader(), AcceptToMemoryPoolWorker(), ConnectBlock(), BlockAssembler::CreateNewBlock(), ProcessMessage(), ProcessNewBlock(), TestBlockValidity(), and CVerifyDB::VerifyDB().
GetAddressIndex()
bool GetAddressIndex (uint160 addressHash, int type, std::vector< std::pair< CAddressIndexKey, CAmount > > & addressIndex, int start = 0, int end = 0)
Definition at line 975 of file validation.cpp.
References error(), fAddressIndex, pblocktree, and CBlockTreeDB::ReadAddressIndex().
Referenced by getaddressbalance(), getaddressdeltas(), and getaddresstxids().
GetAddressUnspent()
bool GetAddressUnspent (uint160 addressHash, int type, std::vector< std::pair< CAddressUnspentKey, CAddressUnspentValue > > & unspentOutputs)
Definition at line 987 of file validation.cpp.
References error(), fAddressIndex, pblocktree, and CBlockTreeDB::ReadAddressUnspentIndex().
Referenced by getaddressutxos().
GetBlockFileInfo()
CBlockFileInfo* GetBlockFileInfo (size_t n)
Get block file info entry for one block file.
Definition at line 4486 of file validation.cpp.
Referenced by BOOST_FIXTURE_TEST_CASE().
GetBlockHash()
bool GetBlockHash (uint256 & hashRet, int nBlockHeight = -1)
Return true if hash can be found in chainActive at nBlockHeight height.
Fills hashRet with found hash, if no nBlockHeight is specified - chainActive.Height() is used.
Definition at line 1872 of file validation.cpp.
References chainActive, cs_main, CChain::Height(), LOCK, and CChain::Tip().
Referenced by CMasternodePayments::AddOrUpdatePaymentVote(), CMasternodeMan::GetMasternodeRank(), CMasternodeMan::GetMasternodeRanks(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), llmq::CQuorumBlockProcessor::GetQuorumBlockHash(), GetRequiredPaymentsStrings(), ProcessMessage(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), protx_list(), CMasternodePayments::RequestLowDataPaymentBlocks(), and CMasternodeMan::SendVerifyReply().
GetBlockPosFilename()
boost::filesystem::path GetBlockPosFilename (const CDiskBlockPos & pos, const char * prefix)
Translation to a filesystem path.
Definition at line 3823 of file validation.cpp.
References GetDataDir(), CDiskBlockPos::nFile, prefix, and strprintf.
Referenced by OpenDiskFile(), ThreadImport(), and UnlinkPrunedFiles().
GetBlockSubsidy()
CAmount GetBlockSubsidy (int nBits, int nHeight, const Consensus::Params & consensusParams, bool fSuperblockPartOnly = false)
Definition at line 1148 of file validation.cpp.
References COIN, ConvertBitsToDouble(), CBaseChainParams::MAIN, Consensus::Params::nBudgetPaymentsStartBlock, Consensus::Params::nHighSubsidyBlocks, Consensus::Params::nHighSubsidyFactor, Consensus::Params::nSubsidyHalvingInterval, and Params().
Referenced by ConnectBlock(), BlockAssembler::CreateNewBlock(), and CSuperblock::GetPaymentsLimit().
GetLegacySigOpCount()
unsigned int GetLegacySigOpCount (const CTransaction & tx)
Count ECDSA signature operations the old-fashioned (pre-0.6) way.
Returns
number of sigops this transaction's outputs will produce when spent
See also
CTransaction::FetchInputs
Definition at line 458 of file validation.cpp.
References CTransaction::vin, and CTransaction::vout.
Referenced by AcceptToMemoryPoolWorker(), CheckBlock(), ConnectBlock(), ContextualCheckBlock(), and BlockAssembler::CreateNewBlock().
GetMasternodePayment()
CAmount GetMasternodePayment (int nHeight, CAmount blockValue)
Definition at line 1199 of file validation.cpp.
References CChainParams::GetConsensus(), Consensus::Params::nMasternodePaymentsIncreaseBlock, Consensus::Params::nMasternodePaymentsIncreasePeriod, and Params().
Referenced by CMasternodePayments::GetBlockTxOuts(), CMasternodePayments::GetMasternodeTxOuts(), CMasternodeBlockPayees::IsTransactionValid(), and CMasternode::UpdateLastPaid().
GetP2SHSigOpCount()
unsigned int GetP2SHSigOpCount (const CTransaction & tx, const CCoinsViewCache & mapInputs)
Count ECDSA signature operations in pay-to-script-hash inputs.
Parameters
[in] mapInputs Map of previous transactions that have outputs we're spending
Returns
maximum number of sigops required to validate this transaction's inputs
See also
CTransaction::FetchInputs
Definition at line 472 of file validation.cpp.
References CCoinsViewCache::AccessCoin(), CScript::GetSigOpCount(), CTransaction::IsCoinBase(), Coin::IsSpent(), Coin::out, CTxOut::scriptPubKey, and CTransaction::vin.
Referenced by AcceptToMemoryPoolWorker(), and ConnectBlock().
GetSpendHeight()
int GetSpendHeight (const CCoinsViewCache & inputs)
Return the spend height, which is one more than the inputs.GetBestBlock().
While checking, GetBestBlock() refers to the parent block. (protected by cs_main) This is also true for mempool checks.
Definition at line 1382 of file validation.cpp.
References cs_main, CCoinsViewCache::GetBestBlock(), LOCK, mapBlockIndex, and CBlockIndex::nHeight.
Referenced by CTxMemPool::check(), and CheckInputs().
GetSpentIndex()
bool GetSpentIndex (CSpentIndexKey & key, CSpentIndexValue & value)
Definition at line 961 of file validation.cpp.
References fSpentIndex, CTxMemPool::getSpentIndex(), mempool, pblocktree, and CBlockTreeDB::ReadSpentIndex().
Referenced by getspentinfo(), and TxToJSON().
GetTimestampIndex()
bool GetTimestampIndex (const unsigned int & high, const unsigned int & low, std::vector< uint256 > & hashes)
Definition at line 950 of file validation.cpp.
References error(), fTimestampIndex, high, low, pblocktree, and CBlockTreeDB::ReadTimestampIndex().
Referenced by getblockhashes().
GetTransaction()
bool GetTransaction (const uint256 & hash, CTransactionRef & txOut, const Consensus::Params & consensusParams, uint256 & hashBlock, bool fAllowSlow)
Retrieve a transaction (from memory pool, or from disk, if possible)
Retrieve a transaction (from memory pool, or from disk, if possible)
Definition at line 1000 of file validation.cpp.
References AccessByTxid(), chainActive, CLIENT_VERSION, cs_main, error(), fTxIndex, CAutoFile::Get(), CTxMemPool::get(), CBlockIndex::GetBlockHash(), CBlockHeader::GetHash(), CAutoFile::IsNull(), Coin::IsSpent(), LOCK, mempool, Coin::nHeight, CDiskTxPos::nTxOffset, OpenBlockFile(), pblocktree, pcoinsTip, ReadBlockFromDisk(), CBlockTreeDB::ReadTxIndex(), SER_DISK, and CBlock::vtx.
Referenced by BuildDMNListEntry(), getrawtransaction(), gettxoutproof(), CGovernanceObject::IsCollateralValid(), CInstantSend::ResolveConflicts(), and rest_tx().
GetUTXOCoin()
bool GetUTXOCoin (const COutPoint & outpoint, Coin & coin)
Definition at line 489 of file validation.cpp.
References cs_main, CCoinsViewCache::GetCoin(), Coin::IsSpent(), LOCK, and pcoinsTip.
Referenced by CDeterministicMNManager::BuildNewListFromBlock(), CMasternode::Check(), CMasternode::CheckCollateral(), CheckProRegTx(), CheckProUpRegTx(), GetUTXOHeight(), CPrivateSend::IsCollateralValid(), CTxLockRequest::IsValid(), CTxLockVote::IsValid(), masternodelist(), CPrivateSendServer::ProcessMessage(), CInstantSend::ResolveConflicts(), and CDeterministicMN::ToJson().
GetUTXOConfirmations()
int GetUTXOConfirmations (const COutPoint & outpoint)
Definition at line 506 of file validation.cpp.
References chainActive, cs_main, GetUTXOHeight(), CChain::Height(), LOCK, and CChain::Tip().
Referenced by BuildDMNListEntry(), and CMasternodeMan::GetNextMasternodeInQueueForPayment().
GetUTXOHeight()
int GetUTXOHeight (const COutPoint & outpoint)
Definition at line 499 of file validation.cpp.
References GetUTXOCoin(), and Coin::nHeight.
Referenced by GetUTXOConfirmations(), and CInstantSend::Vote().
GetWarnings()
std::string GetWarnings (const std::string & strFor)
Format a string that describes several potential problems detected by the core.
strFor can have three values:
"rpc": get critical warnings, which should put the client in safe mode if non-empty
"statusbar": get all warnings
"gui": get all warnings, translated (where possible) for GUI This function only returns the highest priority warning of the set selected by strFor.
Definition at line 48 of file warnings.cpp.
Referenced by getinfo(), getmininginfo(), getnetworkinfo(), ClientModel::getStatusBarWarnings(), BitcoinCore::handleRunawayException(), main(), and OnRPCPreCommand().
GuessVerificationProgress()
double GuessVerificationProgress (const ChainTxData & data, CBlockIndex * pindex)
Guess verification progress (as a fraction between 0.0=genesis and 1.0=current tip).
Guess verification progress (as a fraction between 0.0=genesis and 1.0=current tip).
Definition at line 4619 of file validation.cpp.
References ChainTxData::dTxRate, CBlockIndex::GetBlockTime(), CBlockIndex::nChainTx, ChainTxData::nTime, and ChainTxData::nTxCount.
Referenced by getblockchaininfo(), ClientModel::getVerificationProgress(), LoadBlockIndexDB(), CWallet::ScanForWalletTransactions(), and UpdateTip().
InitBlockIndex()
bool InitBlockIndex (const CChainParams & chainparams)
Initialize a new block tree database + block data on disk.
Definition at line 4130 of file validation.cpp.
References AddGenesisBlock(), chainActive, cs_main, DEFAULT_ADDRESSINDEX, DEFAULT_SPENTINDEX, DEFAULT_TIMESTAMPINDEX, DEFAULT_TXINDEX, CBaseChainParams::DEVNET, CChainParams::DevNetGenesisBlock(), error(), fAddressIndex, FLUSH_STATE_ALWAYS, FlushStateToDisk(), fReindex, fSpentIndex, fTimestampIndex, fTxIndex, CChain::Genesis(), CChainParams::GenesisBlock(), GetBoolArg(), LOCK, LogPrintf, CChainParams::NetworkIDString(), pblocktree, ProcessNewBlock(), and CBlockTreeDB::WriteFlag().
Referenced by AppInitMain(), and ThreadImport().
InsertBlockIndex()
CBlockIndex* InsertBlockIndex (uint256 hash)
Create a new block index entry for a given block hash.
Definition at line 3828 of file validation.cpp.
References base_blob< BITS >::IsNull(), and mapBlockIndex.
Referenced by LoadBlockIndexDB().
InvalidateBlock()
bool InvalidateBlock (CValidationState & state, const CChainParams & chainparams, CBlockIndex * pindex)
Mark a block as invalid.
Definition at line 2991 of file validation.cpp.
References AssertLockHeld, BLOCK_FAILED_CHILD, BLOCK_FAILED_VALID, BLOCK_VALID_TRANSACTIONS, chainActive, CChain::Contains(), cs_main, DEFAULT_MAX_MEMPOOL_SIZE, DEFAULT_MEMPOOL_EXPIRY, DisconnectTip(), GetArg(), GetMainSignals(), InvalidChainFound(), IsInitialBlockDownload(), LimitMempoolSize(), mapBlockIndex, mempool, CBlockIndex::nHeight, CClientUIInterface::NotifyBlockTip, CBlockIndex::nStatus, pcoinsTip, pindexBestHeader, CBlockIndex::pprev, CTxMemPool::removeForReorg(), STANDARD_LOCKTIME_VERIFY_FLAGS, CChain::Tip(), uiInterface, and CMainSignals::UpdatedBlockTip.
Referenced by invalidateblock().
IsFinalTx()
bool IsFinalTx (const CTransaction & tx, int nBlockHeight, int64_t nBlockTime)
Check if transaction is final and can be included in a block with the specified height and time.
Consensus critical.
Definition at line 241 of file validation.cpp.
References LOCKTIME_THRESHOLD, CTransaction::nLockTime, CTxIn::SEQUENCE_FINAL, and CTransaction::vin.
Referenced by CheckFinalTx(), ContextualCheckBlock(), BlockAssembler::TestForBlock(), and BlockAssembler::TestPackageTransactions().
IsInitialBlockDownload()
bool IsInitialBlockDownload ()
Check whether we are doing an initial block download (synchronizing from disk or network)
Definition at line 1220 of file validation.cpp.
References chainActive, cs_main, fImporting(), fReindex, CBlockIndex::GetBlockTime(), CChainParams::GetConsensus(), GetTime(), LOCK, CBlockIndex::nChainWork, nMaxTipAge, Consensus::Params::nMinimumChainWork, Params(), CChain::Tip(), and UintToArith256().
Referenced by AcceptBlock(), ActivateBestChain(), PeerLogicValidation::BlockChecked(), CheckForkWarningConditions(), getblocktemplate(), ClientModel::inInitialBlockDownload(), CDSNotificationInterface::InitializeCurrentBlockTip(), InvalidateBlock(), IsCurrentForFeeEstimation(), NotifyHeaderTip(), ProcessMessage(), SendMessages(), and UpdateTip().
LoadBlockIndex()
bool LoadBlockIndex (const CChainParams & chainparams)
Load the block tree and coins database from disk.
Definition at line 4107 of file validation.cpp.
References fReindex, and LoadBlockIndexDB().
Referenced by AppInitMain().
LoadExternalBlockFile()
bool LoadExternalBlockFile (const CChainParams & chainparams, FILE * fileIn, CDiskBlockPos * dbp = NULL)
Import blocks from an external file.
Definition at line 4180 of file validation.cpp.
References AcceptBlock(), ActivateBestChain(), BLOCK_HAVE_DATA, CLIENT_VERSION, cs_main, CBufferedFile::eof(), CBufferedFile::FindByte(), FLATDATA, CChainParams::GetConsensus(), CBufferedFile::GetPos(), GetTimeMillis(), Consensus::Params::hashGenesisBlock, CValidationState::IsError(), LOCK, LogPrint, LogPrintf, mapBlockIndex, MaxBlockSize(), CMessageHeader::MESSAGE_START_SIZE, CChainParams::MessageStart(), NotifyHeaderTip(), CDiskBlockPos::nPos, ReadBlockFromDisk(), SER_DISK, CBufferedFile::SetLimit(), CBufferedFile::SetPos(), and base_blob< BITS >::ToString().
Referenced by ThreadImport().
LoadMempool()
bool LoadMempool ()
Load the mempool from disk.
Definition at line 4505 of file validation.cpp.
References AcceptToMemoryPoolWithTime(), CLIENT_VERSION, count, cs_main, DEFAULT_MEMPOOL_EXPIRY, GetArg(), GetDataDir(), GetTime(), CAutoFile::IsNull(), CValidationState::IsValid(), LOCK, LogPrintf, mempool, MEMPOOL_DUMP_VERSION, CTxMemPool::PrioritiseTransaction(), SER_DISK, and ShutdownRequested().
Referenced by ThreadImport().
OpenBlockFile()
FILE* OpenBlockFile (const CDiskBlockPos & pos, bool fReadOnly = false)
Open a block file (blk?????.dat)
Definition at line 3815 of file validation.cpp.
References OpenDiskFile().
Referenced by FindBlockPos(), FlushBlockFile(), GetTransaction(), LoadBlockIndexDB(), ReadBlockFromDisk(), ThreadImport(), and WriteBlockToDisk().
OpenUndoFile()
FILE* OpenUndoFile (const CDiskBlockPos & pos, bool fReadOnly = false)
Open an undo file (rev?????.dat)
Definition at line 3819 of file validation.cpp.
References OpenDiskFile().
Referenced by FindUndoPos(), and FlushBlockFile().
PreciousBlock()
bool PreciousBlock (CValidationState & state, const CChainParams & params, CBlockIndex * pindex)
Mark a block as precious and reorganize.
Definition at line 2962 of file validation.cpp.
References ActivateBestChain(), BLOCK_VALID_TRANSACTIONS, chainActive, cs_main, CBlockIndex::IsValid(), LOCK, CBlockIndex::nChainTx, CBlockIndex::nChainWork, CBlockIndex::nSequenceId, PruneBlockIndexCandidates(), and CChain::Tip().
Referenced by preciousblock().
ProcessNewBlock()
bool ProcessNewBlock (const CChainParams & chainparams, const std::shared_ptr< const CBlock > pblock, bool fForceProcessing, bool * fNewBlock)
Process an incoming block.
This only returns after the best known valid block is made active. Note that it does not, however, guarantee that the specific block passed to it has been checked for validity!
If you want to possibly get feedback on whether pblock is valid, you must install a CValidationInterface (see validationinterface.h) - this will have its BlockChecked method called whenever any block completes validation.
Note that we guarantee that either the proof-of-work is valid on pblock, or (and possibly also) BlockChecked will have been called.
Call without cs_main held.
Parameters
[in] pblock The block we want to process.
[in] fForceProcessing Process this block even if unrequested; used for non-network block sources and whitelisted peers.
[out] fNewBlock A boolean which is set to indicate if the block was first received via this call
Returns
True if state.IsValid()
Definition at line 3585 of file validation.cpp.
References AcceptBlock(), ActivateBestChain(), CMainSignals::BlockChecked, CheckBlock(), CheckBlockIndex(), cs_main, error(), FormatStateMessage(), CChainParams::GetConsensus(), GetMainSignals(), LOCK, LogPrintf, and NotifyHeaderTip().
Referenced by generateBlocks(), InitBlockIndex(), ProcessMessage(), and submitblock().
ProcessNewBlockHeaders()
bool ProcessNewBlockHeaders (const std::vector< CBlockHeader > & block, CValidationState & state, const CChainParams & chainparams, const CBlockIndex ** ppindex = NULL)
Process incoming block headers.
Call without cs_main held.
Parameters
[in] block The block headers themselves
[out] state This may be set to an Error state if any error occurred processing them
[in] chainparams The params for the chain we want to connect to
[out] ppindex If set, the pointer will be set to point to the last new block index object for the given headers
Definition at line 3487 of file validation.cpp.
References AcceptBlockHeader(), cs_main, LOCK, and NotifyHeaderTip().
Referenced by ProcessMessage().
PruneAndFlush()
void PruneAndFlush ()
Prune block files and flush state to disk.
Definition at line 2465 of file validation.cpp.
References FLUSH_STATE_NONE, and FlushStateToDisk().
Referenced by AppInitMain().
PruneBlockFilesManual()
void PruneBlockFilesManual (int nPruneUpToHeight)
Prune block files up to a given height.
Definition at line 3727 of file validation.cpp.
References FLUSH_STATE_NONE, and FlushStateToDisk().
Referenced by pruneblockchain().
PruneOneBlockFile()
void PruneOneBlockFile (const int fileNumber)
Mark one block file as pruned.
Definition at line 3662 of file validation.cpp.
References BLOCK_HAVE_DATA, BLOCK_HAVE_UNDO, mapBlockIndex, CBlockIndex::nDataPos, CBlockIndex::nFile, CBlockIndex::nStatus, CBlockIndex::nUndoPos, and CBlockIndex::pprev.
Referenced by BOOST_FIXTURE_TEST_CASE(), FindFilesToPrune(), and FindFilesToPruneManual().
ReadBlockFromDisk() [1/2]
bool ReadBlockFromDisk (CBlock & block, const CDiskBlockPos & pos, const Consensus::Params & consensusParams)
Definition at line 1089 of file validation.cpp.
References CheckProofOfWork(), CLIENT_VERSION, error(), CBlockHeader::GetHash(), CAutoFile::IsNull(), CBlockHeader::nBits, OpenBlockFile(), SER_DISK, CBlock::SetNull(), and CDiskBlockPos::ToString().
Referenced by BuildSimplifiedMNListDiff(), ConnectTip(), DisconnectTip(), getblock(), getspecialtxes(), GetTransaction(), gettxoutproof(), LoadExternalBlockFile(), CZMQPublishRawBlockNotifier::NotifyBlock(), ProcessGetData(), ProcessMessage(), ReadBlockFromDisk(), rest_block(), CWallet::ScanForWalletTransactions(), SendMessages(), CMasternode::UpdateLastPaid(), and CVerifyDB::VerifyDB().
ReadBlockFromDisk() [2/2]
bool ReadBlockFromDisk (CBlock & block, const CBlockIndex * pindex, const Consensus::Params & consensusParams)
Definition at line 1113 of file validation.cpp.
References error(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockPos(), CBlockHeader::GetHash(), ReadBlockFromDisk(), CDiskBlockPos::ToString(), and CBlockIndex::ToString().
ReprocessBlocks()
void ReprocessBlocks (int nBlocks)
Definition at line 2678 of file validation.cpp.
References ActivateBestChain(), cs_main, DisconnectBlocks(), GetTime(), LOCK, LogPrintf, mapBlockIndex, mapRejectedBlocks, Params(), and ResetBlockFailureFlags().
Referenced by CSporkManager::ExecuteSpork().
ResetBlockFailureFlags()
bool ResetBlockFailureFlags (CBlockIndex * pindex)
Remove invalidity status from a block and its descendants.
Definition at line 3041 of file validation.cpp.
References AssertLockHeld, BLOCK_FAILED_MASK, BLOCK_VALID_TRANSACTIONS, chainActive, cs_main, mapBlockIndex, CBlockIndex::nHeight, CBlockIndex::nStatus, CBlockIndex::pprev, and CChain::Tip().
Referenced by reconsiderblock(), and ReprocessBlocks().
SequenceLocks()
bool SequenceLocks (const CTransaction & tx, int flags, std::vector< int > * prevHeights, const CBlockIndex & block)
Check if transaction is final per BIP 68 sequence numbers and can be included in a block.
Consensus critical. Takes as input a list of heights at which tx's inputs (in order) confirmed.
Definition at line 364 of file validation.cpp.
References CalculateSequenceLocks(), EvaluateSequenceLocks(), and flags.
Referenced by ConnectBlock().
TestBlockValidity()
bool TestBlockValidity (CValidationState & state, const CChainParams & chainparams, const CBlock & block, CBlockIndex * pindexPrev, bool fCheckPOW = true, bool fCheckMerkleRoot = true)
Check a block is completely valid from start to finish (only works on top of our current best block, with cs_main held)
Definition at line 3618 of file validation.cpp.
References AssertLockHeld, CEvoDB::BeginTransaction(), chainActive, CheckBlock(), CheckIndexAgainstCheckpoint(), ConnectBlock(), ContextualCheckBlock(), ContextualCheckBlockHeader(), cs_main, error(), evoDb, fCheckpointsEnabled, FormatStateMessage(), GetAdjustedTime(), CChainParams::GetConsensus(), CBlockHeader::GetHash(), CValidationState::GetRejectReason(), CValidationState::IsValid(), CBlockIndex::nHeight, pcoinsTip, CBlockIndex::pprev, and CChain::Tip().
Referenced by BlockAssembler::CreateNewBlock(), and getblocktemplate().
TestLockPointValidity()
bool TestLockPointValidity (const LockPoints * lp)
Test whether the LockPoints height and time are still valid on the current chain.
Definition at line 369 of file validation.cpp.
References AssertLockHeld, chainActive, CChain::Contains(), cs_main, and LockPoints::maxInputBlock.
Referenced by CTxMemPool::removeForReorg().
ThreadScriptCheck()
void ThreadScriptCheck ()
Run an instance of the script checking thread.
Definition at line 1816 of file validation.cpp.
References RenameThread(), and scriptcheckqueue.
Referenced by AppInitMain().
UnlinkPrunedFiles()
void UnlinkPrunedFiles (const std::set< int > & setFilesToPrune)
Actually unlink the specified files.
Definition at line 3694 of file validation.cpp.
References GetBlockPosFilename(), and LogPrintf.
Referenced by BOOST_FIXTURE_TEST_CASE(), and FlushStateToDisk().
UnloadBlockIndex()
void UnloadBlockIndex ()
Unload database information.
Definition at line 4081 of file validation.cpp.
References chainActive, VersionBitsCache::Clear(), CTxMemPool::clear(), cs_main, fHavePruned, LOCK, mapBlockIndex, mempool, pindexBestHeader, CChain::SetTip(), VERSIONBITS_NUM_BITS, versionbitscache, and warningcache.
Referenced by AppInitMain().
UpdateCoins()
void UpdateCoins (const CTransaction & tx, CCoinsViewCache & inputs, int nHeight)
Apply the effects of this transaction on the UTXO set represented by view.
Definition at line 1368 of file validation.cpp.
References UpdateCoins().
VersionBitsTipState()
ThresholdState VersionBitsTipState (const Consensus::Params & params, Consensus::DeploymentPos pos)
Get the BIP9 state for a given deployment at the current tip.
Definition at line 4491 of file validation.cpp.
References AssertLockHeld, chainActive, cs_main, CChain::Tip(), versionbitscache, and VersionBitsState().
Referenced by BIP9SoftForkDesc().
VersionBitsTipStateSinceHeight()
int VersionBitsTipStateSinceHeight (const Consensus::Params & params, Consensus::DeploymentPos pos)
Get the block height at which the BIP9 deployment switched into the state for the block building on the current tip.
Definition at line 4497 of file validation.cpp.
References chainActive, cs_main, LOCK, CChain::Tip(), versionbitscache, and VersionBitsStateSinceHeight().
Referenced by BIP9SoftForkDesc().
WriteBlockToDisk()
bool WriteBlockToDisk (const CBlock & block, CDiskBlockPos & pos, const CMessageHeader::MessageStartChars & messageStart)
Functions for disk access for blocks.
Definition at line 1068 of file validation.cpp.
References CLIENT_VERSION, error(), fileout, FLATDATA, GetSerializeSize(), CDiskBlockPos::nPos, OpenBlockFile(), and SER_DISK.
Referenced by AcceptBlock(), and AddGenesisBlock().
Variable Documentation
AVG_ADDRESS_BROADCAST_INTERVAL
const unsigned int AVG_ADDRESS_BROADCAST_INTERVAL = 30 static
Average delay between peer address broadcasts in seconds.
Definition at line 113 of file validation.h.
Referenced by SendMessages().
AVG_LOCAL_ADDRESS_BROADCAST_INTERVAL
const unsigned int AVG_LOCAL_ADDRESS_BROADCAST_INTERVAL = 24 * 24 * 60 static
Average delay between local address broadcasts in seconds.
Definition at line 111 of file validation.h.
Referenced by SendMessages().
BLOCK_DOWNLOAD_TIMEOUT_BASE
const int64_t BLOCK_DOWNLOAD_TIMEOUT_BASE = 1000000 static
Block download timeout base, expressed in millionths of the block interval (i.e.
2.5 min)
Definition at line 123 of file validation.h.
Referenced by SendMessages().
BLOCK_DOWNLOAD_TIMEOUT_PER_PEER
const int64_t BLOCK_DOWNLOAD_TIMEOUT_PER_PEER = 500000 static
Additional block download timeout per parallel downloading peer (i.e.
1.25 min)
Definition at line 125 of file validation.h.
Referenced by SendMessages().
BLOCK_DOWNLOAD_WINDOW
const unsigned int BLOCK_DOWNLOAD_WINDOW = 1024 static
Size of the "block download window": how far ahead of our current height do we fetch? Larger windows tolerate larger download speed differences between peer, but increase the potential degree of disordering of blocks on disk (which make reindexing and in the future perhaps pruning harder).
We'll probably want to make this a per-peer adaptive value at some point.
Definition at line 103 of file validation.h.
BLOCK_STALLING_TIMEOUT
const unsigned int BLOCK_STALLING_TIMEOUT = 2 static
Timeout in seconds during which a peer must stall block download progress before being disconnected.
Definition at line 90 of file validation.h.
Referenced by SendMessages().
BLOCKFILE_CHUNK_SIZE
const unsigned int BLOCKFILE_CHUNK_SIZE = 0x1000000 static
The pre-allocation chunk size for blk?????.dat files (since 0.8)
Definition at line 79 of file validation.h.
Referenced by FindBlockPos(), and FindFilesToPrune().
chainActive
CChain chainActive
The currently-connected chain of blocks (protected by cs_main).
Definition at line 72 of file validation.cpp.
Referenced by AcceptBlock(), AcceptToMemoryPoolWorker(), ActivateBestChain(), ActivateBestChainStep(), AlreadyHave(), AppInitMain(), BIP9SoftForkDesc(), blockheaderToJSON(), blockToJSON(), BOOST_FIXTURE_TEST_CASE(), BuildSimplifiedMNListDiff(), CMasternode::Check(), CMasternodePing::CheckAndUpdate(), CheckBlockIndex(), CheckFinalTx(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), CMasternodeBroadcast::CheckOutpoint(), CheckSequenceLocks(), CMasternodePing::CMasternodePing(), ConnectTip(), llmq::CDummyDKG::CreateDummyCommitment(), llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::CreateFinalCommitment(), BlockAssembler::CreateNewBlock(), CWallet::CreateTransaction(), CWallet::CreateWalletFromFile(), DisconnectTip(), dumpwallet(), entryToJSON(), FindFilesToPrune(), FindFilesToPruneManual(), FindMostWorkChain(), FlushStateToDisk(), TransactionDesc::FormatTxStatus(), generateBlocks(), getbestblockhash(), getblockchaininfo(), getblockcount(), GetBlockHash(), getblockhash(), getblockheaders(), getblocktemplate(), CMasternodePayments::GetBlockTxOuts(), getchaintips(), CMerkleTx::GetDepthInMainChain(), GetDifficulty(), getgovernanceinfo(), getinfo(), CWallet::GetKeyBirthTimes(), ClientModel::getLastBlockDate(), getmininginfo(), CGovernanceManager::GetMinVoteTime(), GetNetworkHashPS(), GetNextMasternodeForPayment(), ClientModel::getNumBlocks(), GetRequiredPaymentsStrings(), GetTransaction(), gettxoutproof(), GetUTXOConfirmations(), ClientModel::getVerificationProgress(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), InitBlockIndex(), CDSNotificationInterface::InitializeCurrentBlockTip(), InvalidateBlock(), InvalidChainFound(), CGovernanceObject::IsCollateralValid(), IsCurrentForFeeEstimation(), IsInitialBlockDownload(), CTxLockRequest::IsValid(), listsinceblock(), LoadBlockIndexDB(), CWallet::MarkConflicted(), masternode_winners(), masternodelist(), ParseBlock(), WalletModel::pollBalanceChanged(), PreciousBlock(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), ProcessMessage(), CSporkManager::ProcessSpork(), protx_list(), pruneblockchain(), PruneBlockIndexCandidates(), ReceivedBlockTransactions(), CMasternodePayments::RequestLowDataPaymentBlocks(), ResetBlockFailureFlags(), rest_getutxos(), rest_headers(), CWallet::ScanForWalletTransactions(), SendMessages(), TransactionRecord::statusUpdateNeeded(), TestBlockValidity(), TestLockPointValidity(), ThreadImport(), TxToJSON(), UnloadBlockIndex(), llmq::CDummyDKG::UpdatedBlockTip(), CMasternode::UpdateLastPaid(), TransactionRecord::updateStatus(), UpdateTip(), CVerifyDB::VerifyDB(), verifytxoutproof(), VersionBitsTipState(), and VersionBitsTipStateSinceHeight().
COINBASE_FLAGS
CScript COINBASE_FLAGS
Constant stuff for coinbase transactions we create:
Definition at line 109 of file validation.cpp.
Referenced by getblocktemplate(), and IncrementExtraNonce().
cs_main
CCriticalSection cs_main
Global state.
Definition at line 69 of file validation.cpp.
Referenced by WalletModel::abandonTransaction(), CWallet::AbandonTransaction(), abandontransaction(), AcceptBlock(), AcceptBlockHeader(), AcceptToMemoryPoolWorker(), ActivateBestChain(), ActivateBestChainStep(), CGovernanceManager::AddGovernanceObject(), addmultisigaddress(), AppInitMain(), AutoBackupWallet(), CWallet::AutoLockMasternodeCollaterals(), CWallet::AvailableCoins(), backupwallet(), PeerLogicValidation::BlockChecked(), BOOST_FIXTURE_TEST_CASE(), BuildSimplifiedMNListDiff(), CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CMasternodeMan::Check(), CMasternode::Check(), CMasternodeMan::CheckAndRemove(), CMasternodePing::CheckAndUpdate(), CheckBlockIndex(), CMasternode::CheckCollateral(), CheckFinalTx(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), CMasternodeMan::CheckMasternode(), CGovernanceManager::CheckMasternodeOrphanObjects(), CGovernanceManager::CheckMasternodeOrphanVotes(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), CGovernanceManager::CheckPostponedObjects(), CheckSequenceLocks(), CMasternodePing::CMasternodePing(), CPrivateSendServer::CommitFinalTransaction(), CWallet::CommitTransaction(), ComputeBlockVersion(), ConnectBlock(), CWallet::ConvertList(), CWallet::CountInputsWithAmount(), CWallet::CreateCollateralTransaction(), CPrivateSendClientSession::CreateDenominated(), llmq::CDummyDKG::CreateDummyCommitment(), llmq::CDummyDKG::CreateDummyContribution(), llmq::CDummyDKG::CreateFinalCommitment(), BlockAssembler::CreateNewBlock(), CWallet::CreateTransaction(), decoderawtransaction(), TransactionTablePriv::describe(), DisconnectBlocks(), CPrivateSendClientSession::DoAutomaticDenominating(), dumpprivkey(), dumpwallet(), encryptwallet(), FindFilesToPrune(), FindFilesToPruneManual(), FlushStateToDisk(), TransactionDesc::FormatTxStatus(), CWallet::FundTransaction(), generateBlocks(), getaccount(), getaccountaddress(), getaddressesbyaccount(), CWallet::GetAllReserveKeys(), CWallet::GetAnonymizedBalance(), CWallet::GetAverageAnonymizedRounds(), getbalance(), CWallet::GetBalance(), getbestblockhash(), getblock(), getblockchaininfo(), getblockcount(), GetBlockHash(), getblockhash(), getblockheader(), getblockheaders(), getblocktemplate(), CMasternodePayments::GetBlockTxOuts(), getchaintips(), CWallet::GetCollateralTxDSIn(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), CWallet::GetDenominatedBalance(), CMerkleTx::GetDepthInMainChain(), getdifficulty(), getgovernanceinfo(), ClientModel::getHeaderTipHeight(), ClientModel::getHeaderTipTime(), CWallet::GetImmatureBalance(), CWallet::GetImmatureWatchOnlyBalance(), getinfo(), ClientModel::getLastBlockDate(), llmq::CQuorumBlockProcessor::GetMinableCommitment(), llmq::CQuorumBlockProcessor::GetMinableCommitmentTx(), getmininginfo(), CGovernanceManager::GetMinVoteTime(), getnetworkhashps(), getnetworkinfo(), getnewaddress(), GetNextMasternodeForPayment(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetNodeStateStats(), CWallet::GetNormalizedAnonymizedBalance(), ClientModel::getNumBlocks(), WalletModel::getOutputs(), llmq::CQuorumBlockProcessor::GetQuorumBlockHash(), getrawchangeaddress(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), GetRequiredPaymentsStrings(), getspecialtxes(), GetSpendHeight(), GetTransaction(), gettransaction(), TransactionTablePriv::getTxHex(), gettxout(), gettxoutproof(), getunconfirmedbalance(), CWallet::GetUnconfirmedBalance(), CWallet::GetUnconfirmedWatchOnlyBalance(), GetUTXOCoin(), GetUTXOConfirmations(), GetUTXOStats(), ClientModel::getVerificationProgress(), getwalletinfo(), CWallet::GetWatchOnlyBalance(), gobject_get(), gobject_submit(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), TransactionTablePriv::index(), CActiveDeterministicMasternodeManager::Init(), InitBlockIndex(), CDSNotificationInterface::InitializeCurrentBlockTip(), instantsendtoaddress(), InvalidateBlock(), invalidateblock(), CGovernanceObject::IsCollateralValid(), CPrivateSend::IsCollateralValid(), IsCurrentForFeeEstimation(), IsInitialBlockDownload(), WalletModel::isLockedCoin(), WalletModel::isSpent(), CMasternodePaymentVote::IsValid(), CTxLockRequest::IsValid(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), WalletModel::listCoins(), WalletModel::listLockedCoins(), listlockunspent(), ListObjects(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), LoadExternalBlockFile(), LoadMempool(), CWallet::LoadWallet(), WalletModel::lockCoin(), lockunspent(), CPrivateSendClientSession::MakeCollateralAmounts(), CWallet::MarkConflicted(), masternode_winners(), masternodelist(), movecmd(), PeerLogicValidation::NewPoWValidBlock(), CZMQPublishRawBlockNotifier::NotifyBlock(), NotifyHeaderTip(), ParseBlock(), WalletModel::pollBalanceChanged(), PreciousBlock(), preciousblock(), PrepareShutdown(), WalletModel::prepareTransaction(), prioritisetransaction(), llmq::CQuorumBlockProcessor::ProcessBlock(), CDeterministicMNManager::ProcessBlock(), llmq::CDummyDKG::ProcessDummyCommitment(), llmq::CDummyDKG::ProcessDummyContribution(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), CInstantSend::ProcessMessage(), llmq::CDummyDKG::ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), ProcessMessage(), ProcessMessages(), ProcessNewBlock(), ProcessNewBlockHeaders(), CInstantSend::ProcessNewTxLockVote(), CInstantSend::ProcessOrphanTxLockVote(), CInstantSend::ProcessOrphanTxLockVotes(), CSporkManager::ProcessSpork(), CInstantSend::ProcessTxLockRequest(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), protx_diff(), protx_list(), pruneblockchain(), CWallet::ReacceptWalletTransactions(), reconsiderblock(), PeerTablePriv::refreshPeers(), TransactionTablePriv::refreshWallet(), removeprunedfunds(), ReprocessBlocks(), CGovernanceManager::RequestGovernanceObjectVotes(), CMasternodePayments::RequestLowDataPaymentBlocks(), resendwallettransactions(), ResetBlockFailureFlags(), CInstantSend::ResolveConflicts(), rest_block(), rest_getutxos(), rest_headers(), CWallet::ScanForWalletTransactions(), CWallet::SelectCoinsGroupedByAddresses(), SendBlockTransactions(), WalletModel::sendCoins(), sendfrom(), sendmany(), SendMessages(), sendrawtransaction(), SendRejectsAndCheckIfBanned(), sendtoaddress(), CMasternodeMan::SendVerifyReply(), setaccount(), setmocktime(), settxfee(), signmessage(), signrawtransaction(), CMasternodePing::SimpleCheck(), CMasternodeBroadcast::SimpleCheck(), TransactionRecord::statusUpdateNeeded(), submitblock(), CPrivateSendClientSession::SubmitDenominate(), CMasternodeMan::SyncAll(), CGovernanceManager::SyncAll(), CGovernanceManager::SyncSingleObjAndItsVotes(), PeerLogicValidation::SyncTransaction(), CInstantSend::SyncTransaction(), CPrivateSend::SyncTransaction(), CWallet::SyncTransaction(), TestBlockValidity(), TestLockPointValidity(), ThreadImport(), TransactionDesc::toHTML(), WalletModel::transactionCanBeAbandoned(), CInstantSend::TryToFinalizeLockCandidate(), llmq::CQuorumBlockProcessor::UndoBlock(), UnloadBlockIndex(), WalletModel::unlockCoin(), CMasternodeBroadcast::Update(), CGovernanceManager::UpdateCachesAndClean(), CActiveDeterministicMasternodeManager::UpdatedBlockTip(), CMasternodeMan::UpdateLastPaid(), CMasternode::UpdateLastPaid(), CGovernanceObject::UpdateLocalValidity(), CInstantSend::UpdateLockedTransaction(), TransactionRecord::updateStatus(), TransactionTablePriv::updateWallet(), validateaddress(), verifychain(), CVerifyDB::VerifyDB(), verifymessage(), verifytxoutproof(), VersionBitsTipState(), VersionBitsTipStateSinceHeight(), CInstantSend::Vote(), walletlock(), walletpassphrase(), and walletpassphrasechange().
csBestBlock
CWaitableCriticalSection csBestBlock
Definition at line 74 of file validation.cpp.
Referenced by getblocktemplate().
cvBlockChange
CConditionVariable cvBlockChange
Definition at line 75 of file validation.cpp.
Referenced by getblocktemplate(), OnRPCStopped(), and UpdateTip().
DATABASE_FLUSH_INTERVAL
const unsigned int DATABASE_FLUSH_INTERVAL = 24 * 60 * 60 static
Time to wait (in seconds) between flushing chainstate to disk.
Definition at line 107 of file validation.h.
Referenced by FlushStateToDisk().
DATABASE_WRITE_INTERVAL
const unsigned int DATABASE_WRITE_INTERVAL = 60 * 60 static
Time to wait (in seconds) between writing blocks/block index to disk.
Definition at line 105 of file validation.h.
Referenced by FlushStateToDisk().
DEFAULT_ADDRESSINDEX
const bool DEFAULT_ADDRESSINDEX = false static
Definition at line 138 of file validation.h.
Referenced by HelpMessage(), InitBlockIndex(), and InitParameterInteraction().
DEFAULT_ALERTS
const bool DEFAULT_ALERTS = true static
Default for accepting alerts from the P2P network.
Definition at line 53 of file validation.h.
Referenced by AppInitParameterInteraction(), and HelpMessage().
DEFAULT_ANCESTOR_LIMIT
const unsigned int DEFAULT_ANCESTOR_LIMIT = 25 static
Default for -limitancestorcount, max number of in-mempool ancestors.
Definition at line 67 of file validation.h.
Referenced by AcceptToMemoryPoolWorker(), CWallet::CreateTransaction(), HelpMessage(), and CWallet::SelectCoins().
DEFAULT_ANCESTOR_SIZE_LIMIT
const unsigned int DEFAULT_ANCESTOR_SIZE_LIMIT = 101 static
Default for -limitancestorsize, maximum kilobytes of tx + all in-mempool ancestors.
Definition at line 69 of file validation.h.
Referenced by AcceptToMemoryPoolWorker(), CWallet::CreateTransaction(), and HelpMessage().
DEFAULT_BANSCORE_THRESHOLD
const unsigned int DEFAULT_BANSCORE_THRESHOLD = 100 static
Definition at line 141 of file validation.h.
Referenced by HelpMessage(), and Misbehaving().
DEFAULT_BYTES_PER_SIGOP
const unsigned int DEFAULT_BYTES_PER_SIGOP = 20 static
Definition at line 135 of file validation.h.
Referenced by HelpMessage().
DEFAULT_CHECKBLOCKS
const signed int DEFAULT_CHECKBLOCKS = 6 static
Definition at line 210 of file validation.h.
Referenced by AppInitMain(), HelpMessage(), and verifychain().
DEFAULT_CHECKLEVEL
const unsigned int DEFAULT_CHECKLEVEL = 3 static
Definition at line 211 of file validation.h.
Referenced by AppInitMain(), HelpMessage(), InitParameterInteraction(), and verifychain().
DEFAULT_CHECKPOINTS_ENABLED
const bool DEFAULT_CHECKPOINTS_ENABLED = true static
Definition at line 136 of file validation.h.
Referenced by AppInitParameterInteraction(), and HelpMessage().
DEFAULT_DESCENDANT_LIMIT
const unsigned int DEFAULT_DESCENDANT_LIMIT = 25 static
Default for -limitdescendantcount, max number of in-mempool descendants.
Definition at line 71 of file validation.h.
Referenced by AcceptToMemoryPoolWorker(), CWallet::CreateTransaction(), HelpMessage(), and CWallet::SelectCoins().
DEFAULT_DESCENDANT_SIZE_LIMIT
const unsigned int DEFAULT_DESCENDANT_SIZE_LIMIT = 101 static
Default for -limitdescendantsize, maximum kilobytes of in-mempool descendants.
Definition at line 73 of file validation.h.
Referenced by AcceptToMemoryPoolWorker(), AppInitParameterInteraction(), CWallet::CreateTransaction(), and HelpMessage().
DEFAULT_LIMITFREERELAY
const unsigned int DEFAULT_LIMITFREERELAY = 0 static
Definition at line 127 of file validation.h.
Referenced by AcceptToMemoryPoolWorker(), HelpMessage(), and CWallet::ParameterInteraction().
DEFAULT_MAX_TIP_AGE
const int64_t DEFAULT_MAX_TIP_AGE = 6 * 60 * 60 static
Definition at line 129 of file validation.h.
Referenced by AppInitParameterInteraction(), and HelpMessage().
DEFAULT_MEMPOOL_EXPIRY
const unsigned int DEFAULT_MEMPOOL_EXPIRY = 336 static
Default for -mempoolexpiry, expiration time for mempool transactions in hours.
Definition at line 75 of file validation.h.
Referenced by AcceptToMemoryPoolWorker(), ActivateBestChainStep(), HelpMessage(), InvalidateBlock(), and LoadMempool().
DEFAULT_MIN_RELAY_TX_FEE
const unsigned int DEFAULT_MIN_RELAY_TX_FEE = 1000 static
Default for -minrelaytxfee, minimum relay fee for transactions.
Definition at line 59 of file validation.h.
Referenced by HelpMessage().
DEFAULT_PEERBLOOMFILTERS
const bool DEFAULT_PEERBLOOMFILTERS = true static
Definition at line 149 of file validation.h.
Referenced by AppInitParameterInteraction(), and HelpMessage().
DEFAULT_PERMIT_BAREMULTISIG
const bool DEFAULT_PERMIT_BAREMULTISIG = true static
Default for -permitbaremultisig.
Definition at line 134 of file validation.h.
Referenced by AppInitParameterInteraction(), and HelpMessage().
DEFAULT_RELAYPRIORITY
const bool DEFAULT_RELAYPRIORITY = true static
Definition at line 128 of file validation.h.
Referenced by AcceptToMemoryPoolWorker(), and HelpMessage().
DEFAULT_SCRIPTCHECK_THREADS
const int DEFAULT_SCRIPTCHECK_THREADS = 0 static
-par default (number of script-checking threads, 0 = auto)
Definition at line 86 of file validation.h.
Referenced by AppInitParameterInteraction(), HelpMessage(), and OptionsModel::Init().
DEFAULT_SPENTINDEX
const bool DEFAULT_SPENTINDEX = false static
Definition at line 140 of file validation.h.
Referenced by HelpMessage(), InitBlockIndex(), and InitParameterInteraction().
DEFAULT_TIMESTAMPINDEX
const bool DEFAULT_TIMESTAMPINDEX = false static
Definition at line 139 of file validation.h.
Referenced by HelpMessage(), InitBlockIndex(), and InitParameterInteraction().
DEFAULT_TRANSACTION_MAXFEE
const CAmount DEFAULT_TRANSACTION_MAXFEE = 0.1 * COIN static
-maxtxfee default
Definition at line 61 of file validation.h.
Referenced by HelpMessage().
DEFAULT_TXINDEX
const bool DEFAULT_TXINDEX = true static
Definition at line 137 of file validation.h.
Referenced by AppInitMain(), AppInitParameterInteraction(), HelpMessage(), and InitBlockIndex().
DEFAULT_WHITELISTFORCERELAY
const bool DEFAULT_WHITELISTFORCERELAY = true static
Default for DEFAULT_WHITELISTFORCERELAY.
Definition at line 57 of file validation.h.
Referenced by HelpMessage(), InitParameterInteraction(), and ProcessMessage().
DEFAULT_WHITELISTRELAY
const bool DEFAULT_WHITELISTRELAY = true static
Default for DEFAULT_WHITELISTRELAY.
Definition at line 55 of file validation.h.
Referenced by HelpMessage(), and ProcessMessage().
fAlerts
bool fAlerts
Definition at line 92 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and ProcessMessage().
fCheckBlockIndex
bool fCheckBlockIndex
Definition at line 88 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and CheckBlockIndex().
fCheckpointsEnabled
bool fCheckpointsEnabled
Definition at line 89 of file validation.cpp.
Referenced by AcceptBlockHeader(), AppInitParameterInteraction(), and TestBlockValidity().
fDIP0001ActiveAtTip
std::atomic<bool> fDIP0001ActiveAtTip
Definition at line 95 of file validation.cpp.
Referenced by BlockAssembler::BlockAssembler(), getblocktemplate(), CConnman::OutboundTargetReached(), BlockAssembler::TestForBlock(), BlockAssembler::TestPackage(), and CDSNotificationInterface::UpdatedBlockTip().
fHavePruned
bool fHavePruned
Pruning-related variables and constants.
True if any block files have ever been pruned.
Definition at line 83 of file validation.cpp.
Referenced by AppInitMain(), CheckBlockIndex(), FlushStateToDisk(), getblock(), getspecialtxes(), LoadBlockIndexDB(), rest_block(), and UnloadBlockIndex().
fImporting
std::atomic_bool fImporting
Referenced by CImportingNow::CImportingNow(), ClientModel::getBlockSource(), CWallet::GetMasternodeOutpointAndKeys(), CWallet::GetOutpointAndKeysFromOutput(), masternodebroadcast(), ProcessMessage(), SendMessages(), and CImportingNow::~CImportingNow().
fIsBareMultisigStd
bool fIsBareMultisigStd
Definition at line 85 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and IsStandardTx().
fLargeWorkForkFound
bool fLargeWorkForkFound
Definition at line 15 of file warnings.cpp.
Referenced by GetfLargeWorkForkFound(), GetWarnings(), and SetfLargeWorkForkFound().
fLargeWorkInvalidChainFound
bool fLargeWorkInvalidChainFound
Definition at line 16 of file warnings.cpp.
Referenced by GetfLargeWorkInvalidChainFound(), GetWarnings(), and SetfLargeWorkInvalidChainFound().
fPruneMode
bool fPruneMode
True if we're running in -prune mode.
Definition at line 84 of file validation.cpp.
Referenced by AppInitMain(), AppInitParameterInteraction(), CWallet::CreateWalletFromFile(), FindBlockPos(), FindFilesToPruneManual(), FindUndoPos(), FlushStateToDisk(), getblockchaininfo(), importaddress(), importelectrumwallet(), importprivkey(), importpubkey(), importwallet(), ProcessMessage(), pruneblockchain(), and CVerifyDB::VerifyDB().
fReindex
bool fReindex
Definition at line 78 of file validation.cpp.
Referenced by AppInitMain(), FlushStateToDisk(), ClientModel::getBlockSource(), CWallet::GetMasternodeOutpointAndKeys(), CWallet::GetOutpointAndKeysFromOutput(), InitBlockIndex(), IsInitialBlockDownload(), LoadBlockIndex(), LoadBlockIndexDB(), masternodebroadcast(), ProcessMessage(), SendMessages(), and ThreadImport().
fRequireStandard
bool fRequireStandard
Definition at line 86 of file validation.cpp.
Referenced by AcceptToMemoryPoolWorker(), and AppInitParameterInteraction().
fTxIndex
bool fTxIndex
Definition at line 79 of file validation.cpp.
Referenced by AppInitMain(), ConnectBlock(), getrawtransaction(), GetTransaction(), InitBlockIndex(), and LoadBlockIndexDB().
hashAssumeValid
uint256 hashAssumeValid
Block hash whose ancestors we will assume to have valid scripts without checking them.
Definition at line 98 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and ConnectBlock().
HIGH_MAX_TX_FEE
const CAmount HIGH_MAX_TX_FEE = 100 * HIGH_TX_FEE_PER_KB static
-maxtxfee will warn if called with a higher fee than this amount (in duffs)
Definition at line 65 of file validation.h.
Referenced by CWallet::ParameterInteraction().
HIGH_TX_FEE_PER_KB
const CAmount HIGH_TX_FEE_PER_KB = 0.01 * COIN static
Discourage users to set fees higher than this amount (in duffs) per kB.
Definition at line 63 of file validation.h.
Referenced by CWallet::ParameterInteraction().
INVENTORY_BROADCAST_INTERVAL
const unsigned int INVENTORY_BROADCAST_INTERVAL = 5 static
Average delay between trickled inventory transmissions in seconds.
Blocks and whitelisted receivers bypass this, regular outbound peers get half this delay, Masternode outbound peers get quarter this delay.
Definition at line 117 of file validation.h.
Referenced by SendMessages().
INVENTORY_BROADCAST_MAX_PER_1MB_BLOCK
const unsigned int INVENTORY_BROADCAST_MAX_PER_1MB_BLOCK = 4 * 7 * INVENTORY_BROADCAST_INTERVAL static
Maximum number of inventory items to send per transmission.
Limits the impact of low-fee transaction floods. We have 4 times smaller block times in Dash, so we need to push 4 times more invs per 1MB.
Definition at line 121 of file validation.h.
Referenced by SendMessages().
mapBlockIndex
BlockMap mapBlockIndex
Definition at line 71 of file validation.cpp.
Referenced by AcceptBlockHeader(), AddToBlockIndex(), CWallet::AddToWallet(), AlreadyHave(), AppInitMain(), BuildSimplifiedMNListDiff(), CMasternodePing::CheckAndUpdate(), CheckBlockIndex(), llmq::CheckLLMQCommitment(), ConnectBlock(), FindForkInGlobalIndex(), getblock(), getblockheader(), getblockheaders(), getblocktemplate(), getchaintips(), CMerkleTx::GetDepthInMainChain(), CWallet::GetKeyBirthTimes(), Checkpoints::GetLastCheckpoint(), getspecialtxes(), GetSpendHeight(), gettxout(), gettxoutproof(), GetUTXOStats(), importprunedfunds(), InsertBlockIndex(), InvalidateBlock(), invalidateblock(), CGovernanceObject::IsCollateralValid(), listsinceblock(), LoadBlockIndexDB(), LoadExternalBlockFile(), CWallet::MarkConflicted(), preciousblock(), ProcessGetData(), llmq::CQuorumBlockProcessor::ProcessMessage(), ProcessMessage(), PruneOneBlockFile(), reconsiderblock(), ReprocessBlocks(), ResetBlockFailureFlags(), rest_block(), rest_headers(), SendMessages(), CMasternodePing::SimpleCheck(), submitblock(), TxToJSON(), UnloadBlockIndex(), TransactionRecord::updateStatus(), verifytxoutproof(), WalletTxToJSON(), and CMainCleanup::~CMainCleanup().
mapRejectedBlocks
std::map<uint256, int64_t> mapRejectedBlocks
Referenced by ConnectBlock(), and ReprocessBlocks().
MAX_BLOCKFILE_SIZE
const unsigned int MAX_BLOCKFILE_SIZE = 0x8000000 static
The maximum size of a blk?????.dat file (since 0.8)
Definition at line 77 of file validation.h.
Referenced by BOOST_FIXTURE_TEST_CASE(), and FindBlockPos().
MAX_BLOCKS_IN_TRANSIT_PER_PEER
const int MAX_BLOCKS_IN_TRANSIT_PER_PEER = 16 static
Number of blocks that can be requested at any given time from a single peer.
Definition at line 88 of file validation.h.
Referenced by ProcessMessage(), and SendMessages().
MAX_BLOCKS_TO_ANNOUNCE
const unsigned int MAX_BLOCKS_TO_ANNOUNCE = 8 static
Maximum number of headers to announce when relaying blocks with headers message.
Definition at line 144 of file validation.h.
Referenced by ProcessMessage(), SendMessages(), and PeerLogicValidation::UpdatedBlockTip().
MAX_BLOCKTXN_DEPTH
const int MAX_BLOCKTXN_DEPTH = 10 static
Maximum depth of blocks we're willing to respond to GETBLOCKTXN requests for.
Definition at line 98 of file validation.h.
Referenced by ProcessMessage().
MAX_CMPCTBLOCK_DEPTH
const int MAX_CMPCTBLOCK_DEPTH = 5 static
Maximum depth of blocks we're willing to serve as compact blocks to peers when requested.
For older blocks, a regular BLOCK response will be sent.
Definition at line 96 of file validation.h.
Referenced by ProcessGetData().
MAX_FEE_ESTIMATION_TIP_AGE
const int64_t MAX_FEE_ESTIMATION_TIP_AGE = 3 * 60 * 60 static
Maximum age of our tip in seconds for us to be considered current for fee estimation.
Definition at line 131 of file validation.h.
Referenced by IsCurrentForFeeEstimation().
MAX_HEADERS_RESULTS
const unsigned int MAX_HEADERS_RESULTS = 2000 static
Number of headers sent in one getheaders result.
We rely on the assumption that if a peer sends less than this number, we reached its tip. Changing this value is a protocol upgrade.
Definition at line 93 of file validation.h.
Referenced by getblockheaders(), and ProcessMessage().
MAX_REJECT_MESSAGE_LENGTH
const unsigned int MAX_REJECT_MESSAGE_LENGTH = 111 static
Maximum length of reject messages.
Definition at line 109 of file validation.h.
Referenced by PeerLogicValidation::BlockChecked(), and ProcessMessage().
MAX_SCRIPTCHECK_THREADS
const int MAX_SCRIPTCHECK_THREADS = 16 static
Maximum number of script-checking threads allowed.
Definition at line 84 of file validation.h.
Referenced by AppInitParameterInteraction(), HelpMessage(), and OptionsDialog::OptionsDialog().
MAX_UNCONNECTING_HEADERS
const int MAX_UNCONNECTING_HEADERS = 10 static
Maximum number of unconnecting headers announcements before DoS score.
Definition at line 147 of file validation.h.
Referenced by ProcessMessage().
maxTxFee
CAmount maxTxFee
Absolute maximum transaction fee (in duffs) used by wallet and mempool (rejects high fee in sendrawtransaction)
Definition at line 101 of file validation.cpp.
Referenced by CPrivateSendServer::ChargeFees(), CPrivateSendServer::ChargeRandomFees(), CPrivateSendServer::CommitFinalTransaction(), CWallet::CommitTransaction(), CWallet::GetMinimumFee(), CPrivateSend::IsCollateralValid(), CWallet::ParameterInteraction(), WalletModel::prepareTransaction(), SendCoinsDialog::processSendCoinsReturn(), CWallet::ReacceptWalletTransactions(), CWalletTx::RelayWalletTransaction(), CWallet::SelectCoinsMinConf(), and sendrawtransaction().
mempool
CTxMemPool mempool
Referenced by ActivateBestChain(), ActivateBestChainStep(), CheckSequenceLocks(), ConnectTip(), DisconnectTip(), DumpMempool(), FlushStateToDisk(), GetSpentIndex(), GetTransaction(), InvalidateBlock(), LoadMempool(), UnloadBlockIndex(), and UpdateTip().
MIN_BLOCKS_TO_KEEP
const unsigned int MIN_BLOCKS_TO_KEEP = 288 static
Block files containing a block-height within MIN_BLOCKS_TO_KEEP of chainActive.Tip() will not be pruned.
Definition at line 208 of file validation.h.
Referenced by AcceptBlock(), AppInitMain(), FindFilesToPrune(), FindFilesToPruneManual(), ProcessMessage(), and pruneblockchain().
MIN_DISK_SPACE_FOR_BLOCK_FILES
const uint64_t MIN_DISK_SPACE_FOR_BLOCK_FILES = 945 * 1024 * 1024 static
Definition at line 221 of file validation.h.
Referenced by AppInitParameterInteraction(), and HelpMessage().
minRelayTxFee
CFeeRate minRelayTxFee
A fee rate smaller than this is considered zero fee (for relaying, mining and transaction creation)
Definition at line 100 of file validation.cpp.
Referenced by AcceptToMemoryPoolWorker(), AppInitParameterInteraction(), CWallet::CreateTransaction(), CTxOut::GetDustThreshold(), getinfo(), getnetworkinfo(), CWallet::GetRequiredFee(), CTxOut::IsDust(), and CWallet::ParameterInteraction().
nBytesPerSigOp
unsigned int nBytesPerSigOp
Definition at line 87 of file validation.cpp.
Referenced by AcceptToMemoryPoolWorker(), and AppInitParameterInteraction().
nCoinCacheUsage
size_t nCoinCacheUsage
Definition at line 90 of file validation.cpp.
Referenced by AppInitMain(), FlushStateToDisk(), and CVerifyDB::VerifyDB().
nLastBlockSize
uint64_t nLastBlockSize
Definition at line 56 of file miner.cpp.
Referenced by BlockAssembler::CreateNewBlock(), and getmininginfo().
nLastBlockTx
uint64_t nLastBlockTx
Definition at line 55 of file miner.cpp.
Referenced by BlockAssembler::CreateNewBlock(), and getmininginfo().
nMaxTipAge
int64_t nMaxTipAge
If the tip is older than this (in seconds), the node is considered to be in initial block download.
Definition at line 93 of file validation.cpp.
Referenced by AppInitParameterInteraction(), IsInitialBlockDownload(), ProcessMessage(), and SendMessages().
nMinDiskSpace
const uint64_t nMinDiskSpace = 52428800 static
Minimum disk space required - used in CheckDiskSpace()
Definition at line 198 of file validation.h.
Referenced by CheckDiskSpace().
nPruneTarget
uint64_t nPruneTarget
Number of MiB of block files that we're trying to stay below.
Definition at line 91 of file validation.cpp.
Referenced by AppInitParameterInteraction(), and FindFilesToPrune().
nScriptCheckThreads
int nScriptCheckThreads
Definition at line 76 of file validation.cpp.
Referenced by AppInitMain(), AppInitParameterInteraction(), and ConnectBlock().
pblocktree
CBlockTreeDB* pblocktree
Global variable that points to the active block tree (protected by cs_main)
Definition at line 228 of file validation.cpp.
Referenced by AppInitMain(), ConnectBlock(), DisconnectBlock(), FlushStateToDisk(), GetAddressIndex(), GetAddressUnspent(), GetSpentIndex(), GetTimestampIndex(), GetTransaction(), InitBlockIndex(), LoadBlockIndexDB(), PrepareShutdown(), and ThreadImport().
pcoinsdbview
CCoinsViewDB* pcoinsdbview
Global variable that points to the coins database (protected by cs_main)
Definition at line 226 of file validation.cpp.
Referenced by AppInitMain(), gettxoutsetinfo(), and PrepareShutdown().
pcoinsTip
CCoinsViewCache* pcoinsTip
Global variable that points to the active CCoinsView (protected by cs_main)
Definition at line 227 of file validation.cpp.
Referenced by AcceptToMemoryPoolWithTime(), AcceptToMemoryPoolWorker(), ActivateBestChainStep(), AlreadyHave(), AppInitMain(), CheckSequenceLocks(), ConnectTip(), DisconnectTip(), FlushStateToDisk(), GetTransaction(), gettxout(), gettxoutproof(), GetUTXOCoin(), InvalidateBlock(), LimitMempoolSize(), LoadBlockIndexDB(), PrepareShutdown(), ProcessMessage(), rest_getutxos(), sendrawtransaction(), signrawtransaction(), TestBlockValidity(), TransactionDesc::toHTML(), UpdateTip(), verifychain(), and CVerifyDB::VerifyDB().
pindexBestHeader
CBlockIndex* pindexBestHeader
Best header we've seen so far (used for getheaders queries' starting points).
Definition at line 73 of file validation.cpp.
Referenced by AddToBlockIndex(), ConnectBlock(), getblockchaininfo(), ClientModel::getHeaderTipHeight(), ClientModel::getHeaderTipTime(), InvalidateBlock(), IsCurrentForFeeEstimation(), LoadBlockIndexDB(), CMasternodeSync::NotifyHeaderTip(), NotifyHeaderTip(), ProcessGetData(), ProcessMessage(), SendMessages(), UnloadBlockIndex(), and CMasternodeSync::UpdatedBlockTip().
REJECT_ALREADY_KNOWN
const unsigned int REJECT_ALREADY_KNOWN = 0x101 static
Transaction is already known (either in mempool or blockchain)
Definition at line 564 of file validation.h.
Referenced by AcceptToMemoryPoolWorker().
REJECT_CONFLICT
const unsigned int REJECT_CONFLICT = 0x102 static
Transaction conflicts with a transaction already known.
Definition at line 566 of file validation.h.
Referenced by AcceptToMemoryPoolWorker(), and CDeterministicMNManager::BuildNewListFromBlock().
REJECT_HIGHFEE
const unsigned int REJECT_HIGHFEE = 0x100 static
Too high fee.
Can not be triggered by P2P transactions
Definition at line 562 of file validation.h.
Referenced by AcceptToMemoryPoolWorker().
REJECT_INTERNAL
const unsigned int REJECT_INTERNAL = 0x100 static
Reject codes greater or equal to this can be returned by AcceptToMemPool for transactions, to signal internal conditions.
They cannot and should not be sent over the P2P network.
Definition at line 560 of file validation.h.
Referenced by PeerLogicValidation::BlockChecked(), and ProcessMessage().
strMessageMagic
const std::string strMessageMagic
Definition at line 111 of file validation.cpp.
Referenced by CSporkMessage::GetSignerKeyID(), SignVerifyMessageDialog::on_signMessageButton_SM_clicked(), SignVerifyMessageDialog::on_verifyMessageButton_VM_clicked(), CMessageSigner::SignMessage(), signmessage(), signmessagewithprivkey(), CMessageSigner::VerifyMessage(), and verifymessage().
UNDOFILE_CHUNK_SIZE
const unsigned int UNDOFILE_CHUNK_SIZE = 0x100000 static
The pre-allocation chunk size for rev?????.dat files (since 0.8)
Definition at line 81 of file validation.h.
Referenced by FindFilesToPrune(), and FindUndoPos().
versionbitscache
VersionBitsCache versionbitscache
Definition at line 1822 of file validation.cpp.
Referenced by CheckSpecialTx(), ComputeBlockVersion(), ConnectBlock(), ContextualCheckBlock(), ContextualCheckTransaction(), BlockAssembler::CreateNewBlock(), DisconnectBlock(), getblocktemplate(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), llmq::CQuorumBlockProcessor::ProcessBlock(), CDeterministicMNManager::ProcessBlock(), ProcessMessage(), ThreadImport(), UnloadBlockIndex(), CDSNotificationInterface::UpdatedBlockTip(), llmq::CDummyDKG::UpdatedBlockTip(), VersionBitsTipState(), and VersionBitsTipStateSinceHeight().
Released under the MIT license