Dash Core: src/wallet/test/wallet_tests.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
wallet_tests.cpp File Reference
#include "wallet/wallet.h"
#include <set>
#include <stdint.h>
#include <utility>
#include <vector>
#include "rpc/server.h"
#include "test/test_dash.h"
#include "validation.h"
#include "wallet/test/wallet_test_fixture.h"
#include <boost/foreach.hpp>
#include <boost/test/unit_test.hpp>
#include <univalue.h>
Macros
#define RUN_TESTS 100
#define RANDOM_REPEATS 5
Typedefs
typedef std::set< std::pair< const CWalletTx *, unsigned int > > CoinSet
Functions
UniValue importmulti (const JSONRPCRequest &request)
UniValue dumpwallet (const JSONRPCRequest &request)
UniValue importwallet (const JSONRPCRequest &request)
static void add_coin (const CAmount &nValue, int nAge=6 *24, bool fIsFromMe=false, int nInput=0)
static void empty_wallet (void)
static bool equal_sets (CoinSet a, CoinSet b)
BOOST_AUTO_TEST_CASE (coin_selection_tests)
BOOST_AUTO_TEST_CASE (ApproximateBestSubset)
BOOST_FIXTURE_TEST_CASE (rescan, TestChain100Setup)
BOOST_FIXTURE_TEST_CASE (importwallet_rescan, TestChain100Setup)
Variables
std::vector< std::unique_ptr< CWalletTx > > wtxn
static const CWallet wallet
static std::vector< COutput > vCoins
Macro Definition Documentation
RANDOM_REPEATS
#define RANDOM_REPEATS 5
Definition at line 30 of file wallet_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
RUN_TESTS
#define RUN_TESTS 100
Definition at line 26 of file wallet_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
Typedef Documentation
CoinSet
typedef std::set<std::pair<const CWalletTx*,unsigned int> > CoinSet
Definition at line 34 of file wallet_tests.cpp.
Function Documentation
add_coin()
static void add_coin (const CAmount & nValue, int nAge = 6*24, bool fIsFromMe = false, int nInput = 0) static
Definition at line 41 of file wallet_tests.cpp.
References MakeTransactionRef(), CMutableTransaction::nLockTime, vCoins, CMutableTransaction::vin, CMutableTransaction::vout, wallet, and wtxn.
Referenced by BOOST_AUTO_TEST_CASE().
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (coin_selection_tests)
Definition at line 76 of file wallet_tests.cpp.
References add_coin(), CENT, COIN, CWallet::cs_wallet, empty_wallet(), equal_sets(), LOCK, MIN_CHANGE, RANDOM_REPEATS, RUN_TESTS, CWallet::SelectCoinsMinConf(), vCoins, and wallet.
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (ApproximateBestSubset)
Definition at line 343 of file wallet_tests.cpp.
References add_coin(), COIN, CWallet::cs_wallet, empty_wallet(), LOCK, CWallet::SelectCoinsMinConf(), vCoins, and wallet.
BOOST_FIXTURE_TEST_CASE() [1/2]
BOOST_FIXTURE_TEST_CASE (rescan , TestChain100Setup)
Definition at line 364 of file wallet_tests.cpp.
References CWallet::AddKeyPubKey(), chainActive, UniValue::clear(), COIN, cs_main, CWallet::cs_wallet, GetBlockFileInfo(), CBlockIndex::GetBlockPos(), CBlockIndex::GetBlockTimeMax(), CWallet::GetImmatureBalance(), CKey::GetPubKey(), GetScriptForRawPubKey(), HexStr(), importmulti(), LOCK, CKey::MakeNewKey(), MAX_BLOCKFILE_SIZE, CDiskBlockPos::nFile, JSONRPCRequest::params, PruneOneBlockFile(), UniValue::push_back(), UniValue::pushKV(), pwalletMain, CWallet::ScanForWalletTransactions(), UniValue::setArray(), UniValue::setObject(), strprintf, CChain::Tip(), UnlinkPrunedFiles(), wallet, and UniValue::write().
BOOST_FIXTURE_TEST_CASE() [2/2]
BOOST_FIXTURE_TEST_CASE (importwallet_rescan , TestChain100Setup)
Definition at line 435 of file wallet_tests.cpp.
References CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, dumpwallet(), CBlockIndex::GetBlockTimeMax(), GetScriptForRawPubKey(), CWallet::GetWalletTx(), importwallet(), LOCK, CWallet::mapKeyMetadata, CWallet::mapWallet, JSONRPCRequest::params, UniValue::push_back(), pwalletMain, UniValue::setArray(), SetMockTime(), CChain::Tip(), and wallet.
dumpwallet()
UniValue dumpwallet (const JSONRPCRequest & request)
Definition at line 727 of file rpcdump.cpp.
References _(), chainActive, CLIENT_BUILD, CHDChain::CountAccounts(), cs_main, CWallet::cs_wallet, EncodeDumpString(), EncodeDumpTime(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, UniValue::get_str(), CHDChain::GetAccount(), CWallet::GetAllReserveKeys(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockTime(), CWallet::GetDecryptedHDChain(), CCryptoKeyStore::GetHDChain(), CWallet::GetKey(), CWallet::GetKeyBirthTimes(), CHDChain::GetMnemonic(), CHDChain::GetSeed(), GetTime(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, CWallet::mapHdPubKeys, CExtKey::Neuter(), CHDAccount::nExternalChainCounter, CHDAccount::nInternalChainCounter, NullUniValue, Pair(), JSONRPCRequest::params, UniValue::push_back(), pwalletMain, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, CBitcoinExtKeyBase< K, Size, Type >::SetKey(), CExtKey::SetMaster(), UniValue::size(), strprintf, CChain::Tip(), base_blob< BITS >::ToString(), CBase58Data::ToString(), and UniValue::VOBJ.
Referenced by BOOST_FIXTURE_TEST_CASE().
empty_wallet()
static void empty_wallet (void) static
Definition at line 64 of file wallet_tests.cpp.
References vCoins, and wtxn.
Referenced by BOOST_AUTO_TEST_CASE().
equal_sets()
static bool equal_sets (CoinSet a, CoinSet b) static
Definition at line 70 of file wallet_tests.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
importmulti()
UniValue importmulti (const JSONRPCRequest & request)
Definition at line 1186 of file rpcdump.cpp.
References chainActive, UniValue::clear(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), UniValue::exists(), JSONRPCRequest::fHelp, CChain::FindEarliestAtLeast(), CChain::Genesis(), UniValue::get_bool(), CBlockIndex::GetBlockTime(), CBlockIndex::GetBlockTimeMax(), GetImportTimestamp(), CBlockIndex::GetMedianTimePast(), UniValue::getValues(), HelpExampleCli(), JSONRPCError(), LOCK2, CBlockIndex::nHeight, NullUniValue, JSONRPCRequest::params, ProcessImport(), UniValue::push_back(), UniValue::pushKV(), pwalletMain, CWallet::ReacceptWalletTransactions(), RPC_MISC_ERROR, RPCTypeCheck(), CWallet::ScanForWalletTransactions(), UniValue::setArray(), UniValue::size(), strprintf, CChain::Tip(), UniValue::VARR, and UniValue::VOBJ.
Referenced by BOOST_FIXTURE_TEST_CASE().
importwallet()
UniValue importwallet (const JSONRPCRequest & request)
Definition at line 410 of file rpcdump.cpp.
References _(), CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, DecodeDumpString(), DecodeDumpTime(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, CChain::FindEarliestAtLeast(), fPruneMode, UniValue::get_str(), CBlockIndex::GetBlockTime(), CPubKey::GetID(), CBitcoinSecret::GetKey(), CKey::GetPubKey(), CWallet::HaveKey(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, LogPrintf, CWallet::mapKeyMetadata, CWallet::MarkDirty(), CBlockIndex::nHeight, NullUniValue, JSONRPCRequest::params, pwalletMain, RPC_INVALID_PARAMETER, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), CWallet::SetAddressBook(), CBitcoinSecret::SetString(), CWallet::ShowProgress, UniValue::size(), CChain::Tip(), CWallet::UpdateTimeFirstKey(), and CKey::VerifyPubKey().
Referenced by BOOST_FIXTURE_TEST_CASE().
Variable Documentation
vCoins
std::vector<COutput> vCoins static
Definition at line 39 of file wallet_tests.cpp.
Referenced by add_coin(), addCoin(), CWallet::AvailableCoins(), BOOST_AUTO_TEST_CASE(), CoinSelection(), empty_wallet(), WalletModel::getBalance(), CWallet::GetCollateralTxDSIn(), CWallet::HasCollateralInputs(), WalletModel::listCoins(), CWallet::SelectCoins(), CWallet::SelectCoinsMinConf(), CWallet::SelectPrivateCoins(), and CWallet::SelectPSInOutPairsByDenominations().
wallet
const CWallet wallet static
Definition at line 38 of file wallet_tests.cpp.
Referenced by add_coin(), addCoin(), AutoBackupWallet(), BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), CoinSelection(), TransactionRecord::decomposeTransaction(), PaymentServer::fetchPaymentACK(), WalletModelTransaction::newPossibleKeyChange(), NotifyTransactionChanged(), RecentRequestsTableModel::RecentRequestsTableModel(), and TransactionDesc::toHTML().
wtxn
std::vector<std::unique_ptr<CWalletTx> > wtxn
Definition at line 32 of file wallet_tests.cpp.
Referenced by add_coin(), and empty_wallet().
Released under the MIT license