Dash Core: src/wallet/walletdb.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
walletdb.h File Reference
#include "amount.h"
#include "wallet/db.h"
#include "hdchain.h"
#include "key.h"
#include <list>
#include <stdint.h>
#include <string>
#include <utility>
#include <vector>
Classes
class CKeyMetadata
class CWalletDB
Access to the wallet database.
Enumerations
enum DBErrors {
DB_LOAD_OK, DB_CORRUPT, DB_NONCRITICAL_ERROR, DB_TOO_NEW,
DB_LOAD_FAIL, DB_NEED_REWRITE
}
Error statuses for the wallet database.
Functions
void ThreadFlushWalletDB ()
Variables
static const bool DEFAULT_FLUSHWALLET = true
Enumeration Type Documentation
DBErrors
enum DBErrors
Error statuses for the wallet database.
Enumerator
DB_LOAD_OK
DB_CORRUPT
DB_NONCRITICAL_ERROR
DB_TOO_NEW
DB_LOAD_FAIL
DB_NEED_REWRITE
Definition at line 34 of file walletdb.h.
Function Documentation
ThreadFlushWalletDB()
void ThreadFlushWalletDB ()
Definition at line 815 of file walletdb.cpp.
References bitdb, CDBEnv::CheckpointLSN(), CDBEnv::CloseDb(), CDBEnv::cs_db, DEFAULT_FLUSHWALLET, GetBoolArg(), GetTime(), GetTimeMillis(), CWalletDB::GetUpdateCounter(), LogPrint, CDBEnv::mapFileUseCount, MilliSleep(), pwalletMain, RenameThread(), CWallet::strWalletFile, and TRY_LOCK.
Referenced by CWallet::postInitProcess().
Variable Documentation
DEFAULT_FLUSHWALLET
const bool DEFAULT_FLUSHWALLET = true static
Definition at line 20 of file walletdb.h.
Referenced by CWallet::GetWalletHelpString(), and ThreadFlushWalletDB().
Released under the MIT license