Dash Core: src/wallet/walletdb.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
walletdb.cpp File Reference
#include "wallet/walletdb.h"
#include "base58.h"
#include "consensus/validation.h"
#include "validation.h"
#include "protocol.h"
#include "serialize.h"
#include "sync.h"
#include "util.h"
#include "utiltime.h"
#include "wallet/wallet.h"
#include <atomic>
#include <boost/filesystem.hpp>
#include <boost/foreach.hpp>
#include <boost/thread.hpp>
Classes
class CWalletScanState
Functions
bool ReadKeyValue (CWallet *pwallet, CDataStream &ssKey, CDataStream &ssValue, CWalletScanState &wss, std::string &strType, std::string &strErr)
static bool IsKeyType (std::string strType)
void ThreadFlushWalletDB ()
Variables
static uint64_t nAccountingEntryNumber = 0
static std::atomic< unsigned int > nWalletDBUpdateCounter
Function Documentation
IsKeyType()
static bool IsKeyType (std::string strType) static
Definition at line 575 of file walletdb.cpp.
Referenced by CWalletDB::LoadWallet(), and CWalletDB::Recover().
ReadKeyValue()
bool ReadKeyValue (CWallet * pwallet, CDataStream & ssKey, CDataStream & ssValue, CWalletScanState & wss, std::string & strType, std::string & strErr)
Definition at line 280 of file walletdb.cpp.
References CheckTransaction(), CDataStream::empty(), CWalletScanState::fAnyUnordered, CWalletScanState::fIsEncrypted, CBitcoinAddress::Get(), CPubKey::GetID(), Hash(), base_blob< BITS >::IsNull(), CValidationState::IsValid(), CKey::Load(), CWallet::LoadCryptedKey(), CWallet::LoadCScript(), CWallet::LoadDestData(), CWallet::LoadHDPubKey(), CWallet::LoadKey(), CWallet::LoadKeyMetadata(), CWallet::LoadKeyPool(), CWallet::LoadToWallet(), CWallet::LoadWatchOnly(), CWallet::mapAddressBook, CWallet::mapMasterKeys, nAccountingEntryNumber, CWalletScanState::nCKeys, CWalletScanState::nFileVersion, CWalletScanState::nKeyMeta, CWalletScanState::nKeys, CWallet::nMasterKeyMaxID, CWallet::nOrderPosNext, CWalletScanState::nWatchKeys, CWallet::SetCryptedHDChain(), CWallet::SetHDChain(), strprintf, CWallet::vchDefaultKey, CWalletKey::vchPrivKey, and CWalletScanState::vWalletUpgrade.
Referenced by CWalletDB::LoadWallet(), and CWalletDB::Recover().
ThreadFlushWalletDB()
void ThreadFlushWalletDB ()
Definition at line 815 of file walletdb.cpp.
References bitdb, CDBEnv::CheckpointLSN(), CDBEnv::CloseDb(), CDBEnv::cs_db, DEFAULT_FLUSHWALLET, GetBoolArg(), GetTime(), GetTimeMillis(), CWalletDB::GetUpdateCounter(), LogPrint, CDBEnv::mapFileUseCount, MilliSleep(), pwalletMain, RenameThread(), CWallet::strWalletFile, and TRY_LOCK.
Referenced by CWallet::postInitProcess().
Variable Documentation
nAccountingEntryNumber
uint64_t nAccountingEntryNumber = 0 static
Definition at line 25 of file walletdb.cpp.
Referenced by ReadKeyValue(), and CWalletDB::WriteAccountingEntry_Backend().
nWalletDBUpdateCounter
std::atomic<unsigned int> nWalletDBUpdateCounter static
Definition at line 27 of file walletdb.cpp.
Referenced by CWalletDB::EraseDestData(), CWalletDB::EraseName(), CWalletDB::ErasePool(), CWalletDB::ErasePurpose(), CWalletDB::EraseTx(), CWalletDB::EraseWatchOnly(), CWalletDB::GetUpdateCounter(), CWalletDB::IncrementUpdateCounter(), CWalletDB::WriteBestBlock(), CWalletDB::WriteCryptedHDChain(), CWalletDB::WriteCryptedKey(), CWalletDB::WriteCScript(), CWalletDB::WriteDefaultKey(), CWalletDB::WriteDestData(), CWalletDB::WriteHDChain(), CWalletDB::WriteHDPubKey(), CWalletDB::WriteKey(), CWalletDB::WriteMasterKey(), CWalletDB::WriteName(), CWalletDB::WriteOrderPosNext(), CWalletDB::WritePool(), CWalletDB::WritePurpose(), CWalletDB::WriteTx(), and CWalletDB::WriteWatchOnly().
Released under the MIT license