Dash Core: src/warnings.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.13.1.0)
warnings.h File Reference
#include <stdlib.h>
#include <string>
Functions
void SetMiscWarning (const std::string &strWarning)
void SetfLargeWorkForkFound (bool flag)
bool GetfLargeWorkForkFound ()
void SetfLargeWorkInvalidChainFound (bool flag)
bool GetfLargeWorkInvalidChainFound ()
std::string GetWarnings (const std::string &strFor)
Format a string that describes several potential problems detected by the core.
Variables
static const bool DEFAULT_TESTSAFEMODE = false
Function Documentation
GetfLargeWorkForkFound()
bool GetfLargeWorkForkFound ()
Definition at line 30 of file warnings.cpp.
References cs_warnings, fLargeWorkForkFound, and LOCK.
Referenced by CheckForkWarningConditions(), CInstantSend::GetTransactionLockSignatures(), and CInstantSend::IsLockedInstantSendTransaction().
GetfLargeWorkInvalidChainFound()
bool GetfLargeWorkInvalidChainFound ()
Definition at line 42 of file warnings.cpp.
References cs_warnings, fLargeWorkInvalidChainFound, and LOCK.
Referenced by CInstantSend::GetTransactionLockSignatures(), and CInstantSend::IsLockedInstantSendTransaction().
GetWarnings()
std::string GetWarnings (const std::string & strFor)
Format a string that describes several potential problems detected by the core.
strFor can have three values:
"rpc": get critical warnings, which should put the client in safe mode if non-empty
"statusbar": get all warnings
"gui": get all warnings, translated (where possible) for GUI This function only returns the highest priority warning of the set selected by strFor.
Definition at line 48 of file warnings.cpp.
References _(), CAlert::AppliesToMe(), CLIENT_VERSION_IS_RELEASE, cs_mapAlerts, cs_warnings, DEFAULT_TESTSAFEMODE, fLargeWorkForkFound, fLargeWorkInvalidChainFound, GetBoolArg(), LOCK, mapAlerts, CUnsignedAlert::nPriority, strMiscWarning, and CUnsignedAlert::strStatusBar.
SetfLargeWorkForkFound()
void SetfLargeWorkForkFound (bool flag)
Definition at line 24 of file warnings.cpp.
References cs_warnings, fLargeWorkForkFound, and LOCK.
Referenced by CheckForkWarningConditions().
SetfLargeWorkInvalidChainFound()
void SetfLargeWorkInvalidChainFound (bool flag)
Definition at line 36 of file warnings.cpp.
References cs_warnings, fLargeWorkInvalidChainFound, and LOCK.
Referenced by CheckForkWarningConditions().
SetMiscWarning()
void SetMiscWarning (const std::string & strWarning)
Definition at line 18 of file warnings.cpp.
References cs_warnings, LOCK, and strMiscWarning.
Referenced by AddTimeData(), UpdateTip(), and CMasternodeMan::WarnMasternodeDaemonUpdates().
Variable Documentation
DEFAULT_TESTSAFEMODE
const bool DEFAULT_TESTSAFEMODE = false static
Definition at line 19 of file warnings.h.
Referenced by GetWarnings(), and HelpMessage().
Released under the MIT license